Bearsampp: TplAppMailhog Class Reference
TplAppMailhog Class Reference
Static Public Member Functions
static getActionChangeMailhogPort ()
static getActionEnableMailhog ($enable)
static getActionInstallMailhogService ()
static getActionRemoveMailhogService ()
static getActionSwitchMailhogVersion ($version)
static getMenuMailhog ()
static getMenuMailhogService ()
static getMenuMailhogVersions ()
static process ()
Data Fields
const ACTION_CHANGE_PORT = 'changeMailhogPort'
const ACTION_ENABLE = 'enableMailhog'
const ACTION_INSTALL_SERVICE = 'installMailhogService'
const ACTION_REMOVE_SERVICE = 'removeMailhogService'
const ACTION_SWITCH_VERSION = 'switchMailhogVersion'
const MENU = 'mailhog'
const MENU_SERVICE = 'mailhogService'
const MENU_VERSIONS = 'mailhogVersions'
Detailed Description
Definition at line 10 of file class.tpl.app.mailhog.php.
Member Function Documentation
getActionChangeMailhogPort()
static getActionChangeMailhogPort () static
Generates the action to change the Mailhog port.
This method creates the action string for changing the Mailhog port and includes a command to reload the application.
@global object $bearsamppBins Provides access to system binaries and their configurations.
Returns
string The generated action string for changing the Mailhog port.
Definition at line 242 of file class.tpl.app.mailhog.php.
    {
        global $bearsamppBins;
        return TplApp::getActionRun(Action::CHANGE_PORT, array($bearsamppBins->getMailhog()->getName())) . PHP_EOL .
            TplAppReload::getActionReload();
    }
References $bearsamppBins, Action\CHANGE_PORT, TplAppReload\getActionReload(), and TplApp\getActionRun().
getActionEnableMailhog()
static getActionEnableMailhog ($enable) static
Generates the action to enable or disable Mailhog.
This method creates the action string for enabling or disabling Mailhog and includes a command to reload the application.
@global object $bearsamppBins Provides access to system binaries and their configurations.
Parameters
int $enable The enable flag (1 to enable, 0 to disable).
Returns
string The generated action string for enabling or disabling Mailhog.
Definition at line 147 of file class.tpl.app.mailhog.php.
    {
        global $bearsamppBins;
        return TplApp::getActionRun(Action::ENABLE, array($bearsamppBins->getMailhog()->getName(), $enable)) . PHP_EOL .
            TplAppReload::getActionReload();
    }
References $bearsamppBins, Action\ENABLE, TplAppReload\getActionReload(), and TplApp\getActionRun().
getActionInstallMailhogService()
static getActionInstallMailhogService () static
Generates the action to install the Mailhog service.
This method creates the action string for installing the Mailhog service and includes a command to reload the application.
Returns
string The generated action string for installing the Mailhog service.
Definition at line 257 of file class.tpl.app.mailhog.php.
    {
        return TplApp::getActionRun(Action::SERVICE, array(BinMailhog::SERVICE_NAME, ActionService::INSTALL)) . PHP_EOL .
            TplAppReload::getActionReload();
    }
References TplAppReload\getActionReload(), TplApp\getActionRun(), ActionService\INSTALL, Action\SERVICE, and BinMailhog\SERVICE_NAME.
getActionRemoveMailhogService()
static getActionRemoveMailhogService () static
Generates the action to remove the Mailhog service.
This method creates the action string for removing the Mailhog service and includes a command to reload the application.
Returns
string The generated action string for removing the Mailhog service.
Definition at line 270 of file class.tpl.app.mailhog.php.
    {
        return TplApp::getActionRun(Action::SERVICE, array(BinMailhog::SERVICE_NAME, ActionService::REMOVE)) . PHP_EOL .
            TplAppReload::getActionReload();
    }
References TplAppReload\getActionReload(), TplApp\getActionRun(), ActionService\REMOVE, Action\SERVICE, and BinMailhog\SERVICE_NAME.
getActionSwitchMailhogVersion()
static getActionSwitchMailhogVersion ($version) static
Generates the action to switch the Mailhog version.
This method creates the action string for switching the Mailhog version and includes a command to reload the application.
@global object $bearsamppBins Provides access to system binaries and their configurations.
Parameters
string $version The version to switch to.
Returns
string The generated action string for switching the Mailhog version.
Definition at line 165 of file class.tpl.app.mailhog.php.
    {
        global $bearsamppBins;
        return TplApp::getActionRun(Action::SWITCH_VERSION, array($bearsamppBins->getMailhog()->getName(), $version)) . PHP_EOL .
            TplAppReload::getActionReload() . PHP_EOL;
    }
References $bearsamppBins, TplAppReload\getActionReload(), TplApp\getActionRun(), and Action\SWITCH_VERSION.
getMenuMailhog()
static getMenuMailhog () static
Generates the Mailhog menu.
This method creates the menu items and associated actions for Mailhog, including options for downloading, enabling, switching versions, managing the service, and viewing logs.
@global object $bearsamppRoot Provides access to the root path of the application. @global object $bearsamppConfig Provides access to the application configuration. @global object $bearsamppBins Provides access to system binaries and their configurations. @global object $bearsamppLang Provides language support for retrieving language-specific values.
Returns
string The generated Mailhog menu items and actions.
Definition at line 53 of file class.tpl.app.mailhog.php.
    {
        global $bearsamppRoot, $bearsamppConfig, $bearsamppBins, $bearsamppLang;
        $resultItems = $resultActions = '';
        $isEnabled = $bearsamppBins->getMailhog()->isEnable();
        // Download
        $resultItems .= TplAestan::getItemLink(
                $bearsamppLang->getValue(Lang::DOWNLOAD_MORE),
                Util::getWebsiteUrl('module/mailhog', '#releases'),
                false,
                TplAestan::GLYPH_BROWSER
            ) . PHP_EOL;
        // Enable
        $tplEnable     = TplApp::getActionMulti(
            self::ACTION_ENABLE, array($isEnabled ? Config::DISABLED : Config::ENABLED),
            array($bearsamppLang->getValue(Lang::MENU_ENABLE), $isEnabled ? TplAestan::GLYPH_CHECK : ''),
            false, get_called_class()
        );
        $resultItems   .= $tplEnable[TplApp::SECTION_CALL] . PHP_EOL;
        $resultActions .= $tplEnable[TplApp::SECTION_CONTENT] . PHP_EOL;
        if ($isEnabled) {
            $resultItems .= TplAestan::getItemSeparator() . PHP_EOL;
            // Versions
            $tplVersions   = TplApp::getMenu($bearsamppLang->getValue(Lang::VERSIONS), self::MENU_VERSIONS, get_called_class());
            $resultItems   .= $tplVersions[TplApp::SECTION_CALL] . PHP_EOL;
            $resultActions .= $tplVersions[TplApp::SECTION_CONTENT] . PHP_EOL;
            // Service
            $tplService    = TplApp::getMenu($bearsamppLang->getValue(Lang::SERVICE), self::MENU_SERVICE, get_called_class());
            $resultItems   .= $tplService[TplApp::SECTION_CALL] . PHP_EOL;
            $resultActions .= $tplService[TplApp::SECTION_CONTENT] . PHP_EOL;
            // Web page
            $resultItems .= TplAestan::getItemExe(
                    $bearsamppLang->getValue(Lang::MAILHOG),
                    $bearsamppConfig->getBrowser(),
                    TplAestan::GLYPH_WEB_PAGE,
                    $bearsamppRoot->getLocalUrl() . ':' . $bearsamppBins->getMailhog()->getUiPort()
                ) . PHP_EOL;
            // Log
            $resultItems .= TplAestan::getItemNotepad($bearsamppLang->getValue(Lang::MENU_LOGS), $bearsamppBins->getMailhog()->getLog()) . PHP_EOL;
        }
        return $resultItems . PHP_EOL . $resultActions;
    }
References $bearsamppBins, $bearsamppConfig, $bearsamppLang, $bearsamppRoot, Config\DISABLED, Lang\DOWNLOAD_MORE, Config\ENABLED, TplApp\getActionMulti(), TplAestan\getItemExe(), TplAestan\getItemLink(), TplAestan\getItemNotepad(), TplAestan\getItemSeparator(), TplApp\getMenu(), Util\getWebsiteUrl(), TplAestan\GLYPH_BROWSER, TplAestan\GLYPH_CHECK, TplAestan\GLYPH_WEB_PAGE, Lang\MAILHOG, Lang\MENU_ENABLE, Lang\MENU_LOGS, TplApp\SECTION_CALL, TplApp\SECTION_CONTENT, Lang\SERVICE, and Lang\VERSIONS.
getMenuMailhogService()
static getMenuMailhogService () static
Generates the Mailhog service menu.
This method creates the menu items and associated actions for managing the Mailhog service, including starting, stopping, restarting, changing ports, and installing or removing the service.
@global object $bearsamppRoot Provides access to the root path of the application. @global object $bearsamppLang Provides language support for retrieving language-specific values. @global object $bearsamppBins Provides access to system binaries and their configurations.
Returns
string The generated Mailhog service menu items and actions.
Definition at line 185 of file class.tpl.app.mailhog.php.
    {
        global $bearsamppRoot, $bearsamppLang, $bearsamppBins;
        $tplChangePort = TplApp::getActionMulti(
            self::ACTION_CHANGE_PORT, null,
            array($bearsamppLang->getValue(Lang::MENU_CHANGE_PORT), TplAestan::GLYPH_NETWORK),
            false, get_called_class()
        );
        $isInstalled = $bearsamppBins->getMailhog()->getService()->isInstalled();
        $result = TplAestan::getItemActionServiceStart($bearsamppBins->getMailhog()->getService()->getName()) . PHP_EOL .
            TplAestan::getItemActionServiceStop($bearsamppBins->getMailhog()->getService()->getName()) . PHP_EOL .
            TplAestan::getItemActionServiceRestart($bearsamppBins->getMailhog()->getService()->getName()) . PHP_EOL .
            TplAestan::getItemSeparator() . PHP_EOL .
            TplApp::getActionRun(
                Action::CHECK_PORT, array($bearsamppBins->getMailhog()->getName(), $bearsamppBins->getMailhog()->getSmtpPort()),
                array(sprintf($bearsamppLang->getValue(Lang::MENU_CHECK_PORT), $bearsamppBins->getMailhog()->getSmtpPort()), TplAestan::GLYPH_LIGHT)
            ) . PHP_EOL .
            $tplChangePort[TplApp::SECTION_CALL] . PHP_EOL .
            TplAestan::getItemNotepad($bearsamppLang->getValue(Lang::MENU_UPDATE_ENV_PATH), $bearsamppRoot->getRootPath() . '/nssmEnvPaths.dat') . PHP_EOL;
        if (!$isInstalled) {
            $tplInstallService = TplApp::getActionMulti(
                self::ACTION_INSTALL_SERVICE, null,
                array($bearsamppLang->getValue(Lang::MENU_INSTALL_SERVICE), TplAestan::GLYPH_SERVICE_INSTALL),
                $isInstalled, get_called_class()
            );
            $result .= $tplInstallService[TplApp::SECTION_CALL] . PHP_EOL . PHP_EOL .
                $tplInstallService[TplApp::SECTION_CONTENT] . PHP_EOL;
        } else {
            $tplRemoveService = TplApp::getActionMulti(
                self::ACTION_REMOVE_SERVICE, null,
                array($bearsamppLang->getValue(Lang::MENU_REMOVE_SERVICE), TplAestan::GLYPH_SERVICE_REMOVE),
                !$isInstalled, get_called_class()
            );
            $result .= $tplRemoveService[TplApp::SECTION_CALL] . PHP_EOL . PHP_EOL .
                $tplRemoveService[TplApp::SECTION_CONTENT] . PHP_EOL;
        }
        $result .= $tplChangePort[TplApp::SECTION_CONTENT] . PHP_EOL;
        return $result;
    }
References $bearsamppBins, $bearsamppLang, $bearsamppRoot, $result, Action\CHECK_PORT, TplApp\getActionMulti(), TplApp\getActionRun(), TplAestan\getItemActionServiceRestart(), TplAestan\getItemActionServiceStart(), TplAestan\getItemActionServiceStop(), TplAestan\getItemNotepad(), TplAestan\getItemSeparator(), TplAestan\GLYPH_LIGHT, TplAestan\GLYPH_NETWORK, TplAestan\GLYPH_SERVICE_INSTALL, TplAestan\GLYPH_SERVICE_REMOVE, Lang\MENU_CHANGE_PORT, Lang\MENU_CHECK_PORT, Lang\MENU_INSTALL_SERVICE, Lang\MENU_REMOVE_SERVICE, Lang\MENU_UPDATE_ENV_PATH, TplApp\SECTION_CALL, and TplApp\SECTION_CONTENT.
getMenuMailhogVersions()
static getMenuMailhogVersions () static
Generates the Mailhog versions menu.
This method creates the menu items and associated actions for switching between different versions of Mailhog.
@global object $bearsamppBins Provides access to system binaries and their configurations.
Returns
string The generated Mailhog versions menu items and actions.
Definition at line 114 of file class.tpl.app.mailhog.php.
    {
        global $bearsamppBins;
        $items   = '';
        $actions = '';
        foreach ($bearsamppBins->getMailhog()->getVersionList() as $version) {
            $tplSwitchMailhogVersion = TplApp::getActionMulti(
                self::ACTION_SWITCH_VERSION, array($version),
                array($version, $version == $bearsamppBins->getMailhog()->getVersion() ? TplAestan::GLYPH_CHECK : ''),
                false, get_called_class()
            );
            // Item
            $items .= $tplSwitchMailhogVersion[TplApp::SECTION_CALL] . PHP_EOL;
            // Action
            $actions .= PHP_EOL . $tplSwitchMailhogVersion[TplApp::SECTION_CONTENT];
        }
        return $items . $actions;
    }
References $bearsamppBins, TplApp\getActionMulti(), TplAestan\GLYPH_CHECK, TplApp\SECTION_CALL, and TplApp\SECTION_CONTENT.
process()
static process () static
Processes the Mailhog menu.
This method generates the menu for enabling or disabling Mailhog. It uses the global language object to retrieve the localized string for Mailhog.
@global object $bearsamppLang Provides language support for retrieving language-specific values. @global object $bearsamppBins Provides access to system binaries and their configurations.
Returns
array The generated menu for enabling or disabling Mailhog.
Definition at line 33 of file class.tpl.app.mailhog.php.
    {
        global $bearsamppLang, $bearsamppBins;
        return TplApp::getMenuEnable($bearsamppLang->getValue(Lang::MAILHOG), self::MENU, get_called_class(), $bearsamppBins->getMailhog()->isEnable());
    }
References $bearsamppBins, $bearsamppLang, TplApp\getMenuEnable(), and Lang\MAILHOG.
Referenced by TplApp\getSectionMenuLeft().
Field Documentation
ACTION_CHANGE_PORT
const ACTION_CHANGE_PORT = 'changeMailhogPort'
Definition at line 18 of file class.tpl.app.mailhog.php.
ACTION_ENABLE
const ACTION_ENABLE = 'enableMailhog'
Definition at line 16 of file class.tpl.app.mailhog.php.
ACTION_INSTALL_SERVICE
const ACTION_INSTALL_SERVICE = 'installMailhogService'
Definition at line 19 of file class.tpl.app.mailhog.php.
ACTION_REMOVE_SERVICE
const ACTION_REMOVE_SERVICE = 'removeMailhogService'
Definition at line 20 of file class.tpl.app.mailhog.php.
ACTION_SWITCH_VERSION
const ACTION_SWITCH_VERSION = 'switchMailhogVersion'
Definition at line 17 of file class.tpl.app.mailhog.php.
MENU
const MENU = 'mailhog'
Definition at line 12 of file class.tpl.app.mailhog.php.
MENU_SERVICE
const MENU_SERVICE = 'mailhogService'
Definition at line 14 of file class.tpl.app.mailhog.php.
MENU_VERSIONS
const MENU_VERSIONS = 'mailhogVersions'
Definition at line 13 of file class.tpl.app.mailhog.php.
The documentation for this class was generated from the following file:
E:/Bearsampp-development/sandbox/core/classes/tpls/app/class.tpl.app.mailhog.php