Bearsampp: Nssm Class Reference
Nssm Class Reference
Public Member Functions
__construct ($name)
create ()
delete ()
getBinPath ()
getDisplayName ()
getEnvironmentExtra ()
getError ()
getLatestError ()
getLatestStatus ()
getName ()
getParams ()
getStart ()
getStderr ()
getStdout ()
infos ()
isInstalled ()
isPaused ()
isPending ($status)
isRunning ()
isStopped ()
restart ()
setBinPath ($binPath)
setDisplayName ($displayName)
setEnvironmentExtra ($environmentExtra)
setName ($name)
setParams ($params)
setStart ($start)
setStderr ($stderr)
setStdout ($stdout)
start ()
status ($timeout=true)
stop ()
Data Fields
const INFO_APP_DIRECTORY = 'AppDirectory'
const INFO_APP_ENVIRONMENT_EXTRA = 'AppEnvironmentExtra'
const INFO_APP_PARAMETERS = 'AppParameters'
const INFO_APP_STDERR = 'AppStderr'
const INFO_APP_STDOUT = 'AppStdout'
const INFO_APPLICATION = 'Application'
const PENDING_TIMEOUT = 10
const SERVICE_AUTO_START = 'SERVICE_AUTO_START'
const SERVICE_DELAYED_START = 'SERVICE_DELAYED_START'
const SERVICE_DEMAND_START = 'SERVICE_DEMAND_START'
const SERVICE_DISABLED = 'SERVICE_DISABLED'
const SERVICE_INTERACTIVE_PROCESS = 'SERVICE_INTERACTIVE_PROCESS'
const SERVICE_WIN32_OWN_PROCESS = 'SERVICE_WIN32_OWN_PROCESS'
const SLEEP_TIME = 500000
const STATUS_CONTINUE_PENDING = 'SERVICE_CONTINUE_PENDING'
const STATUS_NA = '-1'
const STATUS_NOT_EXIST = 'SERVICE_NOT_EXIST'
const STATUS_PAUSE_PENDING = 'SERVICE_PAUSE_PENDING'
const STATUS_PAUSED = 'SERVICE_PAUSED'
const STATUS_RUNNING = 'SERVICE_RUNNING'
const STATUS_START_PENDING = 'SERVICE_START_PENDING'
const STATUS_STOP_PENDING = 'SERVICE_STOP_PENDING'
const STATUS_STOPPED = 'SERVICE_STOPPED'
Private Member Functions
exec ($args)
getServiceStatusDesc ($status)
writeLog ($log)
writeLogError ($log)
writeLogInfo ($log)
Private Attributes
$binPath
$displayName
$environmentExtra
$latestError
$latestStatus
$name
$params
$start
$stderr
$stdout
Detailed Description
Class Nssm
This class provides methods to manage Windows services using NSSM (Non-Sucking Service Manager). It includes functionalities to create, delete, start, stop, and retrieve the status of services. The class also logs operations and errors.
Definition at line 17 of file class.nssm.php.
Constructor & Destructor Documentation
__construct()
Nssm::__construct ($name)
Nssm constructor. Initializes the Nssm class and logs the initialization.
Parameters
string $name The name of the service.
Definition at line 68 of file class.nssm.php.
    {
        Util::logInitClass( $this );
        $this->name = $name;
    }
References $name, and Util\logInitClass().
Member Function Documentation
create()
Nssm::create ()
Creates a new service.
Returns
bool True if the service was created successfully, false otherwise.
Definition at line 183 of file class.nssm.php.
    {
        $this->writeLog( 'Create service' );
        $this->writeLog( '-> service: ' . $this->getName() );
        $this->writeLog( '-> display: ' . $this->getDisplayName() );
        $this->writeLog( '-> description: ' . $this->getDisplayName() );
        $this->writeLog( '-> path: ' . $this->getBinPath() );
        $this->writeLog( '-> params: ' . $this->getParams() );
        $this->writeLog( '-> stdout: ' . $this->getStdout() );
        $this->writeLog( '-> stderr: ' . $this->getStderr() );
        $this->writeLog( '-> environment extra: ' . $this->getEnvironmentExtra() );
        $this->writeLog( '-> start_type: ' . ($this->getStart() != null ? $this->getStart() : self::SERVICE_DEMAND_START) );
        // Install bin
        $exec = $this->exec( 'install ' . $this->getName() . ' "' . $this->getBinPath() . '"' );
        if ( $exec === false ) {
            return false;
        }
        // Params
        $exec = $this->exec( 'set ' . $this->getName() . ' AppParameters "' . $this->getParams() . '"' );
        if ( $exec === false ) {
            return false;
        }
        // DisplayName
        $exec = $this->exec( 'set ' . $this->getName() . ' DisplayName "' . $this->getDisplayName() . '"' );
        if ( $exec === false ) {
            return false;
        }
        // Description
        $exec = $this->exec( 'set ' . $this->getName() . ' Description "' . $this->getDisplayName() . '"' );
        if ( $exec === false ) {
            return false;
        }
        // No AppNoConsole to fix nssm problems with Windows 10 Creators update.
        $exec = $this->exec( 'set ' . $this->getName() . ' AppNoConsole "1"' );
        if ( $exec === false ) {
            return false;
        }
        // Start
        $exec = $this->exec( 'set ' . $this->getName() . ' Start "' . ($this->getStart() != null ? $this->getStart() : self::SERVICE_DEMAND_START) . '"' );
        if ( $exec === false ) {
            return false;
        }
        // Stdout
        $exec = $this->exec( 'set ' . $this->getName() . ' AppStdout "' . $this->getStdout() . '"' );
        if ( $exec === false ) {
            return false;
        }
        // Stderr
        $exec = $this->exec( 'set ' . $this->getName() . ' AppStderr "' . $this->getStderr() . '"' );
        if ( $exec === false ) {
            return false;
        }
        // Environment Extra
        $exec = $this->exec( 'set ' . $this->getName() . ' AppEnvironmentExtra ' . $this->getEnvironmentExtra() );
        if ( $exec === false ) {
            return false;
        }
        if ( !$this->isInstalled() ) {
            $this->latestError = null;
            return false;
        }
        return true;
    }
References exec(), getBinPath(), getDisplayName(), getEnvironmentExtra(), getName(), getParams(), getStart(), getStderr(), getStdout(), isInstalled(), SERVICE_DEMAND_START, and writeLog().
delete()
Nssm::delete ()
Deletes the service.
Returns
bool True if the service was deleted successfully, false otherwise.
Definition at line 264 of file class.nssm.php.
    {
        $this->stop();
        $this->writeLog( 'Delete service ' . $this->getName() );
        $exec = $this->exec( 'remove ' . $this->getName() . ' confirm' );
        if ( $exec === false ) {
            return false;
        }
        if ( $this->isInstalled() ) {
            $this->latestError = null;
            return false;
        }
        return true;
    }
References exec(), getName(), isInstalled(), stop(), and writeLog().
exec()
Nssm::exec ($args) private
Executes an NSSM command.
Parameters
string $args The arguments for the NSSM command.
Returns
array|false The result of the execution, or false on failure.
Definition at line 114 of file class.nssm.php.
    {
        global $bearsamppCore;
        $command = '"' . $bearsamppCore->getNssmExe() . '" ' . $args;
        $this->writeLogInfo( 'Cmd: ' . $command );
        $result = Batch::exec( 'nssm', $command, 10 );
        if ( is_array( $result ) ) {
            $rebuildResult = array();
            foreach ( $result as $row ) {
                $row = trim( $row );
                if ( !empty( $row ) ) {
                    $rebuildResult[] = preg_replace( '/[\x00-\x1F\x80-\xFF]/', '', $row );
                }
            }
            $result = $rebuildResult;
            if ( count( $result ) > 1 ) {
                $this->latestError = implode( ' ; ', $result );
            }
            return $result;
        }
        return false;
    }
References $bearsamppCore, $result, Batch\exec(), and writeLogInfo().
Referenced by create(), delete(), start(), status(), and stop().
getBinPath()
Nssm::getBinPath ()
Gets the binary path of the service.
Returns
string The binary path of the service.
Definition at line 538 of file class.nssm.php.
    {
        return $this->binPath;
    }
References $binPath.
Referenced by create().
getDisplayName()
Nssm::getDisplayName ()
Gets the display name of the service.
Returns
string The display name of the service.
Definition at line 518 of file class.nssm.php.
    {
        return $this->displayName;
    }
References $displayName.
Referenced by create().
getEnvironmentExtra()
Nssm::getEnvironmentExtra ()
Gets the additional environment variables for the service.
Returns
string The additional environment variables.
Definition at line 638 of file class.nssm.php.
    {
        return $this->environmentExtra;
    }
References $environmentExtra.
Referenced by create().
getError()
Nssm::getError ()
Retrieves the error message or status description of the service.
Returns
string|null The error message or status description, or null if no error or status is available.
Definition at line 678 of file class.nssm.php.
    {
        global $bearsamppLang;
        if ( !empty( $this->latestError ) ) {
            return $bearsamppLang->getValue( Lang::ERROR ) . ' ' . $this->latestError;
        }
        elseif ( $this->latestStatus != self::STATUS_NA ) {
            return $bearsamppLang->getValue( Lang::STATUS ) . ' ' . $this->latestStatus . ' : ' . $this->getWin32ServiceStatusDesc( $this->latestStatus );
        }
        return null;
    }
References $bearsamppLang, $latestError, Lang\ERROR, and Lang\STATUS.
getLatestError()
Nssm::getLatestError ()
Gets the latest error message related to the service.
Returns
string The latest error message.
Definition at line 668 of file class.nssm.php.
    {
        return $this->latestError;
    }
References $latestError.
getLatestStatus()
Nssm::getLatestStatus ()
Gets the latest status of the service.
Returns
string The latest status of the service.
Definition at line 658 of file class.nssm.php.
    {
        return $this->latestStatus;
    }
References $latestStatus.
getName()
Nssm::getName ()
Gets the name of the service.
Returns
string The name of the service.
Definition at line 498 of file class.nssm.php.
    {
        return $this->name;
    }
References $name.
Referenced by create(), delete(), infos(), isInstalled(), isPaused(), isRunning(), isStopped(), start(), status(), and stop().
getParams()
Nssm::getParams ()
Gets the parameters of the service.
Returns
string The parameters of the service.
Definition at line 558 of file class.nssm.php.
    {
        return $this->params;
    }
References $params.
Referenced by create().
getServiceStatusDesc()
Nssm::getServiceStatusDesc ($status) private
Retrieves the description of the service status.
Parameters
string $status The status to describe.
Returns
string|null The description of the status, or null if not recognized.
Definition at line 461 of file class.nssm.php.
    {
        switch ( $status ) {
            case self::STATUS_CONTINUE_PENDING:
                return 'The service continue is pending.';
            case self::STATUS_PAUSE_PENDING:
                return 'The service pause is pending.';
            case self::STATUS_PAUSED:
                return 'The service is paused.';
            case self::STATUS_RUNNING:
                return 'The service is running.';
            case self::STATUS_START_PENDING:
                return 'The service is starting.';
            case self::STATUS_STOP_PENDING:
                return 'The service is stopping.';
            case self::STATUS_STOPPED:
                return 'The service is not running.';
            case self::STATUS_NA:
                return 'Cannot retrieve service status.';
            default:
                return null;
        }
    }
References STATUS_CONTINUE_PENDING, STATUS_NA, STATUS_PAUSE_PENDING, STATUS_PAUSED, STATUS_RUNNING, STATUS_START_PENDING, STATUS_STOP_PENDING, and STATUS_STOPPED.
getStart()
Nssm::getStart ()
Gets the start type of the service.
Returns
string The start type of the service.
Definition at line 578 of file class.nssm.php.
    {
        return $this->start;
    }
References $start.
Referenced by create().
getStderr()
Nssm::getStderr ()
Gets the stderr path of the service.
Returns
string The stderr path of the service.
Definition at line 618 of file class.nssm.php.
    {
        return $this->stderr;
    }
References $stderr.
Referenced by create().
getStdout()
Nssm::getStdout ()
Gets the stdout path of the service.
Returns
string The stdout path of the service.
Definition at line 598 of file class.nssm.php.
    {
        return $this->stdout;
    }
References $stdout.
Referenced by create().
infos()
Nssm::infos ()
Retrieves information about the service.
Returns
array|false The service information, or false on failure.
Definition at line 348 of file class.nssm.php.
    {
        global $bearsamppRegistry;
        $infos = Vbs::getServiceInfos( $this->getName() );
        if ( $infos === false ) {
            return false;
        }
        $infosNssm = array();
        $infosKeys = array(
            self::INFO_APPLICATION,
            self::INFO_APP_PARAMETERS,
        );
        foreach ( $infosKeys as $infoKey ) {
            $value  = null;
            $exists = $bearsamppRegistry->exists(
                Registry::HKEY_LOCAL_MACHINE,
                'SYSTEM\CurrentControlSet\Services\\' . $this->getName() . '\Parameters',
                $infoKey
            );
            if ( $exists ) {
                $value = $bearsamppRegistry->getValue(
                    Registry::HKEY_LOCAL_MACHINE,
                    'SYSTEM\CurrentControlSet\Services\\' . $this->getName() . '\Parameters',
                    $infoKey
                );
            }
            $infosNssm[$infoKey] = $value;
        }
        if ( !isset( $infosNssm[self::INFO_APPLICATION] ) ) {
            return $infos;
        }
        $infos[Win32Service::VBS_PATH_NAME] = $infosNssm[Nssm::INFO_APPLICATION] . ' ' . $infosNssm[Nssm::INFO_APP_PARAMETERS];
        return $infos;
    }
References getName(), Vbs\getServiceInfos(), Registry\HKEY_LOCAL_MACHINE, INFO_APP_PARAMETERS, INFO_APPLICATION, and Win32Service\VBS_PATH_NAME.
isInstalled()
Nssm::isInstalled ()
Checks if the service is installed.
Returns
bool True if the service is installed, false otherwise.
Definition at line 394 of file class.nssm.php.
    {
        $status = $this->status();
        $this->writeLog( 'isInstalled ' . $this->getName() . ': ' . ($status != self::STATUS_NA ? 'YES' : 'NO') . ' (status: ' . $status . ')' );
        return $status != self::STATUS_NA;
    }
References getName(), status(), STATUS_NA, and writeLog().
Referenced by create(), and delete().
isPaused()
Nssm::isPaused ()
Checks if the service is paused.
Returns
bool True if the service is paused, false otherwise.
Definition at line 433 of file class.nssm.php.
    {
        $status = $this->status();
        $this->writeLog( 'isPaused ' . $this->getName() . ': ' . ($status == self::STATUS_PAUSED ? 'YES' : 'NO') . ' (status: ' . $status . ')' );
        return $status == self::STATUS_PAUSED;
    }
References getName(), status(), STATUS_PAUSED, and writeLog().
isPending()
Nssm::isPending ($status)
Checks if the service status is pending.
Parameters
string $status The status to check.
Returns
bool True if the status is pending, false otherwise.
Definition at line 448 of file class.nssm.php.
    {
        return $status == self::STATUS_START_PENDING || $status == self::STATUS_STOP_PENDING
            || $status == self::STATUS_CONTINUE_PENDING || $status == self::STATUS_PAUSE_PENDING;
    }
References STATUS_PAUSE_PENDING.
Referenced by status().
isRunning()
Nssm::isRunning ()
Checks if the service is running.
Returns
bool True if the service is running, false otherwise.
Definition at line 407 of file class.nssm.php.
    {
        $status = $this->status();
        $this->writeLog( 'isRunning ' . $this->getName() . ': ' . ($status == self::STATUS_RUNNING ? 'YES' : 'NO') . ' (status: ' . $status . ')' );
        return $status == self::STATUS_RUNNING;
    }
References getName(), status(), STATUS_RUNNING, and writeLog().
Referenced by start().
isStopped()
Nssm::isStopped ()
Checks if the service is stopped.
Returns
bool True if the service is stopped, false otherwise.
Definition at line 420 of file class.nssm.php.
    {
        $status = $this->status();
        $this->writeLog( 'isStopped ' . $this->getName() . ': ' . ($status == self::STATUS_STOPPED ? 'YES' : 'NO') . ' (status: ' . $status . ')' );
        return $status == self::STATUS_STOPPED;
    }
References getName(), status(), STATUS_STOPPED, and writeLog().
Referenced by stop().
restart()
Nssm::restart ()
Restarts the service.
Returns
bool True if the service was restarted successfully, false otherwise.
Definition at line 334 of file class.nssm.php.
    {
        if ( $this->stop() ) {
            return $this->start();
        }
        return false;
    }
References start(), and stop().
setBinPath()
Nssm::setBinPath ($binPath)
Sets the binary path of the service.
Parameters
string $binPath The binary path to set.
Definition at line 548 of file class.nssm.php.
    {
        $this->binPath = str_replace( '"', '', Util::formatWindowsPath( $binPath ) );
    }
References $binPath, and Util\formatWindowsPath().
setDisplayName()
Nssm::setDisplayName ($displayName)
Sets the display name of the service.
Parameters
string $displayName The display name to set.
Definition at line 528 of file class.nssm.php.
    {
        $this->displayName = $displayName;
    }
References $displayName.
setEnvironmentExtra()
Nssm::setEnvironmentExtra ($environmentExtra)
Sets the additional environment variables for the service.
Parameters
string $environmentExtra The additional environment variables to set.
Definition at line 648 of file class.nssm.php.
    {
        $this->environmentExtra = Util::formatWindowsPath( $environmentExtra );
    }
References $environmentExtra, and Util\formatWindowsPath().
setName()
Nssm::setName ($name)
Sets the name of the service.
Parameters
string $name The name to set.
Definition at line 508 of file class.nssm.php.
    {
        $this->name = $name;
    }
References $name.
setParams()
Nssm::setParams ($params)
Sets the parameters of the service.
Parameters
string $params The parameters to set.
Definition at line 568 of file class.nssm.php.
    {
        $this->params = $params;
    }
References $params.
setStart()
Nssm::setStart ($start)
Sets the start type of the service.
Parameters
string $start The start type to set.
Definition at line 588 of file class.nssm.php.
    {
        $this->start = $start;
    }
References $start, and start().
setStderr()
Nssm::setStderr ($stderr)
Sets the stderr path of the service.
Parameters
string $stderr The stderr path to set.
Definition at line 628 of file class.nssm.php.
    {
        $this->stderr = $stderr;
    }
References $stderr.
setStdout()
Nssm::setStdout ($stdout)
Sets the stdout path of the service.
Parameters
string $stdout The stdout path to set.
Definition at line 608 of file class.nssm.php.
    {
        $this->stdout = $stdout;
    }
References $stdout.
start()
Nssm::start ()
Starts the service.
Returns
bool True if the service was started successfully, false otherwise.
Definition at line 288 of file class.nssm.php.
    {
        $this->writeLog( 'Start service ' . $this->getName() );
        $exec = $this->exec( 'start ' . $this->getName() );
        if ( $exec === false ) {
            return false;
        }
        if ( !$this->isRunning() ) {
            $this->latestError = null;
            return false;
        }
        return true;
    }
References exec(), getName(), isRunning(), and writeLog().
Referenced by restart(), and setStart().
status()
Nssm::status ($timeout = true)
Retrieves the status of the service.
Parameters
bool $timeout Whether to apply a timeout for the status check.
Returns
string The status of the service.
Definition at line 148 of file class.nssm.php.
    {
        usleep( self::SLEEP_TIME );
        $this->latestStatus = self::STATUS_NA;
        $maxtime            = time() + self::PENDING_TIMEOUT;
        while ( $this->latestStatus == self::STATUS_NA || $this->isPending( $this->latestStatus ) ) {
            $exec = $this->exec( 'status ' . $this->getName() );
            if ( $exec !== false ) {
                if ( count( $exec ) > 1 ) {
                    $this->latestStatus = self::STATUS_NOT_EXIST;
                }
                else {
                    $this->latestStatus = $exec[0];
                }
            }
            if ( $timeout && $maxtime < time() ) {
                break;
            }
        }
        if ( $this->latestStatus == self::STATUS_NOT_EXIST ) {
            $this->latestError  = 'Error 3: The specified service does not exist as an installed service.';
            $this->latestStatus = self::STATUS_NA;
        }
        return $this->latestStatus;
    }
References $latestStatus, exec(), getName(), isPending(), PENDING_TIMEOUT, STATUS_NA, and STATUS_NOT_EXIST.
Referenced by isInstalled(), isPaused(), isRunning(), and isStopped().
stop()
Nssm::stop ()
Stops the service.
Returns
bool True if the service was stopped successfully, false otherwise.
Definition at line 311 of file class.nssm.php.
    {
        $this->writeLog( 'Stop service ' . $this->getName() );
        $exec = $this->exec( 'stop ' . $this->getName() );
        if ( $exec === false ) {
            return false;
        }
        if ( !$this->isStopped() ) {
            $this->latestError = null;
            return false;
        }
        return true;
    }
References exec(), getName(), isStopped(), and writeLog().
Referenced by delete(), and restart().
writeLog()
Nssm::writeLog ($log) private
Writes a log entry.
Parameters
string $log The log message to write.
Definition at line 79 of file class.nssm.php.
    {
        global $bearsamppRoot;
        Util::logDebug( $log, $bearsamppRoot->getNssmLogFilePath() );
    }
References $bearsamppRoot, and Util\logDebug().
Referenced by create(), delete(), isInstalled(), isPaused(), isRunning(), isStopped(), start(), and stop().
writeLogError()
Nssm::writeLogError ($log) private
Writes an error log entry.
Parameters
string $log The log message to write.
Definition at line 101 of file class.nssm.php.
    {
        global $bearsamppRoot;
        Util::logError( $log, $bearsamppRoot->getNssmLogFilePath() );
    }
References $bearsamppRoot, and Util\logError().
writeLogInfo()
Nssm::writeLogInfo ($log) private
Writes an informational log entry.
Parameters
string $log The log message to write.
Definition at line 90 of file class.nssm.php.
    {
        global $bearsamppRoot;
        Util::logInfo( $log, $bearsamppRoot->getNssmLogFilePath() );
    }
References $bearsamppRoot, and Util\logInfo().
Referenced by exec().
Field Documentation
$binPath
Nssm::$binPath private
Definition at line 53 of file class.nssm.php.
Referenced by getBinPath(), and setBinPath().
$displayName
Nssm::$displayName private
Definition at line 52 of file class.nssm.php.
Referenced by getDisplayName(), and setDisplayName().
$environmentExtra
Nssm::$environmentExtra private
Definition at line 58 of file class.nssm.php.
Referenced by getEnvironmentExtra(), and setEnvironmentExtra().
$latestError
Nssm::$latestError private
Definition at line 59 of file class.nssm.php.
Referenced by getError(), and getLatestError().
$latestStatus
Nssm::$latestStatus private
Definition at line 60 of file class.nssm.php.
Referenced by getLatestStatus(), and status().
$name
Nssm::$name private
Definition at line 51 of file class.nssm.php.
Referenced by __construct(), getName(), and setName().
$params
Nssm::$params private
Definition at line 54 of file class.nssm.php.
Referenced by getParams(), and setParams().
$start
Nssm::$start private
Definition at line 55 of file class.nssm.php.
Referenced by getStart(), and setStart().
$stderr
Nssm::$stderr private
Definition at line 57 of file class.nssm.php.
Referenced by getStderr(), and setStderr().
$stdout
Nssm::$stdout private
Definition at line 56 of file class.nssm.php.
Referenced by getStdout(), and setStdout().
INFO_APP_DIRECTORY
const Nssm::INFO_APP_DIRECTORY = 'AppDirectory'
Definition at line 41 of file class.nssm.php.
INFO_APP_ENVIRONMENT_EXTRA
const Nssm::INFO_APP_ENVIRONMENT_EXTRA = 'AppEnvironmentExtra'
Definition at line 46 of file class.nssm.php.
INFO_APP_PARAMETERS
const Nssm::INFO_APP_PARAMETERS = 'AppParameters'
Definition at line 43 of file class.nssm.php.
Referenced by infos(), BinMailhog\rebuildConf(), BinMailpit\rebuildConf(), BinMemcached\rebuildConf(), and BinXlight\rebuildConf().
INFO_APP_STDERR
const Nssm::INFO_APP_STDERR = 'AppStderr'
Definition at line 44 of file class.nssm.php.
INFO_APP_STDOUT
const Nssm::INFO_APP_STDOUT = 'AppStdout'
Definition at line 45 of file class.nssm.php.
INFO_APPLICATION
const Nssm::INFO_APPLICATION = 'Application'
Definition at line 42 of file class.nssm.php.
Referenced by infos().
PENDING_TIMEOUT
const Nssm::PENDING_TIMEOUT = 10
Definition at line 48 of file class.nssm.php.
Referenced by status().
SERVICE_AUTO_START
const Nssm::SERVICE_AUTO_START = 'SERVICE_AUTO_START'
Definition at line 20 of file class.nssm.php.
SERVICE_DELAYED_START
const Nssm::SERVICE_DELAYED_START = 'SERVICE_DELAYED_START'
Definition at line 21 of file class.nssm.php.
SERVICE_DEMAND_START
const Nssm::SERVICE_DEMAND_START = 'SERVICE_DEMAND_START'
Definition at line 22 of file class.nssm.php.
Referenced by create(), BinApache\reload(), BinMailhog\reload(), BinMailpit\reload(), BinMemcached\reload(), and BinXlight\reload().
SERVICE_DISABLED
const Nssm::SERVICE_DISABLED = 'SERVICE_DISABLED'
Definition at line 23 of file class.nssm.php.
SERVICE_INTERACTIVE_PROCESS
const Nssm::SERVICE_INTERACTIVE_PROCESS = 'SERVICE_INTERACTIVE_PROCESS'
Definition at line 27 of file class.nssm.php.
SERVICE_WIN32_OWN_PROCESS
const Nssm::SERVICE_WIN32_OWN_PROCESS = 'SERVICE_WIN32_OWN_PROCESS'
Definition at line 26 of file class.nssm.php.
SLEEP_TIME
const Nssm::SLEEP_TIME = 500000
Definition at line 49 of file class.nssm.php.
STATUS_CONTINUE_PENDING
const Nssm::STATUS_CONTINUE_PENDING = 'SERVICE_CONTINUE_PENDING'
Definition at line 30 of file class.nssm.php.
Referenced by getServiceStatusDesc().
STATUS_NA
const Nssm::STATUS_NA = '-1'
Definition at line 38 of file class.nssm.php.
Referenced by getServiceStatusDesc(), isInstalled(), and status().
STATUS_NOT_EXIST
const Nssm::STATUS_NOT_EXIST = 'SERVICE_NOT_EXIST'
Definition at line 37 of file class.nssm.php.
Referenced by status().
STATUS_PAUSE_PENDING
const Nssm::STATUS_PAUSE_PENDING = 'SERVICE_PAUSE_PENDING'
Definition at line 31 of file class.nssm.php.
Referenced by getServiceStatusDesc(), and isPending().
STATUS_PAUSED
const Nssm::STATUS_PAUSED = 'SERVICE_PAUSED'
Definition at line 32 of file class.nssm.php.
Referenced by getServiceStatusDesc(), and isPaused().
STATUS_RUNNING
const Nssm::STATUS_RUNNING = 'SERVICE_RUNNING'
Definition at line 33 of file class.nssm.php.
Referenced by getServiceStatusDesc(), and isRunning().
STATUS_START_PENDING
const Nssm::STATUS_START_PENDING = 'SERVICE_START_PENDING'
Definition at line 34 of file class.nssm.php.
Referenced by getServiceStatusDesc().
STATUS_STOP_PENDING
const Nssm::STATUS_STOP_PENDING = 'SERVICE_STOP_PENDING'
Definition at line 35 of file class.nssm.php.
Referenced by getServiceStatusDesc().
STATUS_STOPPED
const Nssm::STATUS_STOPPED = 'SERVICE_STOPPED'
Definition at line 36 of file class.nssm.php.
Referenced by getServiceStatusDesc(), and isStopped().
The documentation for this class was generated from the following file:
E:/Bearsampp-development/sandbox/core/classes/class.nssm.php