My Project: Module Class Reference
Module Class Reference
Public Member Functions
__toString ()
getCurrentPath ()
getId ()
getName ()
getRelease ()
getRootPath ()
getSymlinkPath ()
getType ()
getVersion ()
getVersionList ()
isEnable ()
setVersion ($version)
update ($sub=0, $showWindow=false)
Data Fields
const BUNDLE_RELEASE = 'bundleRelease'
Protected Member Functions
__construct ()
reload ($id=null, $type=null)
replace ($key, $value)
replaceAll ($params)
updateConfig ($version=null, $sub=0, $showWindow=false)
Protected Attributes
$bearsamppConf
$bearsamppConfRaw
$currentPath
$enable
$name
$release = 'N/A'
$rootPath
$symlinkPath
$version
Private Member Functions
createSymlink ()
Private Attributes
$id
$type
Detailed Description
Abstract class representing a module in the Bearsampp application. This class provides common functionalities for managing modules such as apps, bins, and tools.
Definition at line 14 of file class.module.php.
Constructor & Destructor Documentation
__construct()
Module::__construct () protected
Constructor for the Module class. Initializes the module with default values.
Definition at line 36 of file class.module.php.
{
        // Initialization logic can be added here if needed
    }
Member Function Documentation
__toString()
Module::__toString ()
Returns the name of the module.
Returns
string The name of the module.
Definition at line 169 of file class.module.php.
{
        return $this->getName();
    }
References getName().
createSymlink()
Module::createSymlink () private
Creates a symbolic link from the current path to the symlink path. If the symlink already exists and points to the correct target, no action is taken.
Definition at line 88 of file class.module.php.
    {
        $src = Util::formatWindowsPath($this->currentPath);
        $dest = Util::formatWindowsPath($this->symlinkPath);
        if(file_exists($dest)) {
            if (is_link($dest)) {
                $target = readlink($dest);
                if ($target == $src) {
                    return;
                }
                Batch::removeSymlink($dest);
            } elseif (is_file($dest)) {
                Util::logError('Removing . ' . $this->symlinkPath . ' file. It should not be a regular file');
                unlink($dest);
            } elseif (is_dir($dest)) {
                if (!(new \FilesystemIterator($dest))->valid()) {
                    rmdir($dest);
                } else {
                    Util::logError($this->symlinkPath . ' should be a symlink to ' . $this->currentPath . '. Please remove this dir and restart bearsampp.');
                    return;
                }
            }
        }
        Batch::createSymlink($src, $dest);
    }
References Batch\createSymlink(), Util\formatWindowsPath(), Util\logError(), and Batch\removeSymlink().
Referenced by reload().
getCurrentPath()
Module::getCurrentPath ()
Gets the current path of the module.
Returns
string The current path of the module.
Definition at line 248 of file class.module.php.
{
        return $this->currentPath;
    }
References $currentPath.
Referenced by BinPhp\getApacheModule(), BinPhp\getExtensionsFromFolder(), BinPhp\getPearVersion(), BinPhp\getTsDll(), BinMysql\initData(), BinPostgresql\initData(), BinMysql\updateConfig(), and BinPostgresql\updateConfig().
getId()
Module::getId ()
Gets the ID of the module.
Returns
string The ID of the module.
Definition at line 187 of file class.module.php.
{
        return $this->id;
    }
References $id.
getName()
Module::getName ()
Gets the name of the module.
Returns
string The name of the module.
Definition at line 196 of file class.module.php.
{
        return $this->name;
    }
References $name.
Referenced by __toString(), BinApache\changePort(), BinFilezilla\changePort(), BinMailhog\changePort(), BinMailpit\changePort(), BinMariadb\changePort(), BinMemcached\changePort(), BinMysql\changePort(), BinPostgresql\changePort(), BinXlight\changePort(), BinApache\checkPort(), BinFilezilla\checkPort(), BinMailhog\checkPort(), BinMailpit\checkPort(), BinMariadb\checkPort(), BinMemcached\checkPort(), BinMysql\checkPort(), BinPostgresql\checkPort(), BinXlight\checkPort(), BinApache\reload(), BinFilezilla\reload(), BinMailhog\reload(), BinMailpit\reload(), BinMariadb\reload(), BinMemcached\reload(), BinMysql\reload(), BinPostgresql\reload(), BinXlight\reload(), BinApache\setEnable(), BinFilezilla\setEnable(), BinMailhog\setEnable(), BinMailpit\setEnable(), BinMariadb\setEnable(), BinMemcached\setEnable(), BinMysql\setEnable(), BinNodejs\setEnable(), BinPhp\setEnable(), BinPostgresql\setEnable(), BinXlight\setEnable(), AppAdminer\updateConfig(), AppPhpmyadmin\updateConfig(), AppPhppgadmin\updateConfig(), AppWebgrind\updateConfig(), BinApache\updateConfig(), BinFilezilla\updateConfig(), BinMailhog\updateConfig(), BinMailpit\updateConfig(), BinMariadb\updateConfig(), BinMemcached\updateConfig(), BinMysql\updateConfig(), BinNodejs\updateConfig(), BinPhp\updateConfig(), BinPostgresql\updateConfig(), and BinXlight\updateConfig().
getRelease()
Module::getRelease ()
Gets the release information of the module.
Returns
string The release information.
Definition at line 230 of file class.module.php.
{
        return $this->release;
    }
References $release.
getRootPath()
Module::getRootPath ()
Gets the root path of the module.
Returns
string The root path of the module.
Definition at line 239 of file class.module.php.
{
        return $this->rootPath;
    }
References $rootPath.
getSymlinkPath()
Module::getSymlinkPath ()
Gets the symlink path of the module.
Returns
string The symlink path of the module.
Definition at line 257 of file class.module.php.
{
        return $this->symlinkPath;
    }
References $symlinkPath.
Referenced by AppAdminer\updateConfig(), AppPhpmyadmin\updateConfig(), AppPhppgadmin\updateConfig(), AppWebgrind\updateConfig(), and ToolGit\updateConfig().
getType()
Module::getType ()
Gets the type of the module.
Returns
string The type of the module.
Definition at line 178 of file class.module.php.
{
        return $this->type;
    }
References $type.
getVersion()
Module::getVersion ()
Gets the version of the module.
Returns
string The version of the module.
Definition at line 205 of file class.module.php.
{
        return $this->version;
    }
References $version.
Referenced by BinPostgresql\checkPort(), BinPhp\getApacheModule(), BinApache\getOfflineContent(), BinApache\getOnlineContent(), BinPhp\getTsDll(), BinMysql\initData(), BinApache\setEnable(), BinFilezilla\setEnable(), BinMailhog\setEnable(), BinMailpit\setEnable(), BinMariadb\setEnable(), BinMemcached\setEnable(), BinMysql\setEnable(), BinNodejs\setEnable(), BinPhp\setEnable(), BinPostgresql\setEnable(), BinXlight\setEnable(), BinApache\updateConfig(), BinFilezilla\updateConfig(), BinMailhog\updateConfig(), BinMailpit\updateConfig(), BinMariadb\updateConfig(), BinMemcached\updateConfig(), BinMysql\updateConfig(), BinNodejs\updateConfig(), BinPhp\updateConfig(), BinPostgresql\updateConfig(), and BinXlight\updateConfig().
getVersionList()
Module::getVersionList ()
Gets the list of available versions for the module.
Returns
array The list of available versions.
Definition at line 214 of file class.module.php.
{
        return Util::getVersionList($this->rootPath);
    }
References Util\getVersionList().
Referenced by BinPhp\getApacheModule().
isEnable()
Module::isEnable ()
Checks if the module is enabled.
Returns
bool True if the module is enabled, false otherwise.
Definition at line 266 of file class.module.php.
{
        return $this->enable;
    }
References $enable.
reload()
Module::reload ($id = null, $type = null) protected
Reloads the module configuration based on the provided ID and type.
Parameters
string | null $id The ID of the module. If null, the current ID is used.
string | null $type The type of the module. If null, the current type is used.
Reimplemented in AppAdminer, AppPhpmyadmin, AppPhppgadmin, AppWebgrind, BinApache, BinFilezilla, BinMailhog, BinMailpit, BinMariadb, BinMemcached, BinMysql, BinNodejs, BinPhp, BinPostgresql, BinXlight, ToolComposer, ToolConsoleZ, ToolGhostscript, ToolGit, ToolNgrok, ToolPerl, ToolPython, ToolRuby, ToolXdc, and ToolYarn.
Definition at line 46 of file class.module.php.
{
        global $bearsamppRoot;
        $this->id = empty($id) ? $this->id : $id;
        $this->type = empty($type) ? $this->type : $type;
        $mainPath = 'N/A';
        switch ($this->type) {
            case Apps::TYPE:
                $mainPath = $bearsamppRoot->getAppsPath();
                break;
            case Bins::TYPE:
                $mainPath = $bearsamppRoot->getBinPath();
                break;
            case Tools::TYPE:
                $mainPath = $bearsamppRoot->getToolsPath();
                break;
        }
        $this->rootPath = $mainPath . '/' . $this->id;
        $this->currentPath = $this->rootPath . '/' . $this->id . $this->version;
        $this->symlinkPath = $this->rootPath . '/current';
        $this->enable = is_dir($this->currentPath);
        $this->bearsamppConf = $this->currentPath . '/bearsampp.conf';
        $this->bearsamppConfRaw = @parse_ini_file($this->bearsamppConf);
        if ($bearsamppRoot->isRoot()) {
            $this->createSymlink();
        }
        // TODO Can we replace this or remove it since we dont use bundles?
        if ($this->bearsamppConfRaw !== false) {
            if (isset($this->bearsamppConfRaw[self::BUNDLE_RELEASE])) {
                $this->release = $this->bearsamppConfRaw[self::BUNDLE_RELEASE];
            }
        }
    }
References $bearsamppRoot, $id, $type, $version, BUNDLE_RELEASE, createSymlink(), Apps\TYPE, Bins\TYPE, and Tools\TYPE.
replace()
Module::replace ($key, $value) protected
Replaces a specific key-value pair in the configuration file.
Parameters
string $key The key to replace.
string $value The new value for the key.
Definition at line 122 of file class.module.php.
{
        $this->replaceAll(array($key => $value));
    }
References replaceAll().
Referenced by BinMailhog\setApiPort(), BinMailpit\setListen(), BinMemcached\setMemory(), BinApache\setPort(), BinFilezilla\setPort(), BinMariadb\setPort(), BinMemcached\setPort(), BinMysql\setPort(), BinPostgresql\setPort(), BinXlight\setPort(), BinMariadb\setRootPwd(), BinMysql\setRootPwd(), BinPostgresql\setRootPwd(), BinMariadb\setRootUser(), BinMysql\setRootUser(), BinPostgresql\setRootUser(), BinMailhog\setSmtpPort(), BinMailpit\setSmtpPort(), BinApache\setSslPort(), BinFilezilla\setSslPort(), BinXlight\setSslPort(), BinMailhog\setUiPort(), BinMailpit\setUiPort(), and BinMailpit\setWebRoot().
replaceAll()
Module::replaceAll ($params) protected
Replaces multiple key-value pairs in the configuration file.
Parameters
array $params An associative array of key-value pairs to replace.
Reimplemented in BinApache, BinFilezilla, BinMailhog, BinMailpit, BinMariadb, BinMemcached, BinMysql, BinPostgresql, and BinXlight.
Definition at line 131 of file class.module.php.
{
        $content = file_get_contents($this->bearsamppConf);
        foreach ($params as $key => $value) {
            $content = preg_replace('|' . $key . ' = .*|', $key . ' = ' . '"' . $value.'"', $content);
            $this->bearsamppConfRaw[$key] = $value;
        }
        file_put_contents($this->bearsamppConf, $content);
    }
Referenced by replace().
setVersion()
Module::setVersion ($version) abstract
Sets the version of the module.
Parameters
string $version The version to set.
Reimplemented in AppAdminer, AppPhpmyadmin, AppPhppgadmin, AppWebgrind, BinApache, BinFilezilla, BinMailhog, BinMailpit, BinMariadb, BinMemcached, BinMysql, BinNodejs, BinPhp, BinPostgresql, BinXlight, ToolComposer, ToolConsoleZ, ToolGhostscript, ToolGit, ToolNgrok, ToolPerl, ToolPython, ToolRuby, ToolXdc, and ToolYarn.
update()
Module::update ($sub = 0, $showWindow = false)
Updates the module configuration.
Parameters
int $sub The sub-level for logging indentation.
bool $showWindow Whether to show a window during the update process.
Definition at line 148 of file class.module.php.
{
        $this->updateConfig(null, $sub, $showWindow);
    }
References updateConfig().
Referenced by BinApache\changePort(), BinFilezilla\changePort(), BinMailhog\changePort(), BinMailpit\changePort(), BinMariadb\changePort(), BinMemcached\changePort(), BinMysql\changePort(), BinPostgresql\changePort(), BinXlight\changePort(), BinMariadb\changeRootPassword(), BinMysql\changeRootPassword(), and BinPostgresql\changeRootPassword().
updateConfig()
Module::updateConfig ($version = null, $sub = 0, $showWindow = false) protected
Updates the module configuration with a specific version.
Parameters
string | null $version The version to update to. If null, the current version is used.
int $sub The sub-level for logging indentation.
bool $showWindow Whether to show a window during the update process.
Reimplemented in AppAdminer, AppPhpmyadmin, AppPhppgadmin, AppWebgrind, BinApache, BinFilezilla, BinMailhog, BinMailpit, BinMariadb, BinMemcached, BinMysql, BinNodejs, BinPhp, BinPostgresql, BinXlight, and ToolGit.
Definition at line 159 of file class.module.php.
{
        $version = $version == null ? $this->version : $version;
        Util::logDebug(($sub > 0 ? str_repeat(' ', 2 * $sub) : '') . 'Update ' . $this->name . ' ' . $version . ' config');
    }
References $version, and Util\logDebug().
Referenced by update().
Field Documentation
$bearsamppConf
Module::$bearsamppConf protected
Definition at line 29 of file class.module.php.
Referenced by BinPhp\getApacheModule(), BinApache\updateConfig(), BinFilezilla\updateConfig(), BinMailhog\updateConfig(), BinMailpit\updateConfig(), BinMariadb\updateConfig(), BinMemcached\updateConfig(), BinMysql\updateConfig(), BinNodejs\updateConfig(), BinPhp\updateConfig(), BinPostgresql\updateConfig(), and BinXlight\updateConfig().
$bearsamppConfRaw
Module::$bearsamppConfRaw protected
Definition at line 30 of file class.module.php.
Referenced by BinApache\updateConfig(), BinFilezilla\updateConfig(), BinMailhog\updateConfig(), BinMailpit\updateConfig(), BinMariadb\updateConfig(), BinMemcached\updateConfig(), BinMysql\updateConfig(), BinNodejs\updateConfig(), BinPhp\updateConfig(), BinPostgresql\updateConfig(), and BinXlight\updateConfig().
$currentPath
Module::$currentPath protected
Definition at line 26 of file class.module.php.
Referenced by BinPhp\getApacheModule(), getCurrentPath(), BinPhp\getTsDll(), BinMysql\updateConfig(), and BinPostgresql\updateConfig().
$enable
Module::$enable protected
Definition at line 28 of file class.module.php.
Referenced by isEnable().
$id
Module::$id private
Definition at line 19 of file class.module.php.
Referenced by AppAdminer\__construct(), AppPhpmyadmin\__construct(), AppPhppgadmin\__construct(), AppWebgrind\__construct(), BinApache\__construct(), BinFilezilla\__construct(), BinMailhog\__construct(), BinMailpit\__construct(), BinMariadb\__construct(), BinMemcached\__construct(), BinMysql\__construct(), BinNodejs\__construct(), BinPhp\__construct(), BinPostgresql\__construct(), BinXlight\__construct(), ToolComposer\__construct(), ToolConsoleZ\__construct(), ToolGhostscript\__construct(), ToolGit\__construct(), ToolNgrok\__construct(), ToolPerl\__construct(), ToolPython\__construct(), ToolRuby\__construct(), ToolXdc\__construct(), ToolYarn\__construct(), getId(), AppAdminer\reload(), AppPhpmyadmin\reload(), AppPhppgadmin\reload(), AppWebgrind\reload(), BinApache\reload(), BinFilezilla\reload(), BinMailhog\reload(), BinMailpit\reload(), BinMariadb\reload(), BinMemcached\reload(), BinMysql\reload(), BinNodejs\reload(), BinPhp\reload(), BinPostgresql\reload(), BinXlight\reload(), reload(), ToolComposer\reload(), ToolConsoleZ\reload(), ToolGhostscript\reload(), ToolGit\reload(), ToolNgrok\reload(), ToolPerl\reload(), ToolPython\reload(), ToolRuby\reload(), ToolXdc\reload(), and ToolYarn\reload().
$name
Module::$name protected
Definition at line 21 of file class.module.php.
Referenced by BinApache\getAliasContent(), BinPhp\getExtensionsFromConf(), BinPhp\getExtensionsFromFolder(), BinPhp\getExtensionsLoaded(), BinApache\getModulesFromConf(), BinApache\getModulesFromFolder(), BinApache\getModulesLoaded(), getName(), BinPhp\isSettingActive(), and BinPhp\isSettingExists().
$release
Module::$release = 'N/A' protected
Definition at line 23 of file class.module.php.
Referenced by getRelease().
$rootPath
Module::$rootPath protected
Definition at line 25 of file class.module.php.
Referenced by getRootPath().
$symlinkPath
Module::$symlinkPath protected
Definition at line 27 of file class.module.php.
Referenced by getSymlinkPath().
$type
Module::$type private
Definition at line 18 of file class.module.php.
Referenced by AppAdminer\__construct(), AppPhpmyadmin\__construct(), AppPhppgadmin\__construct(), AppWebgrind\__construct(), BinApache\__construct(), BinFilezilla\__construct(), BinMailhog\__construct(), BinMailpit\__construct(), BinMariadb\__construct(), BinMemcached\__construct(), BinMysql\__construct(), BinNodejs\__construct(), BinPhp\__construct(), BinPostgresql\__construct(), BinXlight\__construct(), ToolComposer\__construct(), ToolConsoleZ\__construct(), ToolGhostscript\__construct(), ToolGit\__construct(), ToolNgrok\__construct(), ToolPerl\__construct(), ToolPython\__construct(), ToolRuby\__construct(), ToolXdc\__construct(), ToolYarn\__construct(), getType(), AppAdminer\reload(), AppPhpmyadmin\reload(), AppPhppgadmin\reload(), AppWebgrind\reload(), BinApache\reload(), BinFilezilla\reload(), BinMailhog\reload(), BinMailpit\reload(), BinMariadb\reload(), BinMemcached\reload(), BinMysql\reload(), BinNodejs\reload(), BinPhp\reload(), BinPostgresql\reload(), BinXlight\reload(), reload(), ToolComposer\reload(), ToolConsoleZ\reload(), ToolGhostscript\reload(), ToolGit\reload(), ToolNgrok\reload(), ToolPerl\reload(), ToolPython\reload(), ToolRuby\reload(), ToolXdc\reload(), and ToolYarn\reload().
$version
Module::$version protected
Definition at line 22 of file class.module.php.
Referenced by BinMariadb\checkPort(), BinMysql\checkPort(), BinPostgresql\checkPort(), BinApache\getOfflineContent(), BinApache\getOnlineContent(), BinApache\getRequiredContent(), getVersion(), BinMysql\initData(), reload(), AppWebgrind\setVersion(), BinApache\setVersion(), BinFilezilla\setVersion(), BinMailhog\setVersion(), BinMailpit\setVersion(), BinMariadb\setVersion(), BinMemcached\setVersion(), BinMysql\setVersion(), BinNodejs\setVersion(), BinPhp\setVersion(), BinPostgresql\setVersion(), BinXlight\setVersion(), ToolComposer\setVersion(), ToolConsoleZ\setVersion(), ToolGhostscript\setVersion(), ToolGit\setVersion(), ToolNgrok\setVersion(), ToolPerl\setVersion(), ToolPython\setVersion(), ToolRuby\setVersion(), ToolXdc\setVersion(), ToolYarn\setVersion(), BinApache\switchVersion(), BinFilezilla\switchVersion(), BinMailhog\switchVersion(), BinMailpit\switchVersion(), BinMariadb\switchVersion(), BinMemcached\switchVersion(), BinMysql\switchVersion(), BinNodejs\switchVersion(), BinPhp\switchVersion(), BinPostgresql\switchVersion(), BinXlight\switchVersion(), AppAdminer\updateConfig(), AppPhpmyadmin\updateConfig(), AppPhppgadmin\updateConfig(), AppWebgrind\updateConfig(), BinApache\updateConfig(), BinFilezilla\updateConfig(), BinMailhog\updateConfig(), BinMailpit\updateConfig(), BinMariadb\updateConfig(), BinMemcached\updateConfig(), BinMysql\updateConfig(), BinNodejs\updateConfig(), BinPhp\updateConfig(), BinPostgresql\updateConfig(), BinXlight\updateConfig(), updateConfig(), and ToolGit\updateConfig().
BUNDLE_RELEASE
const Module::BUNDLE_RELEASE = 'bundleRelease'
Definition at line 16 of file class.module.php.
Referenced by reload().
The documentation for this class was generated from the following file:
E:/Bearsampp-development/sandbox/core/classes/class.module.php