Bearsampp: BinMailhog Class Reference
BinMailhog Class Reference
Public Member Functions
__construct ($id, $type)
changePort ($port, $checkUsed=false, $wbProgressBar=null)
checkPort ($port, $showWindow=false)
getApiPort ()
getExe ()
getLog ()
getMailPath ()
getService ()
getSmtpPort ()
getUiPort ()
rebuildConf ()
reload ($id=null, $type=null)
setApiPort ($apiPort)
setEnable ($enabled, $showWindow=false)
setSmtpPort ($smtpPort)
setUiPort ($uiPort)
setVersion ($version)
switchVersion ($version, $showWindow=false)
Public Member Functions inherited from Module
__toString ()
getCurrentPath ()
getId ()
getName ()
getRelease ()
getRootPath ()
getSymlinkPath ()
getType ()
getVersion ()
getVersionList ()
isEnable ()
update ($sub=0, $showWindow=false)
Data Fields
const LOCAL_CFG_API_PORT = 'mailhogApiPort'
const LOCAL_CFG_EXE = 'mailhogExe'
const LOCAL_CFG_SMTP_PORT = 'mailhogSmtpPort'
const LOCAL_CFG_UI_PORT = 'mailhogUiPort'
const ROOT_CFG_ENABLE = 'mailhogEnable'
const ROOT_CFG_VERSION = 'mailhogVersion'
const SERVICE_NAME = 'bearsamppmailhog'
const SERVICE_PARAMS = '-hostname localhost -api-bind-addr 127.0.0.1:%d -ui-bind-addr 127.0.0.1:%d -smtp-bind-addr 127.0.0.1:%d -storage maildir -maildir-path "%s"'
Data Fields inherited from Module
const BUNDLE_RELEASE = 'bundleRelease'
Protected Member Functions
replaceAll ($params)
updateConfig ($version=null, $sub=0, $showWindow=false)
Protected Member Functions inherited from Module
__construct ()
replace ($key, $value)
Private Attributes
$apiPort
$exe
$log
$mailPath
$service
$smtpPort
$uiPort
Additional Inherited Members
Protected Attributes inherited from Module
$bearsamppConf
$bearsamppConfRaw
$currentPath
$enable
$name
$release = 'N/A'
$rootPath
$symlinkPath
$version
Detailed Description
Class BinMailhog
This class represents the Mailhog module in the Bearsampp application. It handles the configuration, initialization, and management of the Mailhog service.
Definition at line 16 of file class.bin.mailhog.php.
Constructor & Destructor Documentation
__construct()
BinMailhog::__construct ($id, $type)
Constructs a BinMailhog object and initializes the module.
Parameters
string $id The ID of the module.
string $type The type of the module.
Definition at line 44 of file class.bin.mailhog.php.
    {
        Util::logInitClass( $this );
        $this->reload( $id, $type );
    }
References Module\$id, Module\$type, Util\logInitClass(), and reload().
Member Function Documentation
changePort()
BinMailhog::changePort ($port, $checkUsed = false, $wbProgressBar = null)
Changes the SMTP port for the Mailhog service.
Parameters
int $port The new port number.
bool $checkUsed Whether to check if the port is already in use.
mixed $wbProgressBar The progress bar object for UI updates.
Returns
bool|int True if the port was successfully changed, or the process using the port if in use.
Definition at line 192 of file class.bin.mailhog.php.
    {
        global $bearsamppWinbinder;
        if ( !Util::isValidPort( $port ) ) {
            Util::logError( $this->getName() . ' port not valid: ' . $port );
            return false;
        }
        $port = intval( $port );
        $bearsamppWinbinder->incrProgressBar( $wbProgressBar );
        $isPortInUse = Util::isPortInUse( $port );
        if ( !$checkUsed || $isPortInUse === false ) {
            // bearsampp.conf
            $this->setSmtpPort( $port );
            $bearsamppWinbinder->incrProgressBar( $wbProgressBar );
            // conf
            $this->update();
            $bearsamppWinbinder->incrProgressBar( $wbProgressBar );
            return true;
        }
        Util::logDebug( $this->getName() . ' port in used: ' . $port . ' - ' . $isPortInUse );
        return $isPortInUse;
    }
References $port, Module\getName(), Util\isPortInUse(), Util\isValidPort(), Util\logDebug(), Util\logError(), setSmtpPort(), and Module\update().
checkPort()
BinMailhog::checkPort ($port, $showWindow = false)
Checks if a specific port is used by the Mailhog service.
Parameters
int $port The port number to check.
bool $showWindow Whether to show a message box with the result.
Returns
bool True if the port is used by Mailhog, false otherwise.
Definition at line 231 of file class.bin.mailhog.php.
    {
        global $bearsamppLang, $bearsamppWinbinder;
        $boxTitle = sprintf( $bearsamppLang->getValue( Lang::CHECK_PORT_TITLE ), $this->getName(), $port );
        if ( !Util::isValidPort( $port ) ) {
            Util::logError( $this->getName() . ' port not valid: ' . $port );
            return false;
        }
        $headers = Util::getHeaders( '127.0.0.1', $port );
        if ( !empty( $headers ) ) {
            if ( Util::contains( $headers[0], 'MailHog' ) ) {
                Util::logDebug( $this->getName() . ' port ' . $port . ' is used by: ' . str_replace( '220 ', '', $headers[0] ) );
                if ( $showWindow ) {
                    $bearsamppWinbinder->messageBoxInfo(
                        sprintf( $bearsamppLang->getValue( Lang::PORT_USED_BY ), $port, str_replace( '220 ', '', $headers[0] ) ),
                        $boxTitle
                    );
                }
                return true;
            }
            Util::logDebug( $this->getName() . ' port ' . $port . ' is used by another application' );
            if ( $showWindow ) {
                $bearsamppWinbinder->messageBoxWarning(
                    sprintf( $bearsamppLang->getValue( Lang::PORT_NOT_USED_BY ), $port ),
                    $boxTitle
                );
            }
        }
        else {
            Util::logDebug( $this->getName() . ' port ' . $port . ' is not used' );
            if ( $showWindow ) {
                $bearsamppWinbinder->messageBoxError(
                    sprintf( $bearsamppLang->getValue( Lang::PORT_NOT_USED ), $port ),
                    $boxTitle
                );
            }
        }
        return false;
    }
References $bearsamppLang, $port, Lang\CHECK_PORT_TITLE, Util\contains(), Util\getHeaders(), Module\getName(), Util\isValidPort(), Util\logDebug(), Util\logError(), Lang\PORT_NOT_USED, Lang\PORT_NOT_USED_BY, and Lang\PORT_USED_BY.
getApiPort()
BinMailhog::getApiPort ()
Gets the API port for the Mailhog service.
Returns
int The API port.
Definition at line 427 of file class.bin.mailhog.php.
    {
        return $this->apiPort;
    }
References $apiPort.
getExe()
BinMailhog::getExe ()
Gets the executable file path for the Mailhog service.
Returns
string The executable file path.
Definition at line 417 of file class.bin.mailhog.php.
    {
        return $this->exe;
    }
References $exe.
getLog()
BinMailhog::getLog ()
Gets the log file path for the Mailhog service.
Returns
string The log file path.
Definition at line 407 of file class.bin.mailhog.php.
    {
        return $this->log;
    }
References $log.
getMailPath()
BinMailhog::getMailPath ()
Gets the mail directory path for the Mailhog service.
This method returns the path to the directory where Mailhog stores its mail data. The path is typically set during the initialization or reloading of the module and is based on the application's root temporary path.
Returns
string The mail directory path.
Definition at line 491 of file class.bin.mailhog.php.
    {
        return $this->mailPath;
    }
References $mailPath.
getService()
BinMailhog::getService ()
Gets the Win32Service object for the Mailhog service.
Returns
Win32Service The Win32Service object.
Definition at line 363 of file class.bin.mailhog.php.
    {
        return $this->service;
    }
References $service.
getSmtpPort()
BinMailhog::getSmtpPort ()
Gets the SMTP port for the Mailhog service.
Returns
int The SMTP port.
Definition at line 467 of file class.bin.mailhog.php.
    {
        return $this->smtpPort;
    }
References $smtpPort.
getUiPort()
BinMailhog::getUiPort ()
Gets the UI port for the Mailhog service.
Returns
int The UI port.
Definition at line 447 of file class.bin.mailhog.php.
    {
        return $this->uiPort;
    }
References $uiPort.
rebuildConf()
BinMailhog::rebuildConf ()
Rebuilds the configuration in the Windows Registry.
Returns
bool True if the configuration was successfully rebuilt, false otherwise.
Definition at line 162 of file class.bin.mailhog.php.
    {
        global $bearsamppRegistry;
        $exists = $bearsamppRegistry->exists(
            Registry::HKEY_LOCAL_MACHINE,
            'SYSTEM\CurrentControlSet\Services\\' . self::SERVICE_NAME . '\Parameters',
            Nssm::INFO_APP_PARAMETERS
        );
        if ( $exists ) {
            return $bearsamppRegistry->setExpandStringValue(
                Registry::HKEY_LOCAL_MACHINE,
                'SYSTEM\CurrentControlSet\Services\\' . self::SERVICE_NAME . '\Parameters',
                Nssm::INFO_APP_PARAMETERS,
                sprintf( self::SERVICE_PARAMS, $this->apiPort, $this->uiPort, $this->smtpPort, $this->mailPath )
            );
        }
        return false;
    }
References Registry\HKEY_LOCAL_MACHINE, and Nssm\INFO_APP_PARAMETERS.
reload()
BinMailhog::reload ($id = null, $type = null)
Reloads the module configuration based on the provided ID and type.
Parameters
string | null $id The ID of the module. If null, the current ID is used.
string | null $type The type of the module. If null, the current type is used.
Reimplemented from Module.
Definition at line 56 of file class.bin.mailhog.php.
    {
        global $bearsamppRoot, $bearsamppConfig, $bearsamppLang;
        Util::logReloadClass( $this );
        $this->name    = $bearsamppLang->getValue( Lang::MAILHOG );
        $this->version = $bearsamppConfig->getRaw( self::ROOT_CFG_VERSION );
        parent::reload( $id, $type );
        $this->enable   = $this->enable && $bearsamppConfig->getRaw( self::ROOT_CFG_ENABLE );
        $this->service  = new Win32Service( self::SERVICE_NAME );
        $this->mailPath = $bearsamppRoot->getTmpPath() . '/mailhog';
        $this->log      = $bearsamppRoot->getLogsPath() . '/mailhog.log';
        if ( $this->bearsamppConfRaw !== false ) {
            $this->exe      = $this->symlinkPath . '/' . $this->bearsamppConfRaw[self::LOCAL_CFG_EXE];
            $this->apiPort  = intval( $this->bearsamppConfRaw[self::LOCAL_CFG_API_PORT] );
            $this->uiPort   = intval( $this->bearsamppConfRaw[self::LOCAL_CFG_UI_PORT] );
            $this->smtpPort = intval( $this->bearsamppConfRaw[self::LOCAL_CFG_SMTP_PORT] );
        }
        if ( !$this->enable ) {
            Util::logInfo( $this->name . ' is not enabled!' );
            return;
        }
        if ( !is_dir( $this->currentPath ) ) {
            Util::logError( sprintf( $bearsamppLang->getValue( Lang::ERROR_FILE_NOT_FOUND ), $this->name . ' ' . $this->version, $this->currentPath ) );
            return;
        }
        if ( !is_dir( $this->symlinkPath ) ) {
            Util::logError( sprintf( $bearsamppLang->getValue( Lang::ERROR_FILE_NOT_FOUND ), $this->name . ' ' . $this->version, $this->symlinkPath ) );
            return;
        }
        if ( !is_file( $this->bearsamppConf ) ) {
            Util::logError( sprintf( $bearsamppLang->getValue( Lang::ERROR_CONF_NOT_FOUND ), $this->name . ' ' . $this->version, $this->bearsamppConf ) );
            return;
        }
        if ( !is_file( $this->exe ) ) {
            Util::logError( sprintf( $bearsamppLang->getValue( Lang::ERROR_EXE_NOT_FOUND ), $this->name . ' ' . $this->version, $this->exe ) );
            return;
        }
        if ( empty( $this->apiPort ) ) {
            Util::logError( sprintf( $bearsamppLang->getValue( Lang::ERROR_INVALID_PARAMETER ), self::LOCAL_CFG_API_PORT, $this->apiPort ) );
            return;
        }
        if ( empty( $this->uiPort ) ) {
            Util::logError( sprintf( $bearsamppLang->getValue( Lang::ERROR_INVALID_PARAMETER ), self::LOCAL_CFG_UI_PORT, $this->uiPort ) );
            return;
        }
        if ( empty( $this->smtpPort ) ) {
            Util::logError( sprintf( $bearsamppLang->getValue( Lang::ERROR_INVALID_PARAMETER ), self::LOCAL_CFG_SMTP_PORT, $this->smtpPort ) );
            return;
        }
        $nssm = new Nssm( self::SERVICE_NAME );
        $nssm->setDisplayName( APP_TITLE . ' ' . $this->getName() );
        $nssm->setBinPath( $this->exe );
        $nssm->setParams( sprintf( self::SERVICE_PARAMS, $this->apiPort, $this->uiPort, $this->smtpPort, $this->mailPath ) );
        $nssm->setStart( Nssm::SERVICE_DEMAND_START );
        $nssm->setStdout( $bearsamppRoot->getLogsPath() . '/mailhog.out.log' );
        $nssm->setStderr( $bearsamppRoot->getLogsPath() . '/mailhog.err.log' );
        $this->service->setNssm( $nssm );
    }
References $bearsamppConfig, $bearsamppLang, $bearsamppRoot, Module\$id, Module\$type, APP_TITLE, Lang\ERROR_CONF_NOT_FOUND, Lang\ERROR_EXE_NOT_FOUND, Lang\ERROR_FILE_NOT_FOUND, Lang\ERROR_INVALID_PARAMETER, Module\getName(), LOCAL_CFG_EXE, Util\logError(), Util\logInfo(), Util\logReloadClass(), Lang\MAILHOG, and Nssm\SERVICE_DEMAND_START.
Referenced by __construct(), setEnable(), and setVersion().
replaceAll()
BinMailhog::replaceAll ($params) protected
Replaces multiple key-value pairs in the configuration file.
Parameters
array $params An associative array of key-value pairs to replace.
Reimplemented from Module.
Definition at line 134 of file class.bin.mailhog.php.
    {
        $content = file_get_contents( $this->bearsamppConf );
        foreach ( $params as $key => $value ) {
            $content                      = preg_replace( '|' . $key . ' = .*|', $key . ' = ' . '"' . $value . '"', $content );
            $this->bearsamppConfRaw[$key] = $value;
            switch ( $key ) {
                case self::LOCAL_CFG_API_PORT:
                    $this->apiPort = intval( $value );
                    break;
                case self::LOCAL_CFG_UI_PORT:
                    $this->uiPort = intval( $value );
                    break;
                case self::LOCAL_CFG_SMTP_PORT:
                    $this->smtpPort = intval( $value );
                    break;
            }
        }
        file_put_contents( $this->bearsamppConf, $content );
    }
References LOCAL_CFG_API_PORT, LOCAL_CFG_SMTP_PORT, and LOCAL_CFG_UI_PORT.
setApiPort()
BinMailhog::setApiPort ($apiPort)
Sets the API port for the Mailhog service.
Parameters
int $apiPort The new API port.
Definition at line 437 of file class.bin.mailhog.php.
    {
        $this->replace( self::LOCAL_CFG_API_PORT, $apiPort );
    }
References $apiPort, and Module\replace().
setEnable()
BinMailhog::setEnable ($enabled, $showWindow = false)
Enables or disables the Mailhog service.
Parameters
bool $enabled Whether to enable or disable the service.
bool $showWindow Whether to show a message box with the result.
Definition at line 374 of file class.bin.mailhog.php.
    {
        global $bearsamppConfig, $bearsamppLang, $bearsamppWinbinder;
        if ( $enabled == Config::ENABLED && !is_dir( $this->currentPath ) ) {
            Util::logDebug( $this->getName() . ' cannot be enabled because bundle ' . $this->getVersion() . ' does not exist in ' . $this->currentPath );
            if ( $showWindow ) {
                $bearsamppWinbinder->messageBoxError(
                    sprintf( $bearsamppLang->getValue( Lang::ENABLE_BUNDLE_NOT_EXIST ), $this->getName(), $this->getVersion(), $this->currentPath ),
                    sprintf( $bearsamppLang->getValue( Lang::ENABLE_TITLE ), $this->getName() )
                );
            }
            $enabled = Config::DISABLED;
        }
        Util::logInfo( $this->getName() . ' switched to ' . ($enabled == Config::ENABLED ? 'enabled' : 'disabled') );
        $this->enable = $enabled == Config::ENABLED;
        $bearsamppConfig->replace( self::ROOT_CFG_ENABLE, $enabled );
        $this->reload();
        if ( $this->enable ) {
            Util::installService( $this, $this->smtpPort, null, $showWindow );
        }
        else {
            Util::removeService( $this->service, $this->name );
        }
    }
References $bearsamppConfig, $bearsamppLang, Config\DISABLED, Lang\ENABLE_BUNDLE_NOT_EXIST, Lang\ENABLE_TITLE, Config\ENABLED, Module\getName(), Module\getVersion(), Util\installService(), Util\logDebug(), Util\logInfo(), reload(), and Util\removeService().
setSmtpPort()
BinMailhog::setSmtpPort ($smtpPort)
Sets the SMTP port for the Mailhog service.
Parameters
int $smtpPort The new SMTP port.
Definition at line 477 of file class.bin.mailhog.php.
    {
        $this->replace( self::LOCAL_CFG_SMTP_PORT, $smtpPort );
    }
References $smtpPort, and Module\replace().
Referenced by changePort().
setUiPort()
BinMailhog::setUiPort ($uiPort)
Sets the UI port for the Mailhog service.
Parameters
int $uiPort The new UI port.
Definition at line 457 of file class.bin.mailhog.php.
    {
        $this->replace( self::LOCAL_CFG_UI_PORT, $uiPort );
    }
References $uiPort, and Module\replace().
setVersion()
BinMailhog::setVersion ($version)
Sets the version of the Mailhog service.
Parameters
string $version The version to set.
Reimplemented from Module.
Definition at line 350 of file class.bin.mailhog.php.
    {
        global $bearsamppConfig;
        $this->version = $version;
        $bearsamppConfig->replace( self::ROOT_CFG_VERSION, $version );
        $this->reload();
    }
References $bearsamppConfig, Module\$version, and reload().
Referenced by updateConfig().
switchVersion()
BinMailhog::switchVersion ($version, $showWindow = false)
Switches the version of the Mailhog service.
Parameters
string $version The version to switch to.
bool $showWindow Whether to show a message box with the result.
Returns
bool True if the version was successfully switched, false otherwise.
Definition at line 284 of file class.bin.mailhog.php.
    {
        Util::logDebug( 'Switch ' . $this->name . ' version to ' . $version );
        return $this->updateConfig( $version, 0, $showWindow );
    }
References Module\$version, Util\logDebug(), and updateConfig().
updateConfig()
BinMailhog::updateConfig ($version = null, $sub = 0, $showWindow = false) protected
Updates the configuration of the Mailhog service.
Parameters
string | null $version The version to update to. If null, the current version is used.
int $sub The sub-level for logging indentation.
bool $showWindow Whether to show a message box with the result.
Returns
bool True if the configuration was successfully updated, false otherwise.
Reimplemented from Module.
Definition at line 300 of file class.bin.mailhog.php.
    {
        global $bearsamppLang, $bearsamppWinbinder;
        if ( !$this->enable ) {
            return true;
        }
        $version = $version == null ? $this->version : $version;
        Util::logDebug( ($sub > 0 ? str_repeat( ' ', 2 * $sub ) : '') . 'Update ' . $this->name . ' ' . $version . ' config' );
        $boxTitle = sprintf( $bearsamppLang->getValue( Lang::SWITCH_VERSION_TITLE ), $this->getName(), $version );
        $bearsamppConf = str_replace( 'mailhog' . $this->getVersion(), 'mailhog' . $version, $this->bearsamppConf );
        if ( !file_exists( $bearsamppConf ) ) {
            Util::logError( 'bearsampp config files not found for ' . $this->getName() . ' ' . $version );
            if ( $showWindow ) {
                $bearsamppWinbinder->messageBoxError(
                    sprintf( $bearsamppLang->getValue( Lang::BEARSAMPP_CONF_NOT_FOUND_ERROR ), $this->getName() . ' ' . $version ),
                    $boxTitle
                );
            }
            return false;
        }
        $bearsamppConfRaw = parse_ini_file( $bearsamppConf );
        if ( $bearsamppConfRaw === false || !isset( $bearsamppConfRaw[self::ROOT_CFG_VERSION] ) || $bearsamppConfRaw[self::ROOT_CFG_VERSION] != $version ) {
            Util::logError( 'bearsampp config file malformed for ' . $this->getName() . ' ' . $version );
            if ( $showWindow ) {
                $bearsamppWinbinder->messageBoxError(
                    sprintf( $bearsamppLang->getValue( Lang::BEARSAMPP_CONF_MALFORMED_ERROR ), $this->getName() . ' ' . $version ),
                    $boxTitle
                );
            }
            return false;
        }
        // bearsampp.conf
        $this->setVersion( $version );
        return true;
    }
References Module\$bearsamppConf, Module\$bearsamppConfRaw, $bearsamppLang, Module\$version, Lang\BEARSAMPP_CONF_MALFORMED_ERROR, Lang\BEARSAMPP_CONF_NOT_FOUND_ERROR, Module\getName(), Module\getVersion(), Util\logDebug(), Util\logError(), setVersion(), and Lang\SWITCH_VERSION_TITLE.
Referenced by switchVersion().
Field Documentation
$apiPort
BinMailhog::$apiPort private
Definition at line 33 of file class.bin.mailhog.php.
Referenced by getApiPort(), and setApiPort().
$exe
BinMailhog::$exe private
Definition at line 32 of file class.bin.mailhog.php.
Referenced by getExe().
$log
BinMailhog::$log private
Definition at line 30 of file class.bin.mailhog.php.
Referenced by getLog().
$mailPath
BinMailhog::$mailPath private
Definition at line 36 of file class.bin.mailhog.php.
Referenced by getMailPath().
$service
BinMailhog::$service private
Definition at line 29 of file class.bin.mailhog.php.
Referenced by getService().
$smtpPort
BinMailhog::$smtpPort private
Definition at line 35 of file class.bin.mailhog.php.
Referenced by getSmtpPort(), and setSmtpPort().
$uiPort
BinMailhog::$uiPort private
Definition at line 34 of file class.bin.mailhog.php.
Referenced by getUiPort(), and setUiPort().
LOCAL_CFG_API_PORT
const BinMailhog::LOCAL_CFG_API_PORT = 'mailhogApiPort'
Definition at line 25 of file class.bin.mailhog.php.
Referenced by replaceAll().
LOCAL_CFG_EXE
const BinMailhog::LOCAL_CFG_EXE = 'mailhogExe'
Definition at line 24 of file class.bin.mailhog.php.
Referenced by reload().
LOCAL_CFG_SMTP_PORT
const BinMailhog::LOCAL_CFG_SMTP_PORT = 'mailhogSmtpPort'
Definition at line 27 of file class.bin.mailhog.php.
Referenced by replaceAll().
LOCAL_CFG_UI_PORT
const BinMailhog::LOCAL_CFG_UI_PORT = 'mailhogUiPort'
Definition at line 26 of file class.bin.mailhog.php.
Referenced by replaceAll().
ROOT_CFG_ENABLE
const BinMailhog::ROOT_CFG_ENABLE = 'mailhogEnable'
Definition at line 21 of file class.bin.mailhog.php.
ROOT_CFG_VERSION
const BinMailhog::ROOT_CFG_VERSION = 'mailhogVersion'
Definition at line 22 of file class.bin.mailhog.php.
SERVICE_NAME
const BinMailhog::SERVICE_NAME = 'bearsamppmailhog'
Definition at line 18 of file class.bin.mailhog.php.
Referenced by ActionService\__construct(), TplAppMailhog\getActionInstallMailhogService(), TplAppMailhog\getActionRemoveMailhogService(), Bins\getServices(), ActionStartup\installServices(), ActionQuit\processWindow(), and Win32Service\start().
SERVICE_PARAMS
const BinMailhog::SERVICE_PARAMS = '-hostname localhost -api-bind-addr 127.0.0.1:%d -ui-bind-addr 127.0.0.1:%d -smtp-bind-addr 127.0.0.1:%d -storage maildir -maildir-path "%s"'
Definition at line 19 of file class.bin.mailhog.php.
The documentation for this class was generated from the following file:
E:/Bearsampp-development/sandbox/core/classes/bins/class.bin.mailhog.php