My Project: ActionSwitchOnline Class Reference
ActionSwitchOnline Class Reference
Public Member Functions
__construct ($args)
Private Member Functions
switchAlias ($putOnline)
switchApache ($putOnline)
switchFilezilla ($putOnline)
switchVhosts ($putOnline)
Detailed Description
Class ActionSwitchOnline Handles the switching of the application between online and offline modes.
Definition at line 14 of file class.action.switchOnline.php.
Constructor & Destructor Documentation
__construct()
ActionSwitchOnline::__construct ($args)
ActionSwitchOnline constructor. Initializes the online/offline switch based on the provided arguments.
Parameters
array $args Arguments to determine the online/offline state.
Definition at line 22 of file class.action.switchOnline.php.
    {
        global $bearsamppConfig;
        if (isset($args[0]) && $args[0] == Config::ENABLED || $args[0] == Config::DISABLED) {
            Util::startLoading();
            $putOnline = $args[0] == Config::ENABLED;
            $this->switchApache($putOnline);
            $this->switchAlias($putOnline);
            $this->switchVhosts($putOnline);
            $this->switchFilezilla($putOnline);
            $bearsamppConfig->replace(Config::CFG_ONLINE, $args[0]);
        }
    }
References $bearsamppConfig, Config\CFG_ONLINE, Config\DISABLED, Config\ENABLED, Util\startLoading(), switchAlias(), switchApache(), switchFilezilla(), and switchVhosts().
Member Function Documentation
switchAlias()
ActionSwitchOnline::switchAlias ($putOnline) private
Switches the Apache aliases based on the online/offline state.
Parameters
bool $putOnline True to put online, false to put offline.
Definition at line 54 of file class.action.switchOnline.php.
    {
        global $bearsamppBins;
        $bearsamppBins->getApache()->refreshAlias($putOnline);
    }
References $bearsamppBins.
Referenced by __construct().
switchApache()
ActionSwitchOnline::switchApache ($putOnline) private
Switches the Apache configuration based on the online/offline state.
Parameters
bool $putOnline True to put online, false to put offline.
Definition at line 43 of file class.action.switchOnline.php.
    {
        global $bearsamppBins;
        $bearsamppBins->getApache()->refreshConf($putOnline);
    }
References $bearsamppBins.
Referenced by __construct().
switchFilezilla()
ActionSwitchOnline::switchFilezilla ($putOnline) private
Switches the Filezilla configuration based on the online/offline state.
Parameters
bool $putOnline True to put online, false to put offline.
Definition at line 76 of file class.action.switchOnline.php.
    {
        global $bearsamppBins;
        if ($putOnline) {
            $bearsamppBins->getFilezilla()->setConf(array(
                BinFilezilla::CFG_IP_FILTER_ALLOWED => '*',
                BinFilezilla::CFG_IP_FILTER_DISALLOWED => '',
            ));
        } else {
            $bearsamppBins->getFilezilla()->setConf(array(
                BinFilezilla::CFG_IP_FILTER_ALLOWED => '127.0.0.1 ::1',
                BinFilezilla::CFG_IP_FILTER_DISALLOWED => '*',
            ));
        }
    }
References $bearsamppBins, BinFilezilla\CFG_IP_FILTER_ALLOWED, and BinFilezilla\CFG_IP_FILTER_DISALLOWED.
Referenced by __construct().
switchVhosts()
ActionSwitchOnline::switchVhosts ($putOnline) private
Switches the Apache virtual hosts based on the online/offline state.
Parameters
bool $putOnline True to put online, false to put offline.
Definition at line 65 of file class.action.switchOnline.php.
    {
        global $bearsamppBins;
        $bearsamppBins->getApache()->refreshVhosts($putOnline);
    }
References $bearsamppBins.
Referenced by __construct().
The documentation for this class was generated from the following file:
E:/Bearsampp-development/sandbox/core/classes/actions/class.action.switchOnline.php