group:
  # Bearsampp repo unique things
  - files:
      - source: core/
        dest: core/
        exclude: |
            /homepage/img/about.bmp
            /homepage/img/bearsampp.bmp
            /homepage/img/icons/app.ico
            /homepage/img/icons/favicon.ico
            /homepage/img/header-logo.png
        deleteOrphaned: true
      - source: LICENSE
        dest: LICENSE
      - source: bar.dat
        dest: bar.dat
      - source: README.md
        dest: README.md
      - source: nssmEnvPaths.dat
        dest: nssmEnvPaths.dat
      - source: sprites.dat
        dest: sprites.dat
      - source: bearsampp.conf
        dest: base/bearsampp.conf
    repos: |
        Bearsampp/Bearsampp
