group:
          # Sync to Bearsampp
    - files:
          - source: core
            dest: core
          - source: /bearsampp.exe
            dest: /bearsampp.exe
      repos: |
          Bearsampp/Bearsampp
