Bearsampp: BinMysql Class Reference
BinMysql Class Reference
Public Member Functions
__construct ($id, $type)
changePort ($port, $checkUsed=false, $wbProgressBar=null)
changeRootPassword ($currentPwd, $newPwd, $wbProgressBar=null)
checkPort ($port, $showWindow=false)
checkRootPassword ($currentPwd=null, $wbProgressBar=null)
getAdmin ()
getCliExe ()
getCmdLineOutput ($cmd)
getConf ()
getErrorLog ()
getExe ()
getPort ()
getRootPwd ()
getRootUser ()
getService ()
initData ($path=null, $version=null)
reload ($id=null, $type=null)
setEnable ($enabled, $showWindow=false)
setPort ($port)
setRootPwd ($rootPwd)
setRootUser ($rootUser)
setVersion ($version)
switchVersion ($version, $showWindow=false)
Public Member Functions inherited from Module
__toString ()
getCurrentPath ()
getId ()
getName ()
getRelease ()
getRootPath ()
getSymlinkPath ()
getType ()
getVersion ()
getVersionList ()
isEnable ()
update ($sub=0, $showWindow=false)
Data Fields
const CMD_SYNTAX_CHECK = '--help --verbose 1>NUL'
const CMD_VARIABLES = 'variables'
const CMD_VERSION = '--version'
const LOCAL_CFG_ADMIN = 'mysqlAdmin'
const LOCAL_CFG_CLI_EXE = 'mysqlCliExe'
const LOCAL_CFG_CONF = 'mysqlConf'
const LOCAL_CFG_EXE = 'mysqlExe'
const LOCAL_CFG_PORT = 'mysqlPort'
const LOCAL_CFG_ROOT_PWD = 'mysqlRootPwd'
const LOCAL_CFG_ROOT_USER = 'mysqlRootUser'
const ROOT_CFG_ENABLE = 'mysqlEnable'
const ROOT_CFG_VERSION = 'mysqlVersion'
const SERVICE_NAME = 'bearsamppmysql'
Data Fields inherited from Module
const BUNDLE_RELEASE = 'bundleRelease'
Protected Member Functions
replaceAll ($params)
updateConfig ($version=null, $sub=0, $showWindow=false)
Protected Member Functions inherited from Module
__construct ()
replace ($key, $value)
Private Attributes
$admin
$cliExe
$conf
$errorLog
$exe
$port
$rootPwd
$rootUser
$service
Additional Inherited Members
Protected Attributes inherited from Module
$bearsamppConf
$bearsamppConfRaw
$currentPath
$enable
$name
$release = 'N/A'
$rootPath
$symlinkPath
$version
Detailed Description
Class BinMysql
This class represents the MySQL binary module in the Bearsampp application. It handles the configuration, management, and operations related to MySQL.
Definition at line 16 of file class.bin.mysql.php.
Constructor & Destructor Documentation
__construct()
BinMysql::__construct ($id, $type)
Constructs a BinMysql object and initializes the MySQL module.
Parameters
string $id The ID of the module.
string $type The type of the module.
Definition at line 52 of file class.bin.mysql.php.
    {
        Util::logInitClass( $this );
        $this->reload( $id, $type );
    }
References Module\$id, Module\$type, Util\logInitClass(), and reload().
Member Function Documentation
changePort()
BinMysql::changePort ($port, $checkUsed = false, $wbProgressBar = null)
Changes the MySQL port and updates the configuration.
Parameters
int $port The new port number.
bool $checkUsed Whether to check if the port is already in use.
mixed $wbProgressBar The progress bar object for UI updates.
Returns
bool|string True if the port was changed successfully, or an error message if the port is in use.
Definition at line 182 of file class.bin.mysql.php.
    {
        global $bearsamppWinbinder;
        if ( !Util::isValidPort( $port ) ) {
            Util::logError( $this->getName() . ' port not valid: ' . $port );
            return false;
        }
        $port = intval( $port );
        $bearsamppWinbinder->incrProgressBar( $wbProgressBar );
        $isPortInUse = Util::isPortInUse( $port );
        if ( !$checkUsed || $isPortInUse === false ) {
            // bearsampp.conf
            $this->setPort( $port );
            $bearsamppWinbinder->incrProgressBar( $wbProgressBar );
            // conf
            $this->update();
            $bearsamppWinbinder->incrProgressBar( $wbProgressBar );
            return true;
        }
        Util::logDebug( $this->getName() . ' port in used: ' . $port . ' - ' . $isPortInUse );
        return $isPortInUse;
    }
References $port, Module\getName(), Util\isPortInUse(), Util\isValidPort(), Util\logDebug(), Util\logError(), setPort(), and Module\update().
changeRootPassword()
BinMysql::changeRootPassword ($currentPwd, $newPwd, $wbProgressBar = null)
Changes the MySQL root password.
Parameters
string $currentPwd The current root password.
string $newPwd The new root password.
mixed $wbProgressBar The progress bar object for UI updates.
Returns
bool|string True if the password was changed successfully, or an error message if the operation failed.
Definition at line 313 of file class.bin.mysql.php.
    {
        global $bearsamppWinbinder;
        $error = null;
        $bearsamppWinbinder->incrProgressBar( $wbProgressBar );
        if ( version_compare( phpversion(), '5.3' ) === -1 ) {
            $dbLink = @mysqli_connect( '127.0.0.1', $this->rootUser, $currentPwd, '', $this->port );
        }
        else {
            $dbLink = @mysqli_connect( '127.0.0.1:' . $this->port, $this->rootUser, $currentPwd );
        }
        if ( !$dbLink ) {
            $error = mysqli_connect_error();
        }
        $bearsamppWinbinder->incrProgressBar( $wbProgressBar );
        $stmt = @mysqli_prepare( $dbLink, 'UPDATE mysql.user SET Password=PASSWORD(?) WHERE User=?' );
        if ( empty( $error ) && $stmt === false ) {
            $error = mysqli_error( $dbLink );
        }
        $bearsamppWinbinder->incrProgressBar( $wbProgressBar );
        if ( empty( $error ) && !@mysqli_stmt_bind_param( $stmt, 'ss', $newPwd, $this->rootUser ) ) {
            $error = mysqli_stmt_error( $stmt );
        }
        $bearsamppWinbinder->incrProgressBar( $wbProgressBar );
        if ( empty( $error ) && !@mysqli_stmt_execute( $stmt ) ) {
            $error = mysqli_stmt_error( $stmt );
        }
        $bearsamppWinbinder->incrProgressBar( $wbProgressBar );
        if ( $stmt !== false ) {
            mysqli_stmt_close( $stmt );
        }
        $bearsamppWinbinder->incrProgressBar( $wbProgressBar );
        if ( empty( $error ) && @mysqli_query( $dbLink, 'FLUSH PRIVILEGES' ) === false ) {
            $error = mysqli_error( $dbLink );
        }
        $bearsamppWinbinder->incrProgressBar( $wbProgressBar );
        if ( $dbLink ) {
            mysqli_close( $dbLink );
        }
        if ( !empty( $error ) ) {
            return $error;
        }
        // bearsampp.conf
        $bearsamppWinbinder->incrProgressBar( $wbProgressBar );
        $this->setRootPwd( $newPwd );
        // conf
        $this->update();
        $bearsamppWinbinder->incrProgressBar( $wbProgressBar );
        return true;
    }
References setRootPwd(), and Module\update().
checkPort()
BinMysql::checkPort ($port, $showWindow = false)
Checks if the specified port is in use by MySQL.
Parameters
int $port The port number to check.
bool $showWindow Whether to show a message box with the result.
Returns
bool True if the port is in use by MySQL, false otherwise.
Definition at line 221 of file class.bin.mysql.php.
    {
        global $bearsamppLang, $bearsamppWinbinder;
        $boxTitle = sprintf( $bearsamppLang->getValue( Lang::CHECK_PORT_TITLE ), $this->getName(), $port );
        if ( !Util::isValidPort( $port ) ) {
            Util::logError( $this->getName() . ' port not valid: ' . $port );
            return false;
        }
        $fp = @fsockopen( '127.0.0.1', $port, $errno, $errstr, 5 );
        if ( $fp ) {
            if ( version_compare( phpversion(), '5.3' ) === -1 ) {
                $dbLink = mysqli_connect( '127.0.0.1', $this->rootUser, $this->rootPwd, '', $port );
            }
            else {
                $dbLink = mysqli_connect( '127.0.0.1:' . $port, $this->rootUser, $this->rootPwd );
            }
            $isMysql = false;
            $version = false;
            if ( $dbLink ) {
                $result = mysqli_query( $dbLink, 'SHOW VARIABLES' );
                if ( $result ) {
                    while ( false !== ($row = mysqli_fetch_array( $result, MYSQLI_NUM )) ) {
                        if ( $row[0] == 'version' ) {
                            $version = explode( '-', $row[1] );
                            $version = count( $version ) > 1 ? $version[0] : $row[1];
                        }
                        if ( $row[0] == 'version_comment' && Util::startWith( strtolower( $row[1] ), 'mysql' ) ) {
                            $isMysql = true;
                        }
                        if ( $isMysql && $version !== false ) {
                            break;
                        }
                    }
                    if ( !$isMysql ) {
                        Util::logDebug( $this->getName() . ' port used by another DBMS: ' . $port );
                        if ( $showWindow ) {
                            $bearsamppWinbinder->messageBoxWarning(
                                sprintf( $bearsamppLang->getValue( Lang::PORT_USED_BY_ANOTHER_DBMS ), $port ),
                                $boxTitle
                            );
                        }
                    }
                    else {
                        Util::logDebug( $this->getName() . ' port ' . $port . ' is used by: ' . $this->getName() . ' ' . $version );
                        if ( $showWindow ) {
                            $bearsamppWinbinder->messageBoxInfo(
                                sprintf( $bearsamppLang->getValue( Lang::PORT_USED_BY ), $port, $this->getName() . ' ' . $version ),
                                $boxTitle
                            );
                        }
                        return true;
                    }
                }
                mysqli_close( $dbLink );
            }
            else {
                Util::logDebug( $this->getName() . ' port ' . $port . ' is used by another application' );
                if ( $showWindow ) {
                    $bearsamppWinbinder->messageBoxWarning(
                        sprintf( $bearsamppLang->getValue( Lang::PORT_NOT_USED_BY ), $port ),
                        $boxTitle
                    );
                }
            }
        }
        else {
            Util::logDebug( $this->getName() . ' port ' . $port . ' is not used' );
            if ( $showWindow ) {
                $bearsamppWinbinder->messageBoxError(
                    sprintf( $bearsamppLang->getValue( Lang::PORT_NOT_USED ), $port ),
                    $boxTitle
                );
            }
        }
        return false;
    }
References $bearsamppLang, $port, $result, Module\$version, Lang\CHECK_PORT_TITLE, Module\getName(), Util\isValidPort(), Util\logDebug(), Util\logError(), Lang\PORT_NOT_USED, Lang\PORT_NOT_USED_BY, Lang\PORT_USED_BY, Lang\PORT_USED_BY_ANOTHER_DBMS, and Util\startWith().
checkRootPassword()
BinMysql::checkRootPassword ($currentPwd = null, $wbProgressBar = null)
Checks if the provided root password is correct.
Parameters
string | null $currentPwd The current root password. If null, the stored root password is used.
mixed $wbProgressBar The progress bar object for UI updates.
Returns
bool|string True if the password is correct, or an error message if the operation failed.
Definition at line 383 of file class.bin.mysql.php.
    {
        global $bearsamppWinbinder;
        $currentPwd = $currentPwd == null ? $this->rootPwd : $currentPwd;
        $error      = null;
        $bearsamppWinbinder->incrProgressBar( $wbProgressBar );
        if ( version_compare( phpversion(), '5.3' ) === -1 ) {
            $dbLink = @mysqli_connect( '127.0.0.1', $this->rootUser, $currentPwd, '', $this->port );
        }
        else {
            $dbLink = @mysqli_connect( '127.0.0.1:' . $this->port, $this->rootUser, $currentPwd );
        }
        if ( !$dbLink ) {
            $error = mysqli_connect_error();
        }
        $bearsamppWinbinder->incrProgressBar( $wbProgressBar );
        if ( $dbLink ) {
            mysqli_close( $dbLink );
        }
        if ( !empty( $error ) ) {
            return $error;
        }
        return true;
    }
getAdmin()
BinMysql::getAdmin ()
Retrieves the path to the MySQL admin executable.
Returns
string The path to the admin executable.
Definition at line 729 of file class.bin.mysql.php.
    {
        return $this->admin;
    }
References $admin.
Referenced by getCmdLineOutput().
getCliExe()
BinMysql::getCliExe ()
Retrieves the path to the MySQL CLI executable.
Returns
string The path to the CLI executable.
Definition at line 719 of file class.bin.mysql.php.
    {
        return $this->cliExe;
    }
References $cliExe.
getCmdLineOutput()
BinMysql::getCmdLineOutput ($cmd)
Executes a MySQL command and retrieves the output.
Parameters
string $cmd The command to execute.
Returns
array An associative array containing 'syntaxOk' (boolean) and 'content' (string|null).
Definition at line 531 of file class.bin.mysql.php.
    {
        $result = array(
            'syntaxOk' => false,
            'content'  => null,
        );
        $bin         = $this->getExe();
        $removeLines = 0;
        $outputFrom  = '';
        if ( $cmd == self::CMD_SYNTAX_CHECK ) {
            $outputFrom = '2';
        }
        elseif ( $cmd == self::CMD_VARIABLES ) {
            $bin = $this->getAdmin();
            $cmd .= ' --user=' . $this->getRootUser();
            if ( $this->getRootPwd() ) {
                $cmd .= ' --password=' . $this->getRootPwd();
            }
            $removeLines = 2;
        }
        if ( file_exists( $bin ) ) {
            $tmpResult = Batch::exec( 'mysqlGetCmdLineOutput', '"' . $bin . '" ' . $cmd . ' ' . $outputFrom, 5 );
            if ( $tmpResult !== false && is_array( $tmpResult ) ) {
                $result['syntaxOk'] = empty( $tmpResult ) || !Util::contains( trim( $tmpResult[count( $tmpResult ) - 1] ), '[ERROR]' );
                for ( $i = 0; $i < $removeLines; $i++ ) {
                    unset( $tmpResult[$i] );
                }
                $result['content'] = trim( str_replace( $bin, '', implode( PHP_EOL, $tmpResult ) ) );
            }
        }
        return $result;
    }
References $result, Util\contains(), Batch\exec(), getAdmin(), getExe(), getRootPwd(), and getRootUser().
getConf()
BinMysql::getConf ()
Retrieves the path to the MySQL configuration file.
Returns
string The path to the configuration file.
Definition at line 649 of file class.bin.mysql.php.
    {
        return $this->conf;
    }
References $conf.
Referenced by updateConfig().
getErrorLog()
BinMysql::getErrorLog ()
Retrieves the path to the MySQL error log.
Returns
string The path to the error log.
Definition at line 629 of file class.bin.mysql.php.
    {
        return $this->errorLog;
    }
References $errorLog.
getExe()
BinMysql::getExe ()
Retrieves the path to the MySQL executable.
Returns
string The path to the MySQL executable.
Definition at line 639 of file class.bin.mysql.php.
    {
        return $this->exe;
    }
References $exe.
Referenced by getCmdLineOutput().
getPort()
BinMysql::getPort ()
Retrieves the MySQL port number.
Returns
int The port number.
Definition at line 659 of file class.bin.mysql.php.
    {
        return $this->port;
    }
References $port.
getRootPwd()
BinMysql::getRootPwd ()
Retrieves the MySQL root password.
Returns
string The root password.
Definition at line 699 of file class.bin.mysql.php.
    {
        return $this->rootPwd;
    }
References $rootPwd.
Referenced by getCmdLineOutput().
getRootUser()
BinMysql::getRootUser ()
Retrieves the MySQL root username.
Returns
string The root username.
Definition at line 679 of file class.bin.mysql.php.
    {
        return $this->rootUser;
    }
References $rootUser.
Referenced by getCmdLineOutput().
getService()
BinMysql::getService ()
Retrieves the MySQL service object.
Returns
Win32Service The MySQL service object.
Definition at line 585 of file class.bin.mysql.php.
    {
        return $this->service;
    }
References $service.
initData()
BinMysql::initData ($path = null, $version = null)
Initializes the MySQL data directory if it does not exist.
Parameters
string | null $path The path to the MySQL installation. If null, the current path is used.
string | null $version The version of MySQL. If null, the current version is used.
Definition at line 508 of file class.bin.mysql.php.
    {
        $path    = $path != null ? $path : $this->getCurrentPath();
        $version = $version != null ? $version : $this->getVersion();
        if ( version_compare( $version, '5.7.0', '<' ) ) {
            return;
        }
        if ( file_exists( $path . '/data' ) ) {
            return;
        }
        Batch::initializeMysql( $path );
    }
References Module\$version, Module\getCurrentPath(), Module\getVersion(), and Batch\initializeMysql().
Referenced by updateConfig().
reload()
BinMysql::reload ($id = null, $type = null)
Reloads the MySQL module configuration based on the provided ID and type.
Parameters
string | null $id The ID of the module. If null, the current ID is used.
string | null $type The type of the module. If null, the current type is used.
Reimplemented from Module.
Definition at line 64 of file class.bin.mysql.php.
    {
        global $bearsamppRoot, $bearsamppConfig, $bearsamppLang;
        Util::logReloadClass( $this );
        $this->name    = $bearsamppLang->getValue( Lang::MYSQL );
        $this->version = $bearsamppConfig->getRaw( self::ROOT_CFG_VERSION );
        parent::reload( $id, $type );
        $this->enable   = $this->enable && $bearsamppConfig->getRaw( self::ROOT_CFG_ENABLE );
        $this->service  = new Win32Service( self::SERVICE_NAME );
        $this->errorLog = $bearsamppRoot->getLogsPath() . '/mysql.log';
        if ( $this->bearsamppConfRaw !== false ) {
            $this->exe      = $this->symlinkPath . '/' . $this->bearsamppConfRaw[self::LOCAL_CFG_EXE];
            $this->conf     = $this->symlinkPath . '/' . $this->bearsamppConfRaw[self::LOCAL_CFG_CONF];
            $this->port     = $this->bearsamppConfRaw[self::LOCAL_CFG_PORT];
            $this->rootUser = isset( $this->bearsamppConfRaw[self::LOCAL_CFG_ROOT_USER] ) ? $this->bearsamppConfRaw[self::LOCAL_CFG_ROOT_USER] : 'root';
            $this->rootPwd  = isset( $this->bearsamppConfRaw[self::LOCAL_CFG_ROOT_PWD] ) ? $this->bearsamppConfRaw[self::LOCAL_CFG_ROOT_PWD] : '';
            $this->cliExe   = $this->symlinkPath . '/' . $this->bearsamppConfRaw[self::LOCAL_CFG_CLI_EXE];
            $this->admin    = $this->symlinkPath . '/' . $this->bearsamppConfRaw[self::LOCAL_CFG_ADMIN];
        }
        if ( !$this->enable ) {
            Util::logInfo( $this->name . ' is not enabled!' );
            return;
        }
        if ( !is_dir( $this->currentPath ) ) {
            Util::logError( sprintf( $bearsamppLang->getValue( Lang::ERROR_FILE_NOT_FOUND ), $this->name . ' ' . $this->version, $this->currentPath ) );
            return;
        }
        if ( !is_dir( $this->symlinkPath ) ) {
            Util::logError( sprintf( $bearsamppLang->getValue( Lang::ERROR_FILE_NOT_FOUND ), $this->name . ' ' . $this->version, $this->symlinkPath ) );
            return;
        }
        if ( !is_file( $this->bearsamppConf ) ) {
            Util::logError( sprintf( $bearsamppLang->getValue( Lang::ERROR_CONF_NOT_FOUND ), $this->name . ' ' . $this->version, $this->bearsamppConf ) );
            return;
        }
        if ( !is_file( $this->exe ) ) {
            Util::logError( sprintf( $bearsamppLang->getValue( Lang::ERROR_EXE_NOT_FOUND ), $this->name . ' ' . $this->version, $this->exe ) );
            return;
        }
        if ( !is_file( $this->conf ) ) {
            Util::logError( sprintf( $bearsamppLang->getValue( Lang::ERROR_CONF_NOT_FOUND ), $this->name . ' ' . $this->version, $this->conf ) );
            return;
        }
        if ( !is_numeric( $this->port ) || $this->port <= 0 ) {
            Util::logError( sprintf( $bearsamppLang->getValue( Lang::ERROR_INVALID_PARAMETER ), self::LOCAL_CFG_PORT, $this->port ) );
            return;
        }
        if ( empty( $this->rootUser ) ) {
            Util::logError( sprintf( $bearsamppLang->getValue( Lang::ERROR_INVALID_PARAMETER ), self::LOCAL_CFG_ROOT_USER, $this->rootUser ) );
            return;
        }
        if ( !is_file( $this->cliExe ) ) {
            Util::logError( sprintf( $bearsamppLang->getValue( Lang::ERROR_EXE_NOT_FOUND ), $this->name . ' ' . $this->version, $this->cliExe ) );
            return;
        }
        if ( !is_file( $this->admin ) ) {
            Util::logError( sprintf( $bearsamppLang->getValue( Lang::ERROR_EXE_NOT_FOUND ), $this->name . ' ' . $this->version, $this->admin ) );
            return;
        }
        $this->service->setDisplayName( APP_TITLE . ' ' . $this->getName() );
        $this->service->setBinPath( $this->exe );
        $this->service->setParams( self::SERVICE_NAME );
        $this->service->setStartType( Win32Service::SERVICE_DEMAND_START );
        $this->service->setErrorControl( Win32Service::SERVER_ERROR_NORMAL );
    }
References $bearsamppConfig, $bearsamppLang, $bearsamppRoot, Module\$id, Module\$type, APP_TITLE, Lang\ERROR_CONF_NOT_FOUND, Lang\ERROR_EXE_NOT_FOUND, Lang\ERROR_FILE_NOT_FOUND, Lang\ERROR_INVALID_PARAMETER, Module\getName(), LOCAL_CFG_ADMIN, LOCAL_CFG_CLI_EXE, LOCAL_CFG_CONF, LOCAL_CFG_EXE, LOCAL_CFG_PORT, LOCAL_CFG_ROOT_PWD, LOCAL_CFG_ROOT_USER, Util\logError(), Util\logInfo(), Util\logReloadClass(), Lang\MYSQL, Win32Service\SERVER_ERROR_NORMAL, and Win32Service\SERVICE_DEMAND_START.
Referenced by __construct(), setEnable(), and setVersion().
replaceAll()
BinMysql::replaceAll ($params) protected
Replaces multiple key-value pairs in the configuration file.
Parameters
array $params An associative array of key-value pairs to replace.
Reimplemented from Module.
Definition at line 150 of file class.bin.mysql.php.
    {
        $content = file_get_contents( $this->bearsamppConf );
        foreach ( $params as $key => $value ) {
            $content                      = preg_replace( '|' . $key . ' = .*|', $key . ' = ' . '"' . $value . '"', $content );
            $this->bearsamppConfRaw[$key] = $value;
            switch ( $key ) {
                case self::LOCAL_CFG_PORT:
                    $this->port = $value;
                    break;
                case self::LOCAL_CFG_ROOT_USER:
                    $this->rootUser = $value;
                    break;
                case self::LOCAL_CFG_ROOT_PWD:
                    $this->rootPwd = $value;
                    break;
            }
        }
        file_put_contents( $this->bearsamppConf, $content );
    }
References LOCAL_CFG_PORT, LOCAL_CFG_ROOT_PWD, and LOCAL_CFG_ROOT_USER.
setEnable()
BinMysql::setEnable ($enabled, $showWindow = false)
Enables or disables the MySQL module and updates the configuration.
Parameters
bool $enabled Whether to enable or disable the module.
bool $showWindow Whether to show a message box with the result.
Definition at line 596 of file class.bin.mysql.php.
    {
        global $bearsamppConfig, $bearsamppLang, $bearsamppWinbinder;
        if ( $enabled == Config::ENABLED && !is_dir( $this->currentPath ) ) {
            Util::logDebug( $this->getName() . ' cannot be enabled because bundle ' . $this->getVersion() . ' does not exist in ' . $this->currentPath );
            if ( $showWindow ) {
                $bearsamppWinbinder->messageBoxError(
                    sprintf( $bearsamppLang->getValue( Lang::ENABLE_BUNDLE_NOT_EXIST ), $this->getName(), $this->getVersion(), $this->currentPath ),
                    sprintf( $bearsamppLang->getValue( Lang::ENABLE_TITLE ), $this->getName() )
                );
            }
            $enabled = Config::DISABLED;
        }
        Util::logInfo( $this->getName() . ' switched to ' . ($enabled == Config::ENABLED ? 'enabled' : 'disabled') );
        $this->enable = $enabled == Config::ENABLED;
        $bearsamppConfig->replace( self::ROOT_CFG_ENABLE, $enabled );
        $this->reload();
        if ( $this->enable ) {
            Util::installService( $this, $this->port, self::CMD_SYNTAX_CHECK, $showWindow );
        }
        else {
            Util::removeService( $this->service, $this->name );
        }
    }
References $bearsamppConfig, $bearsamppLang, Config\DISABLED, Lang\ENABLE_BUNDLE_NOT_EXIST, Lang\ENABLE_TITLE, Config\ENABLED, Module\getName(), Module\getVersion(), Util\installService(), Util\logDebug(), Util\logInfo(), reload(), and Util\removeService().
setPort()
BinMysql::setPort ($port)
Sets the MySQL port number and updates the configuration.
Parameters
int $port The port number to set.
Definition at line 669 of file class.bin.mysql.php.
    {
        $this->replace( self::LOCAL_CFG_PORT, $port );
    }
References $port, and Module\replace().
Referenced by changePort().
setRootPwd()
BinMysql::setRootPwd ($rootPwd)
Sets the MySQL root password and updates the configuration.
Parameters
string $rootPwd The root password to set.
Definition at line 709 of file class.bin.mysql.php.
    {
        $this->replace( self::LOCAL_CFG_ROOT_PWD, $rootPwd );
    }
References $rootPwd, and Module\replace().
Referenced by changeRootPassword().
setRootUser()
BinMysql::setRootUser ($rootUser)
Sets the MySQL root username and updates the configuration.
Parameters
string $rootUser The root username to set.
Definition at line 689 of file class.bin.mysql.php.
    {
        $this->replace( self::LOCAL_CFG_ROOT_USER, $rootUser );
    }
References $rootUser, and Module\replace().
setVersion()
BinMysql::setVersion ($version)
Sets the MySQL version and reloads the configuration.
Parameters
string $version The version to set.
Reimplemented from Module.
Definition at line 572 of file class.bin.mysql.php.
    {
        global $bearsamppConfig;
        $this->version = $version;
        $bearsamppConfig->replace( self::ROOT_CFG_VERSION, $version );
        $this->reload();
    }
References $bearsamppConfig, Module\$version, and reload().
Referenced by updateConfig().
switchVersion()
BinMysql::switchVersion ($version, $showWindow = false)
Switches the MySQL version and updates the configuration.
Parameters
string $version The new MySQL version.
bool $showWindow Whether to show a message box with the result.
Returns
bool True if the version was switched successfully, false otherwise.
Definition at line 420 of file class.bin.mysql.php.
    {
        Util::logDebug( 'Switch ' . $this->name . ' version to ' . $version );
        return $this->updateConfig( $version, 0, $showWindow );
    }
References Module\$version, Util\logDebug(), and updateConfig().
updateConfig()
BinMysql::updateConfig ($version = null, $sub = 0, $showWindow = false) protected
Updates the MySQL configuration with a specific version.
Parameters
string | null $version The version to update to. If null, the current version is used.
int $sub The sub-level for logging indentation.
bool $showWindow Whether to show a message box with the result.
Returns
bool True if the configuration was updated successfully, false otherwise.
Reimplemented from Module.
Definition at line 436 of file class.bin.mysql.php.
    {
        global $bearsamppLang, $bearsamppBins, $bearsamppApps, $bearsamppWinbinder;
        if ( !$this->enable ) {
            return true;
        }
        $version = $version == null ? $this->version : $version;
        Util::logDebug( ($sub > 0 ? str_repeat( ' ', 2 * $sub ) : '') . 'Update ' . $this->name . ' ' . $version . ' config' );
        $boxTitle = sprintf( $bearsamppLang->getValue( Lang::SWITCH_VERSION_TITLE ), $this->getName(), $version );
        $currentPath   = str_replace( 'mysql' . $this->getVersion(), 'mysql' . $version, $this->getCurrentPath() );
        $conf          = str_replace( 'mysql' . $this->getVersion(), 'mysql' . $version, $this->getConf() );
        $bearsamppConf = str_replace( 'mysql' . $this->getVersion(), 'mysql' . $version, $this->bearsamppConf );
        if ( $this->version != $version ) {
            $this->initData( $currentPath, $version );
        }
        if ( !file_exists( $conf ) || !file_exists( $bearsamppConf ) ) {
            Util::logError( 'bearsampp config files not found for ' . $this->getName() . ' ' . $version );
            if ( $showWindow ) {
                $bearsamppWinbinder->messageBoxError(
                    sprintf( $bearsamppLang->getValue( Lang::BEARSAMPP_CONF_NOT_FOUND_ERROR ), $this->getName() . ' ' . $version ),
                    $boxTitle
                );
            }
            return false;
        }
        $bearsamppConfRaw = parse_ini_file( $bearsamppConf );
        if ( $bearsamppConfRaw === false || !isset( $bearsamppConfRaw[self::ROOT_CFG_VERSION] ) || $bearsamppConfRaw[self::ROOT_CFG_VERSION] != $version ) {
            Util::logError( 'bearsampp config file malformed for ' . $this->getName() . ' ' . $version );
            if ( $showWindow ) {
                $bearsamppWinbinder->messageBoxError(
                    sprintf( $bearsamppLang->getValue( Lang::BEARSAMPP_CONF_MALFORMED_ERROR ), $this->getName() . ' ' . $version ),
                    $boxTitle
                );
            }
            return false;
        }
        // bearsampp.conf
        $this->setVersion( $version );
        // conf
        Util::replaceInFile( $this->getConf(), array(
            '/^port(.*?)=(.*?)(\d+)/' => 'port = ' . $this->port
        ) );
        // phpmyadmin
        $bearsamppApps->getPhpmyadmin()->update( $sub + 1 );
        // adminer
        $bearsamppApps->getAdminer()->update( $sub + 1 );
        // php
        $bearsamppBins->getPhp()->update( $sub + 1 );
        return true;
    }
References $bearsamppBins, Module\$bearsamppConf, Module\$bearsamppConfRaw, $bearsamppLang, $conf, Module\$currentPath, Module\$version, Lang\BEARSAMPP_CONF_MALFORMED_ERROR, Lang\BEARSAMPP_CONF_NOT_FOUND_ERROR, getConf(), Module\getCurrentPath(), Module\getName(), Module\getVersion(), initData(), Util\logDebug(), Util\logError(), Util\replaceInFile(), setVersion(), and Lang\SWITCH_VERSION_TITLE.
Referenced by switchVersion().
Field Documentation
$admin
BinMysql::$admin private
Definition at line 44 of file class.bin.mysql.php.
Referenced by getAdmin().
$cliExe
BinMysql::$cliExe private
Definition at line 43 of file class.bin.mysql.php.
Referenced by getCliExe().
$conf
BinMysql::$conf private
Definition at line 39 of file class.bin.mysql.php.
Referenced by getConf(), and updateConfig().
$errorLog
BinMysql::$errorLog private
Definition at line 36 of file class.bin.mysql.php.
Referenced by getErrorLog().
$exe
BinMysql::$exe private
Definition at line 38 of file class.bin.mysql.php.
Referenced by getExe().
$port
BinMysql::$port private
Definition at line 40 of file class.bin.mysql.php.
Referenced by changePort(), checkPort(), getPort(), and setPort().
$rootPwd
BinMysql::$rootPwd private
Definition at line 42 of file class.bin.mysql.php.
Referenced by getRootPwd(), and setRootPwd().
$rootUser
BinMysql::$rootUser private
Definition at line 41 of file class.bin.mysql.php.
Referenced by getRootUser(), and setRootUser().
$service
BinMysql::$service private
Definition at line 35 of file class.bin.mysql.php.
Referenced by getService().
CMD_SYNTAX_CHECK
const BinMysql::CMD_SYNTAX_CHECK = '--help --verbose 1>NUL'
Definition at line 33 of file class.bin.mysql.php.
Referenced by ActionDebugMysql\__construct(), ActionService\__construct(), TplAppMysql\getMenuMysqlDebug(), ActionStartup\installServices(), and Win32Service\start().
CMD_VARIABLES
const BinMysql::CMD_VARIABLES = 'variables'
Definition at line 32 of file class.bin.mysql.php.
Referenced by ActionDebugMysql\__construct(), and TplAppMysql\getMenuMysqlDebug().
CMD_VERSION
const BinMysql::CMD_VERSION = '--version'
Definition at line 31 of file class.bin.mysql.php.
Referenced by ActionDebugMysql\__construct(), and TplAppMysql\getMenuMysqlDebug().
LOCAL_CFG_ADMIN
const BinMysql::LOCAL_CFG_ADMIN = 'mysqlAdmin'
Definition at line 25 of file class.bin.mysql.php.
Referenced by reload().
LOCAL_CFG_CLI_EXE
const BinMysql::LOCAL_CFG_CLI_EXE = 'mysqlCliExe'
Definition at line 24 of file class.bin.mysql.php.
Referenced by reload().
LOCAL_CFG_CONF
const BinMysql::LOCAL_CFG_CONF = 'mysqlConf'
Definition at line 26 of file class.bin.mysql.php.
Referenced by reload().
LOCAL_CFG_EXE
const BinMysql::LOCAL_CFG_EXE = 'mysqlExe'
Definition at line 23 of file class.bin.mysql.php.
Referenced by reload().
LOCAL_CFG_PORT
const BinMysql::LOCAL_CFG_PORT = 'mysqlPort'
Definition at line 27 of file class.bin.mysql.php.
Referenced by reload(), and replaceAll().
LOCAL_CFG_ROOT_PWD
const BinMysql::LOCAL_CFG_ROOT_PWD = 'mysqlRootPwd'
Definition at line 29 of file class.bin.mysql.php.
Referenced by reload(), and replaceAll().
LOCAL_CFG_ROOT_USER
const BinMysql::LOCAL_CFG_ROOT_USER = 'mysqlRootUser'
Definition at line 28 of file class.bin.mysql.php.
Referenced by reload(), and replaceAll().
ROOT_CFG_ENABLE
const BinMysql::ROOT_CFG_ENABLE = 'mysqlEnable'
Definition at line 20 of file class.bin.mysql.php.
ROOT_CFG_VERSION
const BinMysql::ROOT_CFG_VERSION = 'mysqlVersion'
Definition at line 21 of file class.bin.mysql.php.
SERVICE_NAME
const BinMysql::SERVICE_NAME = 'bearsamppmysql'
Definition at line 18 of file class.bin.mysql.php.
Referenced by ActionService\__construct(), TplAppMysql\getActionInstallMysqlService(), TplAppMysql\getActionRemoveMysqlService(), Bins\getServices(), ActionStartup\installServices(), ActionQuit\processWindow(), and Win32Service\start().
The documentation for this class was generated from the following file:
E:/Bearsampp-development/sandbox/core/classes/bins/class.bin.mysql.php