version: v1.25.0
exclude:
  code:
    - "/core/libs**"
    - "/core/tmp**"
    - "/core/resources/homepage/libs**"
    - "/apps**"
    - "/bin**"
    - "/tools**"
    - "/www**"
    - "/logs**"
    - "/alias**"

