Bearsampp: ActionManualRestart Class Reference
ActionManualRestart Class Reference
Public Member Functions
__construct ($args)
Detailed Description
Class ActionManualRestart
This class handles the manual restart of services in the Bearsampp application. It stops all running services, kills all related processes, and sets the application to restart.
Definition at line 17 of file class.action.manualRestart.php.
Constructor & Destructor Documentation
__construct()
ActionManualRestart::__construct ($args)
ActionManualRestart constructor.
Parameters
array $args Arguments passed to the constructor.
This constructor initializes the manual restart process by performing the following steps:
Starts the loading process.
Deletes all services managed by Bearsampp.
Kills all related processes.
Sets the application to restart.
Stops the loading process.
Definition at line 31 of file class.action.manualRestart.php.
    {
        global $bearsamppCore, $bearsamppBins;
        // Start the loading process
        Util::startLoading();
        // Delete all services managed by Bearsampp
        foreach ($bearsamppBins->getServices() as $sName => $service) {
            $service->delete();
        }
        // Kill all related processes
        Win32Ps::killBins(true);
        // Set the application to restart
        $bearsamppCore->setExec(ActionExec::RESTART);
        // Stop the loading process
        Util::stopLoading();
    }
References $bearsamppBins, $bearsamppCore, Win32Ps\killBins(), ActionExec\RESTART, Util\startLoading(), and Util\stopLoading().
The documentation for this class was generated from the following file:
E:/Bearsampp-development/sandbox/core/classes/actions/class.action.manualRestart.php