Bearsampp: ActionCheckVersion Class Reference
ActionCheckVersion Class Reference
Public Member Functions
__construct ($args)
processWindow ($window, $id, $ctrl, $param1, $param2)
Data Fields
const DISPLAY_OK = 'displayOk'
Private Member Functions
showVersionOkMessageBox ($lang, $winbinder)
showVersionUpdateWindow ($lang, $winbinder, $core, $githubLatestVersion)
Private Attributes
$currentVersion
$githubLatestVersionUrl
$latestVersion
$wbBtnOk
$wbImage
$wbLinkChangelog
$wbLinkFull
$wbWindow
Detailed Description
Definition at line 19 of file class.action.checkVersion.php.
Constructor & Destructor Documentation
__construct()
ActionCheckVersion::__construct ($args)
Constructor for the ActionCheckVersion class.
Parameters
array $args Command line arguments passed to the script.
Definition at line 38 of file class.action.checkVersion.php.
    {
        global $bearsamppCore, $bearsamppLang, $bearsamppWinbinder, $appGithubHeader;
        if (!file_exists($bearsamppCore->getExec())) {
            Util::startLoading();
            $this->currentVersion = $bearsamppCore->getAppVersion();
            // Assuming getLatestVersion now returns an array with version and URL
            $githubVersionData = Util::getLatestVersion(APP_GITHUB_LATEST_URL);
            if ($githubVersionData != null && isset($githubVersionData['version'], $githubVersionData['html_url'])) {
                $githubLatestVersion = $githubVersionData['version'];
                $this->githubLatestVersionUrl = $githubVersionData['html_url']; // URL of the latest version
                if (version_compare($this->currentVersion, $githubLatestVersion, '<')) {
                    $this->showVersionUpdateWindow($bearsamppLang, $bearsamppWinbinder, $bearsamppCore, $githubLatestVersion);
                } elseif (!empty($args[0]) && $args[0] == self::DISPLAY_OK) {
                    $this->showVersionOkMessageBox($bearsamppLang, $bearsamppWinbinder);
                }
            }
        }
    }
References $bearsamppCore, $bearsamppLang, $githubLatestVersion, $githubVersionData, APP_GITHUB_LATEST_URL, Util\getLatestVersion(), showVersionOkMessageBox(), showVersionUpdateWindow(), and Util\startLoading().
Member Function Documentation
processWindow()
ActionCheckVersion::processWindow ($window, $id, $ctrl, $param1, $param2)
Processes window events and handles user interactions.
Parameters
resource $window The window resource.
int $id The control ID that triggered the event.
resource $ctrl The control resource.
mixed $param1 Additional parameter 1.
mixed $param2 Additional parameter 2.
Definition at line 113 of file class.action.checkVersion.php.
    {
        global $bearsamppConfig, $bearsamppWinbinder;
        switch ($id) {
            case $this->wbLinkFull[WinBinder::CTRL_ID]:
                $latestVersionInfo = Util::getLatestVersion(APP_GITHUB_LATEST_URL);
                if ($latestVersionInfo && isset($latestVersionInfo['html_url'])) {
                    $browserPath = $bearsamppConfig->getBrowser();
                    if (!$bearsamppWinbinder->exec($browserPath, $latestVersionInfo['html_url'])) {
                        Util::logError("Failed to open browser at path: $browserPath with URL: " . $latestVersionInfo['html_url']);
                    }
                } else {
                    Util::logError("Failed to retrieve latest version info or 'html_url' not set.");
                }
                break;
            case IDCLOSE:
            case $this->wbBtnOk[WinBinder::CTRL_ID]:
                $bearsamppWinbinder->destroyWindow($window);
                break;
            default:
                Util::logError("Unhandled window control ID: $id");
        }
    }
References $bearsamppConfig, APP_GITHUB_LATEST_URL, WinBinder\CTRL_ID, Util\getLatestVersion(), and Util\logError().
showVersionOkMessageBox()
ActionCheckVersion::showVersionOkMessageBox ($lang, $winbinder) private
Displays a message box indicating that the current version is the latest.
Parameters
Lang $lang Language processor instance.
WinBinder $winbinder WinBinder instance for creating windows and controls.
Definition at line 95 of file class.action.checkVersion.php.
    {
        Util::stopLoading();
        $winbinder->messageBoxInfo(
            $lang->getValue(Lang::CHECK_VERSION_LATEST_TEXT),
            $lang->getValue(Lang::CHECK_VERSION_TITLE)
        );
    }
References Lang\CHECK_VERSION_LATEST_TEXT, Lang\CHECK_VERSION_TITLE, and Util\stopLoading().
Referenced by __construct().
showVersionUpdateWindow()
ActionCheckVersion::showVersionUpdateWindow ($lang, $winbinder, $core, $githubLatestVersion) private
Displays a window with the latest version information.
Parameters
Lang $lang Language processor instance.
WinBinder $winbinder WinBinder instance for creating windows and controls.
Core $core Core instance for accessing application resources.
string $githubLatestVersion The latest version available on GitHub.
Definition at line 69 of file class.action.checkVersion.php.
    {
        $labelFullLink = $lang->getValue(Lang::DOWNLOAD) . ' ' . APP_TITLE . ' ' . $githubLatestVersion;
        $winbinder->reset();
        $this->wbWindow = $winbinder->createAppWindow($lang->getValue(Lang::CHECK_VERSION_TITLE), 380, 170, WBC_NOTIFY, WBC_KEYDOWN | WBC_KEYUP);
        $winbinder->createLabel($this->wbWindow, $lang->getValue(Lang::CHECK_VERSION_AVAILABLE_TEXT), 80, 35, 370, 120);
        $this->wbLinkFull = $winbinder->createHyperLink($this->wbWindow, $labelFullLink, 80, 87, 200, 20, WBC_LINES | WBC_RIGHT);
        $this->wbBtnOk = $winbinder->createButton($this->wbWindow, $lang->getValue(Lang::BUTTON_OK), 280, 103);
        $this->wbImage = $winbinder->drawImage($this->wbWindow, $core->getResourcesPath() . '/homepage/img/about.bmp');
        Util::stopLoading();
        $winbinder->setHandler($this->wbWindow, $this, 'processWindow');
        $winbinder->mainLoop();
        $winbinder->reset();
    }
References $githubLatestVersion, APP_TITLE, Lang\BUTTON_OK, Lang\CHECK_VERSION_AVAILABLE_TEXT, Lang\CHECK_VERSION_TITLE, Lang\DOWNLOAD, and Util\stopLoading().
Referenced by __construct().
Field Documentation
$currentVersion
ActionCheckVersion::$currentVersion private
Definition at line 29 of file class.action.checkVersion.php.
$githubLatestVersionUrl
ActionCheckVersion::$githubLatestVersionUrl private
Definition at line 31 of file class.action.checkVersion.php.
$latestVersion
ActionCheckVersion::$latestVersion private
Definition at line 30 of file class.action.checkVersion.php.
$wbBtnOk
ActionCheckVersion::$wbBtnOk private
Definition at line 27 of file class.action.checkVersion.php.
$wbImage
ActionCheckVersion::$wbImage private
Definition at line 24 of file class.action.checkVersion.php.
$wbLinkChangelog
ActionCheckVersion::$wbLinkChangelog private
Definition at line 25 of file class.action.checkVersion.php.
$wbLinkFull
ActionCheckVersion::$wbLinkFull private
Definition at line 26 of file class.action.checkVersion.php.
$wbWindow
ActionCheckVersion::$wbWindow private
Definition at line 23 of file class.action.checkVersion.php.
DISPLAY_OK
const ActionCheckVersion::DISPLAY_OK = 'displayOk'
Definition at line 21 of file class.action.checkVersion.php.
Referenced by TplApp\getSectionMenuRight().
The documentation for this class was generated from the following file:
E:/Bearsampp-development/sandbox/core/classes/actions/class.action.checkVersion.php