Bearsampp: E:/Bearsampp-development/sandbox/core/libs/winbinder/db/db_mysql.inc.php File Reference
db_mysql.inc.php File Reference
Functions
raw_db_close_database ()
raw_db_create_database ($database, $server="", $username="", $password="")
raw_db_create_field ($tablename, $field, $type)
raw_db_delete_field ($tablename, $field)
raw_db_edit_field ($tablename, $field, $type)
raw_db_escape_string ($str)
raw_db_fetch_array ($result, $type=FETCH_BOTH)
raw_db_free_result ($result)
raw_db_list_database_tables ()
raw_db_list_table_fields_def ($tablename, $type=false)
if(DB_WRAPVERSION !=DB_MYSQL_WRAP) raw_db_open_database ($database, $server="", $username="", $password="")
raw_db_query ($query)
raw_db_rename_field ($tablename, $field, $newname, $type)
raw_db_rename_table ($tablename, $newname)
raw_db_table_exists ($tablename)
raw_get_db_version ()
Variables
const DB_MYSQL_WRAP (PHP_VERSION >="5") if(!extension_loaded('mysql')) if(! @dl('php_mysql.dll')) "db_v2b"
const FETCH_ASSOC MYSQL_ASSOC
const FETCH_BOTH MYSQL_BOTH
const FETCH_NUM MYSQL_NUM
Function Documentation
raw_db_close_database()
raw_db_close_database ()
raw_db_close_database()
Returns
bool
Definition at line 127 of file db_mysql.inc.php.
{
  return mysql_close();
}
Referenced by db_close_database().
raw_db_create_database()
raw_db_create_database ($database, $server = "", $username = "", $password = "")
raw_db_create_database() Creates a database if it does not exist.
Parameters
$database
string $server
string $username
string $password
Returns
resource or FALSE
Definition at line 80 of file db_mysql.inc.php.
{
  global $curr_db;
  $conn = mysql_connect($server, $username, $password);
  if (!$conn) {
    trigger_error(__FUNCTION__ . ": " . mysql_error());
    return false;
  } else {
    if (!mysql_query("CREATE DATABASE IF NOT EXISTS " . $database))
      die(mysql_error());
    $curr_db = $database;
    if (!mysql_select_db($database)) {
      trigger_error(__FUNCTION__ . ": " . mysql_error());
      return false;
    }
  }
  return $conn;
}
Referenced by db_create_database().
raw_db_create_field()
raw_db_create_field ($tablename, $field, $type)
raw_db_create_field()
Parameters
$tablename
$field
$type
Returns
bool
Definition at line 201 of file db_mysql.inc.php.
{
  global $g_lasttable;
  if (!$tablename)
    $tablename = $g_lasttable;
  $g_lasttable = $tablename;
  $res = mysql_query("ALTER TABLE $tablename ADD $field $type");
  return $res;
}
Referenced by db_create_field().
raw_db_delete_field()
raw_db_delete_field ($tablename, $field)
raw_db_delete_field()
Parameters
$tablename
$field
Returns
bool
Definition at line 220 of file db_mysql.inc.php.
{
  global $g_lasttable;
  if (!$tablename)
    $tablename = $g_lasttable;
  $g_lasttable = $tablename;
  $res = mysql_query("ALTER TABLE $tablename DROP $field");
  return $res;
}
Referenced by db_delete_field().
raw_db_edit_field()
raw_db_edit_field ($tablename, $field, $type)
raw_db_edit_field()
Parameters
$tablename
$field
$type
Returns
bool
Definition at line 261 of file db_mysql.inc.php.
{
  global $g_lasttable;
  if (!$tablename)
    $tablename = $g_lasttable;
  $g_lasttable = $tablename;
  $res = mysql_query("ALTER TABLE $tablename MODIFY $field $type");
  return $res;
}
Referenced by db_edit_field().
raw_db_escape_string()
raw_db_escape_string ($str)
raw_db_escape_string()
Parameters
$str
Returns
escaped string
Definition at line 318 of file db_mysql.inc.php.
{
  return mysql_real_escape_string($str);
}
Referenced by db_escape_string().
raw_db_fetch_array()
raw_db_fetch_array ($result, $type = FETCH_BOTH)
raw_db_fetch_array() get the value of SQL-query, row by row
Parameters
$result
unknown $type
Returns
array of row, FALSE if no more rows
Definition at line 296 of file db_mysql.inc.php.
{
  return mysql_fetch_array($result, $type);
}
References $result.
Referenced by db_fetch_array().
raw_db_free_result()
raw_db_free_result ($result)
raw_db_free_result()
Parameters
$result
Returns
bool
Definition at line 307 of file db_mysql.inc.php.
{
  mysql_free_result($result);
}
References $result.
Referenced by db_free_result().
raw_db_list_database_tables()
raw_db_list_database_tables ()
raw_db_list_database_tables() Returns an array with the list of tables of the current database.
Returns
array or FALSE
Definition at line 106 of file db_mysql.inc.php.
{
  global $curr_db;
  $hresult = mysql_query("SHOW TABLES FROM $curr_db");
  if (!$hresult) {
    // no Tables in $database
    return false;
  } else {
    while ($row = mysql_fetch_array($hresult, MYSQL_NUM)) {
      $tables[] = $row[0];
    } // while
    return $tables;
  }
}
Referenced by db_list_database_tables().
raw_db_list_table_fields_def()
raw_db_list_table_fields_def ($tablename, $type = false)
raw_db_list_table_fields_def() lists fieldnames or fieldattributes according type
Parameters
$tablename
boolean $type
Returns
array or FALSE
Definition at line 177 of file db_mysql.inc.php.
{
  $result = mysql_query("SHOW COLUMNS FROM $tablename");
  if ($result === false) return false;
  $coltype = array();
  $colnames = array();
  if (mysql_num_rows($result) > 0) {
    while ($row = mysql_fetch_assoc($result)) {
      $colnames[] = $row['Field'];
      $coltype[] = $row['Type'];
    } // while
  }
  if (mysql_free_result($result) == false) return false;
  return ($type ? $coltype : $colnames);
}
References $result.
Referenced by db_list_table_fields().
raw_db_open_database()
if(DB_WRAPVERSION !=DB_MYSQL_WRAP) raw_db_open_database ($database, $server = "", $username = "", $password = "")
raw_db_open_database() Opens and connects an existing database.
Parameters
$database
string $server
string $username
string $password
Returns
resource or FALSE
Definition at line 52 of file db_mysql.inc.php.
{
  global $curr_db;
  $conn = mysql_connect($server, $username, $password);
  if (!$conn) {
    trigger_error(__FUNCTION__ . ": " . mysql_error());
    return false;
  } else {
    $curr_db = $database;
    if (!mysql_select_db($database)) {
      trigger_error(__FUNCTION__ . ": " . mysql_error());
      return false;
    }
  }
  return $conn;
}
Referenced by db_open_database().
raw_db_query()
raw_db_query ($query)
raw_db_query() queries the database with SQL
Parameters
string $query
Returns
resource on success for SELECT,SHOW,DESCRIBE ans EXPLAIN TRUE on success for UPDATE, DELETE, DROP etc FALSE on errors
Definition at line 282 of file db_mysql.inc.php.
{
  $res = mysql_query($query);
  return $res;
}
Referenced by db_create_record(), db_create_table(), db_delete_records(), db_delete_table(), db_edit_record(), db_get_data(), db_get_id(), db_get_next_free_id(), db_query(), and db_swap_records().
raw_db_rename_field()
raw_db_rename_field ($tablename, $field, $newname, $type)
raw_db_rename_field()
Parameters
$tablename
$field
$newname
$type
Returns
bool
Definition at line 241 of file db_mysql.inc.php.
{
  global $g_lasttable;
  if (!$tablename)
    $tablename = $g_lasttable;
  $g_lasttable = $tablename;
  $res = mysql_query("ALTER TABLE $tablename CHANGE $field $newname $type");
  return $res;
}
Referenced by db_rename_field().
raw_db_rename_table()
raw_db_rename_table ($tablename, $newname)
raw_db_rename_table()
Parameters
$tablename
$newname
Returns
bool
Definition at line 157 of file db_mysql.inc.php.
{
  global $g_lasttable;
  if (!$tablename)
    $tablename = $g_lasttable;
  $g_lasttable = $newname;
  $res = mysql_query("RENAME TABLE $tablename TO $newname");
  return $res;
}
Referenced by db_rename_table().
raw_db_table_exists()
raw_db_table_exists ($tablename)
raw_db_table_exists()
Parameters
$tablename
Returns
bool
Definition at line 138 of file db_mysql.inc.php.
{
  global $g_current_db;
  $sql = "SELECT 1 FROM $tablename LIMIT 0";
  $res = mysql_query($sql);
  if ($res) {
    return true;
  } ;
  return false;
}
Referenced by db_table_exists().
raw_get_db_version()
raw_get_db_version ()
raw_get_db_version() Returns the version of the database library.
Returns
string
Definition at line 33 of file db_mysql.inc.php.
{
    return mysql_get_server_info();
}
if (DB_WRAPVERSION != DB_MYSQL_WRAP) {
  die(" db_common.inc.php has different version number than db_mysql.inc.php ");
}
Referenced by db_get_info().
Variable Documentation
DB_MYSQL_WRAP
const DB_MYSQL_WRAP(PHP_VERSION >="5") if(!extension_loaded('mysql')) if(! @dl('php_mysql.dll')) (PHP_VERSION >="5") "db_v2b"
WINBINDER - The native Windows binding for PHP for PHP
Copyright Hypervisual - see LICENSE.TXT for details Authors: Rubem Pechansky and Hans Rebel
Database wrapper functions for WinBinder (MySQL-specific) version 2b
Definition at line 21 of file db_mysql.inc.php.
FETCH_ASSOC
const FETCH_ASSOC MYSQL_ASSOC
Definition at line 24 of file db_mysql.inc.php.
Referenced by db_swap_records().
FETCH_BOTH
const FETCH_BOTH MYSQL_BOTH
Definition at line 22 of file db_mysql.inc.php.
FETCH_NUM
const FETCH_NUM MYSQL_NUM
Definition at line 23 of file db_mysql.inc.php.
Referenced by db_create_record(), db_get_id(), and db_get_next_free_id().