Bearsampp: TplAppMemcached Class Reference
TplAppMemcached Class Reference
Static Public Member Functions
static getActionChangeMemcachedPort ()
static getActionEnableMemcached ($enable)
static getActionInstallMemcachedService ()
static getActionRemoveMemcachedService ()
static getActionSwitchMemcachedVersion ($version)
static getMenuMemcached ()
static getMenuMemcachedService ()
static getMenuMemcachedVersions ()
static process ()
Data Fields
const ACTION_CHANGE_PORT = 'changeMemcachedPort'
const ACTION_ENABLE = 'enableMemcached'
const ACTION_INSTALL_SERVICE = 'installMemcachedService'
const ACTION_REMOVE_SERVICE = 'removeMemcachedService'
const ACTION_SWITCH_VERSION = 'switchMemcachedVersion'
const MENU = 'memcached'
const MENU_SERVICE = 'memcachedService'
const MENU_VERSIONS = 'memcachedVersions'
Detailed Description
Class TplAppMemcached
This class provides methods to generate menu items and actions for managing Memcached within the Bearsampp application. It includes functionalities for enabling/disabling Memcached, switching versions, changing ports, and managing services.
Definition at line 16 of file class.tpl.app.memcached.php.
Member Function Documentation
getActionChangeMemcachedPort()
static TplAppMemcached::getActionChangeMemcachedPort () static
Generates the action to change the Memcached port.
This method creates the action string for changing the Memcached port. It includes commands to reload the application after the action is performed.
@global object $bearsamppBins Provides access to system binaries and their configurations.
Returns
string The generated action string for changing the Memcached port.
Definition at line 245 of file class.tpl.app.memcached.php.
    {
        global $bearsamppBins;
        return TplApp::getActionRun(Action::CHANGE_PORT, array($bearsamppBins->getMemcached()->getName())) . PHP_EOL .
            TplAppReload::getActionReload();
    }
References $bearsamppBins, Action\CHANGE_PORT, TplAppReload\getActionReload(), and TplApp\getActionRun().
getActionEnableMemcached()
static TplAppMemcached::getActionEnableMemcached ($enable) static
Generates the action to enable or disable Memcached.
This method creates the action string for enabling or disabling Memcached. It includes commands to reload the application after the action is performed.
@global object $bearsamppBins Provides access to system binaries and their configurations.
Parameters
int $enable The value indicating whether to enable or disable Memcached.
Returns
string The generated action string for enabling or disabling Memcached.
Definition at line 149 of file class.tpl.app.memcached.php.
    {
        global $bearsamppBins;
        return TplApp::getActionRun(Action::ENABLE, array($bearsamppBins->getMemcached()->getName(), $enable)) . PHP_EOL .
            TplAppReload::getActionReload();
    }
References $bearsamppBins, Action\ENABLE, TplAppReload\getActionReload(), and TplApp\getActionRun().
getActionInstallMemcachedService()
static TplAppMemcached::getActionInstallMemcachedService () static
Generates the action to install the Memcached service.
This method creates the action string for installing the Memcached service. It includes commands to reload the application after the action is performed.
Returns
string The generated action string for installing the Memcached service.
Definition at line 261 of file class.tpl.app.memcached.php.
    {
        return TplApp::getActionRun(Action::SERVICE, array(BinMemcached::SERVICE_NAME, ActionService::INSTALL)) . PHP_EOL .
            TplAppReload::getActionReload();
    }
References TplAppReload\getActionReload(), TplApp\getActionRun(), ActionService\INSTALL, Action\SERVICE, and BinMemcached\SERVICE_NAME.
getActionRemoveMemcachedService()
static TplAppMemcached::getActionRemoveMemcachedService () static
Generates the action to remove the Memcached service.
This method creates the action string for removing the Memcached service. It includes commands to reload the application after the action is performed.
Returns
string The generated action string for removing the Memcached service.
Definition at line 275 of file class.tpl.app.memcached.php.
    {
        return TplApp::getActionRun(Action::SERVICE, array(BinMemcached::SERVICE_NAME, ActionService::REMOVE)) . PHP_EOL .
            TplAppReload::getActionReload();
    }
References TplAppReload\getActionReload(), TplApp\getActionRun(), ActionService\REMOVE, Action\SERVICE, and BinMemcached\SERVICE_NAME.
getActionSwitchMemcachedVersion()
static TplAppMemcached::getActionSwitchMemcachedVersion ($version) static
Generates the action to switch Memcached versions.
This method creates the action string for switching Memcached versions. It includes commands to reload the application after the action is performed.
@global object $bearsamppBins Provides access to system binaries and their configurations.
Parameters
string $version The version to switch to.
Returns
string The generated action string for switching Memcached versions.
Definition at line 168 of file class.tpl.app.memcached.php.
    {
        global $bearsamppBins;
        return TplApp::getActionRun(Action::SWITCH_VERSION, array($bearsamppBins->getMemcached()->getName(), $version)) . PHP_EOL .
            TplAppReload::getActionReload() . PHP_EOL;
    }
References $bearsamppBins, TplAppReload\getActionReload(), TplApp\getActionRun(), and Action\SWITCH_VERSION.
getMenuMemcached()
static TplAppMemcached::getMenuMemcached () static
Generates the menu items and actions for managing Memcached.
This method creates menu items for downloading Memcached, enabling/disabling it, switching versions, managing services, updating the environment PATH, and viewing logs. It uses the global language object to retrieve localized strings.
@global object $bearsamppRoot Provides access to the root path of the application. @global object $bearsamppBins Provides access to system binaries and their configurations. @global object $bearsamppLang Provides language support for retrieving language-specific values.
Returns
string The generated menu items and actions for managing Memcached.
Definition at line 59 of file class.tpl.app.memcached.php.
    {
        global $bearsamppRoot, $bearsamppBins, $bearsamppLang;
        $resultItems = $resultActions = '';
        $isEnabled = $bearsamppBins->getMemcached()->isEnable();
        // Download
        $resultItems .= TplAestan::getItemLink($bearsamppLang->getValue(Lang::DOWNLOAD_MORE),
            Util::getWebsiteUrl('module/memcached', '#releases'),
            false,
            TplAestan::GLYPH_BROWSER
        ) . PHP_EOL;
        // Enable
        $tplEnable = TplApp::getActionMulti(
            self::ACTION_ENABLE, array($isEnabled ? Config::DISABLED : Config::ENABLED),
            array($bearsamppLang->getValue(Lang::MENU_ENABLE), $isEnabled ? TplAestan::GLYPH_CHECK : ''),
            false, get_called_class()
        );
        $resultItems .= $tplEnable[TplApp::SECTION_CALL] . PHP_EOL;
        $resultActions .= $tplEnable[TplApp::SECTION_CONTENT] . PHP_EOL;
        if ($isEnabled) {
            $resultItems .= TplAestan::getItemSeparator() . PHP_EOL;
            // Versions
            $tplVersions = TplApp::getMenu($bearsamppLang->getValue(Lang::VERSIONS), self::MENU_VERSIONS, get_called_class());
            $resultItems .= $tplVersions[TplApp::SECTION_CALL] . PHP_EOL;
            $resultActions .= $tplVersions[TplApp::SECTION_CONTENT] . PHP_EOL;
            // Service
            $tplService = TplApp::getMenu($bearsamppLang->getValue(Lang::SERVICE), self::MENU_SERVICE, get_called_class());
            $resultItems .= $tplService[TplApp::SECTION_CALL] . PHP_EOL;
            $resultActions .= $tplService[TplApp::SECTION_CONTENT];
            // Update environment PATH
            $resultItems .= TplAestan::getItemNotepad($bearsamppLang->getValue(Lang::MENU_UPDATE_ENV_PATH), $bearsamppRoot->getRootPath() . '/nssmEnvPaths.dat') . PHP_EOL;
            // Log
            $resultItems .= TplAestan::getItemNotepad($bearsamppLang->getValue(Lang::MENU_LOGS), $bearsamppBins->getMemcached()->getLog()) . PHP_EOL;
        }
        return $resultItems . PHP_EOL . $resultActions;
    }
References $bearsamppBins, $bearsamppLang, $bearsamppRoot, Config\DISABLED, Lang\DOWNLOAD_MORE, Config\ENABLED, TplApp\getActionMulti(), TplAestan\getItemLink(), TplAestan\getItemNotepad(), TplAestan\getItemSeparator(), TplApp\getMenu(), Util\getWebsiteUrl(), TplAestan\GLYPH_BROWSER, TplAestan\GLYPH_CHECK, Lang\MENU_ENABLE, Lang\MENU_LOGS, Lang\MENU_UPDATE_ENV_PATH, TplApp\SECTION_CALL, TplApp\SECTION_CONTENT, Lang\SERVICE, and Lang\VERSIONS.
getMenuMemcachedService()
static TplAppMemcached::getMenuMemcachedService () static
Generates the menu items and actions for managing Memcached services.
This method creates menu items for starting, stopping, and restarting the Memcached service, as well as checking and changing the port, and installing or removing the service. It uses the global language object to retrieve localized strings.
@global object $bearsamppLang Provides language support for retrieving language-specific values. @global object $bearsamppBins Provides access to system binaries and their configurations.
Returns
string The generated menu items and actions for managing Memcached services.
Definition at line 188 of file class.tpl.app.memcached.php.
    {
        global $bearsamppLang, $bearsamppBins;
        $tplChangePort = TplApp::getActionMulti(
            self::ACTION_CHANGE_PORT, null,
            array($bearsamppLang->getValue(Lang::MENU_CHANGE_PORT), TplAestan::GLYPH_NETWORK),
            false, get_called_class()
        );
        $isInstalled = $bearsamppBins->getMemcached()->getService()->isInstalled();
        $result = TplAestan::getItemActionServiceStart($bearsamppBins->getMemcached()->getService()->getName()) . PHP_EOL .
            TplAestan::getItemActionServiceStop($bearsamppBins->getMemcached()->getService()->getName()) . PHP_EOL .
            TplAestan::getItemActionServiceRestart($bearsamppBins->getMemcached()->getService()->getName()) . PHP_EOL .
            TplAestan::getItemSeparator() . PHP_EOL .
            TplApp::getActionRun(
                Action::CHECK_PORT, array($bearsamppBins->getMemcached()->getName(), $bearsamppBins->getMemcached()->getPort()),
                array(sprintf($bearsamppLang->getValue(Lang::MENU_CHECK_PORT), $bearsamppBins->getMemcached()->getPort()), TplAestan::GLYPH_LIGHT)
            ) . PHP_EOL .
            $tplChangePort[TplApp::SECTION_CALL] . PHP_EOL;
        if (!$isInstalled) {
            $tplInstallService = TplApp::getActionMulti(
                self::ACTION_INSTALL_SERVICE, null,
                array($bearsamppLang->getValue(Lang::MENU_INSTALL_SERVICE), TplAestan::GLYPH_SERVICE_INSTALL),
                $isInstalled, get_called_class()
            );
            $result .= $tplInstallService[TplApp::SECTION_CALL] . PHP_EOL . PHP_EOL .
            $tplInstallService[TplApp::SECTION_CONTENT] . PHP_EOL;
        } else {
            $tplRemoveService = TplApp::getActionMulti(
                self::ACTION_REMOVE_SERVICE, null,
                array($bearsamppLang->getValue(Lang::MENU_REMOVE_SERVICE), TplAestan::GLYPH_SERVICE_REMOVE),
                !$isInstalled, get_called_class()
            );
            $result .= $tplRemoveService[TplApp::SECTION_CALL] . PHP_EOL . PHP_EOL .
            $tplRemoveService[TplApp::SECTION_CONTENT] . PHP_EOL;
        }
        $result .= $tplChangePort[TplApp::SECTION_CONTENT] . PHP_EOL;
        return $result;
    }
References $bearsamppBins, $bearsamppLang, $result, Action\CHECK_PORT, TplApp\getActionMulti(), TplApp\getActionRun(), TplAestan\getItemActionServiceRestart(), TplAestan\getItemActionServiceStart(), TplAestan\getItemActionServiceStop(), TplAestan\getItemSeparator(), TplAestan\GLYPH_LIGHT, TplAestan\GLYPH_NETWORK, TplAestan\GLYPH_SERVICE_INSTALL, TplAestan\GLYPH_SERVICE_REMOVE, Lang\MENU_CHANGE_PORT, Lang\MENU_CHECK_PORT, Lang\MENU_INSTALL_SERVICE, Lang\MENU_REMOVE_SERVICE, TplApp\SECTION_CALL, and TplApp\SECTION_CONTENT.
getMenuMemcachedVersions()
static TplAppMemcached::getMenuMemcachedVersions () static
Generates the menu items and actions for switching Memcached versions.
This method creates menu items for each available Memcached version and defines the actions to be taken when a version is selected. It uses the global language object to retrieve localized strings.
@global object $bearsamppBins Provides access to system binaries and their configurations.
Returns
string The generated menu items and actions for switching Memcached versions.
Definition at line 115 of file class.tpl.app.memcached.php.
    {
        global $bearsamppBins;
        $items = '';
        $actions = '';
        foreach ($bearsamppBins->getMemcached()->getVersionList() as $version) {
            $tplSwitchMemcachedVersion = TplApp::getActionMulti(
                self::ACTION_SWITCH_VERSION, array($version),
                array($version, $version == $bearsamppBins->getMemcached()->getVersion() ? TplAestan::GLYPH_CHECK : ''),
                false, get_called_class()
            );
            // Item
            $items .= $tplSwitchMemcachedVersion[TplApp::SECTION_CALL] . PHP_EOL;
            // Action
            $actions .= PHP_EOL . $tplSwitchMemcachedVersion[TplApp::SECTION_CONTENT];
        }
        return $items . $actions;
    }
References $bearsamppBins, TplApp\getActionMulti(), TplAestan\GLYPH_CHECK, TplApp\SECTION_CALL, and TplApp\SECTION_CONTENT.
process()
static TplAppMemcached::process () static
Generates the menu item for enabling/disabling Memcached.
This method creates a menu item for enabling or disabling Memcached and defines the actions to be taken when the menu item is selected. It uses the global language object to retrieve the localized string for Memcached.
@global object $bearsamppLang Provides language support for retrieving language-specific values. @global object $bearsamppBins Provides access to system binaries and their configurations.
Returns
array The generated menu item for enabling/disabling Memcached.
Definition at line 40 of file class.tpl.app.memcached.php.
    {
        global $bearsamppLang, $bearsamppBins;
        return TplApp::getMenuEnable($bearsamppLang->getValue(Lang::MEMCACHED), self::MENU, get_called_class(), $bearsamppBins->getMemcached()->isEnable());
    }
References $bearsamppBins, $bearsamppLang, TplApp\getMenuEnable(), and Lang\MEMCACHED.
Referenced by TplApp\getSectionMenuLeft().
Field Documentation
ACTION_CHANGE_PORT
const TplAppMemcached::ACTION_CHANGE_PORT = 'changeMemcachedPort'
Definition at line 25 of file class.tpl.app.memcached.php.
ACTION_ENABLE
const TplAppMemcached::ACTION_ENABLE = 'enableMemcached'
Definition at line 23 of file class.tpl.app.memcached.php.
ACTION_INSTALL_SERVICE
const TplAppMemcached::ACTION_INSTALL_SERVICE = 'installMemcachedService'
Definition at line 26 of file class.tpl.app.memcached.php.
ACTION_REMOVE_SERVICE
const TplAppMemcached::ACTION_REMOVE_SERVICE = 'removeMemcachedService'
Definition at line 27 of file class.tpl.app.memcached.php.
ACTION_SWITCH_VERSION
const TplAppMemcached::ACTION_SWITCH_VERSION = 'switchMemcachedVersion'
Definition at line 24 of file class.tpl.app.memcached.php.
MENU
const TplAppMemcached::MENU = 'memcached'
Definition at line 19 of file class.tpl.app.memcached.php.
MENU_SERVICE
const TplAppMemcached::MENU_SERVICE = 'memcachedService'
Definition at line 21 of file class.tpl.app.memcached.php.
MENU_VERSIONS
const TplAppMemcached::MENU_VERSIONS = 'memcachedVersions'
Definition at line 20 of file class.tpl.app.memcached.php.
The documentation for this class was generated from the following file:
E:/Bearsampp-development/sandbox/core/classes/tpls/app/class.tpl.app.memcached.php