My Project: TplApp Class Reference
TplApp Class Reference
Static Public Member Functions
static getActionExec ()
static getActionMulti ($action, $args=array(), $item=array(), $disabled=false, $class=false)
static getActionRun ($action, $args=array(), $item=array(), $waitUntilTerminated=true)
static getMenu ($caption, $menu, $class)
static getMenuEnable ($caption, $menu, $class, $enabled=true)
static getSectionContent ($name, $class, $args=array())
static getSectionName ($name, $args=array())
static process ()
static processLight ()
Data Fields
const ITEM_CAPTION = 0
const ITEM_GLYPH = 1
const SECTION_CALL = 0
const SECTION_CONTENT = 1
Private Member Functions
__construct ()
Static Private Member Functions
static getSectionMenuLeft ()
static getSectionMenuRight ()
static getSectionServices ()
static getSectionStartupAction ()
Detailed Description
Class TplApp
This class provides various methods to generate and manage menu items, actions, and sections within the Bearsampp application. It includes functionalities for creating and processing different sections, running actions, and generating menus with various options.
Definition at line 17 of file class.tpl.app.php.
Constructor & Destructor Documentation
__construct()
TplApp::__construct () private
Private constructor to prevent instantiation.
Definition at line 29 of file class.tpl.app.php.
    {
    }
Member Function Documentation
getActionExec()
static TplApp::getActionExec () static
Generates an action string to execute a specific action.
Returns
string The generated action string.
Definition at line 176 of file class.tpl.app.php.
    {
        return self::getActionRun(Action::EXEC, array(), array(), false);
    }
References Action\EXEC, and getActionRun().
Referenced by getSectionStartupAction().
getActionMulti()
static TplApp::getActionMulti ($action, $args = array(), $item = array(), $disabled = false, $class = false) static
Generates a multi-action string for a specific action.
Parameters
string $action The action to run.
array $args Optional arguments for the action.
array $item Optional item details for the action.
bool $disabled Whether the action is disabled.
string $class The class name containing the method to generate the section content.
Returns
array An array containing the call string and the section content.
Definition at line 152 of file class.tpl.app.php.
    {
        $action = 'action' . ucfirst($action);
        $args = $args == null ? array() : $args;
        $sectionName = self::getSectionName($action, $args);
        $call = 'Action: multi; Actions: ' . $sectionName;
        if (!empty($item)) {
            $call = 'Type: item; ' . $call .
            '; Caption: "' . $item[self::ITEM_CAPTION] . '"' .
            (!empty($item[self::ITEM_GLYPH]) ? '; Glyph: "' . $item[self::ITEM_GLYPH] . '"' : '');
        } else {
            $call .= '; Flags: waituntilterminated';
        }
        return array($call, self::getSectionContent($action, $class, $args));
    }
References getSectionName(), ITEM_CAPTION, and ITEM_GLYPH.
Referenced by TplAppApache\getMenuApache(), TplAppApache\getMenuApacheAlias(), TplAppApache\getMenuApacheModules(), TplAppApache\getMenuApacheService(), TplAppApache\getMenuApacheVersions(), TplAppApache\getMenuApacheVhosts(), TplAppFilezilla\getMenuFilezilla(), TplAppFilezilla\getMenuFilezillaService(), TplAppFilezilla\getMenuFilezillaVersions(), TplAppGit\getMenuGit(), TplAppLang\getMenuLang(), TplAppLogsVerbose\getMenuLogsVerbose(), TplAppMailhog\getMenuMailhog(), TplAppMailhog\getMenuMailhogService(), TplAppMailhog\getMenuMailhogVersions(), TplAppMailpit\getMenuMailpit(), TplAppMailpit\getMenuMailpitService(), TplAppMailpit\getMenuMailpitVersions(), TplAppMariadb\getMenuMariadb(), TplAppMariadb\getMenuMariadbService(), TplAppMariadb\getMenuMariadbVersions(), TplAppMemcached\getMenuMemcached(), TplAppMemcached\getMenuMemcachedService(), TplAppMemcached\getMenuMemcachedVersions(), TplAppMysql\getMenuMysql(), TplAppMysql\getMenuMysqlService(), TplAppMysql\getMenuMysqlVersions(), TplAppNodejs\getMenuNodejs(), TplAppNodejs\getMenuNodejsVersions(), TplAppPhp\getMenuPhp(), TplAppPhp\getMenuPhpExtensions(), TplAppPhp\getMenuPhpSettings(), TplAppPhp\getMenuPhpVersions(), TplAppPostgresql\getMenuPostgresql(), TplAppPostgresql\getMenuPostgresqlService(), TplAppPostgresql\getMenuPostgresqlVersions(), TplAppTools\getMenuTools(), TplAppXlight\getMenuXlight(), TplAppXlight\getMenuXlightService(), TplAppXlight\getMenuXlightVersions(), TplAppPhp\getSubmenuPhpSettings(), TplAppBrowser\process(), TplAppExit\process(), TplAppLaunchStartup\process(), TplAppOnline\process(), TplAppReload\process(), and TplAppServices\process().
getActionRun()
static TplApp::getActionRun ($action, $args = array(), $item = array(), $waitUntilTerminated = true) static
Generates an action string to run a specific action.
Parameters
string $action The action to run.
array $args Optional arguments for the action.
array $item Optional item details for the action.
bool $waitUntilTerminated Whether to wait until the action is terminated.
@global object $bearsamppRoot Provides access to the root directory of the application. @global object $bearsamppCore Provides access to core functionalities and configurations.
Returns
string The generated action string.
Definition at line 115 of file class.tpl.app.php.
    {
        global $bearsamppRoot, $bearsamppCore;
        $args = $args == null ? array() : $args;
        $argImp = '';
        foreach ($args as $arg) {
            $argImp .= ' ' . base64_encode($arg);
        }
        $result = 'Action: run; ' .
            'FileName: "' . $bearsamppCore->getPhpExe(true) . '"; ' .
            'Parameters: "' . Core::isRoot_FILE . ' ' . $action . $argImp . '"; ' .
            'WorkingDir: "' . $bearsamppRoot->getCorePath(true) . '"';
        if (!empty($item)) {
            $result = 'Type: item; ' . $result .
                '; Caption: "' . $item[self::ITEM_CAPTION] . '"' .
                (!empty($item[self::ITEM_GLYPH]) ? '; Glyph: "' . $item[self::ITEM_GLYPH] . '"' : '');
        } elseif ($waitUntilTerminated) {
            $result .= '; Flags: waituntilterminated';
        }
        return $result;
    }
References $bearsamppCore, $bearsamppRoot, $result, Core\isRoot_FILE, ITEM_CAPTION, and ITEM_GLYPH.
Referenced by TplAppApache\getActionAddAlias(), TplAppApache\getActionAddVhost(), TplAppApache\getActionChangeApachePort(), TplAppBrowser\getActionChangeBrowser(), TplAppFilezilla\getActionChangeFilezillaPort(), TplAppMailhog\getActionChangeMailhogPort(), TplAppMailpit\getActionChangeMailpitPort(), TplAppMariadb\getActionChangeMariadbPort(), TplAppMariadb\getActionChangeMariadbRootPwd(), TplAppMemcached\getActionChangeMemcachedPort(), TplAppMysql\getActionChangeMysqlPort(), TplAppMysql\getActionChangeMysqlRootPwd(), TplAppPostgresql\getActionChangePostgresqlPort(), TplAppPostgresql\getActionChangePostgresqlRootPwd(), TplAppXlight\getActionChangeXlightPort(), TplService\getActionCreate(), TplAppApache\getActionEditAlias(), TplAppApache\getActionEditVhost(), TplAppApache\getActionEnableApache(), TplAppFilezilla\getActionEnableFilezilla(), TplAppMailhog\getActionEnableMailhog(), TplAppMailpit\getActionEnableMailpit(), TplAppMariadb\getActionEnableMariadb(), TplAppMemcached\getActionEnableMemcached(), TplAppMysql\getActionEnableMysql(), TplAppNodejs\getActionEnableNodejs(), TplAppPhp\getActionEnablePhp(), TplAppPostgresql\getActionEnablePostgresql(), TplAppXlight\getActionEnableXlight(), getActionExec(), TplAppExit\getActionExit(), TplAppTools\getActionGenSslCertificate(), TplService\getActionInstall(), TplAppApache\getActionInstallApacheService(), TplAppFilezilla\getActionInstallFilezillaService(), TplAppMailhog\getActionInstallMailhogService(), TplAppMailpit\getActionInstallMailpitService(), TplAppMariadb\getActionInstallMariadbService(), TplAppMemcached\getActionInstallMemcachedService(), TplAppMysql\getActionInstallMysqlService(), TplAppPostgresql\getActionInstallPostgresqlService(), TplAppXlight\getActionInstallXlightService(), TplAppLaunchStartup\getActionLaunchStartup(), TplAppGit\getActionRefreshGitRepos(), TplAppGit\getActionRefreshGitReposStartup(), TplAppReload\getActionReload(), TplService\getActionRemove(), TplAppApache\getActionRemoveApacheService(), TplAppFilezilla\getActionRemoveFilezillaService(), TplAppMailhog\getActionRemoveMailhogService(), TplAppMailpit\getActionRemoveMailpitService(), TplAppMariadb\getActionRemoveMariadbService(), TplAppMemcached\getActionRemoveMemcachedService(), TplAppMysql\getActionRemoveMysqlService(), TplAppPostgresql\getActionRemovePostgresqlService(), TplAppXlight\getActionRemoveXlightService(), TplService\getActionRestart(), TplService\getActionStart(), TplAppOnline\getActionStatus(), TplService\getActionStop(), TplAppApache\getActionSwitchApacheModule(), TplAppApache\getActionSwitchApacheVersion(), TplAppFilezilla\getActionSwitchFilezillaVersion(), TplAppLang\getActionSwitchLang(), TplAppLogsVerbose\getActionSwitchLogsVerbose(), TplAppMailhog\getActionSwitchMailhogVersion(), TplAppMailpit\getActionSwitchMailpitVersion(), TplAppMariadb\getActionSwitchMariadbVersion(), TplAppMemcached\getActionSwitchMemcachedVersion(), TplAppMysql\getActionSwitchMysqlVersion(), TplAppNodejs\getActionSwitchNodejsVersion(), TplAppPhp\getActionSwitchPhpExtension(), TplAppPhp\getActionSwitchPhpSetting(), TplAppPhp\getActionSwitchPhpVersion(), TplAppPostgresql\getActionSwitchPostgresqlVersion(), TplAppXlight\getActionSwitchXlightVersion(), TplService\getItemInstall(), TplService\getItemRemove(), TplService\getItemRestart(), TplService\getItemStart(), TplService\getItemStop(), TplAppApache\getMenuApacheDebug(), TplAppApache\getMenuApacheService(), TplAppFilezilla\getMenuFilezillaService(), TplAppMailhog\getMenuMailhogService(), TplAppMailpit\getMenuMailpitService(), TplAppMariadb\getMenuMariadbDebug(), TplAppMariadb\getMenuMariadbService(), TplAppMemcached\getMenuMemcachedService(), TplAppMysql\getMenuMysqlDebug(), TplAppMysql\getMenuMysqlService(), TplAppPostgresql\getMenuPostgresqlDebug(), TplAppPostgresql\getMenuPostgresqlService(), TplAppXlight\getMenuXlightService(), getSectionMenuRight(), getSectionStartupAction(), TplAppClearFolders\process(), and TplAppRebuildIni\process().
getMenu()
static TplApp::getMenu ($caption, $menu, $class) static
Generates a menu with the specified caption, menu name, and class.
Parameters
string $caption The caption for the menu.
string $menu The name of the menu.
string $class The class name containing the method to generate the menu content.
Returns
array An array containing the call string and the menu content.
Definition at line 190 of file class.tpl.app.php.
    {
        $menu = 'menu' . ucfirst($menu);
        $call = 'Type: submenu; ' .
            'Caption: "' . $caption . '"; ' .
            'SubMenu: ' . self::getSectionName($menu) . '; ' .
            'Glyph: ' . TplAestan::GLYPH_FOLDER_CLOSE;
        return array($call, self::getSectionContent($menu, $class, null));
    }
References getSectionName(), and TplAestan\GLYPH_FOLDER_CLOSE.
Referenced by TplAppApache\getMenuApache(), TplAppFilezilla\getMenuFilezilla(), TplAppGit\getMenuGit(), TplAppMailhog\getMenuMailhog(), TplAppMailpit\getMenuMailpit(), TplAppMariadb\getMenuMariadb(), TplAppMemcached\getMenuMemcached(), TplAppMysql\getMenuMysql(), TplAppNodejs\getMenuNodejs(), TplAppPhp\getMenuPhp(), TplAppPostgresql\getMenuPostgresql(), TplAppXlight\getMenuXlight(), TplAppApps\process(), TplAppGit\process(), TplAppLang\process(), TplAppLogs\process(), TplAppLogsVerbose\process(), TplAppPython\process(), and TplAppTools\process().
getMenuEnable()
static TplApp::getMenuEnable ($caption, $menu, $class, $enabled = true) static
Generates a menu with the specified caption, menu name, class, and enabled state.
Parameters
string $caption The caption for the menu.
string $menu The name of the menu.
string $class The class name containing the method to generate the menu content.
bool $enabled Whether the menu is enabled.
Returns
array An array containing the call string and the menu content.
Definition at line 212 of file class.tpl.app.php.
    {
        $menu = 'menu' . ucfirst($menu);
        $call = 'Type: submenu; ' .
            'Caption: "' . $caption . '"; ' .
            'SubMenu: ' . self::getSectionName($menu) . '; ' .
            'Glyph: ' . ($enabled ? TplAestan::GLYPH_FOLDER_CLOSE : TplAestan::GLYPH_FOLDER_DISABLED);
        return array($call, self::getSectionContent($menu, $class, null));
    }
References getSectionName(), TplAestan\GLYPH_FOLDER_CLOSE, and TplAestan\GLYPH_FOLDER_DISABLED.
Referenced by TplAppApache\process(), TplAppFilezilla\process(), TplAppMailhog\process(), TplAppMailpit\process(), TplAppMariadb\process(), TplAppMemcached\process(), TplAppMysql\process(), TplAppNodejs\process(), TplAppPhp\process(), TplAppPostgresql\process(), and TplAppXlight\process().
getSectionContent()
static TplApp::getSectionContent ($name, $class, $args = array()) static
Generates the content of a section based on the provided name, class, and arguments.
Parameters
string $name The base name of the section.
string $class The class name containing the method to generate the section content.
array $args Optional arguments to pass to the method.
Returns
string The generated section content.
Definition at line 94 of file class.tpl.app.php.
    {
        $baseMethod = 'get' . ucfirst($name);
        $args = $args == null ? array() : $args;
        return '[' . self::getSectionName($name, $args) . ']' . PHP_EOL .
            call_user_func_array($class . '::' . $baseMethod, $args);
    }
References getSectionName().
getSectionMenuLeft()
static TplApp::getSectionMenuLeft () static private
Generates the left menu section.
@global object $bearsamppRoot Provides access to the root directory of the application. @global object $bearsamppBins Provides access to system binaries and their configurations. @global object $bearsamppLang Provides language support for retrieving language-specific values.
Returns
string The generated left menu section.
Definition at line 319 of file class.tpl.app.php.
    {
        global $bearsamppRoot, $bearsamppBins, $bearsamppLang;
        $tplNodejs = TplAppNodejs::process();
        $tplApache = TplAppApache::process();
        $tplPhp = TplAppPhp::process();
        $tplMysql = TplAppMysql::process();
        $tplMariadb = TplAppMariadb::process();
        $tplPostgresql = TplAppPostgresql::process();
        $tplMailhog = TplAppMailhog::process();
        $tplMailpit = TplAppMailpit::process();
        $tplMemcached = TplAppMemcached::process();
        $tplFilezilla = TplAppFilezilla::process();
        $tplXlight = TplAppXlight::process();
        $tplLogs = TplAppLogs::process();
        $tplApps = TplAppApps::process();
        $tplTools = TplAppTools::process();
        $tplServices = TplAppServices::process();
        $tplOnline = TplAppOnline::process();
        $httpUrl = 'http://localhost' . ($bearsamppBins->getApache()->getPort() != 80 ? ':' . $bearsamppBins->getApache()->getPort() : '');
        $httpsUrl = 'https://localhost' . ($bearsamppBins->getApache()->getSslPort() != 443 ? ':' . $bearsamppBins->getApache()->getSslPort() : '');
        return
            // Items
            '[Menu.Left]' . PHP_EOL .
            TplAestan::getItemLink($bearsamppLang->getValue(Lang::MENU_LOCALHOST), $httpUrl) . PHP_EOL .
            TplAestan::getItemLink($bearsamppLang->getValue(Lang::MENU_LOCALHOST) . ' (SSL)', $httpsUrl) . PHP_EOL .
            TplAestan::getItemExplore($bearsamppLang->getValue(Lang::MENU_WWW_DIRECTORY), $bearsamppRoot->getWwwPath()) . PHP_EOL .
            //// Bins menus
            TplAestan::getItemSeparator() . PHP_EOL .
            $tplNodejs[self::SECTION_CALL] . PHP_EOL .
            $tplApache[self::SECTION_CALL] . PHP_EOL .
            $tplPhp[self::SECTION_CALL] . PHP_EOL .
            $tplMysql[self::SECTION_CALL] . PHP_EOL .
            $tplMariadb[self::SECTION_CALL] . PHP_EOL .
            $tplPostgresql[self::SECTION_CALL] . PHP_EOL .
            $tplMailhog[self::SECTION_CALL] . PHP_EOL .
            $tplMailpit[self::SECTION_CALL] . PHP_EOL .
            $tplMemcached[self::SECTION_CALL] . PHP_EOL .
            $tplXlight[self::SECTION_CALL] . PHP_EOL .
            $tplFilezilla[self::SECTION_CALL] . PHP_EOL .
            //// Stuff menus
            TplAestan::getItemSeparator() . PHP_EOL .
            $tplLogs[self::SECTION_CALL] . PHP_EOL .
            $tplTools[self::SECTION_CALL] . PHP_EOL .
            $tplApps[self::SECTION_CALL] . PHP_EOL .
            //// Services
            TplAestan::getItemSeparator() . PHP_EOL .
            $tplServices[self::SECTION_CALL] .
            //// Put online/offline
            TplAestan::getItemSeparator() . PHP_EOL .
            $tplOnline[self::SECTION_CALL] . PHP_EOL .
            // Actions
            PHP_EOL . $tplNodejs[self::SECTION_CONTENT] .
            PHP_EOL . $tplApache[self::SECTION_CONTENT] .
            PHP_EOL . $tplPhp[self::SECTION_CONTENT] .
            PHP_EOL . $tplMysql[self::SECTION_CONTENT] .
            PHP_EOL . $tplMariadb[self::SECTION_CONTENT] .
            PHP_EOL . $tplPostgresql[self::SECTION_CONTENT] .
            PHP_EOL . $tplMailhog[self::SECTION_CONTENT] .
            PHP_EOL . $tplMailpit[self::SECTION_CONTENT] .
            PHP_EOL . $tplMemcached[self::SECTION_CONTENT] .
            PHP_EOL . $tplFilezilla[self::SECTION_CONTENT] .
            PHP_EOL . $tplXlight[self::SECTION_CONTENT] .
            PHP_EOL . $tplLogs[self::SECTION_CONTENT] .
            PHP_EOL . $tplTools[self::SECTION_CONTENT] .
            PHP_EOL . $tplApps[self::SECTION_CONTENT] .
            PHP_EOL . $tplServices[self::SECTION_CONTENT] .
            PHP_EOL . $tplOnline[self::SECTION_CONTENT];
    }
References $bearsamppBins, $bearsamppLang, $bearsamppRoot, TplAestan\getItemExplore(), TplAestan\getItemLink(), TplAestan\getItemSeparator(), Lang\MENU_LOCALHOST, Lang\MENU_WWW_DIRECTORY, TplAppApache\process(), TplAppApps\process(), TplAppFilezilla\process(), TplAppLogs\process(), TplAppMailhog\process(), TplAppMailpit\process(), TplAppMariadb\process(), TplAppMemcached\process(), TplAppMysql\process(), TplAppNodejs\process(), TplAppOnline\process(), TplAppPhp\process(), TplAppPostgresql\process(), TplAppServices\process(), TplAppTools\process(), TplAppXlight\process(), SECTION_CALL, and SECTION_CONTENT.
Referenced by process().
getSectionMenuRight()
static TplApp::getSectionMenuRight () static private
Generates the right menu section.
@global object $bearsamppLang Provides language support for retrieving language-specific values.
Returns
string The generated right menu section.
Definition at line 264 of file class.tpl.app.php.
    {
        global $bearsamppLang;
        $tplReload = TplAppReload::process();
        $tplBrowser = TplAppBrowser::process();
        $tplLang = TplAppLang::process();
        $tplLogsVerbose = TplAppLogsVerbose::process();
        $tplLaunchStartup = TplAppLaunchStartup::process();
        $tplExit = TplAppExit::process();
        return
            // Items
            '[Menu.Right]' . PHP_EOL .
            self::getActionRun(Action::ABOUT, null, array($bearsamppLang->getValue(Lang::MENU_ABOUT), TplAestan::GLYPH_ABOUT)) . PHP_EOL .
            self::getActionRun(
                Action::CHECK_VERSION,
                array(ActionCheckVersion::DISPLAY_OK),
                array($bearsamppLang->getValue(Lang::MENU_CHECK_UPDATE), TplAestan::GLYPH_UPDATE)
            ) . PHP_EOL .
            TplAestan::getItemLink($bearsamppLang->getValue(Lang::HELP), Util::getWebsiteUrl('faq')) . PHP_EOL .
            TplAestan::getItemSeparator() . PHP_EOL .
            $tplReload[self::SECTION_CALL] . PHP_EOL .
            TplAppClearFolders::process() . PHP_EOL .
            TplAppRebuildIni::process() . PHP_EOL .
            $tplBrowser[self::SECTION_CALL] . PHP_EOL .
            TplAppEditConf::process() . PHP_EOL .
            TplAestan::getItemSeparator() . PHP_EOL .
            $tplLang[self::SECTION_CALL] . PHP_EOL .
            $tplLogsVerbose[self::SECTION_CALL] . PHP_EOL .
            $tplLaunchStartup[self::SECTION_CALL] . PHP_EOL .
            TplAestan::getItemSeparator() . PHP_EOL .
            $tplExit[self::SECTION_CALL] . PHP_EOL .
            // Actions
            PHP_EOL . $tplReload[self::SECTION_CONTENT] . PHP_EOL .
            PHP_EOL . $tplBrowser[self::SECTION_CONTENT] . PHP_EOL .
            PHP_EOL . $tplLang[self::SECTION_CONTENT] .
            PHP_EOL . $tplLogsVerbose[self::SECTION_CONTENT] .
            PHP_EOL . $tplLaunchStartup[self::SECTION_CONTENT] .
            PHP_EOL . $tplExit[self::SECTION_CONTENT] . PHP_EOL;
    }
References $bearsamppLang, Action\ABOUT, Action\CHECK_VERSION, ActionCheckVersion\DISPLAY_OK, getActionRun(), TplAestan\getItemLink(), TplAestan\getItemSeparator(), Util\getWebsiteUrl(), TplAestan\GLYPH_ABOUT, TplAestan\GLYPH_UPDATE, Lang\HELP, Lang\MENU_ABOUT, Lang\MENU_CHECK_UPDATE, TplAppBrowser\process(), TplAppClearFolders\process(), TplAppEditConf\process(), TplAppExit\process(), TplAppLang\process(), TplAppLaunchStartup\process(), TplAppLogsVerbose\process(), TplAppRebuildIni\process(), TplAppReload\process(), SECTION_CALL, and SECTION_CONTENT.
Referenced by process().
getSectionName()
static TplApp::getSectionName ($name, $args = array()) static
Generates a section name based on the provided name and arguments.
Parameters
string $name The base name of the section.
array $args Optional arguments to include in the section name.
Returns
string The generated section name.
Definition at line 80 of file class.tpl.app.php.
    {
        return ucfirst($name) . (!empty($args) ? '-' . md5(serialize($args)) : '');
    }
Referenced by getActionMulti(), getMenu(), getMenuEnable(), and getSectionContent().
getSectionServices()
static TplApp::getSectionServices () static private
Generates the services section.
@global object $bearsamppBins Provides access to system binaries and their configurations.
Returns
string The generated services section.
Definition at line 231 of file class.tpl.app.php.
    {
        global $bearsamppBins;
        $result = '[Services]' . PHP_EOL;
        foreach ($bearsamppBins->getServices() as $service) {
            $result .= 'Name: ' . $service->getName() . PHP_EOL;
        }
        return $result;
    }
References $bearsamppBins, and $result.
Referenced by process(), and processLight().
getSectionStartupAction()
static TplApp::getSectionStartupAction () static private
Generates the startup action section.
Returns
string The generated startup action section.
Definition at line 248 of file class.tpl.app.php.
    {
        return '[StartupAction]' . PHP_EOL .
            self::getActionRun(Action::STARTUP) . PHP_EOL .
            TplAppReload::getActionReload() . PHP_EOL .
            self::getActionRun(Action::CHECK_VERSION) . PHP_EOL .
            self::getActionExec() . PHP_EOL;
    }
References Action\CHECK_VERSION, getActionExec(), TplAppReload\getActionReload(), getActionRun(), and Action\STARTUP.
Referenced by process(), and processLight().
process()
static TplApp::process () static
Processes and generates the main sections of the application.
This method generates the main sections of the application, including configuration, services, messages, startup actions, and menu settings.
@global object $bearsamppCore Provides access to core functionalities and configurations.
Returns
string The generated sections as a concatenated string.
Definition at line 43 of file class.tpl.app.php.
    {
        global $bearsamppCore;
        return TplAestan::getSectionConfig() . PHP_EOL .
            self::getSectionServices() . PHP_EOL .
            TplAestan::getSectionMessages() . PHP_EOL .
            self::getSectionStartupAction() . PHP_EOL .
            TplAestan::getSectionMenuRightSettings() . PHP_EOL .
            TplAestan::getSectionMenuLeftSettings(APP_TITLE . ' ' . $bearsamppCore->getAppVersion()) . PHP_EOL .
            self::getSectionMenuRight() . PHP_EOL .
            self::getSectionMenuLeft() . PHP_EOL;
    }
References $bearsamppCore, APP_TITLE, TplAestan\getSectionConfig(), getSectionMenuLeft(), TplAestan\getSectionMenuLeftSettings(), getSectionMenuRight(), TplAestan\getSectionMenuRightSettings(), TplAestan\getSectionMessages(), getSectionServices(), and getSectionStartupAction().
Referenced by ActionReload\__construct().
processLight()
static TplApp::processLight () static
Processes and generates a lighter version of the main sections.
This method generates a lighter version of the main sections, excluding some menu settings.
Returns
string The generated sections as a concatenated string.
Definition at line 64 of file class.tpl.app.php.
    {
        return TplAestan::getSectionConfig() . PHP_EOL .
            self::getSectionServices() . PHP_EOL .
            TplAestan::getSectionMessages() . PHP_EOL .
            self::getSectionStartupAction() . PHP_EOL;
    }
References TplAestan\getSectionConfig(), TplAestan\getSectionMessages(), getSectionServices(), and getSectionStartupAction().
Field Documentation
ITEM_CAPTION
const TplApp::ITEM_CAPTION = 0
Definition at line 20 of file class.tpl.app.php.
Referenced by getActionMulti(), and getActionRun().
ITEM_GLYPH
const TplApp::ITEM_GLYPH = 1
Definition at line 21 of file class.tpl.app.php.
Referenced by getActionMulti(), and getActionRun().
SECTION_CALL
const TplApp::SECTION_CALL = 0
Definition at line 23 of file class.tpl.app.php.
Referenced by TplAppApache\getMenuApache(), TplAppApache\getMenuApacheAlias(), TplAppApache\getMenuApacheModules(), TplAppApache\getMenuApacheService(), TplAppApache\getMenuApacheVersions(), TplAppApache\getMenuApacheVhosts(), TplAppFilezilla\getMenuFilezilla(), TplAppFilezilla\getMenuFilezillaService(), TplAppFilezilla\getMenuFilezillaVersions(), TplAppGit\getMenuGit(), TplAppLang\getMenuLang(), TplAppLogsVerbose\getMenuLogsVerbose(), TplAppMailhog\getMenuMailhog(), TplAppMailhog\getMenuMailhogService(), TplAppMailhog\getMenuMailhogVersions(), TplAppMailpit\getMenuMailpit(), TplAppMailpit\getMenuMailpitService(), TplAppMailpit\getMenuMailpitVersions(), TplAppMariadb\getMenuMariadb(), TplAppMariadb\getMenuMariadbService(), TplAppMariadb\getMenuMariadbVersions(), TplAppMemcached\getMenuMemcached(), TplAppMemcached\getMenuMemcachedService(), TplAppMemcached\getMenuMemcachedVersions(), TplAppMysql\getMenuMysql(), TplAppMysql\getMenuMysqlService(), TplAppMysql\getMenuMysqlVersions(), TplAppNodejs\getMenuNodejs(), TplAppNodejs\getMenuNodejsVersions(), TplAppPhp\getMenuPhp(), TplAppPhp\getMenuPhpExtensions(), TplAppPhp\getMenuPhpSettings(), TplAppPhp\getMenuPhpVersions(), TplAppPostgresql\getMenuPostgresql(), TplAppPostgresql\getMenuPostgresqlService(), TplAppPostgresql\getMenuPostgresqlVersions(), TplAppTools\getMenuTools(), TplAppXlight\getMenuXlight(), TplAppXlight\getMenuXlightService(), TplAppXlight\getMenuXlightVersions(), getSectionMenuLeft(), getSectionMenuRight(), TplAppPhp\getSubmenuPhpSettings(), and TplAppServices\process().
SECTION_CONTENT
const TplApp::SECTION_CONTENT = 1
Definition at line 24 of file class.tpl.app.php.
Referenced by TplAppApache\getMenuApache(), TplAppApache\getMenuApacheAlias(), TplAppApache\getMenuApacheModules(), TplAppApache\getMenuApacheService(), TplAppApache\getMenuApacheVersions(), TplAppApache\getMenuApacheVhosts(), TplAppFilezilla\getMenuFilezilla(), TplAppFilezilla\getMenuFilezillaService(), TplAppFilezilla\getMenuFilezillaVersions(), TplAppGit\getMenuGit(), TplAppLang\getMenuLang(), TplAppLogsVerbose\getMenuLogsVerbose(), TplAppMailhog\getMenuMailhog(), TplAppMailhog\getMenuMailhogService(), TplAppMailhog\getMenuMailhogVersions(), TplAppMailpit\getMenuMailpit(), TplAppMailpit\getMenuMailpitService(), TplAppMailpit\getMenuMailpitVersions(), TplAppMariadb\getMenuMariadb(), TplAppMariadb\getMenuMariadbService(), TplAppMariadb\getMenuMariadbVersions(), TplAppMemcached\getMenuMemcached(), TplAppMemcached\getMenuMemcachedService(), TplAppMemcached\getMenuMemcachedVersions(), TplAppMysql\getMenuMysql(), TplAppMysql\getMenuMysqlService(), TplAppMysql\getMenuMysqlVersions(), TplAppNodejs\getMenuNodejs(), TplAppNodejs\getMenuNodejsVersions(), TplAppPhp\getMenuPhp(), TplAppPhp\getMenuPhpExtensions(), TplAppPhp\getMenuPhpSettings(), TplAppPhp\getMenuPhpVersions(), TplAppPostgresql\getMenuPostgresql(), TplAppPostgresql\getMenuPostgresqlService(), TplAppPostgresql\getMenuPostgresqlVersions(), TplAppTools\getMenuTools(), TplAppXlight\getMenuXlight(), TplAppXlight\getMenuXlightService(), TplAppXlight\getMenuXlightVersions(), getSectionMenuLeft(), getSectionMenuRight(), TplAppPhp\getSubmenuPhpSettings(), and TplAppServices\process().
The documentation for this class was generated from the following file:
E:/Bearsampp-development/sandbox/core/classes/tpls/class.tpl.app.php