Bearsampp: AppPhppgadmin Class Reference
AppPhppgadmin Class Reference
Public Member Functions
__construct ($id, $type)
getConf ()
reload ($id=null, $type=null)
setVersion ($version)
Public Member Functions inherited from Module
__toString ()
getCurrentPath ()
getId ()
getName ()
getRelease ()
getRootPath ()
getSymlinkPath ()
getType ()
getVersion ()
getVersionList ()
isEnable ()
update ($sub=0, $showWindow=false)
Data Fields
const LOCAL_CFG_CONF = 'phppgadminConf'
const ROOT_CFG_VERSION = 'phppgadminVersion'
Data Fields inherited from Module
const BUNDLE_RELEASE = 'bundleRelease'
Protected Member Functions
updateConfig ($version=null, $sub=0, $showWindow=false)
Protected Member Functions inherited from Module
__construct ()
replace ($key, $value)
replaceAll ($params)
Private Attributes
$conf
Additional Inherited Members
Protected Attributes inherited from Module
$bearsamppConf
$bearsamppConfRaw
$currentPath
$enable
$name
$release = 'N/A'
$rootPath
$symlinkPath
$version
Detailed Description
Class AppPhppgadmin
This class represents the phpPgAdmin application module in the Bearsampp application. It handles the initialization, configuration, and management of the phpPgAdmin module.
Definition at line 16 of file class.app.phppgadmin.php.
Constructor & Destructor Documentation
__construct()
AppPhppgadmin::__construct ($id, $type)
Constructor for the AppPhppgadmin class.
Parameters
string $id The ID of the module.
string $type The type of the module.
Definition at line 39 of file class.app.phppgadmin.php.
{
        Util::logInitClass($this);
        $this->reload($id, $type);
    }
References Module\$id, Module\$type, Util\logInitClass(), and reload().
Member Function Documentation
getConf()
AppPhppgadmin::getConf ()
Gets the path to the phpPgAdmin configuration file.
Returns
string The path to the configuration file.
Definition at line 139 of file class.app.phppgadmin.php.
{
        return $this->conf;
    }
Referenced by updateConfig().
reload()
AppPhppgadmin::reload ($id = null, $type = null)
Reloads the module configuration based on the provided ID and type.
Parameters
string | null $id The ID of the module. If null, the current ID is used.
string | null $type The type of the module. If null, the current type is used.
Reimplemented from Module.
Definition at line 50 of file class.app.phppgadmin.php.
{
        global $bearsamppConfig, $bearsamppLang;
        Util::logReloadClass($this);
        $this->name = $bearsamppLang->getValue(Lang::PHPPGADMIN);
        $this->version = $bearsamppConfig->getRaw(self::ROOT_CFG_VERSION);
        parent::reload($id, $type);
        if ($this->bearsamppConfRaw !== false) {
            $this->conf = $this->symlinkPath . '/' . $this->bearsamppConfRaw[self::LOCAL_CFG_CONF];
        }
        if (!$this->enable) {
            Util::logInfo($this->name . ' is not enabled!');
            return;
        }
        if (!is_dir($this->currentPath)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_FILE_NOT_FOUND), $this->name . ' ' . $this->version, $this->currentPath));
        }
        if (!is_dir($this->symlinkPath)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_FILE_NOT_FOUND), $this->name . ' ' . $this->version, $this->symlinkPath));
            return;
        }
        if (!is_file($this->bearsamppConf)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_CONF_NOT_FOUND), $this->name . ' ' . $this->version, $this->bearsamppConf));
        }
        if (!is_file($this->conf)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_CONF_NOT_FOUND), $this->name . ' ' . $this->version, $this->conf));
        }
    }
References $bearsamppConfig, $bearsamppLang, Module\$id, Module\$type, Lang\ERROR_CONF_NOT_FOUND, Lang\ERROR_FILE_NOT_FOUND, LOCAL_CFG_CONF, Util\logError(), Util\logInfo(), Util\logReloadClass(), and Lang\PHPPGADMIN.
Referenced by __construct().
setVersion()
AppPhppgadmin::setVersion ($version)
Sets the version of the module.
Parameters
string $version The version to set.
Reimplemented from Module.
Definition at line 127 of file class.app.phppgadmin.php.
{
        global $bearsamppConfig;
        $this->version = $version;
        $bearsamppConfig->replace(self::ROOT_CFG_VERSION, $version);
        $this->reload();
    }
updateConfig()
AppPhppgadmin::updateConfig ($version = null, $sub = 0, $showWindow = false) protected
Updates the module configuration with a specific version.
Parameters
string | null $version The version to update to. If null, the current version is used.
int $sub The sub-level for logging indentation.
bool $showWindow Whether to show a window during the update process.
Returns
bool True if the update was successful, false otherwise.
Reimplemented from Module.
Definition at line 89 of file class.app.phppgadmin.php.
{
        global $bearsamppRoot, $bearsamppBins;
        if (!$this->enable) {
            return true;
        }
        $version = $version == null ? $this->version : $version;
        Util::logDebug(($sub > 0 ? str_repeat(' ', 2 * $sub) : '') . 'Update ' . $this->name . ' ' . $version . ' config');
        $alias = $bearsamppRoot->getAliasPath() . '/phppgadmin.conf';
        if (is_file($alias)) {
            Util::replaceInFile($alias, array(
                '/^Alias\s\/phppgadmin\s.*/' => 'Alias /phppgadmin "' . $this->getSymlinkPath() . '/"',
                '/^<Directory\s.*/' => '<Directory "' . $this->getSymlinkPath() . '/">',
            ));
        } else {
            Util::logError($this->getName() . ' alias not found : ' . $alias);
        }
        if ($bearsamppBins->getPostgresql()->isEnable()) {
            Util::replaceInFile($this->getConf(), array(
                '/^\$postgresqlPort\s=\s(\d+)/' => '$postgresqlPort = ' . $bearsamppBins->getPostgresql()->getPort() . ';',
                '/^\$postgresqlRootUser\s=\s/' => '$postgresqlRootUser = \'' . $bearsamppBins->getPostgresql()->getRootUser() . '\';',
                '/^\$postgresqlRootPwd\s=\s/' => '$postgresqlRootPwd = \'' . $bearsamppBins->getPostgresql()->getRootPwd() . '\';',
                '/^\$postgresqlDumpExe\s=\s/' => '$postgresqlDumpExe = \'' . $bearsamppBins->getPostgresql()->getDumpExe() . '\';',
                '/^\$postgresqlDumpAllExe\s=\s/' => '$postgresqlDumpAllExe = \'' . $bearsamppBins->getPostgresql()->getDumpAllExe() . '\';',
            ));
        }
        return true;
    }
References $bearsamppBins, $bearsamppRoot, Module\$version, getConf(), Module\getName(), Module\getSymlinkPath(), Util\logDebug(), Util\logError(), and Util\replaceInFile().
Field Documentation
$conf
AppPhppgadmin::$conf private
Definition at line 31 of file class.app.phppgadmin.php.
LOCAL_CFG_CONF
const AppPhppgadmin::LOCAL_CFG_CONF = 'phppgadminConf'
Configuration key for the phpPgAdmin configuration file in the local configuration.
Definition at line 26 of file class.app.phppgadmin.php.
Referenced by reload().
ROOT_CFG_VERSION
const AppPhppgadmin::ROOT_CFG_VERSION = 'phppgadminVersion'
Configuration key for the phpPgAdmin version in the root configuration.
Definition at line 21 of file class.app.phppgadmin.php.
The documentation for this class was generated from the following file:
E:/Bearsampp-development/sandbox/core/classes/apps/class.app.phppgadmin.php