Bearsampp: TplAppPostgresql Class Reference
TplAppPostgresql Class Reference
Static Public Member Functions
static getActionChangePostgresqlPort ()
static getActionChangePostgresqlRootPwd ()
static getActionEnablePostgresql ($enable)
static getActionInstallPostgresqlService ()
static getActionRemovePostgresqlService ()
static getActionSwitchPostgresqlVersion ($version)
static getMenuPostgresql ()
static getMenuPostgresqlDebug ()
static getMenuPostgresqlService ()
static getMenuPostgresqlVersions ()
static process ()
Data Fields
const ACTION_CHANGE_PORT = 'changePostgresqlPort'
const ACTION_CHANGE_ROOT_PWD = 'changePostgresqlRootPwd'
const ACTION_ENABLE = 'enablePostgresql'
const ACTION_INSTALL_SERVICE = 'installPostgresqlService'
const ACTION_REMOVE_SERVICE = 'removePostgresqlService'
const ACTION_SWITCH_VERSION = 'switchPostgresqlVersion'
const MENU = 'postgresql'
const MENU_DEBUG = 'postgresqlDebug'
const MENU_SERVICE = 'postgresqlService'
const MENU_VERSIONS = 'postgresqlVersions'
Detailed Description
Class TplAppPostgresql
This class provides methods to generate menu items and actions for managing PostgreSQL services within the Bearsampp application. It includes functionalities for enabling/disabling PostgreSQL, switching versions, changing ports, changing root passwords, and managing services.
Definition at line 17 of file class.tpl.app.postgresql.php.
Member Function Documentation
getActionChangePostgresqlPort()
static TplAppPostgresql::getActionChangePostgresqlPort () static
Generates the action to change the PostgreSQL port.
@global object $bearsamppBins Provides access to system binaries and their configurations.
Returns
string The generated action to change the PostgreSQL port.
Definition at line 267 of file class.tpl.app.postgresql.php.
    {
        global $bearsamppBins;
        return TplApp::getActionRun(Action::CHANGE_PORT, array($bearsamppBins->getPostgresql()->getName())) . PHP_EOL .
            TplAppReload::getActionReload();
    }
References $bearsamppBins, Action\CHANGE_PORT, TplAppReload\getActionReload(), and TplApp\getActionRun().
getActionChangePostgresqlRootPwd()
static TplAppPostgresql::getActionChangePostgresqlRootPwd () static
Generates the action to change the PostgreSQL root password.
@global object $bearsamppBins Provides access to system binaries and their configurations.
Returns
string The generated action to change the PostgreSQL root password.
Definition at line 282 of file class.tpl.app.postgresql.php.
    {
        global $bearsamppBins;
        return TplApp::getActionRun(Action::CHANGE_DB_ROOT_PWD, array($bearsamppBins->getPostgresql()->getName())) . PHP_EOL .
            TplAppReload::getActionReload();
    }
References $bearsamppBins, Action\CHANGE_DB_ROOT_PWD, TplAppReload\getActionReload(), and TplApp\getActionRun().
getActionEnablePostgresql()
static TplAppPostgresql::getActionEnablePostgresql ($enable) static
Generates the action to enable or disable PostgreSQL.
@global object $bearsamppBins Provides access to system binaries and their configurations.
Parameters
int $enable The flag to enable (1) or disable (0) PostgreSQL.
Returns
string The generated action to enable or disable PostgreSQL.
Definition at line 152 of file class.tpl.app.postgresql.php.
    {
        global $bearsamppBins;
        return TplApp::getActionRun(Action::ENABLE, array($bearsamppBins->getPostgresql()->getName(), $enable)) . PHP_EOL .
            TplAppReload::getActionReload();
    }
References $bearsamppBins, Action\ENABLE, TplAppReload\getActionReload(), and TplApp\getActionRun().
getActionInstallPostgresqlService()
static TplAppPostgresql::getActionInstallPostgresqlService () static
Generates the action to install the PostgreSQL service.
Returns
string The generated action to install the PostgreSQL service.
Definition at line 295 of file class.tpl.app.postgresql.php.
    {
        return TplApp::getActionRun(Action::SERVICE, array(BinPostgresql::SERVICE_NAME, ActionService::INSTALL)) . PHP_EOL .
            TplAppReload::getActionReload();
    }
References TplAppReload\getActionReload(), TplApp\getActionRun(), ActionService\INSTALL, Action\SERVICE, and BinPostgresql\SERVICE_NAME.
getActionRemovePostgresqlService()
static TplAppPostgresql::getActionRemovePostgresqlService () static
Generates the action to remove the PostgreSQL service.
Returns
string The generated action to remove the PostgreSQL service.
Definition at line 306 of file class.tpl.app.postgresql.php.
    {
        return TplApp::getActionRun(Action::SERVICE, array(BinPostgresql::SERVICE_NAME, ActionService::REMOVE)) . PHP_EOL .
            TplAppReload::getActionReload();
    }
References TplAppReload\getActionReload(), TplApp\getActionRun(), ActionService\REMOVE, Action\SERVICE, and BinPostgresql\SERVICE_NAME.
getActionSwitchPostgresqlVersion()
static TplAppPostgresql::getActionSwitchPostgresqlVersion ($version) static
Generates the action to switch the PostgreSQL version.
@global object $bearsamppBins Provides access to system binaries and their configurations.
Parameters
string $version The version to switch to.
Returns
string The generated action to switch the PostgreSQL version.
Definition at line 168 of file class.tpl.app.postgresql.php.
    {
        global $bearsamppBins;
        return TplApp::getActionRun(Action::SWITCH_VERSION, array($bearsamppBins->getPostgresql()->getName(), $version)) . PHP_EOL .
            TplAppReload::getActionReload() . PHP_EOL;
    }
References $bearsamppBins, TplAppReload\getActionReload(), TplApp\getActionRun(), and Action\SWITCH_VERSION.
getMenuPostgresql()
static TplAppPostgresql::getMenuPostgresql () static
Generates the PostgreSQL menu with options for versions, service, debug, and console access.
@global object $bearsamppBins Provides access to system binaries and their configurations. @global object $bearsamppLang Provides language support for retrieving language-specific values. @global object $bearsamppTools Provides access to various tools and utilities.
Returns
string The generated menu items and actions for PostgreSQL.
Definition at line 55 of file class.tpl.app.postgresql.php.
    {
        global $bearsamppBins, $bearsamppLang, $bearsamppTools;
        $resultItems = $resultActions = '';
        $isEnabled = $bearsamppBins->getPostgresql()->isEnable();
        // Download
        $resultItems .= TplAestan::getItemLink(
            $bearsamppLang->getValue(Lang::DOWNLOAD_MORE),
            Util::getWebsiteUrl('module/postgresql', '#releases'),
            false,
            TplAestan::GLYPH_BROWSER
        ) . PHP_EOL;
        // Enable
        $tplEnable = TplApp::getActionMulti(
            self::ACTION_ENABLE, array($isEnabled ? Config::DISABLED : Config::ENABLED),
            array($bearsamppLang->getValue(Lang::MENU_ENABLE), $isEnabled ? TplAestan::GLYPH_CHECK : ''),
            false, get_called_class()
        );
        $resultItems .= $tplEnable[TplApp::SECTION_CALL] . PHP_EOL;
        $resultActions .= $tplEnable[TplApp::SECTION_CONTENT] . PHP_EOL;
        if ($isEnabled) {
            $resultItems .= TplAestan::getItemSeparator() . PHP_EOL;
            // Versions
            $tplVersions = TplApp::getMenu($bearsamppLang->getValue(Lang::VERSIONS), self::MENU_VERSIONS, get_called_class());
            $resultItems .= $tplVersions[TplApp::SECTION_CALL] . PHP_EOL;
            $resultActions .= $tplVersions[TplApp::SECTION_CONTENT] . PHP_EOL;
            // Service
            $tplService = TplApp::getMenu($bearsamppLang->getValue(Lang::SERVICE), self::MENU_SERVICE, get_called_class());
            $resultItems .= $tplService[TplApp::SECTION_CALL] . PHP_EOL;
            $resultActions .= $tplService[TplApp::SECTION_CONTENT] . PHP_EOL;
            // Debug
            $tplDebug = TplApp::getMenu($bearsamppLang->getValue(Lang::DEBUG), self::MENU_DEBUG, get_called_class());
            $resultItems .= $tplDebug[TplApp::SECTION_CALL] . PHP_EOL;
            $resultActions .= $tplDebug[TplApp::SECTION_CONTENT];
            // Console
            $resultItems .= TplAestan::getItemConsoleZ(
                $bearsamppLang->getValue(Lang::CONSOLE),
                TplAestan::GLYPH_CONSOLEZ,
                $bearsamppTools->getConsoleZ()->getTabTitlePostgresql()
            ) . PHP_EOL;
            // Conf
            $resultItems .= TplAestan::getItemNotepad(basename($bearsamppBins->getPostgresql()->getConf()), $bearsamppBins->getPostgresql()->getConf()) . PHP_EOL;
            // Errors log
            $resultItems .= TplAestan::getItemNotepad($bearsamppLang->getValue(Lang::MENU_ERROR_LOGS), $bearsamppBins->getPostgresql()->getErrorLog()) . PHP_EOL;
        }
        return $resultItems . PHP_EOL . $resultActions;
    }
References $bearsamppBins, $bearsamppLang, Lang\CONSOLE, Lang\DEBUG, Config\DISABLED, Lang\DOWNLOAD_MORE, Config\ENABLED, TplApp\getActionMulti(), TplAestan\getItemConsoleZ(), TplAestan\getItemLink(), TplAestan\getItemNotepad(), TplAestan\getItemSeparator(), TplApp\getMenu(), Util\getWebsiteUrl(), TplAestan\GLYPH_BROWSER, TplAestan\GLYPH_CHECK, TplAestan\GLYPH_CONSOLEZ, Lang\MENU_ENABLE, Lang\MENU_ERROR_LOGS, TplApp\SECTION_CALL, TplApp\SECTION_CONTENT, Lang\SERVICE, and Lang\VERSIONS.
getMenuPostgresqlDebug()
static TplAppPostgresql::getMenuPostgresqlDebug () static
Generates the PostgreSQL debug menu with options to run various debug commands.
@global object $bearsamppLang Provides language support for retrieving language-specific values.
Returns
string The generated menu items and actions for PostgreSQL debug.
Definition at line 250 of file class.tpl.app.postgresql.php.
    {
        global $bearsamppLang;
        return TplApp::getActionRun(
            Action::DEBUG_POSTGRESQL, array(BinPostgresql::CMD_VERSION),
            array($bearsamppLang->getValue(Lang::DEBUG_POSTGRESQL_VERSION), TplAestan::GLYPH_DEBUG)
        ) . PHP_EOL;
    }
References $bearsamppLang, BinPostgresql\CMD_VERSION, Action\DEBUG_POSTGRESQL, Lang\DEBUG_POSTGRESQL_VERSION, TplApp\getActionRun(), and TplAestan\GLYPH_DEBUG.
getMenuPostgresqlService()
static TplAppPostgresql::getMenuPostgresqlService () static
Generates the PostgreSQL service menu with options to start, stop, restart, and manage the service.
@global object $bearsamppLang Provides language support for retrieving language-specific values. @global object $bearsamppBins Provides access to system binaries and their configurations.
Returns
string The generated menu items and actions for PostgreSQL service.
Definition at line 184 of file class.tpl.app.postgresql.php.
    {
        global $bearsamppLang, $bearsamppBins;
        $tplChangePort = TplApp::getActionMulti(
            self::ACTION_CHANGE_PORT, null,
            array($bearsamppLang->getValue(Lang::MENU_CHANGE_PORT), TplAestan::GLYPH_NETWORK),
            false, get_called_class()
        );
        $isInstalled = $bearsamppBins->getPostgresql()->getService()->isInstalled();
        $result = TplAestan::getItemActionServiceStart($bearsamppBins->getPostgresql()->getService()->getName()) . PHP_EOL .
            TplAestan::getItemActionServiceStop($bearsamppBins->getPostgresql()->getService()->getName()) . PHP_EOL .
            TplAestan::getItemActionServiceRestart($bearsamppBins->getPostgresql()->getService()->getName()) . PHP_EOL .
            TplAestan::getItemSeparator() . PHP_EOL .
            TplApp::getActionRun(
                Action::CHECK_PORT, array($bearsamppBins->getPostgresql()->getName(), $bearsamppBins->getPostgresql()->getPort()),
                array(sprintf($bearsamppLang->getValue(Lang::MENU_CHECK_PORT), $bearsamppBins->getPostgresql()->getPort()), TplAestan::GLYPH_LIGHT)
            ) . PHP_EOL .
            $tplChangePort[TplApp::SECTION_CALL] . PHP_EOL;
        $tplChangeRootPwd = null;
        if ($isInstalled) {
            $tplChangeRootPwd = TplApp::getActionMulti(
                self::ACTION_CHANGE_ROOT_PWD, null,
                array($bearsamppLang->getValue(Lang::MENU_CHANGE_ROOT_PWD), TplAestan::GLYPH_PASSWORD),
                !$isInstalled, get_called_class()
            );
            $result .= $tplChangeRootPwd[TplApp::SECTION_CALL] . PHP_EOL;
        }
        if (!$isInstalled) {
            $tplInstallService = TplApp::getActionMulti(
                self::ACTION_INSTALL_SERVICE, null,
                array($bearsamppLang->getValue(Lang::MENU_INSTALL_SERVICE), TplAestan::GLYPH_SERVICE_INSTALL),
                $isInstalled, get_called_class()
            );
            $result .= $tplInstallService[TplApp::SECTION_CALL] . PHP_EOL . PHP_EOL .
            $tplInstallService[TplApp::SECTION_CONTENT] . PHP_EOL;
        } else {
            $tplRemoveService = TplApp::getActionMulti(
                self::ACTION_REMOVE_SERVICE, null,
                array($bearsamppLang->getValue(Lang::MENU_REMOVE_SERVICE), TplAestan::GLYPH_SERVICE_REMOVE),
                !$isInstalled, get_called_class()
            );
            $result .= $tplRemoveService[TplApp::SECTION_CALL] . PHP_EOL . PHP_EOL .
            $tplRemoveService[TplApp::SECTION_CONTENT] . PHP_EOL;
        }
        $result .= $tplChangePort[TplApp::SECTION_CONTENT] . PHP_EOL .
            ($tplChangeRootPwd != null ? $tplChangeRootPwd[TplApp::SECTION_CONTENT] . PHP_EOL : '');
        return $result;
    }
References $bearsamppBins, $bearsamppLang, $result, Action\CHECK_PORT, TplApp\getActionMulti(), TplApp\getActionRun(), TplAestan\getItemActionServiceRestart(), TplAestan\getItemActionServiceStart(), TplAestan\getItemActionServiceStop(), TplAestan\getItemSeparator(), TplAestan\GLYPH_LIGHT, TplAestan\GLYPH_NETWORK, TplAestan\GLYPH_PASSWORD, TplAestan\GLYPH_SERVICE_INSTALL, TplAestan\GLYPH_SERVICE_REMOVE, Lang\MENU_CHANGE_PORT, Lang\MENU_CHANGE_ROOT_PWD, Lang\MENU_CHECK_PORT, Lang\MENU_INSTALL_SERVICE, Lang\MENU_REMOVE_SERVICE, TplApp\SECTION_CALL, and TplApp\SECTION_CONTENT.
getMenuPostgresqlVersions()
static TplAppPostgresql::getMenuPostgresqlVersions () static
Generates the PostgreSQL versions menu with options to switch between different versions.
@global object $bearsamppBins Provides access to system binaries and their configurations.
Returns
string The generated menu items and actions for PostgreSQL versions.
Definition at line 121 of file class.tpl.app.postgresql.php.
    {
        global $bearsamppBins;
        $items = '';
        $actions = '';
        foreach ($bearsamppBins->getPostgresql()->getVersionList() as $version) {
            $tplSwitchPostgresqlVersion = TplApp::getActionMulti(
                self::ACTION_SWITCH_VERSION, array($version),
                array($version, $version == $bearsamppBins->getPostgresql()->getVersion() ? TplAestan::GLYPH_CHECK : ''),
                false, get_called_class()
            );
            // Item
            $items .= $tplSwitchPostgresqlVersion[TplApp::SECTION_CALL] . PHP_EOL;
            // Action
            $actions .= PHP_EOL . $tplSwitchPostgresqlVersion[TplApp::SECTION_CONTENT];
        }
        return $items . $actions;
    }
References $bearsamppBins, TplApp\getActionMulti(), TplAestan\GLYPH_CHECK, TplApp\SECTION_CALL, and TplApp\SECTION_CONTENT.
process()
static TplAppPostgresql::process () static
Generates the main PostgreSQL menu with options to enable/disable PostgreSQL and access submenus.
@global object $bearsamppLang Provides language support for retrieving language-specific values. @global object $bearsamppBins Provides access to system binaries and their configurations.
Returns
array The generated menu items and actions for PostgreSQL.
Definition at line 39 of file class.tpl.app.postgresql.php.
    {
        global $bearsamppLang, $bearsamppBins;
        return TplApp::getMenuEnable($bearsamppLang->getValue(Lang::POSTGRESQL), self::MENU, get_called_class(), $bearsamppBins->getPostgresql()->isEnable());
    }
References $bearsamppBins, $bearsamppLang, TplApp\getMenuEnable(), and Lang\POSTGRESQL.
Referenced by TplApp\getSectionMenuLeft().
Field Documentation
ACTION_CHANGE_PORT
const TplAppPostgresql::ACTION_CHANGE_PORT = 'changePostgresqlPort'
Definition at line 26 of file class.tpl.app.postgresql.php.
ACTION_CHANGE_ROOT_PWD
const TplAppPostgresql::ACTION_CHANGE_ROOT_PWD = 'changePostgresqlRootPwd'
Definition at line 27 of file class.tpl.app.postgresql.php.
ACTION_ENABLE
const TplAppPostgresql::ACTION_ENABLE = 'enablePostgresql'
Definition at line 24 of file class.tpl.app.postgresql.php.
ACTION_INSTALL_SERVICE
const TplAppPostgresql::ACTION_INSTALL_SERVICE = 'installPostgresqlService'
Definition at line 28 of file class.tpl.app.postgresql.php.
ACTION_REMOVE_SERVICE
const TplAppPostgresql::ACTION_REMOVE_SERVICE = 'removePostgresqlService'
Definition at line 29 of file class.tpl.app.postgresql.php.
ACTION_SWITCH_VERSION
const TplAppPostgresql::ACTION_SWITCH_VERSION = 'switchPostgresqlVersion'
Definition at line 25 of file class.tpl.app.postgresql.php.
MENU
const TplAppPostgresql::MENU = 'postgresql'
Definition at line 19 of file class.tpl.app.postgresql.php.
MENU_DEBUG
const TplAppPostgresql::MENU_DEBUG = 'postgresqlDebug'
Definition at line 22 of file class.tpl.app.postgresql.php.
MENU_SERVICE
const TplAppPostgresql::MENU_SERVICE = 'postgresqlService'
Definition at line 21 of file class.tpl.app.postgresql.php.
MENU_VERSIONS
const TplAppPostgresql::MENU_VERSIONS = 'postgresqlVersions'
Definition at line 20 of file class.tpl.app.postgresql.php.
The documentation for this class was generated from the following file:
E:/Bearsampp-development/sandbox/core/classes/tpls/app/class.tpl.app.postgresql.php