My Project: BinPostgresql Class Reference
BinPostgresql Class Reference
Public Member Functions
__construct ($id, $type)
changePort ($port, $checkUsed=false, $wbProgressBar=null)
changeRootPassword ($currentPwd, $newPwd, $wbProgressBar=null)
checkPort ($port, $showWindow=false)
checkRootPassword ($currentPwd=null, $wbProgressBar=null)
getCliExe ()
getCmdLineOutput ($cmd)
getConf ()
getCtlExe ()
getDumpAllExe ()
getDumpExe ()
getErrorLog ()
getHbaConf ()
getPort ()
getRootPwd ()
getRootUser ()
getService ()
initData ($path=null)
rebuildConf ()
reload ($id=null, $type=null)
setEnable ($enabled, $showWindow=false)
setPort ($port)
setRootPwd ($rootPwd)
setRootUser ($rootUser)
setVersion ($version)
switchVersion ($version, $showWindow=false)
Public Member Functions inherited from Module
__toString ()
getCurrentPath ()
getId ()
getName ()
getRelease ()
getRootPath ()
getSymlinkPath ()
getType ()
getVersion ()
getVersionList ()
isEnable ()
update ($sub=0, $showWindow=false)
Data Fields
const CMD_VERSION = '--version'
const LOCAL_CFG_ALT_CONF = 'postgresqlAltConf'
const LOCAL_CFG_ALT_HBA_CONF = 'postgresqlAltUserConf'
const LOCAL_CFG_CLI_EXE = 'postgresqlCliExe'
const LOCAL_CFG_CONF = 'postgresqlConf'
const LOCAL_CFG_CTL_EXE = 'postgresqlCtlExe'
const LOCAL_CFG_DUMP_ALL_EXE = 'postgresqlDumpAllExe'
const LOCAL_CFG_DUMP_EXE = 'postgresqlDumpExe'
const LOCAL_CFG_HBA_CONF = 'postgresqlUserConf'
const LOCAL_CFG_PORT = 'postgresqlPort'
const LOCAL_CFG_ROOT_PWD = 'postgresqlRootPwd'
const LOCAL_CFG_ROOT_USER = 'postgresqlRootUser'
const ROOT_CFG_ENABLE = 'postgresqlEnable'
const ROOT_CFG_VERSION = 'postgresqlVersion'
const SERVICE_NAME = 'bearsampppostgresql'
Data Fields inherited from Module
const BUNDLE_RELEASE = 'bundleRelease'
Protected Member Functions
replaceAll ($params)
updateConfig ($version=null, $sub=0, $showWindow=false)
Protected Member Functions inherited from Module
__construct ()
replace ($key, $value)
Private Attributes
$altConf
$altHbaConf
$cliExe
$conf
$ctlExe
$dumpAllExe
$dumpExe
$errorLog
$hbaConf
$port
$rootPwd
$rootUser
$service
Additional Inherited Members
Protected Attributes inherited from Module
$bearsamppConf
$bearsamppConfRaw
$currentPath
$enable
$name
$release = 'N/A'
$rootPath
$symlinkPath
$version
Detailed Description
Class BinPostgresql
This class represents the PostgreSQL module in the Bearsampp application. It handles the configuration, management, and operations related to PostgreSQL.
Definition at line 16 of file class.bin.postgresql.php.
Constructor & Destructor Documentation
__construct()
BinPostgresql::__construct ($id, $type)
Constructor for the BinPostgresql class.
Parameters
string $id The ID of the module.
string $type The type of the module.
Definition at line 57 of file class.bin.postgresql.php.
    {
        Util::logInitClass( $this );
        $this->reload( $id, $type );
    }
References Module\$id, Module\$type, Util\logInitClass(), and reload().
Member Function Documentation
changePort()
BinPostgresql::changePort ($port, $checkUsed = false, $wbProgressBar = null)
Changes the port used by PostgreSQL.
Parameters
int $port The new port number.
bool $checkUsed Whether to check if the port is already in use.
mixed $wbProgressBar The progress bar object for UI updates.
Returns
bool|string True if the port was changed successfully, or the process using the port if it is in use.
Definition at line 207 of file class.bin.postgresql.php.
    {
        global $bearsamppWinbinder;
        if ( !Util::isValidPort( $port ) ) {
            Util::logError( $this->getName() . ' port not valid: ' . $port );
            return false;
        }
        $port = intval( $port );
        $bearsamppWinbinder->incrProgressBar( $wbProgressBar );
        $isPortInUse = Util::isPortInUse( $port );
        if ( !$checkUsed || $isPortInUse === false ) {
            // bearsampp.conf
            $this->setPort( $port );
            $bearsamppWinbinder->incrProgressBar( $wbProgressBar );
            // conf
            $this->update();
            $bearsamppWinbinder->incrProgressBar( $wbProgressBar );
            return true;
        }
        Util::logDebug( $this->getName() . ' port in used: ' . $port . ' - ' . $isPortInUse );
        return $isPortInUse;
    }
References $port, Module\getName(), Util\isPortInUse(), Util\isValidPort(), Util\logDebug(), Util\logError(), setPort(), and Module\update().
changeRootPassword()
BinPostgresql::changeRootPassword ($currentPwd, $newPwd, $wbProgressBar = null)
Changes the root password for PostgreSQL.
Parameters
string $currentPwd The current root password.
string $newPwd The new root password.
mixed $wbProgressBar The progress bar object for UI updates.
Returns
bool|string True if the password was changed successfully, or an error message if it failed.
Definition at line 326 of file class.bin.postgresql.php.
    {
        global $bearsamppWinbinder;
        $error = null;
        $bearsamppWinbinder->incrProgressBar( $wbProgressBar );
        $dbLink = pg_connect( 'host=127.0.0.1 port=' . $this->port . ' user=' . $this->rootUser . ' password=' . $currentPwd );
        if ( !$dbLink ) {
            $error = pg_last_error( $dbLink );
        }
        $bearsamppWinbinder->incrProgressBar( $wbProgressBar );
        $pgr = pg_query_params( $dbLink, 'SELECT quote_ident($1)', array(pg_escape_string( $this->rootUser )) );
        list( $quoted_user ) = pg_fetch_array( $pgr );
        $password = pg_escape_string( $newPwd );
        $result   = pg_query( $dbLink, "ALTER USER $quoted_user WITH PASSWORD '$password'" );
        if ( empty( $error ) && !$result ) {
            $error = pg_last_error( $dbLink );
        }
        $bearsamppWinbinder->incrProgressBar( $wbProgressBar );
        if ( $dbLink ) {
            pg_close( $dbLink );
        }
        if ( !empty( $error ) ) {
            return $error;
        }
        // bearsampp.conf
        $bearsamppWinbinder->incrProgressBar( $wbProgressBar );
        $this->setRootPwd( $newPwd );
        // conf
        $this->update();
        $bearsamppWinbinder->incrProgressBar( $wbProgressBar );
        return true;
    }
References $result, setRootPwd(), and Module\update().
checkPort()
BinPostgresql::checkPort ($port, $showWindow = false)
Checks if the specified port is used by PostgreSQL.
Parameters
int $port The port number to check.
bool $showWindow Whether to show a message box with the result.
Returns
bool True if the port is used by PostgreSQL, false otherwise.
Definition at line 246 of file class.bin.postgresql.php.
    {
        global $bearsamppLang, $bearsamppWinbinder;
        $boxTitle = sprintf( $bearsamppLang->getValue( Lang::CHECK_PORT_TITLE ), $this->getName(), $port );
        if ( !Util::isValidPort( $port ) ) {
            Util::logError( $this->getName() . ' port not valid: ' . $port );
            return false;
        }
        $fp = @fsockopen( '127.0.0.1', $port, $errno, $errstr, 5 );
        if ( $fp ) {
            $dbLink = pg_connect( 'host=127.0.0.1 port=' . $port . ' user=' . $this->rootUser . ' password=' . $this->rootPwd );
            $isPostgresql = false;
            $version      = false;
            if ( $dbLink ) {
                $result = pg_version( $dbLink );
                pg_close( $dbLink );
                if ( $result ) {
                    if ( isset( $result['server'] ) && $result['server'] == $this->getVersion() ) {
                        $version      = $result['server'];
                        $isPostgresql = true;
                    }
                    if ( !$isPostgresql ) {
                        Util::logDebug( $this->getName() . ' port used by another DBMS: ' . $port );
                        if ( $showWindow ) {
                            $bearsamppWinbinder->messageBoxWarning(
                                sprintf( $bearsamppLang->getValue( Lang::PORT_USED_BY_ANOTHER_DBMS ), $port ),
                                $boxTitle
                            );
                        }
                    }
                    else {
                        Util::logDebug( $this->getName() . ' port ' . $port . ' is used by: ' . $this->getName() . ' ' . $version );
                        if ( $showWindow ) {
                            $bearsamppWinbinder->messageBoxInfo(
                                sprintf( $bearsamppLang->getValue( Lang::PORT_USED_BY ), $port, $this->getName() . ' ' . $version ),
                                $boxTitle
                            );
                        }
                        return true;
                    }
                }
            }
            else {
                Util::logDebug( $this->getName() . ' port ' . $port . ' is used by another application' );
                if ( $showWindow ) {
                    $bearsamppWinbinder->messageBoxWarning(
                        sprintf( $bearsamppLang->getValue( Lang::PORT_NOT_USED_BY ), $port ),
                        $boxTitle
                    );
                }
            }
        }
        else {
            Util::logDebug( $this->getName() . ' port ' . $port . ' is not used' );
            if ( $showWindow ) {
                $bearsamppWinbinder->messageBoxError(
                    sprintf( $bearsamppLang->getValue( Lang::PORT_NOT_USED ), $port ),
                    $boxTitle
                );
            }
        }
        return false;
    }
References $bearsamppLang, $port, $result, Module\$version, Lang\CHECK_PORT_TITLE, Module\getName(), Module\getVersion(), Util\isValidPort(), Util\logDebug(), Util\logError(), Lang\PORT_NOT_USED, Lang\PORT_NOT_USED_BY, Lang\PORT_USED_BY, and Lang\PORT_USED_BY_ANOTHER_DBMS.
checkRootPassword()
BinPostgresql::checkRootPassword ($currentPwd = null, $wbProgressBar = null)
Checks if the provided root password is correct.
Parameters
string | null $currentPwd The current root password. If null, the stored root password is used.
mixed $wbProgressBar The progress bar object for UI updates.
Returns
bool|string True if the password is correct, or an error message if it is incorrect.
Definition at line 375 of file class.bin.postgresql.php.
    {
        global $bearsamppWinbinder;
        $currentPwd = $currentPwd == null ? $this->rootPwd : $currentPwd;
        $error      = null;
        $bearsamppWinbinder->incrProgressBar( $wbProgressBar );
        $dbLink = pg_connect( 'host=127.0.0.1 port=' . $this->port . ' user=' . $this->rootUser . ' password=' . $currentPwd );
        if ( !$dbLink ) {
            $error = pg_last_error( $dbLink );
        }
        $bearsamppWinbinder->incrProgressBar( $wbProgressBar );
        if ( $dbLink ) {
            pg_close( $dbLink );
        }
        if ( !empty( $error ) ) {
            return $error;
        }
        return true;
    }
getCliExe()
BinPostgresql::getCliExe ()
Gets the path to the PostgreSQL command line interface executable.
Returns
string The path to the CLI executable.
Definition at line 619 of file class.bin.postgresql.php.
    {
        return $this->cliExe;
    }
References $cliExe.
Referenced by getCmdLineOutput().
getCmdLineOutput()
BinPostgresql::getCmdLineOutput ($cmd)
Executes a PostgreSQL command line instruction and returns the output.
Parameters
string $cmd The command to execute.
Returns
string|null The output of the command, or null if the command failed.
Definition at line 522 of file class.bin.postgresql.php.
    {
        $result = null;
        $bin = $this->getCliExe();
        if ( file_exists( $bin ) ) {
            $tmpResult = Batch::exec( 'postgresqlGetCmdLineOutput', '"' . $bin . '" ' . $cmd );
            if ( $tmpResult !== false && is_array( $tmpResult ) ) {
                $result = trim( str_replace( $bin, '', implode( PHP_EOL, $tmpResult ) ) );
            }
        }
        return $result;
    }
References $result, Batch\exec(), and getCliExe().
getConf()
BinPostgresql::getConf ()
Gets the path to the PostgreSQL configuration file.
Returns
string The path to the configuration file.
Definition at line 649 of file class.bin.postgresql.php.
    {
        return $this->conf;
    }
References $conf.
Referenced by updateConfig().
getCtlExe()
BinPostgresql::getCtlExe ()
Gets the path to the PostgreSQL control executable.
Returns
string The path to the control executable.
Definition at line 609 of file class.bin.postgresql.php.
    {
        return $this->ctlExe;
    }
References $ctlExe.
getDumpAllExe()
BinPostgresql::getDumpAllExe ()
Gets the path to the PostgreSQL dump all executable.
Returns
string The path to the dump all executable.
Definition at line 639 of file class.bin.postgresql.php.
    {
        return $this->dumpAllExe;
    }
References $dumpAllExe.
getDumpExe()
BinPostgresql::getDumpExe ()
Gets the path to the PostgreSQL dump executable.
Returns
string The path to the dump executable.
Definition at line 629 of file class.bin.postgresql.php.
    {
        return $this->dumpExe;
    }
References $dumpExe.
getErrorLog()
BinPostgresql::getErrorLog ()
Gets the path to the PostgreSQL error log file.
Returns
string The path to the error log file.
Definition at line 599 of file class.bin.postgresql.php.
    {
        return $this->errorLog;
    }
References $errorLog.
getHbaConf()
BinPostgresql::getHbaConf ()
Gets the path to the PostgreSQL host-based authentication configuration file.
Returns
string The path to the HBA configuration file.
Definition at line 659 of file class.bin.postgresql.php.
    {
        return $this->hbaConf;
    }
References $hbaConf.
getPort()
BinPostgresql::getPort ()
Gets the port number used by PostgreSQL.
Returns
int The port number.
Definition at line 669 of file class.bin.postgresql.php.
    {
        return $this->port;
    }
References $port.
getRootPwd()
BinPostgresql::getRootPwd ()
Gets the root password for PostgreSQL.
Returns
string The root password.
Definition at line 709 of file class.bin.postgresql.php.
    {
        return $this->rootPwd;
    }
References $rootPwd.
getRootUser()
BinPostgresql::getRootUser ()
Gets the root user for PostgreSQL.
Returns
string The root user.
Definition at line 689 of file class.bin.postgresql.php.
    {
        return $this->rootUser;
    }
References $rootUser.
getService()
BinPostgresql::getService ()
Gets the service object for PostgreSQL.
Returns
Win32Service The service object.
Definition at line 555 of file class.bin.postgresql.php.
    {
        return $this->service;
    }
References $service.
initData()
BinPostgresql::initData ($path = null)
Initializes the data directory for PostgreSQL if it does not already exist.
Parameters
string | null $path The path to the PostgreSQL data directory. If null, the current path is used.
Definition at line 491 of file class.bin.postgresql.php.
    {
        $path = $path != null ? $path : $this->getCurrentPath();
        if ( file_exists( $path . '/data' ) ) {
            return;
        }
        Batch::initializePostgresql( $path );
    }
References Module\getCurrentPath(), and Batch\initializePostgresql().
Referenced by updateConfig().
rebuildConf()
BinPostgresql::rebuildConf ()
Rebuilds the PostgreSQL configuration files by updating the port number.
Definition at line 505 of file class.bin.postgresql.php.
    {
        Util::replaceInFile( $this->conf, array(
            '/^port(.*?)=(.*?)(\d+)/' => 'port = ' . $this->port
        ) );
        Util::replaceInFile( $this->altConf, array(
            '/^port(.*?)=(.*?)(\d+)/' => 'port = ' . $this->port
        ) );
    }
References Util\replaceInFile().
reload()
BinPostgresql::reload ($id = null, $type = null)
Reloads the module configuration based on the provided ID and type.
Parameters
string | null $id The ID of the module. If null, the current ID is used.
string | null $type The type of the module. If null, the current type is used.
Reimplemented from Module.
Definition at line 69 of file class.bin.postgresql.php.
    {
        global $bearsamppRoot, $bearsamppConfig, $bearsamppLang;
        Util::logReloadClass( $this );
        $this->name    = $bearsamppLang->getValue( Lang::POSTGRESQL );
        $this->version = $bearsamppConfig->getRaw( self::ROOT_CFG_VERSION );
        parent::reload( $id, $type );
        $this->enable   = $this->enable && $bearsamppConfig->getRaw( self::ROOT_CFG_ENABLE );
        $this->service  = new Win32Service( self::SERVICE_NAME );
        $this->errorLog = $bearsamppRoot->getLogsPath() . '/postgresql.log';
        if ( $this->bearsamppConfRaw !== false ) {
            $this->ctlExe     = $this->symlinkPath . '/' . $this->bearsamppConfRaw[self::LOCAL_CFG_CTL_EXE];
            $this->cliExe     = $this->symlinkPath . '/' . $this->bearsamppConfRaw[self::LOCAL_CFG_CLI_EXE];
            $this->dumpExe    = $this->symlinkPath . '/' . $this->bearsamppConfRaw[self::LOCAL_CFG_DUMP_EXE];
            $this->dumpAllExe = $this->symlinkPath . '/' . $this->bearsamppConfRaw[self::LOCAL_CFG_DUMP_ALL_EXE];
            $this->conf       = $this->symlinkPath . '/' . $this->bearsamppConfRaw[self::LOCAL_CFG_CONF];
            $this->hbaConf    = $this->symlinkPath . '/' . $this->bearsamppConfRaw[self::LOCAL_CFG_HBA_CONF];
            $this->altConf    = $this->symlinkPath . '/' . $this->bearsamppConfRaw[self::LOCAL_CFG_ALT_CONF];
            $this->altHbaConf = $this->symlinkPath . '/' . $this->bearsamppConfRaw[self::LOCAL_CFG_ALT_HBA_CONF];
            $this->port       = $this->bearsamppConfRaw[self::LOCAL_CFG_PORT];
            $this->rootUser   = isset( $this->bearsamppConfRaw[self::LOCAL_CFG_ROOT_USER] ) ? $this->bearsamppConfRaw[self::LOCAL_CFG_ROOT_USER] : 'postgres';
            $this->rootPwd    = isset( $this->bearsamppConfRaw[self::LOCAL_CFG_ROOT_PWD] ) ? $this->bearsamppConfRaw[self::LOCAL_CFG_ROOT_PWD] : '';
        }
        if ( !$this->enable ) {
            Util::logInfo( $this->name . ' is not enabled!' );
            return;
        }
        if ( !is_dir( $this->currentPath ) ) {
            Util::logError( sprintf( $bearsamppLang->getValue( Lang::ERROR_FILE_NOT_FOUND ), $this->name . ' ' . $this->version, $this->currentPath ) );
            return;
        }
        if ( !is_dir( $this->symlinkPath ) ) {
            Util::logError( sprintf( $bearsamppLang->getValue( Lang::ERROR_FILE_NOT_FOUND ), $this->name . ' ' . $this->version, $this->symlinkPath ) );
            return;
        }
        if ( !is_file( $this->bearsamppConf ) ) {
            Util::logError( sprintf( $bearsamppLang->getValue( Lang::ERROR_CONF_NOT_FOUND ), $this->name . ' ' . $this->version, $this->bearsamppConf ) );
            return;
        }
        if ( !file_exists( $this->conf ) ) {
            $this->conf = $this->altConf;
        }
        if ( !file_exists( $this->hbaConf ) ) {
            $this->hbaConf = $this->altHbaConf;
        }
        if ( !is_file( $this->ctlExe ) ) {
            Util::logError( sprintf( $bearsamppLang->getValue( Lang::ERROR_EXE_NOT_FOUND ), $this->name . ' ' . $this->version, $this->ctlExe ) );
            return;
        }
        if ( !is_file( $this->cliExe ) ) {
            Util::logError( sprintf( $bearsamppLang->getValue( Lang::ERROR_EXE_NOT_FOUND ), $this->name . ' ' . $this->version, $this->cliExe ) );
            return;
        }
        if ( !is_file( $this->dumpExe ) ) {
            Util::logError( sprintf( $bearsamppLang->getValue( Lang::ERROR_EXE_NOT_FOUND ), $this->name . ' ' . $this->version, $this->dumpExe ) );
            return;
        }
        if ( !is_file( $this->dumpAllExe ) ) {
            Util::logError( sprintf( $bearsamppLang->getValue( Lang::ERROR_EXE_NOT_FOUND ), $this->name . ' ' . $this->version, $this->dumpAllExe ) );
            return;
        }
        if ( !is_file( $this->conf ) ) {
            Util::logError( sprintf( $bearsamppLang->getValue( Lang::ERROR_CONF_NOT_FOUND ), $this->name . ' ' . $this->version, $this->conf ) );
            return;
        }
        if ( !is_file( $this->hbaConf ) ) {
            Util::logError( sprintf( $bearsamppLang->getValue( Lang::ERROR_CONF_NOT_FOUND ), $this->name . ' ' . $this->version, $this->hbaConf ) );
            return;
        }
        if ( !is_numeric( $this->port ) || $this->port <= 0 ) {
            Util::logError( sprintf( $bearsamppLang->getValue( Lang::ERROR_INVALID_PARAMETER ), self::LOCAL_CFG_PORT, $this->port ) );
            return;
        }
        if ( empty( $this->rootUser ) ) {
            Util::logError( sprintf( $bearsamppLang->getValue( Lang::ERROR_INVALID_PARAMETER ), self::LOCAL_CFG_ROOT_USER, $this->rootUser ) );
            return;
        }
        $this->service->setDisplayName( APP_TITLE . ' ' . $this->getName() );
        $this->service->setBinPath( $this->ctlExe );
        $this->service->setStartType( Win32Service::SERVICE_DEMAND_START );
        $this->service->setErrorControl( Win32Service::SERVER_ERROR_NORMAL );
    }
References $altConf, $altHbaConf, $bearsamppConfig, $bearsamppLang, $bearsamppRoot, Module\$id, Module\$type, APP_TITLE, Lang\ERROR_CONF_NOT_FOUND, Lang\ERROR_EXE_NOT_FOUND, Lang\ERROR_FILE_NOT_FOUND, Lang\ERROR_INVALID_PARAMETER, Module\getName(), LOCAL_CFG_ALT_CONF, LOCAL_CFG_ALT_HBA_CONF, LOCAL_CFG_CLI_EXE, LOCAL_CFG_CONF, LOCAL_CFG_CTL_EXE, LOCAL_CFG_DUMP_ALL_EXE, LOCAL_CFG_DUMP_EXE, LOCAL_CFG_HBA_CONF, LOCAL_CFG_PORT, LOCAL_CFG_ROOT_PWD, LOCAL_CFG_ROOT_USER, Util\logError(), Util\logInfo(), Util\logReloadClass(), Lang\POSTGRESQL, Win32Service\SERVER_ERROR_NORMAL, and Win32Service\SERVICE_DEMAND_START.
Referenced by __construct(), setEnable(), and setVersion().
replaceAll()
BinPostgresql::replaceAll ($params) protected
Replaces multiple key-value pairs in the configuration file.
Parameters
array $params An associative array of key-value pairs to replace.
Reimplemented from Module.
Definition at line 175 of file class.bin.postgresql.php.
    {
        $content = file_get_contents( $this->bearsamppConf );
        foreach ( $params as $key => $value ) {
            $content                      = preg_replace( '|' . $key . ' = .*|', $key . ' = ' . '"' . $value . '"', $content );
            $this->bearsamppConfRaw[$key] = $value;
            switch ( $key ) {
                case self::LOCAL_CFG_PORT:
                    $this->port = $value;
                    break;
                case self::LOCAL_CFG_ROOT_USER:
                    $this->rootUser = $value;
                    break;
                case self::LOCAL_CFG_ROOT_PWD:
                    $this->rootPwd = $value;
                    break;
            }
        }
        file_put_contents( $this->bearsamppConf, $content );
    }
References LOCAL_CFG_PORT, LOCAL_CFG_ROOT_PWD, and LOCAL_CFG_ROOT_USER.
setEnable()
BinPostgresql::setEnable ($enabled, $showWindow = false)
Enables or disables the PostgreSQL module.
Parameters
bool $enabled Whether to enable or disable the module.
bool $showWindow Whether to show a message box with the result.
Definition at line 566 of file class.bin.postgresql.php.
    {
        global $bearsamppConfig, $bearsamppLang, $bearsamppWinbinder;
        if ( $enabled == Config::ENABLED && !is_dir( $this->currentPath ) ) {
            Util::logDebug( $this->getName() . ' cannot be enabled because bundle ' . $this->getVersion() . ' does not exist in ' . $this->currentPath );
            if ( $showWindow ) {
                $bearsamppWinbinder->messageBoxError(
                    sprintf( $bearsamppLang->getValue( Lang::ENABLE_BUNDLE_NOT_EXIST ), $this->getName(), $this->getVersion(), $this->currentPath ),
                    sprintf( $bearsamppLang->getValue( Lang::ENABLE_TITLE ), $this->getName() )
                );
            }
            $enabled = Config::DISABLED;
        }
        Util::logInfo( $this->getName() . ' switched to ' . ($enabled == Config::ENABLED ? 'enabled' : 'disabled') );
        $this->enable = $enabled == Config::ENABLED;
        $bearsamppConfig->replace( self::ROOT_CFG_ENABLE, $enabled );
        $this->reload();
        if ( $this->enable ) {
            Util::installService( $this, $this->port, null, $showWindow );
        }
        else {
            Util::removeService( $this->service, $this->name );
        }
    }
References $bearsamppConfig, $bearsamppLang, Config\DISABLED, Lang\ENABLE_BUNDLE_NOT_EXIST, Lang\ENABLE_TITLE, Config\ENABLED, Module\getName(), Module\getVersion(), Util\installService(), Util\logDebug(), Util\logInfo(), reload(), and Util\removeService().
setPort()
BinPostgresql::setPort ($port)
Sets the port number used by PostgreSQL.
Parameters
int $port The port number to set.
Definition at line 679 of file class.bin.postgresql.php.
    {
        $this->replace( self::LOCAL_CFG_PORT, $port );
    }
References $port, and Module\replace().
Referenced by changePort().
setRootPwd()
BinPostgresql::setRootPwd ($rootPwd)
Sets the root password for PostgreSQL.
Parameters
string $rootPwd The root password to set.
Definition at line 719 of file class.bin.postgresql.php.
    {
        $this->replace( self::LOCAL_CFG_ROOT_PWD, $rootPwd );
    }
References $rootPwd, and Module\replace().
Referenced by changeRootPassword().
setRootUser()
BinPostgresql::setRootUser ($rootUser)
Sets the root user for PostgreSQL.
Parameters
string $rootUser The root user to set.
Definition at line 699 of file class.bin.postgresql.php.
    {
        $this->replace( self::LOCAL_CFG_ROOT_USER, $rootUser );
    }
References $rootUser, and Module\replace().
setVersion()
BinPostgresql::setVersion ($version)
Sets the version of PostgreSQL and reloads the configuration.
Parameters
string $version The version to set.
Reimplemented from Module.
Definition at line 542 of file class.bin.postgresql.php.
    {
        global $bearsamppConfig;
        $this->version = $version;
        $bearsamppConfig->replace( self::ROOT_CFG_VERSION, $version );
        $this->reload();
    }
References $bearsamppConfig, Module\$version, and reload().
Referenced by updateConfig().
switchVersion()
BinPostgresql::switchVersion ($version, $showWindow = false)
Switches the PostgreSQL version.
Parameters
string $version The version to switch to.
bool $showWindow Whether to show a message box with the result.
Returns
bool True if the version was switched successfully, false otherwise.
Definition at line 407 of file class.bin.postgresql.php.
    {
        Util::logDebug( 'Switch ' . $this->name . ' version to ' . $version );
        return $this->updateConfig( $version, 0, $showWindow );
    }
References Module\$version, Util\logDebug(), and updateConfig().
updateConfig()
BinPostgresql::updateConfig ($version = null, $sub = 0, $showWindow = false) protected
Updates the PostgreSQL configuration.
Parameters
string | null $version The version to update to. If null, the current version is used.
int $sub The sub-level for logging indentation.
bool $showWindow Whether to show a window during the update process.
Returns
bool True if the configuration was updated successfully, false otherwise.
Reimplemented from Module.
Definition at line 423 of file class.bin.postgresql.php.
    {
        global $bearsamppLang, $bearsamppApps, $bearsamppWinbinder;
        if ( !$this->enable ) {
            return true;
        }
        $version = $version == null ? $this->version : $version;
        Util::logDebug( ($sub > 0 ? str_repeat( ' ', 2 * $sub ) : '') . 'Update ' . $this->name . ' ' . $version . ' config' );
        $boxTitle = sprintf( $bearsamppLang->getValue( Lang::SWITCH_VERSION_TITLE ), $this->getName(), $version );
        $currentPath   = str_replace( 'postgresql' . $this->getVersion(), 'postgresql' . $version, $this->getCurrentPath() );
        $conf          = str_replace( 'postgresql' . $this->getVersion(), 'postgresql' . $version, $this->getConf() );
        $bearsamppConf = str_replace( 'postgresql' . $this->getVersion(), 'postgresql' . $version, $this->bearsamppConf );
        if ( $this->version != $version ) {
            $this->initData( $currentPath );
        }
        if ( !file_exists( $conf ) || !file_exists( $bearsamppConf ) ) {
            Util::logError( 'bearsampp config files not found for ' . $this->getName() . ' ' . $version );
            if ( $showWindow ) {
                $bearsamppWinbinder->messageBoxError(
                    sprintf( $bearsamppLang->getValue( Lang::BEARSAMPP_CONF_NOT_FOUND_ERROR ), $this->getName() . ' ' . $version ),
                    $boxTitle
                );
            }
            return false;
        }
        $bearsamppConfRaw = parse_ini_file( $bearsamppConf );
        if ( $bearsamppConfRaw === false || !isset( $bearsamppConfRaw[self::ROOT_CFG_VERSION] ) || $bearsamppConfRaw[self::ROOT_CFG_VERSION] != $version ) {
            Util::logError( 'bearsampp config file malformed for ' . $this->getName() . ' ' . $version );
            if ( $showWindow ) {
                $bearsamppWinbinder->messageBoxError(
                    sprintf( $bearsamppLang->getValue( Lang::BEARSAMPP_CONF_MALFORMED_ERROR ), $this->getName() . ' ' . $version ),
                    $boxTitle
                );
            }
            return false;
        }
        // bearsampp.conf
        $this->setVersion( $version );
        // conf
        Util::replaceInFile( $this->getConf(), array(
            '/^port(.*?)=(.*?)(\d+)/' => 'port = ' . $this->port
        ) );
        // phppgadmin
        $bearsamppApps->getPhppgadmin()->update( $sub + 1 );
        // adminer
        $bearsamppApps->getAdminer()->update( $sub + 1 );
        return true;
    }
References Module\$bearsamppConf, Module\$bearsamppConfRaw, $bearsamppLang, $conf, Module\$currentPath, Module\$version, Lang\BEARSAMPP_CONF_MALFORMED_ERROR, Lang\BEARSAMPP_CONF_NOT_FOUND_ERROR, getConf(), Module\getCurrentPath(), Module\getName(), Module\getVersion(), initData(), Util\logDebug(), Util\logError(), Util\replaceInFile(), setVersion(), and Lang\SWITCH_VERSION_TITLE.
Referenced by switchVersion().
Field Documentation
$altConf
BinPostgresql::$altConf private
Definition at line 45 of file class.bin.postgresql.php.
Referenced by reload().
$altHbaConf
BinPostgresql::$altHbaConf private
Definition at line 46 of file class.bin.postgresql.php.
Referenced by reload().
$cliExe
BinPostgresql::$cliExe private
Definition at line 40 of file class.bin.postgresql.php.
Referenced by getCliExe().
$conf
BinPostgresql::$conf private
Definition at line 43 of file class.bin.postgresql.php.
Referenced by getConf(), and updateConfig().
$ctlExe
BinPostgresql::$ctlExe private
Definition at line 39 of file class.bin.postgresql.php.
Referenced by getCtlExe().
$dumpAllExe
BinPostgresql::$dumpAllExe private
Definition at line 42 of file class.bin.postgresql.php.
Referenced by getDumpAllExe().
$dumpExe
BinPostgresql::$dumpExe private
Definition at line 41 of file class.bin.postgresql.php.
Referenced by getDumpExe().
$errorLog
BinPostgresql::$errorLog private
Definition at line 38 of file class.bin.postgresql.php.
Referenced by getErrorLog().
$hbaConf
BinPostgresql::$hbaConf private
Definition at line 44 of file class.bin.postgresql.php.
Referenced by getHbaConf().
$port
BinPostgresql::$port private
Definition at line 47 of file class.bin.postgresql.php.
Referenced by changePort(), checkPort(), getPort(), and setPort().
$rootPwd
BinPostgresql::$rootPwd private
Definition at line 49 of file class.bin.postgresql.php.
Referenced by getRootPwd(), and setRootPwd().
$rootUser
BinPostgresql::$rootUser private
Definition at line 48 of file class.bin.postgresql.php.
Referenced by getRootUser(), and setRootUser().
$service
BinPostgresql::$service private
Definition at line 37 of file class.bin.postgresql.php.
Referenced by getService().
CMD_VERSION
const BinPostgresql::CMD_VERSION = '--version'
Definition at line 35 of file class.bin.postgresql.php.
Referenced by ActionDebugPostgresql\__construct(), and TplAppPostgresql\getMenuPostgresqlDebug().
LOCAL_CFG_ALT_CONF
const BinPostgresql::LOCAL_CFG_ALT_CONF = 'postgresqlAltConf'
Definition at line 29 of file class.bin.postgresql.php.
Referenced by reload().
LOCAL_CFG_ALT_HBA_CONF
const BinPostgresql::LOCAL_CFG_ALT_HBA_CONF = 'postgresqlAltUserConf'
Definition at line 30 of file class.bin.postgresql.php.
Referenced by reload().
LOCAL_CFG_CLI_EXE
const BinPostgresql::LOCAL_CFG_CLI_EXE = 'postgresqlCliExe'
Definition at line 24 of file class.bin.postgresql.php.
Referenced by reload().
LOCAL_CFG_CONF
const BinPostgresql::LOCAL_CFG_CONF = 'postgresqlConf'
Definition at line 27 of file class.bin.postgresql.php.
Referenced by reload().
LOCAL_CFG_CTL_EXE
const BinPostgresql::LOCAL_CFG_CTL_EXE = 'postgresqlCtlExe'
Definition at line 23 of file class.bin.postgresql.php.
Referenced by reload().
LOCAL_CFG_DUMP_ALL_EXE
const BinPostgresql::LOCAL_CFG_DUMP_ALL_EXE = 'postgresqlDumpAllExe'
Definition at line 26 of file class.bin.postgresql.php.
Referenced by reload().
LOCAL_CFG_DUMP_EXE
const BinPostgresql::LOCAL_CFG_DUMP_EXE = 'postgresqlDumpExe'
Definition at line 25 of file class.bin.postgresql.php.
Referenced by reload().
LOCAL_CFG_HBA_CONF
const BinPostgresql::LOCAL_CFG_HBA_CONF = 'postgresqlUserConf'
Definition at line 28 of file class.bin.postgresql.php.
Referenced by reload().
LOCAL_CFG_PORT
const BinPostgresql::LOCAL_CFG_PORT = 'postgresqlPort'
Definition at line 31 of file class.bin.postgresql.php.
Referenced by reload(), and replaceAll().
LOCAL_CFG_ROOT_PWD
const BinPostgresql::LOCAL_CFG_ROOT_PWD = 'postgresqlRootPwd'
Definition at line 33 of file class.bin.postgresql.php.
Referenced by reload(), and replaceAll().
LOCAL_CFG_ROOT_USER
const BinPostgresql::LOCAL_CFG_ROOT_USER = 'postgresqlRootUser'
Definition at line 32 of file class.bin.postgresql.php.
Referenced by reload(), and replaceAll().
ROOT_CFG_ENABLE
const BinPostgresql::ROOT_CFG_ENABLE = 'postgresqlEnable'
Definition at line 20 of file class.bin.postgresql.php.
ROOT_CFG_VERSION
const BinPostgresql::ROOT_CFG_VERSION = 'postgresqlVersion'
Definition at line 21 of file class.bin.postgresql.php.
SERVICE_NAME
const BinPostgresql::SERVICE_NAME = 'bearsampppostgresql'
Definition at line 18 of file class.bin.postgresql.php.
Referenced by ActionService\__construct(), Win32Service\create(), Win32Service\delete(), TplAppPostgresql\getActionInstallPostgresqlService(), TplAppPostgresql\getActionRemovePostgresqlService(), Bins\getServices(), Batch\installPostgresqlService(), ActionStartup\installServices(), ActionQuit\processWindow(), Win32Service\start(), and Batch\uninstallPostgresqlService().
The documentation for this class was generated from the following file:
E:/Bearsampp-development/sandbox/core/classes/bins/class.bin.postgresql.php