My Project: Batch Class Reference
Batch Class Reference
Public Member Functions
__construct ()
Static Public Member Functions
static createSymlink ($src, $dest)
static exec ($basename, $content, $timeout=true, $catchOutput=true, $standalone=false, $silent=true, $rebuild=true)
static execStandalone ($basename, $content, $silent=true)
static exitApp ($restart=false)
static findExeByPid ($pid)
static getOsInfo ()
static getPearVersion ()
static getProcessUsingPort ($port)
static initializeMysql ($path)
static initializePostgresql ($path)
static installFilezillaService ()
static installPostgresqlService ()
static refreshEnvVars ()
static removeSymlink ($link)
static restartApp ()
static setServiceDescription ($serviceName, $desc)
static setServiceDisplayName ($serviceName, $displayName)
static setServiceStartType ($serviceName, $startType)
static uninstallFilezillaService ()
static uninstallPostgresqlService ()
Data Fields
const CATCH_OUTPUT_FALSE = 'bearsamppCatchOutputFalse'
const END_PROCESS_STR = 'FINISHED!'
Static Private Member Functions
static getTmpFile ($ext, $customName=null)
static writeLog ($log)
Detailed Description
Class Batch
This class provides various utility functions for managing processes, services, and environment variables within the Bearsampp application. It includes methods for finding executables by process ID, checking which process is using a specific port, exiting and restarting the application, managing services, and executing batch scripts.
Key functionalities include:
Finding executables by process ID.
Checking which process is using a specific port.
Exiting and restarting the application.
Managing services (installing, uninstalling, setting descriptions, etc.).
Executing batch scripts with optional output capture and timeout.
Refreshing environment variables.
Creating and removing symbolic links.
Retrieving operating system information.
The class utilizes global variables to access application settings and paths, and logs operations for debugging purposes.
Definition at line 30 of file class.batch.php.
Constructor & Destructor Documentation
__construct()
Batch::__construct ()
Constructor for the Batch class.
Definition at line 38 of file class.batch.php.
    {
    }
Member Function Documentation
createSymlink()
static Batch::createSymlink ($src, $dest) static
Creates a symbolic link.
Parameters
string $src The source path.
string $dest The destination path.
Definition at line 273 of file class.batch.php.
    {
        global $bearsamppCore;
        $src = Util::formatWindowsPath($src);
        $dest = Util::formatWindowsPath($dest);
        self::exec('createSymlink', '"' . $bearsamppCore->getLnExe() . '" --absolute --symbolic --traditional --1023safe "' . $src . '" ' . '"' . $dest . '"', true, false);
    }
References $bearsamppCore, exec(), and Util\formatWindowsPath().
Referenced by Module\createSymlink().
exec()
static Batch::exec ($basename, $content, $timeout = true, $catchOutput = true, $standalone = false, $silent = true, $rebuild = true) static
Executes a batch script.
Parameters
string $basename The base name for the script and result files.
string $content The content of the batch script.
int | bool $timeout The timeout for the script execution in seconds, or true for default timeout, or false for no timeout.
bool $catchOutput Whether to capture the output of the script.
bool $standalone Whether the script is standalone.
bool $silent Whether to execute the script silently.
bool $rebuild Whether to rebuild the result array.
Returns
array|false The result of the execution, or false on failure.
Definition at line 370 of file class.batch.php.
    {
        global $bearsamppConfig, $bearsamppWinbinder;
        $result = false;
        $resultFile = self::getTmpFile('.tmp', $basename);
        $scriptPath = self::getTmpFile('.bat', $basename);
        $checkFile = self::getTmpFile('.tmp', $basename);
        // Redirect output
        if ($catchOutput) {
            $content .= '> "' . $resultFile . '"' . (!Util::endWith($content, '2') ? ' 2>&1' : '');
        }
        // Header
        $header = '@ECHO OFF' . PHP_EOL . PHP_EOL;
        // Footer
        $footer = PHP_EOL . (!$standalone ? PHP_EOL . 'ECHO ' . self::END_PROCESS_STR . ' > "' . $checkFile . '"' : '');
        // Process
        file_put_contents($scriptPath, $header . $content . $footer);
        $bearsamppWinbinder->exec($scriptPath, null, $silent);
        if (!$standalone) {
            $timeout = is_numeric($timeout) ? $timeout : ($timeout === true ? $bearsamppConfig->getScriptsTimeout() : false);
            $maxtime = time() + $timeout;
            $noTimeout = $timeout === false;
            while ($result === false || empty($result)) {
                if (file_exists($checkFile)) {
                    $check = file($checkFile);
                    if (!empty($check) && trim($check[0]) == self::END_PROCESS_STR) {
                        if ($catchOutput && file_exists($resultFile)) {
                            $result = file($resultFile);
                        } else {
                            $result = self::CATCH_OUTPUT_FALSE;
                        }
                    }
                }
                if ($maxtime < time() && !$noTimeout) {
                    break;
                }
            }
        }
        self::writeLog('Exec:');
        self::writeLog('-> basename: ' . $basename);
        self::writeLog('-> content: ' . str_replace(PHP_EOL, ' \\\\ ', $content));
        self::writeLog('-> checkFile: ' . $checkFile);
        self::writeLog('-> resultFile: ' . $resultFile);
        self::writeLog('-> scriptPath: ' . $scriptPath);
        if ($result !== false && !empty($result) && is_array($result)) {
            if ($rebuild) {
                $rebuildResult = array();
                foreach ($result as $row) {
                    $row = trim($row);
                    if (!empty($row)) {
                        $rebuildResult[] = $row;
                    }
                }
                $result = $rebuildResult;
            }
            self::writeLog('-> result: ' . substr(implode(' \\\\ ', $result), 0, 2048));
        } else {
            self::writeLog('-> result: N/A');
        }
        return $result;
    }
References $bearsamppConfig, $result, CATCH_OUTPUT_FALSE, Util\endWith(), getTmpFile(), and writeLog().
Referenced by OpenSsl\createCrt(), createSymlink(), Nssm\exec(), execStandalone(), findExeByPid(), BinApache\getCmdLineOutput(), BinMariadb\getCmdLineOutput(), BinMysql\getCmdLineOutput(), BinPostgresql\getCmdLineOutput(), getOsInfo(), getPearVersion(), getProcessUsingPort(), initializeMysql(), initializePostgresql(), installFilezillaService(), installPostgresqlService(), removeSymlink(), setServiceDescription(), setServiceDisplayName(), setServiceStartType(), uninstallFilezillaService(), and uninstallPostgresqlService().
execStandalone()
static Batch::execStandalone ($basename, $content, $silent = true) static
Executes a standalone batch script.
Parameters
string $basename The base name for the script and result files.
string $content The content of the batch script.
bool $silent Whether to execute the script silently.
Returns
array|false The result of the execution, or false on failure.
Definition at line 353 of file class.batch.php.
    {
        return self::exec($basename, $content, false, false, true, $silent);
    }
References exec().
Referenced by exitApp(), and refreshEnvVars().
exitApp()
static Batch::exitApp ($restart = false) static
Exits the application, optionally restarting it.
Parameters
bool $restart Whether to restart the application after exiting.
Definition at line 106 of file class.batch.php.
    {
        global $bearsamppRoot, $bearsamppCore;
        $content = 'PING 1.1.1.1 -n 1 -w 2000 > nul' . PHP_EOL;
        $content .= '"' . $bearsamppRoot->getExeFilePath() . '" -quit -id={bearsampp}' . PHP_EOL;
        if ($restart) {
            $basename = 'restartApp';
            Util::logInfo('Restart App');
            $content .= '"' . $bearsamppCore->getPhpExe() . '" "' . Core::isRoot_FILE . '" "' . Action::RESTART . '"' . PHP_EOL;
        } else {
            $basename = 'exitApp';
            Util::logInfo('Exit App');
        }
        Win32Ps::killBins();
        self::execStandalone($basename, $content);
    }
References $bearsamppCore, $bearsamppRoot, execStandalone(), Core\isRoot_FILE, Win32Ps\killBins(), Util\logInfo(), and Action\RESTART.
Referenced by ActionExec\__construct(), and restartApp().
findExeByPid()
static Batch::findExeByPid ($pid) static
Finds the executable name by its process ID (PID).
Parameters
int $pid The process ID to search for.
Returns
string|false The executable name if found, false otherwise.
Definition at line 59 of file class.batch.php.
    {
        $result = self::exec('findExeByPid', 'TASKLIST /FO CSV /NH /FI "PID eq ' . $pid . '"', 5);
        if ($result !== false) {
            $expResult = explode('","', $result[0]);
            if (is_array($expResult) && count($expResult) > 2 && isset($expResult[0]) && !empty($expResult[0])) {
                return substr($expResult[0], 1);
            }
        }
        return false;
    }
References $result, and exec().
Referenced by getProcessUsingPort().
getOsInfo()
static Batch::getOsInfo () static
Gets the operating system information.
Returns
string The operating system information.
Definition at line 296 of file class.batch.php.
    {
        $result = self::exec('getOsInfo', 'ver', 5);
        if (is_array($result)) {
            foreach ($result as $row) {
                if (Util::startWith($row, 'Microsoft')) {
                    return trim($row);
                }
            }
        }
        return '';
    }
References $result, exec(), and Util\startWith().
Referenced by ActionStartup\sysInfos().
getPearVersion()
static Batch::getPearVersion () static
Gets the version of PEAR installed.
Returns
string|null The PEAR version if found, null otherwise.
Definition at line 138 of file class.batch.php.
    {
        global $bearsamppBins;
        $result = self::exec('getPearVersion', 'CMD /C "' . $bearsamppBins->getPhp()->getPearExe() . '" -V', 5);
        if (is_array($result)) {
            foreach ($result as $row) {
                if (Util::startWith($row, 'PEAR Version:')) {
                    $expResult = explode(' ', $row);
                    if (count($expResult) == 3) {
                        return trim($expResult[2]);
                    }
                }
            }
        }
        return null;
    }
References $bearsamppBins, $result, exec(), and Util\startWith().
Referenced by BinPhp\getPearVersion().
getProcessUsingPort()
static Batch::getProcessUsingPort ($port) static
Gets the process using a specific port.
Parameters
int $port The port number to check.
Returns
string|int|null The executable name and PID if found, the PID if executable not found, or null if no process is using the port.
Definition at line 78 of file class.batch.php.
    {
        $result = self::exec('getProcessUsingPort', 'NETSTAT -aon', 4);
        if ($result !== false) {
            foreach ($result as $row) {
                if (!Util::startWith($row, 'TCP')) {
                    continue;
                }
                $rowExp = explode(' ', preg_replace('/\s+/', ' ', $row));
                if (count($rowExp) == 5 && Util::endWith($rowExp[1], ':' . $port) && $rowExp[3] == 'LISTENING') {
                    $pid = intval($rowExp[4]);
                    $exe = self::findExeByPid($pid);
                    if ($exe !== false) {
                        return $exe . ' (' . $pid . ')';
                    }
                    return $pid;
                }
            }
        }
        return null;
    }
References $port, $result, Util\endWith(), exec(), findExeByPid(), and Util\startWith().
Referenced by Util\isPortInUse().
getTmpFile()
static Batch::getTmpFile ($ext, $customName = null) static private
Gets a temporary file path with a specified extension and optional custom name.
Parameters
string $ext The file extension.
string | null $customName An optional custom name for the file.
Returns
string The temporary file path.
Definition at line 448 of file class.batch.php.
    {
        global $bearsamppCore;
        return Util::formatWindowsPath($bearsamppCore->getTmpPath() . '/' . (!empty($customName) ? $customName . '-' : '') . Util::random() . $ext);
    }
References $bearsamppCore, Util\formatWindowsPath(), and Util\random().
Referenced by exec().
initializeMysql()
static Batch::initializeMysql ($path) static
Initializes MySQL using a specified path.
Parameters
string $path The path to the MySQL initialization script.
Definition at line 204 of file class.batch.php.
    {
        if (!file_exists($path . '/init.bat')) {
            Util::logWarning($path . '/init.bat does not exist');
            return;
        }
        self::exec('initializeMysql', 'CMD /C "' . $path . '/init.bat"', 60);
    }
References exec(), and Util\logWarning().
Referenced by BinMysql\initData().
initializePostgresql()
static Batch::initializePostgresql ($path) static
Initializes PostgreSQL using a specified path.
Parameters
string $path The path to the PostgreSQL initialization script.
Definition at line 258 of file class.batch.php.
    {
        if (!file_exists($path . '/init.bat')) {
            Util::logWarning($path . '/init.bat does not exist');
            return;
        }
        self::exec('initializePostgresql', 'CMD /C "' . $path . '/init.bat"', 15);
    }
References exec(), and Util\logWarning().
Referenced by BinPostgresql\initData().
installFilezillaService()
static Batch::installFilezillaService () static
Installs the FileZilla service.
Returns
bool True if the service was installed successfully, false otherwise.
Definition at line 171 of file class.batch.php.
    {
        global $bearsamppBins;
        self::exec('installFilezillaService', '"' . $bearsamppBins->getFilezilla()->getExe() . '" /install', true, false);
        if (!$bearsamppBins->getFilezilla()->getService()->isInstalled()) {
            return false;
        }
        self::setServiceDescription(BinFilezilla::SERVICE_NAME, $bearsamppBins->getFilezilla()->getService()->getDisplayName());
        return true;
    }
References $bearsamppBins, exec(), BinFilezilla\SERVICE_NAME, and setServiceDescription().
Referenced by Win32Service\create().
installPostgresqlService()
static Batch::installPostgresqlService () static
Installs the PostgreSQL service.
Returns
bool True if the service was installed successfully, false otherwise.
Definition at line 218 of file class.batch.php.
    {
        global $bearsamppBins;
        $cmd = '"' . Util::formatWindowsPath($bearsamppBins->getPostgresql()->getCtlExe()) . '" register -N "' . BinPostgresql::SERVICE_NAME . '"';
        $cmd .= ' -U "LocalSystem" -D "' . Util::formatWindowsPath($bearsamppBins->getPostgresql()->getSymlinkPath()) . '\\data"';
        $cmd .= ' -l "' . Util::formatWindowsPath($bearsamppBins->getPostgresql()->getErrorLog()) . '" -w';
        self::exec('installPostgresqlService', $cmd, true, false);
        if (!$bearsamppBins->getPostgresql()->getService()->isInstalled()) {
            return false;
        }
        self::setServiceDisplayName(BinPostgresql::SERVICE_NAME, $bearsamppBins->getPostgresql()->getService()->getDisplayName());
        self::setServiceDescription(BinPostgresql::SERVICE_NAME, $bearsamppBins->getPostgresql()->getService()->getDisplayName());
        self::setServiceStartType(BinPostgresql::SERVICE_NAME, "demand");
        return true;
    }
References $bearsamppBins, exec(), Util\formatWindowsPath(), BinPostgresql\SERVICE_NAME, setServiceDescription(), setServiceDisplayName(), and setServiceStartType().
Referenced by Win32Service\create().
refreshEnvVars()
static Batch::refreshEnvVars () static
Refreshes the environment variables.
Definition at line 160 of file class.batch.php.
    {
        global $bearsamppRoot, $bearsamppCore;
        self::execStandalone('refreshEnvVars', '"' . $bearsamppCore->getSetEnvExe() . '" -a ' . Registry::APP_PATH_REG_ENTRY . ' "' . Util::formatWindowsPath($bearsamppRoot->getRootPath()) . '"');
    }
References $bearsamppCore, $bearsamppRoot, Registry\APP_PATH_REG_ENTRY, execStandalone(), and Util\formatWindowsPath().
Referenced by Registry\setValue().
removeSymlink()
static Batch::removeSymlink ($link) static
Removes a symbolic link.
Parameters
string $link The path to the symbolic link.
Definition at line 286 of file class.batch.php.
    {
        self::exec('removeSymlink', 'rmdir /Q "' . Util::formatWindowsPath($link) . '"', true, false);
    }
References exec(), and Util\formatWindowsPath().
Referenced by Module\createSymlink(), and Symlinks\deleteCurrentSymlinks().
restartApp()
static Batch::restartApp () static
Restarts the application.
Definition at line 128 of file class.batch.php.
    {
        self::exitApp(true);
    }
References exitApp().
Referenced by ActionExec\__construct().
setServiceDescription()
static Batch::setServiceDescription ($serviceName, $desc) static
Sets the description of a service.
Parameters
string $serviceName The name of the service.
string $desc The description to set.
Definition at line 327 of file class.batch.php.
    {
        $cmd = 'sc description ' . $serviceName . ' "' . $desc . '"';
        self::exec('setServiceDescription', $cmd, true, false);
    }
References exec().
Referenced by installFilezillaService(), and installPostgresqlService().
setServiceDisplayName()
static Batch::setServiceDisplayName ($serviceName, $displayName) static
Sets the display name of a service.
Parameters
string $serviceName The name of the service.
string $displayName The display name to set.
Definition at line 315 of file class.batch.php.
    {
        $cmd = 'sc config ' . $serviceName . ' DisplayName= "' . $displayName . '"';
        self::exec('setServiceDisplayName', $cmd, true, false);
    }
References exec().
Referenced by installPostgresqlService().
setServiceStartType()
static Batch::setServiceStartType ($serviceName, $startType) static
Sets the start type of a service.
Parameters
string $serviceName The name of the service.
string $startType The start type to set (e.g., "auto", "demand").
Definition at line 339 of file class.batch.php.
    {
        $cmd = 'sc config ' . $serviceName . ' start= ' . $startType;
        self::exec('setServiceStartType', $cmd, true, false);
    }
References exec().
Referenced by installPostgresqlService().
uninstallFilezillaService()
static Batch::uninstallFilezillaService () static
Uninstalls the FileZilla service.
Returns
bool True if the service was uninstalled successfully, false otherwise.
Definition at line 191 of file class.batch.php.
    {
        global $bearsamppBins;
        self::exec('uninstallFilezillaService', '"' . $bearsamppBins->getFilezilla()->getExe() . '" /uninstall', true, false);
        return !$bearsamppBins->getFilezilla()->getService()->isInstalled();
    }
References $bearsamppBins, and exec().
Referenced by Win32Service\delete().
uninstallPostgresqlService()
static Batch::uninstallPostgresqlService () static
Uninstalls the PostgreSQL service.
Returns
bool True if the service was uninstalled successfully, false otherwise.
Definition at line 243 of file class.batch.php.
    {
        global $bearsamppBins;
        $cmd = '"' . Util::formatWindowsPath($bearsamppBins->getPostgresql()->getCtlExe()) . '" unregister -N "' . BinPostgresql::SERVICE_NAME . '"';
        $cmd .= ' -l "' . Util::formatWindowsPath($bearsamppBins->getPostgresql()->getErrorLog()) . '" -w';
        self::exec('uninstallPostgresqlService', $cmd, true, false);
        return !$bearsamppBins->getPostgresql()->getService()->isInstalled();
    }
References $bearsamppBins, exec(), Util\formatWindowsPath(), and BinPostgresql\SERVICE_NAME.
Referenced by Win32Service\delete().
writeLog()
static Batch::writeLog ($log) static private
Writes a log entry to the batch log file.
Parameters
string $log The log message to write.
Definition at line 47 of file class.batch.php.
    {
        global $bearsamppRoot;
        Util::logDebug($log, $bearsamppRoot->getBatchLogFilePath());
    }
References $bearsamppRoot, and Util\logDebug().
Referenced by exec().
Field Documentation
CATCH_OUTPUT_FALSE
const Batch::CATCH_OUTPUT_FALSE = 'bearsamppCatchOutputFalse'
Definition at line 33 of file class.batch.php.
Referenced by exec().
END_PROCESS_STR
const Batch::END_PROCESS_STR = 'FINISHED!'
Definition at line 32 of file class.batch.php.
The documentation for this class was generated from the following file:
E:/Bearsampp-development/sandbox/core/classes/class.batch.php