My Project: TplAppServices Class Reference
TplAppServices Class Reference
Static Public Member Functions
static getActionRestartServices ()
static getActionStartServices ()
static getActionStopServices ()
static process ()
Data Fields
const ACTION_RESTART = 'restartServices'
const ACTION_START = 'startServices'
const ACTION_STOP = 'stopServices'
Detailed Description
Class TplAppServices
This class provides methods to generate menu items and actions for managing multiple services within the Bearsampp application. It includes functionalities for starting, stopping, and restarting all services at once.
Definition at line 17 of file class.tpl.app.services.php.
Member Function Documentation
getActionRestartServices()
static TplAppServices::getActionRestartServices () static
Generates the actions to restart all services by stopping and then starting them.
Returns
string The generated actions to restart all services.
Definition at line 109 of file class.tpl.app.services.php.
    {
        return self::getActionStopServices() . self::getActionStartServices();
    }
References getActionStartServices(), and getActionStopServices().
getActionStartServices()
static TplAppServices::getActionStartServices () static
Generates the actions to start all services.
@global object $bearsamppBins Provides access to system binaries and their configurations.
Returns
string The generated actions to start all services.
Definition at line 73 of file class.tpl.app.services.php.
    {
        global $bearsamppBins;
        $actions = '';
        foreach ($bearsamppBins->getServices() as $sName => $service) {
            $actions .= TplService::getActionStart($service->getName()) . PHP_EOL;
        }
        return $actions;
    }
References $bearsamppBins, and TplService\getActionStart().
Referenced by getActionRestartServices().
getActionStopServices()
static TplAppServices::getActionStopServices () static
Generates the actions to stop all services.
@global object $bearsamppBins Provides access to system binaries and their configurations.
Returns
string The generated actions to stop all services.
Definition at line 92 of file class.tpl.app.services.php.
    {
        global $bearsamppBins;
        $actions = '';
        foreach ($bearsamppBins->getServices() as $sName => $service) {
            $actions .= TplService::getActionStop($service->getName()) . PHP_EOL;
        }
        return $actions;
    }
References $bearsamppBins, and TplService\getActionStop().
Referenced by getActionRestartServices().
process()
static TplAppServices::process () static
Generates the main services menu with options to start, stop, and restart all services.
@global object $bearsamppLang Provides language support for retrieving language-specific values.
Returns
array An array containing the generated menu items and actions for services.
Definition at line 31 of file class.tpl.app.services.php.
    {
        global $bearsamppLang;
        $tplStart = TplApp::getActionMulti(
            self::ACTION_START, null,
            array($bearsamppLang->getValue(Lang::MENU_START_SERVICES), TplAestan::GLYPH_SERVICES_START),
            false, get_called_class()
        );
        $tplStop = TplApp::getActionMulti(
            self::ACTION_STOP, null,
            array($bearsamppLang->getValue(Lang::MENU_STOP_SERVICES), TplAestan::GLYPH_SERVICES_STOP),
            false, get_called_class()
        );
        $tplRestart = TplApp::getActionMulti(
            self::ACTION_RESTART, null,
            array($bearsamppLang->getValue(Lang::MENU_RESTART_SERVICES), TplAestan::GLYPH_SERVICES_RESTART),
            false, get_called_class()
        );
        // Items
        $items = $tplStart[TplApp::SECTION_CALL] . PHP_EOL .
            $tplStop[TplApp::SECTION_CALL] . PHP_EOL .
            $tplRestart[TplApp::SECTION_CALL] . PHP_EOL;
        // Actions
        $actions = PHP_EOL . $tplStart[TplApp::SECTION_CONTENT] .
            PHP_EOL . $tplStop[TplApp::SECTION_CONTENT] .
            PHP_EOL . $tplRestart[TplApp::SECTION_CONTENT];
        return array($items, $actions);
    }
References $bearsamppLang, TplApp\getActionMulti(), TplAestan\GLYPH_SERVICES_RESTART, TplAestan\GLYPH_SERVICES_START, TplAestan\GLYPH_SERVICES_STOP, Lang\MENU_RESTART_SERVICES, Lang\MENU_START_SERVICES, Lang\MENU_STOP_SERVICES, TplApp\SECTION_CALL, and TplApp\SECTION_CONTENT.
Referenced by TplApp\getSectionMenuLeft().
Field Documentation
ACTION_RESTART
const TplAppServices::ACTION_RESTART = 'restartServices'
Definition at line 22 of file class.tpl.app.services.php.
ACTION_START
const TplAppServices::ACTION_START = 'startServices'
Definition at line 20 of file class.tpl.app.services.php.
ACTION_STOP
const TplAppServices::ACTION_STOP = 'stopServices'
Definition at line 21 of file class.tpl.app.services.php.
The documentation for this class was generated from the following file:
E:/Bearsampp-development/sandbox/core/classes/tpls/app/class.tpl.app.services.php