Bearsampp: BinMailpit Class Reference
BinMailpit Class Reference
Public Member Functions
__construct ($id, $type)
changePort ($port, $checkUsed=false, $wbProgressBar=null)
checkPort ($port, $showWindow=false)
getExe ()
getListen ()
getLog ()
getService ()
getSmtpPort ()
getUiPort ()
getWebRoot ()
rebuildConf ()
reload ($id=null, $type=null)
setEnable ($enabled, $showWindow=false)
setListen ()
setSmtpPort ($smtpPort)
setUiPort ($uiPort)
setVersion ($version)
setWebRoot ($webRoot)
switchVersion ($version, $showWindow=false)
Public Member Functions inherited from Module
__toString ()
getCurrentPath ()
getId ()
getName ()
getRelease ()
getRootPath ()
getSymlinkPath ()
getType ()
getVersion ()
getVersionList ()
isEnable ()
update ($sub=0, $showWindow=false)
Data Fields
const LOCAL_CFG_EXE = 'mailpitExe'
const LOCAL_CFG_LISTEN = 'mailpitListen'
const LOCAL_CFG_SMTP_PORT = 'mailpitSmtpPort'
const LOCAL_CFG_UI_PORT = 'mailpitUiPort'
const LOCAL_CFG_WEB_ROOT = 'mailpitWebRoot'
const ROOT_CFG_ENABLE = 'mailpitEnable'
const ROOT_CFG_VERSION = 'mailpitVersion'
const SERVICE_NAME = 'bearsamppmailpit'
const SERVICE_PARAMS = ' --listen "%s:%d" --smtp "%s:%d" --webroot "%s"'
Data Fields inherited from Module
const BUNDLE_RELEASE = 'bundleRelease'
Protected Member Functions
replaceAll ($params)
updateConfig ($version=null, $sub=0, $showWindow=false)
Protected Member Functions inherited from Module
__construct ()
replace ($key, $value)
Private Attributes
$exe
$listen
$log
$service
$smtpPort
$uiPort
$webRoot
Additional Inherited Members
Protected Attributes inherited from Module
$bearsamppConf
$bearsamppConfRaw
$currentPath
$enable
$name
$release = 'N/A'
$rootPath
$symlinkPath
$version
Detailed Description
Class BinMailpit
This class represents the Mailpit module in the Bearsampp application. It handles the configuration, initialization, and management of the Mailpit service.
Definition at line 16 of file class.bin.mailpit.php.
Constructor & Destructor Documentation
__construct()
BinMailpit::__construct ($id, $type)
Constructs a BinMailpit object and initializes the module.
Parameters
string $id The ID of the module.
string $type The type of the module.
Definition at line 45 of file class.bin.mailpit.php.
    {
        Util::logInitClass( $this );
        $this->reload( $id, $type );
    }
References Module\$id, Module\$type, Util\logInitClass(), and reload().
Member Function Documentation
changePort()
BinMailpit::changePort ($port, $checkUsed = false, $wbProgressBar = null)
Changes the SMTP port for the Mailpit service.
Parameters
int $port The new port number.
bool $checkUsed Whether to check if the port is already in use.
mixed $wbProgressBar The progress bar object for UI updates.
Returns
bool|int True if the port was successfully changed, or the process using the port if it is in use.
Definition at line 195 of file class.bin.mailpit.php.
    {
        global $bearsamppWinbinder;
        if ( !Util::isValidPort( $port ) ) {
            Util::logError( $this->getName() . ' port not valid: ' . $port );
            return false;
        }
        $port = intval( $port );
        $bearsamppWinbinder->incrProgressBar( $wbProgressBar );
        $isPortInUse = Util::isPortInUse( $port );
        if ( !$checkUsed || $isPortInUse === false ) {
            // bearsampp.conf
            $this->setSmtpPort( $port );
            $bearsamppWinbinder->incrProgressBar( $wbProgressBar );
            // conf
            $this->update();
            $bearsamppWinbinder->incrProgressBar( $wbProgressBar );
            return true;
        }
        Util::logDebug( $this->getName() . ' port in used: ' . $port . ' - ' . $isPortInUse );
        return $isPortInUse;
    }
References $port, Module\getName(), Util\isPortInUse(), Util\isValidPort(), Util\logDebug(), Util\logError(), setSmtpPort(), and Module\update().
checkPort()
BinMailpit::checkPort ($port, $showWindow = false)
Checks if the specified port is used by the Mailpit service.
Parameters
int $port The port number to check.
bool $showWindow Whether to show a message box with the result.
Returns
bool True if the port is used by the Mailpit service, false otherwise.
Definition at line 234 of file class.bin.mailpit.php.
    {
        global $bearsamppLang, $bearsamppWinbinder;
        $boxTitle = sprintf( $bearsamppLang->getValue( Lang::CHECK_PORT_TITLE ), $this->getName(), $port );
        if ( !Util::isValidPort( $port ) ) {
            Util::logError( $this->getName() . ' port not valid: ' . $port );
            return false;
        }
        $headers = Util::getHeaders( $this->listen, $port );
        if ( !empty( $headers ) ) {
            if ( Util::contains( $headers[0], 'Mailpit' ) ) {
                Util::logDebug( $this->getName() . ' port ' . $port . ' is used by: ' . str_replace( '220 ', '', $headers[0] ) );
                if ( $showWindow ) {
                    $bearsamppWinbinder->messageBoxInfo(
                        sprintf( $bearsamppLang->getValue( Lang::PORT_USED_BY ), $port, str_replace( '220 ', '', $headers[0] ) ),
                        $boxTitle
                    );
                }
                return true;
            }
            Util::logDebug( $this->getName() . ' port ' . $port . ' is used by another application' );
            if ( $showWindow ) {
                $bearsamppWinbinder->messageBoxWarning(
                    sprintf( $bearsamppLang->getValue( Lang::PORT_NOT_USED_BY ), $port ),
                    $boxTitle
                );
            }
        }
        else {
            Util::logDebug( $this->getName() . ' port ' . $port . ' is not used' );
            if ( $showWindow ) {
                $bearsamppWinbinder->messageBoxError(
                    sprintf( $bearsamppLang->getValue( Lang::PORT_NOT_USED ), $port ),
                    $boxTitle
                );
            }
        }
        return false;
    }
References $bearsamppLang, $port, Lang\CHECK_PORT_TITLE, Util\contains(), Util\getHeaders(), Module\getName(), Util\isValidPort(), Util\logDebug(), Util\logError(), Lang\PORT_NOT_USED, Lang\PORT_NOT_USED_BY, and Lang\PORT_USED_BY.
getExe()
BinMailpit::getExe ()
Retrieves the executable file path for the Mailpit service.
Returns
string The executable file path.
Definition at line 420 of file class.bin.mailpit.php.
    {
        return $this->exe;
    }
References $exe.
getListen()
BinMailpit::getListen ()
Retrieves the listen address for the Mailpit service.
Returns
string The listen address.
Definition at line 490 of file class.bin.mailpit.php.
    {
        return $this->listen;
    }
References $listen.
getLog()
BinMailpit::getLog ()
Retrieves the log file path for the Mailpit service.
Returns
string The log file path.
Definition at line 410 of file class.bin.mailpit.php.
    {
        return $this->log;
    }
References $log.
getService()
BinMailpit::getService ()
Retrieves the service object for the Mailpit service.
Returns
Win32Service The service object.
Definition at line 366 of file class.bin.mailpit.php.
    {
        return $this->service;
    }
References $service.
getSmtpPort()
BinMailpit::getSmtpPort ()
Retrieves the SMTP port for the Mailpit service.
Returns
int The SMTP port.
Definition at line 470 of file class.bin.mailpit.php.
    {
        return $this->smtpPort;
    }
References $smtpPort.
getUiPort()
BinMailpit::getUiPort ()
Retrieves the UI port for the Mailpit service.
Returns
int The UI port.
Definition at line 450 of file class.bin.mailpit.php.
    {
        return $this->uiPort;
    }
References $uiPort.
getWebRoot()
BinMailpit::getWebRoot ()
Retrieves the web root directory for the Mailpit service.
Returns
string The web root directory.
Definition at line 430 of file class.bin.mailpit.php.
    {
        return $this->webRoot;
    }
References $webRoot.
rebuildConf()
BinMailpit::rebuildConf ()
Rebuilds the configuration for the Mailpit service in the Windows Registry.
Returns
bool True if the configuration was successfully rebuilt, false otherwise.
Definition at line 165 of file class.bin.mailpit.php.
    {
        global $bearsamppRegistry;
        $exists = $bearsamppRegistry->exists(
            Registry::HKEY_LOCAL_MACHINE,
            'SYSTEM\CurrentControlSet\Services\\' . self::SERVICE_NAME . '\Parameters',
            Nssm::INFO_APP_PARAMETERS
        );
        if ( $exists ) {
            return $bearsamppRegistry->setExpandStringValue(
                Registry::HKEY_LOCAL_MACHINE,
                'SYSTEM\CurrentControlSet\Services\\' . self::SERVICE_NAME . '\Parameters',
                Nssm::INFO_APP_PARAMETERS,
                sprintf( self::SERVICE_PARAMS, $this->listen, $this->uiPort, $this->listen, $this->smtpPort, $this->webRoot )
                );
        }
        return false;
    }
References Registry\HKEY_LOCAL_MACHINE, and Nssm\INFO_APP_PARAMETERS.
reload()
BinMailpit::reload ($id = null, $type = null)
Reloads the module configuration based on the provided ID and type.
Parameters
string | null $id The ID of the module. If null, the current ID is used.
string | null $type The type of the module. If null, the current type is used.
Reimplemented from Module.
Definition at line 57 of file class.bin.mailpit.php.
    {
        global $bearsamppRoot, $bearsamppConfig, $bearsamppLang;
        Util::logReloadClass( $this );
        $this->name    = $bearsamppLang->getValue( Lang::MAILPIT );
        $this->version = $bearsamppConfig->getRaw( self::ROOT_CFG_VERSION );
        parent::reload( $id, $type );
        $this->enable  = $this->enable && $bearsamppConfig->getRaw( self::ROOT_CFG_ENABLE );
        $this->service = new Win32Service( self::SERVICE_NAME );
        $this->log     = $bearsamppRoot->getLogsPath() . '/mailpit.log';
        if ( $this->bearsamppConfRaw !== false ) {
            $this->exe      = $this->symlinkPath . '/' . $this->bearsamppConfRaw[self::LOCAL_CFG_EXE];
            $this->webRoot  = $this->bearsamppConfRaw[self::LOCAL_CFG_WEB_ROOT];
            $this->uiPort   = intval( $this->bearsamppConfRaw[self::LOCAL_CFG_UI_PORT] );
            $this->smtpPort = intval( $this->bearsamppConfRaw[self::LOCAL_CFG_SMTP_PORT] );
            $this->listen   = $this->bearsamppConfRaw[self::LOCAL_CFG_LISTEN];
        }
        if ( !$this->enable ) {
            Util::logInfo( $this->name . ' is not enabled!' );
            return;
        }
        if ( !is_dir( $this->currentPath ) ) {
            Util::logError( sprintf( $bearsamppLang->getValue( Lang::ERROR_FILE_NOT_FOUND ), $this->name . ' ' . $this->version, $this->currentPath ) );
            return;
        }
        if ( !is_dir( $this->symlinkPath ) ) {
            Util::logError( sprintf( $bearsamppLang->getValue( Lang::ERROR_FILE_NOT_FOUND ), $this->name . ' ' . $this->version, $this->symlinkPath ) );
            return;
        }
        if ( !is_file( $this->bearsamppConf ) ) {
            Util::logError( sprintf( $bearsamppLang->getValue( Lang::ERROR_CONF_NOT_FOUND ), $this->name . ' ' . $this->version, $this->bearsamppConf ) );
            return;
        }
        if ( !is_file( $this->exe ) ) {
            Util::logError( sprintf( $bearsamppLang->getValue( Lang::ERROR_EXE_NOT_FOUND ), $this->name . ' ' . $this->version, $this->exe ) );
            return;
        }
        if ( (empty( $this->webRoot ) && $this->webRoot !== '' || is_numeric( $this->webRoot )) ) {
            Util::logError( sprintf( $bearsamppLang->getValue( Lang::ERROR_INVALID_PARAMETER ), self::LOCAL_CFG_WEB_ROOT, $this->webRoot ) );
            return;
        }
        if ( empty( $this->uiPort ) ) {
            Util::logError( sprintf( $bearsamppLang->getValue( Lang::ERROR_INVALID_PARAMETER ), self::LOCAL_CFG_UI_PORT, $this->uiPort ) );
            return;
        }
        if ( empty( $this->smtpPort ) ) {
            Util::logError( sprintf( $bearsamppLang->getValue( Lang::ERROR_INVALID_PARAMETER ), self::LOCAL_CFG_SMTP_PORT, $this->smtpPort ) );
            return;
        }
        if ( empty( $this->listen ) ) {
            Util::logError( sprintf( $bearsamppLang->getValue( Lang::ERROR_INVALID_PARAMETER ), self::LOCAL_CFG_LISTEN, $this->listen ) );
            return;
        }
        $nssm = new Nssm( self::SERVICE_NAME );
        $nssm->setDisplayName( APP_TITLE . ' ' . $this->getName() );
        $nssm->setBinPath( $this->exe );
        $nssm->setParams( sprintf( self::SERVICE_PARAMS, $this->listen, $this->uiPort, $this->listen, $this->smtpPort, $this->webRoot ) );
        $nssm->setStart( Nssm::SERVICE_DEMAND_START );
        $nssm->setStdout( $bearsamppRoot->getLogsPath() . '/mailpit.out.log' );
        $nssm->setStderr( $bearsamppRoot->getLogsPath() . '/mailpit.err.log' );
        $this->service->setNssm( $nssm );
    }
References $bearsamppConfig, $bearsamppLang, $bearsamppRoot, Module\$id, Module\$type, APP_TITLE, Lang\ERROR_CONF_NOT_FOUND, Lang\ERROR_EXE_NOT_FOUND, Lang\ERROR_FILE_NOT_FOUND, Lang\ERROR_INVALID_PARAMETER, Module\getName(), LOCAL_CFG_EXE, LOCAL_CFG_LISTEN, LOCAL_CFG_WEB_ROOT, Util\logError(), Util\logInfo(), Util\logReloadClass(), Lang\MAILPIT, and Nssm\SERVICE_DEMAND_START.
Referenced by __construct(), setEnable(), and setVersion().
replaceAll()
BinMailpit::replaceAll ($params) protected
Replaces multiple key-value pairs in the configuration file.
Parameters
array $params An associative array of key-value pairs to replace.
Reimplemented from Module.
Definition at line 140 of file class.bin.mailpit.php.
    {
        $content = file_get_contents( $this->bearsamppConf );
        foreach ( $params as $key => $value ) {
            $content                      = preg_replace( '|' . $key . ' = .*|', $key . ' = ' . '"' . $value . '"', $content );
            $this->bearsamppConfRaw[$key] = $value;
            switch ( $key ) {
                case self::LOCAL_CFG_UI_PORT:
                    $this->uiPort = intval( $value );
                    break;
                case self::LOCAL_CFG_SMTP_PORT:
                    $this->smtpPort = intval( $value );
                    break;
            }
        }
        file_put_contents( $this->bearsamppConf, $content );
    }
References LOCAL_CFG_SMTP_PORT, and LOCAL_CFG_UI_PORT.
setEnable()
BinMailpit::setEnable ($enabled, $showWindow = false)
Enables or disables the Mailpit service.
Parameters
bool $enabled Whether to enable or disable the service.
bool $showWindow Whether to show a message box with the result.
Definition at line 377 of file class.bin.mailpit.php.
    {
        global $bearsamppConfig, $bearsamppLang, $bearsamppWinbinder;
        if ( $enabled == Config::ENABLED && !is_dir( $this->currentPath ) ) {
            Util::logDebug( $this->getName() . ' cannot be enabled because bundle ' . $this->getVersion() . ' does not exist in ' . $this->currentPath );
            if ( $showWindow ) {
                $bearsamppWinbinder->messageBoxError(
                    sprintf( $bearsamppLang->getValue( Lang::ENABLE_BUNDLE_NOT_EXIST ), $this->getName(), $this->getVersion(), $this->currentPath ),
                    sprintf( $bearsamppLang->getValue( Lang::ENABLE_TITLE ), $this->getName() )
                );
            }
            $enabled = Config::DISABLED;
        }
        Util::logInfo( $this->getName() . ' switched to ' . ($enabled == Config::ENABLED ? 'enabled' : 'disabled') );
        $this->enable = $enabled == Config::ENABLED;
        $bearsamppConfig->replace( self::ROOT_CFG_ENABLE, $enabled );
        $this->reload();
        if ( $this->enable ) {
            Util::installService( $this, $this->smtpPort, null, $showWindow );
        }
        else {
            Util::removeService( $this->service, $this->name );
        }
    }
References $bearsamppConfig, $bearsamppLang, Config\DISABLED, Lang\ENABLE_BUNDLE_NOT_EXIST, Lang\ENABLE_TITLE, Config\ENABLED, Module\getName(), Module\getVersion(), Util\installService(), Util\logDebug(), Util\logInfo(), reload(), and Util\removeService().
setListen()
BinMailpit::setListen ()
Sets the listen address for the Mailpit service.
Returns
bool True if the listen address was successfully set, false otherwise.
Definition at line 500 of file class.bin.mailpit.php.
    {
        return $this->replace( self::LOCAL_CFG_LISTEN, $this->listen );
    }
References Module\replace().
setSmtpPort()
BinMailpit::setSmtpPort ($smtpPort)
Sets the SMTP port for the Mailpit service.
Parameters
int $smtpPort The SMTP port to set.
Definition at line 480 of file class.bin.mailpit.php.
    {
        $this->replace( self::LOCAL_CFG_SMTP_PORT, $smtpPort );
    }
References $smtpPort, and Module\replace().
Referenced by changePort().
setUiPort()
BinMailpit::setUiPort ($uiPort)
Sets the UI port for the Mailpit service.
Parameters
int $uiPort The UI port to set.
Definition at line 460 of file class.bin.mailpit.php.
    {
        $this->replace( self::LOCAL_CFG_UI_PORT, $uiPort );
    }
References $uiPort, and Module\replace().
setVersion()
BinMailpit::setVersion ($version)
Sets the version of the Mailpit service.
Parameters
string $version The version to set.
Reimplemented from Module.
Definition at line 353 of file class.bin.mailpit.php.
    {
        global $bearsamppConfig;
        $this->version = $version;
        $bearsamppConfig->replace( self::ROOT_CFG_VERSION, $version );
        $this->reload();
    }
References $bearsamppConfig, Module\$version, and reload().
Referenced by updateConfig().
setWebRoot()
BinMailpit::setWebRoot ($webRoot)
Sets the web root directory for the Mailpit service.
Parameters
string $webRoot The web root directory to set.
Definition at line 440 of file class.bin.mailpit.php.
    {
        $this->replace( self::LOCAL_CFG_WEB_ROOT, $webRoot );
    }
References $webRoot, and Module\replace().
switchVersion()
BinMailpit::switchVersion ($version, $showWindow = false)
Switches the version of the Mailpit service.
Parameters
string $version The version to switch to.
bool $showWindow Whether to show a message box with the result.
Returns
bool True if the version was successfully switched, false otherwise.
Definition at line 287 of file class.bin.mailpit.php.
    {
        Util::logDebug( 'Switch ' . $this->name . ' version to ' . $version );
        return $this->updateConfig( $version, 0, $showWindow );
    }
References Module\$version, Util\logDebug(), and updateConfig().
updateConfig()
BinMailpit::updateConfig ($version = null, $sub = 0, $showWindow = false) protected
Updates the configuration for the Mailpit service.
Parameters
string | null $version The version to update to. If null, the current version is used.
int $sub The sub-level for logging indentation.
bool $showWindow Whether to show a message box with the result.
Returns
bool True if the configuration was successfully updated, false otherwise.
Reimplemented from Module.
Definition at line 303 of file class.bin.mailpit.php.
    {
        global $bearsamppLang, $bearsamppWinbinder;
        if ( !$this->enable ) {
            return true;
        }
        $version = $version == null ? $this->version : $version;
        Util::logDebug( ($sub > 0 ? str_repeat( ' ', 2 * $sub ) : '') . 'Update ' . $this->name . ' ' . $version . ' config' );
        $boxTitle = sprintf( $bearsamppLang->getValue( Lang::SWITCH_VERSION_TITLE ), $this->getName(), $version );
        $bearsamppConf = str_replace( 'mailpit' . $this->getVersion(), 'mailpit' . $version, $this->bearsamppConf );
        if ( !file_exists( $bearsamppConf ) ) {
            Util::logError( 'bearsampp config files not found for ' . $this->getName() . ' ' . $version );
            if ( $showWindow ) {
                $bearsamppWinbinder->messageBoxError(
                    sprintf( $bearsamppLang->getValue( Lang::BEARSAMPP_CONF_NOT_FOUND_ERROR ), $this->getName() . ' ' . $version ),
                    $boxTitle
                );
            }
            return false;
        }
        $bearsamppConfRaw = parse_ini_file( $bearsamppConf );
        if ( $bearsamppConfRaw === false || !isset( $bearsamppConfRaw[self::ROOT_CFG_VERSION] ) || $bearsamppConfRaw[self::ROOT_CFG_VERSION] != $version ) {
            Util::logError( 'bearsampp config file malformed for ' . $this->getName() . ' ' . $version );
            if ( $showWindow ) {
                $bearsamppWinbinder->messageBoxError(
                    sprintf( $bearsamppLang->getValue( Lang::BEARSAMPP_CONF_MALFORMED_ERROR ), $this->getName() . ' ' . $version ),
                    $boxTitle
                );
            }
            return false;
        }
        // bearsampp.conf
        $this->setVersion( $version );
        return true;
    }
References Module\$bearsamppConf, Module\$bearsamppConfRaw, $bearsamppLang, Module\$version, Lang\BEARSAMPP_CONF_MALFORMED_ERROR, Lang\BEARSAMPP_CONF_NOT_FOUND_ERROR, Module\getName(), Module\getVersion(), Util\logDebug(), Util\logError(), setVersion(), and Lang\SWITCH_VERSION_TITLE.
Referenced by switchVersion().
Field Documentation
$exe
BinMailpit::$exe private
Definition at line 33 of file class.bin.mailpit.php.
Referenced by getExe().
$listen
BinMailpit::$listen private
Definition at line 37 of file class.bin.mailpit.php.
Referenced by getListen().
$log
BinMailpit::$log private
Definition at line 31 of file class.bin.mailpit.php.
Referenced by getLog().
$service
BinMailpit::$service private
Definition at line 30 of file class.bin.mailpit.php.
Referenced by getService().
$smtpPort
BinMailpit::$smtpPort private
Definition at line 36 of file class.bin.mailpit.php.
Referenced by getSmtpPort(), and setSmtpPort().
$uiPort
BinMailpit::$uiPort private
Definition at line 35 of file class.bin.mailpit.php.
Referenced by getUiPort(), and setUiPort().
$webRoot
BinMailpit::$webRoot private
Definition at line 34 of file class.bin.mailpit.php.
Referenced by getWebRoot(), and setWebRoot().
LOCAL_CFG_EXE
const BinMailpit::LOCAL_CFG_EXE = 'mailpitExe'
Definition at line 24 of file class.bin.mailpit.php.
Referenced by reload().
LOCAL_CFG_LISTEN
const BinMailpit::LOCAL_CFG_LISTEN = 'mailpitListen'
Definition at line 28 of file class.bin.mailpit.php.
Referenced by reload().
LOCAL_CFG_SMTP_PORT
const BinMailpit::LOCAL_CFG_SMTP_PORT = 'mailpitSmtpPort'
Definition at line 27 of file class.bin.mailpit.php.
Referenced by replaceAll().
LOCAL_CFG_UI_PORT
const BinMailpit::LOCAL_CFG_UI_PORT = 'mailpitUiPort'
Definition at line 26 of file class.bin.mailpit.php.
Referenced by replaceAll().
LOCAL_CFG_WEB_ROOT
const BinMailpit::LOCAL_CFG_WEB_ROOT = 'mailpitWebRoot'
Definition at line 25 of file class.bin.mailpit.php.
Referenced by reload().
ROOT_CFG_ENABLE
const BinMailpit::ROOT_CFG_ENABLE = 'mailpitEnable'
Definition at line 21 of file class.bin.mailpit.php.
ROOT_CFG_VERSION
const BinMailpit::ROOT_CFG_VERSION = 'mailpitVersion'
Definition at line 22 of file class.bin.mailpit.php.
SERVICE_NAME
const BinMailpit::SERVICE_NAME = 'bearsamppmailpit'
Definition at line 18 of file class.bin.mailpit.php.
Referenced by ActionService\__construct(), TplAppMailpit\getActionInstallMailpitService(), TplAppMailpit\getActionRemoveMailpitService(), Bins\getServices(), ActionStartup\installServices(), ActionQuit\processWindow(), and Win32Service\start().
SERVICE_PARAMS
const BinMailpit::SERVICE_PARAMS = ' --listen "%s:%d" --smtp "%s:%d" --webroot "%s"'
Definition at line 19 of file class.bin.mailpit.php.
The documentation for this class was generated from the following file:
E:/Bearsampp-development/sandbox/core/classes/bins/class.bin.mailpit.php