Bearsampp: TplAppFilezilla Class Reference
TplAppFilezilla Class Reference
Static Public Member Functions
static getActionChangeFilezillaPort ()
static getActionEnableFilezilla ($enable)
static getActionInstallFilezillaService ()
static getActionRemoveFilezillaService ()
static getActionSwitchFilezillaVersion ($version)
static getMenuFilezilla ()
static getMenuFilezillaService ()
static getMenuFilezillaVersions ()
static process ()
Data Fields
const ACTION_CHANGE_PORT = 'changeFilezillaPort'
const ACTION_ENABLE = 'enableFilezilla'
const ACTION_INSTALL_SERVICE = 'installFilezillaService'
const ACTION_REMOVE_SERVICE = 'removeFilezillaService'
const ACTION_SWITCH_VERSION = 'switchFilezillaVersion'
const MENU = 'filezilla'
const MENU_SERVICE = 'filezillaService'
const MENU_VERSIONS = 'filezillaVersions'
Detailed Description
Class TplAppFilezilla
This class provides methods to generate actions and menu items for managing the Filezilla module in the Bearsampp application. It includes functionalities for enabling/disabling Filezilla, switching versions, changing ports, and managing services.
Definition at line 16 of file class.tpl.app.filezilla.php.
Member Function Documentation
getActionChangeFilezillaPort()
static TplAppFilezilla::getActionChangeFilezillaPort () static
Generates the action to change the Filezilla port.
This method creates the action string for changing the Filezilla port, and includes a command to reload the application.
@global object $bearsamppBins Provides access to system binaries and their configurations.
Returns
string The generated action string for changing the Filezilla port.
Definition at line 242 of file class.tpl.app.filezilla.php.
    {
        global $bearsamppBins;
        return TplApp::getActionRun(Action::CHANGE_PORT, array($bearsamppBins->getFilezilla()->getName())) . PHP_EOL .
            TplAppReload::getActionReload();
    }
References $bearsamppBins, Action\CHANGE_PORT, TplAppReload\getActionReload(), and TplApp\getActionRun().
getActionEnableFilezilla()
static TplAppFilezilla::getActionEnableFilezilla ($enable) static
Generates the action to enable or disable Filezilla.
This method creates the action string for enabling or disabling Filezilla, and includes a command to reload the application.
@global object $bearsamppBins Provides access to system binaries and their configurations.
Parameters
int $enable The enable/disable flag (1 for enable, 0 for disable).
Returns
string The generated action string for enabling/disabling Filezilla.
Definition at line 147 of file class.tpl.app.filezilla.php.
    {
        global $bearsamppBins;
        return TplApp::getActionRun(Action::ENABLE, array($bearsamppBins->getFilezilla()->getName(), $enable)) . PHP_EOL .
            TplAppReload::getActionReload();
    }
References $bearsamppBins, Action\ENABLE, TplAppReload\getActionReload(), and TplApp\getActionRun().
getActionInstallFilezillaService()
static TplAppFilezilla::getActionInstallFilezillaService () static
Generates the action to install the Filezilla service.
This method creates the action string for installing the Filezilla service, and includes a command to reload the application.
Returns
string The generated action string for installing the Filezilla service.
Definition at line 257 of file class.tpl.app.filezilla.php.
    {
        return TplApp::getActionRun(Action::SERVICE, array(BinFilezilla::SERVICE_NAME, ActionService::INSTALL)) . PHP_EOL .
            TplAppReload::getActionReload();
    }
References TplAppReload\getActionReload(), TplApp\getActionRun(), ActionService\INSTALL, Action\SERVICE, and BinFilezilla\SERVICE_NAME.
getActionRemoveFilezillaService()
static TplAppFilezilla::getActionRemoveFilezillaService () static
Generates the action to remove the Filezilla service.
This method creates the action string for removing the Filezilla service, and includes a command to reload the application.
Returns
string The generated action string for removing the Filezilla service.
Definition at line 270 of file class.tpl.app.filezilla.php.
    {
        return TplApp::getActionRun(Action::SERVICE, array(BinFilezilla::SERVICE_NAME, ActionService::REMOVE)) . PHP_EOL .
            TplAppReload::getActionReload();
    }
References TplAppReload\getActionReload(), TplApp\getActionRun(), ActionService\REMOVE, Action\SERVICE, and BinFilezilla\SERVICE_NAME.
getActionSwitchFilezillaVersion()
static TplAppFilezilla::getActionSwitchFilezillaVersion ($version) static
Generates the action to switch Filezilla versions.
This method creates the action string for switching Filezilla versions, and includes a command to reload the application.
@global object $bearsamppBins Provides access to system binaries and their configurations.
Parameters
string $version The version to switch to.
Returns
string The generated action string for switching Filezilla versions.
Definition at line 165 of file class.tpl.app.filezilla.php.
    {
        global $bearsamppBins;
        return TplApp::getActionRun(Action::SWITCH_VERSION, array($bearsamppBins->getFilezilla()->getName(), $version)) . PHP_EOL .
            TplAppReload::getActionReload() . PHP_EOL;
    }
References $bearsamppBins, TplAppReload\getActionReload(), TplApp\getActionRun(), and Action\SWITCH_VERSION.
getMenuFilezilla()
static TplAppFilezilla::getMenuFilezilla () static
Generates the menu items and actions for managing Filezilla.
This method creates menu items for downloading, enabling/disabling, switching versions, managing services, accessing the admin interface, and viewing logs for Filezilla.
@global object $bearsamppBins Provides access to system binaries and their configurations. @global object $bearsamppLang Provides language support for retrieving language-specific values.
Returns
string The generated menu items and actions for managing Filezilla.
Definition at line 54 of file class.tpl.app.filezilla.php.
    {
        global $bearsamppBins, $bearsamppLang;
        $resultItems = $resultActions = '';
        $isEnabled = $bearsamppBins->getFilezilla()->isEnable();
        // Download
        $resultItems .= TplAestan::getItemLink(
            $bearsamppLang->getValue(Lang::DOWNLOAD_MORE),
            Util::getWebsiteUrl('module/filezilla', '#releases'),
            false,
            TplAestan::GLYPH_BROWSER
        ) . PHP_EOL;
        // Enable
        $tplEnable = TplApp::getActionMulti(
            self::ACTION_ENABLE, array($isEnabled ? Config::DISABLED : Config::ENABLED),
            array($bearsamppLang->getValue(Lang::MENU_ENABLE), $isEnabled ? TplAestan::GLYPH_CHECK : ''),
            false, get_called_class()
        );
        $resultItems .= $tplEnable[TplApp::SECTION_CALL] . PHP_EOL;
        $resultActions .= $tplEnable[TplApp::SECTION_CONTENT] . PHP_EOL;
        if ($isEnabled) {
            $resultItems .= TplAestan::getItemSeparator() . PHP_EOL;
            // Versions
            $tplVersions = TplApp::getMenu($bearsamppLang->getValue(Lang::VERSIONS), self::MENU_VERSIONS, get_called_class());
            $resultItems .= $tplVersions[TplApp::SECTION_CALL] . PHP_EOL;
            $resultActions .= $tplVersions[TplApp::SECTION_CONTENT] . PHP_EOL;
            // Service
            $tplService = TplApp::getMenu($bearsamppLang->getValue(Lang::SERVICE), self::MENU_SERVICE, get_called_class());
            $resultItems .= $tplService[TplApp::SECTION_CALL] . PHP_EOL;
            $resultActions .= $tplService[TplApp::SECTION_CONTENT];
            // Admin interface
            $resultItems .= TplAestan::getItemExe(
                $bearsamppLang->getValue(Lang::ADMINISTRATION),
                $bearsamppBins->getFilezilla()->getItfExe(),
                TplAestan::GLYPH_FILEZILLA
            ) . PHP_EOL;
            // Log
            $resultItems .= TplAestan::getItemNotepad($bearsamppLang->getValue(Lang::MENU_LOGS), $bearsamppBins->getFilezilla()->getLog()) . PHP_EOL;
        }
        return $resultItems . PHP_EOL . $resultActions;
    }
References $bearsamppBins, $bearsamppLang, Lang\ADMINISTRATION, Config\DISABLED, Lang\DOWNLOAD_MORE, Config\ENABLED, TplApp\getActionMulti(), TplAestan\getItemExe(), TplAestan\getItemLink(), TplAestan\getItemNotepad(), TplAestan\getItemSeparator(), TplApp\getMenu(), Util\getWebsiteUrl(), TplAestan\GLYPH_BROWSER, TplAestan\GLYPH_CHECK, TplAestan\GLYPH_FILEZILLA, Lang\MENU_ENABLE, Lang\MENU_LOGS, TplApp\SECTION_CALL, TplApp\SECTION_CONTENT, Lang\SERVICE, and Lang\VERSIONS.
getMenuFilezillaService()
static TplAppFilezilla::getMenuFilezillaService () static
Generates the menu items and actions for managing Filezilla services.
This method creates menu items for starting, stopping, restarting, checking ports, changing ports, and installing/removing the Filezilla service.
@global object $bearsamppLang Provides language support for retrieving language-specific values. @global object $bearsamppBins Provides access to system binaries and their configurations.
Returns
string The generated menu items and actions for managing Filezilla services.
Definition at line 183 of file class.tpl.app.filezilla.php.
    {
        global $bearsamppLang, $bearsamppBins;
        $tplChangePort = TplApp::getActionMulti(
            self::ACTION_CHANGE_PORT, null,
            array($bearsamppLang->getValue(Lang::MENU_CHANGE_PORT), TplAestan::GLYPH_NETWORK),
            false, get_called_class()
        );
        $result = TplAestan::getItemActionServiceStart($bearsamppBins->getFilezilla()->getService()->getName()) . PHP_EOL .
            TplAestan::getItemActionServiceStop($bearsamppBins->getFilezilla()->getService()->getName()) . PHP_EOL .
            TplAestan::getItemActionServiceRestart($bearsamppBins->getFilezilla()->getService()->getName()) . PHP_EOL .
            TplAestan::getItemSeparator() . PHP_EOL .
            TplApp::getActionRun(
                Action::CHECK_PORT, array($bearsamppBins->getFilezilla()->getName(), $bearsamppBins->getFilezilla()->getPort()),
                array(sprintf($bearsamppLang->getValue(Lang::MENU_CHECK_PORT), $bearsamppBins->getFilezilla()->getPort()), TplAestan::GLYPH_LIGHT)
            ) . PHP_EOL .
            TplApp::getActionRun(
                Action::CHECK_PORT, array($bearsamppBins->getFilezilla()->getName(), $bearsamppBins->getFilezilla()->getSslPort(), true),
                array(sprintf($bearsamppLang->getValue(Lang::MENU_CHECK_PORT), $bearsamppBins->getFilezilla()->getSslPort()) . ' (SSL)', TplAestan::GLYPH_RED_LIGHT)
            ) . PHP_EOL .
            $tplChangePort[TplApp::SECTION_CALL] . PHP_EOL;
        $isInstalled = $bearsamppBins->getFilezilla()->getService()->isInstalled();
        if (!$isInstalled) {
            $tplInstallService = TplApp::getActionMulti(
                self::ACTION_INSTALL_SERVICE, null,
                array($bearsamppLang->getValue(Lang::MENU_INSTALL_SERVICE), TplAestan::GLYPH_SERVICE_INSTALL),
                $isInstalled, get_called_class()
            );
            $result .= $tplInstallService[TplApp::SECTION_CALL] . PHP_EOL . PHP_EOL .
                $tplInstallService[TplApp::SECTION_CONTENT] . PHP_EOL;
        } else {
            $tplRemoveService = TplApp::getActionMulti(
                self::ACTION_REMOVE_SERVICE, null,
                array($bearsamppLang->getValue(Lang::MENU_REMOVE_SERVICE), TplAestan::GLYPH_SERVICE_REMOVE),
                !$isInstalled, get_called_class()
            );
            $result .= $tplRemoveService[TplApp::SECTION_CALL] . PHP_EOL . PHP_EOL .
                $tplRemoveService[TplApp::SECTION_CONTENT] . PHP_EOL;
        }
        $result .= $tplChangePort[TplApp::SECTION_CONTENT] . PHP_EOL;
        return $result;
    }
References $bearsamppBins, $bearsamppLang, $result, Action\CHECK_PORT, TplApp\getActionMulti(), TplApp\getActionRun(), TplAestan\getItemActionServiceRestart(), TplAestan\getItemActionServiceStart(), TplAestan\getItemActionServiceStop(), TplAestan\getItemSeparator(), TplAestan\GLYPH_LIGHT, TplAestan\GLYPH_NETWORK, TplAestan\GLYPH_RED_LIGHT, TplAestan\GLYPH_SERVICE_INSTALL, TplAestan\GLYPH_SERVICE_REMOVE, Lang\MENU_CHANGE_PORT, Lang\MENU_CHECK_PORT, Lang\MENU_INSTALL_SERVICE, Lang\MENU_REMOVE_SERVICE, TplApp\SECTION_CALL, and TplApp\SECTION_CONTENT.
getMenuFilezillaVersions()
static TplAppFilezilla::getMenuFilezillaVersions () static
Generates the menu items and actions for switching Filezilla versions.
This method creates menu items for each available version of Filezilla, allowing the user to switch between them.
@global object $bearsamppBins Provides access to system binaries and their configurations.
Returns
string The generated menu items and actions for switching Filezilla versions.
Definition at line 114 of file class.tpl.app.filezilla.php.
    {
        global $bearsamppBins;
        $items = '';
        $actions = '';
        foreach ($bearsamppBins->getFilezilla()->getVersionList() as $version) {
            $tplSwitchFilezillaVersion = TplApp::getActionMulti(
                self::ACTION_SWITCH_VERSION, array($version),
                array($version, $version == $bearsamppBins->getFilezilla()->getVersion() ? TplAestan::GLYPH_CHECK : ''),
                false, get_called_class()
            );
            // Item
            $items .= $tplSwitchFilezillaVersion[TplApp::SECTION_CALL] . PHP_EOL;
            // Action
            $actions .= PHP_EOL . $tplSwitchFilezillaVersion[TplApp::SECTION_CONTENT];
        }
        return $items . $actions;
    }
References $bearsamppBins, TplApp\getActionMulti(), TplAestan\GLYPH_CHECK, TplApp\SECTION_CALL, and TplApp\SECTION_CONTENT.
process()
static TplAppFilezilla::process () static
Generates the menu item and associated actions for enabling/disabling Filezilla.
@global object $bearsamppLang Provides language support for retrieving language-specific values. @global object $bearsamppBins Provides access to system binaries and their configurations.
Returns
array The generated menu item and actions for enabling/disabling Filezilla.
Definition at line 36 of file class.tpl.app.filezilla.php.
    {
        global $bearsamppLang, $bearsamppBins;
        return TplApp::getMenuEnable($bearsamppLang->getValue(Lang::FILEZILLA), self::MENU, get_called_class(), $bearsamppBins->getFilezilla()->isEnable());
    }
References $bearsamppBins, $bearsamppLang, Lang\FILEZILLA, and TplApp\getMenuEnable().
Referenced by TplApp\getSectionMenuLeft().
Field Documentation
ACTION_CHANGE_PORT
const TplAppFilezilla::ACTION_CHANGE_PORT = 'changeFilezillaPort'
Definition at line 24 of file class.tpl.app.filezilla.php.
ACTION_ENABLE
const TplAppFilezilla::ACTION_ENABLE = 'enableFilezilla'
Definition at line 22 of file class.tpl.app.filezilla.php.
ACTION_INSTALL_SERVICE
const TplAppFilezilla::ACTION_INSTALL_SERVICE = 'installFilezillaService'
Definition at line 25 of file class.tpl.app.filezilla.php.
ACTION_REMOVE_SERVICE
const TplAppFilezilla::ACTION_REMOVE_SERVICE = 'removeFilezillaService'
Definition at line 26 of file class.tpl.app.filezilla.php.
ACTION_SWITCH_VERSION
const TplAppFilezilla::ACTION_SWITCH_VERSION = 'switchFilezillaVersion'
Definition at line 23 of file class.tpl.app.filezilla.php.
MENU
const TplAppFilezilla::MENU = 'filezilla'
Definition at line 18 of file class.tpl.app.filezilla.php.
MENU_SERVICE
const TplAppFilezilla::MENU_SERVICE = 'filezillaService'
Definition at line 20 of file class.tpl.app.filezilla.php.
MENU_VERSIONS
const TplAppFilezilla::MENU_VERSIONS = 'filezillaVersions'
Definition at line 19 of file class.tpl.app.filezilla.php.
The documentation for this class was generated from the following file:
E:/Bearsampp-development/sandbox/core/classes/tpls/app/class.tpl.app.filezilla.php