My Project: E:/Bearsampp-development/sandbox/core/resources/homepage/ajax/ajax.quickpick.php File Reference
ajax.quickpick.php File Reference
Namespaces
namespace Bearsampp
Variables
$QuickPick = new QuickPick()
$response = array()
if($_SERVER['REQUEST_METHOD']==='POST') else
Variable Documentation
$QuickPick
$QuickPick = new QuickPick()
Definition at line 36 of file ajax.quickpick.php.
$response
$response = array()
Definition at line 40 of file ajax.quickpick.php.
Referenced by QuickPick\checkDownloadId(), Util\getCurlHttpHeaders(), and QuickPick\installModule().
else
if ($_SERVER[ 'REQUEST_METHOD']==='POST') else
Initial value:
{
    $response['error'] = "Invalid request method."
Definition at line 63 of file ajax.quickpick.php.