My Project: ActionLoading Class Reference
ActionLoading Class Reference
Public Member Functions
__construct ($args)
incrProgressBar ($nb=1)
processLoading ($window, $id, $ctrl, $param1, $param2)
Data Fields
const GAUGE = 20
const WINDOW_HEIGHT = 90
const WINDOW_WIDTH = 360
Private Attributes
$wbProgressBar
$wbWindow
Detailed Description
Class ActionLoading
This class handles the loading action, including the creation and management of a progress bar window.
Definition at line 15 of file class.action.loading.php.
Constructor & Destructor Documentation
__construct()
ActionLoading::__construct ($args)
ActionLoading constructor.
Initializes the loading action, creates the progress bar window, and starts the main loop.
Parameters
array $args The arguments passed to the constructor.
Definition at line 39 of file class.action.loading.php.
    {
        global $bearsamppCore, $bearsamppLang, $bearsamppWinbinder;
        $bearsamppWinbinder->reset();
        $bearsamppCore->addLoadingPid(Win32Ps::getCurrentPid());
        // Screen information
        $screenArea = explode(' ', $bearsamppWinbinder->getSystemInfo(WinBinder::SYSINFO_WORKAREA));
        $screenWidth = intval($screenArea[2]);
        $screenHeight = intval($screenArea[3]);
        $xPos = $screenWidth - self::WINDOW_WIDTH;
        $yPos = $screenHeight - self::WINDOW_HEIGHT - 5;
        // Create the window and progress bar
        $this->wbWindow = $bearsamppWinbinder->createWindow(null, ToolDialog, null, $xPos, $yPos, self::WINDOW_WIDTH, self::WINDOW_HEIGHT, WBC_TOP, null);
        $bearsamppWinbinder->createLabel($this->wbWindow, $bearsamppLang->getValue(Lang::LOADING), 42, 2, 295, null, WBC_LEFT);
        $this->wbProgressBar = $bearsamppWinbinder->createProgressBar($this->wbWindow, self::GAUGE, 42, 20, 290, 15);
        // Set the handler and start the main loop
        $bearsamppWinbinder->setHandler($this->wbWindow, $this, 'processLoading', 10);
        $bearsamppWinbinder->mainLoop();
    }
References $bearsamppCore, $bearsamppLang, Win32Ps\getCurrentPid(), Lang\LOADING, WinBinder\SYSINFO_WORKAREA, and WINDOW_WIDTH.
Member Function Documentation
incrProgressBar()
ActionLoading::incrProgressBar ($nb = 1)
Increments the progress bar by a specified number of steps.
Parameters
int $nb The number of steps to increment the progress bar by. Default is 1.
Definition at line 68 of file class.action.loading.php.
    {
        global $bearsamppCore, $bearsamppWinbinder;
        for ($i = 0; $i < $nb; $i++) {
            $bearsamppWinbinder->incrProgressBar($this->wbProgressBar);
            $bearsamppWinbinder->drawImage($this->wbWindow, $bearsamppCore->getResourcesPath() . '/homepage/img/bearsampp.bmp', 4, 2, 32, 32);
        }
        $bearsamppWinbinder->wait();
        $bearsamppWinbinder->wait($this->wbWindow);
    }
References $bearsamppCore.
Referenced by processLoading().
processLoading()
ActionLoading::processLoading ($window, $id, $ctrl, $param1, $param2)
Processes the loading action, including handling window events and updating the progress bar.
Parameters
mixed $window The window object.
int $id The ID of the event.
mixed $ctrl The control object.
mixed $param1 The first parameter of the event.
mixed $param2 The second parameter of the event.
Definition at line 90 of file class.action.loading.php.
    {
        global $bearsamppRoot, $bearsamppWinbinder;
        switch ($id) {
            case IDCLOSE:
                Win32Ps::kill(Win32Ps::getCurrentPid());
                break;
        }
        while (true) {
            $bearsamppRoot->removeErrorHandling();
            $bearsamppWinbinder->resetProgressBar($this->wbProgressBar);
            usleep(100000);
            for ($i = 0; $i < self::GAUGE; $i++) {
                $this->incrProgressBar();
                usleep(100000);
            }
        }
    }
References $bearsamppRoot, GAUGE, Win32Ps\getCurrentPid(), incrProgressBar(), and Win32Ps\kill().
Field Documentation
$wbProgressBar
ActionLoading::$wbProgressBar private
Definition at line 30 of file class.action.loading.php.
$wbWindow
ActionLoading::$wbWindow private
Definition at line 27 of file class.action.loading.php.
GAUGE
const ActionLoading::GAUGE = 20
Definition at line 24 of file class.action.loading.php.
Referenced by processLoading().
WINDOW_HEIGHT
const ActionLoading::WINDOW_HEIGHT = 90
Definition at line 21 of file class.action.loading.php.
WINDOW_WIDTH
const ActionLoading::WINDOW_WIDTH = 360
Definition at line 18 of file class.action.loading.php.
Referenced by __construct().
The documentation for this class was generated from the following file:
E:/Bearsampp-development/sandbox/core/classes/actions/class.action.loading.php