Bearsampp: AppPhpmyadmin Class Reference
AppPhpmyadmin Class Reference
Public Member Functions
__construct ($id, $type)
getConf ()
reload ($id=null, $type=null)
setVersion ($version)
Public Member Functions inherited from Module
__toString ()
getCurrentPath ()
getId ()
getName ()
getRelease ()
getRootPath ()
getSymlinkPath ()
getType ()
getVersion ()
getVersionList ()
isEnable ()
update ($sub=0, $showWindow=false)
Data Fields
const LOCAL_CFG_CONF = 'phpmyadminConf'
const ROOT_CFG_VERSION = 'phpmyadminVersion'
Data Fields inherited from Module
const BUNDLE_RELEASE = 'bundleRelease'
Protected Member Functions
updateConfig ($version=null, $sub=0, $showWindow=false)
Protected Member Functions inherited from Module
__construct ()
replace ($key, $value)
replaceAll ($params)
Private Attributes
$conf
Additional Inherited Members
Protected Attributes inherited from Module
$bearsamppConf
$bearsamppConfRaw
$currentPath
$enable
$name
$release = 'N/A'
$rootPath
$symlinkPath
$version
Detailed Description
Class AppPhpmyadmin
This class represents the phpMyAdmin application module in the Bearsampp application. It extends the Module class and provides functionalities specific to phpMyAdmin, such as configuration management and version handling.
Definition at line 17 of file class.app.phpmyadmin.php.
Constructor & Destructor Documentation
__construct()
AppPhpmyadmin::__construct ($id, $type)
Constructor for the AppPhpmyadmin class.
Parameters
string $id The ID of the module.
string $type The type of the module.
Definition at line 40 of file class.app.phpmyadmin.php.
{
        Util::logInitClass($this);
        $this->reload($id, $type);
    }
References Module\$id, Module\$type, Util\logInitClass(), and reload().
Member Function Documentation
getConf()
AppPhpmyadmin::getConf ()
Gets the path to the phpMyAdmin configuration file.
Returns
string The path to the configuration file.
Definition at line 146 of file class.app.phpmyadmin.php.
{
        return $this->conf;
    }
Referenced by updateConfig().
reload()
AppPhpmyadmin::reload ($id = null, $type = null)
Reloads the module configuration based on the provided ID and type.
Parameters
string | null $id The ID of the module. If null, the current ID is used.
string | null $type The type of the module. If null, the current type is used.
Reimplemented from Module.
Definition at line 51 of file class.app.phpmyadmin.php.
{
        global $bearsamppConfig, $bearsamppLang;
        Util::logReloadClass($this);
        // This makes name and version the values in bearsampp.conf
        $this->name = $bearsamppLang->getValue(Lang::PHPMYADMIN);
        $this->version = $bearsamppConfig->getRaw(self::ROOT_CFG_VERSION);
        parent::reload($id, $type);
        if ($this->bearsamppConfRaw !== false) {
            $this->conf = $this->symlinkPath . '/' . $this->bearsamppConfRaw[self::LOCAL_CFG_CONF];
        }
        if (!$this->enable) {
            Util::logInfo($this->name . ' is not enabled!');
            return;
        }
        if (!is_dir($this->currentPath)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_FILE_NOT_FOUND), $this->name . ' ' . $this->version, $this->currentPath));
        }
        if (!is_dir($this->symlinkPath)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_FILE_NOT_FOUND), $this->name . ' ' . $this->version, $this->symlinkPath));
            return;
        }
        if (!is_file($this->bearsamppConf)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_CONF_NOT_FOUND), $this->name . ' ' . $this->version, $this->bearsamppConf));
        }
        if (!is_file($this->conf)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_CONF_NOT_FOUND), $this->name . ' ' . $this->version, $this->conf));
        }
    }
References $bearsamppConfig, $bearsamppLang, Module\$id, Module\$type, Lang\ERROR_CONF_NOT_FOUND, Lang\ERROR_FILE_NOT_FOUND, LOCAL_CFG_CONF, Util\logError(), Util\logInfo(), Util\logReloadClass(), and Lang\PHPMYADMIN.
Referenced by __construct().
setVersion()
AppPhpmyadmin::setVersion ($version)
Sets the version of the phpMyAdmin module.
Parameters
string $version The version to set.
Reimplemented from Module.
Definition at line 134 of file class.app.phpmyadmin.php.
{
        global $bearsamppConfig;
        $this->version = $version;
        $bearsamppConfig->replace(self::ROOT_CFG_VERSION, $version);
        $this->reload();
    }
updateConfig()
AppPhpmyadmin::updateConfig ($version = null, $sub = 0, $showWindow = false) protected
Updates the configuration of the phpMyAdmin module.
Parameters
string | null $version The version to update to. If null, the current version is used.
int $sub The sub-level for logging indentation.
bool $showWindow Whether to show a window during the update process.
Returns
bool True if the update was successful, false otherwise.
Reimplemented from Module.
Definition at line 91 of file class.app.phpmyadmin.php.
{
        global $bearsamppRoot, $bearsamppBins;
        if (!$this->enable) {
            return true;
        }
        $version = $version == null ? $this->version : $version;
        Util::logDebug(($sub > 0 ? str_repeat(' ', 2 * $sub) : '') . 'Update ' . $this->name . ' ' . $version . ' config');
        $alias = $bearsamppRoot->getAliasPath() . '/phpmyadmin.conf';
        if (is_file($alias)) {
            Util::replaceInFile($alias, array(
                '/^Alias\s\/phpmyadmin\s.*/' => 'Alias /phpmyadmin "' . $this->getSymlinkPath() . '/"',
                '/^<Directory\s.*/' => '<Directory "' . $this->getSymlinkPath() . '/">',
            ));
        } else {
            Util::logError($this->getName() . ' alias not found : ' . $alias);
        }
        if ($bearsamppBins->getMysql()->isEnable()) {
            Util::replaceInFile($this->getConf(), array(
                '/^\$mysqlPort\s=\s(\d+)/' => '$mysqlPort = ' . $bearsamppBins->getMysql()->getPort() . ';',
                '/^\$mysqlRootUser\s=\s/' => '$mysqlRootUser = \'' . $bearsamppBins->getMysql()->getRootUser() . '\';',
                '/^\$mysqlRootPwd\s=\s/' => '$mysqlRootPwd = \'' . $bearsamppBins->getMysql()->getRootPwd() . '\';'
            ));
        }
        if ($bearsamppBins->getMariadb()->isEnable()) {
            Util::replaceInFile($this->getConf(), array(
                '/^\$mariadbPort\s=\s(\d+)/' => '$mariadbPort = ' . $bearsamppBins->getMariadb()->getPort() . ';',
                '/^\$mariadbRootUser\s=\s/' => '$mariadbRootUser = \'' . $bearsamppBins->getMariadb()->getRootUser() . '\';',
                '/^\$mariadbRootPwd\s=\s/' => '$mariadbRootPwd = \'' . $bearsamppBins->getMariadb()->getRootPwd() . '\';'
            ));
        }
        return true;
    }
References $bearsamppBins, $bearsamppRoot, Module\$version, getConf(), Module\getName(), Module\getSymlinkPath(), Util\logDebug(), Util\logError(), and Util\replaceInFile().
Field Documentation
$conf
AppPhpmyadmin::$conf private
Definition at line 32 of file class.app.phpmyadmin.php.
LOCAL_CFG_CONF
const AppPhpmyadmin::LOCAL_CFG_CONF = 'phpmyadminConf'
Constant for the configuration key representing the phpMyAdmin configuration file.
Definition at line 27 of file class.app.phpmyadmin.php.
Referenced by reload().
ROOT_CFG_VERSION
const AppPhpmyadmin::ROOT_CFG_VERSION = 'phpmyadminVersion'
Constant for the configuration key representing the phpMyAdmin version.
Definition at line 22 of file class.app.phpmyadmin.php.
The documentation for this class was generated from the following file:
E:/Bearsampp-development/sandbox/core/classes/apps/class.app.phpmyadmin.php