Bearsampp: ToolNgrok Class Reference
ToolNgrok Class Reference
Public Member Functions
__construct ($id, $type)
getExe ()
reload ($id=null, $type=null)
setVersion ($version)
Public Member Functions inherited from Module
__toString ()
getCurrentPath ()
getId ()
getName ()
getRelease ()
getRootPath ()
getSymlinkPath ()
getType ()
getVersion ()
getVersionList ()
isEnable ()
update ($sub=0, $showWindow=false)
Data Fields
const LOCAL_CFG_EXE = 'ngrokExe'
const ROOT_CFG_VERSION = 'ngrokVersion'
Data Fields inherited from Module
const BUNDLE_RELEASE = 'bundleRelease'
Private Attributes
$exe
Additional Inherited Members
Protected Member Functions inherited from Module
__construct ()
replace ($key, $value)
replaceAll ($params)
updateConfig ($version=null, $sub=0, $showWindow=false)
Protected Attributes inherited from Module
$bearsamppConf
$bearsamppConfRaw
$currentPath
$enable
$name
$release = 'N/A'
$rootPath
$symlinkPath
$version
Detailed Description
Definition at line 3 of file class.tool.ngrok.php.
Constructor & Destructor Documentation
__construct()
__construct ($id, $type)
Definition at line 11 of file class.tool.ngrok.php.
{
        Util::logInitClass($this);
        $this->reload($id, $type);
    }
References Module\$id, Module\$type, Util\logInitClass(), and reload().
Member Function Documentation
getExe()
getExe ()
Definition at line 54 of file class.tool.ngrok.php.
{
        return $this->exe;
    }
References $exe.
reload()
reload ($id = null, $type = null)
Reimplemented from Module.
Definition at line 16 of file class.tool.ngrok.php.
{
        global $bearsamppConfig, $bearsamppLang;
        Util::logReloadClass($this);
        $this->name = $bearsamppLang->getValue(Lang::NGROK);
        $this->version = $bearsamppConfig->getRaw(self::ROOT_CFG_VERSION);
        parent::reload($id, $type);
        if ($this->bearsamppConfRaw !== false) {
            $this->exe = $this->symlinkPath . '/' . $this->bearsamppConfRaw[self::LOCAL_CFG_EXE];
        }
        if (!$this->enable) {
            Util::logInfo($this->name . ' is not enabled!');
            return;
        }
        if (!is_dir($this->currentPath)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_FILE_NOT_FOUND), $this->name . ' ' . $this->version, $this->currentPath));
        }
        if (!is_dir($this->symlinkPath)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_FILE_NOT_FOUND), $this->name . ' ' . $this->version, $this->symlinkPath));
            return;
        }
        if (!is_file($this->bearsamppConf)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_CONF_NOT_FOUND), $this->name . ' ' . $this->version, $this->bearsamppConf));
        }
        if (!is_file($this->exe)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_EXE_NOT_FOUND), $this->name . ' ' . $this->version, $this->exe));
        }
    }
References $bearsamppConfig, $bearsamppLang, Module\$id, Module\$type, Lang\ERROR_CONF_NOT_FOUND, Lang\ERROR_EXE_NOT_FOUND, Lang\ERROR_FILE_NOT_FOUND, LOCAL_CFG_EXE, Util\logError(), Util\logInfo(), Util\logReloadClass(), and Lang\NGROK.
Referenced by __construct(), and setVersion().
setVersion()
setVersion ($version)
Reimplemented from Module.
Definition at line 47 of file class.tool.ngrok.php.
{
        global $bearsamppConfig;
        $this->version = $version;
        $bearsamppConfig->replace(self::ROOT_CFG_VERSION, $version);
        $this->reload();
    }
References $bearsamppConfig, Module\$version, and reload().
Field Documentation
$exe
$exe private
Definition at line 9 of file class.tool.ngrok.php.
Referenced by getExe().
LOCAL_CFG_EXE
const LOCAL_CFG_EXE = 'ngrokExe'
Definition at line 7 of file class.tool.ngrok.php.
Referenced by reload().
ROOT_CFG_VERSION
const ROOT_CFG_VERSION = 'ngrokVersion'
Definition at line 5 of file class.tool.ngrok.php.
The documentation for this class was generated from the following file:
E:/Bearsampp-development/sandbox/core/classes/tools/class.tool.ngrok.php