My Project: TplAppLogs Class Reference
TplAppLogs Class Reference
Static Public Member Functions
static getMenuLogs ()
static process ()
Data Fields
const MENU = 'logs'
Detailed Description
Class TplAppLogs
This class provides methods to generate and manage the logs menu within the Bearsampp application. It includes functionalities for creating the logs menu and listing log files.
Definition at line 16 of file class.tpl.app.logs.php.
Member Function Documentation
getMenuLogs()
static TplAppLogs::getMenuLogs () static
Generates the logs menu content.
This method retrieves the list of log files from the logs directory, sorts them, and generates menu items for each log file using the getItemNotepad method from the TplAestan class.
@global object $bearsamppRoot Provides access to the root directory of the application.
Returns
string The generated logs menu content as a string.
Definition at line 48 of file class.tpl.app.logs.php.
    {
        global $bearsamppRoot;
        $files = array();
        // Open the logs directory
        $handle = @opendir($bearsamppRoot->getLogsPath());
        if (!$handle) {
            return '';
        }
        // Read log files from the directory
        while (false !== ($file = readdir($handle))) {
            if ($file != "." && $file != ".." && Util::endWith($file, '.log')) {
                $files[] = $file;
            }
        }
        // Close the directory handle
        closedir($handle);
        ksort($files);
        // Generate menu items for each log file
        $result = '';
        foreach ($files as $file) {
            $result .= TplAestan::getItemNotepad(basename($file), $bearsamppRoot->getLogsPath() . '/' . $file) . PHP_EOL;
        }
        return $result;
    }
References $bearsamppRoot, $result, Util\endWith(), and TplAestan\getItemNotepad().
process()
static TplAppLogs::process () static
Processes and generates the logs menu.
This method generates the logs menu by retrieving the localized string for logs and calling the getMenu method from the TplApp class.
@global object $bearsamppLang Provides language support for retrieving language-specific values.
Returns
array The generated logs menu as a string.
Definition at line 31 of file class.tpl.app.logs.php.
    {
        global $bearsamppLang;
        return TplApp::getMenu($bearsamppLang->getValue(Lang::LOGS), self::MENU, get_called_class());
    }
References $bearsamppLang, TplApp\getMenu(), and Lang\LOGS.
Referenced by TplApp\getSectionMenuLeft().
Field Documentation
MENU
const TplAppLogs::MENU = 'logs'
Definition at line 19 of file class.tpl.app.logs.php.
The documentation for this class was generated from the following file:
E:/Bearsampp-development/sandbox/core/classes/tpls/app/class.tpl.app.logs.php