My Project: ActionStartup Class Reference
ActionStartup Class Reference
Public Member Functions
__construct ($args)
processWindow ($window, $id, $ctrl, $param1, $param2)
Data Fields
const GAUGE_OTHERS = 19
const GAUGE_SERVICES = 5
Private Member Functions
changePath ()
checkBinsRegKey ()
checkBrowser ()
checkLaunchStartup ()
checkPath ()
checkPathRegKey ()
checkSystemPathRegKey ()
cleanOldBehaviors ()
cleanTmpFolders ()
createSslCrts ()
installServices ()
killOldInstances ()
refreshAliases ()
refreshGitRepos ()
refreshHostname ()
refreshVhosts ()
rotationLogs ()
savePath ()
scanFolders ()
sysInfos ()
updateConfig ()
writeLog ($log)
Private Attributes
$error
$filesToScan
$restart
$rootPath
$splash
$startTime
Detailed Description
Class ActionStartup Handles the startup process of the Bearsampp application, including initializing services, cleaning temporary files, refreshing configurations, and more.
Definition at line 15 of file class.action.startup.php.
Constructor & Destructor Documentation
__construct()
ActionStartup::__construct ($args)
ActionStartup constructor. Initializes the startup process, including the splash screen and various configurations.
Parameters
array $args Command line arguments.
Definition at line 34 of file class.action.startup.php.
    {
        global $bearsamppRoot, $bearsamppCore, $bearsamppLang, $bearsamppBins, $bearsamppWinbinder;
        $this->writeLog( 'Starting ' . APP_TITLE );
        // Init
        $this->splash    = new Splash();
        $this->restart   = false;
        $this->startTime = Util::getMicrotime();
        $this->error     = '';
        $this->rootPath    = $bearsamppRoot->getRootPath();
        $this->filesToScan = array();
        $gauge = self::GAUGE_SERVICES * count( $bearsamppBins->getServices() );
        $gauge += self::GAUGE_OTHERS + 1;
        // Start splash screen
        $this->splash->init(
            $bearsamppLang->getValue( Lang::STARTUP ),
            $gauge,
            sprintf( $bearsamppLang->getValue( Lang::STARTUP_STARTING_TEXT ), APP_TITLE . ' ' . $bearsamppCore->getAppVersion() )
        );
        $bearsamppWinbinder->setHandler( $this->splash->getWbWindow(), $this, 'processWindow', 1000 );
        $bearsamppWinbinder->mainLoop();
        $bearsamppWinbinder->reset();
    }
References $bearsamppBins, $bearsamppCore, $bearsamppLang, $bearsamppRoot, APP_TITLE, Util\getMicrotime(), Lang\STARTUP, Lang\STARTUP_STARTING_TEXT, and writeLog().
Member Function Documentation
changePath()
ActionStartup::changePath () private
Changes the application path and logs the number of files and occurrences changed.
Definition at line 460 of file class.action.startup.php.
    {
        global $bearsamppLang;
        $this->splash->setTextLoading( sprintf( $bearsamppLang->getValue( Lang::STARTUP_CHANGE_PATH_TEXT ), $this->rootPath ) );
        $this->splash->incrProgressBar();
        $result = Util::changePath( $this->filesToScan, $this->rootPath );
        $this->writeLog( 'Nb files changed: ' . $result['countChangedFiles'] );
        $this->writeLog( 'Nb occurences changed: ' . $result['countChangedOcc'] );
    }
References $bearsamppLang, $result, Util\changePath(), Lang\STARTUP_CHANGE_PATH_TEXT, and writeLog().
Referenced by processWindow().
checkBinsRegKey()
ActionStartup::checkBinsRegKey () private
Checks and updates the application bins registry key. If the current registry key does not match the generated key, it updates the registry key. Logs the current and generated registry keys. Sets an error message if the registry key update fails. Sets a restart flag if the registry key is updated.
Definition at line 519 of file class.action.startup.php.
    {
        global $bearsamppLang, $bearsamppRegistry;
        $this->splash->setTextLoading( sprintf( $bearsamppLang->getValue( Lang::STARTUP_REGISTRY_TEXT ), Registry::APP_BINS_REG_ENTRY ) );
        $this->splash->incrProgressBar();
        $currentAppBinsRegKey = Util::getAppBinsRegKey();
        $genAppBinsRegKey     = Util::getAppBinsRegKey( false );
        $this->writeLog( 'Current app bins reg key: ' . $currentAppBinsRegKey );
        $this->writeLog( 'Gen app bins reg key: ' . $genAppBinsRegKey );
        if ( $currentAppBinsRegKey != $genAppBinsRegKey ) {
            if ( !Util::setAppBinsRegKey( $genAppBinsRegKey ) ) {
                if ( !empty( $this->error ) ) {
                    $this->error .= PHP_EOL . PHP_EOL;
                }
                $this->error .= sprintf( $bearsamppLang->getValue( Lang::STARTUP_REGISTRY_ERROR_TEXT ), Registry::APP_BINS_REG_ENTRY );
                $this->error .= PHP_EOL . $bearsamppRegistry->getLatestError();
            }
            else {
                $this->writeLog( 'Need restart: checkBinsRegKey' );
                $this->restart = true;
            }
        }
    }
References $bearsamppLang, Registry\APP_BINS_REG_ENTRY, Util\getAppBinsRegKey(), Util\setAppBinsRegKey(), Lang\STARTUP_REGISTRY_ERROR_TEXT, Lang\STARTUP_REGISTRY_TEXT, and writeLog().
Referenced by processWindow().
checkBrowser()
ActionStartup::checkBrowser () private
Checks and sets the default browser configuration.
Definition at line 374 of file class.action.startup.php.
    {
        global $bearsamppConfig, $bearsamppLang;
        $this->splash->setTextLoading( $bearsamppLang->getValue( Lang::STARTUP_CHECK_BROWSER_TEXT ) );
        $this->splash->incrProgressBar();
        $this->writeLog( 'Check browser' );
        $currentBrowser = $bearsamppConfig->getBrowser();
        if ( empty( $currentBrowser ) || !file_exists( $currentBrowser ) ) {
            $bearsamppConfig->replace( Config::CFG_BROWSER, Vbs::getDefaultBrowser() );
        }
    }
References $bearsamppConfig, $bearsamppLang, Config\CFG_BROWSER, Vbs\getDefaultBrowser(), Lang\STARTUP_CHECK_BROWSER_TEXT, and writeLog().
Referenced by processWindow().
checkLaunchStartup()
ActionStartup::checkLaunchStartup () private
Checks and sets the launch startup configuration.
Definition at line 357 of file class.action.startup.php.
    {
        global $bearsamppConfig;
        $this->writeLog( 'Check launch startup' );
        if ( $bearsamppConfig->isLaunchStartup() ) {
            Util::enableLaunchStartup();
        }
        else {
            Util::disableLaunchStartup();
        }
    }
References $bearsamppConfig, Util\disableLaunchStartup(), Util\enableLaunchStartup(), and writeLog().
Referenced by processWindow().
checkPath()
ActionStartup::checkPath () private
Checks the application path and logs the last path content.
Definition at line 433 of file class.action.startup.php.
    {
        global $bearsamppCore, $bearsamppLang;
        $this->splash->setTextLoading( $bearsamppLang->getValue( Lang::STARTUP_CHECK_PATH_TEXT ) );
        $this->splash->incrProgressBar();
        $this->writeLog( 'Last path: ' . $bearsamppCore->getLastPathContent() );
    }
References $bearsamppCore, $bearsamppLang, Lang\STARTUP_CHECK_PATH_TEXT, and writeLog().
Referenced by processWindow().
checkPathRegKey()
ActionStartup::checkPathRegKey () private
Checks and updates the application path registry key.
Definition at line 486 of file class.action.startup.php.
    {
        global $bearsamppRoot, $bearsamppLang, $bearsamppRegistry;
        $this->splash->setTextLoading( sprintf( $bearsamppLang->getValue( Lang::STARTUP_REGISTRY_TEXT ), Registry::APP_PATH_REG_ENTRY ) );
        $this->splash->incrProgressBar();
        $currentAppPathRegKey = Util::getAppPathRegKey();
        $genAppPathRegKey     = Util::formatWindowsPath( $bearsamppRoot->getRootPath() );
        $this->writeLog( 'Current app path reg key: ' . $currentAppPathRegKey );
        $this->writeLog( 'Gen app path reg key: ' . $genAppPathRegKey );
        if ( $currentAppPathRegKey != $genAppPathRegKey ) {
            if ( !Util::setAppPathRegKey( $genAppPathRegKey ) ) {
                if ( !empty( $this->error ) ) {
                    $this->error .= PHP_EOL . PHP_EOL;
                }
                $this->error .= sprintf( $bearsamppLang->getValue( Lang::STARTUP_REGISTRY_ERROR_TEXT ), Registry::APP_PATH_REG_ENTRY );
                $this->error .= PHP_EOL . $bearsamppRegistry->getLatestError();
            }
            else {
                $this->writeLog( 'Need restart: checkPathRegKey' );
                $this->restart = true;
            }
        }
    }
References $bearsamppLang, $bearsamppRoot, Registry\APP_PATH_REG_ENTRY, Util\formatWindowsPath(), Util\getAppPathRegKey(), Util\setAppPathRegKey(), Lang\STARTUP_REGISTRY_ERROR_TEXT, Lang\STARTUP_REGISTRY_TEXT, and writeLog().
Referenced by processWindow().
checkSystemPathRegKey()
ActionStartup::checkSystemPathRegKey () private
Checks and updates the system PATH registry key. Ensures the application bins registry entry is at the beginning of the system PATH. Logs the current and new system PATH. Sets an error message if the system PATH update fails. Sets a restart flag if the system PATH is updated.
Definition at line 552 of file class.action.startup.php.
    {
        global $bearsamppLang, $bearsamppRegistry;
        $this->splash->setTextLoading( sprintf( $bearsamppLang->getValue( Lang::STARTUP_REGISTRY_TEXT ), Registry::SYSPATH_REG_ENTRY ) );
        $this->splash->incrProgressBar();
        $currentSysPathRegKey = Util::getSysPathRegKey();
        $this->writeLog( 'Current system PATH: ' . $currentSysPathRegKey );
        $newSysPathRegKey = str_replace( '%' . Registry::APP_BINS_REG_ENTRY . '%;', '', $currentSysPathRegKey );
        $newSysPathRegKey = str_replace( '%' . Registry::APP_BINS_REG_ENTRY . '%', '', $newSysPathRegKey );
        $newSysPathRegKey = '%' . Registry::APP_BINS_REG_ENTRY . '%;' . $newSysPathRegKey;
        $this->writeLog( 'New system PATH: ' . $newSysPathRegKey );
        if ( $currentSysPathRegKey != $newSysPathRegKey ) {
            if ( !Util::setSysPathRegKey( $newSysPathRegKey ) ) {
                if ( !empty( $this->error ) ) {
                    $this->error .= PHP_EOL . PHP_EOL;
                }
                $this->error .= sprintf( $bearsamppLang->getValue( Lang::STARTUP_REGISTRY_ERROR_TEXT ), Registry::SYSPATH_REG_ENTRY );
                $this->error .= PHP_EOL . $bearsamppRegistry->getLatestError();
            }
            else {
                $this->writeLog( 'Need restart: checkSystemPathRegKey' );
                $this->restart = true;
            }
        }
        else {
            $this->writeLog( 'Refresh system PATH: ' . $currentSysPathRegKey );
            Util::setSysPathRegKey( str_replace( '%' . Registry::APP_BINS_REG_ENTRY . '%', '', $currentSysPathRegKey ) );
            Util::setSysPathRegKey( $currentSysPathRegKey );
        }
    }
References $bearsamppLang, Registry\APP_BINS_REG_ENTRY, Util\getSysPathRegKey(), Util\setSysPathRegKey(), Lang\STARTUP_REGISTRY_ERROR_TEXT, Lang\STARTUP_REGISTRY_TEXT, Registry\SYSPATH_REG_ENTRY, and writeLog().
Referenced by processWindow().
cleanOldBehaviors()
ActionStartup::cleanOldBehaviors () private
Cleans old behaviors by removing outdated registry entries.
Definition at line 288 of file class.action.startup.php.
    {
        global $bearsamppLang, $bearsamppRegistry;
        $this->writeLog( 'Clean old behaviors' );
        $this->splash->setTextLoading( $bearsamppLang->getValue( Lang::STARTUP_CLEAN_OLD_BEHAVIORS_TEXT ) );
        $this->splash->incrProgressBar();
        // App >= 1.0.13
        $bearsamppRegistry->deleteValue(
            Registry::HKEY_LOCAL_MACHINE,
            'SOFTWARE\Microsoft\Windows\CurrentVersion\Run',
            APP_TITLE
        );
    }
References $bearsamppLang, APP_TITLE, Registry\HKEY_LOCAL_MACHINE, Lang\STARTUP_CLEAN_OLD_BEHAVIORS_TEXT, and writeLog().
Referenced by processWindow().
cleanTmpFolders()
ActionStartup::cleanTmpFolders () private
Cleans temporary folders by removing unnecessary files.
Definition at line 273 of file class.action.startup.php.
    {
        global $bearsamppRoot, $bearsamppLang, $bearsamppCore;
        $this->splash->setTextLoading( $bearsamppLang->getValue( Lang::STARTUP_CLEAN_TMP_TEXT ) );
        $this->splash->incrProgressBar();
        $this->writeLog( 'Clear tmp folders' );
        Util::clearFolder( $bearsamppRoot->getTmpPath(), array('cachegrind', 'composer', 'openssl', 'mailhog', 'mailpit', 'xlight', 'npm-cache', 'pip', 'yarn', '.gitignore') );
        Util::clearFolder( $bearsamppCore->getTmpPath(), array('.gitignore') );
    }
References $bearsamppCore, $bearsamppLang, $bearsamppRoot, Util\clearFolder(), Lang\STARTUP_CLEAN_TMP_TEXT, and writeLog().
Referenced by processWindow().
createSslCrts()
ActionStartup::createSslCrts () private
Creates SSL certificates if they do not already exist. Logs the creation process.
Definition at line 608 of file class.action.startup.php.
    {
        global $bearsamppLang, $bearsamppOpenSsl;
        $this->splash->incrProgressBar();
        if ( !$bearsamppOpenSsl->existsCrt( 'localhost' ) ) {
            $this->splash->setTextLoading( sprintf( $bearsamppLang->getValue( Lang::STARTUP_GEN_SSL_CRT_TEXT ), 'localhost' ) );
            $bearsamppOpenSsl->createCrt( 'localhost' );
        }
    }
References $bearsamppLang, and Lang\STARTUP_GEN_SSL_CRT_TEXT.
Referenced by processWindow().
installServices()
ActionStartup::installServices () private
Installs and starts services for the application. Checks if services are already installed and updates them if necessary. Logs the installation process and any errors encountered.
Definition at line 624 of file class.action.startup.php.
    {
        global $bearsamppLang, $bearsamppBins, $bearsamppRoot;
        if ( !$this->restart ) {
            foreach ( $bearsamppBins->getServices() as $sName => $service ) {
                $serviceError            = '';
                $serviceRestart          = false;
                $serviceAlreadyInstalled = false;
                $serviceToRemove         = false;
                $startServiceTime        = Util::getMicrotime();
                $syntaxCheckCmd = null;
                $bin            = null;
                $port           = 0;
                if ( $sName == BinMailhog::SERVICE_NAME ) {
                    $bin  = $bearsamppBins->getMailhog();
                    $port = $bearsamppBins->getMailhog()->getSmtpPort();
                }
                elseif ( $sName == BinMailpit::SERVICE_NAME ) {
                    $bin  = $bearsamppBins->getMailpit();
                    $port = $bearsamppBins->getMailpit()->getSmtpPort();
                }
                elseif ( $sName == BinMemcached::SERVICE_NAME ) {
                    $bin  = $bearsamppBins->getMemcached();
                    $port = $bearsamppBins->getMemcached()->getPort();
                }
                elseif ( $sName == BinApache::SERVICE_NAME ) {
                    $bin            = $bearsamppBins->getApache();
                    $port           = $bearsamppBins->getApache()->getPort();
                    $syntaxCheckCmd = BinApache::CMD_SYNTAX_CHECK;
                }
                elseif ( $sName == BinMysql::SERVICE_NAME ) {
                    $bin            = $bearsamppBins->getMysql();
                    $port           = $bearsamppBins->getMysql()->getPort();
                    $syntaxCheckCmd = BinMysql::CMD_SYNTAX_CHECK;
                }
                elseif ( $sName == BinMariadb::SERVICE_NAME ) {
                    $bin            = $bearsamppBins->getMariadb();
                    $port           = $bearsamppBins->getMariadb()->getPort();
                    $syntaxCheckCmd = BinMariadb::CMD_SYNTAX_CHECK;
                }
                elseif ( $sName == BinPostgresql::SERVICE_NAME ) {
                    $bin  = $bearsamppBins->getPostgresql();
                    $port = $bearsamppBins->getPostgresql()->getPort();
                }
                elseif ( $sName == BinFilezilla::SERVICE_NAME ) {
                    $bin  = $bearsamppBins->getFilezilla();
                    $port = $bearsamppBins->getFilezilla()->getPort();
                }
                elseif ( $sName == BinXlight::SERVICE_NAME ) {
                    $bin  = $bearsamppBins->getXlight();
                    $port = $bearsamppBins->getXlight()->getPort();
                }
                $name = $bin->getName() . ' ' . $bin->getVersion() . ' (' . $service->getName() . ')';
                $this->splash->incrProgressBar();
                $this->splash->setTextLoading( sprintf( $bearsamppLang->getValue( Lang::STARTUP_CHECK_SERVICE_TEXT ), $name ) );
                $serviceInfos = $service->infos();
                if ( $serviceInfos !== false ) {
                    $serviceAlreadyInstalled = true;
                    $this->writeLog( $name . ' service already installed' );
                    foreach ( $serviceInfos as $key => $value ) {
                        $this->writeLog( '-> ' . $key . ': ' . $value );
                    }
                    $serviceGenPathName = trim( str_replace( '"', '', $service->getBinPath() . ($service->getParams() ? ' ' . $service->getParams() : '') ) );
                    $serviceVbsPathName = trim( str_replace( '"', '', $serviceInfos[Win32Service::VBS_PATH_NAME] ) );
                    if ( $serviceGenPathName != $serviceVbsPathName ) {
                        $serviceToRemove = true;
                        $this->writeLog( $name . ' service has to be removed' );
                        $this->writeLog( '-> serviceGenPathName: ' . $serviceGenPathName );
                        $this->writeLog( '-> serviceVbsPathName: ' . $serviceVbsPathName );
                    }
                }
                $this->splash->incrProgressBar();
                if ( $serviceToRemove && !$service->delete() ) {
                    $serviceRestart = true;
                }
                if ( !$serviceRestart ) {
                    $isPortInUse = Util::isPortInUse( $port );
                    if ( $isPortInUse === false ) {
                        $this->splash->incrProgressBar();
                        if ( !$serviceAlreadyInstalled && !$serviceToRemove ) {
                            $this->splash->setTextLoading( sprintf( $bearsamppLang->getValue( Lang::STARTUP_INSTALL_SERVICE_TEXT ), $name ) );
                            if ( !$service->create() ) {
                                $serviceError .= sprintf( $bearsamppLang->getValue( Lang::STARTUP_SERVICE_CREATE_ERROR ), $service->getError() );
                            }
                        }
                        $this->splash->incrProgressBar();
                        $this->splash->setTextLoading( sprintf( $bearsamppLang->getValue( Lang::STARTUP_START_SERVICE_TEXT ), $name ) );
                        if ( !$service->start() ) {
                            if ( !empty( $serviceError ) ) {
                                $serviceError .= PHP_EOL;
                            }
                            $serviceError .= sprintf( $bearsamppLang->getValue( Lang::STARTUP_SERVICE_START_ERROR ), $service->getError() );
                            if ( !empty( $syntaxCheckCmd ) ) {
                                $cmdSyntaxCheck = $bin->getCmdLineOutput( $syntaxCheckCmd );
                                if ( !$cmdSyntaxCheck['syntaxOk'] ) {
                                    $serviceError .= PHP_EOL . sprintf( $bearsamppLang->getValue( Lang::STARTUP_SERVICE_SYNTAX_ERROR ), $cmdSyntaxCheck['content'] );
                                }
                            }
                        }
                        $this->splash->incrProgressBar();
                    }
                    else {
                        if ( !empty( $serviceError ) ) {
                            $serviceError .= PHP_EOL;
                        }
                        $serviceError .= sprintf( $bearsamppLang->getValue( Lang::STARTUP_SERVICE_PORT_ERROR ), $port, $isPortInUse );
                        $this->splash->incrProgressBar( 3 );
                    }
                }
                else {
                    $this->writeLog( 'Need restart: installService ' . $bin->getName() );
                    $this->restart = true;
                    $this->splash->incrProgressBar( 3 );
                }
                if ( !empty( $serviceError ) ) {
                    if ( !empty( $this->error ) ) {
                        $this->error .= PHP_EOL . PHP_EOL;
                    }
                    $this->error .= sprintf( $bearsamppLang->getValue( Lang::STARTUP_SERVICE_ERROR ), $name ) . PHP_EOL . $serviceError;
                }
                else {
                    $this->writeLog( $name . ' service installed in ' . round( Util::getMicrotime() - $startServiceTime, 3 ) . 's' );
                }
            }
        }
        else {
            $this->splash->incrProgressBar( self::GAUGE_SERVICES * count( $bearsamppBins->getServices() ) );
        }
    }
References $bearsamppBins, $bearsamppLang, $bearsamppRoot, $port, BinApache\CMD_SYNTAX_CHECK, BinMariadb\CMD_SYNTAX_CHECK, BinMysql\CMD_SYNTAX_CHECK, Util\getMicrotime(), Util\isPortInUse(), BinApache\SERVICE_NAME, BinFilezilla\SERVICE_NAME, BinMailhog\SERVICE_NAME, BinMailpit\SERVICE_NAME, BinMariadb\SERVICE_NAME, BinMemcached\SERVICE_NAME, BinMysql\SERVICE_NAME, BinPostgresql\SERVICE_NAME, BinXlight\SERVICE_NAME, Lang\STARTUP_CHECK_SERVICE_TEXT, Lang\STARTUP_INSTALL_SERVICE_TEXT, Lang\STARTUP_SERVICE_CREATE_ERROR, Lang\STARTUP_SERVICE_ERROR, Lang\STARTUP_SERVICE_PORT_ERROR, Lang\STARTUP_SERVICE_START_ERROR, Lang\STARTUP_SERVICE_SYNTAX_ERROR, Lang\STARTUP_START_SERVICE_TEXT, Win32Service\VBS_PATH_NAME, and writeLog().
Referenced by processWindow().
killOldInstances()
ActionStartup::killOldInstances () private
Kills old instances of Bearsampp processes.
Definition at line 308 of file class.action.startup.php.
    {
        global $bearsamppLang;
        $this->splash->setTextLoading( $bearsamppLang->getValue( Lang::STARTUP_KILL_OLD_PROCS_TEXT ) );
        $this->splash->incrProgressBar();
        // Stop services
        /*foreach ($bearsamppBins->getServices() as $sName => $service) {
            $serviceInfos = $service->infos();
            if ($serviceInfos === false) {
                continue;
            }
            $service->stop();
        }*/
        // Stop third party procs
        $procsKilled = Win32Ps::killBins();
        if ( !empty( $procsKilled ) ) {
            $this->writeLog( 'Procs killed:' );
            $procsKilledSort = array();
            foreach ( $procsKilled as $proc ) {
                $unixExePath       = Util::formatUnixPath( $proc[Win32Ps::EXECUTABLE_PATH] );
                $procsKilledSort[] = '-> ' . basename( $unixExePath ) . ' (PID ' . $proc[Win32Ps::PROCESS_ID] . ') in ' . $unixExePath;
            }
            sort( $procsKilledSort );
            foreach ( $procsKilledSort as $proc ) {
                $this->writeLog( $proc );
            }
        }
    }
References $bearsamppLang, $proc, Win32Ps\EXECUTABLE_PATH, Util\formatUnixPath(), Win32Ps\killBins(), Win32Ps\PROCESS_ID, Lang\STARTUP_KILL_OLD_PROCS_TEXT, and writeLog().
Referenced by processWindow().
processWindow()
ActionStartup::processWindow ($window, $id, $ctrl, $param1, $param2)
Processes the main window events during startup.
Parameters
mixed $window The window handle.
int $id The event ID.
mixed $ctrl The control that triggered the event.
mixed $param1 Additional parameter 1.
mixed $param2 Additional parameter 2.
Definition at line 72 of file class.action.startup.php.
    {
        global $bearsamppRoot, $bearsamppCore, $bearsamppLang, $bearsamppBins, $bearsamppTools, $bearsamppApps, $bearsamppWinbinder;
        // Rotation logs
        $this->rotationLogs();
        // Clean
        $this->cleanTmpFolders();
        $this->cleanOldBehaviors();
        // List procs
        if ( $bearsamppRoot->getProcs() !== false ) {
            $this->writeLog( 'List procs:' );
            $listProcs = array();
            foreach ( $bearsamppRoot->getProcs() as $proc ) {
                $unixExePath = Util::formatUnixPath( $proc[Win32Ps::EXECUTABLE_PATH] );
                $listProcs[] = '-> ' . basename( $unixExePath ) . ' (PID ' . $proc[Win32Ps::PROCESS_ID] . ') in ' . $unixExePath;
            }
            sort( $listProcs );
            foreach ( $listProcs as $proc ) {
                $this->writeLog( $proc );
            }
        }
        // List modules
        $this->writeLog( 'List bins modules:' );
        foreach ( $bearsamppBins->getAll() as $module ) {
            if ( !$module->isEnable() ) {
                $this->writeLog( '-> ' . $module->getName() . ': ' . $bearsamppLang->getValue( Lang::DISABLED ) );
            }
            else {
                $this->writeLog( '-> ' . $module->getName() . ': ' . $module->getVersion() . ' (' . $module->getRelease() . ')' );
            }
        }
        $this->writeLog( 'List tools modules:' );
        foreach ( $bearsamppTools->getAll() as $module ) {
            if ( !$module->isEnable() ) {
                $this->writeLog( '-> ' . $module->getName() . ': ' . $bearsamppLang->getValue( Lang::DISABLED ) );
            }
            else {
                $this->writeLog( '-> ' . $module->getName() . ': ' . $module->getVersion() . ' (' . $module->getRelease() . ')' );
            }
        }
        $this->writeLog( 'List apps modules:' );
        foreach ( $bearsamppApps->getAll() as $module ) {
            if ( !$module->isEnable() ) {
                $this->writeLog( '-> ' . $module->getName() . ': ' . $bearsamppLang->getValue( Lang::DISABLED ) );
            }
            else {
                $this->writeLog( '-> ' . $module->getName() . ': ' . $module->getVersion() . ' (' . $module->getRelease() . ')' );
            }
        }
        // Kill old instances
        $this->killOldInstances();
        // Prepare app
        $this->refreshHostname();
        $this->checkLaunchStartup();
        $this->checkBrowser();
        $this->sysInfos();
        $this->refreshAliases();
        $this->refreshVhosts();
        // Check app path
        $this->checkPath();
        $this->scanFolders();
        $this->changePath();
        $this->savePath();
        // Check BEARSAMPP_PATH, BEARSAMPP_BINS and System Path reg keys
        $this->checkPathRegKey();
        $this->checkBinsRegKey();
        $this->checkSystemPathRegKey();
        // Update config
        $this->updateConfig();
        // Create SSL certificates
        $this->createSslCrts();
        // Install
        $this->installServices();
        // Actions if everything OK
        if ( !$this->restart && empty( $this->error ) ) {
            $this->refreshGitRepos();
            $this->writeLog( 'Started in ' . round( Util::getMicrotime() - $this->startTime, 3 ) . 's' );
        }
        else {
            $this->splash->incrProgressBar( 2 );
        }
        if ( $this->restart ) {
            $this->writeLog( APP_TITLE . ' has to be restarted' );
            $this->splash->setTextLoading(
                sprintf(
                    $bearsamppLang->getValue( Lang::STARTUP_PREPARE_RESTART_TEXT ),
                    APP_TITLE . ' ' . $bearsamppCore->getAppVersion()
                )
            );
            foreach ( $bearsamppBins->getServices() as $sName => $service ) {
                $service->delete();
            }
            $bearsamppCore->setExec( ActionExec::RESTART );
        }
        if ( !empty( $this->error ) ) {
            $this->writeLog( 'Error: ' . $this->error );
            $bearsamppWinbinder->messageBoxError( $this->error, $bearsamppLang->getValue( Lang::STARTUP_ERROR_TITLE ) );
        }
        Util::startLoading();
        $bearsamppWinbinder->destroyWindow( $window );
    }
References $bearsamppBins, $bearsamppCore, $bearsamppLang, $bearsamppRoot, $proc, APP_TITLE, changePath(), checkBinsRegKey(), checkBrowser(), checkLaunchStartup(), checkPath(), checkPathRegKey(), checkSystemPathRegKey(), cleanOldBehaviors(), cleanTmpFolders(), createSslCrts(), Lang\DISABLED, Win32Ps\EXECUTABLE_PATH, Util\formatUnixPath(), Util\getMicrotime(), installServices(), killOldInstances(), Win32Ps\PROCESS_ID, refreshAliases(), refreshGitRepos(), refreshHostname(), refreshVhosts(), ActionExec\RESTART, rotationLogs(), savePath(), scanFolders(), Util\startLoading(), Lang\STARTUP_ERROR_TITLE, Lang\STARTUP_PREPARE_RESTART_TEXT, sysInfos(), updateConfig(), and writeLog().
refreshAliases()
ActionStartup::refreshAliases () private
Refreshes the aliases in the Apache configuration.
Definition at line 405 of file class.action.startup.php.
    {
        global $bearsamppConfig, $bearsamppLang, $bearsamppBins;
        $this->splash->setTextLoading( $bearsamppLang->getValue( Lang::STARTUP_REFRESH_ALIAS_TEXT ) );
        $this->splash->incrProgressBar();
        $this->writeLog( 'Refresh aliases' );
        $bearsamppBins->getApache()->refreshAlias( $bearsamppConfig->isOnline() );
    }
References $bearsamppBins, $bearsamppConfig, $bearsamppLang, Lang\STARTUP_REFRESH_ALIAS_TEXT, and writeLog().
Referenced by processWindow().
refreshGitRepos()
ActionStartup::refreshGitRepos () private
Refreshes Git repositories if the scan on startup is enabled. Logs the number of repositories found.
Definition at line 767 of file class.action.startup.php.
    {
        global $bearsamppLang, $bearsamppTools;
        $this->splash->incrProgressBar();
        if ( $bearsamppTools->getGit()->isScanStartup() ) {
            $this->splash->setTextLoading( $bearsamppLang->getValue( Lang::STARTUP_REFRESH_GIT_REPOS_TEXT ) );
            $repos = $bearsamppTools->getGit()->findRepos( false );
            $this->writeLog( 'Update GIT repos: ' . count( $repos ) . ' found' );
        }
    }
References $bearsamppLang, Lang\STARTUP_REFRESH_GIT_REPOS_TEXT, and writeLog().
Referenced by processWindow().
refreshHostname()
ActionStartup::refreshHostname () private
Refreshes the hostname in the configuration.
Definition at line 343 of file class.action.startup.php.
    {
        global $bearsamppConfig, $bearsamppLang;
        $this->splash->setTextLoading( $bearsamppLang->getValue( Lang::STARTUP_REFRESH_HOSTNAME_TEXT ) );
        $this->splash->incrProgressBar();
        $this->writeLog( 'Refresh hostname' );
        $bearsamppConfig->replace( Config::CFG_HOSTNAME, gethostname() );
    }
References $bearsamppConfig, $bearsamppLang, Config\CFG_HOSTNAME, Lang\STARTUP_REFRESH_HOSTNAME_TEXT, and writeLog().
Referenced by processWindow().
refreshVhosts()
ActionStartup::refreshVhosts () private
Refreshes the virtual hosts in the Apache configuration.
Definition at line 419 of file class.action.startup.php.
    {
        global $bearsamppConfig, $bearsamppLang, $bearsamppBins;
        $this->splash->setTextLoading( $bearsamppLang->getValue( Lang::STARTUP_REFRESH_VHOSTS_TEXT ) );
        $this->splash->incrProgressBar();
        $this->writeLog( 'Refresh vhosts' );
        $bearsamppBins->getApache()->refreshVhosts( $bearsamppConfig->isOnline() );
    }
References $bearsamppBins, $bearsamppConfig, $bearsamppLang, Lang\STARTUP_REFRESH_VHOSTS_TEXT, and writeLog().
Referenced by processWindow().
rotationLogs()
ActionStartup::rotationLogs () private
Rotates the logs by archiving old logs and purging old archives.
Definition at line 192 of file class.action.startup.php.
    {
        global $bearsamppRoot, $bearsamppCore, $bearsamppConfig, $bearsamppLang, $bearsamppBins;
        $this->splash->setTextLoading( $bearsamppLang->getValue( Lang::STARTUP_ROTATION_LOGS_TEXT ) );
        $this->splash->incrProgressBar();
        $archivesPath = $bearsamppRoot->getLogsPath() . '/archives';
        if ( !is_dir( $archivesPath ) ) {
            mkdir( $archivesPath, 0777, true );
            return;
        }
        $date               = date( 'Y-m-d-His', time() );
        $archiveLogsPath    = $archivesPath . '/' . $date;
        $archiveScriptsPath = $archiveLogsPath . '/scripts';
        // Create archive folders
        mkdir( $archiveLogsPath, 0777, true );
        mkdir( $archiveScriptsPath, 0777, true );
        // Count archives
        $archives = array();
        $handle   = @opendir( $archivesPath );
        if ( !$handle ) {
            return;
        }
        while ( false !== ($file = readdir( $handle )) ) {
            if ( $file == '.' || $file == '..' ) {
                continue;
            }
            $archives[] = $archivesPath . '/' . $file;
        }
        closedir( $handle );
        sort( $archives );
        // Remove old archives
        if ( count( $archives ) > $bearsamppConfig->getMaxLogsArchives() ) {
            $total = count( $archives ) - $bearsamppConfig->getMaxLogsArchives();
            for ( $i = 0; $i < $total; $i++ ) {
                Util::deleteFolder( $archives[$i] );
            }
        }
        // Logs
        $srcPath = $bearsamppRoot->getLogsPath();
        $handle  = @opendir( $srcPath );
        if ( !$handle ) {
            return;
        }
        while ( false !== ($file = readdir( $handle )) ) {
            if ( $file == '.' || $file == '..' || is_dir( $srcPath . '/' . $file ) ) {
                continue;
            }
            copy( $srcPath . '/' . $file, $archiveLogsPath . '/' . $file );
        }
        closedir( $handle );
        // Scripts
        $srcPath = $bearsamppCore->getTmpPath();
        $handle  = @opendir( $srcPath );
        if ( !$handle ) {
            return;
        }
        while ( false !== ($file = readdir( $handle )) ) {
            if ( $file == '.' || $file == '..' || is_dir( $srcPath . '/' . $file ) ) {
                continue;
            }
            copy( $srcPath . '/' . $file, $archiveScriptsPath . '/' . $file );
        }
        closedir( $handle );
        // Purge logs
        Util::clearFolders( $bearsamppBins->getLogsPath() );
        Util::clearFolder( $bearsamppRoot->getLogsPath(), array('archives', '.gitignore') );
    }
References $bearsamppBins, $bearsamppConfig, $bearsamppCore, $bearsamppLang, $bearsamppRoot, Util\clearFolder(), Util\clearFolders(), Util\deleteFolder(), and Lang\STARTUP_ROTATION_LOGS_TEXT.
Referenced by processWindow().
savePath()
ActionStartup::savePath () private
Saves the current application path.
Definition at line 475 of file class.action.startup.php.
    {
        global $bearsamppCore;
        file_put_contents( $bearsamppCore->getLastPath(), $this->rootPath );
        $this->writeLog( 'Save current path: ' . $this->rootPath );
    }
References $bearsamppCore, and writeLog().
Referenced by processWindow().
scanFolders()
ActionStartup::scanFolders () private
Scans folders and logs the number of files to scan.
Definition at line 446 of file class.action.startup.php.
    {
        global $bearsamppLang;
        $this->splash->setTextLoading( $bearsamppLang->getValue( Lang::STARTUP_SCAN_FOLDERS_TEXT ) );
        $this->splash->incrProgressBar();
        $this->filesToScan = Util::getFilesToScan();
        $this->writeLog( 'Files to scan: ' . count( $this->filesToScan ) );
    }
References $bearsamppLang, Util\getFilesToScan(), Lang\STARTUP_SCAN_FOLDERS_TEXT, and writeLog().
Referenced by processWindow().
sysInfos()
ActionStartup::sysInfos () private
Logs system information.
Definition at line 391 of file class.action.startup.php.
    {
        global $bearsamppLang;
        $this->splash->setTextLoading( $bearsamppLang->getValue( Lang::STARTUP_SYS_INFOS ) );
        $this->splash->incrProgressBar();
        $os = Batch::getOsInfo();
        $this->writeLog( sprintf( 'OS: %s', $os ) );
    }
References $bearsamppLang, Batch\getOsInfo(), Lang\STARTUP_SYS_INFOS, and writeLog().
Referenced by processWindow().
updateConfig()
ActionStartup::updateConfig () private
Updates the configuration for bins, tools, and apps. Logs the update process.
Definition at line 591 of file class.action.startup.php.
    {
        global $bearsamppLang, $bearsamppBins, $bearsamppTools, $bearsamppApps;
        $this->splash->setTextLoading( $bearsamppLang->getValue( Lang::STARTUP_UPDATE_CONFIG_TEXT ) );
        $this->splash->incrProgressBar();
        $this->writeLog( 'Update config' );
        $bearsamppBins->update();
        $bearsamppTools->update();
        $bearsamppApps->update();
    }
References $bearsamppBins, $bearsamppLang, Lang\STARTUP_UPDATE_CONFIG_TEXT, and writeLog().
Referenced by processWindow().
writeLog()
ActionStartup::writeLog ($log) private
Writes a log message to the startup log file.
Parameters
string $log The log message to write.
Definition at line 785 of file class.action.startup.php.
    {
        global $bearsamppRoot;
        Util::logDebug( $log, $bearsamppRoot->getStartupLogFilePath() );
    }
References $bearsamppRoot, and Util\logDebug().
Referenced by __construct(), changePath(), checkBinsRegKey(), checkBrowser(), checkLaunchStartup(), checkPath(), checkPathRegKey(), checkSystemPathRegKey(), cleanOldBehaviors(), cleanTmpFolders(), installServices(), killOldInstances(), processWindow(), refreshAliases(), refreshGitRepos(), refreshHostname(), refreshVhosts(), savePath(), scanFolders(), sysInfos(), and updateConfig().
Field Documentation
$error
ActionStartup::$error private
Definition at line 20 of file class.action.startup.php.
$filesToScan
ActionStartup::$filesToScan private
Definition at line 23 of file class.action.startup.php.
$restart
ActionStartup::$restart private
Definition at line 18 of file class.action.startup.php.
$rootPath
ActionStartup::$rootPath private
Definition at line 22 of file class.action.startup.php.
$splash
ActionStartup::$splash private
Definition at line 17 of file class.action.startup.php.
$startTime
ActionStartup::$startTime private
Definition at line 19 of file class.action.startup.php.
GAUGE_OTHERS
const ActionStartup::GAUGE_OTHERS = 19
Definition at line 26 of file class.action.startup.php.
GAUGE_SERVICES
const ActionStartup::GAUGE_SERVICES = 5
Definition at line 25 of file class.action.startup.php.
The documentation for this class was generated from the following file:
E:/Bearsampp-development/sandbox/core/classes/actions/class.action.startup.php