Bearsampp: Core Class Reference
Core Class Reference
Public Member Functions
__construct ()
__toString ()
addLoadingPid ($pid)
getAjaxPath ($aetrayPath=false)
getAppVersion ()
getExec ($aetrayPath=false)
getFileFromUrl (string $moduleUrl, string $filePath, $progressBar=false)
getHomepagePath ($aetrayPath=false)
getHostsEditorExe ($aetrayPath=false)
getHostsEditorPath ($aetrayPath=false)
getIconsPath ($aetrayPath=false)
getisRootFilePath ($aetrayPath=false)
getLangsPath ($aetrayPath=false)
getLastPath ($aetrayPath=false)
getLastPathContent ()
getLibsPath ($aetrayPath=false)
getLnExe ($aetrayPath=false)
getLnPath ($aetrayPath=false)
getLoadingPid ($aetrayPath=false)
getNssmExe ($aetrayPath=false)
getNssmPath ($aetrayPath=false)
getOpenSslConf ($aetrayPath=false)
getOpenSslExe ($aetrayPath=false)
getOpenSslPath ($aetrayPath=false)
getPhpExe ($aetrayPath=false)
getPhpPath ($aetrayPath=false)
getPwgenExe ($aetrayPath=false)
getPwgenPath ($aetrayPath=false)
getResourcesPath ($aetrayPath=false)
getScript ($type)
getScriptsPath ($aetrayPath=false)
getSetEnvExe ($aetrayPath=false)
getSetEnvPath ($aetrayPath=false)
getTmpPath ($aetrayPath=false)
setExec ($action)
unzipFile ($filePath, $destination, $progressCallback=null)
Data Fields
const APP_VERSION = 'version.dat'
const EXEC = 'exec.dat'
const HOSTSEDITOR_EXE = 'hEdit_x64.exe'
const HOSTSEDITOR_VERSION = '1.3'
const isRoot_FILE = 'root.php'
const LAST_PATH = 'lastPath.dat'
const LN_EXE = 'ln.exe'
const LN_VERSION = '2.928'
const LOADING_PID = 'loading.pid'
const NSSM_EXE = 'nssm.exe'
const NSSM_VERSION = '2.24'
const OPENSSL_CONF = 'openssl.cfg'
const OPENSSL_EXE = 'openssl.exe'
const OPENSSL_VERSION = '1.1.0c'
const PATH_LIN_PLACEHOLDER = '~BEARSAMPP_LIN_PATH~'
const PATH_WIN_PLACEHOLDER = '~BEARSAMPP_WIN_PATH~'
const PHP_CONF = 'php.ini'
const PHP_EXE = 'php-win.exe'
const PHP_VERSION = '5.4.23'
const PWGEN_EXE = "PWGenPortable.exe"
const PWGEN_VERSION = '3.5.4'
const SCRIPT_EXEC_SILENT = 'execSilent.vbs'
const SETENV_EXE = 'SetEnv.exe'
const SETENV_VERSION = '1.09'
Detailed Description
Class Core
This class provides core functionalities and constants for the Bearsampp application. It includes methods for retrieving paths, managing application versions, and handling various executable files and configurations.
Definition at line 17 of file class.core.php.
Constructor & Destructor Documentation
__construct()
Core::__construct ()
Core constructor.
Loads the WinBinder extension if available.
Definition at line 59 of file class.core.php.
    {
        if ( extension_loaded( 'winbinder' ) ) {
            require_once $this->getLibsPath() . '/winbinder/winbinder.php';
        }
    }
References getLibsPath().
Member Function Documentation
__toString()
Core::__toString ()
Provides a string representation of the core object.
Returns
string A string describing the core object.
Definition at line 456 of file class.core.php.
    {
        return 'core object';
    }
addLoadingPid()
Core::addLoadingPid ($pid)
Adds a PID to the loading PID file.
Parameters
int $pid The PID to add.
Definition at line 266 of file class.core.php.
    {
        file_put_contents( $this->getLoadingPid(), $pid . PHP_EOL, FILE_APPEND );
    }
References getLoadingPid().
getAjaxPath()
Core::getAjaxPath ($aetrayPath = false)
Definition at line 141 of file class.core.php.
    {
        return $this->getHomepagePath( $aetrayPath ) . '/ajax';
    }
References getHomepagePath().
getAppVersion()
Core::getAppVersion ()
Retrieves the application version.
Returns
string|null The application version or null if not found.
Definition at line 191 of file class.core.php.
    {
        global $bearsamppLang;
        $filePath = $this->getResourcesPath() . '/' . self::APP_VERSION;
        if ( !is_file( $filePath ) ) {
            Util::logError( sprintf( $bearsamppLang->getValue( Lang::ERROR_CONF_NOT_FOUND ), APP_TITLE, $filePath ) );
            return null;
        }
        return trim( file_get_contents( $filePath ) );
    }
References $bearsamppLang, APP_TITLE, APP_VERSION, Lang\ERROR_CONF_NOT_FOUND, getResourcesPath(), and Util\logError().
getExec()
Core::getExec ($aetrayPath = false)
Retrieves the path to the exec file.
Parameters
bool $aetrayPath Whether to format the path for AeTrayMenu.
Returns
string The path to the exec file.
Definition at line 234 of file class.core.php.
    {
        return $this->getTmpPath( $aetrayPath ) . '/' . self::EXEC;
    }
References EXEC, and getTmpPath().
Referenced by setExec().
getFileFromUrl()
Core::getFileFromUrl (string $moduleUrl, string $filePath, $progressBar = false)
Fetches a file from a given URL and saves it to a specified file path.
This method attempts to retrieve the content from the provided URL and save it to the specified file path. If any error occurs during fetching or saving, it logs the error and returns an error message. If the operation is successful, it returns the file path. The method also logs the file size if the input stream is a valid resource.
Parameters
string $moduleUrl The URL from which to fetch the file content.
string $filePath The path where the file content should be saved.
bool $progressBar Optional. Whether to display a progress bar during the download process. Default is false.
Returns
array Returns the file path if successful, or an array with an error message if an error occurs.
Definition at line 564 of file class.core.php.
    {
        // Open the URL for reading
        $inputStream = @fopen( $moduleUrl, 'rb' );
        if ( $inputStream === false ) {
            Util::logError( 'Error fetching content from URL: ' . $moduleUrl );
            return ['error' => 'Error fetching module'];
        }
        // Open the file for writing
        $outputStream = @fopen( $filePath, 'wb' );
        if ( $outputStream === false ) {
            Util::logError( 'Error opening file for writing: ' . $filePath );
            fclose( $inputStream );
            return ['error' => 'Error saving module'];
        }
        // Read and write in chunks to avoid memory overload
        $bufferSize = 8096; // 8KB
        $chunksRead = 0;
        while ( !feof( $inputStream ) ) {
            $buffer = fread( $inputStream, $bufferSize );
            fwrite( $outputStream, $buffer );
            $chunksRead++;
            // Send progress update
            if ( $progressBar ) {
                $progress = $chunksRead;
                echo json_encode( ['progress' => $progress] );
                // Check if output buffering is active before calling ob_flush()
                if ( ob_get_length() !== false ) {
                    ob_flush();
                }
                flush();
            }
        }
        fclose( $inputStream );
        fclose( $outputStream );
        return ['success' => true];
    }
References Util\logError().
getHomepagePath()
Core::getHomepagePath ($aetrayPath = false)
Definition at line 136 of file class.core.php.
    {
        return $this->getResourcesPath( $aetrayPath ) . '/homepage';
    }
References getResourcesPath().
Referenced by getAjaxPath().
getHostsEditorExe()
Core::getHostsEditorExe ($aetrayPath = false)
Retrieves the path to the HostsEditor executable.
Parameters
bool $aetrayPath Whether to format the path for AeTrayMenu.
Returns
string The path to the HostsEditor executable.
Definition at line 398 of file class.core.php.
    {
        return $this->getHostsEditorPath( $aetrayPath ) . '/' . self::HOSTSEDITOR_EXE;
    }
References getHostsEditorPath(), and HOSTSEDITOR_EXE.
getHostsEditorPath()
Core::getHostsEditorPath ($aetrayPath = false)
Retrieves the path to the HostsEditor directory.
Parameters
bool $aetrayPath Whether to format the path for AeTrayMenu.
Returns
string The path to the HostsEditor directory.
Definition at line 386 of file class.core.php.
    {
        return $this->getLibsPath( $aetrayPath ) . '/hostseditor';
    }
References getLibsPath().
Referenced by getHostsEditorExe().
getIconsPath()
Core::getIconsPath ($aetrayPath = false)
Retrieves the path to the icons.
Parameters
bool $aetrayPath Whether to format the path for AeTrayMenu.
Returns
string The path to the icons.
Definition at line 115 of file class.core.php.
    {
        global $bearsamppCore;
        return $bearsamppCore->getResourcesPath( $aetrayPath ) . '/img/icons';
    }
References $bearsamppCore.
getisRootFilePath()
Core::getisRootFilePath ($aetrayPath = false)
Retrieves the path to the root file.
Parameters
bool $aetrayPath Whether to format the path for AeTrayMenu.
Returns
string The path to the root file.
Definition at line 179 of file class.core.php.
    {
        global $bearsamppRoot;
        return $bearsamppRoot->getCorePath( $aetrayPath ) . '/' . self::isRoot_FILE;
    }
References $bearsamppRoot, and isRoot_FILE.
getLangsPath()
Core::getLangsPath ($aetrayPath = false)
Retrieves the path to the language files.
Parameters
bool $aetrayPath Whether to format the path for AeTrayMenu.
Returns
string The path to the language files.
Definition at line 73 of file class.core.php.
    {
        global $bearsamppRoot;
        return $bearsamppRoot->getCorePath( $aetrayPath ) . '/langs';
    }
References $bearsamppRoot.
getLastPath()
Core::getLastPath ($aetrayPath = false)
Retrieves the path to the last path file.
Parameters
bool $aetrayPath Whether to format the path for AeTrayMenu.
Returns
string The path to the last path file.
Definition at line 212 of file class.core.php.
    {
        return $this->getResourcesPath( $aetrayPath ) . '/' . self::LAST_PATH;
    }
References getResourcesPath(), and LAST_PATH.
Referenced by getLastPathContent().
getLastPathContent()
Core::getLastPathContent ()
Retrieves the content of the last path file.
Returns
string|false The content of the last path file or false on failure.
Definition at line 222 of file class.core.php.
    {
        return @file_get_contents( $this->getLastPath() );
    }
References getLastPath().
getLibsPath()
Core::getLibsPath ($aetrayPath = false)
Retrieves the path to the libraries.
Parameters
bool $aetrayPath Whether to format the path for AeTrayMenu.
Returns
string The path to the libraries.
Definition at line 87 of file class.core.php.
    {
        global $bearsamppRoot;
        return $bearsamppRoot->getCorePath( $aetrayPath ) . '/libs';
    }
References $bearsamppRoot.
Referenced by __construct(), getHostsEditorPath(), getLnPath(), getNssmPath(), getOpenSslPath(), getPhpPath(), getPwgenPath(), getSetEnvPath(), and unzipFile().
getLnExe()
Core::getLnExe ($aetrayPath = false)
Retrieves the path to the LN executable.
Parameters
bool $aetrayPath Whether to format the path for AeTrayMenu.
Returns
string The path to the LN executable.
Definition at line 422 of file class.core.php.
    {
        return $this->getLnPath( $aetrayPath ) . '/' . self::LN_EXE;
    }
References getLnPath(), and LN_EXE.
getLnPath()
Core::getLnPath ($aetrayPath = false)
Retrieves the path to the LN directory.
Parameters
bool $aetrayPath Whether to format the path for AeTrayMenu.
Returns
string The path to the LN directory.
Definition at line 410 of file class.core.php.
    {
        return $this->getLibsPath( $aetrayPath ) . '/ln';
    }
References getLibsPath().
Referenced by getLnExe().
getLoadingPid()
Core::getLoadingPid ($aetrayPath = false)
Retrieves the path to the loading PID file.
Parameters
bool $aetrayPath Whether to format the path for AeTrayMenu.
Returns
string The path to the loading PID file.
Definition at line 256 of file class.core.php.
    {
        return $this->getResourcesPath( $aetrayPath ) . '/' . self::LOADING_PID;
    }
References getResourcesPath(), and LOADING_PID.
Referenced by addLoadingPid().
getNssmExe()
Core::getNssmExe ($aetrayPath = false)
Retrieves the path to the NSSM executable.
Parameters
bool $aetrayPath Whether to format the path for AeTrayMenu.
Returns
string The path to the NSSM executable.
Definition at line 338 of file class.core.php.
    {
        return $this->getNssmPath( $aetrayPath ) . '/' . self::NSSM_EXE;
    }
References getNssmPath(), and NSSM_EXE.
getNssmPath()
Core::getNssmPath ($aetrayPath = false)
Retrieves the path to the NSSM directory.
Parameters
bool $aetrayPath Whether to format the path for AeTrayMenu.
Returns
string The path to the NSSM directory.
Definition at line 326 of file class.core.php.
    {
        return $this->getLibsPath( $aetrayPath ) . '/nssm';
    }
References getLibsPath().
Referenced by getNssmExe().
getOpenSslConf()
Core::getOpenSslConf ($aetrayPath = false)
Retrieves the path to the OpenSSL configuration file.
Parameters
bool $aetrayPath Whether to format the path for AeTrayMenu.
Returns
string The path to the OpenSSL configuration file.
Definition at line 374 of file class.core.php.
    {
        return $this->getOpenSslPath( $aetrayPath ) . '/' . self::OPENSSL_CONF;
    }
References getOpenSslPath(), and OPENSSL_CONF.
getOpenSslExe()
Core::getOpenSslExe ($aetrayPath = false)
Retrieves the path to the OpenSSL executable.
Parameters
bool $aetrayPath Whether to format the path for AeTrayMenu.
Returns
string The path to the OpenSSL executable.
Definition at line 362 of file class.core.php.
    {
        return $this->getOpenSslPath( $aetrayPath ) . '/' . self::OPENSSL_EXE;
    }
References getOpenSslPath(), and OPENSSL_EXE.
getOpenSslPath()
Core::getOpenSslPath ($aetrayPath = false)
Retrieves the path to the OpenSSL directory.
Parameters
bool $aetrayPath Whether to format the path for AeTrayMenu.
Returns
string The path to the OpenSSL directory.
Definition at line 350 of file class.core.php.
    {
        return $this->getLibsPath( $aetrayPath ) . '/openssl';
    }
References getLibsPath().
Referenced by getOpenSslConf(), and getOpenSslExe().
getPhpExe()
Core::getPhpExe ($aetrayPath = false)
Retrieves the path to the PHP executable.
Parameters
bool $aetrayPath Whether to format the path for AeTrayMenu.
Returns
string The path to the PHP executable.
Definition at line 290 of file class.core.php.
    {
        return $this->getPhpPath( $aetrayPath ) . '/' . self::PHP_EXE;
    }
References getPhpPath(), and PHP_EXE.
getPhpPath()
Core::getPhpPath ($aetrayPath = false)
Retrieves the path to the PHP directory.
Parameters
bool $aetrayPath Whether to format the path for AeTrayMenu.
Returns
string The path to the PHP directory.
Definition at line 278 of file class.core.php.
    {
        return $this->getLibsPath( $aetrayPath ) . '/php';
    }
References getLibsPath().
Referenced by getPhpExe().
getPwgenExe()
Core::getPwgenExe ($aetrayPath = false)
Retrieves the path to the PWGen executable.
Parameters
bool $aetrayPath Whether to format the path for AeTrayMenu.
Returns
string The path to the PWGen executable.
Definition at line 446 of file class.core.php.
    {
        return $this->getPwgenPath( $aetrayPath ) . '/' . self::PWGEN_EXE;
    }
References getPwgenPath(), and PWGEN_EXE.
getPwgenPath()
Core::getPwgenPath ($aetrayPath = false)
Retrieves the path to the PWGen directory.
Parameters
bool $aetrayPath Whether to format the path for AeTrayMenu.
Returns
string The path to the PWGen directory.
Definition at line 434 of file class.core.php.
    {
        return $this->getLibsPath( $aetrayPath ) . '/pwgen';
    }
References getLibsPath().
Referenced by getPwgenExe().
getResourcesPath()
Core::getResourcesPath ($aetrayPath = false)
Retrieves the path to the resources.
Parameters
bool $aetrayPath Whether to format the path for AeTrayMenu.
Returns
string The path to the resources.
Definition at line 101 of file class.core.php.
    {
        global $bearsamppRoot;
        return $bearsamppRoot->getCorePath( $aetrayPath ) . '/resources';
    }
References $bearsamppRoot.
Referenced by getAppVersion(), getHomepagePath(), getLastPath(), and getLoadingPid().
getScript()
Core::getScript ($type)
Retrieves the path to a specific script.
Parameters
string $type The type of script.
Returns
string The path to the script.
Definition at line 153 of file class.core.php.
    {
        return $this->getScriptsPath() . '/' . $type;
    }
References getScriptsPath().
getScriptsPath()
Core::getScriptsPath ($aetrayPath = false)
Retrieves the path to the scripts.
Parameters
bool $aetrayPath Whether to format the path for AeTrayMenu.
Returns
string The path to the scripts.
Definition at line 129 of file class.core.php.
    {
        global $bearsamppRoot;
        return $bearsamppRoot->getCorePath( $aetrayPath ) . '/scripts';
    }
References $bearsamppRoot.
Referenced by getScript().
getSetEnvExe()
Core::getSetEnvExe ($aetrayPath = false)
Retrieves the path to the SetEnv executable.
Parameters
bool $aetrayPath Whether to format the path for AeTrayMenu.
Returns
string The path to the SetEnv executable.
Definition at line 314 of file class.core.php.
    {
        return $this->getSetEnvPath( $aetrayPath ) . '/' . self::SETENV_EXE;
    }
References getSetEnvPath(), and SETENV_EXE.
getSetEnvPath()
Core::getSetEnvPath ($aetrayPath = false)
Retrieves the path to the SetEnv directory.
Parameters
bool $aetrayPath Whether to format the path for AeTrayMenu.
Returns
string The path to the SetEnv directory.
Definition at line 302 of file class.core.php.
    {
        return $this->getLibsPath( $aetrayPath ) . '/setenv';
    }
References getLibsPath().
Referenced by getSetEnvExe().
getTmpPath()
Core::getTmpPath ($aetrayPath = false)
Retrieves the path to the temporary directory.
Parameters
bool $aetrayPath Whether to format the path for AeTrayMenu.
Returns
string The path to the temporary directory.
Definition at line 165 of file class.core.php.
    {
        global $bearsamppRoot;
        return $bearsamppRoot->getCorePath( $aetrayPath ) . '/tmp';
    }
References $bearsamppRoot.
Referenced by getExec().
setExec()
Core::setExec ($action)
Sets the content of the exec file.
Parameters
string $action The content to set in the exec file.
Definition at line 244 of file class.core.php.
    {
        file_put_contents( $this->getExec(), $action );
    }
References getExec().
unzipFile()
Core::unzipFile ($filePath, $destination, $progressCallback = null)
Unzips a file to the specified directory and provides progress updates.
This method uses the 7-Zip command-line tool to extract the contents of a zip file. It first tests the archive to determine the number of files to be extracted, then proceeds with the extraction while providing progress updates via a callback function.
Parameters
string $filePath The path to the zip file.
string $destination The directory to extract the files to.
callable | null $progressCallback A callback function to report progress. The callback receives two parameters:
int $currentFile: The current file number being extracted.
int $totalFiles: The total number of files to be extracted.
Returns
array An array containing the result of the extraction:
'success' => true and 'numFiles' => int on success.
'error' => string and 'numFiles' => int on failure.
Definition at line 478 of file class.core.php.
{
    global $bearsamppRoot;
    $sevenZipPath = $this->getLibsPath() . '/7zip/7za.exe';
    if (!file_exists($sevenZipPath)) {
        Util::logError('7za.exe not found at: ' . $sevenZipPath);
        return false;
    }
    // Command to test the archive and get the number of files
    $testCommand = escapeshellarg($sevenZipPath) . " t " . escapeshellarg($filePath) . " -y -bsp1";
    $testOutput = shell_exec($testCommand);
    // Extract the number of files from the test command output
    preg_match('/Files: (\d+)/', $testOutput, $matches);
    $numFiles = isset($matches[1]) ? (int)$matches[1] : 0;
    Util::logDebug('Number of files to be extracted: ' . $numFiles);
    // Command to extract the archive
    $command = escapeshellarg($sevenZipPath) . " x " . escapeshellarg($filePath) . " -y -bb1 -o" . escapeshellarg($destination);
    Util::logTrace('Executing command: ' . $command);
    $process = popen($command, 'r');
    if ($process) {
        $filesExtracted = 0;
        $buffer = '';
        while (!feof($process)) {
            $buffer .= fread($process, 262144); // Read in smaller chunks of 64KB
            while (($newlinePos = strpos($buffer, "\n")) !== false) {
                $line = substr($buffer, 0, $newlinePos + 1);
                $buffer = substr($buffer, $newlinePos + 1);
                if ($progressCallback && preg_match('/^- (.+)$/', $line, $matches)) {
                    $fileName = trim($matches[1]);
                    // Check if the extracted item is a file and not a directory
                    if (substr($fileName, -1) !== '\\') {
                        $filesExtracted++;
                        if ($filesExtracted <= $numFiles) {
                            call_user_func($progressCallback, $filesExtracted, $numFiles);
                        }
                    }
                }
            }
            // Clear the buffer periodically to release memory ( 128k chunks )
            if (strlen($buffer) > 524288) {
                $buffer = '';
            }
        }
        $returnVar = pclose($process);
        Util::logDebug('Command return value: ' . $returnVar);
        if ($returnVar === 0) {
            Util::logDebug('Successfully unzipped file to: ' . $destination);
            return ['success' => true, 'numFiles' => $numFiles];
        } else {
            Util::logError('Failed to unzip file. Command return value: ' . $returnVar);
            return ['error' => 'Failed to unzip file', 'numFiles' => $numFiles];
        }
    } else {
        Util::logError('Failed to open process for command: ' . $command);
        return ['error' => 'Failed to open process', 'numFiles' => $numFiles];
    }
}
References $bearsamppRoot, getLibsPath(), Util\logDebug(), Util\logError(), and Util\logTrace().
Field Documentation
APP_VERSION
const Core::APP_VERSION = 'version.dat'
Definition at line 47 of file class.core.php.
Referenced by getAppVersion().
EXEC
const Core::EXEC = 'exec.dat'
Definition at line 49 of file class.core.php.
Referenced by getExec().
HOSTSEDITOR_EXE
const Core::HOSTSEDITOR_EXE = 'hEdit_x64.exe'
Definition at line 39 of file class.core.php.
Referenced by getHostsEditorExe().
HOSTSEDITOR_VERSION
const Core::HOSTSEDITOR_VERSION = '1.3'
Definition at line 38 of file class.core.php.
isRoot_FILE
const Core::isRoot_FILE = 'root.php'
Definition at line 20 of file class.core.php.
Referenced by Batch\exitApp(), TplApp\getActionRun(), getisRootFilePath(), and Util\startLoading().
LAST_PATH
const Core::LAST_PATH = 'lastPath.dat'
Definition at line 48 of file class.core.php.
Referenced by getLastPath().
LN_EXE
const Core::LN_EXE = 'ln.exe'
Definition at line 42 of file class.core.php.
Referenced by getLnExe().
LN_VERSION
const Core::LN_VERSION = '2.928'
Definition at line 41 of file class.core.php.
LOADING_PID
const Core::LOADING_PID = 'loading.pid'
Definition at line 50 of file class.core.php.
Referenced by getLoadingPid().
NSSM_EXE
const Core::NSSM_EXE = 'nssm.exe'
Definition at line 32 of file class.core.php.
Referenced by getNssmExe().
NSSM_VERSION
const Core::NSSM_VERSION = '2.24'
Definition at line 31 of file class.core.php.
OPENSSL_CONF
const Core::OPENSSL_CONF = 'openssl.cfg'
Definition at line 36 of file class.core.php.
Referenced by getOpenSslConf().
OPENSSL_EXE
const Core::OPENSSL_EXE = 'openssl.exe'
Definition at line 35 of file class.core.php.
Referenced by getOpenSslExe().
OPENSSL_VERSION
const Core::OPENSSL_VERSION = '1.1.0c'
Definition at line 34 of file class.core.php.
PATH_LIN_PLACEHOLDER
const Core::PATH_LIN_PLACEHOLDER = '~BEARSAMPP_LIN_PATH~'
Definition at line 22 of file class.core.php.
Referenced by Util\changePath().
PATH_WIN_PLACEHOLDER
const Core::PATH_WIN_PLACEHOLDER = '~BEARSAMPP_WIN_PATH~'
Definition at line 21 of file class.core.php.
Referenced by Util\changePath().
PHP_CONF
const Core::PHP_CONF = 'php.ini'
Definition at line 26 of file class.core.php.
PHP_EXE
const Core::PHP_EXE = 'php-win.exe'
Definition at line 25 of file class.core.php.
Referenced by getPhpExe().
PHP_VERSION
const Core::PHP_VERSION = '5.4.23'
Definition at line 24 of file class.core.php.
PWGEN_EXE
const Core::PWGEN_EXE = "PWGenPortable.exe"
Definition at line 45 of file class.core.php.
Referenced by getPwgenExe().
PWGEN_VERSION
const Core::PWGEN_VERSION = '3.5.4'
Definition at line 44 of file class.core.php.
SCRIPT_EXEC_SILENT
const Core::SCRIPT_EXEC_SILENT = 'execSilent.vbs'
Definition at line 52 of file class.core.php.
Referenced by WinBinder\exec().
SETENV_EXE
const Core::SETENV_EXE = 'SetEnv.exe'
Definition at line 29 of file class.core.php.
Referenced by getSetEnvExe().
SETENV_VERSION
const Core::SETENV_VERSION = '1.09'
Definition at line 28 of file class.core.php.
The documentation for this class was generated from the following file:
E:/Bearsampp-development/sandbox/core/classes/class.core.php