My Project: TplAppGit Class Reference
TplAppGit Class Reference
Static Public Member Functions
static getActionRefreshGitRepos ()
static getActionRefreshGitReposStartup ($scanStartup)
static getMenuGit ()
static getMenuGitRepos ()
static process ()
Data Fields
const ACTION_REFRESH_REPOS = 'refreshGitRepos'
const ACTION_REFRESH_REPOS_STARTUP = 'refreshGitReposStartup'
const MENU = 'git'
const MENU_REPOS = 'gitRepos'
Detailed Description
Class TplAppGit
This class provides methods to generate and manage Git-related menu items and actions within the Bearsampp application. It includes functionalities for creating Git menus, refreshing repositories, and handling startup actions.
Definition at line 17 of file class.tpl.app.git.php.
Member Function Documentation
getActionRefreshGitRepos()
static TplAppGit::getActionRefreshGitRepos () static
Generates the action to refresh Git repositories.
This method creates the action string for refreshing Git repositories. It includes commands to reload the application after refreshing the repositories.
Returns
string The generated action string for refreshing Git repositories.
Definition at line 135 of file class.tpl.app.git.php.
    {
        return TplApp::getActionRun(Action::REFRESH_REPOS, array(ActionRefreshRepos::GIT)) . PHP_EOL .
            TplAppReload::getActionReload() . PHP_EOL;
    }
References TplAppReload\getActionReload(), TplApp\getActionRun(), ActionRefreshRepos\GIT, and Action\REFRESH_REPOS.
getActionRefreshGitReposStartup()
static TplAppGit::getActionRefreshGitReposStartup ($scanStartup) static
Generates the action to refresh Git repositories at startup.
This method creates the action string for setting up repository scanning at startup. It includes commands to reload the application after setting the startup action.
Parameters
int $scanStartup The flag indicating whether to enable or disable scanning at startup.
Returns
string The generated action string for refreshing Git repositories at startup.
Definition at line 151 of file class.tpl.app.git.php.
    {
        return TplApp::getActionRun(Action::REFRESH_REPOS_STARTUP, array(ActionRefreshRepos::GIT, $scanStartup)) . PHP_EOL .
            TplAppReload::getActionReload() . PHP_EOL;
    }
References TplAppReload\getActionReload(), TplApp\getActionRun(), ActionRefreshRepos\GIT, and Action\REFRESH_REPOS_STARTUP.
getMenuGit()
static TplAppGit::getMenuGit () static
Generates the Git menu with various options.
This method creates the Git menu with options for opening Git console, Git GUI, refreshing repositories, and setting up repository scanning at startup.
@global object $bearsamppLang Provides language support for retrieving language-specific values. @global object $bearsamppTools Provides access to various tools and utilities.
Returns
string The generated Git menu content.
Definition at line 54 of file class.tpl.app.git.php.
    {
        global $bearsamppLang, $bearsamppTools;
        $tplRepos = TplApp::getMenu($bearsamppLang->getValue(Lang::REPOS), self::MENU_REPOS, get_called_class());
        $emptyRepos = count(explode(PHP_EOL, $tplRepos[TplApp::SECTION_CONTENT])) == 2;
        $isScanStartup = $bearsamppTools->getGit()->isScanStartup();
        $tplRefreshRepos = TplApp::getActionMulti(
            self::ACTION_REFRESH_REPOS, null,
            array($bearsamppLang->getValue(Lang::MENU_REFRESH_REPOS), TplAestan::GLYPH_RELOAD),
            false, get_called_class()
        );
        $tplRefreshReposStartup = TplApp::getActionMulti(
            self::ACTION_REFRESH_REPOS_STARTUP, array($isScanStartup ? Config::DISABLED : Config::ENABLED),
            array($bearsamppLang->getValue(Lang::MENU_SCAN_REPOS_STARTUP), $isScanStartup ? TplAestan::GLYPH_CHECK : ''),
            false, get_called_class()
        );
        /* get path for git gui */
        $gitgui = $bearsamppTools->getGit()->getSymlinkPath() . '/cmd';
        return TplAestan::getItemConsoleZ(
                $bearsamppLang->getValue(Lang::GIT_CONSOLE),
                TplAestan::GLYPH_GIT,
                $bearsamppTools->getConsoleZ()->getTabTitleGit()
            ) . PHP_EOL .
            TplAestan::getItemExe(
                    $bearsamppLang->getValue(Lang::GITGUI),
                    $gitgui . '/git-gui',
                    TplAestan::GLYPH_GIT
                ) . PHP_EOL .
            TplAestan::getItemSeparator() . PHP_EOL .
            // Items
            (!$emptyRepos ? $tplRepos[TplApp::SECTION_CALL] . PHP_EOL : '') .
            $tplRefreshRepos[TplApp::SECTION_CALL] . PHP_EOL .
            $tplRefreshReposStartup[TplApp::SECTION_CALL] . PHP_EOL .
            // Actions
            (!$emptyRepos ? $tplRepos[TplApp::SECTION_CONTENT] . PHP_EOL : PHP_EOL) .
            $tplRefreshRepos[TplApp::SECTION_CONTENT] . PHP_EOL .
            $tplRefreshReposStartup[TplApp::SECTION_CONTENT];
    }
References $bearsamppLang, Config\DISABLED, Config\ENABLED, TplApp\getActionMulti(), TplAestan\getItemConsoleZ(), TplAestan\getItemExe(), TplAestan\getItemSeparator(), TplApp\getMenu(), Lang\GIT_CONSOLE, Lang\GITGUI, TplAestan\GLYPH_CHECK, TplAestan\GLYPH_GIT, TplAestan\GLYPH_RELOAD, Lang\MENU_REFRESH_REPOS, Lang\MENU_SCAN_REPOS_STARTUP, Lang\REPOS, TplApp\SECTION_CALL, and TplApp\SECTION_CONTENT.
getMenuGitRepos()
static TplAppGit::getMenuGitRepos () static
Generates the Git repositories menu.
This method creates the menu for listing and managing Git repositories found by the application.
@global object $bearsamppTools Provides access to various tools and utilities.
Returns
string The generated Git repositories menu content.
Definition at line 109 of file class.tpl.app.git.php.
    {
        global $bearsamppTools;
        $result = '';
        foreach ($bearsamppTools->getGit()->findRepos() as $repo) {
            $result .= TplAestan::getItemConsoleZ(
                basename($repo),
                TplAestan::GLYPH_GIT,
                $bearsamppTools->getConsoleZ()->getTabTitleGit(),
                $bearsamppTools->getConsoleZ()->getTabTitleGit($repo),
                $repo
            ) . PHP_EOL;
        }
        return $result;
    }
References $result, TplAestan\getItemConsoleZ(), and TplAestan\GLYPH_GIT.
process()
static TplAppGit::process () static
Processes and generates the main Git menu.
This method generates the main Git menu item, which includes options for managing Git repositories and actions related to Git functionalities.
@global object $bearsamppLang Provides language support for retrieving language-specific values.
Returns
array The generated Git menu item and actions.
Definition at line 36 of file class.tpl.app.git.php.
    {
        global $bearsamppLang;
        return TplApp::getMenu($bearsamppLang->getValue(Lang::GIT), self::MENU, get_called_class());
    }
References $bearsamppLang, TplApp\getMenu(), and Lang\GIT.
Referenced by TplAppTools\getMenuTools().
Field Documentation
ACTION_REFRESH_REPOS
const TplAppGit::ACTION_REFRESH_REPOS = 'refreshGitRepos'
Definition at line 23 of file class.tpl.app.git.php.
ACTION_REFRESH_REPOS_STARTUP
const TplAppGit::ACTION_REFRESH_REPOS_STARTUP = 'refreshGitReposStartup'
Definition at line 24 of file class.tpl.app.git.php.
MENU
const TplAppGit::MENU = 'git'
Definition at line 20 of file class.tpl.app.git.php.
MENU_REPOS
const TplAppGit::MENU_REPOS = 'gitRepos'
Definition at line 21 of file class.tpl.app.git.php.
The documentation for this class was generated from the following file:
E:/Bearsampp-development/sandbox/core/classes/tpls/app/class.tpl.app.git.php