My Project: BinXlight Class Reference
BinXlight Class Reference
Public Member Functions
__construct ($id, $type)
changePort ($port, $checkUsed=false, $wbProgressBar=null)
checkPort ($port, $showWindow=false)
getExe ()
getLog ()
getPort ()
getService ()
getUiPort ()
rebuildConf ()
reload ($id=null, $type=null)
setEnable ($enabled, $showWindow=false)
setPort ($port)
setSslPort ($SslPort)
setVersion ($version)
switchVersion ($version, $showWindow=false)
Public Member Functions inherited from Module
__toString ()
getCurrentPath ()
getId ()
getName ()
getRelease ()
getRootPath ()
getSymlinkPath ()
getType ()
getVersion ()
getVersionList ()
isEnable ()
update ($sub=0, $showWindow=false)
Data Fields
const LOCAL_CFG_EXE = 'xlightExe'
const LOCAL_CFG_PORT = 'xlightPort'
const LOCAL_CFG_SSL_PORT = 'xlightSslPort'
const ROOT_CFG_ENABLE = 'xlightEnable'
const ROOT_CFG_VERSION = 'xlightVersion'
const SERVICE_NAME = 'bearsamppxlight'
const SERVICE_PARAMS = ' -startall'
Data Fields inherited from Module
const BUNDLE_RELEASE = 'bundleRelease'
Protected Member Functions
replaceAll ($params)
updateConfig ($version=null, $sub=0, $showWindow=false)
Protected Member Functions inherited from Module
__construct ()
replace ($key, $value)
Private Attributes
$exe
$log
$port
$service
$SslPort
Additional Inherited Members
Protected Attributes inherited from Module
$bearsamppConf
$bearsamppConfRaw
$currentPath
$enable
$name
$release = 'N/A'
$rootPath
$symlinkPath
$version
Detailed Description
Class BinXlight
This class represents the Xlight FTP server module in the Bearsampp application. It handles the configuration, initialization, and management of the Xlight FTP server.
Definition at line 16 of file class.bin.xlight.php.
Constructor & Destructor Documentation
__construct()
BinXlight::__construct ($id, $type)
Constructs a BinXlight object and initializes the module.
Parameters
string $id The ID of the module.
string $type The type of the module.
Definition at line 41 of file class.bin.xlight.php.
{
        Util::logInitClass($this);
        $this->reload($id, $type);
    }
References Module\$id, Module\$type, Util\logInitClass(), and reload().
Member Function Documentation
changePort()
BinXlight::changePort ($port, $checkUsed = false, $wbProgressBar = null)
Changes the port used by the Xlight FTP server.
Parameters
int $port The new port number.
bool $checkUsed Whether to check if the port is already in use.
mixed | null $wbProgressBar The progress bar object for UI updates (optional).
Returns
bool|int True if the port was successfully changed, false if invalid, or the process using the port.
Definition at line 167 of file class.bin.xlight.php.
{
        global $bearsamppWinbinder;
        if (!Util::isValidPort($port)) {
            Util::logError($this->getName() . ' port not valid: ' . $port);
            return false;
        }
        $port = intval($port);
        $bearsamppWinbinder->incrProgressBar($wbProgressBar);
        $isPortInUse = Util::isPortInUse($port);
        if (!$checkUsed || $isPortInUse === false) {
            // bearsampp.conf
            $this->setSmtpPort($port);
            $bearsamppWinbinder->incrProgressBar($wbProgressBar);
            // conf
            $this->update();
            $bearsamppWinbinder->incrProgressBar($wbProgressBar);
            return true;
        }
        Util::logDebug($this->getName() . ' port in used: ' . $port . ' - ' . $isPortInUse);
        return $isPortInUse;
    }
References $port, Module\getName(), Util\isPortInUse(), Util\isValidPort(), Util\logDebug(), Util\logError(), and Module\update().
checkPort()
BinXlight::checkPort ($port, $showWindow = false)
Checks if a port is used by the Xlight FTP server.
Parameters
int $port The port number to check.
bool $showWindow Whether to show a message box with the result.
Returns
bool True if the port is used by Xlight, false otherwise.
Definition at line 202 of file class.bin.xlight.php.
{
        global $bearsamppLang, $bearsamppWinbinder;
        $boxTitle = sprintf($bearsamppLang->getValue(Lang::CHECK_PORT_TITLE), $this->getName(), $port);
        if (!Util::isValidPort($port)) {
            Util::logError($this->getName() . ' port not valid: ' . $port);
            return false;
        }
        $headers = Util::getHeaders('127.0.0.1', $port);
        if (!empty($headers)) {
            if (Util::contains($headers[0], 'Xlight')) {
                Util::logDebug($this->getName() . ' port ' . $port . ' is used by: ' . str_replace('220 ', '', $headers[0]));
                if ($showWindow) {
                    $bearsamppWinbinder->messageBoxInfo(
                        sprintf($bearsamppLang->getValue(Lang::PORT_USED_BY), $port, str_replace('220 ', '', $headers[0])),
                        $boxTitle
                    );
                }
                return true;
            }
            Util::logDebug($this->getName() . ' port ' . $port . ' is used by another application');
            if ($showWindow) {
                $bearsamppWinbinder->messageBoxWarning(
                    sprintf($bearsamppLang->getValue(Lang::PORT_NOT_USED_BY), $port),
                    $boxTitle
                );
            }
        } else {
            Util::logDebug($this->getName() . ' port ' . $port . ' is not used');
            if ($showWindow) {
                $bearsamppWinbinder->messageBoxError(
                    sprintf($bearsamppLang->getValue(Lang::PORT_NOT_USED), $port),
                    $boxTitle
                );
            }
        }
        return false;
    }
References $bearsamppLang, $port, Lang\CHECK_PORT_TITLE, Util\contains(), Util\getHeaders(), Module\getName(), Util\isValidPort(), Util\logDebug(), Util\logError(), Lang\PORT_NOT_USED, Lang\PORT_NOT_USED_BY, and Lang\PORT_USED_BY.
getExe()
BinXlight::getExe ()
Gets the executable file path for the Xlight FTP server.
Returns
string The executable file path.
Definition at line 372 of file class.bin.xlight.php.
{
        return $this->exe;
    }
References $exe.
getLog()
BinXlight::getLog ()
Gets the log file path for the Xlight FTP server.
Returns
string The log file path.
Definition at line 363 of file class.bin.xlight.php.
{
        return $this->log;
    }
References $log.
getPort()
BinXlight::getPort ()
Gets the port used by the Xlight FTP server.
Returns
int The port number.
Definition at line 399 of file class.bin.xlight.php.
{
        return $this->port;
    }
References $port.
getService()
BinXlight::getService ()
Gets the service object for the Xlight FTP server.
Returns
Win32Service The service object.
Definition at line 322 of file class.bin.xlight.php.
{
        return $this->service;
    }
References $service.
getUiPort()
BinXlight::getUiPort ()
Gets the SSL port used by the Xlight FTP server.
Returns
int The SSL port number.
Definition at line 381 of file class.bin.xlight.php.
{
        return $this->SslPort;
    }
References $SslPort.
rebuildConf()
BinXlight::rebuildConf ()
Rebuilds the configuration in the Windows Registry.
Returns
bool True if the configuration was successfully rebuilt, false otherwise.
Definition at line 139 of file class.bin.xlight.php.
{
        global $bearsamppRegistry;
        $exists = $bearsamppRegistry->exists(
            Registry::HKEY_LOCAL_MACHINE,
            'SYSTEM\CurrentControlSet\Services\\' . self::SERVICE_NAME . '\Parameters',
            Nssm::INFO_APP_PARAMETERS
        );
        if ($exists) {
            return $bearsamppRegistry->setExpandStringValue(
                Registry::HKEY_LOCAL_MACHINE,
                'SYSTEM\CurrentControlSet\Services\\' . self::SERVICE_NAME . '\Parameters',
                Nssm::INFO_APP_PARAMETERS,
                sprintf(self::SERVICE_PARAMS, $this->SslPort, $this->port)
            );
        }
        return false;
    }
References Registry\HKEY_LOCAL_MACHINE, and Nssm\INFO_APP_PARAMETERS.
reload()
BinXlight::reload ($id = null, $type = null)
Reloads the module configuration based on the provided ID and type.
Parameters
string | null $id The ID of the module. If null, the current ID is used.
string | null $type The type of the module. If null, the current type is used.
Reimplemented from Module.
Definition at line 52 of file class.bin.xlight.php.
{
        global $bearsamppRoot, $bearsamppConfig, $bearsamppLang;
        Util::logReloadClass($this);
        $this->name = $bearsamppLang->getValue(Lang::XLIGHT);
        $this->version = $bearsamppConfig->getRaw(self::ROOT_CFG_VERSION);
        parent::reload($id, $type);
        $this->enable = $this->enable && $bearsamppConfig->getRaw(self::ROOT_CFG_ENABLE);
        $this->service = new Win32Service(self::SERVICE_NAME);
        $this->log = $bearsamppRoot->getLogsPath() . '/xlight.log';
        if ($this->bearsamppConfRaw !== false) {
            $this->exe = $this->symlinkPath . '/' . $this->bearsamppConfRaw[self::LOCAL_CFG_EXE];
            $this->SslPort = intval($this->bearsamppConfRaw[self::LOCAL_CFG_SSL_PORT]);
            $this->port = intval($this->bearsamppConfRaw[self::LOCAL_CFG_PORT]);
        }
        if (!$this->enable) {
            Util::logInfo($this->name . ' is not enabled!');
            return;
        }
        if (!is_dir($this->currentPath)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_FILE_NOT_FOUND), $this->name . ' ' . $this->version, $this->currentPath));
            return;
        }
        if (!is_dir($this->symlinkPath)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_FILE_NOT_FOUND), $this->name . ' ' . $this->version, $this->symlinkPath));
            return;
        }
        if (!is_file($this->bearsamppConf)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_CONF_NOT_FOUND), $this->name . ' ' . $this->version, $this->bearsamppConf));
            return;
        }
        if (!is_file($this->exe)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_EXE_NOT_FOUND), $this->name . ' ' . $this->version, $this->exe));
            return;
        }
        if (empty($this->SslPort)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_INVALID_PARAMETER), self::LOCAL_CFG_SSL_PORT, $this->SslPort));
            return;
        }
        if (empty($this->port)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_INVALID_PARAMETER), self::LOCAL_CFG_PORT, $this->port));
            return;
        }
        $nssm = new Nssm(self::SERVICE_NAME);
        $nssm->setDisplayName(APP_TITLE . ' ' . $this->getName());
        $nssm->setBinPath($this->exe);
        $nssm->setParams(sprintf(self::SERVICE_PARAMS, $this->SslPort, $this->port));
        $nssm->setStart(Nssm::SERVICE_DEMAND_START);
        $nssm->setStdout($bearsamppRoot->getLogsPath() . '/xlight.log');
        $nssm->setStderr($bearsamppRoot->getLogsPath() . '/xlight.error.log');
        $this->service->setNssm($nssm);
    }
References $bearsamppConfig, $bearsamppLang, $bearsamppRoot, Module\$id, Module\$type, APP_TITLE, Lang\ERROR_CONF_NOT_FOUND, Lang\ERROR_EXE_NOT_FOUND, Lang\ERROR_FILE_NOT_FOUND, Lang\ERROR_INVALID_PARAMETER, Module\getName(), LOCAL_CFG_EXE, Util\logError(), Util\logInfo(), Util\logReloadClass(), Nssm\SERVICE_DEMAND_START, and Lang\XLIGHT.
Referenced by __construct(), setEnable(), and setVersion().
replaceAll()
BinXlight::replaceAll ($params) protected
Replaces multiple key-value pairs in the configuration file.
Parameters
array $params An associative array of key-value pairs to replace.
Reimplemented from Module.
Definition at line 115 of file class.bin.xlight.php.
{
        $content = file_get_contents($this->bearsamppConf);
        foreach ($params as $key => $value) {
            $content = preg_replace('|' . $key . ' = .*|', $key . ' = ' . '"' . $value.'"', $content);
            $this->bearsamppConfRaw[$key] = $value;
            switch ($key) {
                case self::LOCAL_CFG_SSL_PORT:
                    $this->SslPort = intval($value);
                    break;
                case self::LOCAL_CFG_PORT:
                    $this->port = intval($value);
                    break;
            }
        }
        file_put_contents($this->bearsamppConf, $content);
    }
References LOCAL_CFG_PORT, and LOCAL_CFG_SSL_PORT.
setEnable()
BinXlight::setEnable ($enabled, $showWindow = false)
Enables or disables the Xlight FTP server.
Parameters
bool $enabled Whether to enable or disable the server.
bool $showWindow Whether to show a message box with the result.
Definition at line 332 of file class.bin.xlight.php.
{
        global $bearsamppConfig, $bearsamppLang, $bearsamppWinbinder;
        if ($enabled == Config::ENABLED && !is_dir($this->currentPath)) {
            Util::logDebug($this->getName() . ' cannot be enabled because bundle ' . $this->getVersion() . ' does not exist in ' . $this->currentPath);
            if ($showWindow) {
                $bearsamppWinbinder->messageBoxError(
                    sprintf($bearsamppLang->getValue(Lang::ENABLE_BUNDLE_NOT_EXIST), $this->getName(), $this->getVersion(), $this->currentPath),
                    sprintf($bearsamppLang->getValue(Lang::ENABLE_TITLE), $this->getName())
                );
            }
            $enabled = Config::DISABLED;
        }
        Util::logInfo($this->getName() . ' switched to ' . ($enabled == Config::ENABLED ? 'enabled' : 'disabled'));
        $this->enable = $enabled == Config::ENABLED;
        $bearsamppConfig->replace(self::ROOT_CFG_ENABLE, $enabled);
        $this->reload();
        if ($this->enable) {
            Util::installService($this, $this->port, null, $showWindow);
        } else {
            Util::removeService($this->service, $this->name);
        }
    }
References $bearsamppConfig, $bearsamppLang, Config\DISABLED, Lang\ENABLE_BUNDLE_NOT_EXIST, Lang\ENABLE_TITLE, Config\ENABLED, Module\getName(), Module\getVersion(), Util\installService(), Util\logDebug(), Util\logInfo(), reload(), and Util\removeService().
setPort()
BinXlight::setPort ($port)
Sets the port for the Xlight FTP server.
Parameters
int $port The port number.
Definition at line 408 of file class.bin.xlight.php.
{
        $this->replace(self::LOCAL_CFG_PORT, $port);
    }
References $port, and Module\replace().
setSslPort()
BinXlight::setSslPort ($SslPort)
Sets the SSL port for the Xlight FTP server.
Parameters
int $SslPort The SSL port number.
Definition at line 390 of file class.bin.xlight.php.
{
        $this->replace(self::LOCAL_CFG_SSL_PORT, $SslPort);
    }
References $SslPort, and Module\replace().
setVersion()
BinXlight::setVersion ($version)
Sets the version of the Xlight FTP server.
Parameters
string $version The version to set.
Reimplemented from Module.
Definition at line 310 of file class.bin.xlight.php.
{
        global $bearsamppConfig;
        $this->version = $version;
        $bearsamppConfig->replace(self::ROOT_CFG_VERSION, $version);
        $this->reload();
    }
References $bearsamppConfig, Module\$version, and reload().
Referenced by updateConfig().
switchVersion()
BinXlight::switchVersion ($version, $showWindow = false)
Switches the version of the Xlight FTP server.
Parameters
string $version The version to switch to.
bool $showWindow Whether to show a message box with the result.
Returns
bool True if the version was successfully switched, false otherwise.
Definition at line 250 of file class.bin.xlight.php.
{
        Util::logDebug('Switch ' . $this->name . ' version to ' . $version);
        return $this->updateConfig($version, 0, $showWindow);
    }
References Module\$version, Util\logDebug(), and updateConfig().
updateConfig()
BinXlight::updateConfig ($version = null, $sub = 0, $showWindow = false) protected
Updates the configuration of the Xlight FTP server.
Parameters
string | null $version The version to update to. If null, the current version is used.
int $sub The sub-level for logging indentation.
bool $showWindow Whether to show a message box with the result.
Returns
bool True if the configuration was successfully updated, false otherwise.
Reimplemented from Module.
Definition at line 263 of file class.bin.xlight.php.
{
        global $bearsamppLang, $bearsamppWinbinder;
        if (!$this->enable) {
            return true;
        }
        $version = $version == null ? $this->version : $version;
        Util::logDebug(($sub > 0 ? str_repeat(' ', 2 * $sub) : '') . 'Update ' . $this->name . ' ' . $version . ' config');
        $boxTitle = sprintf($bearsamppLang->getValue(Lang::SWITCH_VERSION_TITLE), $this->getName(), $version);
        $bearsamppConf = str_replace('xlight' . $this->getVersion(), 'xlight' . $version, $this->bearsamppConf);
        if (!file_exists($bearsamppConf)) {
            Util::logError('bearsampp config files not found for ' . $this->getName() . ' ' . $version);
            if ($showWindow) {
                $bearsamppWinbinder->messageBoxError(
                    sprintf($bearsamppLang->getValue(Lang::BEARSAMPP_CONF_NOT_FOUND_ERROR), $this->getName() . ' ' . $version),
                    $boxTitle
                );
            }
            return false;
        }
        $bearsamppConfRaw = parse_ini_file($bearsamppConf);
        if ($bearsamppConfRaw === false || !isset($bearsamppConfRaw[self::ROOT_CFG_VERSION]) || $bearsamppConfRaw[self::ROOT_CFG_VERSION] != $version) {
            Util::logError('bearsampp config file malformed for ' . $this->getName() . ' ' . $version);
            if ($showWindow) {
                $bearsamppWinbinder->messageBoxError(
                    sprintf($bearsamppLang->getValue(Lang::BEARSAMPP_CONF_MALFORMED_ERROR), $this->getName() . ' ' . $version),
                    $boxTitle
                );
            }
            return false;
        }
        // bearsampp.conf
        $this->setVersion($version);
        return true;
    }
References Module\$bearsamppConf, Module\$bearsamppConfRaw, $bearsamppLang, Module\$version, Lang\BEARSAMPP_CONF_MALFORMED_ERROR, Lang\BEARSAMPP_CONF_NOT_FOUND_ERROR, Module\getName(), Module\getVersion(), Util\logDebug(), Util\logError(), setVersion(), and Lang\SWITCH_VERSION_TITLE.
Referenced by switchVersion().
Field Documentation
$exe
BinXlight::$exe private
Definition at line 31 of file class.bin.xlight.php.
Referenced by getExe().
$log
BinXlight::$log private
Definition at line 29 of file class.bin.xlight.php.
Referenced by getLog().
$port
BinXlight::$port private
Definition at line 32 of file class.bin.xlight.php.
Referenced by changePort(), checkPort(), getPort(), and setPort().
$service
BinXlight::$service private
Definition at line 28 of file class.bin.xlight.php.
Referenced by getService().
$SslPort
BinXlight::$SslPort private
Definition at line 33 of file class.bin.xlight.php.
Referenced by getUiPort(), and setSslPort().
LOCAL_CFG_EXE
const BinXlight::LOCAL_CFG_EXE = 'xlightExe'
Definition at line 24 of file class.bin.xlight.php.
Referenced by reload().
LOCAL_CFG_PORT
const BinXlight::LOCAL_CFG_PORT = 'xlightPort'
Definition at line 26 of file class.bin.xlight.php.
Referenced by replaceAll().
LOCAL_CFG_SSL_PORT
const BinXlight::LOCAL_CFG_SSL_PORT = 'xlightSslPort'
Definition at line 25 of file class.bin.xlight.php.
Referenced by replaceAll().
ROOT_CFG_ENABLE
const BinXlight::ROOT_CFG_ENABLE = 'xlightEnable'
Definition at line 21 of file class.bin.xlight.php.
ROOT_CFG_VERSION
const BinXlight::ROOT_CFG_VERSION = 'xlightVersion'
Definition at line 22 of file class.bin.xlight.php.
SERVICE_NAME
const BinXlight::SERVICE_NAME = 'bearsamppxlight'
Definition at line 18 of file class.bin.xlight.php.
Referenced by ActionService\__construct(), TplAppXlight\getActionInstallXlightService(), TplAppXlight\getActionRemoveXlightService(), Bins\getServices(), ActionStartup\installServices(), ActionQuit\processWindow(), and Win32Service\start().
SERVICE_PARAMS
const BinXlight::SERVICE_PARAMS = ' -startall'
Definition at line 19 of file class.bin.xlight.php.
The documentation for this class was generated from the following file:
E:/Bearsampp-development/sandbox/core/classes/bins/class.bin.xlight.php