Bearsampp: BinFilezilla Class Reference
BinFilezilla Class Reference
Public Member Functions
__construct ($id, $type)
changePort ($port, $checkUsed=false, $wbProgressBar=null)
checkPort ($port, $ssl=false, $showWindow=false)
getConf ()
getExe ()
getItfConf ()
getItfExe ()
getLog ()
getLogsPath ()
getPort ()
getService ()
getSslPort ()
rebuildConf ()
reload ($id=null, $type=null)
setConf ($elts)
setEnable ($enabled, $showWindow=false)
setPort ($port)
setSslPort ($sslPort)
setVersion ($version)
switchVersion ($version, $showWindow=false)
Public Member Functions inherited from Module
__toString ()
getCurrentPath ()
getId ()
getName ()
getRelease ()
getRootPath ()
getSymlinkPath ()
getType ()
getVersion ()
getVersionList ()
isEnable ()
update ($sub=0, $showWindow=false)
Data Fields
const CFG_IP_FILTER_ALLOWED = 39
const CFG_IP_FILTER_DISALLOWED = 40
const CFG_SERVER_PORT = 0
const CFG_SERVICE_DISPLAY_NAME = 59
const CFG_SERVICE_NAME = 58
const CFG_WELCOME_MSG = 15
const LOCAL_CFG_CONF = 'filezillaConf'
const LOCAL_CFG_EXE = 'filezillaExe'
const LOCAL_CFG_ITF_CONF = 'filezillaItfConf'
const LOCAL_CFG_ITF_EXE = 'filezillaItfExe'
const LOCAL_CFG_PORT = 'filezillaPort'
const LOCAL_CFG_SSL_PORT = 'filezillaSslPort'
const ROOT_CFG_ENABLE = 'filezillaEnable'
const ROOT_CFG_VERSION = 'filezillaVersion'
const SERVICE_NAME = 'bearsamppfilezilla'
Data Fields inherited from Module
const BUNDLE_RELEASE = 'bundleRelease'
Protected Member Functions
replaceAll ($params)
updateConfig ($version=null, $sub=0, $showWindow=false)
Protected Member Functions inherited from Module
__construct ()
replace ($key, $value)
Private Attributes
$conf
$exe
$itfConf
$itfExe
$localItfConf
$log
$logsPath
$port
$service
$sslPort
Additional Inherited Members
Protected Attributes inherited from Module
$bearsamppConf
$bearsamppConfRaw
$currentPath
$enable
$name
$release = 'N/A'
$rootPath
$symlinkPath
$version
Detailed Description
Class BinFilezilla
This class represents the FileZilla module in the Bearsampp application. It handles the configuration, management, and operations related to the FileZilla service.
Definition at line 16 of file class.bin.filezilla.php.
Constructor & Destructor Documentation
__construct()
BinFilezilla::__construct ($id, $type)
Constructs a BinFilezilla object and initializes the module.
Parameters
string $id The ID of the module.
string $type The type of the module.
Definition at line 55 of file class.bin.filezilla.php.
    {
        Util::logInitClass( $this );
        $this->reload( $id, $type );
    }
References Module\$id, Module\$type, Util\logInitClass(), and reload().
Member Function Documentation
changePort()
BinFilezilla::changePort ($port, $checkUsed = false, $wbProgressBar = null)
Changes the port for the FileZilla service.
Parameters
int $port The new port number.
bool $checkUsed Whether to check if the port is already in use.
mixed $wbProgressBar The progress bar object for displaying progress.
Returns
bool|string Returns true if the port is changed successfully, false if the port is invalid, or a string if the port is in use.
Definition at line 162 of file class.bin.filezilla.php.
    {
        global $bearsamppWinbinder;
        if ( !Util::isValidPort( $port ) ) {
            Util::logError( $this->getName() . ' port not valid: ' . $port );
            return false;
        }
        $port = intval( $port );
        $bearsamppWinbinder->incrProgressBar( $wbProgressBar );
        $isPortInUse = Util::isPortInUse( $port );
        if ( !$checkUsed || $isPortInUse === false ) {
            // bearsampp.conf
            $this->setPort( $port );
            $bearsamppWinbinder->incrProgressBar( $wbProgressBar );
            // conf
            $this->update();
            $bearsamppWinbinder->incrProgressBar( $wbProgressBar );
            return true;
        }
        Util::logDebug( $this->getName() . ' port in used: ' . $port . ' - ' . $isPortInUse );
        return $isPortInUse;
    }
References $port, Module\getName(), Util\isPortInUse(), Util\isValidPort(), Util\logDebug(), Util\logError(), setPort(), and Module\update().
checkPort()
BinFilezilla::checkPort ($port, $ssl = false, $showWindow = false)
Checks if the specified port is in use.
Parameters
int $port The port number to check.
bool $ssl Whether to use SSL for the check.
bool $showWindow Whether to show a window with the result.
Returns
bool Returns true if the port is in use, false otherwise.
Definition at line 202 of file class.bin.filezilla.php.
    {
        global $bearsamppLang, $bearsamppWinbinder;
        $boxTitle = sprintf( $bearsamppLang->getValue( Lang::CHECK_PORT_TITLE ), $this->getName(), $port );
        if ( !Util::isValidPort( $port ) ) {
            Util::logError( $this->getName() . ' port not valid: ' . $port );
            return false;
        }
        $headers = Util::getHeaders( '127.0.0.1', $port, $ssl );
        if ( !empty( $headers ) ) {
            if ( $headers[0] == '220 ' . $this->getService()->getDisplayName() ) {
                Util::logDebug( $this->getName() . ' port ' . $port . ' is used by: ' . str_replace( '220 ', '', $headers[0] ) );
                if ( $showWindow ) {
                    $bearsamppWinbinder->messageBoxInfo(
                        sprintf( $bearsamppLang->getValue( Lang::PORT_USED_BY ), $port, str_replace( '220 ', '', $headers[0] ) ),
                        $boxTitle
                    );
                }
                return true;
            }
            Util::logDebug( $this->getName() . ' port ' . $port . ' is used by another application' );
            if ( $showWindow ) {
                $bearsamppWinbinder->messageBoxWarning(
                    sprintf( $bearsamppLang->getValue( Lang::PORT_NOT_USED_BY ), $port ),
                    $boxTitle
                );
            }
        }
        else {
            Util::logDebug( $this->getName() . ' port ' . $port . ' is not used' );
            if ( $showWindow ) {
                $bearsamppWinbinder->messageBoxError(
                    sprintf( $bearsamppLang->getValue( Lang::PORT_NOT_USED ), $port ),
                    $boxTitle
                );
            }
        }
        return false;
    }
References $bearsamppLang, $port, Lang\CHECK_PORT_TITLE, Util\getHeaders(), Module\getName(), getService(), Util\isValidPort(), Util\logDebug(), Util\logError(), Lang\PORT_NOT_USED, Lang\PORT_NOT_USED_BY, and Lang\PORT_USED_BY.
getConf()
BinFilezilla::getConf ()
Retrieves the configuration file path for the FileZilla module.
Returns
string The configuration file path.
Definition at line 336 of file class.bin.filezilla.php.
    {
        return $this->conf;
    }
References $conf.
Referenced by updateConfig().
getExe()
BinFilezilla::getExe ()
Retrieves the executable file path for the FileZilla module.
Returns
string The executable file path.
Definition at line 448 of file class.bin.filezilla.php.
    {
        return $this->exe;
    }
References $exe.
getItfConf()
BinFilezilla::getItfConf ()
Retrieves the interface configuration file path for the FileZilla module.
Returns
string The interface configuration file path.
Definition at line 468 of file class.bin.filezilla.php.
    {
        return $this->itfConf;
    }
References $itfConf.
getItfExe()
BinFilezilla::getItfExe ()
Retrieves the interface executable file path for the FileZilla module.
Returns
string The interface executable file path.
Definition at line 458 of file class.bin.filezilla.php.
    {
        return $this->itfExe;
    }
References $itfExe.
getLog()
BinFilezilla::getLog ()
Retrieves the log file path for the FileZilla module.
Returns
string The log file path.
Definition at line 438 of file class.bin.filezilla.php.
    {
        return $this->log;
    }
References $log.
getLogsPath()
BinFilezilla::getLogsPath ()
Retrieves the logs path for the FileZilla module.
Returns
string The logs path.
Definition at line 428 of file class.bin.filezilla.php.
    {
        return $this->logsPath;
    }
References $logsPath.
getPort()
BinFilezilla::getPort ()
Retrieves the port number for the FileZilla service.
Returns
int The port number.
Definition at line 478 of file class.bin.filezilla.php.
    {
        return $this->port;
    }
References $port.
getService()
BinFilezilla::getService ()
Retrieves the Win32Service object for the FileZilla service.
Returns
Win32Service The Win32Service object.
Definition at line 252 of file class.bin.filezilla.php.
    {
        return $this->service;
    }
References $service.
Referenced by checkPort().
getSslPort()
BinFilezilla::getSslPort ()
Retrieves the SSL port number for the FileZilla service.
Returns
int The SSL port number.
Definition at line 498 of file class.bin.filezilla.php.
    {
        return $this->sslPort;
    }
References $sslPort.
rebuildConf()
BinFilezilla::rebuildConf ()
Rebuilds the configuration file for the FileZilla module.
Definition at line 375 of file class.bin.filezilla.php.
    {
        if ( !$this->enable ) {
            return;
        }
        $this->setConf( array(
                            self::CFG_SERVER_PORT          => $this->port,
                            self::CFG_SERVICE_NAME         => $this->service->getName(),
                            self::CFG_WELCOME_MSG          => $this->service->getDisplayName(),
                            self::CFG_SERVICE_DISPLAY_NAME => $this->service->getDisplayName()
                        ) );
    }
References setConf().
Referenced by updateConfig().
reload()
BinFilezilla::reload ($id = null, $type = null)
Reloads the module configuration based on the provided ID and type.
Parameters
string | null $id The ID of the module. If null, the current ID is used.
string | null $type The type of the module. If null, the current type is used.
Reimplemented from Module.
Definition at line 67 of file class.bin.filezilla.php.
    {
        global $bearsamppRoot, $bearsamppConfig, $bearsamppLang;
        Util::logReloadClass( $this );
        $this->name    = $bearsamppLang->getValue( Lang::FILEZILLA );
        $this->version = $bearsamppConfig->getRaw( self::ROOT_CFG_VERSION );
        parent::reload( $id, $type );
        $this->enable   = $this->enable && $bearsamppConfig->getRaw( self::ROOT_CFG_ENABLE );
        $this->service  = new Win32Service( self::SERVICE_NAME );
        $this->logsPath = $this->symlinkPath . '/Logs';
        $this->log      = $bearsamppRoot->getLogsPath() . '/filezilla.log';
        if ( $this->bearsamppConfRaw !== false ) {
            $this->exe          = $this->symlinkPath . '/' . $this->bearsamppConfRaw[self::LOCAL_CFG_EXE];
            $this->itfExe       = $this->symlinkPath . '/' . $this->bearsamppConfRaw[self::LOCAL_CFG_ITF_EXE];
            $this->conf         = $this->symlinkPath . '/' . $this->bearsamppConfRaw[self::LOCAL_CFG_CONF];
            $this->itfConf      = $this->symlinkPath . '/' . $this->bearsamppConfRaw[self::LOCAL_CFG_ITF_CONF];
            $this->localItfConf = Util::formatUnixPath( getenv( 'APPDATA' ) ) . '/FileZilla Server/' . $this->bearsamppConfRaw[self::LOCAL_CFG_ITF_CONF];
            $this->port         = $this->bearsamppConfRaw[self::LOCAL_CFG_PORT];
            $this->sslPort      = $this->bearsamppConfRaw[self::LOCAL_CFG_SSL_PORT];
        }
        if ( !$this->enable ) {
            Util::logInfo( $this->name . ' is not enabled!' );
            return;
        }
        if ( !is_dir( $this->currentPath ) ) {
            Util::logError( sprintf( $bearsamppLang->getValue( Lang::ERROR_FILE_NOT_FOUND ), $this->name . ' ' . $this->version, $this->currentPath ) );
            return;
        }
        if ( !is_dir( $this->symlinkPath ) ) {
            Util::logError( sprintf( $bearsamppLang->getValue( Lang::ERROR_FILE_NOT_FOUND ), $this->name . ' ' . $this->version, $this->symlinkPath ) );
            return;
        }
        if ( !is_file( $this->bearsamppConf ) ) {
            Util::logError( sprintf( $bearsamppLang->getValue( Lang::ERROR_CONF_NOT_FOUND ), $this->name . ' ' . $this->version, $this->bearsamppConf ) );
            return;
        }
        // Create log hard link
        $log = $this->logsPath . '/FileZilla Server.log';
        if ( !file_exists( $this->log ) && file_exists( $log ) ) {
            @link( $log, $this->log );
        }
        if ( !is_file( $this->exe ) ) {
            Util::logError( sprintf( $bearsamppLang->getValue( Lang::ERROR_EXE_NOT_FOUND ), $this->name . ' ' . $this->version, $this->exe ) );
            return;
        }
        if ( !is_file( $this->conf ) ) {
            Util::logError( sprintf( $bearsamppLang->getValue( Lang::ERROR_CONF_NOT_FOUND ), $this->name . ' ' . $this->version, $this->conf ) );
            return;
        }
        if ( !is_numeric( $this->port ) || $this->port <= 0 ) {
            Util::logError( sprintf( $bearsamppLang->getValue( Lang::ERROR_INVALID_PARAMETER ), self::LOCAL_CFG_PORT, $this->port ) );
            return;
        }
        if ( !is_numeric( $this->sslPort ) || $this->sslPort <= 0 ) {
            Util::logError( sprintf( $bearsamppLang->getValue( Lang::ERROR_INVALID_PARAMETER ), self::LOCAL_CFG_SSL_PORT, $this->sslPort ) );
            return;
        }
        if ( !file_exists( $this->localItfConf ) ) {
            if ( !is_dir( dirname( $this->localItfConf ) ) ) {
                Util::logDebug( 'Create folder ' . dirname( $this->localItfConf ) );
                @mkdir( dirname( $this->localItfConf ), 0777 );
            }
            Util::logDebug( 'Write ' . $this->bearsamppConfRaw[self::LOCAL_CFG_ITF_CONF] . ' to ' . $this->localItfConf );
            @copy( $this->itfConf, $this->localItfConf );
        }
        $this->service->setDisplayName( APP_TITLE . ' ' . $this->getName() );
        $this->service->setBinPath( $this->exe );
        $this->service->setStartType( Win32Service::SERVICE_DEMAND_START );
        $this->service->setErrorControl( Win32Service::SERVER_ERROR_NORMAL );
    }
References $bearsamppConfig, $bearsamppLang, $bearsamppRoot, Module\$id, $log, Module\$type, APP_TITLE, Lang\ERROR_CONF_NOT_FOUND, Lang\ERROR_EXE_NOT_FOUND, Lang\ERROR_FILE_NOT_FOUND, Lang\ERROR_INVALID_PARAMETER, Lang\FILEZILLA, Util\formatUnixPath(), Module\getName(), LOCAL_CFG_CONF, LOCAL_CFG_EXE, LOCAL_CFG_ITF_CONF, LOCAL_CFG_ITF_EXE, LOCAL_CFG_PORT, LOCAL_CFG_SSL_PORT, Util\logDebug(), Util\logError(), Util\logInfo(), Util\logReloadClass(), Win32Service\SERVER_ERROR_NORMAL, and Win32Service\SERVICE_DEMAND_START.
Referenced by __construct(), setEnable(), and setVersion().
replaceAll()
BinFilezilla::replaceAll ($params) protected
Replaces multiple key-value pairs in the configuration file.
This method reads the current configuration file, replaces the specified key-value pairs, and updates the internal configuration state. It also updates the port and SSL port properties if they are included in the key-value pairs.
Parameters
array $params An associative array of key-value pairs to replace in the configuration file.
Reimplemented from Module.
Definition at line 522 of file class.bin.filezilla.php.
    {
        $content = file_get_contents( $this->bearsamppConf );
        foreach ( $params as $key => $value ) {
            $content                      = preg_replace( '|' . $key . ' = .*|', $key . ' = ' . '"' . $value . '"', $content );
            $this->bearsamppConfRaw[$key] = $value;
            switch ( $key ) {
                case self::LOCAL_CFG_PORT:
                    $this->port = $value;
                    break;
                case self::LOCAL_CFG_SSL_PORT:
                    $this->sslPort = $value;
                    break;
            }
        }
        file_put_contents( $this->bearsamppConf, $content );
    }
References LOCAL_CFG_PORT, and LOCAL_CFG_SSL_PORT.
setConf()
BinFilezilla::setConf ($elts)
Sets the configuration values for the FileZilla module.
Parameters
array $elts An associative array of configuration key-value pairs.
Definition at line 346 of file class.bin.filezilla.php.
    {
        if ( !$this->enable ) {
            return;
        }
        $conf = simplexml_load_file( $this->conf );
        foreach ( $elts as $key => $value ) {
            $conf->Settings->Item[$key] = $value;
        }
        $conf->asXML( $this->conf );
    }
References $conf.
Referenced by rebuildConf().
setEnable()
BinFilezilla::setEnable ($enabled, $showWindow = false)
Enables or disables the FileZilla module.
Parameters
bool $enabled Whether to enable or disable the module.
bool $showWindow Whether to show a window with the result.
Definition at line 395 of file class.bin.filezilla.php.
    {
        global $bearsamppConfig, $bearsamppLang, $bearsamppWinbinder;
        if ( $enabled == Config::ENABLED && !is_dir( $this->currentPath ) ) {
            Util::logDebug( $this->getName() . ' cannot be enabled because bundle ' . $this->getVersion() . ' does not exist in ' . $this->currentPath );
            if ( $showWindow ) {
                $bearsamppWinbinder->messageBoxError(
                    sprintf( $bearsamppLang->getValue( Lang::ENABLE_BUNDLE_NOT_EXIST ), $this->getName(), $this->getVersion(), $this->currentPath ),
                    sprintf( $bearsamppLang->getValue( Lang::ENABLE_TITLE ), $this->getName() )
                );
            }
            $enabled = Config::DISABLED;
        }
        Util::logInfo( $this->getName() . ' switched to ' . ($enabled == Config::ENABLED ? 'enabled' : 'disabled') );
        $this->enable = $enabled == Config::ENABLED;
        $bearsamppConfig->replace( self::ROOT_CFG_ENABLE, $enabled );
        $this->reload();
        if ( $this->enable ) {
            Util::installService( $this, $this->port, null, $showWindow );
        }
        else {
            Util::removeService( $this->service, $this->name );
        }
    }
References $bearsamppConfig, $bearsamppLang, Config\DISABLED, Lang\ENABLE_BUNDLE_NOT_EXIST, Lang\ENABLE_TITLE, Config\ENABLED, Module\getName(), Module\getVersion(), Util\installService(), Util\logDebug(), Util\logInfo(), reload(), and Util\removeService().
setPort()
BinFilezilla::setPort ($port)
Sets the port number for the FileZilla service.
Parameters
int $port The new port number.
Definition at line 488 of file class.bin.filezilla.php.
    {
        $this->replace( self::LOCAL_CFG_PORT, $port );
    }
References $port, and Module\replace().
Referenced by changePort().
setSslPort()
BinFilezilla::setSslPort ($sslPort)
Sets the SSL port number for the FileZilla service.
Parameters
int $sslPort The new SSL port number.
Definition at line 508 of file class.bin.filezilla.php.
    {
        $this->replace( self::LOCAL_CFG_SSL_PORT, $sslPort );
    }
References $sslPort, and Module\replace().
setVersion()
BinFilezilla::setVersion ($version)
Sets the version for the FileZilla module.
Parameters
string $version The version to set.
Reimplemented from Module.
Definition at line 364 of file class.bin.filezilla.php.
    {
        global $bearsamppConfig;
        $this->version = $version;
        $bearsamppConfig->replace( self::ROOT_CFG_VERSION, $version );
        $this->reload();
    }
References $bearsamppConfig, Module\$version, and reload().
Referenced by updateConfig().
switchVersion()
BinFilezilla::switchVersion ($version, $showWindow = false)
Switches the version of the FileZilla module.
Parameters
string $version The version to switch to.
bool $showWindow Whether to show a window with the result.
Returns
bool Returns true if the version is switched successfully, false otherwise.
Definition at line 265 of file class.bin.filezilla.php.
    {
        Util::logDebug( 'Switch ' . $this->name . ' version to ' . $version );
        return $this->updateConfig( $version, 0, $showWindow );
    }
References Module\$version, Util\logDebug(), and updateConfig().
updateConfig()
BinFilezilla::updateConfig ($version = null, $sub = 0, $showWindow = false) protected
Updates the configuration for the specified version.
Parameters
string | null $version The version to update to. If null, the current version is used.
int $sub The sub-level for logging indentation.
bool $showWindow Whether to show a window with the result.
Returns
bool Returns true if the configuration is updated successfully, false otherwise.
Reimplemented from Module.
Definition at line 281 of file class.bin.filezilla.php.
    {
        global $bearsamppLang, $bearsamppWinbinder;
        if ( !$this->enable ) {
            return true;
        }
        $version = $version == null ? $this->version : $version;
        Util::logDebug( ($sub > 0 ? str_repeat( ' ', 2 * $sub ) : '') . 'Update ' . $this->name . ' ' . $version . ' config' );
        $boxTitle = sprintf( $bearsamppLang->getValue( Lang::SWITCH_VERSION_TITLE ), $this->getName(), $version );
        $conf          = str_replace( 'filezilla' . $this->getVersion(), 'filezilla' . $version, $this->getConf() );
        $bearsamppConf = str_replace( 'filezilla' . $this->getVersion(), 'filezilla' . $version, $this->bearsamppConf );
        if ( !file_exists( $conf ) || !file_exists( $bearsamppConf ) ) {
            Util::logError( 'bearsampp config files not found for ' . $this->getName() . ' ' . $version );
            if ( $showWindow ) {
                $bearsamppWinbinder->messageBoxError(
                    sprintf( $bearsamppLang->getValue( Lang::BEARSAMPP_CONF_NOT_FOUND_ERROR ), $this->getName() . ' ' . $version ),
                    $boxTitle
                );
            }
            return false;
        }
        $bearsamppConfRaw = parse_ini_file( $bearsamppConf );
        if ( $bearsamppConfRaw === false || !isset( $bearsamppConfRaw[self::ROOT_CFG_VERSION] ) || $bearsamppConfRaw[self::ROOT_CFG_VERSION] != $version ) {
            Util::logError( 'bearsampp config file malformed for ' . $this->getName() . ' ' . $version );
            if ( $showWindow ) {
                $bearsamppWinbinder->messageBoxError(
                    sprintf( $bearsamppLang->getValue( Lang::BEARSAMPP_CONF_MALFORMED_ERROR ), $this->getName() . ' ' . $version ),
                    $boxTitle
                );
            }
            return false;
        }
        // bearsampp.conf
        $this->setVersion( $version );
        // conf
        $this->rebuildConf();
        return true;
    }
References Module\$bearsamppConf, Module\$bearsamppConfRaw, $bearsamppLang, $conf, Module\$version, Lang\BEARSAMPP_CONF_MALFORMED_ERROR, Lang\BEARSAMPP_CONF_NOT_FOUND_ERROR, getConf(), Module\getName(), Module\getVersion(), Util\logDebug(), Util\logError(), rebuildConf(), setVersion(), and Lang\SWITCH_VERSION_TITLE.
Referenced by switchVersion().
Field Documentation
$conf
BinFilezilla::$conf private
Definition at line 43 of file class.bin.filezilla.php.
Referenced by getConf(), setConf(), and updateConfig().
$exe
BinFilezilla::$exe private
Definition at line 41 of file class.bin.filezilla.php.
Referenced by getExe().
$itfConf
BinFilezilla::$itfConf private
Definition at line 44 of file class.bin.filezilla.php.
Referenced by getItfConf().
$itfExe
BinFilezilla::$itfExe private
Definition at line 42 of file class.bin.filezilla.php.
Referenced by getItfExe().
$localItfConf
BinFilezilla::$localItfConf private
Definition at line 45 of file class.bin.filezilla.php.
$log
BinFilezilla::$log private
Definition at line 39 of file class.bin.filezilla.php.
Referenced by getLog(), and reload().
$logsPath
BinFilezilla::$logsPath private
Definition at line 38 of file class.bin.filezilla.php.
Referenced by getLogsPath().
$port
BinFilezilla::$port private
Definition at line 46 of file class.bin.filezilla.php.
Referenced by changePort(), checkPort(), getPort(), and setPort().
$service
BinFilezilla::$service private
Definition at line 37 of file class.bin.filezilla.php.
Referenced by getService().
$sslPort
BinFilezilla::$sslPort private
Definition at line 47 of file class.bin.filezilla.php.
Referenced by getSslPort(), and setSslPort().
CFG_IP_FILTER_ALLOWED
const BinFilezilla::CFG_IP_FILTER_ALLOWED = 39
Definition at line 32 of file class.bin.filezilla.php.
Referenced by ActionSwitchOnline\switchFilezilla().
CFG_IP_FILTER_DISALLOWED
const BinFilezilla::CFG_IP_FILTER_DISALLOWED = 40
Definition at line 33 of file class.bin.filezilla.php.
Referenced by ActionSwitchOnline\switchFilezilla().
CFG_SERVER_PORT
const BinFilezilla::CFG_SERVER_PORT = 0
Definition at line 30 of file class.bin.filezilla.php.
CFG_SERVICE_DISPLAY_NAME
const BinFilezilla::CFG_SERVICE_DISPLAY_NAME = 59
Definition at line 35 of file class.bin.filezilla.php.
CFG_SERVICE_NAME
const BinFilezilla::CFG_SERVICE_NAME = 58
Definition at line 34 of file class.bin.filezilla.php.
CFG_WELCOME_MSG
const BinFilezilla::CFG_WELCOME_MSG = 15
Definition at line 31 of file class.bin.filezilla.php.
LOCAL_CFG_CONF
const BinFilezilla::LOCAL_CFG_CONF = 'filezillaConf'
Definition at line 25 of file class.bin.filezilla.php.
Referenced by reload().
LOCAL_CFG_EXE
const BinFilezilla::LOCAL_CFG_EXE = 'filezillaExe'
Definition at line 23 of file class.bin.filezilla.php.
Referenced by reload().
LOCAL_CFG_ITF_CONF
const BinFilezilla::LOCAL_CFG_ITF_CONF = 'filezillaItfConf'
Definition at line 26 of file class.bin.filezilla.php.
Referenced by reload().
LOCAL_CFG_ITF_EXE
const BinFilezilla::LOCAL_CFG_ITF_EXE = 'filezillaItfExe'
Definition at line 24 of file class.bin.filezilla.php.
Referenced by reload().
LOCAL_CFG_PORT
const BinFilezilla::LOCAL_CFG_PORT = 'filezillaPort'
Definition at line 27 of file class.bin.filezilla.php.
Referenced by reload(), and replaceAll().
LOCAL_CFG_SSL_PORT
const BinFilezilla::LOCAL_CFG_SSL_PORT = 'filezillaSslPort'
Definition at line 28 of file class.bin.filezilla.php.
Referenced by reload(), and replaceAll().
ROOT_CFG_ENABLE
const BinFilezilla::ROOT_CFG_ENABLE = 'filezillaEnable'
Definition at line 20 of file class.bin.filezilla.php.
ROOT_CFG_VERSION
const BinFilezilla::ROOT_CFG_VERSION = 'filezillaVersion'
Definition at line 21 of file class.bin.filezilla.php.
SERVICE_NAME
const BinFilezilla::SERVICE_NAME = 'bearsamppfilezilla'
Definition at line 18 of file class.bin.filezilla.php.
Referenced by ActionService\__construct(), Win32Service\create(), Win32Service\delete(), TplAppFilezilla\getActionInstallFilezillaService(), TplAppFilezilla\getActionRemoveFilezillaService(), TplAppOnline\getActionStatus(), Bins\getServices(), Batch\installFilezillaService(), ActionStartup\installServices(), ActionQuit\processWindow(), and Win32Service\start().
The documentation for this class was generated from the following file:
E:/Bearsampp-development/sandbox/core/classes/bins/class.bin.filezilla.php