My Project: TplAppReload Class Reference
TplAppReload Class Reference
Static Public Member Functions
static getActionReload ()
static process ()
Data Fields
const ACTION = 'reload'
Detailed Description
Class TplAppReload
This class provides methods to generate actions and menu items for reloading the Bearsampp application. It includes functionalities for creating reload actions and processing reload commands.
Definition at line 16 of file class.tpl.app.reload.php.
Member Function Documentation
getActionReload()
static TplAppReload::getActionReload () static
Generates the action to reload the application.
This method creates the action string for reloading the application. It includes commands to reset services and read the configuration. The action string is used to define what happens when the reload action is triggered.
Returns
string The generated action string for reloading the application.
Definition at line 52 of file class.tpl.app.reload.php.
    {
        return TplApp::getActionRun(Action::RELOAD) . PHP_EOL .
            'Action: resetservices' . PHP_EOL .
            'Action: readconfig';
    }
References TplApp\getActionRun(), and Action\RELOAD.
Referenced by ActionRebuildini\__construct(), TplAppApache\getActionAddAlias(), TplAppApache\getActionAddVhost(), TplAppApache\getActionChangeApachePort(), TplAppBrowser\getActionChangeBrowser(), TplAppFilezilla\getActionChangeFilezillaPort(), TplAppMailhog\getActionChangeMailhogPort(), TplAppMailpit\getActionChangeMailpitPort(), TplAppMariadb\getActionChangeMariadbPort(), TplAppMariadb\getActionChangeMariadbRootPwd(), TplAppMemcached\getActionChangeMemcachedPort(), TplAppMysql\getActionChangeMysqlPort(), TplAppMysql\getActionChangeMysqlRootPwd(), TplAppPostgresql\getActionChangePostgresqlPort(), TplAppPostgresql\getActionChangePostgresqlRootPwd(), TplAppXlight\getActionChangeXlightPort(), TplAppApache\getActionEditAlias(), TplAppApache\getActionEditVhost(), TplAppApache\getActionEnableApache(), TplAppFilezilla\getActionEnableFilezilla(), TplAppMailhog\getActionEnableMailhog(), TplAppMailpit\getActionEnableMailpit(), TplAppMariadb\getActionEnableMariadb(), TplAppMemcached\getActionEnableMemcached(), TplAppMysql\getActionEnableMysql(), TplAppNodejs\getActionEnableNodejs(), TplAppPhp\getActionEnablePhp(), TplAppPostgresql\getActionEnablePostgresql(), TplAppXlight\getActionEnableXlight(), TplAppApache\getActionInstallApacheService(), TplAppFilezilla\getActionInstallFilezillaService(), TplAppMailhog\getActionInstallMailhogService(), TplAppMailpit\getActionInstallMailpitService(), TplAppMariadb\getActionInstallMariadbService(), TplAppMemcached\getActionInstallMemcachedService(), TplAppMysql\getActionInstallMysqlService(), TplAppPostgresql\getActionInstallPostgresqlService(), TplAppXlight\getActionInstallXlightService(), TplAppLaunchStartup\getActionLaunchStartup(), TplAppGit\getActionRefreshGitRepos(), TplAppGit\getActionRefreshGitReposStartup(), TplAppApache\getActionRemoveApacheService(), TplAppFilezilla\getActionRemoveFilezillaService(), TplAppMailhog\getActionRemoveMailhogService(), TplAppMailpit\getActionRemoveMailpitService(), TplAppMariadb\getActionRemoveMariadbService(), TplAppMemcached\getActionRemoveMemcachedService(), TplAppMysql\getActionRemoveMysqlService(), TplAppPostgresql\getActionRemovePostgresqlService(), TplAppXlight\getActionRemoveXlightService(), TplAppOnline\getActionStatus(), TplAppApache\getActionSwitchApacheModule(), TplAppApache\getActionSwitchApacheVersion(), TplAppFilezilla\getActionSwitchFilezillaVersion(), TplAppLang\getActionSwitchLang(), TplAppLogsVerbose\getActionSwitchLogsVerbose(), TplAppMailhog\getActionSwitchMailhogVersion(), TplAppMailpit\getActionSwitchMailpitVersion(), TplAppMariadb\getActionSwitchMariadbVersion(), TplAppMemcached\getActionSwitchMemcachedVersion(), TplAppMysql\getActionSwitchMysqlVersion(), TplAppNodejs\getActionSwitchNodejsVersion(), TplAppPhp\getActionSwitchPhpExtension(), TplAppPhp\getActionSwitchPhpSetting(), TplAppPhp\getActionSwitchPhpVersion(), TplAppPostgresql\getActionSwitchPostgresqlVersion(), TplAppXlight\getActionSwitchXlightVersion(), and TplApp\getSectionStartupAction().
process()
static TplAppReload::process () static
Generates the reload menu item and associated actions.
This method creates a menu item for reloading the application and defines the actions to be taken when the reload menu item is selected. It uses the global language object to retrieve the localized string for the reload action.
@global object $bearsamppLang Provides language support for retrieving language-specific values.
Returns
array The generated menu item and actions for reloading the application.
Definition at line 32 of file class.tpl.app.reload.php.
    {
        global $bearsamppLang;
        return TplApp::getActionMulti(
            self::ACTION, null,
            array($bearsamppLang->getValue(Lang::RELOAD), TplAestan::GLYPH_RELOAD),
            false, get_called_class()
        );
    }
References $bearsamppLang, TplApp\getActionMulti(), TplAestan\GLYPH_RELOAD, and Lang\RELOAD.
Referenced by TplApp\getSectionMenuRight().
Field Documentation
ACTION
const TplAppReload::ACTION = 'reload'
Definition at line 19 of file class.tpl.app.reload.php.
The documentation for this class was generated from the following file:
E:/Bearsampp-development/sandbox/core/classes/tpls/app/class.tpl.app.reload.php