My Project: Splash Class Reference
Splash Class Reference
Public Member Functions
__construct ()
getWbWindow ()
incrProgressBar ($nb=1)
init ($title, $gauge, $text)
setTextLoading ($caption)
Data Fields
const WINDOW_HEIGHT = 90
const WINDOW_WIDTH = 460
Private Attributes
$currentImg
$wbImage
$wbProgressBar
$wbTextLoading
$wbWindow
Detailed Description
Class Splash
This class represents a splash screen with a progress bar for the Bearsampp application. It provides methods to initialize the splash screen, set loading text, and increment the progress bar.
Definition at line 16 of file class.splash.php.
Constructor & Destructor Documentation
__construct()
Splash::__construct ()
Splash constructor.
Initializes the Splash class and sets the current image to null.
Definition at line 34 of file class.splash.php.
    {
        Util::logInitClass($this);
        $this->currentImg = null;
    }
References Util\logInitClass().
Member Function Documentation
getWbWindow()
Splash::getWbWindow ()
Retrieves the window object of the splash screen.
Returns
mixed The window object of the splash screen.
Definition at line 103 of file class.splash.php.
    {
        return $this->wbWindow;
    }
References $wbWindow.
incrProgressBar()
Splash::incrProgressBar ($nb = 1)
Increments the progress bar by a specified number of steps.
Parameters
int $nb The number of steps to increment the progress bar by. Default is 1.
Definition at line 85 of file class.splash.php.
    {
        global $bearsamppCore, $bearsamppWinbinder;
        for ($i = 0; $i < $nb; $i++) {
            $bearsamppWinbinder->drawImage($this->wbWindow, $bearsamppCore->getResourcesPath() . '/homepage/img/bearsampp.bmp', 4, 4, 32, 32);
            $bearsamppWinbinder->incrProgressBar($this->wbProgressBar);
        }
        $bearsamppWinbinder->wait();
        $bearsamppWinbinder->wait($this->wbWindow);
    }
References $bearsamppCore.
Referenced by init().
init()
Splash::init ($title, $gauge, $text)
Initializes the splash screen.
Parameters
string $title The title of the splash screen window.
int $gauge The maximum value for the progress bar.
string $text The initial loading text to display.
Definition at line 47 of file class.splash.php.
    {
        global $bearsamppCore, $bearsamppWinbinder;
        $bearsamppWinbinder->reset();
        $screenArea = explode(' ', $bearsamppWinbinder->getSystemInfo(WinBinder::SYSINFO_WORKAREA));
        $screenWidth = intval($screenArea[2]);
        $screenHeight = intval($screenArea[3]);
        $xPos = $screenWidth - self::WINDOW_WIDTH;
        $yPos = $screenHeight - self::WINDOW_HEIGHT - 5;
        $this->wbWindow = $bearsamppWinbinder->createWindow(null, ToolDialog, $title, $xPos, $yPos, self::WINDOW_WIDTH, self::WINDOW_HEIGHT, WBC_TOP | WBC_READONLY, null);
        $this->wbImage = $bearsamppWinbinder->drawImage($this->wbWindow, $bearsamppCore->getResourcesPath() . '/homepage/img/bearsampp.bmp');
        $this->wbProgressBar = $bearsamppWinbinder->createProgressBar($this->wbWindow, $gauge + 1, 42, 24, 390, 15);
        $this->setTextLoading($text);
        $this->incrProgressBar();
    }
References $bearsamppCore, incrProgressBar(), setTextLoading(), WinBinder\SYSINFO_WORKAREA, and WINDOW_WIDTH.
setTextLoading()
Splash::setTextLoading ($caption)
Sets the loading text on the splash screen.
Parameters
string $caption The loading text to display.
Definition at line 72 of file class.splash.php.
    {
        global $bearsamppWinbinder;
        $bearsamppWinbinder->drawRect($this->wbWindow, 42, 0, self::WINDOW_WIDTH - 42, self::WINDOW_HEIGHT);
        $this->wbTextLoading = $bearsamppWinbinder->drawText($this->wbWindow, $caption, 42, 0, self::WINDOW_WIDTH - 44, 25);
    }
Referenced by init().
Field Documentation
$currentImg
Splash::$currentImg private
Definition at line 27 of file class.splash.php.
$wbImage
Splash::$wbImage private
Definition at line 23 of file class.splash.php.
$wbProgressBar
Splash::$wbProgressBar private
Definition at line 25 of file class.splash.php.
$wbTextLoading
Splash::$wbTextLoading private
Definition at line 24 of file class.splash.php.
$wbWindow
Splash::$wbWindow private
Definition at line 22 of file class.splash.php.
Referenced by getWbWindow().
WINDOW_HEIGHT
const Splash::WINDOW_HEIGHT = 90
Definition at line 20 of file class.splash.php.
WINDOW_WIDTH
const Splash::WINDOW_WIDTH = 460
Definition at line 19 of file class.splash.php.
Referenced by init().
The documentation for this class was generated from the following file:
E:/Bearsampp-development/sandbox/core/classes/class.splash.php