My Project: ActionService Class Reference
ActionService Class Reference
Public Member Functions
__construct ($args)
Data Fields
const CREATE = 'create'
const INSTALL = 'install'
const REMOVE = 'remove'
const RESTART = 'restart'
const START = 'start'
const STOP = 'stop'
Private Member Functions
create ($service)
install ($bin, $port, $syntaxCheckCmd)
remove ($service, $name)
restart ($bin, $syntaxCheckCmd)
start ($bin, $syntaxCheckCmd)
stop ($service)
Detailed Description
Class ActionService Handles various actions related to services such as creating, starting, stopping, restarting, installing, and removing.
Definition at line 14 of file class.action.service.php.
Constructor & Destructor Documentation
__construct()
ActionService::__construct ($args)
ActionService constructor. Initializes the service action based on provided arguments.
Parameters
array $args Arguments for the service action.
Definition at line 30 of file class.action.service.php.
    {
        global $bearsamppBins;
        Util::startLoading();
        // Reload bins
        $bearsamppBins->reload();
        if ( isset( $args[0] ) && !empty( $args[0] ) && isset( $args[1] ) && !empty( $args[1] ) ) {
            $sName          = $args[0];
            $bin            = null;
            $port           = 0;
            $syntaxCheckCmd = null;
            if ( $sName == BinMailhog::SERVICE_NAME ) {
                $bin  = $bearsamppBins->getMailhog();
                $port = $bin->getSmtpPort();
            }
            elseif ( $sName == BinMailpit::SERVICE_NAME ) {
                $bin  = $bearsamppBins->getMailpit();
                $port = $bin->getSmtpPort();
            }
            elseif ( $sName == BinMemcached::SERVICE_NAME ) {
                $bin  = $bearsamppBins->getMemcached();
                $port = $bin->getPort();
            }
            elseif ( $sName == BinApache::SERVICE_NAME ) {
                $bin            = $bearsamppBins->getApache();
                $port           = $bin->getPort();
                $syntaxCheckCmd = BinApache::CMD_SYNTAX_CHECK;
            }
            elseif ( $sName == BinMysql::SERVICE_NAME ) {
                $bin            = $bearsamppBins->getMysql();
                $port           = $bin->getPort();
                $syntaxCheckCmd = BinMysql::CMD_SYNTAX_CHECK;
            }
            elseif ( $sName == BinMariadb::SERVICE_NAME ) {
                $bin            = $bearsamppBins->getMariadb();
                $port           = $bin->getPort();
                $syntaxCheckCmd = BinMariadb::CMD_SYNTAX_CHECK;
            }
            elseif ( $sName == BinPostgresql::SERVICE_NAME ) {
                $bin  = $bearsamppBins->getPostgresql();
                $port = $bin->getPort();
            }
            elseif ( $sName == BinFilezilla::SERVICE_NAME ) {
                $bin  = $bearsamppBins->getFilezilla();
                $port = $bin->getPort();
            }
            elseif ( $sName == BinXlight::SERVICE_NAME ) {
                $bin  = $bearsamppBins->getXlight();
                $port = $bin->getPort();
            }
            $name    = $bin->getName();
            $service = $bin->getService();
            if ( !empty( $service ) && $service instanceof Win32Service ) {
                if ( $args[1] == self::CREATE ) {
                    $this->create( $service );
                }
                elseif ( $args[1] == self::START ) {
                    $this->start( $bin, $syntaxCheckCmd );
                }
                elseif ( $args[1] == self::STOP ) {
                    $this->stop( $service );
                }
                elseif ( $args[1] == self::RESTART ) {
                    $this->restart( $bin, $syntaxCheckCmd );
                }
                elseif ( $args[1] == self::INSTALL ) {
                    if ( !empty( $port ) ) {
                        $this->install( $bin, $port, $syntaxCheckCmd );
                    }
                }
                elseif ( $args[1] == self::REMOVE ) {
                    $this->remove( $service, $name );
                }
            }
        }
        Util::stopLoading();
    }
References $bearsamppBins, $port, BinApache\CMD_SYNTAX_CHECK, BinMariadb\CMD_SYNTAX_CHECK, BinMysql\CMD_SYNTAX_CHECK, create(), install(), restart(), BinApache\SERVICE_NAME, BinFilezilla\SERVICE_NAME, BinMailhog\SERVICE_NAME, BinMailpit\SERVICE_NAME, BinMariadb\SERVICE_NAME, BinMemcached\SERVICE_NAME, BinMysql\SERVICE_NAME, BinPostgresql\SERVICE_NAME, BinXlight\SERVICE_NAME, start(), Util\startLoading(), stop(), and Util\stopLoading().
Member Function Documentation
create()
ActionService::create ($service) private
Creates a service.
Parameters
Win32Service $service The service to create.
Definition at line 119 of file class.action.service.php.
    {
        $service->create();
    }
Referenced by __construct().
install()
ActionService::install ($bin, $port, $syntaxCheckCmd) private
Installs a service.
Parameters
mixed $bin The binary object of the service.
int $port The port number for the service.
string | null $syntaxCheckCmd The command to check syntax, if applicable.
Definition at line 165 of file class.action.service.php.
    {
        Util::installService( $bin, $port, $syntaxCheckCmd, true );
    }
References $port, and Util\installService().
Referenced by __construct().
remove()
ActionService::remove ($service, $name) private
Removes a service.
Parameters
Win32Service $service The service to remove.
string $name The name of the service.
Definition at line 176 of file class.action.service.php.
    {
        Util::removeService( $service, $name );
    }
References Util\removeService().
restart()
ActionService::restart ($bin, $syntaxCheckCmd) private
Restarts a service.
Parameters
mixed $bin The binary object of the service.
string | null $syntaxCheckCmd The command to check syntax, if applicable.
Definition at line 151 of file class.action.service.php.
    {
        if ( $bin->getService()->stop() ) {
            $this->start( $bin, $syntaxCheckCmd );
        }
    }
References start().
Referenced by __construct().
start()
ActionService::start ($bin, $syntaxCheckCmd) private
Starts a service.
Parameters
mixed $bin The binary object of the service.
string | null $syntaxCheckCmd The command to check syntax, if applicable.
Definition at line 130 of file class.action.service.php.
    {
        Util::startService( $bin, $syntaxCheckCmd, true );
    }
References Util\startService().
Referenced by __construct(), and restart().
stop()
ActionService::stop ($service) private
Stops a service.
Parameters
Win32Service $service The service to stop.
Definition at line 140 of file class.action.service.php.
    {
        $service->stop();
    }
Referenced by __construct().
Field Documentation
CREATE
const ActionService::CREATE = 'create'
Definition at line 16 of file class.action.service.php.
Referenced by TplService\getActionCreate().
INSTALL
const ActionService::INSTALL = 'install'
Definition at line 21 of file class.action.service.php.
Referenced by TplService\getActionInstall(), TplAppApache\getActionInstallApacheService(), TplAppFilezilla\getActionInstallFilezillaService(), TplAppMailhog\getActionInstallMailhogService(), TplAppMailpit\getActionInstallMailpitService(), TplAppMariadb\getActionInstallMariadbService(), TplAppMemcached\getActionInstallMemcachedService(), TplAppMysql\getActionInstallMysqlService(), TplAppPostgresql\getActionInstallPostgresqlService(), TplAppXlight\getActionInstallXlightService(), and TplService\getItemInstall().
REMOVE
const ActionService::REMOVE = 'remove'
Definition at line 22 of file class.action.service.php.
Referenced by TplService\getActionRemove(), TplAppApache\getActionRemoveApacheService(), TplAppFilezilla\getActionRemoveFilezillaService(), TplAppMailhog\getActionRemoveMailhogService(), TplAppMailpit\getActionRemoveMailpitService(), TplAppMariadb\getActionRemoveMariadbService(), TplAppMemcached\getActionRemoveMemcachedService(), TplAppMysql\getActionRemoveMysqlService(), TplAppPostgresql\getActionRemovePostgresqlService(), TplAppXlight\getActionRemoveXlightService(), and TplService\getItemRemove().
RESTART
const ActionService::RESTART = 'restart'
Definition at line 19 of file class.action.service.php.
Referenced by TplService\getActionRestart(), and TplService\getItemRestart().
START
const ActionService::START = 'start'
Definition at line 17 of file class.action.service.php.
Referenced by TplService\getActionStart(), and TplService\getItemStart().
STOP
const ActionService::STOP = 'stop'
Definition at line 18 of file class.action.service.php.
Referenced by TplService\getActionStop(), and TplService\getItemStop().
The documentation for this class was generated from the following file:
E:/Bearsampp-development/sandbox/core/classes/actions/class.action.service.php