My Project: ActionEditVhost Class Reference
ActionEditVhost Class Reference
Public Member Functions
__construct ($args)
processWindow ($window, $id, $ctrl, $param1, $param2)
Data Fields
const GAUGE_DELETE = 2
const GAUGE_SAVE = 3
Private Attributes
$initServerName
$wbBtnCancel
$wbBtnDelete
$wbBtnDocRoot
$wbBtnSave
$wbInputDocRoot
$wbInputServerName
$wbLabelDocRoot
$wbLabelExp
$wbLabelServerName
$wbProgressBar
$wbWindow
Detailed Description
Class ActionEditVhost Handles the editing of virtual hosts within the Bearsampp application.
Definition at line 14 of file class.action.editVhost.php.
Constructor & Destructor Documentation
__construct()
ActionEditVhost::__construct ($args)
ActionEditVhost constructor. Initializes the virtual host editing window and its components.
Parameters
array $args Arguments passed to the constructor, typically containing the server name.
Definition at line 38 of file class.action.editVhost.php.
    {
        global $bearsamppRoot, $bearsamppLang, $bearsamppWinbinder;
        if (isset($args[0]) && !empty($args[0])) {
            $filePath = $bearsamppRoot->getVhostsPath() . '/' . $args[0] . '.conf';
            $fileContent = file_get_contents($filePath);
            if (preg_match('/ServerName\s+(.*)/', $fileContent, $matchServerName) && preg_match('/DocumentRoot\s+"(.*)"/', $fileContent, $matchDocumentRoot)) {
                $this->initServerName = trim($matchServerName[1]);
                $initDocumentRoot = Util::formatWindowsPath(trim($matchDocumentRoot[1]));
                $bearsamppWinbinder->reset();
                $this->wbWindow = $bearsamppWinbinder->createAppWindow(sprintf($bearsamppLang->getValue(Lang::EDIT_VHOST_TITLE), $this->initServerName), 490, 200, WBC_NOTIFY, WBC_KEYDOWN | WBC_KEYUP);
                $this->wbLabelServerName = $bearsamppWinbinder->createLabel($this->wbWindow, $bearsamppLang->getValue(Lang::VHOST_SERVER_NAME_LABEL) . ' :', 15, 15, 85, null, WBC_RIGHT);
                $this->wbInputServerName = $bearsamppWinbinder->createInputText($this->wbWindow, $this->initServerName, 105, 13, 150, null);
                $this->wbLabelDocRoot = $bearsamppWinbinder->createLabel($this->wbWindow, $bearsamppLang->getValue(Lang::VHOST_DOCUMENT_ROOT_LABEL) . ' :', 15, 45, 85, null, WBC_RIGHT);
                $this->wbInputDocRoot = $bearsamppWinbinder->createInputText($this->wbWindow, $initDocumentRoot, 105, 43, 190, null, null, WBC_READONLY);
                $this->wbBtnDocRoot = $bearsamppWinbinder->createButton($this->wbWindow, $bearsamppLang->getValue(Lang::BUTTON_BROWSE), 300, 43, 110);
                $this->wbLabelExp = $bearsamppWinbinder->createLabel($this->wbWindow, sprintf($bearsamppLang->getValue(Lang::VHOST_EXP_LABEL), $this->initServerName, $initDocumentRoot), 15, 80, 470, 50);
                $this->wbProgressBar = $bearsamppWinbinder->createProgressBar($this->wbWindow, self::GAUGE_SAVE + 1, 15, 137, 190);
                $this->wbBtnSave = $bearsamppWinbinder->createButton($this->wbWindow, $bearsamppLang->getValue(Lang::BUTTON_SAVE), 215, 132);
                $this->wbBtnDelete = $bearsamppWinbinder->createButton($this->wbWindow, $bearsamppLang->getValue(Lang::BUTTON_DELETE), 300, 132);
                $this->wbBtnCancel = $bearsamppWinbinder->createButton($this->wbWindow, $bearsamppLang->getValue(Lang::BUTTON_CANCEL), 385, 132);
                $bearsamppWinbinder->setHandler($this->wbWindow, $this, 'processWindow');
                $bearsamppWinbinder->mainLoop();
                $bearsamppWinbinder->reset();
            }
        }
    }
References $bearsamppLang, $bearsamppRoot, Lang\BUTTON_BROWSE, Lang\BUTTON_CANCEL, Lang\BUTTON_DELETE, Lang\BUTTON_SAVE, Lang\EDIT_VHOST_TITLE, Util\formatWindowsPath(), Lang\VHOST_DOCUMENT_ROOT_LABEL, Lang\VHOST_EXP_LABEL, and Lang\VHOST_SERVER_NAME_LABEL.
Member Function Documentation
processWindow()
ActionEditVhost::processWindow ($window, $id, $ctrl, $param1, $param2)
Processes window events and handles user interactions.
Parameters
mixed $window The window object.
int $id The ID of the control that triggered the event.
mixed $ctrl The control object.
mixed $param1 Additional parameter 1.
mixed $param2 Additional parameter 2.
Definition at line 82 of file class.action.editVhost.php.
    {
        global $bearsamppRoot, $bearsamppBins, $bearsamppLang, $bearsamppOpenSsl, $bearsamppWinbinder;
        $serverName = $bearsamppWinbinder->getText($this->wbInputServerName[WinBinder::CTRL_OBJ]);
        $documentRoot = $bearsamppWinbinder->getText($this->wbInputDocRoot[WinBinder::CTRL_OBJ]);
        switch ($id) {
            case $this->wbInputServerName[WinBinder::CTRL_ID]:
                $bearsamppWinbinder->setText(
                    $this->wbLabelExp[WinBinder::CTRL_OBJ],
                    sprintf($bearsamppLang->getValue(Lang::VHOST_EXP_LABEL), $serverName, $documentRoot)
                );
                $bearsamppWinbinder->setEnabled($this->wbBtnSave[WinBinder::CTRL_OBJ], empty($serverName) ? false : true);
                break;
            case $this->wbBtnDocRoot[WinBinder::CTRL_ID]:
                $documentRoot = $bearsamppWinbinder->sysDlgPath($window, $bearsamppLang->getValue(Lang::VHOST_DOC_ROOT_PATH), $documentRoot);
                if ($documentRoot && is_dir($documentRoot)) {
                    $bearsamppWinbinder->setText($this->wbInputDocRoot[WinBinder::CTRL_OBJ], $documentRoot . '\\');
                    $bearsamppWinbinder->setText(
                        $this->wbLabelExp[WinBinder::CTRL_OBJ],
                        sprintf($bearsamppLang->getValue(Lang::VHOST_EXP_LABEL), $serverName, $documentRoot . '\\')
                    );
                    // Reload to add host
                    TplService::getActionRestart(BinApache::SERVICE_NAME) . PHP_EOL;
                }
                break;
            case $this->wbBtnSave[WinBinder::CTRL_ID]:
                $bearsamppWinbinder->setProgressBarMax($this->wbProgressBar, self::GAUGE_SAVE + 1);
                $bearsamppWinbinder->incrProgressBar($this->wbProgressBar);
                if (!Util::isValidDomainName($serverName)) {
                    $bearsamppWinbinder->messageBoxError(
                        sprintf($bearsamppLang->getValue(Lang::VHOST_NOT_VALID_DOMAIN), $serverName),
                        $bearsamppLang->getValue(Lang::ADD_VHOST_TITLE));
                    $bearsamppWinbinder->resetProgressBar($this->wbProgressBar);
                    break;
                }
                if ($serverName != $this->initServerName && is_file($bearsamppRoot->getVhostsPath() . '/' . $serverName . '.conf')) {
                    $bearsamppWinbinder->messageBoxError(
                        sprintf($bearsamppLang->getValue(Lang::VHOST_ALREADY_EXISTS), $serverName),
                        sprintf($bearsamppLang->getValue(Lang::EDIT_VHOST_TITLE), $this->initServerName));
                    $bearsamppWinbinder->resetProgressBar($this->wbProgressBar);
                    break;
                }
                // Remove old vhost
                $bearsamppOpenSsl->removeCrt($this->initServerName);
                @unlink($bearsamppRoot->getVhostsPath() . '/' . $this->initServerName . '.conf');
                if ($bearsamppOpenSsl->createCrt($serverName) && file_put_contents($bearsamppRoot->getVhostsPath() . '/' . $serverName . '.conf', $bearsamppBins->getApache()->getVhostContent($serverName, $documentRoot)) !== false) {
                    $bearsamppWinbinder->incrProgressBar($this->wbProgressBar);
                    $bearsamppBins->getApache()->getService()->restart();
                    $bearsamppWinbinder->incrProgressBar($this->wbProgressBar);
                    $bearsamppWinbinder->messageBoxInfo(
                        sprintf($bearsamppLang->getValue(Lang::VHOST_CREATED), $serverName, $serverName, $documentRoot),
                        sprintf($bearsamppLang->getValue(Lang::EDIT_VHOST_TITLE), $this->initServerName));
                    $bearsamppWinbinder->destroyWindow($window);
                } else {
                    $bearsamppWinbinder->messageBoxError(
                        $bearsamppLang->getValue(Lang::VHOST_CREATED_ERROR),
                        sprintf($bearsamppLang->getValue(Lang::EDIT_VHOST_TITLE), $this->initServerName));
                    $bearsamppWinbinder->resetProgressBar($this->wbProgressBar);
                }
                // Reload to remove host
                TplService::getActionRestart(BinApache::SERVICE_NAME) . PHP_EOL;
                break;
            case $this->wbBtnDelete[WinBinder::CTRL_ID]:
                $bearsamppWinbinder->setProgressBarMax($this->wbProgressBar, self::GAUGE_DELETE + 1);
                $boxTitle = $bearsamppLang->getValue(Lang::DELETE_VHOST_TITLE);
                $confirm = $bearsamppWinbinder->messageBoxYesNo(
                    sprintf($bearsamppLang->getValue(Lang::DELETE_VHOST), $this->initServerName),
                    $boxTitle);
                $bearsamppWinbinder->incrProgressBar($this->wbProgressBar);
                if ($confirm) {
                    if ($bearsamppOpenSsl->removeCrt($this->initServerName) && @unlink($bearsamppRoot->getVhostsPath() . '/' . $this->initServerName . '.conf')) {
                        $bearsamppWinbinder->incrProgressBar($this->wbProgressBar);
                        $bearsamppBins->getApache()->getService()->restart();
                        $bearsamppWinbinder->incrProgressBar($this->wbProgressBar);
                        $bearsamppWinbinder->messageBoxInfo(
                            sprintf($bearsamppLang->getValue(Lang::VHOST_REMOVED), $this->initServerName),
                            $boxTitle);
                        $bearsamppWinbinder->destroyWindow($window);
                    } else {
                        $bearsamppWinbinder->messageBoxError(
                            sprintf($bearsamppLang->getValue(Lang::VHOST_REMOVE_ERROR), $bearsamppRoot->getVhostsPath() . '/' . $this->initServerName . '.conf'),
                            $boxTitle);
                        $bearsamppWinbinder->resetProgressBar($this->wbProgressBar);
                    }
                }
                break;
            case IDCLOSE:
            case $this->wbBtnCancel[WinBinder::CTRL_ID]:
                $bearsamppWinbinder->destroyWindow($window);
                break;
        }
    }
References $bearsamppBins, $bearsamppLang, $bearsamppRoot, Lang\ADD_VHOST_TITLE, WinBinder\CTRL_ID, WinBinder\CTRL_OBJ, Lang\DELETE_VHOST, Lang\DELETE_VHOST_TITLE, Lang\EDIT_VHOST_TITLE, TplService\getActionRestart(), Util\isValidDomainName(), BinApache\SERVICE_NAME, Lang\VHOST_ALREADY_EXISTS, Lang\VHOST_CREATED, Lang\VHOST_CREATED_ERROR, Lang\VHOST_DOC_ROOT_PATH, Lang\VHOST_EXP_LABEL, Lang\VHOST_NOT_VALID_DOMAIN, Lang\VHOST_REMOVE_ERROR, and Lang\VHOST_REMOVED.
Field Documentation
$initServerName
ActionEditVhost::$initServerName private
Definition at line 16 of file class.action.editVhost.php.
$wbBtnCancel
ActionEditVhost::$wbBtnCancel private
Definition at line 27 of file class.action.editVhost.php.
$wbBtnDelete
ActionEditVhost::$wbBtnDelete private
Definition at line 26 of file class.action.editVhost.php.
$wbBtnDocRoot
ActionEditVhost::$wbBtnDocRoot private
Definition at line 22 of file class.action.editVhost.php.
$wbBtnSave
ActionEditVhost::$wbBtnSave private
Definition at line 25 of file class.action.editVhost.php.
$wbInputDocRoot
ActionEditVhost::$wbInputDocRoot private
Definition at line 21 of file class.action.editVhost.php.
$wbInputServerName
ActionEditVhost::$wbInputServerName private
Definition at line 19 of file class.action.editVhost.php.
$wbLabelDocRoot
ActionEditVhost::$wbLabelDocRoot private
Definition at line 20 of file class.action.editVhost.php.
$wbLabelExp
ActionEditVhost::$wbLabelExp private
Definition at line 23 of file class.action.editVhost.php.
$wbLabelServerName
ActionEditVhost::$wbLabelServerName private
Definition at line 18 of file class.action.editVhost.php.
$wbProgressBar
ActionEditVhost::$wbProgressBar private
Definition at line 24 of file class.action.editVhost.php.
$wbWindow
ActionEditVhost::$wbWindow private
Definition at line 17 of file class.action.editVhost.php.
GAUGE_DELETE
const ActionEditVhost::GAUGE_DELETE = 2
Definition at line 30 of file class.action.editVhost.php.
GAUGE_SAVE
const ActionEditVhost::GAUGE_SAVE = 3
Definition at line 29 of file class.action.editVhost.php.
The documentation for this class was generated from the following file:
E:/Bearsampp-development/sandbox/core/classes/actions/class.action.editVhost.php