My Project: TplAppLaunchStartup Class Reference
TplAppLaunchStartup Class Reference
Static Public Member Functions
static getActionLaunchStartup ($launchStartup)
static process ()
Data Fields
const ACTION = 'launchStartup'
Detailed Description
Class TplAppLaunchStartup
This class provides methods to generate actions and menu items for launching the Bearsampp application at startup. It includes functionalities for creating launch startup actions and processing launch startup commands.
Definition at line 16 of file class.tpl.app.launchStartup.php.
Member Function Documentation
getActionLaunchStartup()
static TplAppLaunchStartup::getActionLaunchStartup ($launchStartup) static
Generates the action to launch the application at startup.
This method creates the action string for launching the application at startup. It includes commands to reload the application configuration. The action string is used to define what happens when the launch startup action is triggered.
Parameters
int $launchStartup The status to set for launch startup (enabled or disabled).
Returns
string The generated action string for launching the application at startup.
Definition at line 55 of file class.tpl.app.launchStartup.php.
    {
        return TplApp::getActionRun(Action::LAUNCH_STARTUP, array($launchStartup)) . PHP_EOL .
            TplAppReload::getActionReload() . PHP_EOL;
    }
References TplAppReload\getActionReload(), TplApp\getActionRun(), and Action\LAUNCH_STARTUP.
process()
static TplAppLaunchStartup::process () static
Generates the launch startup menu item and associated actions.
This method creates a menu item for launching the application at startup and defines the actions to be taken when the launch startup menu item is selected. It checks the current launch startup status and toggles it. It uses the global language object to retrieve the localized string for the launch startup action.
@global object $bearsamppLang Provides language support for retrieving language-specific values.
Returns
array The generated menu item and actions for launching the application at startup.
Definition at line 32 of file class.tpl.app.launchStartup.php.
    {
        global $bearsamppLang;
        $isLaunchStartup = Util::isLaunchStartup();
        return TplApp::getActionMulti(
            self::ACTION, array($isLaunchStartup ? Config::DISABLED : Config::ENABLED),
            array($bearsamppLang->getValue(Lang::MENU_LAUNCH_STARTUP), $isLaunchStartup ? TplAestan::GLYPH_CHECK : ''),
            false, get_called_class()
        );
    }
References $bearsamppLang, Config\DISABLED, Config\ENABLED, TplApp\getActionMulti(), TplAestan\GLYPH_CHECK, Util\isLaunchStartup(), and Lang\MENU_LAUNCH_STARTUP.
Referenced by TplApp\getSectionMenuRight().
Field Documentation
ACTION
const TplAppLaunchStartup::ACTION = 'launchStartup'
Definition at line 19 of file class.tpl.app.launchStartup.php.
The documentation for this class was generated from the following file:
E:/Bearsampp-development/sandbox/core/classes/tpls/app/class.tpl.app.launchStartup.php