Bearsampp: Tools Class Reference
Tools Class Reference
Public Member Functions
__construct ()
getAll ()
getComposer ()
getConsoleZ ()
getGhostscript ()
getGit ()
getGitGui ()
getNgrok ()
getPerl ()
getPython ()
getRuby ()
getXdc ()
getYarn ()
update ()
Data Fields
const TYPE = 'tools'
Private Attributes
$composer
$consolez
$ghostscript
$git
$ngrok
$perl
$python
$ruby
$xdc
$yarn
Detailed Description
Class Tools
This class manages various tool modules in the Bearsampp application. It provides methods to retrieve and update the configuration of these tools.
Definition at line 16 of file class.tools.php.
Constructor & Destructor Documentation
__construct()
Tools::__construct ()
Constructor for the Tools class.
Definition at line 76 of file class.tools.php.
    {
    }
Member Function Documentation
getAll()
Tools::getAll ()
Retrieves all tool instances.
Returns
array An array of all tool instances.
Definition at line 96 of file class.tools.php.
    {
        return array(
            $this->getComposer(),
            $this->getConsoleZ(),
            $this->getGhostscript(),
            $this->getGit(),
            $this->getNgrok(),
            $this->getPerl(),
            $this->getPython(),
            $this->getRuby(),
            $this->getXdc(),
            $this->getYarn(),
        );
    }
References getComposer(), getConsoleZ(), getGhostscript(), getGit(), getNgrok(), getPerl(), getPython(), getRuby(), getXdc(), and getYarn().
Referenced by update().
getComposer()
Tools::getComposer ()
Retrieves the Composer tool instance.
Returns
ToolComposer The Composer tool instance.
Definition at line 117 of file class.tools.php.
    {
        if ($this->composer == null) {
            $this->composer = new ToolComposer('composer', self::TYPE);
        }
        return $this->composer;
    }
References $composer.
Referenced by getAll().
getConsoleZ()
Tools::getConsoleZ ()
Retrieves the ConsoleZ tool instance.
Returns
ToolConsoleZ The ConsoleZ tool instance.
Definition at line 130 of file class.tools.php.
    {
        if ($this->consolez == null) {
            $this->consolez = new ToolConsoleZ('consolez', self::TYPE);
        }
        return $this->consolez;
    }
References $consolez.
Referenced by getAll().
getGhostscript()
Tools::getGhostscript ()
Retrieves the Ghostscript tool instance.
Returns
ToolGhostscript The Ghostscript tool instance.
Definition at line 143 of file class.tools.php.
    {
        if ($this->ghostscript == null) {
            $this->ghostscript = new ToolGhostscript('ghostscript', self::TYPE);
        }
        return $this->ghostscript;
    }
References $ghostscript.
Referenced by getAll().
getGit()
Tools::getGit ()
Retrieves the Git tool instance.
Returns
ToolGit The Git tool instance.
Definition at line 156 of file class.tools.php.
    {
        if ($this->git == null) {
            $this->git = new ToolGit('git', self::TYPE);
        }
        return $this->git;
    }
References $git.
Referenced by getAll().
getGitGui()
Tools::getGitGui ()
Retrieves the Git GUI tool instance.
Returns
ToolGit The Git GUI tool instance.
Definition at line 169 of file class.tools.php.
    {
        if ($this->git == null) {
            $this->git = new ToolGit('git-gui', self::TYPE);
        }
        return $this->git;
    }
References $git.
getNgrok()
Tools::getNgrok ()
Retrieves the Ngrok tool instance.
Returns
ToolNgrok The Ngrok tool instance.
Definition at line 182 of file class.tools.php.
    {
        if ($this->ngrok == null) {
            $this->ngrok = new ToolNgrok('ngrok', self::TYPE);
        }
        return $this->ngrok;
    }
References $ngrok.
Referenced by getAll().
getPerl()
Tools::getPerl ()
Retrieves the Perl tool instance.
Returns
ToolPerl The Perl tool instance.
Definition at line 195 of file class.tools.php.
    {
        if ($this->perl == null) {
            $this->perl = new ToolPerl('perl', self::TYPE);
        }
        return $this->perl;
    }
References $perl.
Referenced by getAll().
getPython()
Tools::getPython ()
Retrieves the Python tool instance.
Returns
ToolPython The Python tool instance.
Definition at line 208 of file class.tools.php.
    {
        if ($this->python == null) {
            $this->python = new ToolPython('python', self::TYPE);
        }
        return $this->python;
    }
References $python.
Referenced by getAll().
getRuby()
Tools::getRuby ()
Retrieves the Ruby tool instance.
Returns
ToolRuby The Ruby tool instance.
Definition at line 221 of file class.tools.php.
    {
        if ($this->ruby == null) {
            $this->ruby = new ToolRuby('ruby', self::TYPE);
        }
        return $this->ruby;
    }
References $ruby.
Referenced by getAll().
getXdc()
Tools::getXdc ()
Retrieves the Xdc tool instance.
Returns
ToolXdc The Xdc tool instance.
Definition at line 234 of file class.tools.php.
    {
        if ($this->xdc == null) {
            $this->xdc = new ToolXdc('xdc', self::TYPE);
        }
        return $this->xdc;
    }
References $xdc.
Referenced by getAll().
getYarn()
Tools::getYarn ()
Retrieves the Yarn tool instance.
Returns
ToolYarn The Yarn tool instance.
Definition at line 247 of file class.tools.php.
    {
        if ($this->yarn == null) {
            $this->yarn = new ToolYarn('yarn', self::TYPE);
        }
        return $this->yarn;
    }
References $yarn.
Referenced by getAll().
update()
Tools::update ()
Updates the configuration of all tools.
Definition at line 83 of file class.tools.php.
    {
        Util::logInfo('Update tools config');
        foreach ($this->getAll() as $tool) {
            $tool->update();
        }
    }
References getAll(), and Util\logInfo().
Field Documentation
$composer
Tools::$composer private
Definition at line 26 of file class.tools.php.
Referenced by getComposer().
$consolez
Tools::$consolez private
Definition at line 31 of file class.tools.php.
Referenced by getConsoleZ().
$ghostscript
Tools::$ghostscript private
Definition at line 36 of file class.tools.php.
Referenced by getGhostscript().
$git
Tools::$git private
Definition at line 41 of file class.tools.php.
Referenced by getGit(), and getGitGui().
$ngrok
Tools::$ngrok private
Definition at line 46 of file class.tools.php.
Referenced by getNgrok().
$perl
Tools::$perl private
Definition at line 51 of file class.tools.php.
Referenced by getPerl().
$python
Tools::$python private
Definition at line 56 of file class.tools.php.
Referenced by getPython().
$ruby
Tools::$ruby private
Definition at line 61 of file class.tools.php.
Referenced by getRuby().
$xdc
Tools::$xdc private
Definition at line 66 of file class.tools.php.
Referenced by getXdc().
$yarn
Tools::$yarn private
Definition at line 71 of file class.tools.php.
Referenced by getYarn().
TYPE
const Tools::TYPE = 'tools'
The type of the tools.
Definition at line 21 of file class.tools.php.
Referenced by Module\reload().
The documentation for this class was generated from the following file:
E:/Bearsampp-development/sandbox/core/classes/tools/class.tools.php