Bearsampp: Apps Class Reference
Apps Class Reference
Public Member Functions
__construct ()
getAdminer ()
getAll ()
getPhpmyadmin ()
getPhppgadmin ()
getWebgrind ()
update ()
Data Fields
const TYPE = 'apps'
Private Attributes
$adminer
$phpmyadmin
$phppgadmin
$webgrind
Detailed Description
Class Apps
This class manages various application modules within the Bearsampp application. It provides methods to retrieve and update configurations for different tools such as Adminer, PhpMyAdmin, PhpPgAdmin, and Webgrind.
Definition at line 16 of file class.apps.php.
Constructor & Destructor Documentation
__construct()
Apps::__construct ()
Constructor for the Apps class.
Definition at line 46 of file class.apps.php.
    {
    }
Member Function Documentation
getAdminer()
Apps::getAdminer ()
Retrieves the Adminer module instance.
If the instance is not already created, it initializes a new AppAdminer object.
Returns
AppAdminer The instance of the Adminer module.
Definition at line 85 of file class.apps.php.
    {
        if ($this->adminer == null) {
            $this->adminer = new AppAdminer('adminer', self::TYPE);
        }
        return $this->adminer;
    }
References $adminer.
Referenced by getAll().
getAll()
Apps::getAll ()
Retrieves all application modules.
Returns
array An array containing instances of all application modules.
Definition at line 68 of file class.apps.php.
    {
        return array(
            $this->getAdminer(),
            $this->getPhpmyadmin(),
            $this->getPhppgadmin(),
            $this->getWebgrind()
        );
    }
References getAdminer(), getPhpmyadmin(), getPhppgadmin(), and getWebgrind().
Referenced by update().
getPhpmyadmin()
Apps::getPhpmyadmin ()
Retrieves the PhpMyAdmin module instance.
If the instance is not already created, it initializes a new AppPhpmyadmin object.
Returns
AppPhpmyadmin The instance of the PhpMyAdmin module.
Definition at line 100 of file class.apps.php.
    {
        if ($this->phpmyadmin == null) {
            $this->phpmyadmin = new AppPhpmyadmin('phpmyadmin', self::TYPE);
        }
        return $this->phpmyadmin;
    }
References $phpmyadmin.
Referenced by getAll().
getPhppgadmin()
Apps::getPhppgadmin ()
Retrieves the PhpPgAdmin module instance.
If the instance is not already created, it initializes a new AppPhppgadmin object.
Returns
AppPhppgadmin The instance of the PhpPgAdmin module.
Definition at line 115 of file class.apps.php.
    {
        if ($this->phppgadmin == null) {
            $this->phppgadmin = new AppPhppgadmin('phppgadmin', self::TYPE);
        }
        return $this->phppgadmin;
    }
References $phppgadmin.
Referenced by getAll().
getWebgrind()
Apps::getWebgrind ()
Retrieves the Webgrind module instance.
If the instance is not already created, it initializes a new AppWebgrind object.
Returns
AppWebgrind The instance of the Webgrind module.
Definition at line 130 of file class.apps.php.
    {
        if ($this->webgrind == null) {
            $this->webgrind = new AppWebgrind('webgrind', self::TYPE);
        }
        return $this->webgrind;
    }
References $webgrind.
Referenced by getAll().
update()
Apps::update ()
Updates the configuration for all application modules.
This method logs the update process and iterates through all the tools to update their configurations.
Definition at line 55 of file class.apps.php.
    {
        Util::logInfo('Update apps config');
        foreach ($this->getAll() as $tool) {
            $tool->update();
        }
    }
References getAll(), and Util\logInfo().
Field Documentation
$adminer
Apps::$adminer private
Definition at line 36 of file class.apps.php.
Referenced by getAdminer().
$phpmyadmin
Apps::$phpmyadmin private
Definition at line 26 of file class.apps.php.
Referenced by getPhpmyadmin().
$phppgadmin
Apps::$phppgadmin private
Definition at line 41 of file class.apps.php.
Referenced by getPhppgadmin().
$webgrind
Apps::$webgrind private
Definition at line 31 of file class.apps.php.
Referenced by getWebgrind().
TYPE
const Apps::TYPE = 'apps'
The type of the module.
Definition at line 21 of file class.apps.php.
Referenced by Module\reload().
The documentation for this class was generated from the following file:
E:/Bearsampp-development/sandbox/core/classes/apps/class.apps.php