Bearsampp: ToolConsoleZ Class Reference
ToolConsoleZ Class Reference
Public Member Functions
__construct ($id, $type)
getCols ()
getConf ()
getExe ()
getLaunchExe ()
getRows ()
getShell ($args=null)
getTabTitleComposer ()
getTabTitleDefault ()
getTabTitleGhostscript ()
getTabTitleGit ($repoPath=null)
getTabTitleMariadb ()
getTabTitleMysql ()
getTabTitleNgrok ()
getTabTitleNodejs ()
getTabTitlePear ()
getTabTitlePerl ()
getTabTitlePostgresql ()
getTabTitlePowershell ()
getTabTitlePython ()
getTabTitleRuby ()
getTabTitleYarn ()
reload ($id=null, $type=null)
setVersion ($version)
Public Member Functions inherited from Module
__toString ()
getCurrentPath ()
getId ()
getName ()
getRelease ()
getRootPath ()
getSymlinkPath ()
getType ()
getVersion ()
getVersionList ()
isEnable ()
update ($sub=0, $showWindow=false)
Data Fields
const LOCAL_CFG_COLS = 'consolezCols'
const LOCAL_CFG_CONF = 'consolezConf'
const LOCAL_CFG_EXE = 'consolezExe'
const LOCAL_CFG_LAUNCH_EXE = 'consolezLaunchExe'
const LOCAL_CFG_ROWS = 'consolezRows'
const ROOT_CFG_VERSION = 'consolezVersion'
Data Fields inherited from Module
const BUNDLE_RELEASE = 'bundleRelease'
Private Attributes
$cols
$conf
$exe
$launchExe
$rows
Additional Inherited Members
Protected Member Functions inherited from Module
__construct ()
replace ($key, $value)
replaceAll ($params)
updateConfig ($version=null, $sub=0, $showWindow=false)
Protected Attributes inherited from Module
$bearsamppConf
$bearsamppConfRaw
$currentPath
$enable
$name
$release = 'N/A'
$rootPath
$symlinkPath
$version
Detailed Description
Class ToolConsoleZ
This class represents the ConsoleZ tool in the Bearsampp application. It extends the Module class and provides functionalities specific to ConsoleZ.
Definition at line 16 of file class.tool.consolez.php.
Constructor & Destructor Documentation
__construct()
ToolConsoleZ::__construct ($id, $type)
Constructor for the ToolConsoleZ class.
Parameters
string $id The ID of the module.
string $type The type of the module.
Definition at line 38 of file class.tool.consolez.php.
{
        Util::logInitClass($this);
        $this->reload($id, $type);
    }
References Module\$id, Module\$type, Util\logInitClass(), and reload().
Member Function Documentation
getCols()
ToolConsoleZ::getCols ()
Gets the number of columns for the ConsoleZ window.
Returns
int The number of columns.
Definition at line 149 of file class.tool.consolez.php.
{
        return $this->cols;
    }
References $cols.
getConf()
ToolConsoleZ::getConf ()
Gets the configuration file path for ConsoleZ.
Returns
string The configuration file path.
Definition at line 131 of file class.tool.consolez.php.
{
        return $this->conf;
    }
References $conf.
getExe()
ToolConsoleZ::getExe ()
Gets the executable path for ConsoleZ.
Returns
string The executable path.
Definition at line 113 of file class.tool.consolez.php.
{
        return $this->exe;
    }
References $exe.
getLaunchExe()
ToolConsoleZ::getLaunchExe ()
Gets the launch executable path for ConsoleZ.
Returns
string The launch executable path.
Definition at line 122 of file class.tool.consolez.php.
{
        return $this->launchExe;
    }
References $launchExe.
Referenced by getShell().
getRows()
ToolConsoleZ::getRows ()
Gets the number of rows for the ConsoleZ window.
Returns
int The number of rows.
Definition at line 140 of file class.tool.consolez.php.
{
        return $this->rows;
    }
References $rows.
getShell()
ToolConsoleZ::getShell ($args = null)
Gets the shell command to launch ConsoleZ.
Parameters
string | null $args Additional arguments for the shell command.
Returns
string The shell command.
Definition at line 159 of file class.tool.consolez.php.
{
        if (empty($args)) {
            return 'cmd /k &quot;' . Util::formatWindowsPath($this->launchExe) . '&quot;';
        } else {
            return 'cmd /k &quot;&quot;' . Util::formatWindowsPath($this->getLaunchExe()) . '&quot; &amp; ' . Util::formatWindowsPath($args) . '&quot;';
        }
    }
References Util\formatWindowsPath(), and getLaunchExe().
getTabTitleComposer()
ToolConsoleZ::getTabTitleComposer ()
Gets the tab title for Composer.
Returns
string The tab title for Composer.
Definition at line 256 of file class.tool.consolez.php.
{
        global $bearsamppLang, $bearsamppTools;
        return $bearsamppLang->getValue(Lang::COMPOSER) . ' ' . $bearsamppTools->getComposer()->getVersion();
    }
References $bearsamppLang, and Lang\COMPOSER.
getTabTitleDefault()
ToolConsoleZ::getTabTitleDefault ()
Gets the default tab title for ConsoleZ.
Returns
string The default tab title.
Definition at line 172 of file class.tool.consolez.php.
{
        global $bearsamppLang;
        return $bearsamppLang->getValue(Lang::CONSOLE);
    }
References $bearsamppLang, and Lang\CONSOLE.
getTabTitleGhostscript()
ToolConsoleZ::getTabTitleGhostscript ()
Gets the tab title for Ghostscript.
Returns
string The tab title for Ghostscript.
Definition at line 306 of file class.tool.consolez.php.
{
        global $bearsamppLang, $bearsamppTools;
        return $bearsamppLang->getValue(Lang::GHOSTSCRIPT) . ' ' . $bearsamppTools->getGhostscript()->getVersion();
    }
References $bearsamppLang, and Lang\GHOSTSCRIPT.
getTabTitleGit()
ToolConsoleZ::getTabTitleGit ($repoPath = null)
Gets the tab title for Git.
Parameters
string | null $repoPath The repository path.
Returns
string The tab title for Git.
Definition at line 232 of file class.tool.consolez.php.
{
        global $bearsamppLang, $bearsamppTools;
        $result = $bearsamppLang->getValue(Lang::GIT) . ' ' . $bearsamppTools->getGit()->getVersion();
        if ($repoPath != null) {
            $result .= ' - ' . basename($repoPath);
        }
        return $result;
    }
References $bearsamppLang, $result, and Lang\GIT.
getTabTitleMariadb()
ToolConsoleZ::getTabTitleMariadb ()
Gets the tab title for MariaDB.
Returns
string The tab title for MariaDB.
Definition at line 211 of file class.tool.consolez.php.
{
        global $bearsamppLang, $bearsamppBins;
        return $bearsamppLang->getValue(Lang::MARIADB) . ' ' . $bearsamppBins->getMariadb()->getVersion();
    }
References $bearsamppBins, $bearsamppLang, and Lang\MARIADB.
getTabTitleMysql()
ToolConsoleZ::getTabTitleMysql ()
Gets the tab title for MySQL.
Returns
string The tab title for MySQL.
Definition at line 201 of file class.tool.consolez.php.
{
        global $bearsamppLang, $bearsamppBins;
        return $bearsamppLang->getValue(Lang::MYSQL) . ' ' . $bearsamppBins->getMysql()->getVersion();
    }
References $bearsamppBins, $bearsamppLang, and Lang\MYSQL.
getTabTitleNgrok()
ToolConsoleZ::getTabTitleNgrok ()
Gets the tab title for Ngrok.
Returns
string The tab title for Ngrok.
Definition at line 316 of file class.tool.consolez.php.
{
        global $bearsamppLang, $bearsamppTools;
        return $bearsamppLang->getValue(Lang::NGROK) . ' ' . $bearsamppTools->getNgrok()->getVersion();
    }
References $bearsamppLang, and Lang\NGROK.
getTabTitleNodejs()
ToolConsoleZ::getTabTitleNodejs ()
Gets the tab title for Node.js.
Returns
string The tab title for Node.js.
Definition at line 246 of file class.tool.consolez.php.
{
        global $bearsamppLang, $bearsamppBins;
        return $bearsamppLang->getValue(Lang::NODEJS) . ' ' . $bearsamppBins->getNodejs()->getVersion();
    }
References $bearsamppBins, $bearsamppLang, and Lang\NODEJS.
getTabTitlePear()
ToolConsoleZ::getTabTitlePear ()
Gets the tab title for PEAR.
Returns
string The tab title for PEAR.
Definition at line 191 of file class.tool.consolez.php.
{
        global $bearsamppLang, $bearsamppBins;
        return $bearsamppLang->getValue(Lang::PEAR) . ' ' . $bearsamppBins->getPhp()->getPearVersion(true);
    }
References $bearsamppBins, $bearsamppLang, and Lang\PEAR.
getTabTitlePerl()
ToolConsoleZ::getTabTitlePerl ()
Gets the tab title for Perl.
Returns
string The tab title for Perl.
Definition at line 296 of file class.tool.consolez.php.
{
        global $bearsamppLang, $bearsamppTools;
        return $bearsamppLang->getValue(Lang::PERL) . ' ' . $bearsamppTools->getPerl()->getVersion();
    }
References $bearsamppLang, and Lang\PERL.
getTabTitlePostgresql()
ToolConsoleZ::getTabTitlePostgresql ()
Gets the tab title for PostgreSQL.
Returns
string The tab title for PostgreSQL.
Definition at line 221 of file class.tool.consolez.php.
{
        global $bearsamppLang, $bearsamppBins;
        return $bearsamppLang->getValue(Lang::POSTGRESQL) . ' ' . $bearsamppBins->getPostgresql()->getVersion();
    }
References $bearsamppBins, $bearsamppLang, and Lang\POSTGRESQL.
getTabTitlePowershell()
ToolConsoleZ::getTabTitlePowershell ()
Gets the tab title for PowerShell.
Returns
string The tab title for PowerShell.
Definition at line 182 of file class.tool.consolez.php.
{
        return 'PowerShell';
    }
getTabTitlePython()
ToolConsoleZ::getTabTitlePython ()
Gets the tab title for Python.
Returns
string The tab title for Python.
Definition at line 266 of file class.tool.consolez.php.
{
        global $bearsamppLang, $bearsamppTools;
        return $bearsamppLang->getValue(Lang::PYTHON) . ' ' . $bearsamppTools->getPython()->getVersion();
    }
References $bearsamppLang, and Lang\PYTHON.
getTabTitleRuby()
ToolConsoleZ::getTabTitleRuby ()
Gets the tab title for Ruby.
Returns
string The tab title for Ruby.
Definition at line 276 of file class.tool.consolez.php.
{
        global $bearsamppLang, $bearsamppTools;
        return $bearsamppLang->getValue(Lang::RUBY) . ' ' . $bearsamppTools->getRuby()->getVersion();
    }
References $bearsamppLang, and Lang\RUBY.
getTabTitleYarn()
ToolConsoleZ::getTabTitleYarn ()
Gets the tab title for Yarn.
Returns
string The tab title for Yarn.
Definition at line 286 of file class.tool.consolez.php.
{
        global $bearsamppLang, $bearsamppTools;
        return $bearsamppLang->getValue(Lang::YARN) . ' ' . $bearsamppTools->getYarn()->getVersion();
    }
References $bearsamppLang, and Lang\YARN.
reload()
ToolConsoleZ::reload ($id = null, $type = null)
Reloads the configuration for the ConsoleZ tool.
Parameters
string | null $id The ID of the module. If null, the current ID is used.
string | null $type The type of the module. If null, the current type is used.
Reimplemented from Module.
Definition at line 49 of file class.tool.consolez.php.
{
        global $bearsamppConfig, $bearsamppLang;
        Util::logReloadClass($this);
        $this->name = $bearsamppLang->getValue(Lang::CONSOLEZ);
        $this->version = $bearsamppConfig->getRaw(self::ROOT_CFG_VERSION);
        parent::reload($id, $type);
        if ($this->bearsamppConfRaw !== false) {
            $this->exe = $this->symlinkPath . '/' . $this->bearsamppConfRaw[self::LOCAL_CFG_EXE];
            $this->launchExe = $this->symlinkPath . '/' . $this->bearsamppConfRaw[self::LOCAL_CFG_LAUNCH_EXE];
            $this->conf = $this->symlinkPath . '/' . $this->bearsamppConfRaw[self::LOCAL_CFG_CONF];
            $this->rows = intval($this->bearsamppConfRaw[self::LOCAL_CFG_ROWS]);
            $this->cols = intval($this->bearsamppConfRaw[self::LOCAL_CFG_COLS]);
        }
        if (!$this->enable) {
            Util::logInfo($this->name . ' is not enabled!');
            return;
        }
        if (!is_dir($this->currentPath)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_FILE_NOT_FOUND), $this->name . ' ' . $this->version, $this->currentPath));
        }
        if (!is_dir($this->symlinkPath)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_FILE_NOT_FOUND), $this->name . ' ' . $this->version, $this->symlinkPath));
            return;
        }
        if (!is_file($this->bearsamppConf)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_CONF_NOT_FOUND), $this->name . ' ' . $this->version, $this->bearsamppConf));
        }
        if (!is_file($this->exe)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_EXE_NOT_FOUND), $this->name . ' ' . $this->version, $this->exe));
        }
        if (!is_file($this->launchExe)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_EXE_NOT_FOUND), $this->name . ' ' . $this->version, $this->launchExe));
        }
        if (!is_file($this->conf)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_CONF_NOT_FOUND), $this->name . ' ' . $this->version, $this->conf));
        }
        if (!is_numeric($this->rows) || $this->rows <= 0) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_INVALID_PARAMETER), self::LOCAL_CFG_ROWS, $this->rows));
        }
        if (!is_numeric($this->cols) || $this->cols <= 0) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_INVALID_PARAMETER), self::LOCAL_CFG_COLS, $this->cols));
        }
    }
References $bearsamppConfig, $bearsamppLang, Module\$id, Module\$type, Lang\CONSOLEZ, Lang\ERROR_CONF_NOT_FOUND, Lang\ERROR_EXE_NOT_FOUND, Lang\ERROR_FILE_NOT_FOUND, Lang\ERROR_INVALID_PARAMETER, LOCAL_CFG_CONF, LOCAL_CFG_EXE, LOCAL_CFG_LAUNCH_EXE, Util\logError(), Util\logInfo(), and Util\logReloadClass().
Referenced by __construct(), and setVersion().
setVersion()
ToolConsoleZ::setVersion ($version)
Sets the version of the ConsoleZ tool.
Parameters
string $version The version to set.
Reimplemented from Module.
Definition at line 101 of file class.tool.consolez.php.
{
        global $bearsamppConfig;
        $this->version = $version;
        $bearsamppConfig->replace(self::ROOT_CFG_VERSION, $version);
        $this->reload();
    }
References $bearsamppConfig, Module\$version, and reload().
Field Documentation
$cols
ToolConsoleZ::$cols private
Definition at line 30 of file class.tool.consolez.php.
Referenced by getCols().
$conf
ToolConsoleZ::$conf private
Definition at line 28 of file class.tool.consolez.php.
Referenced by getConf().
$exe
ToolConsoleZ::$exe private
Definition at line 26 of file class.tool.consolez.php.
Referenced by getExe().
$launchExe
ToolConsoleZ::$launchExe private
Definition at line 27 of file class.tool.consolez.php.
Referenced by getLaunchExe().
$rows
ToolConsoleZ::$rows private
Definition at line 29 of file class.tool.consolez.php.
Referenced by getRows().
LOCAL_CFG_COLS
const ToolConsoleZ::LOCAL_CFG_COLS = 'consolezCols'
Definition at line 24 of file class.tool.consolez.php.
LOCAL_CFG_CONF
const ToolConsoleZ::LOCAL_CFG_CONF = 'consolezConf'
Definition at line 21 of file class.tool.consolez.php.
Referenced by reload().
LOCAL_CFG_EXE
const ToolConsoleZ::LOCAL_CFG_EXE = 'consolezExe'
Definition at line 20 of file class.tool.consolez.php.
Referenced by reload().
LOCAL_CFG_LAUNCH_EXE
const ToolConsoleZ::LOCAL_CFG_LAUNCH_EXE = 'consolezLaunchExe'
Definition at line 22 of file class.tool.consolez.php.
Referenced by reload().
LOCAL_CFG_ROWS
const ToolConsoleZ::LOCAL_CFG_ROWS = 'consolezRows'
Definition at line 23 of file class.tool.consolez.php.
ROOT_CFG_VERSION
const ToolConsoleZ::ROOT_CFG_VERSION = 'consolezVersion'
Definition at line 18 of file class.tool.consolez.php.
The documentation for this class was generated from the following file:
E:/Bearsampp-development/sandbox/core/classes/tools/class.tool.consolez.php