My Project: TplAppPhp Class Reference
TplAppPhp Class Reference
Static Public Member Functions
static getActionEnablePhp ($enable)
static getActionSwitchPhpExtension ($extension, $switch)
static getActionSwitchPhpSetting ($setting, $enabled)
static getActionSwitchPhpVersion ($version)
static getMenuPhp ()
static getMenuPhpExtensions ()
static getMenuPhpSettings ()
static getMenuPhpVersions ()
static process ()
Data Fields
const ACTION_ENABLE = 'enablePhp'
const ACTION_SWITCH_EXTENSION = 'switchPhpExtension'
const ACTION_SWITCH_SETTING = 'switchPhpSetting'
const ACTION_SWITCH_VERSION = 'switchPhpVersion'
const MENU = 'php'
const MENU_EXTENSIONS = 'phpExtensions'
const MENU_SETTINGS = 'phpSettings'
const MENU_VERSIONS = 'phpVersions'
Static Private Member Functions
static getSubmenuPhpSettings ($passThr=array(), $result=array(), $settings=array(), $sectionCall=true)
Detailed Description
Definition at line 10 of file class.tpl.app.php.php.
Member Function Documentation
getActionEnablePhp()
static TplAppPhp::getActionEnablePhp ($enable) static
Generates the action to enable or disable PHP.
@global object $bearsamppBins Provides access to system binaries and their configurations.
Parameters
int $enable The enable flag (1 to enable, 0 to disable).
Returns
string The generated action string to enable or disable PHP.
Definition at line 143 of file class.tpl.app.php.php.
    {
        global $bearsamppBins;
        return TplApp::getActionRun(Action::ENABLE, array($bearsamppBins->getPhp()->getName(), $enable)) . PHP_EOL .
            TplAppReload::getActionReload();
    }
References $bearsamppBins, Action\ENABLE, TplAppReload\getActionReload(), and TplApp\getActionRun().
getActionSwitchPhpExtension()
static TplAppPhp::getActionSwitchPhpExtension ($extension, $switch) static
Generates the action to switch a PHP extension.
Parameters
string $extension The PHP extension to switch.
string $switch The current state of the extension (on or off).
Returns
string The generated action string to switch the PHP extension.
Definition at line 335 of file class.tpl.app.php.php.
    {
        $switch = $switch == ActionSwitchPhpExtension::SWITCH_OFF ? ActionSwitchPhpExtension::SWITCH_ON : ActionSwitchPhpExtension::SWITCH_OFF;
        return TplApp::getActionRun(Action::SWITCH_PHP_EXTENSION, array($extension, $switch)) . PHP_EOL .
            TplService::getActionRestart(BinApache::SERVICE_NAME) . PHP_EOL .
            TplAppReload::getActionReload() . PHP_EOL;
    }
References TplAppReload\getActionReload(), TplService\getActionRestart(), TplApp\getActionRun(), BinApache\SERVICE_NAME, ActionSwitchPhpExtension\SWITCH_OFF, ActionSwitchPhpExtension\SWITCH_ON, and Action\SWITCH_PHP_EXTENSION.
getActionSwitchPhpSetting()
static TplAppPhp::getActionSwitchPhpSetting ($setting, $enabled) static
Generates the action to switch a PHP setting.
Parameters
string $setting The PHP setting to switch.
bool $enabled The current state of the setting (true if enabled, false otherwise).
Returns
string The generated action string to switch the PHP setting.
Definition at line 289 of file class.tpl.app.php.php.
    {
        $switch = $enabled ? ActionSwitchPhpParam::SWITCH_OFF : ActionSwitchPhpParam::SWITCH_ON;
        return TplApp::getActionRun(Action::SWITCH_PHP_PARAM, array($setting, $switch)) . PHP_EOL .
            TplService::getActionRestart(BinApache::SERVICE_NAME) . PHP_EOL .
            TplAppReload::getActionReload() . PHP_EOL;
    }
References TplAppReload\getActionReload(), TplService\getActionRestart(), TplApp\getActionRun(), BinApache\SERVICE_NAME, ActionSwitchPhpParam\SWITCH_OFF, ActionSwitchPhpParam\SWITCH_ON, and Action\SWITCH_PHP_PARAM.
getActionSwitchPhpVersion()
static TplAppPhp::getActionSwitchPhpVersion ($version) static
Generates the action to switch the PHP version.
@global object $bearsamppBins Provides access to system binaries and their configurations.
Parameters
string $version The PHP version to switch to.
Returns
string The generated action string to switch the PHP version.
Definition at line 160 of file class.tpl.app.php.php.
    {
        global $bearsamppBins;
        return TplApp::getActionRun(Action::SWITCH_VERSION, array($bearsamppBins->getPhp()->getName(), $version)) . PHP_EOL .
            TplAppReload::getActionReload() . PHP_EOL;
    }
References $bearsamppBins, TplAppReload\getActionReload(), TplApp\getActionRun(), and Action\SWITCH_VERSION.
getMenuPhp()
static TplAppPhp::getMenuPhp () static
Generates the PHP menu items and actions.
@global object $bearsamppBins Provides access to system binaries and their configurations. @global object $bearsamppLang Provides language support for retrieving language-specific values.
Returns
string The generated PHP menu items and actions.
Definition at line 45 of file class.tpl.app.php.php.
    {
        global $bearsamppBins, $bearsamppLang;
        $resultItems = $resultActions = '';
        $isEnabled = $bearsamppBins->getPhp()->isEnable();
        // Download
        $resultItems .= TplAestan::getItemLink($bearsamppLang->getValue(Lang::DOWNLOAD_MORE),
            Util::getWebsiteUrl('module/php', '#releases'),
            false,
            TplAestan::GLYPH_BROWSER
        ) . PHP_EOL;
        // Enable
        $tplEnable = TplApp::getActionMulti(
            self::ACTION_ENABLE, array($isEnabled ? Config::DISABLED : Config::ENABLED),
            array($bearsamppLang->getValue(Lang::MENU_ENABLE), $isEnabled ? TplAestan::GLYPH_CHECK : ''),
            false, get_called_class()
        );
        $resultItems .= $tplEnable[TplApp::SECTION_CALL] . PHP_EOL;
        $resultActions .= $tplEnable[TplApp::SECTION_CONTENT] . PHP_EOL;
        if ($isEnabled) {
            $resultItems .= TplAestan::getItemSeparator() . PHP_EOL;
            // Versions
            $tplVersions = TplApp::getMenu($bearsamppLang->getValue(Lang::VERSIONS), self::MENU_VERSIONS, get_called_class());
            $resultItems .= $tplVersions[TplApp::SECTION_CALL] . PHP_EOL;
            $resultActions .= $tplVersions[TplApp::SECTION_CONTENT] . PHP_EOL;
            // Settings
            $tplSettings = TplApp::getMenu($bearsamppLang->getValue(Lang::SETTINGS), self::MENU_SETTINGS, get_called_class());
            $resultItems .= $tplSettings[TplApp::SECTION_CALL] . PHP_EOL;
            $resultActions .= $tplSettings[TplApp::SECTION_CONTENT] . PHP_EOL;
            // Extensions
            $tplExtensions = TplApp::getMenu($bearsamppLang->getValue(Lang::EXTENSIONS), self::MENU_EXTENSIONS, get_called_class());
            $resultItems .= $tplExtensions[TplApp::SECTION_CALL] . PHP_EOL;
            $resultActions .= $tplExtensions[TplApp::SECTION_CONTENT];
            // Conf
            $resultItems .= TplAestan::getItemNotepad(basename($bearsamppBins->getPhp()->getConf()), $bearsamppBins->getPhp()->getConf()) . PHP_EOL;
            // Errors log
            $resultItems .= TplAestan::getItemNotepad($bearsamppLang->getValue(Lang::MENU_ERROR_LOGS), $bearsamppBins->getPhp()->getErrorLog()) . PHP_EOL;
        }
        return $resultItems . PHP_EOL . $resultActions;
    }
References $bearsamppBins, $bearsamppLang, Config\DISABLED, Lang\DOWNLOAD_MORE, Config\ENABLED, Lang\EXTENSIONS, TplApp\getActionMulti(), TplAestan\getItemLink(), TplAestan\getItemNotepad(), TplAestan\getItemSeparator(), TplApp\getMenu(), Util\getWebsiteUrl(), TplAestan\GLYPH_BROWSER, TplAestan\GLYPH_CHECK, Lang\MENU_ENABLE, Lang\MENU_ERROR_LOGS, TplApp\SECTION_CALL, TplApp\SECTION_CONTENT, Lang\SETTINGS, and Lang\VERSIONS.
getMenuPhpExtensions()
static TplAppPhp::getMenuPhpExtensions () static
Generates the PHP extensions menu items and actions.
@global object $bearsamppBins Provides access to system binaries and their configurations.
Returns
string The generated PHP extensions menu items and actions.
Definition at line 304 of file class.tpl.app.php.php.
    {
        global $bearsamppBins;
        $items = '';
        $actions = '';
        foreach ($bearsamppBins->getPhp()->getExtensions() as $extension => $switch) {
            $tplSwitchPhpExtension = TplApp::getActionMulti(
                self::ACTION_SWITCH_EXTENSION, array($extension, $switch),
                array($extension, ($switch == ActionSwitchPhpExtension::SWITCH_ON ? TplAestan::GLYPH_CHECK : '')),
                false, get_called_class()
            );
            // Item
            $items .= $tplSwitchPhpExtension[TplApp::SECTION_CALL] . PHP_EOL;
            // Action
            $actions .= PHP_EOL . $tplSwitchPhpExtension[TplApp::SECTION_CONTENT];
        }
        return $items . $actions;
    }
References $bearsamppBins, TplApp\getActionMulti(), TplAestan\GLYPH_CHECK, TplApp\SECTION_CALL, TplApp\SECTION_CONTENT, and ActionSwitchPhpExtension\SWITCH_ON.
getMenuPhpSettings()
static TplAppPhp::getMenuPhpSettings () static
Generates the PHP settings menu items and actions.
@global object $bearsamppBins Provides access to system binaries and their configurations.
Returns
string The generated PHP settings menu items and actions.
Definition at line 175 of file class.tpl.app.php.php.
    {
        global $bearsamppBins;
        $menuItems = '';
        $menuActions = '';
        foreach ($bearsamppBins->getPhp()->getSettings() as $key => $value) {
            if (is_array($value)) {
                $menuItems .= 'Type: submenu; ' .
                    'Caption: "' . $key . '"; ' .
                    'SubMenu: MenuPhpSetting-' . md5($key) . '; ' .
                    'Glyph: ' . TplAestan::GLYPH_FOLDER_CLOSE . PHP_EOL;
            } else {
                $glyph = '';
                $settingEnabled = $bearsamppBins->getPhp()->isSettingActive($value);
                if (!$bearsamppBins->getPhp()->isSettingExists($value)) {
                    $glyph = TplAestan::GLYPH_WARNING;
                } elseif ($settingEnabled) {
                    $glyph = TplAestan::GLYPH_CHECK;
                }
                $tplSwitchPhpSetting = TplApp::getActionMulti(
                    self::ACTION_SWITCH_SETTING, array($value, $settingEnabled),
                    array($key, $glyph),
                    false, get_called_class()
                );
                $menuItems .= $tplSwitchPhpSetting[TplApp::SECTION_CALL] . PHP_EOL;
                $menuActions .= $tplSwitchPhpSetting[TplApp::SECTION_CONTENT];
            }
        }
        $submenusItems = '';
        $submenusActions = '';
        $submenuKeys = self::getSubmenuPhpSettings();
        foreach ($submenuKeys as $submenuKey) {
            $submenusItems .= PHP_EOL . '[MenuPhpSetting-' . md5($submenuKey) . ']' .
                PHP_EOL . self::getSubmenuPhpSettings($submenuKey);
            $submenusActions .= self::getSubmenuPhpSettings($submenuKey, array(), array(), false);
        }
        return $menuItems . $submenusItems . PHP_EOL . $menuActions . $submenusActions;
    }
References $bearsamppBins, TplApp\getActionMulti(), getSubmenuPhpSettings(), TplAestan\GLYPH_CHECK, TplAestan\GLYPH_FOLDER_CLOSE, TplAestan\GLYPH_WARNING, TplApp\SECTION_CALL, and TplApp\SECTION_CONTENT.
getMenuPhpVersions()
static TplAppPhp::getMenuPhpVersions () static
Generates the PHP versions menu items and actions.
@global object $bearsamppBins Provides access to system binaries and their configurations.
Returns
string The generated PHP versions menu items and actions.
Definition at line 103 of file class.tpl.app.php.php.
    {
        global $bearsamppBins;
        $items = '';
        $actions = '';
        foreach ($bearsamppBins->getPhp()->getVersionList() as $version) {
            $glyph = '';
            $apachePhpModule = $bearsamppBins->getPhp()->getApacheModule($bearsamppBins->getApache()->getVersion(), $version);
            if ($apachePhpModule === false) {
                $glyph = TplAestan::GLYPH_WARNING;
            } elseif ($version == $bearsamppBins->getPhp()->getVersion()) {
                $glyph = TplAestan::GLYPH_CHECK;
            }
            $tplSwitchPhpVersion = TplApp::getActionMulti(
                self::ACTION_SWITCH_VERSION, array($version),
                array($version, $glyph),
                false, get_called_class()
            );
            // Item
            $items .= $tplSwitchPhpVersion[TplApp::SECTION_CALL] . PHP_EOL;
            // Action
            $actions .= PHP_EOL . $tplSwitchPhpVersion[TplApp::SECTION_CONTENT];
        }
        return $items . $actions;
    }
References $bearsamppBins, TplApp\getActionMulti(), TplAestan\GLYPH_CHECK, TplAestan\GLYPH_WARNING, TplApp\SECTION_CALL, and TplApp\SECTION_CONTENT.
getSubmenuPhpSettings()
static TplAppPhp::getSubmenuPhpSettings ($passThr = array(), $result = array(), $settings = array(), $sectionCall = true) static private
Generates the submenu items and actions for PHP settings.
@global object $bearsamppBins Provides access to system binaries and their configurations.
Parameters
array $passThr The pass-through array for nested settings.
array $result The result array to store submenu items.
array $settings The settings array to process.
bool $sectionCall Whether to generate section calls or content.
Returns
string The generated submenu items and actions for PHP settings.
Definition at line 231 of file class.tpl.app.php.php.
    {
        global $bearsamppBins;
        $settings = empty($settings) ? $bearsamppBins->getPhp()->getSettings() : $settings;
        foreach ($settings as $key => $value) {
            if (is_array($value)) {
                if (is_array($passThr)) {
                    array_push($result, $key);
                    $result = self::getSubmenuPhpSettings($passThr, $result, $value);
                } else {
                    $result = is_array($result) ? '' : $result;
                    if ($key == $passThr) {
                        foreach ($value as $key2 => $value2) {
                            if (is_array($value2) && $sectionCall) {
                                $result .= 'Type: submenu; ' .
                                    'Caption: "' . $key2 . '"; ' .
                                    'SubMenu: MenuPhpSetting-' . md5($key2) . '; ' .
                                    'Glyph: ' . TplAestan::GLYPH_FOLDER_CLOSE . PHP_EOL;
                            } elseif (!is_array($value2)) {
                                $glyph = '';
                                $settingEnabled = $bearsamppBins->getPhp()->isSettingActive($value2);
                                if (!$bearsamppBins->getPhp()->isSettingExists($value2)) {
                                    $glyph = TplAestan::GLYPH_WARNING;
                                } elseif ($settingEnabled) {
                                    $glyph = TplAestan::GLYPH_CHECK;
                                }
                                $tplSwitchPhpSetting = TplApp::getActionMulti(
                                    self::ACTION_SWITCH_SETTING, array($value2, $settingEnabled),
                                    array($key2, $glyph),
                                    false, get_called_class()
                                );
                                if ($sectionCall) {
                                    $result .= $tplSwitchPhpSetting[TplApp::SECTION_CALL] . PHP_EOL;
                                } else {
                                    $result .= $tplSwitchPhpSetting[TplApp::SECTION_CONTENT] . PHP_EOL;
                                }
                            }
                        }
                    } else {
                        $result .= self::getSubmenuPhpSettings($passThr, null, $value, $sectionCall);
                    }
                }
            }
        }
        return $result;
    }
References $bearsamppBins, $result, TplApp\getActionMulti(), getSubmenuPhpSettings(), TplAestan\GLYPH_CHECK, TplAestan\GLYPH_FOLDER_CLOSE, TplAestan\GLYPH_WARNING, TplApp\SECTION_CALL, and TplApp\SECTION_CONTENT.
Referenced by getMenuPhpSettings(), and getSubmenuPhpSettings().
process()
static TplAppPhp::process () static
Processes the PHP menu and returns the menu items and actions.
@global object $bearsamppLang Provides language support for retrieving language-specific values. @global object $bearsamppBins Provides access to system binaries and their configurations.
Returns
array The generated menu items and actions for the PHP menu.
Definition at line 30 of file class.tpl.app.php.php.
    {
        global $bearsamppLang, $bearsamppBins;
        return TplApp::getMenuEnable($bearsamppLang->getValue(Lang::PHP), self::MENU, get_called_class(), $bearsamppBins->getPhp()->isEnable());
    }
References $bearsamppBins, $bearsamppLang, TplApp\getMenuEnable(), and Lang\PHP.
Referenced by TplApp\getSectionMenuLeft().
Field Documentation
ACTION_ENABLE
const TplAppPhp::ACTION_ENABLE = 'enablePhp'
Definition at line 17 of file class.tpl.app.php.php.
ACTION_SWITCH_EXTENSION
const TplAppPhp::ACTION_SWITCH_EXTENSION = 'switchPhpExtension'
Definition at line 20 of file class.tpl.app.php.php.
ACTION_SWITCH_SETTING
const TplAppPhp::ACTION_SWITCH_SETTING = 'switchPhpSetting'
Definition at line 19 of file class.tpl.app.php.php.
ACTION_SWITCH_VERSION
const TplAppPhp::ACTION_SWITCH_VERSION = 'switchPhpVersion'
Definition at line 18 of file class.tpl.app.php.php.
MENU
const TplAppPhp::MENU = 'php'
Definition at line 12 of file class.tpl.app.php.php.
MENU_EXTENSIONS
const TplAppPhp::MENU_EXTENSIONS = 'phpExtensions'
Definition at line 15 of file class.tpl.app.php.php.
MENU_SETTINGS
const TplAppPhp::MENU_SETTINGS = 'phpSettings'
Definition at line 14 of file class.tpl.app.php.php.
MENU_VERSIONS
const TplAppPhp::MENU_VERSIONS = 'phpVersions'
Definition at line 13 of file class.tpl.app.php.php.
The documentation for this class was generated from the following file:
E:/Bearsampp-development/sandbox/core/classes/tpls/app/class.tpl.app.php.php