Bearsampp: ToolXdc Class Reference
ToolXdc Class Reference
Public Member Functions
__construct ($id, $type)
getExe ()
reload ($id=null, $type=null)
setVersion ($version)
Public Member Functions inherited from Module
__toString ()
getCurrentPath ()
getId ()
getName ()
getRelease ()
getRootPath ()
getSymlinkPath ()
getType ()
getVersion ()
getVersionList ()
isEnable ()
update ($sub=0, $showWindow=false)
Data Fields
const LOCAL_CFG_EXE = 'xdcExe'
const ROOT_CFG_VERSION = 'xdcVersion'
Data Fields inherited from Module
const BUNDLE_RELEASE = 'bundleRelease'
Private Attributes
$exe
Additional Inherited Members
Protected Member Functions inherited from Module
__construct ()
replace ($key, $value)
replaceAll ($params)
updateConfig ($version=null, $sub=0, $showWindow=false)
Protected Attributes inherited from Module
$bearsamppConf
$bearsamppConfRaw
$currentPath
$enable
$name
$release = 'N/A'
$rootPath
$symlinkPath
$version
Detailed Description
Class ToolXdc
This class represents the XDC tool module in the Bearsampp application. It extends the abstract Module class and provides specific functionalities for managing the XDC tool, including loading configurations, setting versions, and retrieving the executable path.
Definition at line 18 of file class.tool.xdc.php.
Constructor & Destructor Documentation
__construct()
ToolXdc::__construct ($id, $type)
Constructor for the ToolXdc class.
Initializes the ToolXdc instance by logging the initialization and reloading the module configuration with the provided ID and type.
Parameters
string $id The ID of the module.
string $type The type of the module.
Definition at line 46 of file class.tool.xdc.php.
{
        Util::logInitClass($this);
        $this->reload($id, $type);
    }
References Module\$id, Module\$type, Util\logInitClass(), and reload().
Member Function Documentation
getExe()
ToolXdc::getExe ()
Gets the path to the XDC executable.
Returns
string The path to the XDC executable.
Definition at line 112 of file class.tool.xdc.php.
{
        return $this->exe;
    }
References $exe.
reload()
ToolXdc::reload ($id = null, $type = null)
Reloads the module configuration based on the provided ID and type.
This method overrides the parent reload method to include additional configurations specific to the XDC tool. It sets the name, version, and executable path, and logs errors if the module is not properly configured.
Parameters
string | null $id The ID of the module. If null, the current ID is used.
string | null $type The type of the module. If null, the current type is used.
Reimplemented from Module.
Definition at line 61 of file class.tool.xdc.php.
{
        global $bearsamppConfig, $bearsamppLang;
        Util::logReloadClass($this);
        $this->name = $bearsamppLang->getValue(Lang::XDC);
        $this->version = $bearsamppConfig->getRaw(self::ROOT_CFG_VERSION);
        parent::reload($id, $type);
        if ($this->bearsamppConfRaw !== false) {
            $this->exe = $this->symlinkPath . '/' . $this->bearsamppConfRaw[self::LOCAL_CFG_EXE];
        }
        if (!$this->enable) {
            Util::logInfo($this->name . ' is not enabled!');
            return;
        }
        if (!is_dir($this->currentPath)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_FILE_NOT_FOUND), $this->name . ' ' . $this->version, $this->currentPath));
        }
        if (!is_dir($this->symlinkPath)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_FILE_NOT_FOUND), $this->name . ' ' . $this->version, $this->symlinkPath));
            return;
        }
        if (!is_file($this->bearsamppConf)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_CONF_NOT_FOUND), $this->name . ' ' . $this->version, $this->bearsamppConf));
        }
        if (!is_file($this->exe)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_EXE_NOT_FOUND), $this->name . ' ' . $this->version, $this->exe));
        }
    }
References $bearsamppConfig, $bearsamppLang, Module\$id, Module\$type, Lang\ERROR_CONF_NOT_FOUND, Lang\ERROR_EXE_NOT_FOUND, Lang\ERROR_FILE_NOT_FOUND, LOCAL_CFG_EXE, Util\logError(), Util\logInfo(), Util\logReloadClass(), and Lang\XDC.
Referenced by __construct(), and setVersion().
setVersion()
ToolXdc::setVersion ($version)
Sets the version of the XDC tool.
This method updates the version in the configuration and reloads the module to apply the new version.
Parameters
string $version The version to set.
Reimplemented from Module.
Definition at line 100 of file class.tool.xdc.php.
{
        global $bearsamppConfig;
        $this->version = $version;
        $bearsamppConfig->replace(self::ROOT_CFG_VERSION, $version);
        $this->reload();
    }
References $bearsamppConfig, Module\$version, and reload().
Field Documentation
$exe
ToolXdc::$exe private
Definition at line 35 of file class.tool.xdc.php.
Referenced by getExe().
LOCAL_CFG_EXE
const ToolXdc::LOCAL_CFG_EXE = 'xdcExe'
Configuration key for the XDC executable in the local configuration.
Definition at line 28 of file class.tool.xdc.php.
Referenced by reload().
ROOT_CFG_VERSION
const ToolXdc::ROOT_CFG_VERSION = 'xdcVersion'
Configuration key for the XDC version in the root configuration.
Definition at line 23 of file class.tool.xdc.php.
The documentation for this class was generated from the following file:
E:/Bearsampp-development/sandbox/core/classes/tools/class.tool.xdc.php