My Project: ToolGit Class Reference
ToolGit Class Reference
Public Member Functions
__construct ($id, $type)
findRepos ($cache=true)
getBash ()
getExe ()
getRepos ()
isScanStartup ()
reload ($id=null, $type=null)
setScanStartup ($scanStartup)
setVersion ($version)
Public Member Functions inherited from Module
__toString ()
getCurrentPath ()
getId ()
getName ()
getRelease ()
getRootPath ()
getSymlinkPath ()
getType ()
getVersion ()
getVersionList ()
isEnable ()
update ($sub=0, $showWindow=false)
Data Fields
const LOCAL_CFG_BASH = 'gitBash'
const LOCAL_CFG_EXE = 'gitExe'
const LOCAL_CFG_SCAN_STARTUP = 'gitScanStartup'
const REPOS_CACHE_FILE = 'reposCache.dat'
const REPOS_FILE = 'repos.dat'
const ROOT_CFG_VERSION = 'gitVersion'
Data Fields inherited from Module
const BUNDLE_RELEASE = 'bundleRelease'
Protected Member Functions
updateConfig ($version=null, $sub=0, $showWindow=false)
Protected Member Functions inherited from Module
__construct ()
replace ($key, $value)
replaceAll ($params)
Private Attributes
$bash
$exe
$repos
$reposCacheFile
$reposFile
$scanStartup
Additional Inherited Members
Protected Attributes inherited from Module
$bearsamppConf
$bearsamppConfRaw
$currentPath
$enable
$name
$release = 'N/A'
$rootPath
$symlinkPath
$version
Detailed Description
Class ToolGit
This class represents the Git tool module in the Bearsampp application. It handles the configuration, initialization, and management of Git-related settings and repositories.
Definition at line 16 of file class.tool.git.php.
Constructor & Destructor Documentation
__construct()
ToolGit::__construct ($id, $type)
Constructs a ToolGit object and initializes the Git tool module.
Parameters
string $id The ID of the module.
string $type The type of the module.
Definition at line 41 of file class.tool.git.php.
{
        Util::logInitClass($this);
        $this->reload($id, $type);
    }
References Module\$id, Module\$type, Util\logInitClass(), and reload().
Member Function Documentation
findRepos()
ToolGit::findRepos ($cache = true)
Finds Git repositories either from cache or by scanning the directories.
Parameters
bool $cache Whether to use the cached repositories list.
Returns
array The list of found repositories.
Definition at line 145 of file class.tool.git.php.
{
        $result = array();
        if ($cache) {
            if (file_exists($this->reposCacheFile)) {
                $repos = file($this->reposCacheFile);
                foreach ($repos as $repo) {
                    array_push($result, trim($repo));
                }
            }
        } else {
            if (!empty($this->repos)) {
                foreach ($this->repos as $repo) {
                    $foundRepos = Util::findRepos($repo, $repo,'.git/config');
                    if (!empty($foundRepos)) {
                        foreach ($foundRepos as $foundRepo) {
                            array_push($result, $foundRepo);
                        }
                    }
                }
            }
            $strResult = implode(PHP_EOL, $result);
            file_put_contents($this->reposCacheFile, $strResult);
        }
        return $result;
    }
References $repos, $result, and Util\findRepos().
getBash()
ToolGit::getBash ()
Retrieves the path to the Git Bash executable.
Returns
string The path to the Git Bash executable.
Definition at line 208 of file class.tool.git.php.
{
        return $this->bash;
    }
References $bash.
Referenced by updateConfig().
getExe()
ToolGit::getExe ()
Retrieves the path to the Git executable.
Returns
string The path to the Git executable.
Definition at line 199 of file class.tool.git.php.
{
        return $this->exe;
    }
References $exe.
Referenced by updateConfig().
getRepos()
ToolGit::getRepos ()
Retrieves the list of repositories.
Returns
array The list of repositories.
Definition at line 190 of file class.tool.git.php.
{
        return $this->repos;
    }
References $repos.
isScanStartup()
ToolGit::isScanStartup ()
Checks if the Git tool module is set to scan repositories at startup.
Returns
bool True if set to scan at startup, false otherwise.
Definition at line 217 of file class.tool.git.php.
{
        return $this->scanStartup == Config::ENABLED;
    }
References Config\ENABLED.
reload()
ToolGit::reload ($id = null, $type = null)
Reloads the Git tool module configuration based on the provided ID and type.
Parameters
string | null $id The ID of the module. If null, the current ID is used.
string | null $type The type of the module. If null, the current type is used.
Reimplemented from Module.
Definition at line 52 of file class.tool.git.php.
{
        global $bearsamppRoot, $bearsamppConfig, $bearsamppLang;
        Util::logReloadClass($this);
        $this->name = $bearsamppLang->getValue(Lang::GIT);
        $this->version = $bearsamppConfig->getRaw(self::ROOT_CFG_VERSION);
        parent::reload($id, $type);
        $this->reposFile = $this->symlinkPath . '/' . self::REPOS_FILE;
        $this->reposCacheFile = $this->symlinkPath . '/' . self::REPOS_CACHE_FILE;
        if ($this->bearsamppConfRaw !== false) {
            $this->exe = $this->symlinkPath . '/' . $this->bearsamppConfRaw[self::LOCAL_CFG_EXE];
            $this->bash = $this->symlinkPath . '/' . $this->bearsamppConfRaw[self::LOCAL_CFG_BASH];
            $this->scanStartup = $this->bearsamppConfRaw[self::LOCAL_CFG_SCAN_STARTUP];
        }
        if (!$this->enable) {
            Util::logInfo($this->name . ' is not enabled!');
            return;
        }
        if (!is_dir($this->currentPath)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_FILE_NOT_FOUND), $this->name . ' ' . $this->version, $this->currentPath));
        }
        if (!is_dir($this->symlinkPath)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_FILE_NOT_FOUND), $this->name . ' ' . $this->version, $this->symlinkPath));
            return;
        }
        if (!is_file($this->bearsamppConf)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_CONF_NOT_FOUND), $this->name . ' ' . $this->version, $this->bearsamppConf));
        }
        if (!is_file($this->reposFile)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_CONF_NOT_FOUND), $this->name . ' ' . $this->version, $this->reposFile));
        }
        if (!is_file($this->exe)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_EXE_NOT_FOUND), $this->name . ' ' . $this->version, $this->exe));
        }
        if (!is_file($this->bash)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_EXE_NOT_FOUND), $this->name . ' ' . $this->version, $this->bash));
        }
        if (is_file($this->reposFile)) {
            $this->repos = explode(PHP_EOL, file_get_contents($this->reposFile));
            $rebuildRepos = array();
            foreach ($this->repos as $repo) {
                $repo = trim($repo);
                if (stripos($repo, ':') === false) {
                    $repo = $bearsamppRoot->getRootPath() . '/' . $repo;
                }
                if (is_dir($repo)) {
                    $rebuildRepos[] = Util::formatUnixPath($repo);
                } else {
                    Util::logWarning($this->name . ' repository not found: ' . $repo);
                }
            }
            $this->repos = $rebuildRepos;
        }
    }
References $bearsamppConfig, $bearsamppLang, $bearsamppRoot, Module\$id, Module\$type, Lang\ERROR_CONF_NOT_FOUND, Lang\ERROR_EXE_NOT_FOUND, Lang\ERROR_FILE_NOT_FOUND, Util\formatUnixPath(), Lang\GIT, LOCAL_CFG_BASH, LOCAL_CFG_EXE, LOCAL_CFG_SCAN_STARTUP, Util\logError(), Util\logInfo(), Util\logReloadClass(), Util\logWarning(), REPOS_CACHE_FILE, and REPOS_FILE.
Referenced by __construct(), and setVersion().
setScanStartup()
ToolGit::setScanStartup ($scanStartup)
Sets whether the Git tool module should scan repositories at startup.
Parameters
bool $scanStartup True to enable scanning at startup, false to disable.
Definition at line 226 of file class.tool.git.php.
{
        $this->scanStartup = $scanStartup;
        Util::replaceInFile($this->bearsamppConf, array(
            '/^' . self::LOCAL_CFG_SCAN_STARTUP . '/' => self::LOCAL_CFG_SCAN_STARTUP . ' = "' . $this->scanStartup . '"'
        ));
    }
References $scanStartup, and Util\replaceInFile().
setVersion()
ToolGit::setVersion ($version)
Sets the version of the Git tool module.
Parameters
string $version The version to set.
Reimplemented from Module.
Definition at line 178 of file class.tool.git.php.
{
        global $bearsamppConfig;
        $this->version = $version;
        $bearsamppConfig->replace(self::ROOT_CFG_VERSION, $version);
        $this->reload();
    }
References $bearsamppConfig, Module\$version, and reload().
updateConfig()
ToolGit::updateConfig ($version = null, $sub = 0, $showWindow = false) protected
Updates the Git tool module configuration with a specific version.
Parameters
string | null $version The version to update to. If null, the current version is used.
int $sub The sub-level for logging indentation.
bool $showWindow Whether to show a window during the update process.
Returns
bool True if the update was successful, false otherwise.
Reimplemented from Module.
Definition at line 119 of file class.tool.git.php.
{
        global $bearsamppWinbinder;
        if (!$this->enable) {
            return true;
        }
        $version = $version == null ? $this->version : $version;
        Util::logDebug(($sub > 0 ? str_repeat(' ', 2 * $sub) : '') . 'Update ' . $this->name . ' ' . $version . ' config');
        if (file_exists($this->getSymlinkPath() . '/post-install.bat')) {
            $bearsamppWinbinder->exec($this->getBash(), '--no-needs-console --hide --no-cd --command=' . $this->getSymlinkPath() . '/post-install.bat', true);
        }
        $bearsamppWinbinder->exec($this->getExe(), 'config --global core.autocrlf false', true);
        $bearsamppWinbinder->exec($this->getExe(), 'config --global core.eol lf', true);
        return true;
    }
References Module\$version, getBash(), getExe(), Module\getSymlinkPath(), and Util\logDebug().
Field Documentation
$bash
ToolGit::$bash private
Definition at line 32 of file class.tool.git.php.
Referenced by getBash().
$exe
ToolGit::$exe private
Definition at line 31 of file class.tool.git.php.
Referenced by getExe().
$repos
ToolGit::$repos private
Definition at line 29 of file class.tool.git.php.
Referenced by findRepos(), and getRepos().
$reposCacheFile
ToolGit::$reposCacheFile private
Definition at line 28 of file class.tool.git.php.
$reposFile
ToolGit::$reposFile private
Definition at line 27 of file class.tool.git.php.
$scanStartup
ToolGit::$scanStartup private
Definition at line 33 of file class.tool.git.php.
Referenced by setScanStartup().
LOCAL_CFG_BASH
const ToolGit::LOCAL_CFG_BASH = 'gitBash'
Definition at line 21 of file class.tool.git.php.
Referenced by reload().
LOCAL_CFG_EXE
const ToolGit::LOCAL_CFG_EXE = 'gitExe'
Definition at line 20 of file class.tool.git.php.
Referenced by reload().
LOCAL_CFG_SCAN_STARTUP
const ToolGit::LOCAL_CFG_SCAN_STARTUP = 'gitScanStartup'
Definition at line 22 of file class.tool.git.php.
Referenced by reload().
REPOS_CACHE_FILE
const ToolGit::REPOS_CACHE_FILE = 'reposCache.dat'
Definition at line 25 of file class.tool.git.php.
Referenced by reload().
REPOS_FILE
const ToolGit::REPOS_FILE = 'repos.dat'
Definition at line 24 of file class.tool.git.php.
Referenced by reload().
ROOT_CFG_VERSION
const ToolGit::ROOT_CFG_VERSION = 'gitVersion'
Definition at line 18 of file class.tool.git.php.
The documentation for this class was generated from the following file:
E:/Bearsampp-development/sandbox/core/classes/tools/class.tool.git.php