Bearsampp: TplAppApache Class Reference
TplAppApache Class Reference
Static Public Member Functions
static getActionAddAlias ()
static getActionAddVhost ()
static getActionChangeApachePort ()
static getActionEditAlias ($alias)
static getActionEditVhost ($vhost)
static getActionEnableApache ($enable)
static getActionInstallApacheService ()
static getActionRemoveApacheService ()
static getActionSwitchApacheModule ($module, $switch)
static getActionSwitchApacheVersion ($version)
static getMenuApache ()
static getMenuApacheAlias ()
static getMenuApacheDebug ()
static getMenuApacheModules ()
static getMenuApacheService ()
static getMenuApacheVersions ()
static getMenuApacheVhosts ()
static process ()
Data Fields
const ACTION_ADD_ALIAS = 'addAlias'
const ACTION_ADD_VHOST = 'addVhost'
const ACTION_CHANGE_PORT = 'changeApachePort'
const ACTION_EDIT_ALIAS = 'editAlias'
const ACTION_EDIT_VHOST = 'editVhost'
const ACTION_ENABLE = 'enableApache'
const ACTION_INSTALL_SERVICE = 'installApacheService'
const ACTION_REMOVE_SERVICE = 'removeApacheService'
const ACTION_SWITCH_MODULE = 'switchApacheModule'
const ACTION_SWITCH_VERSION = 'switchApacheVersion'
const MENU = 'apache'
const MENU_ALIAS = 'apacheAlias'
const MENU_DEBUG = 'apacheDebug'
const MENU_MODULES = 'apacheModules'
const MENU_SERVICE = 'apacheService'
const MENU_VERSIONS = 'apacheVersions'
const MENU_VHOSTS = 'apacheVhosts'
Detailed Description
Class TplAppApache
This class provides methods to generate menu items and actions for managing Apache services within the Bearsampp application. It includes functionalities for enabling/disabling Apache, switching versions, changing ports, managing modules, aliases, and virtual hosts.
Definition at line 17 of file class.tpl.app.apache.php.
Member Function Documentation
getActionAddAlias()
static TplAppApache::getActionAddAlias () static
Generates the action to add an Apache alias.
Returns
string The generated action to add an Apache alias.
Definition at line 433 of file class.tpl.app.apache.php.
    {
        return TplApp::getActionRun(Action::ADD_ALIAS) . PHP_EOL .
            TplAppReload::getActionReload();
    }
References Action\ADD_ALIAS, TplAppReload\getActionReload(), and TplApp\getActionRun().
getActionAddVhost()
static TplAppApache::getActionAddVhost () static
Generates the action to add an Apache Virtual Host (Vhost).
Returns
string The generated action to add an Apache Vhost.
Definition at line 498 of file class.tpl.app.apache.php.
    {
        return TplApp::getActionRun(Action::ADD_VHOST) . PHP_EOL .
            TplAppReload::getActionReload();
    }
References Action\ADD_VHOST, TplAppReload\getActionReload(), and TplApp\getActionRun().
getActionChangeApachePort()
static TplAppApache::getActionChangeApachePort () static
Generates the action to change the Apache port.
@global object $bearsamppBins Provides access to system binaries and their configurations.
Returns
string The generated action to change the Apache port.
Definition at line 271 of file class.tpl.app.apache.php.
    {
        global $bearsamppBins;
        return TplApp::getActionRun(Action::CHANGE_PORT, array($bearsamppBins->getApache()->getName())) . PHP_EOL .
            TplAppReload::getActionReload();
    }
References $bearsamppBins, Action\CHANGE_PORT, TplAppReload\getActionReload(), and TplApp\getActionRun().
getActionEditAlias()
static TplAppApache::getActionEditAlias ($alias) static
Generates the action to edit an Apache alias.
Parameters
string $alias The alias to edit.
Returns
string The generated action to edit an Apache alias.
Definition at line 445 of file class.tpl.app.apache.php.
    {
        return TplApp::getActionRun(Action::EDIT_ALIAS, array($alias)) . PHP_EOL .
            TplAppReload::getActionReload();
    }
References Action\EDIT_ALIAS, TplAppReload\getActionReload(), and TplApp\getActionRun().
getActionEditVhost()
static TplAppApache::getActionEditVhost ($vhost) static
Generates the action to edit an Apache Virtual Host (Vhost).
Parameters
string $vhost The Vhost to edit.
Returns
string The generated action to edit an Apache Vhost.
Definition at line 510 of file class.tpl.app.apache.php.
    {
        return TplApp::getActionRun(Action::EDIT_VHOST, array($vhost)) . PHP_EOL .
            TplAppReload::getActionReload();
    }
References Action\EDIT_VHOST, TplAppReload\getActionReload(), and TplApp\getActionRun().
getActionEnableApache()
static TplAppApache::getActionEnableApache ($enable) static
Generates the action to enable or disable Apache.
@global object $bearsamppBins Provides access to system binaries and their configurations.
Parameters
int $enable The flag to enable (1) or disable (0) Apache.
Returns
string The generated action to enable or disable Apache.
Definition at line 181 of file class.tpl.app.apache.php.
    {
        global $bearsamppBins;
        return TplApp::getActionRun(Action::ENABLE, array($bearsamppBins->getApache()->getName(), $enable)) . PHP_EOL .
            TplAppReload::getActionReload();
    }
References $bearsamppBins, Action\ENABLE, TplAppReload\getActionReload(), and TplApp\getActionRun().
getActionInstallApacheService()
static TplAppApache::getActionInstallApacheService () static
Generates the action to install the Apache service.
Returns
string The generated action to install the Apache service.
Definition at line 284 of file class.tpl.app.apache.php.
    {
        return TplApp::getActionRun(Action::SERVICE, array(BinApache::SERVICE_NAME, ActionService::INSTALL)) . PHP_EOL .
            TplAppReload::getActionReload();
    }
References TplAppReload\getActionReload(), TplApp\getActionRun(), ActionService\INSTALL, Action\SERVICE, and BinApache\SERVICE_NAME.
getActionRemoveApacheService()
static TplAppApache::getActionRemoveApacheService () static
Generates the action to remove the Apache service.
Returns
string The generated action to remove the Apache service.
Definition at line 295 of file class.tpl.app.apache.php.
    {
        return TplApp::getActionRun(Action::SERVICE, array(BinApache::SERVICE_NAME, ActionService::REMOVE)) . PHP_EOL .
            TplAppReload::getActionReload();
    }
References TplAppReload\getActionReload(), TplApp\getActionRun(), ActionService\REMOVE, Action\SERVICE, and BinApache\SERVICE_NAME.
getActionSwitchApacheModule()
static TplAppApache::getActionSwitchApacheModule ($module, $switch) static
Generates the action to switch an Apache module on or off.
Parameters
string $module The module to switch.
string $switch The current switch state of the module.
Returns
string The generated action to switch the Apache module.
Definition at line 379 of file class.tpl.app.apache.php.
    {
        $switch = $switch == ActionSwitchApacheModule::SWITCH_OFF ? ActionSwitchApacheModule::SWITCH_ON : ActionSwitchApacheModule::SWITCH_OFF;
        return TplApp::getActionRun(Action::SWITCH_APACHE_MODULE, array($module, $switch)) . PHP_EOL .
            TplService::getActionRestart(BinApache::SERVICE_NAME) . PHP_EOL .
            TplAppReload::getActionReload() . PHP_EOL;
    }
References TplAppReload\getActionReload(), TplService\getActionRestart(), TplApp\getActionRun(), BinApache\SERVICE_NAME, Action\SWITCH_APACHE_MODULE, ActionSwitchApacheModule\SWITCH_OFF, and ActionSwitchApacheModule\SWITCH_ON.
getActionSwitchApacheVersion()
static TplAppApache::getActionSwitchApacheVersion ($version) static
Generates the action to switch the Apache version.
@global object $bearsamppBins Provides access to system binaries and their configurations.
Parameters
string $version The version to switch to.
Returns
string The generated action to switch the Apache version.
Definition at line 197 of file class.tpl.app.apache.php.
    {
        global $bearsamppBins;
        return TplApp::getActionRun(Action::SWITCH_VERSION, array($bearsamppBins->getApache()->getName(), $version)) . PHP_EOL .
            TplAppReload::getActionReload() . PHP_EOL;
    }
References $bearsamppBins, TplAppReload\getActionReload(), TplApp\getActionRun(), and Action\SWITCH_VERSION.
getMenuApache()
static TplAppApache::getMenuApache () static
Generates the Apache menu with options for versions, service, debug, modules, aliases, and virtual hosts.
@global object $bearsamppBins Provides access to system binaries and their configurations. @global object $bearsamppLang Provides language support for retrieving language-specific values.
Returns
string The generated menu items and actions for Apache.
Definition at line 62 of file class.tpl.app.apache.php.
    {
        global $bearsamppBins, $bearsamppLang;
        $resultItems = $resultActions = '';
        $isEnabled = $bearsamppBins->getApache()->isEnable();
        // Download
        $resultItems .= TplAestan::getItemLink(
            $bearsamppLang->getValue(Lang::DOWNLOAD_MORE),
            Util::getWebsiteUrl('module/apache', '#releases'),
            false,
            TplAestan::GLYPH_BROWSER
        ) . PHP_EOL;
        // Enable
        $tplEnable = TplApp::getActionMulti(
            self::ACTION_ENABLE, array($isEnabled ? Config::DISABLED : Config::ENABLED),
            array($bearsamppLang->getValue(Lang::MENU_ENABLE), $isEnabled ? TplAestan::GLYPH_CHECK : ''),
            false, get_called_class()
        );
        $resultItems .= $tplEnable[TplApp::SECTION_CALL] . PHP_EOL;
        $resultActions .= $tplEnable[TplApp::SECTION_CONTENT] . PHP_EOL;
        if ($isEnabled) {
            $resultItems .= TplAestan::getItemSeparator() . PHP_EOL;
            // Versions
            $tplVersions = TplApp::getMenu($bearsamppLang->getValue(Lang::VERSIONS), self::MENU_VERSIONS, get_called_class());
            $resultItems .= $tplVersions[TplApp::SECTION_CALL] . PHP_EOL;
            $resultActions .= $tplVersions[TplApp::SECTION_CONTENT] . PHP_EOL;
            // Service
            $tplService = TplApp::getMenu($bearsamppLang->getValue(Lang::SERVICE), self::MENU_SERVICE, get_called_class());
            $resultItems .= $tplService[TplApp::SECTION_CALL] . PHP_EOL;
            $resultActions .= $tplService[TplApp::SECTION_CONTENT] . PHP_EOL;
            // Debug
            $tplDebug = TplApp::getMenu($bearsamppLang->getValue(Lang::DEBUG), self::MENU_DEBUG, get_called_class());
            $resultItems .= $tplDebug[TplApp::SECTION_CALL] . PHP_EOL;
            $resultActions .= $tplDebug[TplApp::SECTION_CONTENT] . PHP_EOL;
            // Modules
            $tplModules = TplApp::getMenu($bearsamppLang->getValue(Lang::MODULES), self::MENU_MODULES, get_called_class());
            $resultItems .= $tplModules[TplApp::SECTION_CALL] . PHP_EOL;
            $resultActions .= $tplModules[TplApp::SECTION_CONTENT] . PHP_EOL;
            // Alias
            $tplAlias = TplApp::getMenu($bearsamppLang->getValue(Lang::ALIASES), self::MENU_ALIAS, get_called_class());
            $resultItems .= $tplAlias[TplApp::SECTION_CALL] . PHP_EOL;
            $resultActions .= $tplAlias[TplApp::SECTION_CONTENT] . PHP_EOL;
            // Vhosts
            $tplVhosts = TplApp::getMenu($bearsamppLang->getValue(Lang::VIRTUAL_HOSTS), self::MENU_VHOSTS, get_called_class());
            $resultItems .= $tplVhosts[TplApp::SECTION_CALL] . PHP_EOL;
            $resultActions .= $tplVhosts[TplApp::SECTION_CONTENT];
            // Conf
            $resultItems .= TplAestan::getItemNotepad(basename($bearsamppBins->getApache()->getConf()), $bearsamppBins->getApache()->getConf()) . PHP_EOL;
            // Access log
            $resultItems .= TplAestan::getItemNotepad($bearsamppLang->getValue(Lang::MENU_ACCESS_LOGS), $bearsamppBins->getApache()->getAccessLog()) . PHP_EOL;
            // Rewrite log
            $resultItems .= TplAestan::getItemNotepad($bearsamppLang->getValue(Lang::MENU_REWRITE_LOGS), $bearsamppBins->getApache()->getRewriteLog()) . PHP_EOL;
            // Error log
            $resultItems .= TplAestan::getItemNotepad($bearsamppLang->getValue(Lang::MENU_ERROR_LOGS), $bearsamppBins->getApache()->getErrorLog()) . PHP_EOL;
        }
        return $resultItems . PHP_EOL . $resultActions;
    }
References $bearsamppBins, $bearsamppLang, Lang\ALIASES, Lang\DEBUG, Config\DISABLED, Lang\DOWNLOAD_MORE, Config\ENABLED, TplApp\getActionMulti(), TplAestan\getItemLink(), TplAestan\getItemNotepad(), TplAestan\getItemSeparator(), TplApp\getMenu(), Util\getWebsiteUrl(), TplAestan\GLYPH_BROWSER, TplAestan\GLYPH_CHECK, Lang\MENU_ACCESS_LOGS, Lang\MENU_ENABLE, Lang\MENU_ERROR_LOGS, Lang\MENU_REWRITE_LOGS, Lang\MODULES, TplApp\SECTION_CALL, TplApp\SECTION_CONTENT, Lang\SERVICE, Lang\VERSIONS, and Lang\VIRTUAL_HOSTS.
getMenuApacheAlias()
static TplAppApache::getMenuApacheAlias () static
Generates the Apache Alias menu with options to add and edit aliases.
@global object $bearsamppLang Provides language support for retrieving language-specific values. @global object $bearsamppBins Provides access to system binaries and their configurations.
Returns
string The generated menu items and actions for Apache aliases.
Definition at line 394 of file class.tpl.app.apache.php.
    {
        global $bearsamppLang, $bearsamppBins;
        $tplAddAlias = TplApp::getActionMulti(
            self::ACTION_ADD_ALIAS, null,
            array($bearsamppLang->getValue(Lang::MENU_ADD_ALIAS), TplAestan::GLYPH_ADD),
            false, get_called_class()
        );
        // Items
        $items = $tplAddAlias[TplApp::SECTION_CALL] . PHP_EOL .
            TplAestan::getItemSeparator() . PHP_EOL;
        // Actions
        $actions = PHP_EOL . $tplAddAlias[TplApp::SECTION_CONTENT];
        foreach ($bearsamppBins->getApache()->getAlias() as $alias) {
            $tplEditAlias = TplApp::getActionMulti(
                self::ACTION_EDIT_ALIAS, array($alias),
                array(sprintf($bearsamppLang->getValue(Lang::MENU_EDIT_ALIAS), $alias), TplAestan::GLYPH_FILE),
                false, get_called_class()
            );
            // Items
            $items .= $tplEditAlias[TplApp::SECTION_CALL] . PHP_EOL;
            // Actions
            $actions .= PHP_EOL . PHP_EOL . $tplEditAlias[TplApp::SECTION_CONTENT];
        }
        return $items . $actions;
    }
References $bearsamppBins, $bearsamppLang, TplApp\getActionMulti(), TplAestan\getItemSeparator(), TplAestan\GLYPH_ADD, TplAestan\GLYPH_FILE, Lang\MENU_ADD_ALIAS, Lang\MENU_EDIT_ALIAS, TplApp\SECTION_CALL, and TplApp\SECTION_CONTENT.
getMenuApacheDebug()
static TplAppApache::getMenuApacheDebug () static
Generates the Apache debug menu with options to run various debug commands.
@global object $bearsamppLang Provides language support for retrieving language-specific values.
Returns
string The generated menu items and actions for Apache debug.
Definition at line 308 of file class.tpl.app.apache.php.
    {
        global $bearsamppLang;
        return TplApp::getActionRun(
            Action::DEBUG_APACHE, array(BinApache::CMD_VERSION_NUMBER),
            array($bearsamppLang->getValue(Lang::DEBUG_APACHE_VERSION_NUMBER), TplAestan::GLYPH_DEBUG)
        ) . PHP_EOL .
        TplApp::getActionRun(
            Action::DEBUG_APACHE, array(BinApache::CMD_COMPILE_SETTINGS),
            array($bearsamppLang->getValue(Lang::DEBUG_APACHE_COMPILE_SETTINGS), TplAestan::GLYPH_DEBUG)
        ) . PHP_EOL .
        TplApp::getActionRun(
            Action::DEBUG_APACHE, array(BinApache::CMD_COMPILED_MODULES),
            array($bearsamppLang->getValue(Lang::DEBUG_APACHE_COMPILED_MODULES), TplAestan::GLYPH_DEBUG)
        ) . PHP_EOL .
        TplApp::getActionRun(
            Action::DEBUG_APACHE, array(BinApache::CMD_CONFIG_DIRECTIVES),
            array($bearsamppLang->getValue(Lang::DEBUG_APACHE_CONFIG_DIRECTIVES), TplAestan::GLYPH_DEBUG)
        ) . PHP_EOL .
        TplApp::getActionRun(
            Action::DEBUG_APACHE, array(BinApache::CMD_VHOSTS_SETTINGS),
            array($bearsamppLang->getValue(Lang::DEBUG_APACHE_VHOSTS_SETTINGS), TplAestan::GLYPH_DEBUG)
        ) . PHP_EOL .
        TplApp::getActionRun(
            Action::DEBUG_APACHE, array(BinApache::CMD_LOADED_MODULES),
            array($bearsamppLang->getValue(Lang::DEBUG_APACHE_LOADED_MODULES), TplAestan::GLYPH_DEBUG)
        ) . PHP_EOL .
        TplApp::getActionRun(
            Action::DEBUG_APACHE, array(BinApache::CMD_SYNTAX_CHECK),
            array($bearsamppLang->getValue(Lang::DEBUG_APACHE_SYNTAX_CHECK), TplAestan::GLYPH_DEBUG)
        ) . PHP_EOL;
    }
References $bearsamppLang, BinApache\CMD_COMPILE_SETTINGS, BinApache\CMD_COMPILED_MODULES, BinApache\CMD_CONFIG_DIRECTIVES, BinApache\CMD_LOADED_MODULES, BinApache\CMD_SYNTAX_CHECK, BinApache\CMD_VERSION_NUMBER, BinApache\CMD_VHOSTS_SETTINGS, Action\DEBUG_APACHE, Lang\DEBUG_APACHE_COMPILE_SETTINGS, Lang\DEBUG_APACHE_COMPILED_MODULES, Lang\DEBUG_APACHE_CONFIG_DIRECTIVES, Lang\DEBUG_APACHE_LOADED_MODULES, Lang\DEBUG_APACHE_SYNTAX_CHECK, Lang\DEBUG_APACHE_VERSION_NUMBER, Lang\DEBUG_APACHE_VHOSTS_SETTINGS, TplApp\getActionRun(), and TplAestan\GLYPH_DEBUG.
getMenuApacheModules()
static TplAppApache::getMenuApacheModules () static
Generates the Apache modules menu with options to switch modules on or off.
@global object $bearsamppBins Provides access to system binaries and their configurations.
Returns
string The generated menu items and actions for Apache modules.
Definition at line 349 of file class.tpl.app.apache.php.
    {
        global $bearsamppBins;
        $items = '';
        $actions = '';
        foreach ($bearsamppBins->getApache()->getModulesFromConf() as $module => $switch) {
            $tplSwitchApacheModule = TplApp::getActionMulti(
                self::ACTION_SWITCH_MODULE, array($module, $switch),
                array($module, ($switch == ActionSwitchApacheModule::SWITCH_ON ? TplAestan::GLYPH_CHECK : '')),
                false, get_called_class()
            );
            // Item
            $items .= $tplSwitchApacheModule[TplApp::SECTION_CALL] . PHP_EOL;
            // Action
            $actions .= PHP_EOL . $tplSwitchApacheModule[TplApp::SECTION_CONTENT];
        }
        return $items . $actions;
    }
References $bearsamppBins, TplApp\getActionMulti(), TplAestan\GLYPH_CHECK, TplApp\SECTION_CALL, TplApp\SECTION_CONTENT, and ActionSwitchApacheModule\SWITCH_ON.
getMenuApacheService()
static TplAppApache::getMenuApacheService () static
Generates the Apache service menu with options to start, stop, restart, and manage the service.
@global object $bearsamppRoot Provides access to the root path of the application. @global object $bearsamppLang Provides language support for retrieving language-specific values. @global object $bearsamppBins Provides access to system binaries and their configurations.
Returns
string The generated menu items and actions for Apache service.
Definition at line 213 of file class.tpl.app.apache.php.
    {
        global $bearsamppRoot, $bearsamppLang, $bearsamppBins;
        $tplChangePort = TplApp::getActionMulti(
            self::ACTION_CHANGE_PORT, null,
            array($bearsamppLang->getValue(Lang::MENU_CHANGE_PORT), TplAestan::GLYPH_NETWORK),
            false, get_called_class()
        );
        $result = TplAestan::getItemActionServiceStart($bearsamppBins->getApache()->getService()->getName()) . PHP_EOL .
            TplAestan::getItemActionServiceStop($bearsamppBins->getApache()->getService()->getName()) . PHP_EOL .
            TplAestan::getItemActionServiceRestart($bearsamppBins->getApache()->getService()->getName()) . PHP_EOL .
            TplAestan::getItemSeparator() . PHP_EOL .
            TplApp::getActionRun(
                Action::CHECK_PORT, array($bearsamppBins->getApache()->getName(), $bearsamppBins->getApache()->getPort()),
                array(sprintf($bearsamppLang->getValue(Lang::MENU_CHECK_PORT), $bearsamppBins->getApache()->getPort()), TplAestan::GLYPH_LIGHT)
            ) . PHP_EOL .
            TplApp::getActionRun(
                Action::CHECK_PORT, array($bearsamppBins->getApache()->getName(), $bearsamppBins->getApache()->getSslPort(), true),
                array(sprintf($bearsamppLang->getValue(Lang::MENU_CHECK_PORT), $bearsamppBins->getApache()->getSslPort()) . ' (SSL)', TplAestan::GLYPH_RED_LIGHT)
            ) . PHP_EOL .
            $tplChangePort[TplApp::SECTION_CALL] . PHP_EOL .
            TplAestan::getItemNotepad($bearsamppLang->getValue(Lang::MENU_UPDATE_ENV_PATH), $bearsamppRoot->getRootPath() . '/nssmEnvPaths.dat') . PHP_EOL;
        $isInstalled = $bearsamppBins->getApache()->getService()->isInstalled();
        if (!$isInstalled) {
            $tplInstallService = TplApp::getActionMulti(
                self::ACTION_INSTALL_SERVICE, null,
                array($bearsamppLang->getValue(Lang::MENU_INSTALL_SERVICE), TplAestan::GLYPH_SERVICE_INSTALL),
                $isInstalled, get_called_class()
            );
            $result .= $tplInstallService[TplApp::SECTION_CALL] . PHP_EOL . PHP_EOL .
                $tplInstallService[TplApp::SECTION_CONTENT] . PHP_EOL;
        } else {
            $tplRemoveService = TplApp::getActionMulti(
                self::ACTION_REMOVE_SERVICE, null,
                array($bearsamppLang->getValue(Lang::MENU_REMOVE_SERVICE), TplAestan::GLYPH_SERVICE_REMOVE),
                !$isInstalled, get_called_class()
            );
            $result .= $tplRemoveService[TplApp::SECTION_CALL] . PHP_EOL . PHP_EOL .
                $tplRemoveService[TplApp::SECTION_CONTENT] . PHP_EOL;
        }
        $result .= $tplChangePort[TplApp::SECTION_CONTENT] . PHP_EOL;
        return $result;
    }
References $bearsamppBins, $bearsamppLang, $bearsamppRoot, $result, Action\CHECK_PORT, TplApp\getActionMulti(), TplApp\getActionRun(), TplAestan\getItemActionServiceRestart(), TplAestan\getItemActionServiceStart(), TplAestan\getItemActionServiceStop(), TplAestan\getItemNotepad(), TplAestan\getItemSeparator(), TplAestan\GLYPH_LIGHT, TplAestan\GLYPH_NETWORK, TplAestan\GLYPH_RED_LIGHT, TplAestan\GLYPH_SERVICE_INSTALL, TplAestan\GLYPH_SERVICE_REMOVE, Lang\MENU_CHANGE_PORT, Lang\MENU_CHECK_PORT, Lang\MENU_INSTALL_SERVICE, Lang\MENU_REMOVE_SERVICE, Lang\MENU_UPDATE_ENV_PATH, TplApp\SECTION_CALL, and TplApp\SECTION_CONTENT.
getMenuApacheVersions()
static TplAppApache::getMenuApacheVersions () static
Generates the Apache versions menu with options to switch between different versions.
@global object $bearsamppBins Provides access to system binaries and their configurations.
Returns
string The generated menu items and actions for Apache versions.
Definition at line 142 of file class.tpl.app.apache.php.
    {
        global $bearsamppBins;
        $items = '';
        $actions = '';
        foreach ($bearsamppBins->getApache()->getVersionList() as $version) {
            $glyph = '';
            $apachePhpModule = $bearsamppBins->getPhp()->getApacheModule($version);
            if ($apachePhpModule === false) {
                $glyph = TplAestan::GLYPH_WARNING;
            } elseif ($version == $bearsamppBins->getApache()->getVersion()) {
                $glyph = TplAestan::GLYPH_CHECK;
            }
            $tplSwitchApacheVersion = TplApp::getActionMulti(
                self::ACTION_SWITCH_VERSION, array($version),
                array($version, $glyph),
                false, get_called_class()
            );
            // Item
            $items .= $tplSwitchApacheVersion[TplApp::SECTION_CALL] . PHP_EOL;
            // Action
            $actions .= PHP_EOL . $tplSwitchApacheVersion[TplApp::SECTION_CONTENT];
        }
        return $items . $actions;
    }
References $bearsamppBins, TplApp\getActionMulti(), TplAestan\GLYPH_CHECK, TplAestan\GLYPH_WARNING, TplApp\SECTION_CALL, and TplApp\SECTION_CONTENT.
getMenuApacheVhosts()
static TplAppApache::getMenuApacheVhosts () static
Generates the Apache Virtual Hosts (Vhosts) menu with options to add and edit Vhosts.
@global object $bearsamppLang Provides language support for retrieving language-specific values. @global object $bearsamppBins Provides access to system binaries and their configurations.
Returns
string The generated menu items and actions for Apache Vhosts.
Definition at line 459 of file class.tpl.app.apache.php.
    {
        global $bearsamppLang, $bearsamppBins;
        $tplAddVhost = TplApp::getActionMulti(
            self::ACTION_ADD_VHOST, null,
            array($bearsamppLang->getValue(Lang::MENU_ADD_VHOST), TplAestan::GLYPH_ADD),
            false, get_called_class()
        );
        // Items
        $items = $tplAddVhost[TplApp::SECTION_CALL] . PHP_EOL .
            TplAestan::getItemSeparator() . PHP_EOL;
        // Actions
        $actions = PHP_EOL . $tplAddVhost[TplApp::SECTION_CONTENT];
        foreach ($bearsamppBins->getApache()->getVhosts() as $vhost) {
            $tplEditVhost = TplApp::getActionMulti(
                self::ACTION_EDIT_VHOST, array($vhost),
                array(sprintf($bearsamppLang->getValue(Lang::MENU_EDIT_VHOST), $vhost), TplAestan::GLYPH_FILE),
                false, get_called_class()
            );
            // Items
            $items .= $tplEditVhost[TplApp::SECTION_CALL] . PHP_EOL;
            // Actions
            $actions .= PHP_EOL . PHP_EOL . $tplEditVhost[TplApp::SECTION_CONTENT];
        }
        return $items . $actions;
    }
References $bearsamppBins, $bearsamppLang, TplApp\getActionMulti(), TplAestan\getItemSeparator(), TplAestan\GLYPH_ADD, TplAestan\GLYPH_FILE, Lang\MENU_ADD_VHOST, Lang\MENU_EDIT_VHOST, TplApp\SECTION_CALL, and TplApp\SECTION_CONTENT.
process()
static TplAppApache::process () static
Generates the main Apache menu with options to enable/disable Apache and access submenus.
@global object $bearsamppLang Provides language support for retrieving language-specific values. @global object $bearsamppBins Provides access to system binaries and their configurations.
Returns
string The generated menu items and actions for Apache.
Definition at line 47 of file class.tpl.app.apache.php.
    {
        global $bearsamppLang, $bearsamppBins;
        return TplApp::getMenuEnable($bearsamppLang->getValue(Lang::APACHE), self::MENU, get_called_class(), $bearsamppBins->getApache()->isEnable());
    }
References $bearsamppBins, $bearsamppLang, Lang\APACHE, and TplApp\getMenuEnable().
Referenced by TplApp\getSectionMenuLeft().
Field Documentation
ACTION_ADD_ALIAS
const TplAppApache::ACTION_ADD_ALIAS = 'addAlias'
Definition at line 34 of file class.tpl.app.apache.php.
ACTION_ADD_VHOST
const TplAppApache::ACTION_ADD_VHOST = 'addVhost'
Definition at line 36 of file class.tpl.app.apache.php.
ACTION_CHANGE_PORT
const TplAppApache::ACTION_CHANGE_PORT = 'changeApachePort'
Definition at line 30 of file class.tpl.app.apache.php.
ACTION_EDIT_ALIAS
const TplAppApache::ACTION_EDIT_ALIAS = 'editAlias'
Definition at line 35 of file class.tpl.app.apache.php.
ACTION_EDIT_VHOST
const TplAppApache::ACTION_EDIT_VHOST = 'editVhost'
Definition at line 37 of file class.tpl.app.apache.php.
ACTION_ENABLE
const TplAppApache::ACTION_ENABLE = 'enableApache'
Definition at line 28 of file class.tpl.app.apache.php.
ACTION_INSTALL_SERVICE
const TplAppApache::ACTION_INSTALL_SERVICE = 'installApacheService'
Definition at line 31 of file class.tpl.app.apache.php.
ACTION_REMOVE_SERVICE
const TplAppApache::ACTION_REMOVE_SERVICE = 'removeApacheService'
Definition at line 32 of file class.tpl.app.apache.php.
ACTION_SWITCH_MODULE
const TplAppApache::ACTION_SWITCH_MODULE = 'switchApacheModule'
Definition at line 33 of file class.tpl.app.apache.php.
ACTION_SWITCH_VERSION
const TplAppApache::ACTION_SWITCH_VERSION = 'switchApacheVersion'
Definition at line 29 of file class.tpl.app.apache.php.
MENU
const TplAppApache::MENU = 'apache'
Definition at line 20 of file class.tpl.app.apache.php.
MENU_ALIAS
const TplAppApache::MENU_ALIAS = 'apacheAlias'
Definition at line 25 of file class.tpl.app.apache.php.
MENU_DEBUG
const TplAppApache::MENU_DEBUG = 'apacheDebug'
Definition at line 23 of file class.tpl.app.apache.php.
MENU_MODULES
const TplAppApache::MENU_MODULES = 'apacheModules'
Definition at line 24 of file class.tpl.app.apache.php.
MENU_SERVICE
const TplAppApache::MENU_SERVICE = 'apacheService'
Definition at line 22 of file class.tpl.app.apache.php.
MENU_VERSIONS
const TplAppApache::MENU_VERSIONS = 'apacheVersions'
Definition at line 21 of file class.tpl.app.apache.php.
MENU_VHOSTS
const TplAppApache::MENU_VHOSTS = 'apacheVhosts'
Definition at line 26 of file class.tpl.app.apache.php.
The documentation for this class was generated from the following file:
E:/Bearsampp-development/sandbox/core/classes/tpls/app/class.tpl.app.apache.php