My Project: Registry Class Reference
Registry Class Reference
Public Member Functions
__construct ()
deleteValue ($key, $subkey, $entry)
exists ($key, $subkey, $entry=null)
getLatestError ()
getValue ($key, $subkey, $entry=null)
setExpandStringValue ($key, $subkey, $entry, $value)
setStringValue ($key, $subkey, $entry, $value)
Data Fields
const APP_BINS_REG_ENTRY = 'BEARSAMPP_BINS'
const APP_PATH_REG_ENTRY = 'BEARSAMPP_PATH'
const END_PROCESS_STR = 'FINISHED!'
const ENV_KEY = 'SYSTEM\CurrentControlSet\Control\Session Manager\Environment'
const HKEY_CLASSES_ROOT = 'HKCR'
const HKEY_CURRENT_USER = 'HKCU'
const HKEY_LOCAL_MACHINE = 'HKLM'
const HKEY_USERS = 'HKEY_USERS'
const PROCESSOR_REG_ENTRY = 'Identifier'
const PROCESSOR_REG_SUBKEY = 'HARDWARE\DESCRIPTION\System\CentralProcessor\0'
const REG_BINARY = 'REG_BINARY'
const REG_DWORD = 'REG_DWORD'
const REG_ERROR_ENTRY = 'REG_ERROR_ENTRY'
const REG_ERROR_SET = 'REG_ERROR_SET'
const REG_EXPAND_SZ = 'REG_EXPAND_SZ'
const REG_MULTI_SZ = 'REG_MULTI_SZ'
const REG_NO_ERROR = 'REG_NO_ERROR'
const REG_SZ = 'REG_SZ'
const SYSPATH_REG_ENTRY = 'Path'
Private Member Functions
setValue ($key, $subkey, $entry, $value, $type)
writeLog ($log)
Private Attributes
$latestError
Detailed Description
Class Registry
This class provides methods to interact with the Windows Registry using VBScript. It includes functionalities to check the existence of registry keys, get and set values, and delete registry entries. The class also logs operations and errors.
Definition at line 17 of file class.registry.php.
Constructor & Destructor Documentation
__construct()
Registry::__construct ()
Registry constructor. Initializes the Registry class and logs the initialization.
Definition at line 57 of file class.registry.php.
    {
        Util::logInitClass($this);
        $this->latestError = null;
    }
References Util\logInitClass().
Member Function Documentation
deleteValue()
Registry::deleteValue ($key, $subkey, $entry)
Deletes a registry entry.
Parameters
string $key The root key (e.g., HKEY_LOCAL_MACHINE).
string $subkey The subkey path.
string $entry The entry name.
Returns
bool True if the entry was deleted successfully, false otherwise.
Definition at line 213 of file class.registry.php.
    {
        $this->writeLog('delete');
        return $this->setValue($key, $subkey, $entry, null, 'DeleteValue');
    }
References setValue(), and writeLog().
exists()
Registry::exists ($key, $subkey, $entry = null)
Checks if a registry key or entry exists.
Parameters
string $key The root key (e.g., HKEY_LOCAL_MACHINE).
string $subkey The subkey path.
string | null $entry The entry name (optional).
Returns
bool True if the key or entry exists, false otherwise.
Definition at line 82 of file class.registry.php.
    {
        $basename = 'registryExists';
        $resultFile = Vbs::getResultFile($basename);
        $scriptContent = 'On Error Resume Next' . PHP_EOL;
        $scriptContent .= 'Err.Clear' . PHP_EOL . PHP_EOL;
        $scriptContent .= 'Dim objShell, objFso, objFile, outFile, bExists' . PHP_EOL . PHP_EOL;
        $scriptContent .= 'outFile = "' . $resultFile . '"' . PHP_EOL;
        $scriptContent .= 'Set objShell = WScript.CreateObject("WScript.Shell")' . PHP_EOL;
        $scriptContent .= 'Set objFso = CreateObject("Scripting.FileSystemObject")' . PHP_EOL;
        $scriptContent .= 'Set objFile = objFso.CreateTextFile(outFile, True)' . PHP_EOL . PHP_EOL;
        $scriptContent .= 'strKey = "' . $key . '\\' . $subkey . '\\' . $entry . '"' . PHP_EOL;
        $scriptContent .= 'entryValue = objShell.RegRead(strKey)' . PHP_EOL;
        $scriptContent .= 'If Err.Number <> 0 Then' . PHP_EOL;
        $scriptContent .= '    If Right(strKey,1) = "\" Then' . PHP_EOL;
        $scriptContent .= '        If Instr(1, Err.Description, ssig, 1) <> 0 Then' . PHP_EOL;
        $scriptContent .= '            bExists = true' . PHP_EOL;
        $scriptContent .= '        Else' . PHP_EOL;
        $scriptContent .= '            bExists = false' . PHP_EOL;
        $scriptContent .= '        End If' . PHP_EOL;
        $scriptContent .= '    Else' . PHP_EOL;
        $scriptContent .= '        bExists = false' . PHP_EOL;
        $scriptContent .= '    End If' . PHP_EOL;
        $scriptContent .= '    Err.Clear' . PHP_EOL;
        $scriptContent .= 'Else' . PHP_EOL;
        $scriptContent .= '    bExists = true' . PHP_EOL;
        $scriptContent .= 'End If' . PHP_EOL . PHP_EOL;
        $scriptContent .= 'On Error Goto 0' . PHP_EOL;
        $scriptContent .= 'If bExists = vbFalse Then' . PHP_EOL;
        $scriptContent .= '    objFile.Write "0"' . PHP_EOL;
        $scriptContent .= 'Else' . PHP_EOL;
        $scriptContent .= '    objFile.Write "1"' . PHP_EOL;
        $scriptContent .= 'End If' . PHP_EOL;
        $scriptContent .= 'objFile.Close' . PHP_EOL;
        $result = Vbs::exec($basename, $resultFile, $scriptContent);
        $result = isset($result[0]) ? $result[0] : null;
        $this->writeLog('Exists ' . $key . '\\' . $subkey . '\\' . $entry);
        $this->writeLog('-> result: ' . $result);
        return !empty($result) && intval($result) == 1;
    }
References $result, Vbs\exec(), Vbs\getResultFile(), and writeLog().
getLatestError()
Registry::getLatestError ()
Retrieves the latest error message.
Returns
string|null The latest error message, or null if no error occurred.
Definition at line 311 of file class.registry.php.
    {
        return $this->latestError;
    }
References $latestError.
getValue()
Registry::getValue ($key, $subkey, $entry = null)
Retrieves the value of a registry entry.
Parameters
string $key The root key (e.g., HKEY_LOCAL_MACHINE).
string $subkey The subkey path.
string | null $entry The entry name (optional).
Returns
mixed The value of the registry entry, or false on error.
Definition at line 139 of file class.registry.php.
    {
        global $bearsamppLang;
        $basename = 'registryGetValue';
        $resultFile = Vbs::getResultFile($basename);
        $this->latestError = null;
        $scriptContent = 'On Error Resume Next' . PHP_EOL;
        $scriptContent .= 'Err.Clear' . PHP_EOL . PHP_EOL;
        $scriptContent .= 'Dim objShell, objFso, objFile, outFile, entryValue' . PHP_EOL . PHP_EOL;
        $scriptContent .= 'outFile = "' . $resultFile . '"' . PHP_EOL;
        $scriptContent .= 'Set objShell = WScript.CreateObject("WScript.Shell")' . PHP_EOL;
        $scriptContent .= 'Set objFso = CreateObject("Scripting.FileSystemObject")' . PHP_EOL;
        $scriptContent .= 'Set objFile = objFso.CreateTextFile(outFile, True)' . PHP_EOL . PHP_EOL;
        $scriptContent .= 'entryValue = objShell.RegRead("' . $key . '\\' . $subkey . '\\' . $entry . '")' . PHP_EOL;
        $scriptContent .= 'If Err.Number <> 0 Then' . PHP_EOL;
        $scriptContent .= '    objFile.Write "' . self::REG_ERROR_ENTRY . '" & Err.Number & ": " & Err.Description' . PHP_EOL;
        $scriptContent .= 'Else' . PHP_EOL;
        $scriptContent .= '    objFile.Write entryValue' . PHP_EOL;
        $scriptContent .= 'End If' . PHP_EOL;
        $scriptContent .= 'objFile.Close' . PHP_EOL;
        $result = Vbs::exec($basename, $resultFile, $scriptContent);
        $result = isset($result[0]) ? $result[0] : null;
        $this->writeLog('GetValue ' . $key . '\\' . $subkey . '\\' . $entry);
        $this->writeLog('-> result: ' . $result);
        if (Util::startWith($result, self::REG_ERROR_ENTRY)) {
            $this->latestError = $bearsamppLang->getValue(Lang::ERROR) . ' ' . str_replace(self::REG_ERROR_ENTRY, '', $result);
            return false;
        }
        return $result;
    }
References $bearsamppLang, $result, Lang\ERROR, Vbs\exec(), Vbs\getResultFile(), Util\startWith(), and writeLog().
setExpandStringValue()
Registry::setExpandStringValue ($key, $subkey, $entry, $value)
Sets an expanded string value in the registry.
Parameters
string $key The root key (e.g., HKEY_LOCAL_MACHINE).
string $subkey The subkey path.
string $entry The entry name.
string $value The value to set.
Returns
bool True if the value was set successfully, false otherwise.
Definition at line 200 of file class.registry.php.
    {
        return $this->setValue($key, $subkey, $entry, $value, 'SetExpandedStringValue');
    }
References setValue().
setStringValue()
Registry::setStringValue ($key, $subkey, $entry, $value)
Sets a string value in the registry.
Parameters
string $key The root key (e.g., HKEY_LOCAL_MACHINE).
string $subkey The subkey path.
string $entry The entry name.
string $value The value to set.
Returns
bool True if the value was set successfully, false otherwise.
Definition at line 186 of file class.registry.php.
    {
        return $this->setValue($key, $subkey, $entry, $value, 'SetStringValue');
    }
References setValue().
setValue()
Registry::setValue ($key, $subkey, $entry, $value, $type) private
Sets a value in the registry.
Parameters
string $key The root key (e.g., HKEY_LOCAL_MACHINE).
string $subkey The subkey path.
string $entry The entry name.
string | null $value The value to set (optional).
string $type The type of value to set (e.g., SetStringValue).
Returns
bool True if the value was set successfully, false otherwise.
Definition at line 229 of file class.registry.php.
    {
        global $bearsamppLang;
        $basename = 'registrySetValue';
        $resultFile = Vbs::getResultFile($basename);
        $this->latestError = null;
        $strKey = $key;
        if ($key == self::HKEY_CLASSES_ROOT) {
            $key = '&H80000000';
        } elseif ($key == self::HKEY_CURRENT_USER) {
            $key = '&H80000001';
        } elseif ($key == self::HKEY_LOCAL_MACHINE) {
            $key = '&H80000002';
        } elseif ($key == self::HKEY_LOCAL_MACHINE) {
            $key = '&H80000003';
        }
        $scriptContent = 'On Error Resume Next' . PHP_EOL;
        $scriptContent .= 'Err.Clear' . PHP_EOL . PHP_EOL;
        $scriptContent .= 'Const HKEY = ' . $key . PHP_EOL . PHP_EOL;
        $scriptContent .= 'Dim objShell, objRegistry, objFso, objFile, outFile, entryValue, newValue' . PHP_EOL . PHP_EOL;
        $scriptContent .= 'newValue = "' . (!empty($value) ? str_replace('"', '""', $value) : '') . '"' . PHP_EOL;
        $scriptContent .= 'outFile = "' . $resultFile . '"' . PHP_EOL;
        $scriptContent .= 'Set objShell = WScript.CreateObject("WScript.Shell")' . PHP_EOL;
        $scriptContent .= 'Set objRegistry = GetObject("winmgmts://./root/default:StdRegProv")' . PHP_EOL;
        $scriptContent .= 'Set objFso = CreateObject("Scripting.FileSystemObject")' . PHP_EOL;
        $scriptContent .= 'Set objFile = objFso.CreateTextFile(outFile, True)' . PHP_EOL . PHP_EOL;
        if (!empty($value)) {
            $scriptContent .= 'objRegistry.' . $type . ' HKEY, "' . $subkey . '", "' . $entry . '", newValue' . PHP_EOL;
        } elseif (!empty($entry)) {
            $scriptContent .= 'objRegistry.' . $type . ' HKEY, "' . $subkey . '", "' . $entry . '"' . PHP_EOL;
        } else {
            $scriptContent .= 'objRegistry.' . $type . ' HKEY, "' . $subkey . '"' . PHP_EOL;
        }
        $scriptContent .= 'If Err.Number <> 0 Then' . PHP_EOL;
        $scriptContent .= '    objFile.Write "' . self::REG_ERROR_ENTRY . '" & Err.Number & ": " & Err.Description' . PHP_EOL;
        $scriptContent .= 'Else' . PHP_EOL;
        if (!empty($value)) {
            $scriptContent .= '    entryValue = objShell.RegRead("' . $strKey . '\\' . $subkey . '\\' . $entry . '")' . PHP_EOL;
            $scriptContent .= '    If entryValue = newValue Then' . PHP_EOL;
            $scriptContent .= '        objFile.Write "' . self::REG_NO_ERROR . '"' . PHP_EOL;
            $scriptContent .= '    Else' . PHP_EOL;
            $scriptContent .= '        objFile.Write "' . self::REG_ERROR_SET . '" & newValue' . PHP_EOL;
            $scriptContent .= '    End If' . PHP_EOL;
        } else {
            $scriptContent .= '    objFile.Write "' . self::REG_NO_ERROR . '"' . PHP_EOL;
        }
        $scriptContent .= 'End If' . PHP_EOL;
        $scriptContent .= 'objFile.Close' . PHP_EOL;
        $result = Vbs::exec($basename, $resultFile, $scriptContent);
        $result = isset($result[0]) ? $result[0] : null;
        if ($subkey == self::ENV_KEY) {
            Batch::refreshEnvVars();
        }
        $this->writeLog('SetValue ' . $strKey . '\\' . $subkey . '\\' . $entry);
        $this->writeLog('-> value: ' . $value);
        $this->writeLog('-> result: ' . $result);
        if (Util::startWith($result, self::REG_ERROR_SET)) {
            $this->latestError = sprintf($bearsamppLang->getValue(Lang::REGISTRY_SET_ERROR_TEXT), str_replace(self::REG_ERROR_SET, '', $result));
            return false;
        } elseif (Util::startWith($result, self::REG_ERROR_ENTRY)) {
            $this->latestError = $bearsamppLang->getValue(Lang::ERROR) . ' ' . str_replace(self::REG_ERROR_ENTRY, '', $result);
            return false;
        }
        return $result == self::REG_NO_ERROR;
    }
References $bearsamppLang, $result, Lang\ERROR, Vbs\exec(), Vbs\getResultFile(), Batch\refreshEnvVars(), REG_NO_ERROR, Lang\REGISTRY_SET_ERROR_TEXT, Util\startWith(), and writeLog().
Referenced by deleteValue(), setExpandStringValue(), and setStringValue().
writeLog()
Registry::writeLog ($log) private
Writes a log entry.
Parameters
string $log The log message to write.
Definition at line 68 of file class.registry.php.
    {
        global $bearsamppRoot;
        Util::logDebug($log, $bearsamppRoot->getRegistryLogFilePath());
    }
References $bearsamppRoot, and Util\logDebug().
Referenced by deleteValue(), exists(), getValue(), and setValue().
Field Documentation
$latestError
Registry::$latestError private
Definition at line 51 of file class.registry.php.
Referenced by getLatestError().
APP_BINS_REG_ENTRY
const Registry::APP_BINS_REG_ENTRY = 'BEARSAMPP_BINS'
Definition at line 39 of file class.registry.php.
Referenced by ActionStartup\checkBinsRegKey(), ActionStartup\checkSystemPathRegKey(), Util\getAppBinsRegKey(), ActionSwitchVersion\processWindow(), and Util\setAppBinsRegKey().
APP_PATH_REG_ENTRY
const Registry::APP_PATH_REG_ENTRY = 'BEARSAMPP_PATH'
Definition at line 42 of file class.registry.php.
Referenced by ActionStartup\checkPathRegKey(), Util\getAppPathRegKey(), Batch\refreshEnvVars(), and Util\setAppPathRegKey().
END_PROCESS_STR
const Registry::END_PROCESS_STR = 'FINISHED!'
Definition at line 19 of file class.registry.php.
ENV_KEY
const Registry::ENV_KEY = 'SYSTEM\CurrentControlSet\Control\Session Manager\Environment'
Definition at line 36 of file class.registry.php.
Referenced by Util\getAppBinsRegKey(), Util\getAppPathRegKey(), Util\getSysPathRegKey(), Util\setAppBinsRegKey(), Util\setAppPathRegKey(), and Util\setSysPathRegKey().
HKEY_CLASSES_ROOT
const Registry::HKEY_CLASSES_ROOT = 'HKCR'
Definition at line 21 of file class.registry.php.
HKEY_CURRENT_USER
const Registry::HKEY_CURRENT_USER = 'HKCU'
Definition at line 22 of file class.registry.php.
HKEY_LOCAL_MACHINE
const Registry::HKEY_LOCAL_MACHINE = 'HKLM'
Definition at line 23 of file class.registry.php.
Referenced by ActionStartup\cleanOldBehaviors(), Util\getAppBinsRegKey(), Util\getAppPathRegKey(), Util\getProcessorRegKey(), Util\getSysPathRegKey(), Nssm\infos(), BinMailhog\rebuildConf(), BinMailpit\rebuildConf(), BinMemcached\rebuildConf(), BinXlight\rebuildConf(), Util\setAppBinsRegKey(), Util\setAppPathRegKey(), and Util\setSysPathRegKey().
HKEY_USERS
const Registry::HKEY_USERS = 'HKEY_USERS'
Definition at line 24 of file class.registry.php.
PROCESSOR_REG_ENTRY
const Registry::PROCESSOR_REG_ENTRY = 'Identifier'
Definition at line 49 of file class.registry.php.
Referenced by Util\getProcessorRegKey().
PROCESSOR_REG_SUBKEY
const Registry::PROCESSOR_REG_SUBKEY = 'HARDWARE\DESCRIPTION\System\CentralProcessor\0'
Definition at line 48 of file class.registry.php.
Referenced by Util\getProcessorRegKey().
REG_BINARY
const Registry::REG_BINARY = 'REG_BINARY'
Definition at line 28 of file class.registry.php.
REG_DWORD
const Registry::REG_DWORD = 'REG_DWORD'
Definition at line 29 of file class.registry.php.
REG_ERROR_ENTRY
const Registry::REG_ERROR_ENTRY = 'REG_ERROR_ENTRY'
Definition at line 32 of file class.registry.php.
REG_ERROR_SET
const Registry::REG_ERROR_SET = 'REG_ERROR_SET'
Definition at line 33 of file class.registry.php.
REG_EXPAND_SZ
const Registry::REG_EXPAND_SZ = 'REG_EXPAND_SZ'
Definition at line 27 of file class.registry.php.
REG_MULTI_SZ
const Registry::REG_MULTI_SZ = 'REG_MULTI_SZ'
Definition at line 30 of file class.registry.php.
REG_NO_ERROR
const Registry::REG_NO_ERROR = 'REG_NO_ERROR'
Definition at line 34 of file class.registry.php.
Referenced by setValue().
REG_SZ
const Registry::REG_SZ = 'REG_SZ'
Definition at line 26 of file class.registry.php.
SYSPATH_REG_ENTRY
const Registry::SYSPATH_REG_ENTRY = 'Path'
Definition at line 45 of file class.registry.php.
Referenced by ActionStartup\checkSystemPathRegKey(), Util\getSysPathRegKey(), and Util\setSysPathRegKey().
The documentation for this class was generated from the following file:
E:/Bearsampp-development/sandbox/core/classes/class.registry.php