Bearsampp: BinApache Class Reference
BinApache Class Reference
Public Member Functions
__construct ($id, $type)
changePort ($port, $checkUsed=false, $wbProgressBar=null)
checkPort ($port, $ssl=false, $showWindow=false)
getAccessLog ()
getAlias ()
getAliasContent ($name, $dest)
getCmdLineOutput ($cmd)
getConf ()
getErrorLog ()
getExe ()
getModules ()
getModulesFromConf ()
getModulesLoaded ()
getModulesPath ()
getOpensslExe ()
getPort ()
getRewriteLog ()
getService ()
getSslConf ()
getSslPort ()
getVhostContent ($serverName, $documentRoot)
getVhosts ()
getVhostsUrl ()
getWwwDirectories ()
refreshAlias ($putOnline)
refreshConf ($putOnline)
refreshVhosts ($putOnline)
reload ($id=null, $type=null)
setEnable ($enabled, $showWindow=false)
setPort ($port)
setSslPort ($sslPort)
setVersion ($version)
switchVersion ($version, $showWindow=false)
Public Member Functions inherited from Module
__toString ()
getCurrentPath ()
getId ()
getName ()
getRelease ()
getRootPath ()
getSymlinkPath ()
getType ()
getVersion ()
getVersionList ()
isEnable ()
update ($sub=0, $showWindow=false)
Data Fields
const CMD_COMPILE_SETTINGS = '-V'
const CMD_COMPILED_MODULES = '-l'
const CMD_CONFIG_DIRECTIVES = '-L'
const CMD_LOADED_MODULES = '-M'
const CMD_SYNTAX_CHECK = '-t'
const CMD_VERSION_NUMBER = '-v'
const CMD_VHOSTS_SETTINGS = '-S'
const LOCAL_CFG_CONF = 'apacheConf'
const LOCAL_CFG_EXE = 'apacheExe'
const LOCAL_CFG_OPENSSL_EXE = 'apacheOpensslExe'
const LOCAL_CFG_PORT = 'apachePort'
const LOCAL_CFG_SSL_PORT = 'apacheSslPort'
const ROOT_CFG_ENABLE = 'apacheEnable'
const ROOT_CFG_VERSION = 'apacheVersion'
const SERVICE_NAME = 'bearsamppapache'
const SERVICE_PARAMS = '-k runservice'
const TAG_END_SWITCHONLINE = '# END switchOnline tag - Do not replace!'
const TAG_START_SWITCHONLINE = '# START switchOnline tag - Do not replace!'
Data Fields inherited from Module
const BUNDLE_RELEASE = 'bundleRelease'
Protected Member Functions
replaceAll ($params)
updateConfig ($version=null, $sub=0, $showWindow=false)
Protected Member Functions inherited from Module
__construct ()
replace ($key, $value)
Private Member Functions
getModulesFromFolder ()
getOfflineContent ($version=null)
getOnlineContent ($version=null)
getRequiredContent ($version=null)
Private Attributes
$accessLog
$conf
$errorLog
$exe
$modulesPath
$opensslExe
$port
$rewriteLog
$service
$sslConf
$sslPort
Additional Inherited Members
Protected Attributes inherited from Module
$bearsamppConf
$bearsamppConfRaw
$currentPath
$enable
$name
$release = 'N/A'
$rootPath
$symlinkPath
$version
Detailed Description
Class BinApache
This class represents the Apache module in the Bearsampp application. It provides functionalities to manage Apache services, configurations, and modules.
Definition at line 16 of file class.bin.apache.php.
Constructor & Destructor Documentation
__construct()
BinApache::__construct ($id, $type)
Constructor for the BinApache class.
Parameters
string $id The ID of the module.
string $type The type of the module.
Definition at line 60 of file class.bin.apache.php.
    {
        Util::logInitClass( $this );
        $this->reload( $id, $type );
    }
References Module\$id, Module\$type, Util\logInitClass(), and reload().
Member Function Documentation
changePort()
BinApache::changePort ($port, $checkUsed = false, $wbProgressBar = null)
Changes the port for the Apache service.
Parameters
int $port The new port number.
bool $checkUsed Whether to check if the port is already in use.
mixed $wbProgressBar The progress bar object for updating progress.
Returns
bool|string True if the port was changed successfully, or the process using the port if it is in use.
Definition at line 190 of file class.bin.apache.php.
    {
        global $bearsamppWinbinder;
        if ( !Util::isValidPort( $port ) ) {
            Util::logError( $this->getName() . ' port not valid: ' . $port );
            return false;
        }
        $port = intval( $port );
        $bearsamppWinbinder->incrProgressBar( $wbProgressBar );
        $isPortInUse = Util::isPortInUse( $port );
        if ( !$checkUsed || $isPortInUse === false ) {
            // bearsampp.conf
            $this->setPort( $port );
            $bearsamppWinbinder->incrProgressBar( $wbProgressBar );
            // conf
            $this->update();
            $bearsamppWinbinder->incrProgressBar( $wbProgressBar );
            return true;
        }
        Util::logDebug( $this->getName() . ' port in used: ' . $port . ' - ' . $isPortInUse );
        return $isPortInUse;
    }
References $port, Module\getName(), Util\isPortInUse(), Util\isValidPort(), Util\logDebug(), Util\logError(), setPort(), and Module\update().
checkPort()
BinApache::checkPort ($port, $ssl = false, $showWindow = false)
Checks if a specific port is being used by the Apache service.
Parameters
int $port The port number to check.
bool $ssl Whether to check for SSL.
bool $showWindow Whether to show a window with the result.
Returns
bool True if the port is used by Apache, false otherwise.
Definition at line 230 of file class.bin.apache.php.
    {
        global $bearsamppLang, $bearsamppWinbinder, $bearsamppHomepage;
        $boxTitle = sprintf( $bearsamppLang->getValue( Lang::CHECK_PORT_TITLE ), $this->getName(), $port );
        if ( !Util::isValidPort( $port ) ) {
            Util::logError( $this->getName() . ' port not valid: ' . $port );
            return false;
        }
        $headers = Util::getHttpHeaders( 'http' . ($ssl ? 's' : '') . '://localhost:' . $port . '/' . $bearsamppHomepage->getResourcesPath() . '/ping.php' );
        if ( !empty( $headers ) ) {
            foreach ( $headers as $row ) {
                if ( Util::startWith( $row, 'Server: ' ) || Util::startWith( $row, 'server: ' ) ) {
                    Util::logDebug( $this->getName() . ' port ' . $port . ' is used by: ' . $this->getName() . ' ' . str_replace( 'Server: ', '', str_replace( 'server: ', '', trim( $row ) ) ) );
                    if ( $showWindow ) {
                        $bearsamppWinbinder->messageBoxInfo(
                            sprintf( $bearsamppLang->getValue( Lang::PORT_USED_BY ), $port, str_replace( 'Server: ', '', str_replace( 'server: ', '', trim( $row ) ) ) ),
                            $boxTitle
                        );
                    }
                    return true;
                }
            }
            Util::logDebug( $this->getName() . ' port ' . $port . ' is used by another application' );
            if ( $showWindow ) {
                $bearsamppWinbinder->messageBoxWarning(
                    sprintf( $bearsamppLang->getValue( Lang::PORT_NOT_USED_BY ), $port ),
                    $boxTitle
                );
            }
        }
        else {
            Util::logDebug( $this->getName() . ' port ' . $port . ' is not used' );
            if ( $showWindow ) {
                $bearsamppWinbinder->messageBoxError(
                    sprintf( $bearsamppLang->getValue( Lang::PORT_NOT_USED ), $port ),
                    $boxTitle
                );
            }
        }
        return false;
    }
References $bearsamppHomepage, $bearsamppLang, $port, Lang\CHECK_PORT_TITLE, Util\getHttpHeaders(), Module\getName(), Util\isValidPort(), Util\logDebug(), Util\logError(), Lang\PORT_NOT_USED, Lang\PORT_NOT_USED_BY, Lang\PORT_USED_BY, and Util\startWith().
getAccessLog()
BinApache::getAccessLog ()
Gets the access log file path.
Returns
string The access log file path.
Definition at line 970 of file class.bin.apache.php.
    {
        return $this->accessLog;
    }
References $accessLog.
getAlias()
BinApache::getAlias ()
Retrieves the list of alias configurations.
Returns
array The list of alias configurations.
Definition at line 505 of file class.bin.apache.php.
    {
        global $bearsamppRoot;
        $result = array();
        $handle = @opendir( $bearsamppRoot->getAliasPath() );
        if ( !$handle ) {
            return $result;
        }
        while ( false !== ($file = readdir( $handle )) ) {
            if ( $file != '.' && $file != '..' && Util::endWith( $file, '.conf' ) ) {
                $result[] = str_replace( '.conf', '', $file );
            }
        }
        closedir( $handle );
        ksort( $result );
        return $result;
    }
References $bearsamppRoot, $result, and Util\endWith().
Referenced by refreshAlias().
getAliasContent()
BinApache::getAliasContent ($name, $dest)
Generates the alias content for the configuration file.
Parameters
string $name The name of the alias.
string $dest The destination path of the alias.
Returns
string The alias content.
Definition at line 708 of file class.bin.apache.php.
    {
        $dest = Util::formatUnixPath( $dest );
        return 'Alias /' . $name . ' "' . $dest . '"' . PHP_EOL . PHP_EOL .
            '<Directory "' . $dest . '">' . PHP_EOL .
            '    Options Indexes FollowSymLinks MultiViews' . PHP_EOL .
            '    AllowOverride all' . PHP_EOL .
            $this->getRequiredContent() . PHP_EOL .
            '</Directory>' . PHP_EOL;
    }
References Module\$name, Util\formatUnixPath(), and getRequiredContent().
getCmdLineOutput()
BinApache::getCmdLineOutput ($cmd)
Executes a command line and retrieves the output.
Parameters
string $cmd The command to execute.
Returns
array The output of the command.
Definition at line 618 of file class.bin.apache.php.
    {
        $result = array(
            'syntaxOk' => false,
            'content'  => null,
        );
        if ( file_exists( $this->getExe() ) ) {
            $tmpResult = Batch::exec( 'apacheGetCmdLineOutput', '"' . $this->getExe() . '" ' . $cmd );
            if ( $tmpResult !== false && is_array( $tmpResult ) ) {
                $result['syntaxOk'] = trim( $tmpResult[count( $tmpResult ) - 1] ) == 'Syntax OK';
                if ( $result['syntaxOk'] ) {
                    unset( $tmpResult[count( $tmpResult ) - 1] );
                }
                $result['content'] = implode( PHP_EOL, $tmpResult );
            }
        }
        return $result;
    }
References $result, Batch\exec(), and getExe().
getConf()
BinApache::getConf ()
Gets the configuration file path.
Returns
string The configuration file path.
Definition at line 1010 of file class.bin.apache.php.
    {
        return $this->conf;
    }
References $conf.
Referenced by getModulesFromConf(), refreshConf(), and updateConfig().
getErrorLog()
BinApache::getErrorLog ()
Gets the error log file path.
Returns
string The error log file path.
Definition at line 990 of file class.bin.apache.php.
    {
        return $this->errorLog;
    }
References $errorLog.
getExe()
BinApache::getExe ()
Gets the executable file path.
Returns
string The executable file path.
Definition at line 1000 of file class.bin.apache.php.
    {
        return $this->exe;
    }
References $exe.
Referenced by getCmdLineOutput().
getModules()
BinApache::getModules ()
Retrieves the list of modules by merging the modules from the folder and the configuration file.
Returns
array The list of modules.
Definition at line 407 of file class.bin.apache.php.
    {
        $fromFolder = $this->getModulesFromFolder();
        $fromConf   = $this->getModulesFromConf();
        $result     = array_merge( $fromFolder, $fromConf );
        ksort( $result );
        return $result;
    }
References $result, getModulesFromConf(), and getModulesFromFolder().
getModulesFromConf()
BinApache::getModulesFromConf ()
Retrieves the list of modules from the configuration file.
Returns
array The list of modules from the configuration file.
Definition at line 422 of file class.bin.apache.php.
    {
        $result = array();
        if ( !$this->enable ) {
            return $result;
        }
        $confContent = file( $this->getConf() );
        foreach ( $confContent as $row ) {
            $modMatch = array();
            if ( preg_match( '/^(#)?LoadModule\s*([a-z0-9_-]+)\s*"?(.*)"?/i', $row, $modMatch ) ) {
                $name = $modMatch[2];
                //$path = $modMatch[3];
                if ( !Util::startWith( $name, 'php' ) ) {
                    if ( $modMatch[1] == '#' ) {
                        $result[$name] = ActionSwitchApacheModule::SWITCH_OFF;
                    }
                    else {
                        $result[$name] = ActionSwitchApacheModule::SWITCH_ON;
                    }
                }
            }
        }
        ksort( $result );
        return $result;
    }
References Module\$name, $result, getConf(), Util\startWith(), ActionSwitchApacheModule\SWITCH_OFF, and ActionSwitchApacheModule\SWITCH_ON.
Referenced by getModules(), and getModulesLoaded().
getModulesFromFolder()
BinApache::getModulesFromFolder () private
Retrieves the list of modules from the modules folder.
Returns
array The list of modules from the modules folder.
Definition at line 474 of file class.bin.apache.php.
    {
        $result = array();
        if ( !$this->enable ) {
            return $result;
        }
        $handle = @opendir( $this->getModulesPath() );
        if ( !$handle ) {
            return $result;
        }
        while ( false !== ($file = readdir( $handle )) ) {
            if ( $file != '.' && $file != '..' && Util::startWith( $file, 'mod_' ) && (Util::endWith( $file, '.so' ) || Util::endWith( $file, '.dll' )) ) {
                $name          = str_replace( array('mod_', '.so', '.dll'), '', $file ) . '_module';
                $result[$name] = ActionSwitchApacheModule::SWITCH_OFF;
            }
        }
        closedir( $handle );
        ksort( $result );
        return $result;
    }
References Module\$name, $result, Util\endWith(), getModulesPath(), Util\startWith(), and ActionSwitchApacheModule\SWITCH_OFF.
Referenced by getModules().
getModulesLoaded()
BinApache::getModulesLoaded ()
Retrieves the list of loaded modules from the configuration file.
Returns
array The list of loaded modules.
Definition at line 457 of file class.bin.apache.php.
    {
        $result = array();
        foreach ( $this->getModulesFromConf() as $name => $status ) {
            if ( $status == ActionSwitchApacheModule::SWITCH_ON ) {
                $result[] = $name;
            }
        }
        return $result;
    }
References Module\$name, $result, getModulesFromConf(), and ActionSwitchApacheModule\SWITCH_ON.
getModulesPath()
BinApache::getModulesPath ()
Gets the path to the modules.
Returns
string The path to the modules.
Definition at line 950 of file class.bin.apache.php.
    {
        return $this->modulesPath;
    }
References $modulesPath.
Referenced by getModulesFromFolder().
getOfflineContent()
BinApache::getOfflineContent ($version = null) private
Generates the offline content for the configuration file.
Parameters
string | null $version The version of the configuration.
Returns
string The offline content.
Definition at line 669 of file class.bin.apache.php.
    {
        $version = $version != null ? $version : $this->getVersion();
        $result  = self::TAG_START_SWITCHONLINE . PHP_EOL;
        if ( Util::startWith( $version, '2.4' ) ) {
            $result .= 'Require local' . PHP_EOL;
        }
        else {
            $result .= 'Order Deny,Allow' . PHP_EOL .
                'Deny from all' . PHP_EOL .
                'Allow from 127.0.0.1 ::1' . PHP_EOL;
        }
        return $result . self::TAG_END_SWITCHONLINE;
    }
References $result, Module\$version, Module\getVersion(), Util\startWith(), and TAG_END_SWITCHONLINE.
Referenced by getRequiredContent(), refreshAlias(), refreshConf(), and refreshVhosts().
getOnlineContent()
BinApache::getOnlineContent ($version = null) private
Generates the online content for the configuration file.
Parameters
string | null $version The version of the configuration.
Returns
string The online content.
Definition at line 646 of file class.bin.apache.php.
    {
        $version = $version != null ? $version : $this->getVersion();
        $result  = self::TAG_START_SWITCHONLINE . PHP_EOL;
        if ( Util::startWith( $version, '2.4' ) ) {
            $result .= 'Require all granted' . PHP_EOL;
        }
        else {
            $result .= 'Order Allow,Deny' . PHP_EOL .
                'Allow from all' . PHP_EOL;
        }
        return $result . self::TAG_END_SWITCHONLINE;
    }
References $result, Module\$version, Module\getVersion(), Util\startWith(), and TAG_END_SWITCHONLINE.
Referenced by getRequiredContent(), refreshAlias(), refreshConf(), and refreshVhosts().
getOpensslExe()
BinApache::getOpensslExe ()
Gets the OpenSSL executable file path.
Returns
string The OpenSSL executable file path.
Definition at line 1064 of file class.bin.apache.php.
    {
        return $this->opensslExe;
    }
References $opensslExe.
getPort()
BinApache::getPort ()
Gets the port number.
Returns
int The port number.
Definition at line 1020 of file class.bin.apache.php.
    {
        return $this->port;
    }
References $port.
Referenced by getVhostContent().
getRequiredContent()
BinApache::getRequiredContent ($version = null) private
Generates the required content for the configuration file based on the online status.
Parameters
string | null $version The version of the configuration.
Returns
string The required content.
Definition at line 693 of file class.bin.apache.php.
    {
        global $bearsamppConfig;
        return $bearsamppConfig->isOnline() ? $this->getOnlineContent( $version ) : $this->getOfflineContent( $version );
    }
References $bearsamppConfig, Module\$version, getOfflineContent(), and getOnlineContent().
Referenced by getAliasContent(), and getVhostContent().
getRewriteLog()
BinApache::getRewriteLog ()
Gets the rewrite log file path.
Returns
string The rewrite log file path.
Definition at line 980 of file class.bin.apache.php.
    {
        return $this->rewriteLog;
    }
References $rewriteLog.
getService()
BinApache::getService ()
Gets the service associated with the module.
Returns
string The service associated with the module.
Definition at line 940 of file class.bin.apache.php.
    {
        return $this->service;
    }
References $service.
getSslConf()
BinApache::getSslConf ()
Gets the SSL configuration file path.
Returns
string The SSL configuration file path.
Definition at line 960 of file class.bin.apache.php.
    {
        return $this->sslConf;
    }
References $sslConf.
Referenced by refreshConf().
getSslPort()
BinApache::getSslPort ()
Gets the SSL port number.
Returns
int The SSL port number.
Definition at line 1042 of file class.bin.apache.php.
    {
        return $this->sslPort;
    }
References $sslPort.
Referenced by getVhostContent().
getVhostContent()
BinApache::getVhostContent ($serverName, $documentRoot)
Generates the virtual host content for the configuration file.
Parameters
string $serverName The server name of the virtual host.
string $documentRoot The document root of the virtual host.
Returns
string The virtual host content.
Definition at line 728 of file class.bin.apache.php.
    {
        global $bearsamppRoot;
        $documentRoot = Util::formatUnixPath( $documentRoot );
        return '<VirtualHost *:' . $this->getPort() . '>' . PHP_EOL .
            '    ServerAdmin webmaster@' . $serverName . PHP_EOL .
            '    DocumentRoot "' . $documentRoot . '"' . PHP_EOL .
            '    ServerName ' . $serverName . PHP_EOL .
            '    ErrorLog "' . $bearsamppRoot->getLogsPath() . '/' . $serverName . '_error.log"' . PHP_EOL .
            '    CustomLog "' . $bearsamppRoot->getLogsPath() . '/' . $serverName . '_access.log" combined' . PHP_EOL . PHP_EOL .
            '    <Directory "' . $documentRoot . '">' . PHP_EOL .
            '        Options Indexes FollowSymLinks MultiViews' . PHP_EOL .
            '        AllowOverride all' . PHP_EOL .
            $this->getRequiredContent() . PHP_EOL .
            '    </Directory>' . PHP_EOL .
            '</VirtualHost>' . PHP_EOL . PHP_EOL .
            '<IfModule ssl_module>' . PHP_EOL .
            '<VirtualHost *:' . $this->getSslPort() . '> #SSL' . PHP_EOL .
            '    DocumentRoot "' . $documentRoot . '"' . PHP_EOL .
            '    ServerName ' . $serverName . PHP_EOL .
            '    ServerAdmin webmaster@' . $serverName . PHP_EOL .
            '    ErrorLog "' . $bearsamppRoot->getLogsPath() . '/' . $serverName . '_error.log"' . PHP_EOL .
            '    TransferLog "' . $bearsamppRoot->getLogsPath() . '/' . $serverName . '_access.log"' . PHP_EOL . PHP_EOL .
            '    SSLEngine on' . PHP_EOL .
            '    SSLProtocol all -SSLv2' . PHP_EOL .
            '    SSLCipherSuite HIGH:MEDIUM:!aNULL:!MD5' . PHP_EOL .
            '    SSLCertificateFile "' . $bearsamppRoot->getSslPath() . '/' . $serverName . '.crt"' . PHP_EOL .
            '    SSLCertificateKeyFile "' . $bearsamppRoot->getSslPath() . '/' . $serverName . '.pub"' . PHP_EOL .
            '    BrowserMatch "MSIE [2-5]" nokeepalive ssl-unclean-shutdown downgrade-1.0 force-response-1.0' . PHP_EOL .
            '    CustomLog "' . $bearsamppRoot->getLogsPath() . '/' . $serverName . '_sslreq.log" "%t %h %{SSL_PROTOCOL}x %{SSL_CIPHER}x \"%r\" %b"' . PHP_EOL . PHP_EOL .
            '    <Directory "' . $documentRoot . '">' . PHP_EOL .
            '        SSLOptions +StdEnvVars' . PHP_EOL .
            '        Options Indexes FollowSymLinks MultiViews' . PHP_EOL .
            '        AllowOverride all' . PHP_EOL .
            $this->getRequiredContent() . PHP_EOL .
            '    </Directory>' . PHP_EOL .
            '</VirtualHost>' . PHP_EOL .
            '</IfModule>' . PHP_EOL;
    }
References $bearsamppRoot, Util\formatUnixPath(), getPort(), getRequiredContent(), and getSslPort().
getVhosts()
BinApache::getVhosts ()
Retrieves the list of virtual hosts configurations.
Returns
array The list of virtual hosts configurations.
Definition at line 532 of file class.bin.apache.php.
    {
        global $bearsamppRoot;
        $result = array();
        $handle = @opendir( $bearsamppRoot->getVhostsPath() );
        if ( !$handle ) {
            return $result;
        }
        while ( false !== ($file = readdir( $handle )) ) {
            if ( $file != '.' && $file != '..' && Util::endWith( $file, '.conf' ) ) {
                $result[] = str_replace( '.conf', '', $file );
            }
        }
        closedir( $handle );
        ksort( $result );
        return $result;
    }
References $bearsamppRoot, $result, and Util\endWith().
Referenced by getVhostsUrl(), refreshVhosts(), and updateConfig().
getVhostsUrl()
BinApache::getVhostsUrl ()
Retrieves the URLs of the virtual hosts.
Returns
array The list of virtual hosts URLs.
Definition at line 559 of file class.bin.apache.php.
    {
        global $bearsamppRoot;
        $result = array();
        foreach ( $this->getVhosts() as $vhost ) {
            $vhostContent = file( $bearsamppRoot->getVhostsPath() . '/' . $vhost . '.conf' );
            foreach ( $vhostContent as $vhostLine ) {
                $vhostLine = trim( $vhostLine );
                $enabled   = !Util::startWith( $vhostLine, '#' );
                if ( preg_match_all( '/ServerName\s+(.*)/', $vhostLine, $matches ) ) {
                    foreach ( $matches as $match ) {
                        $found = isset( $match[1] ) ? trim( $match[1] ) : trim( $match[0] );
                        if ( filter_var( 'http://' . $found, FILTER_VALIDATE_URL ) !== false ) {
                            $result[$found] = $enabled;
                            break 2;
                        }
                    }
                }
            }
        }
        return $result;
    }
References $bearsamppRoot, $result, getVhosts(), and Util\startWith().
getWwwDirectories()
BinApache::getWwwDirectories ()
Retrieves the list of directories in the www folder.
Returns
array The list of directories in the www folder.
Definition at line 589 of file class.bin.apache.php.
    {
        global $bearsamppRoot;
        $result = array();
        $handle = @opendir( $bearsamppRoot->getWwwPath() );
        if ( !$handle ) {
            return $result;
        }
        while ( false !== ($file = readdir( $handle )) ) {
            if ( $file != '.' && $file != '..' && is_dir( $bearsamppRoot->getWwwPath() . '/' . $file ) ) {
                $result[] = $file;
            }
        }
        closedir( $handle );
        ksort( $result );
        return $result;
    }
References $bearsamppRoot, and $result.
refreshAlias()
BinApache::refreshAlias ($putOnline)
Refreshes the alias configurations to switch between online and offline modes.
Parameters
bool $putOnline Whether to put the alias configurations online.
Definition at line 818 of file class.bin.apache.php.
    {
        global $bearsamppRoot, $bearsamppHomepage;
        if ( !$this->enable ) {
            return;
        }
        $onlineContent  = $this->getOnlineContent();
        $offlineContent = $this->getOfflineContent();
        foreach ( $this->getAlias() as $alias ) {
            $aliasConf = file_get_contents( $bearsamppRoot->getAliasPath() . '/' . $alias . '.conf' );
            Util::logTrace( 'refreshAlias ' . $bearsamppRoot->getAliasPath() . '/' . $alias . '.conf' );
            preg_match( '/' . self::TAG_START_SWITCHONLINE . '(.*?)' . self::TAG_END_SWITCHONLINE . '/s', $aliasConf, $matches );
            Util::logTrace( isset( $matches[1] ) ? print_r( $matches[1], true ) : 'N/A' );
            if ( $putOnline ) {
                $aliasConf = preg_replace( '/' . self::TAG_START_SWITCHONLINE . '(.*?)' . self::TAG_END_SWITCHONLINE . '/s', $onlineContent, $aliasConf, -1, $count );
            }
            else {
                $aliasConf = preg_replace( '/' . self::TAG_START_SWITCHONLINE . '(.*?)' . self::TAG_END_SWITCHONLINE . '/s', $offlineContent, $aliasConf, -1, $count );
            }
            file_put_contents( $bearsamppRoot->getAliasPath() . '/' . $alias . '.conf', $aliasConf );
            Util::logDebug( 'Refresh ' . $bearsamppRoot->getAliasPath() . '/' . $alias . '.conf: ' . $count . ' occurrence(s) replaced' );
        }
        // Homepage
        $bearsamppHomepage->refreshAliasContent();
    }
References $bearsamppHomepage, $bearsamppRoot, getAlias(), getOfflineContent(), getOnlineContent(), Util\logDebug(), and Util\logTrace().
refreshConf()
BinApache::refreshConf ($putOnline)
Refreshes the configuration file to switch between online and offline modes.
Parameters
bool $putOnline Whether to put the configuration online.
Definition at line 775 of file class.bin.apache.php.
    {
        if ( !$this->enable ) {
            return;
        }
        $onlineContent  = $this->getOnlineContent();
        $offlineContent = $this->getOfflineContent();
        $conf = file_get_contents( $this->getConf() );
        Util::logTrace( 'refreshConf ' . $this->getConf() );
        preg_match( '/' . self::TAG_START_SWITCHONLINE . '(.*?)' . self::TAG_END_SWITCHONLINE . '/s', $conf, $matches );
        Util::logTrace( isset( $matches[1] ) ? print_r( $matches[1], true ) : 'N/A' );
        if ( $putOnline ) {
            $conf = preg_replace( '/' . self::TAG_START_SWITCHONLINE . '(.*?)' . self::TAG_END_SWITCHONLINE . '/s', $onlineContent, $conf, -1, $count );
        }
        else {
            $conf = preg_replace( '/' . self::TAG_START_SWITCHONLINE . '(.*?)' . self::TAG_END_SWITCHONLINE . '/s', $offlineContent, $conf, -1, $count );
        }
        file_put_contents( $this->getConf(), $conf );
        Util::logDebug( 'Refresh ' . $this->getConf() . ': ' . $count . ' occurrence(s) replaced' );
        $sslConf = file_get_contents( $this->getSslConf() );
        Util::logTrace( 'refreshConf ' . $this->getSslConf() );
        preg_match( '/' . self::TAG_START_SWITCHONLINE . '(.*?)' . self::TAG_END_SWITCHONLINE . '/s', $sslConf, $matches );
        Util::logTrace( isset( $matches[1] ) ? print_r( $matches[1], true ) : 'N/A' );
        if ( $putOnline ) {
            $sslConf = preg_replace( '/' . self::TAG_START_SWITCHONLINE . '(.*?)' . self::TAG_END_SWITCHONLINE . '/s', $onlineContent, $sslConf, -1, $count );
        }
        else {
            $sslConf = preg_replace( '/' . self::TAG_START_SWITCHONLINE . '(.*?)' . self::TAG_END_SWITCHONLINE . '/s', $offlineContent, $sslConf, -1, $count );
        }
        file_put_contents( $this->getSslConf(), $sslConf );
        Util::logDebug( 'Refresh ' . $this->getSslConf() . ': ' . $count . ' occurrence(s) replaced' );
    }
References $conf, $sslConf, getConf(), getOfflineContent(), getOnlineContent(), getSslConf(), Util\logDebug(), and Util\logTrace().
refreshVhosts()
BinApache::refreshVhosts ($putOnline)
Refreshes the virtual host configurations to switch between online and offline modes.
Parameters
bool $putOnline Whether to put the virtual host configurations online.
Definition at line 854 of file class.bin.apache.php.
    {
        global $bearsamppRoot;
        if ( !$this->enable ) {
            return;
        }
        $onlineContent  = $this->getOnlineContent();
        $offlineContent = $this->getOfflineContent();
        foreach ( $this->getVhosts() as $vhost ) {
            $vhostConf = file_get_contents( $bearsamppRoot->getVhostsPath() . '/' . $vhost . '.conf' );
            Util::logTrace( 'refreshVhost ' . $bearsamppRoot->getVhostsPath() . '/' . $vhost . '.conf' );
            preg_match( '/' . self::TAG_START_SWITCHONLINE . '(.*?)' . self::TAG_END_SWITCHONLINE . '/s', $vhostConf, $matches );
            Util::logTrace( isset( $matches[1] ) ? print_r( $matches[1], true ) : 'N/A' );
            if ( $putOnline ) {
                $vhostConf = preg_replace( '/' . self::TAG_START_SWITCHONLINE . '(.*?)' . self::TAG_END_SWITCHONLINE . '/s', $onlineContent, $vhostConf, -1, $count );
            }
            else {
                $vhostConf = preg_replace( '/' . self::TAG_START_SWITCHONLINE . '(.*?)' . self::TAG_END_SWITCHONLINE . '/s', $offlineContent, $vhostConf, -1, $count );
            }
            file_put_contents( $bearsamppRoot->getVhostsPath() . '/' . $vhost . '.conf', $vhostConf );
            Util::logDebug( 'Refresh ' . $bearsamppRoot->getVhostsPath() . '/' . $vhost . '.conf: ' . $count . ' occurrence(s) replaced' );
        }
    }
References $bearsamppRoot, getOfflineContent(), getOnlineContent(), getVhosts(), Util\logDebug(), and Util\logTrace().
reload()
BinApache::reload ($id = null, $type = null)
Reloads the module configuration based on the provided ID and type.
Parameters
string | null $id The ID of the module. If null, the current ID is used.
string | null $type The type of the module. If null, the current type is used.
Reimplemented from Module.
Definition at line 72 of file class.bin.apache.php.
    {
        global $bearsamppRoot, $bearsamppConfig, $bearsamppLang;
        Util::logReloadClass( $this );
        $this->name    = $bearsamppLang->getValue( Lang::APACHE );
        $this->version = $bearsamppConfig->getRaw( self::ROOT_CFG_VERSION );
        parent::reload( $id, $type );
        $this->enable      = $this->enable && $bearsamppConfig->getRaw( self::ROOT_CFG_ENABLE );
        $this->service     = new Win32Service( self::SERVICE_NAME );
        $this->modulesPath = $this->symlinkPath . '/modules';
        $this->sslConf     = $this->symlinkPath . '/conf/extra/httpd-ssl.conf';
        $this->accessLog   = $bearsamppRoot->getLogsPath() . '/apache_access.log';
        $this->rewriteLog  = $bearsamppRoot->getLogsPath() . '/apache_rewrite.log';
        $this->errorLog    = $bearsamppRoot->getLogsPath() . '/apache_error.log';
        if ( $this->bearsamppConfRaw !== false ) {
            $this->exe        = $this->symlinkPath . '/' . $this->bearsamppConfRaw[self::LOCAL_CFG_EXE];
            $this->conf       = $this->symlinkPath . '/' . $this->bearsamppConfRaw[self::LOCAL_CFG_CONF];
            $this->port       = $this->bearsamppConfRaw[self::LOCAL_CFG_PORT];
            $this->sslPort    = $this->bearsamppConfRaw[self::LOCAL_CFG_SSL_PORT];
            $this->opensslExe = $this->symlinkPath . '/' . $this->bearsamppConfRaw[self::LOCAL_CFG_OPENSSL_EXE];
        }
        if ( !$this->enable ) {
            Util::logInfo( $this->name . ' is not enabled!' );
            return;
        }
        if ( !is_dir( $this->currentPath ) ) {
            Util::logError( sprintf( $bearsamppLang->getValue( Lang::ERROR_FILE_NOT_FOUND ), $this->name . ' ' . $this->version, $this->currentPath ) );
            return;
        }
        if ( !is_dir( $this->symlinkPath ) ) {
            Util::logError( sprintf( $bearsamppLang->getValue( Lang::ERROR_FILE_NOT_FOUND ), $this->name . ' ' . $this->version, $this->symlinkPath ) );
            return;
        }
        if ( !is_file( $this->bearsamppConf ) ) {
            Util::logError( sprintf( $bearsamppLang->getValue( Lang::ERROR_CONF_NOT_FOUND ), $this->name . ' ' . $this->version, $this->bearsamppConf ) );
            return;
        }
        if ( !is_file( $this->sslConf ) ) {
            Util::logError( sprintf( $bearsamppLang->getValue( Lang::ERROR_CONF_NOT_FOUND ), $this->name . ' ' . $this->version, $this->sslConf ) );
            return;
        }
        if ( !is_file( $this->exe ) ) {
            Util::logError( sprintf( $bearsamppLang->getValue( Lang::ERROR_EXE_NOT_FOUND ), $this->name . ' ' . $this->version, $this->exe ) );
            return;
        }
        if ( !is_file( $this->conf ) ) {
            Util::logError( sprintf( $bearsamppLang->getValue( Lang::ERROR_CONF_NOT_FOUND ), $this->name . ' ' . $this->version, $this->conf ) );
            return;
        }
        if ( !is_numeric( $this->port ) || $this->port <= 0 ) {
            Util::logError( sprintf( $bearsamppLang->getValue( Lang::ERROR_INVALID_PARAMETER ), self::LOCAL_CFG_PORT, $this->port ) );
            return;
        }
        if ( !is_numeric( $this->sslPort ) || $this->sslPort <= 0 ) {
            Util::logError( sprintf( $bearsamppLang->getValue( Lang::ERROR_INVALID_PARAMETER ), self::LOCAL_CFG_SSL_PORT, $this->sslPort ) );
            return;
        }
        if ( !is_file( $this->opensslExe ) ) {
            Util::logError( sprintf( $bearsamppLang->getValue( Lang::ERROR_EXE_NOT_FOUND ), $this->name . ' ' . $this->version, $this->opensslExe ) );
            return;
        }
        $nssm = new Nssm( self::SERVICE_NAME );
        $nssm->setDisplayName( APP_TITLE . ' ' . $this->getName() );
        $nssm->setBinPath( $this->exe );
        $nssm->setStart( Nssm::SERVICE_DEMAND_START );
        $this->service->setNssm( $nssm );
    }
References $bearsamppConfig, $bearsamppLang, $bearsamppRoot, Module\$id, Module\$type, Lang\APACHE, APP_TITLE, Lang\ERROR_CONF_NOT_FOUND, Lang\ERROR_EXE_NOT_FOUND, Lang\ERROR_FILE_NOT_FOUND, Lang\ERROR_INVALID_PARAMETER, Module\getName(), LOCAL_CFG_CONF, LOCAL_CFG_EXE, LOCAL_CFG_OPENSSL_EXE, LOCAL_CFG_PORT, LOCAL_CFG_SSL_PORT, Util\logError(), Util\logInfo(), Util\logReloadClass(), and Nssm\SERVICE_DEMAND_START.
Referenced by __construct(), setEnable(), and setVersion().
replaceAll()
BinApache::replaceAll ($params) protected
Replaces multiple key-value pairs in the configuration file.
Parameters
array $params An associative array of key-value pairs to replace.
Reimplemented from Module.
Definition at line 161 of file class.bin.apache.php.
    {
        $content = file_get_contents( $this->bearsamppConf );
        foreach ( $params as $key => $value ) {
            $content                      = preg_replace( '|' . $key . ' = .*|', $key . ' = ' . '"' . $value . '"', $content );
            $this->bearsamppConfRaw[$key] = $value;
            switch ( $key ) {
                case self::LOCAL_CFG_PORT:
                    $this->port = $value;
                    break;
                case self::LOCAL_CFG_SSL_PORT:
                    $this->sslPort = $value;
                    break;
            }
        }
        file_put_contents( $this->bearsamppConf, $content );
    }
References LOCAL_CFG_PORT, and LOCAL_CFG_SSL_PORT.
setEnable()
BinApache::setEnable ($enabled, $showWindow = false)
Sets the enable status of the module.
This method enables or disables the module based on the provided parameter. If enabling the module and the current path does not exist, it logs an error and optionally shows an error message window.
Parameters
bool $enabled Whether to enable or disable the module.
bool $showWindow Whether to show an error message window if enabling fails.
Definition at line 892 of file class.bin.apache.php.
    {
        global $bearsamppConfig, $bearsamppLang, $bearsamppWinbinder;
        if ( $enabled == Config::ENABLED && !is_dir( $this->currentPath ) ) {
            Util::logDebug( $this->getName() . ' cannot be enabled because bundle ' . $this->getVersion() . ' does not exist in ' . $this->currentPath );
            if ( $showWindow ) {
                $bearsamppWinbinder->messageBoxError(
                    sprintf( $bearsamppLang->getValue( Lang::ENABLE_BUNDLE_NOT_EXIST ), $this->getName(), $this->getVersion(), $this->currentPath ),
                    sprintf( $bearsamppLang->getValue( Lang::ENABLE_TITLE ), $this->getName() )
                );
            }
            $enabled = Config::DISABLED;
        }
        Util::logInfo( $this->getName() . ' switched to ' . ($enabled == Config::ENABLED ? 'enabled' : 'disabled') );
        $this->enable = $enabled == Config::ENABLED;
        $bearsamppConfig->replace( self::ROOT_CFG_ENABLE, $enabled );
        $this->reload();
        if ( $this->enable ) {
            Util::installService( $this, $this->port, self::CMD_SYNTAX_CHECK, $showWindow );
        }
        else {
            Util::removeService( $this->service, $this->name );
        }
    }
References $bearsamppConfig, $bearsamppLang, Config\DISABLED, Lang\ENABLE_BUNDLE_NOT_EXIST, Lang\ENABLE_TITLE, Config\ENABLED, Module\getName(), Module\getVersion(), Util\installService(), Util\logDebug(), Util\logInfo(), reload(), and Util\removeService().
setPort()
BinApache::setPort ($port)
Sets the port number.
This method updates the port number in the configuration.
Parameters
int $port The port number to set.
Definition at line 1032 of file class.bin.apache.php.
    {
        $this->replace( self::LOCAL_CFG_PORT, $port );
    }
References $port, and Module\replace().
Referenced by changePort().
setSslPort()
BinApache::setSslPort ($sslPort)
Sets the SSL port number.
This method updates the SSL port number in the configuration.
Parameters
int $sslPort The SSL port number to set.
Definition at line 1054 of file class.bin.apache.php.
    {
        $this->replace( self::LOCAL_CFG_SSL_PORT, $sslPort );
    }
References $sslPort, and Module\replace().
setVersion()
BinApache::setVersion ($version)
Sets the version of the module.
This method updates the version of the module and reloads its configuration.
Parameters
string $version The version to set for the module.
Reimplemented from Module.
Definition at line 927 of file class.bin.apache.php.
    {
        global $bearsamppConfig;
        $this->version = $version;
        $bearsamppConfig->replace( self::ROOT_CFG_VERSION, $version );
        $this->reload();
    }
References $bearsamppConfig, Module\$version, and reload().
Referenced by updateConfig().
switchVersion()
BinApache::switchVersion ($version, $showWindow = false)
Switches the Apache version.
Parameters
string $version The version to switch to.
bool $showWindow Whether to show a window with the result.
Returns
bool True if the version was switched successfully, false otherwise.
Definition at line 285 of file class.bin.apache.php.
    {
        Util::logDebug( 'Switch ' . $this->name . ' version to ' . $version );
        return $this->updateConfig( $version, 0, $showWindow );
    }
References Module\$version, Util\logDebug(), and updateConfig().
updateConfig()
BinApache::updateConfig ($version = null, $sub = 0, $showWindow = false) protected
Updates the Apache configuration with a specific version.
Parameters
string | null $version The version to update to. If null, the current version is used.
int $sub The sub-level for logging indentation.
bool $showWindow Whether to show a window during the update process.
Returns
bool True if the configuration was updated successfully, false otherwise.
Reimplemented from Module.
Definition at line 301 of file class.bin.apache.php.
    {
        global $bearsamppRoot, $bearsamppLang, $bearsamppBins, $bearsamppWinbinder;
        if ( !$this->enable ) {
            return true;
        }
        $version = $version == null ? $this->version : $version;
        Util::logDebug( ($sub > 0 ? str_repeat( ' ', 2 * $sub ) : '') . 'Update ' . $this->name . ' ' . $version . ' config' );
        $boxTitle = sprintf( $bearsamppLang->getValue( Lang::SWITCH_VERSION_TITLE ), $this->getName(), $version );
        $conf          = str_replace( 'apache' . $this->getVersion(), 'apache' . $version, $this->getConf() );
        $bearsamppConf = str_replace( 'apache' . $this->getVersion(), 'apache' . $version, $this->bearsamppConf );
        $tsDll = $bearsamppBins->getPhp()->getTsDll();
        $apachePhpModuleName = null;
        if ( $tsDll !== false ) {
            $apachemoduleNamePrefix = substr( $tsDll, 0, 4 );
            $apachePhpModuleName    = ($apachemoduleNamePrefix == 'php8' ? 'php' : $apachemoduleNamePrefix) . '_module';
        }
        $apachePhpModulePath = $bearsamppBins->getPhp()->getApacheModule( $version );
        $apachePhpModuleDll  = basename( $apachePhpModulePath );
        Util::logDebug( ($sub > 0 ? str_repeat( ' ', 2 * $sub ) : '') . 'PHP TsDll found: ' . $tsDll );
        Util::logDebug( ($sub > 0 ? str_repeat( ' ', 2 * $sub ) : '') . 'PHP Apache module found: ' . $apachePhpModulePath );
        if ( !file_exists( $conf ) || !file_exists( $bearsamppConf ) ) {
            Util::logError( 'bearsampp config files not found for ' . $this->getName() . ' ' . $version );
            if ( $showWindow ) {
                $bearsamppWinbinder->messageBoxError(
                    sprintf( $bearsamppLang->getValue( Lang::BEARSAMPP_CONF_NOT_FOUND_ERROR ), $this->getName() . ' ' . $version ),
                    $boxTitle
                );
            }
            return false;
        }
        $bearsamppConfRaw = parse_ini_file( $bearsamppConf );
        if ( $bearsamppConfRaw === false || !isset( $bearsamppConfRaw[self::ROOT_CFG_VERSION] ) || $bearsamppConfRaw[self::ROOT_CFG_VERSION] != $version ) {
            Util::logError( 'bearsampp config file malformed for ' . $this->getName() . ' ' . $version );
            if ( $showWindow ) {
                $bearsamppWinbinder->messageBoxError(
                    sprintf( $bearsamppLang->getValue( Lang::BEARSAMPP_CONF_MALFORMED_ERROR ), $this->getName() . ' ' . $version ),
                    $boxTitle
                );
            }
            return false;
        }
        if ( $tsDll === false || $apachePhpModulePath === false ) {
            Util::logDebug( $this->getName() . ' ' . $version . ' does not seem to be compatible with PHP ' . $bearsamppBins->getPhp()->getVersion() );
            if ( $showWindow ) {
                $bearsamppWinbinder->messageBoxError(
                    sprintf( $bearsamppLang->getValue( Lang::APACHE_INCPT ), $version, $bearsamppBins->getPhp()->getVersion() ),
                    $boxTitle
                );
            }
            return false;
        }
        // httpd.conf
        $this->setVersion( $version );
        // conf
        Util::logDebug( 'httpd.conf = ' . $conf );
        Util::replaceInFile( $conf, array(
            // PHP module
            '/^#?PHPIniDir\s.*/'                          => ($bearsamppBins->getPhp()->isEnable() ? '' : '#') . 'PHPIniDir "' . $bearsamppBins->getPhp()->getSymlinkPath() . '"',
            '/^#?LoadFile\s.*php.ts\.dll.*/'              => ($bearsamppBins->getPhp()->isEnable() ? '' : '#') . (!file_exists( $bearsamppBins->getPhp()->getSymlinkPath() . '/' . $tsDll ) ? '#' : '') . 'LoadFile "' . $bearsamppBins->getPhp()->getSymlinkPath() . '/' . $tsDll . '"',
            '/^#?LoadModule\sphp.*/'                      => ($bearsamppBins->getPhp()->isEnable() ? '' : '#') . 'LoadModule ' . $apachePhpModuleName . ' "' . $bearsamppBins->getPhp()->getSymlinkPath() . '/' . $apachePhpModuleDll . '"',
            '/^#?LoadModule\sphp_*/'                      => ($bearsamppBins->getPhp()->isEnable() ? '' : '#') . 'LoadModule ' . $apachePhpModuleName . ' "' . $bearsamppBins->getPhp()->getSymlinkPath() . '/' . $apachePhpModuleDll . '"',
            // Port
            '/^Listen\s(\d+)/'                            => 'Listen ' . $this->port,
            '/^ServerName\s+([a-zA-Z0-9.]+):(\d+)/'       => 'ServerName {{1}}:' . $this->port,
            '/^NameVirtualHost\s+([a-zA-Z0-9.*]+):(\d+)/' => 'NameVirtualHost {{1}}:' . $this->port,
            '/^<VirtualHost\s+([a-zA-Z0-9.*]+):(\d+)>/'   => '<VirtualHost {{1}}:' . $this->port . '>'
        ) );
        // vhosts
        foreach ( $this->getVhosts() as $vhost ) {
            Util::replaceInFile( $bearsamppRoot->getVhostsPath() . '/' . $vhost . '.conf', array(
                '/^<VirtualHost\s+([a-zA-Z0-9.*]+):(\d+)>$/' => '<VirtualHost {{1}}:' . $this->port . '>$'
            ) );
        }
        // www .htaccess
        Util::replaceInFile( $bearsamppRoot->getWwwPath() . '/.htaccess', array(
            '/(.*)http:\/\/localhost(.*)/' => '{{1}}http://localhost' . ($this->port != 80 ? ':' . $this->port : '') . '/$1 [QSA,R=301,L]',
        ) );
        return true;
    }
References $bearsamppBins, Module\$bearsamppConf, Module\$bearsamppConfRaw, $bearsamppLang, $bearsamppRoot, $conf, $port, Module\$version, Lang\APACHE_INCPT, Lang\BEARSAMPP_CONF_MALFORMED_ERROR, Lang\BEARSAMPP_CONF_NOT_FOUND_ERROR, getConf(), Module\getName(), Module\getVersion(), getVhosts(), Util\logDebug(), Util\logError(), Util\replaceInFile(), setVersion(), and Lang\SWITCH_VERSION_TITLE.
Referenced by switchVersion().
Field Documentation
$accessLog
BinApache::$accessLog private
Definition at line 44 of file class.bin.apache.php.
Referenced by getAccessLog().
$conf
BinApache::$conf private
Definition at line 49 of file class.bin.apache.php.
Referenced by getConf(), refreshConf(), and updateConfig().
$errorLog
BinApache::$errorLog private
Definition at line 46 of file class.bin.apache.php.
Referenced by getErrorLog().
$exe
BinApache::$exe private
Definition at line 48 of file class.bin.apache.php.
Referenced by getExe().
$modulesPath
BinApache::$modulesPath private
Definition at line 42 of file class.bin.apache.php.
Referenced by getModulesPath().
$opensslExe
BinApache::$opensslExe private
Definition at line 52 of file class.bin.apache.php.
Referenced by getOpensslExe().
$port
BinApache::$port private
Definition at line 50 of file class.bin.apache.php.
Referenced by changePort(), checkPort(), getPort(), setPort(), and updateConfig().
$rewriteLog
BinApache::$rewriteLog private
Definition at line 45 of file class.bin.apache.php.
Referenced by getRewriteLog().
$service
BinApache::$service private
Definition at line 41 of file class.bin.apache.php.
Referenced by getService().
$sslConf
BinApache::$sslConf private
Definition at line 43 of file class.bin.apache.php.
Referenced by getSslConf(), and refreshConf().
$sslPort
BinApache::$sslPort private
Definition at line 51 of file class.bin.apache.php.
Referenced by getSslPort(), and setSslPort().
CMD_COMPILE_SETTINGS
const BinApache::CMD_COMPILE_SETTINGS = '-V'
Definition at line 31 of file class.bin.apache.php.
Referenced by ActionDebugApache\__construct(), and TplAppApache\getMenuApacheDebug().
CMD_COMPILED_MODULES
const BinApache::CMD_COMPILED_MODULES = '-l'
Definition at line 32 of file class.bin.apache.php.
Referenced by ActionDebugApache\__construct(), and TplAppApache\getMenuApacheDebug().
CMD_CONFIG_DIRECTIVES
const BinApache::CMD_CONFIG_DIRECTIVES = '-L'
Definition at line 33 of file class.bin.apache.php.
Referenced by ActionDebugApache\__construct(), and TplAppApache\getMenuApacheDebug().
CMD_LOADED_MODULES
const BinApache::CMD_LOADED_MODULES = '-M'
Definition at line 35 of file class.bin.apache.php.
Referenced by ActionDebugApache\__construct(), and TplAppApache\getMenuApacheDebug().
CMD_SYNTAX_CHECK
const BinApache::CMD_SYNTAX_CHECK = '-t'
Definition at line 36 of file class.bin.apache.php.
Referenced by ActionDebugApache\__construct(), ActionService\__construct(), TplAppApache\getMenuApacheDebug(), ActionStartup\installServices(), BinPhp\setEnable(), and Win32Service\start().
CMD_VERSION_NUMBER
const BinApache::CMD_VERSION_NUMBER = '-v'
Definition at line 30 of file class.bin.apache.php.
Referenced by ActionDebugApache\__construct(), and TplAppApache\getMenuApacheDebug().
CMD_VHOSTS_SETTINGS
const BinApache::CMD_VHOSTS_SETTINGS = '-S'
Definition at line 34 of file class.bin.apache.php.
Referenced by ActionDebugApache\__construct(), and TplAppApache\getMenuApacheDebug().
LOCAL_CFG_CONF
const BinApache::LOCAL_CFG_CONF = 'apacheConf'
Definition at line 25 of file class.bin.apache.php.
Referenced by reload().
LOCAL_CFG_EXE
const BinApache::LOCAL_CFG_EXE = 'apacheExe'
Definition at line 24 of file class.bin.apache.php.
Referenced by reload().
LOCAL_CFG_OPENSSL_EXE
const BinApache::LOCAL_CFG_OPENSSL_EXE = 'apacheOpensslExe'
Definition at line 28 of file class.bin.apache.php.
Referenced by reload().
LOCAL_CFG_PORT
const BinApache::LOCAL_CFG_PORT = 'apachePort'
Definition at line 26 of file class.bin.apache.php.
Referenced by reload(), and replaceAll().
LOCAL_CFG_SSL_PORT
const BinApache::LOCAL_CFG_SSL_PORT = 'apacheSslPort'
Definition at line 27 of file class.bin.apache.php.
Referenced by reload(), and replaceAll().
ROOT_CFG_ENABLE
const BinApache::ROOT_CFG_ENABLE = 'apacheEnable'
Definition at line 21 of file class.bin.apache.php.
ROOT_CFG_VERSION
const BinApache::ROOT_CFG_VERSION = 'apacheVersion'
Definition at line 22 of file class.bin.apache.php.
SERVICE_NAME
const BinApache::SERVICE_NAME = 'bearsamppapache'
Definition at line 18 of file class.bin.apache.php.
Referenced by ActionService\__construct(), TplAppApache\getActionInstallApacheService(), TplAppApache\getActionRemoveApacheService(), TplAppOnline\getActionStatus(), TplAppApache\getActionSwitchApacheModule(), TplAppPhp\getActionSwitchPhpExtension(), TplAppPhp\getActionSwitchPhpSetting(), Bins\getServices(), ActionStartup\installServices(), ActionEditVhost\processWindow(), and Win32Service\start().
SERVICE_PARAMS
const BinApache::SERVICE_PARAMS = '-k runservice'
Definition at line 19 of file class.bin.apache.php.
TAG_END_SWITCHONLINE
const BinApache::TAG_END_SWITCHONLINE = '# END switchOnline tag - Do not replace!'
Definition at line 39 of file class.bin.apache.php.
Referenced by getOfflineContent(), and getOnlineContent().
TAG_START_SWITCHONLINE
const BinApache::TAG_START_SWITCHONLINE = '# START switchOnline tag - Do not replace!'
Definition at line 38 of file class.bin.apache.php.
The documentation for this class was generated from the following file:
E:/Bearsampp-development/sandbox/core/classes/bins/class.bin.apache.php