Bearsampp: TplAppOnline Class Reference
TplAppOnline Class Reference
Static Public Member Functions
static getActionStatus ($status)
static process ()
Data Fields
const ACTION = 'status'
Detailed Description
Class TplAppOnline
This class provides methods to handle the online/offline status of the Bearsampp application. It includes functionalities for generating actions and menu items to switch the application between online and offline states.
Definition at line 17 of file class.tpl.app.online.php.
Member Function Documentation
getActionStatus()
static TplAppOnline::getActionStatus ($status) static
Generates the action string to switch the online/offline status.
This method creates the action string for switching the application's online/offline status. It includes commands to restart relevant services and reload the application. The action string is used to define what happens when the status switch action is triggered.
Parameters
int $status The status to switch to (enabled or disabled).
Returns
string The generated action string for switching the online/offline status.
Definition at line 56 of file class.tpl.app.online.php.
    {
        return TplApp::getActionRun(Action::SWITCH_ONLINE, array($status)) . PHP_EOL .
            TplService::getActionRestart(BinApache::SERVICE_NAME) . PHP_EOL .
            TplService::getActionRestart(BinFilezilla::SERVICE_NAME) . PHP_EOL .
            TplAppReload::getActionReload() . PHP_EOL;
    }
References TplAppReload\getActionReload(), TplService\getActionRestart(), TplApp\getActionRun(), BinApache\SERVICE_NAME, BinFilezilla\SERVICE_NAME, and Action\SWITCH_ONLINE.
process()
static TplAppOnline::process () static
Generates the menu item and associated actions for switching the online/offline status.
This method creates a menu item for switching the application's online/offline status and defines the actions to be taken when the menu item is selected. It uses the global configuration and language objects to retrieve the current status and localized strings.
@global object $bearsamppConfig Provides access to the application's configuration settings. @global object $bearsamppLang Provides language support for retrieving language-specific values.
Returns
array The generated menu item and actions for switching the online/offline status.
Definition at line 34 of file class.tpl.app.online.php.
    {
        global $bearsamppConfig, $bearsamppLang;
        return TplApp::getActionMulti(
            self::ACTION, array($bearsamppConfig->isOnline() ? Config::DISABLED : Config::ENABLED),
            array($bearsamppConfig->isOnline() ? $bearsamppLang->getValue(Lang::MENU_PUT_OFFLINE) : $bearsamppLang->getValue(Lang::MENU_PUT_ONLINE)),
            false, get_called_class()
        );
    }
References $bearsamppConfig, $bearsamppLang, Config\DISABLED, Config\ENABLED, TplApp\getActionMulti(), Lang\MENU_PUT_OFFLINE, and Lang\MENU_PUT_ONLINE.
Referenced by TplApp\getSectionMenuLeft().
Field Documentation
ACTION
const TplAppOnline::ACTION = 'status'
Definition at line 20 of file class.tpl.app.online.php.
The documentation for this class was generated from the following file:
E:/Bearsampp-development/sandbox/core/classes/tpls/app/class.tpl.app.online.php