Bearsampp: ToolPython Class Reference
ToolPython Class Reference
Public Member Functions
__construct ($id, $type)
getCpExe ()
getExe ()
getIdleExe ()
reload ($id=null, $type=null)
setVersion ($version)
Public Member Functions inherited from Module
__toString ()
getCurrentPath ()
getId ()
getName ()
getRelease ()
getRootPath ()
getSymlinkPath ()
getType ()
getVersion ()
getVersionList ()
isEnable ()
update ($sub=0, $showWindow=false)
Data Fields
const LOCAL_CFG_CP_EXE = 'pythonCpExe'
const LOCAL_CFG_EXE = 'pythonExe'
const LOCAL_CFG_IDLE_EXE = 'pythonIdleExe'
const ROOT_CFG_VERSION = 'pythonVersion'
Data Fields inherited from Module
const BUNDLE_RELEASE = 'bundleRelease'
Private Attributes
$cpExe
$exe
$idleExe
Additional Inherited Members
Protected Member Functions inherited from Module
__construct ()
replace ($key, $value)
replaceAll ($params)
updateConfig ($version=null, $sub=0, $showWindow=false)
Protected Attributes inherited from Module
$bearsamppConf
$bearsamppConfRaw
$currentPath
$enable
$name
$release = 'N/A'
$rootPath
$symlinkPath
$version
Detailed Description
Class ToolPython
This class represents a Python tool module in the Bearsampp application. It extends the abstract Module class and provides specific functionalities for managing Python executables and configurations.
Definition at line 17 of file class.tool.python.php.
Constructor & Destructor Documentation
__construct()
ToolPython::__construct ($id, $type)
Constructor for the ToolPython class.
Parameters
string $id The ID of the module.
string $type The type of the module.
Definition at line 35 of file class.tool.python.php.
{
        Util::logInitClass($this);
        $this->reload($id, $type);
    }
References Module\$id, Module\$type, Util\logInitClass(), and reload().
Member Function Documentation
getCpExe()
ToolPython::getCpExe ()
Gets the path to the Python CP executable.
Returns
string The path to the Python CP executable.
Definition at line 111 of file class.tool.python.php.
{
        return $this->cpExe;
    }
References $cpExe.
getExe()
ToolPython::getExe ()
Gets the path to the Python executable.
Returns
string The path to the Python executable.
Definition at line 102 of file class.tool.python.php.
{
        return $this->exe;
    }
References $exe.
getIdleExe()
ToolPython::getIdleExe ()
Gets the path to the Python IDLE executable.
Returns
string The path to the Python IDLE executable.
Definition at line 120 of file class.tool.python.php.
{
        return $this->idleExe;
    }
References $idleExe.
reload()
ToolPython::reload ($id = null, $type = null)
Reloads the module configuration based on the provided ID and type.
Parameters
string | null $id The ID of the module. If null, the current ID is used.
string | null $type The type of the module. If null, the current type is used.
Reimplemented from Module.
Definition at line 46 of file class.tool.python.php.
{
        global $bearsamppConfig, $bearsamppLang;
        Util::logReloadClass($this);
        $this->name = $bearsamppLang->getValue(Lang::PYTHON);
        $this->version = $bearsamppConfig->getRaw(self::ROOT_CFG_VERSION);
        parent::reload($id, $type);
        if ($this->bearsamppConfRaw !== false) {
            $this->exe = $this->symlinkPath . '/' . $this->bearsamppConfRaw[self::LOCAL_CFG_EXE];
            $this->cpExe = $this->symlinkPath . '/' . $this->bearsamppConfRaw[self::LOCAL_CFG_CP_EXE];
            $this->idleExe = $this->symlinkPath . '/' . $this->bearsamppConfRaw[self::LOCAL_CFG_IDLE_EXE];
        }
        if (!$this->enable) {
            Util::logInfo($this->name . ' is not enabled!');
            return;
        }
        if (!is_dir($this->currentPath)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_FILE_NOT_FOUND), $this->name . ' ' . $this->version, $this->currentPath));
        }
        if (!is_dir($this->symlinkPath)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_FILE_NOT_FOUND), $this->name . ' ' . $this->version, $this->symlinkPath));
            return;
        }
        if (!is_file($this->bearsamppConf)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_CONF_NOT_FOUND), $this->name . ' ' . $this->version, $this->bearsamppConf));
        }
        if (!is_file($this->exe)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_EXE_NOT_FOUND), $this->name . ' ' . $this->version, $this->exe));
        }
        if (!is_file($this->cpExe)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_EXE_NOT_FOUND), $this->name . ' ' . $this->version, $this->cpExe));
        }
        if (!is_file($this->idleExe)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_EXE_NOT_FOUND), $this->name . ' ' . $this->version, $this->idleExe));
        }
    }
References $bearsamppConfig, $bearsamppLang, Module\$id, Module\$type, Lang\ERROR_CONF_NOT_FOUND, Lang\ERROR_EXE_NOT_FOUND, Lang\ERROR_FILE_NOT_FOUND, LOCAL_CFG_CP_EXE, LOCAL_CFG_EXE, LOCAL_CFG_IDLE_EXE, Util\logError(), Util\logInfo(), Util\logReloadClass(), and Lang\PYTHON.
Referenced by __construct(), and setVersion().
setVersion()
ToolPython::setVersion ($version)
Sets the version of the Python module and reloads the configuration.
Parameters
string $version The version to set.
Reimplemented from Module.
Definition at line 90 of file class.tool.python.php.
{
        global $bearsamppConfig;
        $this->version = $version;
        $bearsamppConfig->replace(self::ROOT_CFG_VERSION, $version);
        $this->reload();
    }
References $bearsamppConfig, Module\$version, and reload().
Field Documentation
$cpExe
ToolPython::$cpExe private
Definition at line 26 of file class.tool.python.php.
Referenced by getCpExe().
$exe
ToolPython::$exe private
Definition at line 25 of file class.tool.python.php.
Referenced by getExe().
$idleExe
ToolPython::$idleExe private
Definition at line 27 of file class.tool.python.php.
Referenced by getIdleExe().
LOCAL_CFG_CP_EXE
const ToolPython::LOCAL_CFG_CP_EXE = 'pythonCpExe'
Definition at line 22 of file class.tool.python.php.
Referenced by reload().
LOCAL_CFG_EXE
const ToolPython::LOCAL_CFG_EXE = 'pythonExe'
Definition at line 21 of file class.tool.python.php.
Referenced by reload().
LOCAL_CFG_IDLE_EXE
const ToolPython::LOCAL_CFG_IDLE_EXE = 'pythonIdleExe'
Definition at line 23 of file class.tool.python.php.
Referenced by reload().
ROOT_CFG_VERSION
const ToolPython::ROOT_CFG_VERSION = 'pythonVersion'
Definition at line 19 of file class.tool.python.php.
The documentation for this class was generated from the following file:
E:/Bearsampp-development/sandbox/core/classes/tools/class.tool.python.php