Bearsampp: ActionAbout Class Reference
ActionAbout Class Reference
Public Member Functions
__construct ($args)
processWindow ($window, $id, $ctrl, $param1, $param2)
Data Fields
const GAUGE_SAVE = 2
Private Attributes
$wbBtnOk
$wbImage
$wbLinkDonate
$wbLinkGithub
$wbLinkHomepage
$wbWindow
Detailed Description
Class ActionAbout Handles the creation and management of the "About" window in the Bearsampp application.
Definition at line 14 of file class.action.about.php.
Constructor & Destructor Documentation
__construct()
ActionAbout::__construct ($args)
ActionAbout constructor. Initializes the "About" window and its components.
Parameters
array $args Arguments passed to the constructor.
Definition at line 31 of file class.action.about.php.
    {
        global $bearsamppCore, $bearsamppLang, $bearsamppWinbinder;
        $bearsamppWinbinder->reset();
        $this->wbWindow = $bearsamppWinbinder->createAppWindow($bearsamppLang->getValue(Lang::ABOUT_TITLE), 500, 250, WBC_NOTIFY, WBC_KEYDOWN | WBC_KEYUP);
        $aboutText = sprintf($bearsamppLang->getValue(Lang::ABOUT_TEXT), APP_TITLE . ' ' . $bearsamppCore->getAppVersion(), date('Y'), APP_AUTHOR_NAME);
        $bearsamppWinbinder->createLabel($this->wbWindow, $aboutText, 80, 20, 470, 120);
        $bearsamppWinbinder->createLabel($this->wbWindow, $bearsamppLang->getValue(Lang::WEBSITE) . ' :', 80, 105, 470, 15);
        $this->wbLinkHomepage = $bearsamppWinbinder->createHyperLink($this->wbWindow, Util::getWebsiteUrlNoUtm(), 180, 105, 300, 15, WBC_LINES);
        $bearsamppWinbinder->createLabel($this->wbWindow, $bearsamppLang->getValue(Lang::DONATE) . ' :', 80, 125, 470, 15);
        $this->wbLinkDonate = $bearsamppWinbinder->createHyperLink($this->wbWindow, Util::getWebsiteUrlNoUtm('donate'), 180, 125, 300, 15, WBC_LINES | WBC_RIGHT);
        $bearsamppWinbinder->createLabel($this->wbWindow, $bearsamppLang->getValue(Lang::GITHUB) . ' :', 80, 145, 470, 15);
        $this->wbLinkGithub = $bearsamppWinbinder->createHyperLink($this->wbWindow, Util::getGithubUserUrl(), 180, 145, 300, 15, WBC_LINES | WBC_RIGHT);
        $this->wbBtnOk = $bearsamppWinbinder->createButton($this->wbWindow, $bearsamppLang->getValue(Lang::BUTTON_OK), 390, 180);
        $this->wbImage = $bearsamppWinbinder->drawImage($this->wbWindow, $bearsamppCore->getResourcesPath() . '/homepage/img/about.bmp');
        $bearsamppWinbinder->setHandler($this->wbWindow, $this, 'processWindow');
        $bearsamppWinbinder->mainLoop();
        $bearsamppWinbinder->reset();
    }
References $bearsamppCore, $bearsamppLang, Lang\ABOUT_TEXT, Lang\ABOUT_TITLE, APP_AUTHOR_NAME, APP_TITLE, Lang\BUTTON_OK, Lang\DONATE, Util\getGithubUserUrl(), Util\getWebsiteUrlNoUtm(), Lang\GITHUB, and Lang\WEBSITE.
Member Function Documentation
processWindow()
ActionAbout::processWindow ($window, $id, $ctrl, $param1, $param2)
Processes window events and handles user interactions.
Parameters
int $window The window identifier.
int $id The control identifier.
int $ctrl The control object.
mixed $param1 Additional parameter 1.
mixed $param2 Additional parameter 2.
Definition at line 68 of file class.action.about.php.
    {
        global $bearsamppConfig, $bearsamppWinbinder;
        switch ($id) {
            case $this->wbLinkHomepage[WinBinder::CTRL_ID]:
                $bearsamppWinbinder->exec($bearsamppConfig->getBrowser(), Util::getWebsiteUrl());
                break;
            case $this->wbLinkDonate[WinBinder::CTRL_ID]:
                $bearsamppWinbinder->exec($bearsamppConfig->getBrowser(), Util::getWebsiteUrl('donate'));
                break;
            case $this->wbLinkGithub[WinBinder::CTRL_ID]:
                $bearsamppWinbinder->exec($bearsamppConfig->getBrowser(), Util::getGithubUserUrl());
                break;
            case IDCLOSE:
            case $this->wbBtnOk[WinBinder::CTRL_ID]:
                $bearsamppWinbinder->destroyWindow($window);
                break;
        }
    }
References $bearsamppConfig, WinBinder\CTRL_ID, Util\getGithubUserUrl(), and Util\getWebsiteUrl().
Field Documentation
$wbBtnOk
ActionAbout::$wbBtnOk private
Definition at line 21 of file class.action.about.php.
$wbImage
ActionAbout::$wbImage private
Definition at line 17 of file class.action.about.php.
$wbLinkDonate
ActionAbout::$wbLinkDonate private
Definition at line 19 of file class.action.about.php.
$wbLinkGithub
ActionAbout::$wbLinkGithub private
Definition at line 20 of file class.action.about.php.
$wbLinkHomepage
ActionAbout::$wbLinkHomepage private
Definition at line 18 of file class.action.about.php.
$wbWindow
ActionAbout::$wbWindow private
Definition at line 16 of file class.action.about.php.
GAUGE_SAVE
const ActionAbout::GAUGE_SAVE = 2
Definition at line 23 of file class.action.about.php.
The documentation for this class was generated from the following file:
E:/Bearsampp-development/sandbox/core/classes/actions/class.action.about.php