My Project: TplAppNodejs Class Reference
TplAppNodejs Class Reference
Static Public Member Functions
static getActionEnableNodejs ($enable)
static getActionSwitchNodejsVersion ($version)
static getMenuNodejs ()
static getMenuNodejsVersions ()
static process ()
Data Fields
const ACTION_ENABLE = 'enableNodejs'
const ACTION_SWITCH_VERSION = 'switchNodejsVersion'
const MENU = 'nodejs'
const MENU_VERSIONS = 'nodejsVersions'
Detailed Description
Class TplAppNodejs
This class provides methods to generate and manage menu items and actions related to Node.js within the Bearsampp application. It includes functionalities for enabling/disabling Node.js, switching Node.js versions, and generating menus for Node.js actions.
Definition at line 16 of file class.tpl.app.nodejs.php.
Member Function Documentation
getActionEnableNodejs()
static TplAppNodejs::getActionEnableNodejs ($enable) static
Generates the action to enable or disable Node.js.
This method creates the action string for enabling or disabling Node.js. It includes commands to reload the application.
Parameters
int $enable The flag indicating whether to enable (1) or disable (0) Node.js.
@global object $bearsamppBins Provides access to system binaries and their configurations.
Returns
string The generated action string for enabling or disabling Node.js.
Definition at line 159 of file class.tpl.app.nodejs.php.
    {
        global $bearsamppBins;
        return TplApp::getActionRun(
            Action::ENABLE,
            array($bearsamppBins->getNodejs()->getName(), $enable)
        ) . PHP_EOL . TplAppReload::getActionReload();
    }
References $bearsamppBins, Action\ENABLE, TplAppReload\getActionReload(), and TplApp\getActionRun().
getActionSwitchNodejsVersion()
static TplAppNodejs::getActionSwitchNodejsVersion ($version) static
Generates the action to switch Node.js versions.
This method creates the action string for switching Node.js versions. It includes commands to reload the application.
Parameters
string $version The version of Node.js to switch to.
@global object $bearsamppBins Provides access to system binaries and their configurations.
Returns
string The generated action string for switching Node.js versions.
Definition at line 180 of file class.tpl.app.nodejs.php.
    {
        global $bearsamppBins;
        return TplApp::getActionRun(
            Action::SWITCH_VERSION,
            array($bearsamppBins->getNodejs()->getName(), $version)
        ) . PHP_EOL . TplAppReload::getActionReload() . PHP_EOL;
    }
References $bearsamppBins, TplAppReload\getActionReload(), TplApp\getActionRun(), and Action\SWITCH_VERSION.
getMenuNodejs()
static TplAppNodejs::getMenuNodejs () static
Generates the Node.js menu items and associated actions.
This method creates menu items for Node.js, including options to download more versions, enable/disable Node.js, switch versions, open a console, and edit the configuration file.
@global object $bearsamppBins Provides access to system binaries and their configurations. @global object $bearsamppLang Provides language support for retrieving language-specific values. @global object $bearsamppTools Provides access to various tools used in the application.
Returns
string The generated menu items and actions for Node.js.
Definition at line 59 of file class.tpl.app.nodejs.php.
    {
        global $bearsamppBins, $bearsamppLang, $bearsamppTools;
        $resultItems = $resultActions = '';
        $isEnabled = $bearsamppBins->getNodejs()->isEnable();
        // Download
        $resultItems .= TplAestan::getItemLink(
            $bearsamppLang->getValue(Lang::DOWNLOAD_MORE),
            Util::getWebsiteUrl('module/nodejs', '#releases'),
            false,
            TplAestan::GLYPH_BROWSER
        ) . PHP_EOL;
        // Enable
        $tplEnable = TplApp::getActionMulti(
            self::ACTION_ENABLE,
            array($isEnabled ? Config::DISABLED : Config::ENABLED),
            array($bearsamppLang->getValue(Lang::MENU_ENABLE), $isEnabled ? TplAestan::GLYPH_CHECK : ''),
            false,
            get_called_class()
        );
        $resultItems .= $tplEnable[TplApp::SECTION_CALL] . PHP_EOL;
        $resultActions .= $tplEnable[TplApp::SECTION_CONTENT] . PHP_EOL;
        if ($isEnabled) {
            $resultItems .= TplAestan::getItemSeparator() . PHP_EOL;
            // Versions
            $tplVersions = TplApp::getMenu(
                $bearsamppLang->getValue(Lang::VERSIONS),
                self::MENU_VERSIONS,
                get_called_class()
            );
            $resultItems .= $tplVersions[TplApp::SECTION_CALL] . PHP_EOL;
            $resultActions .= $tplVersions[TplApp::SECTION_CONTENT];
            // Console
            $resultItems .= TplAestan::getItemConsoleZ(
                $bearsamppLang->getValue(Lang::CONSOLE),
                TplAestan::GLYPH_CONSOLEZ,
                $bearsamppTools->getConsoleZ()->getTabTitleNodejs()
            ) . PHP_EOL;
            // Conf
            $resultItems .= TplAestan::getItemNotepad(
                basename($bearsamppBins->getNodejs()->getConf()),
                $bearsamppBins->getNodejs()->getConf()
            ) . PHP_EOL;
        }
        return $resultItems . PHP_EOL . $resultActions;
    }
References $bearsamppBins, $bearsamppLang, Lang\CONSOLE, Config\DISABLED, Lang\DOWNLOAD_MORE, Config\ENABLED, TplApp\getActionMulti(), TplAestan\getItemConsoleZ(), TplAestan\getItemLink(), TplAestan\getItemNotepad(), TplAestan\getItemSeparator(), TplApp\getMenu(), Util\getWebsiteUrl(), TplAestan\GLYPH_BROWSER, TplAestan\GLYPH_CHECK, TplAestan\GLYPH_CONSOLEZ, Lang\MENU_ENABLE, TplApp\SECTION_CALL, TplApp\SECTION_CONTENT, and Lang\VERSIONS.
getMenuNodejsVersions()
static TplAppNodejs::getMenuNodejsVersions () static
Generates the Node.js versions menu items and associated actions.
This method creates menu items for switching between different Node.js versions.
@global object $bearsamppBins Provides access to system binaries and their configurations.
Returns
string The generated menu items and actions for Node.js versions.
Definition at line 123 of file class.tpl.app.nodejs.php.
    {
        global $bearsamppBins;
        $items = '';
        $actions = '';
        foreach ($bearsamppBins->getNodejs()->getVersionList() as $version) {
            $tplSwitchNodejsVersion = TplApp::getActionMulti(
                self::ACTION_SWITCH_VERSION,
                array($version),
                array($version, $version == $bearsamppBins->getNodejs()->getVersion() ? TplAestan::GLYPH_CHECK : ''),
                false,
                get_called_class()
            );
            // Item
            $items .= $tplSwitchNodejsVersion[TplApp::SECTION_CALL] . PHP_EOL;
            // Action
            $actions .= PHP_EOL . $tplSwitchNodejsVersion[TplApp::SECTION_CONTENT];
        }
        return $items . $actions;
    }
References $bearsamppBins, TplApp\getActionMulti(), TplAestan\GLYPH_CHECK, TplApp\SECTION_CALL, and TplApp\SECTION_CONTENT.
process()
static TplAppNodejs::process () static
Processes and generates the Node.js menu.
This method generates the menu for Node.js, including options to enable/disable Node.js and switch versions.
@global object $bearsamppLang Provides language support for retrieving language-specific values. @global object $bearsamppBins Provides access to system binaries and their configurations.
Returns
array The generated menu for Node.js.
Definition at line 35 of file class.tpl.app.nodejs.php.
    {
        global $bearsamppLang, $bearsamppBins;
        return TplApp::getMenuEnable(
            $bearsamppLang->getValue(Lang::NODEJS),
            self::MENU,
            get_called_class(),
            $bearsamppBins->getNodejs()->isEnable()
        );
    }
References $bearsamppBins, $bearsamppLang, TplApp\getMenuEnable(), and Lang\NODEJS.
Referenced by TplApp\getSectionMenuLeft().
Field Documentation
ACTION_ENABLE
const TplAppNodejs::ACTION_ENABLE = 'enableNodejs'
Definition at line 22 of file class.tpl.app.nodejs.php.
ACTION_SWITCH_VERSION
const TplAppNodejs::ACTION_SWITCH_VERSION = 'switchNodejsVersion'
Definition at line 23 of file class.tpl.app.nodejs.php.
MENU
const TplAppNodejs::MENU = 'nodejs'
Definition at line 19 of file class.tpl.app.nodejs.php.
MENU_VERSIONS
const TplAppNodejs::MENU_VERSIONS = 'nodejsVersions'
Definition at line 20 of file class.tpl.app.nodejs.php.
The documentation for this class was generated from the following file:
E:/Bearsampp-development/sandbox/core/classes/tpls/app/class.tpl.app.nodejs.php