Bearsampp: ActionExt Class Reference
ActionExt Class Reference
Public Member Functions
__construct ($args)
Data Fields
const REFRESH = 'refresh'
const RELOAD = 'reload'
const START = 'start'
const STATUS_ERROR = 2
const STATUS_SUCCESS = 0
const STATUS_WARNING = 1
const STOP = 'stop'
Private Member Functions
addLog ($data)
getProcs ()
procRefresh ($args)
procReload ($args)
procStart ($args)
procStop ($args)
sendLogs ()
setStatus ($status)
Private Attributes
$logs = ''
$status = self::STATUS_SUCCESS
Detailed Description
Class ActionExt handles the execution of various extended actions.
Definition at line 13 of file class.action.ext.php.
Constructor & Destructor Documentation
__construct()
ActionExt::__construct ($args)
Constructor for the ActionExt class.
Parameters
array $args The command line arguments passed to the action.
Definition at line 41 of file class.action.ext.php.
    {
        if (!isset($args[0]) || empty($args[0])) {
            $this->addLog('No args defined');
            $this->addLog('Available args:');
            foreach ($this->getProcs() as $proc) {
                $this->addLog('- ' . $proc);
            }
            $this->setStatus(self::STATUS_ERROR);
            $this->sendLogs();
            return;
        }
        $action = $args[0];
        $newArgs = array();
        foreach ($args as $key => $arg) {
            if ($key > 0) {
                $newArgs[] = $arg;
            }
        }
        $method = 'proc' . ucfirst($action);
        if (!method_exists($this, $method)) {
            $this->addLog('Unknown arg: ' . $action);
            $this->addLog('Available args:');
            foreach ($this->getProcs() as $procName => $procDesc) {
                $this->addLog('- ' . $procName . ': ' . $procDesc);
            }
            $this->setStatus(self::STATUS_ERROR);
            $this->sendLogs();
            return;
        }
        call_user_func(array($this, $method), $newArgs);
        $this->sendLogs();
    }
References $proc, addLog(), getProcs(), sendLogs(), and setStatus().
Member Function Documentation
addLog()
ActionExt::addLog ($data) private
Adds a log entry to the logs.
Parameters
string $data The log entry to add.
Definition at line 99 of file class.action.ext.php.
    {
        $this->logs .= $data . "\n";
    }
Referenced by __construct(), procRefresh(), procReload(), procStart(), and procStop().
getProcs()
ActionExt::getProcs () private
Retrieves the list of available actions.
Returns
array The list of available actions.
Definition at line 84 of file class.action.ext.php.
    {
        return array(
            self::START,
            self::STOP,
            self::RELOAD,
            self::REFRESH
        );
    }
Referenced by __construct().
procRefresh()
ActionExt::procRefresh ($args) private
Refreshes the application by calling the reload action.
Parameters
array $args The command line arguments passed to the action.
Definition at line 217 of file class.action.ext.php.
    {
        global $bearsamppAction;
        if (!Util::isLaunched()) {
            $this->addLog(APP_TITLE . ' is not started.');
            $this->setStatus(self::STATUS_ERROR);
            return;
        }
        $bearsamppAction->call(Action::RELOAD);
    }
References $bearsamppAction, addLog(), APP_TITLE, Action\RELOAD, and setStatus().
procReload()
ActionExt::procReload ($args) private
Reloads the application by stopping and starting services.
Parameters
array $args The command line arguments passed to the action.
Definition at line 176 of file class.action.ext.php.
    {
        global $bearsamppRoot, $bearsamppBins, $bearsamppWinbinder;
        if (!Util::isLaunched()) {
            $this->addLog(APP_TITLE . ' is not started.');
            $bearsamppWinbinder->exec($bearsamppRoot->getExeFilePath(), null, false);
            $this->addLog('Start ' . APP_TITLE);
            $this->setStatus(self::STATUS_WARNING);
            return;
        }
        $this->addLog('Remove services');
        foreach ($bearsamppBins->getServices() as $sName => $service) {
            if ($service->delete()) {
                $this->addLog('- ' . $sName . ': OK');
            } else {
                $this->addLog('- ' . $sName . ': KO');
                $this->setStatus(self::STATUS_ERROR);
            }
        }
        Win32Ps::killBins();
        $this->addLog('Start services');
        foreach ($bearsamppBins->getServices() as $sName => $service) {
            $service->create();
            if ($service->start()) {
                $this->addLog('- ' . $sName . ': OK');
            } else {
                $this->addLog('- ' . $sName . ': KO');
                $this->setStatus(self::STATUS_ERROR);
            }
        }
    }
References $bearsamppBins, $bearsamppRoot, addLog(), APP_TITLE, Win32Ps\killBins(), and setStatus().
procStart()
ActionExt::procStart ($args) private
Starts the application.
Parameters
array $args The command line arguments passed to the action.
Definition at line 130 of file class.action.ext.php.
    {
        global $bearsamppRoot, $bearsamppWinbinder;
        if (!Util::isLaunched()) {
            $this->addLog('Starting ' . APP_TITLE);
            $bearsamppWinbinder->exec($bearsamppRoot->getExeFilePath(), null, false);
        } else {
            $this->addLog(APP_TITLE . ' already started');
            $this->setStatus(self::STATUS_WARNING);
        }
    }
References $bearsamppRoot, addLog(), APP_TITLE, and setStatus().
procStop()
ActionExt::procStop ($args) private
Stops the application and removes services.
Parameters
array $args The command line arguments passed to the action.
Definition at line 148 of file class.action.ext.php.
    {
        global $bearsamppBins;
        if (Util::isLaunched()) {
            $this->addLog('Remove services');
            foreach ($bearsamppBins->getServices() as $sName => $service) {
                if ($service->delete()) {
                    $this->addLog('- ' . $sName . ': OK');
                } else {
                    $this->addLog('- ' . $sName . ': KO');
                    $this->setStatus(self::STATUS_ERROR);
                }
            }
            $this->addLog('Stop ' . APP_TITLE);
            Batch::exitAppStandalone();
        } else {
            $this->addLog(APP_TITLE . ' already stopped');
            $this->setStatus(self::STATUS_WARNING);
        }
    }
References $bearsamppBins, addLog(), APP_TITLE, and setStatus().
sendLogs()
ActionExt::sendLogs () private
Sends the logs as a JSON-encoded response.
Definition at line 117 of file class.action.ext.php.
    {
        echo json_encode(array(
            'status' => $this->status,
            'response' => $this->logs
        ));
    }
Referenced by __construct().
setStatus()
ActionExt::setStatus ($status) private
Sets the status of the action.
Parameters
int $status The status code to set.
Definition at line 109 of file class.action.ext.php.
    {
        $this->status = $status;
    }
References $status.
Referenced by __construct(), procRefresh(), procReload(), procStart(), and procStop().
Field Documentation
$logs
ActionExt::$logs = '' private
Definition at line 34 of file class.action.ext.php.
$status
ActionExt::$status = self::STATUS_SUCCESS private
Definition at line 29 of file class.action.ext.php.
Referenced by setStatus().
REFRESH
const ActionExt::REFRESH = 'refresh'
Definition at line 19 of file class.action.ext.php.
RELOAD
const ActionExt::RELOAD = 'reload'
Definition at line 18 of file class.action.ext.php.
START
const ActionExt::START = 'start'
Definition at line 16 of file class.action.ext.php.
STATUS_ERROR
const ActionExt::STATUS_ERROR = 2
Definition at line 22 of file class.action.ext.php.
STATUS_SUCCESS
const ActionExt::STATUS_SUCCESS = 0
Definition at line 24 of file class.action.ext.php.
STATUS_WARNING
const ActionExt::STATUS_WARNING = 1
Definition at line 23 of file class.action.ext.php.
STOP
const ActionExt::STOP = 'stop'
Definition at line 17 of file class.action.ext.php.
The documentation for this class was generated from the following file:
E:/Bearsampp-development/sandbox/core/classes/actions/class.action.ext.php