Bearsampp: TplAppMariadb Class Reference
TplAppMariadb Class Reference
Static Public Member Functions
static getActionChangeMariadbPort ()
static getActionChangeMariadbRootPwd ()
static getActionEnableMariadb ($enable)
static getActionInstallMariadbService ()
static getActionRemoveMariadbService ()
static getActionSwitchMariadbVersion ($version)
static getMenuMariadb ()
static getMenuMariadbDebug ()
static getMenuMariadbService ()
static getMenuMariadbVersions ()
static process ()
Data Fields
const ACTION_CHANGE_PORT = 'changeMariadbPort'
const ACTION_CHANGE_ROOT_PWD = 'changeMariadbRootPwd'
const ACTION_ENABLE = 'enableMariadb'
const ACTION_INSTALL_SERVICE = 'installMariadbService'
const ACTION_REMOVE_SERVICE = 'removeMariadbService'
const ACTION_SWITCH_VERSION = 'switchMariadbVersion'
const MENU = 'mariadb'
const MENU_DEBUG = 'mariadbDebug'
const MENU_SERVICE = 'mariadbService'
const MENU_VERSIONS = 'mariadbVersions'
Detailed Description
Definition at line 10 of file class.tpl.app.mariadb.php.
Member Function Documentation
getActionChangeMariadbPort()
static TplAppMariadb::getActionChangeMariadbPort () static
Generates the action to change the MariaDB port.
This method creates the action string for changing the MariaDB port. It uses the global binaries object to retrieve the necessary values.
@global object $bearsamppBins Provides access to system binaries and their configurations.
Returns
string The generated action string for changing the MariaDB port.
Definition at line 295 of file class.tpl.app.mariadb.php.
    {
        global $bearsamppBins;
        return TplApp::getActionRun(Action::CHANGE_PORT, array($bearsamppBins->getMariadb()->getName())) . PHP_EOL .
            TplAppReload::getActionReload();
    }
References $bearsamppBins, Action\CHANGE_PORT, TplAppReload\getActionReload(), and TplApp\getActionRun().
getActionChangeMariadbRootPwd()
static TplAppMariadb::getActionChangeMariadbRootPwd () static
Generates the action to change the MariaDB root password.
This method creates the action string for changing the MariaDB root password. It uses the global binaries object to retrieve the necessary values.
@global object $bearsamppBins Provides access to system binaries and their configurations.
Returns
string The generated action string for changing the MariaDB root password.
Definition at line 313 of file class.tpl.app.mariadb.php.
    {
        global $bearsamppBins;
        return TplApp::getActionRun(Action::CHANGE_DB_ROOT_PWD, array($bearsamppBins->getMariadb()->getName())) . PHP_EOL .
            TplAppReload::getActionReload();
    }
References $bearsamppBins, Action\CHANGE_DB_ROOT_PWD, TplAppReload\getActionReload(), and TplApp\getActionRun().
getActionEnableMariadb()
static TplAppMariadb::getActionEnableMariadb ($enable) static
Generates the action to enable or disable MariaDB.
This method creates the action string for enabling or disabling MariaDB. It uses the global binaries object to retrieve the necessary values.
@global object $bearsamppBins Provides access to system binaries and their configurations.
Parameters
int $enable The enable flag (1 for enable, 0 for disable).
Returns
string The generated action string for enabling or disabling MariaDB.
Definition at line 158 of file class.tpl.app.mariadb.php.
    {
        global $bearsamppBins;
        return TplApp::getActionRun(Action::ENABLE, array($bearsamppBins->getMariadb()->getName(), $enable)) . PHP_EOL .
            TplAppReload::getActionReload();
    }
References $bearsamppBins, Action\ENABLE, TplAppReload\getActionReload(), and TplApp\getActionRun().
getActionInstallMariadbService()
static TplAppMariadb::getActionInstallMariadbService () static
Generates the action to install the MariaDB service.
This method creates the action string for installing the MariaDB service.
Returns
string The generated action string for installing the MariaDB service.
Definition at line 328 of file class.tpl.app.mariadb.php.
    {
        return TplApp::getActionRun(Action::SERVICE, array(BinMariadb::SERVICE_NAME, ActionService::INSTALL)) . PHP_EOL .
            TplAppReload::getActionReload();
    }
References TplAppReload\getActionReload(), TplApp\getActionRun(), ActionService\INSTALL, Action\SERVICE, and BinMariadb\SERVICE_NAME.
getActionRemoveMariadbService()
static TplAppMariadb::getActionRemoveMariadbService () static
Generates the action to remove the MariaDB service.
This method creates the action string for removing the MariaDB service.
Returns
string The generated action string for removing the MariaDB service.
Definition at line 341 of file class.tpl.app.mariadb.php.
    {
        return TplApp::getActionRun(Action::SERVICE, array(BinMariadb::SERVICE_NAME, ActionService::REMOVE)) . PHP_EOL .
            TplAppReload::getActionReload();
    }
References TplAppReload\getActionReload(), TplApp\getActionRun(), ActionService\REMOVE, Action\SERVICE, and BinMariadb\SERVICE_NAME.
getActionSwitchMariadbVersion()
static TplAppMariadb::getActionSwitchMariadbVersion ($version) static
Generates the action to switch the MariaDB version.
This method creates the action string for switching the MariaDB version. It uses the global binaries object to retrieve the necessary values.
@global object $bearsamppBins Provides access to system binaries and their configurations.
Parameters
string $version The version to switch to.
Returns
string The generated action string for switching the MariaDB version.
Definition at line 178 of file class.tpl.app.mariadb.php.
    {
        global $bearsamppBins;
        return TplApp::getActionRun(Action::SWITCH_VERSION, array($bearsamppBins->getMariadb()->getName(), $version)) . PHP_EOL .
            TplAppReload::getActionReload() . PHP_EOL;
    }
References $bearsamppBins, TplAppReload\getActionReload(), TplApp\getActionRun(), and Action\SWITCH_VERSION.
getMenuMariadb()
static TplAppMariadb::getMenuMariadb () static
Generates the MariaDB menu items and actions.
This method creates menu items and actions for managing MariaDB, including enabling/disabling, switching versions, managing services, and debugging. It uses the global language, binaries, and tools objects to retrieve the necessary values.
@global object $bearsamppBins Provides access to system binaries and their configurations. @global object $bearsamppLang Provides language support for retrieving language-specific values. @global object $bearsamppTools Provides access to various tools and utilities.
Returns
string The generated MariaDB menu items and actions.
Definition at line 55 of file class.tpl.app.mariadb.php.
    {
        global $bearsamppBins, $bearsamppLang, $bearsamppTools;
        $resultItems = $resultActions = '';
        $isEnabled = $bearsamppBins->getMariadb()->isEnable();
        // Download
        $resultItems .= TplAestan::getItemLink( $bearsamppLang->getValue(Lang::DOWNLOAD_MORE),
            Util::getWebsiteUrl('module/mariadb', '#releases'),
            false,
            TplAestan::GLYPH_BROWSER
        ) . PHP_EOL;
        // Enable
        $tplEnable = TplApp::getActionMulti(
            self::ACTION_ENABLE, array($isEnabled ? Config::DISABLED : Config::ENABLED),
            array($bearsamppLang->getValue(Lang::MENU_ENABLE), $isEnabled ? TplAestan::GLYPH_CHECK : ''),
            false, get_called_class()
        );
        $resultItems .= $tplEnable[TplApp::SECTION_CALL] . PHP_EOL;
        $resultActions .= $tplEnable[TplApp::SECTION_CONTENT] . PHP_EOL;
        if ($isEnabled) {
            $resultItems .= TplAestan::getItemSeparator() . PHP_EOL;
            // Versions
            $tplVersions = TplApp::getMenu($bearsamppLang->getValue(Lang::VERSIONS), self::MENU_VERSIONS, get_called_class());
            $resultItems .= $tplVersions[TplApp::SECTION_CALL] . PHP_EOL;
            $resultActions .= $tplVersions[TplApp::SECTION_CONTENT] . PHP_EOL;
            // Service
            $tplService = TplApp::getMenu($bearsamppLang->getValue(Lang::SERVICE), self::MENU_SERVICE, get_called_class());
            $resultItems .= $tplService[TplApp::SECTION_CALL] . PHP_EOL;
            $resultActions .= $tplService[TplApp::SECTION_CONTENT] . PHP_EOL;
            // Debug
            $tplDebug = TplApp::getMenu($bearsamppLang->getValue(Lang::DEBUG), self::MENU_DEBUG, get_called_class());
            $resultItems .= $tplDebug[TplApp::SECTION_CALL] . PHP_EOL;
            $resultActions .= $tplDebug[TplApp::SECTION_CONTENT];
            // Console
            $resultItems .= TplAestan::getItemConsoleZ(
                $bearsamppLang->getValue(Lang::CONSOLE),
                TplAestan::GLYPH_CONSOLEZ,
                $bearsamppTools->getConsoleZ()->getTabTitleMariadb()
            ) . PHP_EOL;
            // Conf
            $resultItems .= TplAestan::getItemNotepad(basename($bearsamppBins->getMariadb()->getConf()), $bearsamppBins->getMariadb()->getConf()) . PHP_EOL;
            // Errors log
            $resultItems .= TplAestan::getItemNotepad($bearsamppLang->getValue(Lang::MENU_ERROR_LOGS), $bearsamppBins->getMariadb()->getErrorLog()) . PHP_EOL;
        }
        return $resultItems . PHP_EOL . $resultActions;
    }
References $bearsamppBins, $bearsamppLang, Lang\CONSOLE, Lang\DEBUG, Config\DISABLED, Lang\DOWNLOAD_MORE, Config\ENABLED, TplApp\getActionMulti(), TplAestan\getItemConsoleZ(), TplAestan\getItemLink(), TplAestan\getItemNotepad(), TplAestan\getItemSeparator(), TplApp\getMenu(), Util\getWebsiteUrl(), TplAestan\GLYPH_BROWSER, TplAestan\GLYPH_CHECK, TplAestan\GLYPH_CONSOLEZ, Lang\MENU_ENABLE, Lang\MENU_ERROR_LOGS, TplApp\SECTION_CALL, TplApp\SECTION_CONTENT, Lang\SERVICE, and Lang\VERSIONS.
getMenuMariadbDebug()
static TplAppMariadb::getMenuMariadbDebug () static
Generates the MariaDB debug menu items and actions.
This method creates menu items and actions for debugging MariaDB, including checking the version, variables, and syntax. It uses the global language object to retrieve the necessary values.
@global object $bearsamppLang Provides language support for retrieving language-specific values.
Returns
string The generated MariaDB debug menu items and actions.
Definition at line 267 of file class.tpl.app.mariadb.php.
    {
        global $bearsamppLang;
        return TplApp::getActionRun(
            Action::DEBUG_MARIADB, array(BinMariadb::CMD_VERSION),
            array($bearsamppLang->getValue(Lang::DEBUG_MARIADB_VERSION), TplAestan::GLYPH_DEBUG)
        ) . PHP_EOL .
        TplApp::getActionRun(
            Action::DEBUG_MARIADB, array(BinMariadb::CMD_VARIABLES),
            array($bearsamppLang->getValue(Lang::DEBUG_MARIADB_VARIABLES), TplAestan::GLYPH_DEBUG)
        ) . PHP_EOL .
        TplApp::getActionRun(
            Action::DEBUG_MARIADB, array(BinMariadb::CMD_SYNTAX_CHECK),
            array($bearsamppLang->getValue(Lang::DEBUG_MARIADB_SYNTAX_CHECK), TplAestan::GLYPH_DEBUG)
        ) . PHP_EOL;
    }
References $bearsamppLang, BinMariadb\CMD_SYNTAX_CHECK, BinMariadb\CMD_VARIABLES, BinMariadb\CMD_VERSION, Action\DEBUG_MARIADB, Lang\DEBUG_MARIADB_SYNTAX_CHECK, Lang\DEBUG_MARIADB_VARIABLES, Lang\DEBUG_MARIADB_VERSION, TplApp\getActionRun(), and TplAestan\GLYPH_DEBUG.
getMenuMariadbService()
static TplAppMariadb::getMenuMariadbService () static
Generates the MariaDB service menu items and actions.
This method creates menu items and actions for managing the MariaDB service, including starting, stopping, restarting, changing the port, and changing the root password. It uses the global language and binaries objects to retrieve the necessary values.
@global object $bearsamppLang Provides language support for retrieving language-specific values. @global object $bearsamppBins Provides access to system binaries and their configurations.
Returns
string The generated MariaDB service menu items and actions.
Definition at line 198 of file class.tpl.app.mariadb.php.
    {
        global $bearsamppLang, $bearsamppBins;
        $tplChangePort = TplApp::getActionMulti(
            self::ACTION_CHANGE_PORT, null,
            array($bearsamppLang->getValue(Lang::MENU_CHANGE_PORT), TplAestan::GLYPH_NETWORK),
            false, get_called_class()
        );
        $isInstalled = $bearsamppBins->getMariadb()->getService()->isInstalled();
        $result = TplAestan::getItemActionServiceStart($bearsamppBins->getMariadb()->getService()->getName()) . PHP_EOL .
            TplAestan::getItemActionServiceStop($bearsamppBins->getMariadb()->getService()->getName()) . PHP_EOL .
            TplAestan::getItemActionServiceRestart($bearsamppBins->getMariadb()->getService()->getName()) . PHP_EOL .
            TplAestan::getItemSeparator() . PHP_EOL .
            TplApp::getActionRun(
                Action::CHECK_PORT, array($bearsamppBins->getMariadb()->getName(), $bearsamppBins->getMariadb()->getPort()),
                array(sprintf($bearsamppLang->getValue(Lang::MENU_CHECK_PORT), $bearsamppBins->getMariadb()->getPort()), TplAestan::GLYPH_LIGHT)
            ) . PHP_EOL .
            $tplChangePort[TplApp::SECTION_CALL] . PHP_EOL;
        $tplChangeRootPwd = null;
        if ($isInstalled) {
            $tplChangeRootPwd = TplApp::getActionMulti(
                self::ACTION_CHANGE_ROOT_PWD, null,
                array($bearsamppLang->getValue(Lang::MENU_CHANGE_ROOT_PWD), TplAestan::GLYPH_PASSWORD),
                !$isInstalled, get_called_class()
            );
            $result .= $tplChangeRootPwd[TplApp::SECTION_CALL] . PHP_EOL;
        }
        if (!$isInstalled) {
            $tplInstallService = TplApp::getActionMulti(
                self::ACTION_INSTALL_SERVICE, null,
                array($bearsamppLang->getValue(Lang::MENU_INSTALL_SERVICE), TplAestan::GLYPH_SERVICE_INSTALL),
                $isInstalled, get_called_class()
            );
            $result .= $tplInstallService[TplApp::SECTION_CALL] . PHP_EOL . PHP_EOL .
            $tplInstallService[TplApp::SECTION_CONTENT] . PHP_EOL;
        } else {
            $tplRemoveService = TplApp::getActionMulti(
                self::ACTION_REMOVE_SERVICE, null,
                array($bearsamppLang->getValue(Lang::MENU_REMOVE_SERVICE), TplAestan::GLYPH_SERVICE_REMOVE),
                !$isInstalled, get_called_class()
            );
            $result .= $tplRemoveService[TplApp::SECTION_CALL] . PHP_EOL . PHP_EOL .
            $tplRemoveService[TplApp::SECTION_CONTENT] . PHP_EOL;
        }
        $result .= $tplChangePort[TplApp::SECTION_CONTENT] . PHP_EOL .
            ($tplChangeRootPwd != null ? $tplChangeRootPwd[TplApp::SECTION_CONTENT] . PHP_EOL : '');
        return $result;
    }
References $bearsamppBins, $bearsamppLang, $result, Action\CHECK_PORT, TplApp\getActionMulti(), TplApp\getActionRun(), TplAestan\getItemActionServiceRestart(), TplAestan\getItemActionServiceStart(), TplAestan\getItemActionServiceStop(), TplAestan\getItemSeparator(), TplAestan\GLYPH_LIGHT, TplAestan\GLYPH_NETWORK, TplAestan\GLYPH_PASSWORD, TplAestan\GLYPH_SERVICE_INSTALL, TplAestan\GLYPH_SERVICE_REMOVE, Lang\MENU_CHANGE_PORT, Lang\MENU_CHANGE_ROOT_PWD, Lang\MENU_CHECK_PORT, Lang\MENU_INSTALL_SERVICE, Lang\MENU_REMOVE_SERVICE, TplApp\SECTION_CALL, and TplApp\SECTION_CONTENT.
getMenuMariadbVersions()
static TplAppMariadb::getMenuMariadbVersions () static
Generates the MariaDB versions menu items and actions.
This method creates menu items and actions for switching between different MariaDB versions. It uses the global binaries object to retrieve the available versions.
@global object $bearsamppBins Provides access to system binaries and their configurations.
Returns
string The generated MariaDB versions menu items and actions.
Definition at line 123 of file class.tpl.app.mariadb.php.
    {
        global $bearsamppBins;
        $items = '';
        $actions = '';
        foreach ($bearsamppBins->getMariadb()->getVersionList() as $version) {
            $tplSwitchMariadbVersion = TplApp::getActionMulti(
                self::ACTION_SWITCH_VERSION, array($version),
                array($version, $version == $bearsamppBins->getMariadb()->getVersion() ? TplAestan::GLYPH_CHECK : ''),
                false, get_called_class()
            );
            // Item
            $items .= $tplSwitchMariadbVersion[TplApp::SECTION_CALL] . PHP_EOL;
            // Action
            $actions .= PHP_EOL . $tplSwitchMariadbVersion[TplApp::SECTION_CONTENT];
        }
        return $items . $actions;
    }
References $bearsamppBins, TplApp\getActionMulti(), TplAestan\GLYPH_CHECK, TplApp\SECTION_CALL, and TplApp\SECTION_CONTENT.
process()
static TplAppMariadb::process () static
Processes the MariaDB menu.
This method generates the MariaDB menu and determines if MariaDB is enabled. It uses the global language and binaries objects to retrieve the necessary values.
@global object $bearsamppLang Provides language support for retrieving language-specific values. @global object $bearsamppBins Provides access to system binaries and their configurations.
Returns
array The generated MariaDB menu.
Definition at line 35 of file class.tpl.app.mariadb.php.
    {
        global $bearsamppLang, $bearsamppBins;
        return TplApp::getMenuEnable($bearsamppLang->getValue(Lang::MARIADB), self::MENU, get_called_class(), $bearsamppBins->getMariadb()->isEnable());
    }
References $bearsamppBins, $bearsamppLang, TplApp\getMenuEnable(), and Lang\MARIADB.
Referenced by TplApp\getSectionMenuLeft().
Field Documentation
ACTION_CHANGE_PORT
const TplAppMariadb::ACTION_CHANGE_PORT = 'changeMariadbPort'
Definition at line 19 of file class.tpl.app.mariadb.php.
ACTION_CHANGE_ROOT_PWD
const TplAppMariadb::ACTION_CHANGE_ROOT_PWD = 'changeMariadbRootPwd'
Definition at line 20 of file class.tpl.app.mariadb.php.
ACTION_ENABLE
const TplAppMariadb::ACTION_ENABLE = 'enableMariadb'
Definition at line 17 of file class.tpl.app.mariadb.php.
ACTION_INSTALL_SERVICE
const TplAppMariadb::ACTION_INSTALL_SERVICE = 'installMariadbService'
Definition at line 21 of file class.tpl.app.mariadb.php.
ACTION_REMOVE_SERVICE
const TplAppMariadb::ACTION_REMOVE_SERVICE = 'removeMariadbService'
Definition at line 22 of file class.tpl.app.mariadb.php.
ACTION_SWITCH_VERSION
const TplAppMariadb::ACTION_SWITCH_VERSION = 'switchMariadbVersion'
Definition at line 18 of file class.tpl.app.mariadb.php.
MENU
const TplAppMariadb::MENU = 'mariadb'
Definition at line 12 of file class.tpl.app.mariadb.php.
MENU_DEBUG
const TplAppMariadb::MENU_DEBUG = 'mariadbDebug'
Definition at line 15 of file class.tpl.app.mariadb.php.
MENU_SERVICE
const TplAppMariadb::MENU_SERVICE = 'mariadbService'
Definition at line 14 of file class.tpl.app.mariadb.php.
MENU_VERSIONS
const TplAppMariadb::MENU_VERSIONS = 'mariadbVersions'
Definition at line 13 of file class.tpl.app.mariadb.php.
The documentation for this class was generated from the following file:
E:/Bearsampp-development/sandbox/core/classes/tpls/app/class.tpl.app.mariadb.php