Bearsampp: TplAppApps Class Reference
TplAppApps Class Reference
Static Public Member Functions
static getMenuApps ()
static process ()
Data Fields
const MENU = 'apps'
Detailed Description
Class TplAppApps
This class provides methods to generate and manage the "Apps" menu within the Bearsampp application. It includes functionalities for creating the menu and adding specific application links.
Definition at line 16 of file class.tpl.app.apps.php.
Member Function Documentation
getMenuApps()
static TplAppApps::getMenuApps () static
Generates the content of the "Apps" menu.
This method generates the content of the "Apps" menu by adding links to various applications such as Adminer, phpMyAdmin, phpPgAdmin, and Webgrind.
@global object $bearsamppLang Provides language support for retrieving language-specific values.
Returns
string The generated menu content as a concatenated string.
Definition at line 49 of file class.tpl.app.apps.php.
    {
        global $bearsamppLang;
        return TplAestan::getItemLink(
                $bearsamppLang->getValue(Lang::ADMINER),
                'adminer/',
                true
            ) . PHP_EOL .
            TplAestan::getItemLink(
                $bearsamppLang->getValue(Lang::PHPMYADMIN),
                'phpmyadmin/',
                true
            ) . PHP_EOL .
            TplAestan::getItemLink(
                $bearsamppLang->getValue(Lang::PHPPGADMIN),
                'phppgadmin/',
                true
                ) . PHP_EOL .
            TplAestan::getItemLink(
                $bearsamppLang->getValue(Lang::WEBGRIND),
                'webgrind/',
                true
            );
    }
References $bearsamppLang, Lang\ADMINER, TplAestan\getItemLink(), Lang\PHPMYADMIN, Lang\PHPPGADMIN, and Lang\WEBGRIND.
process()
static TplAppApps::process () static
Processes and generates the "Apps" menu.
This method generates the "Apps" menu by calling the getMenu method from the TplApp class.
@global object $bearsamppLang Provides language support for retrieving language-specific values.
Returns
array An array containing the call string and the menu content.
Definition at line 32 of file class.tpl.app.apps.php.
    {
        global $bearsamppLang;
        return TplApp::getMenu($bearsamppLang->getValue(Lang::APPS), self::MENU, get_called_class());
    }
References $bearsamppLang, Lang\APPS, and TplApp\getMenu().
Referenced by TplApp\getSectionMenuLeft().
Field Documentation
MENU
const TplAppApps::MENU = 'apps'
Constant representing the menu identifier for apps.
Definition at line 21 of file class.tpl.app.apps.php.
The documentation for this class was generated from the following file:
E:/Bearsampp-development/sandbox/core/classes/tpls/app/class.tpl.app.apps.php