Bearsampp: TplAppMysql Class Reference
TplAppMysql Class Reference
Static Public Member Functions
static getActionChangeMysqlPort ()
static getActionChangeMysqlRootPwd ()
static getActionEnableMysql ($enable)
static getActionInstallMysqlService ()
static getActionRemoveMysqlService ()
static getActionSwitchMysqlVersion ($version)
static getMenuMysql ()
static getMenuMysqlDebug ()
static getMenuMysqlService ()
static getMenuMysqlVersions ()
static process ()
Data Fields
const ACTION_CHANGE_PORT = 'changeMysqlPort'
const ACTION_CHANGE_ROOT_PWD = 'changeMysqlRootPwd'
const ACTION_ENABLE = 'enableMysql'
const ACTION_INSTALL_SERVICE = 'installMysqlService'
const ACTION_REMOVE_SERVICE = 'removeMysqlService'
const ACTION_SWITCH_VERSION = 'switchMysqlVersion'
const MENU = 'mysql'
const MENU_DEBUG = 'mysqlDebug'
const MENU_SERVICE = 'mysqlService'
const MENU_VERSIONS = 'mysqlVersions'
Detailed Description
Class TplAppMysql
This class provides methods to generate and manage menu items, actions, and sections related to MySQL within the Bearsampp application. It includes functionalities for enabling/disabling MySQL, switching versions, changing ports, managing services, and debugging.
Definition at line 17 of file class.tpl.app.mysql.php.
Member Function Documentation
getActionChangeMysqlPort()
static TplAppMysql::getActionChangeMysqlPort () static
Generates the action to change MySQL port.
This method creates the action string for changing the MySQL port.
@global object $bearsamppBins Provides access to system binaries and their configurations.
Returns
string The generated action string for changing MySQL port.
Definition at line 294 of file class.tpl.app.mysql.php.
    {
        global $bearsamppBins;
        return TplApp::getActionRun(Action::CHANGE_PORT, array($bearsamppBins->getMysql()->getName())) . PHP_EOL .
            TplAppReload::getActionReload();
    }
References $bearsamppBins, Action\CHANGE_PORT, TplAppReload\getActionReload(), and TplApp\getActionRun().
getActionChangeMysqlRootPwd()
static TplAppMysql::getActionChangeMysqlRootPwd () static
Generates the action to change MySQL root password.
This method creates the action string for changing the MySQL root password.
@global object $bearsamppBins Provides access to system binaries and their configurations.
Returns
string The generated action string for changing MySQL root password.
Definition at line 311 of file class.tpl.app.mysql.php.
    {
        global $bearsamppBins;
        return TplApp::getActionRun(Action::CHANGE_DB_ROOT_PWD, array($bearsamppBins->getMysql()->getName())) . PHP_EOL .
            TplAppReload::getActionReload();
    }
References $bearsamppBins, Action\CHANGE_DB_ROOT_PWD, TplAppReload\getActionReload(), and TplApp\getActionRun().
getActionEnableMysql()
static TplAppMysql::getActionEnableMysql ($enable) static
Generates the action to enable or disable MySQL.
This method creates the action string for enabling or disabling MySQL.
@global object $bearsamppBins Provides access to system binaries and their configurations.
Parameters
int $enable The enable/disable flag (1 for enable, 0 for disable).
Returns
string The generated action string for enabling/disabling MySQL.
Definition at line 161 of file class.tpl.app.mysql.php.
    {
        global $bearsamppBins;
        return TplApp::getActionRun(Action::ENABLE, array($bearsamppBins->getMysql()->getName(), $enable)) . PHP_EOL .
            TplAppReload::getActionReload();
    }
References $bearsamppBins, Action\ENABLE, TplAppReload\getActionReload(), and TplApp\getActionRun().
getActionInstallMysqlService()
static TplAppMysql::getActionInstallMysqlService () static
Generates the action to install MySQL service.
This method creates the action string for installing the MySQL service.
Returns
string The generated action string for installing MySQL service.
Definition at line 326 of file class.tpl.app.mysql.php.
    {
        return TplApp::getActionRun(Action::SERVICE, array(BinMysql::SERVICE_NAME, ActionService::INSTALL)) . PHP_EOL .
            TplAppReload::getActionReload();
    }
References TplAppReload\getActionReload(), TplApp\getActionRun(), ActionService\INSTALL, Action\SERVICE, and BinMysql\SERVICE_NAME.
getActionRemoveMysqlService()
static TplAppMysql::getActionRemoveMysqlService () static
Generates the action to remove MySQL service.
This method creates the action string for removing the MySQL service.
Returns
string The generated action string for removing MySQL service.
Definition at line 339 of file class.tpl.app.mysql.php.
    {
        return TplApp::getActionRun(Action::SERVICE, array(BinMysql::SERVICE_NAME, ActionService::REMOVE)) . PHP_EOL .
            TplAppReload::getActionReload();
    }
References TplAppReload\getActionReload(), TplApp\getActionRun(), ActionService\REMOVE, Action\SERVICE, and BinMysql\SERVICE_NAME.
getActionSwitchMysqlVersion()
static TplAppMysql::getActionSwitchMysqlVersion ($version) static
Generates the action to switch MySQL version.
This method creates the action string for switching to a different MySQL version.
@global object $bearsamppBins Provides access to system binaries and their configurations.
Parameters
string $version The version to switch to.
Returns
string The generated action string for switching MySQL version.
Definition at line 179 of file class.tpl.app.mysql.php.
    {
        global $bearsamppBins;
        return TplApp::getActionRun(Action::SWITCH_VERSION, array($bearsamppBins->getMysql()->getName(), $version)) . PHP_EOL .
            TplAppReload::getActionReload() . PHP_EOL;
    }
References $bearsamppBins, TplAppReload\getActionReload(), TplApp\getActionRun(), and Action\SWITCH_VERSION.
getMenuMysql()
static TplAppMysql::getMenuMysql () static
Generates the MySQL menu items and actions.
This method creates menu items and actions for MySQL, including download links, enabling/disabling, version switching, service management, debugging, and configuration file access.
@global object $bearsamppBins Provides access to system binaries and their configurations. @global object $bearsamppLang Provides language support for retrieving language-specific values. @global object $bearsamppTools Provides access to various tools used in the application.
Returns
string The generated MySQL menu items and actions.
Definition at line 61 of file class.tpl.app.mysql.php.
    {
        global $bearsamppBins, $bearsamppLang, $bearsamppTools;
        $resultItems = $resultActions = '';
        $isEnabled = $bearsamppBins->getMysql()->isEnable();
        // Download
        $resultItems .= TplAestan::getItemLink( $bearsamppLang->getValue(Lang::DOWNLOAD_MORE),
            Util::getWebsiteUrl('module/mysql', '#releases'),
            false,
            TplAestan::GLYPH_BROWSER
        ) . PHP_EOL;
        // Enable
        $tplEnable = TplApp::getActionMulti(
            self::ACTION_ENABLE, array($isEnabled ? Config::DISABLED : Config::ENABLED),
            array($bearsamppLang->getValue(Lang::MENU_ENABLE), $isEnabled ? TplAestan::GLYPH_CHECK : ''),
            false, get_called_class()
        );
        $resultItems .= $tplEnable[TplApp::SECTION_CALL] . PHP_EOL;
        $resultActions .= $tplEnable[TplApp::SECTION_CONTENT] . PHP_EOL;
        if ($isEnabled) {
            $resultItems .= TplAestan::getItemSeparator() . PHP_EOL;
            // Versions
            $tplVersions = TplApp::getMenu($bearsamppLang->getValue(Lang::VERSIONS), self::MENU_VERSIONS, get_called_class());
            $resultItems .= $tplVersions[TplApp::SECTION_CALL] . PHP_EOL;
            $resultActions .= $tplVersions[TplApp::SECTION_CONTENT] . PHP_EOL;
            // Service
            $tplService = TplApp::getMenu($bearsamppLang->getValue(Lang::SERVICE), self::MENU_SERVICE, get_called_class());
            $resultItems .= $tplService[TplApp::SECTION_CALL] . PHP_EOL;
            $resultActions .= $tplService[TplApp::SECTION_CONTENT] . PHP_EOL;
            // Debug
            $tplDebug = TplApp::getMenu($bearsamppLang->getValue(Lang::DEBUG), self::MENU_DEBUG, get_called_class());
            $resultItems .= $tplDebug[TplApp::SECTION_CALL] . PHP_EOL;
            $resultActions .= $tplDebug[TplApp::SECTION_CONTENT];
            // Console
            $resultItems .= TplAestan::getItemConsoleZ(
                $bearsamppLang->getValue(Lang::CONSOLE),
                TplAestan::GLYPH_CONSOLEZ,
                $bearsamppTools->getConsoleZ()->getTabTitleMysql()
            ) . PHP_EOL;
            // Conf
            $resultItems .= TplAestan::getItemNotepad(basename($bearsamppBins->getMysql()->getConf()), $bearsamppBins->getMysql()->getConf()) . PHP_EOL;
            // Errors log
            $resultItems .= TplAestan::getItemNotepad($bearsamppLang->getValue(Lang::MENU_ERROR_LOGS), $bearsamppBins->getMysql()->getErrorLog()) . PHP_EOL;
        }
        return $resultItems . PHP_EOL . $resultActions;
    }
References $bearsamppBins, $bearsamppLang, Lang\CONSOLE, Lang\DEBUG, Config\DISABLED, Lang\DOWNLOAD_MORE, Config\ENABLED, TplApp\getActionMulti(), TplAestan\getItemConsoleZ(), TplAestan\getItemLink(), TplAestan\getItemNotepad(), TplAestan\getItemSeparator(), TplApp\getMenu(), Util\getWebsiteUrl(), TplAestan\GLYPH_BROWSER, TplAestan\GLYPH_CHECK, TplAestan\GLYPH_CONSOLEZ, Lang\MENU_ENABLE, Lang\MENU_ERROR_LOGS, TplApp\SECTION_CALL, TplApp\SECTION_CONTENT, Lang\SERVICE, and Lang\VERSIONS.
getMenuMysqlDebug()
static TplAppMysql::getMenuMysqlDebug () static
Generates the MySQL debug menu.
This method creates menu items and actions for debugging MySQL, including checking version, variables, and syntax.
@global object $bearsamppLang Provides language support for retrieving language-specific values.
Returns
string The generated MySQL debug menu items and actions.
Definition at line 267 of file class.tpl.app.mysql.php.
    {
        global $bearsamppLang;
        return TplApp::getActionRun(
            Action::DEBUG_MYSQL, array(BinMysql::CMD_VERSION),
            array($bearsamppLang->getValue(Lang::DEBUG_MYSQL_VERSION), TplAestan::GLYPH_DEBUG)
        ) . PHP_EOL .
        TplApp::getActionRun(
            Action::DEBUG_MYSQL, array(BinMysql::CMD_VARIABLES),
            array($bearsamppLang->getValue(Lang::DEBUG_MYSQL_VARIABLES), TplAestan::GLYPH_DEBUG)
        ) . PHP_EOL .
        TplApp::getActionRun(
            Action::DEBUG_MYSQL, array(BinMysql::CMD_SYNTAX_CHECK),
            array($bearsamppLang->getValue(Lang::DEBUG_MYSQL_SYNTAX_CHECK), TplAestan::GLYPH_DEBUG)
        ) . PHP_EOL;
    }
References $bearsamppLang, BinMysql\CMD_SYNTAX_CHECK, BinMysql\CMD_VARIABLES, BinMysql\CMD_VERSION, Action\DEBUG_MYSQL, Lang\DEBUG_MYSQL_SYNTAX_CHECK, Lang\DEBUG_MYSQL_VARIABLES, Lang\DEBUG_MYSQL_VERSION, TplApp\getActionRun(), and TplAestan\GLYPH_DEBUG.
getMenuMysqlService()
static TplAppMysql::getMenuMysqlService () static
Generates the MySQL service menu.
This method creates menu items and actions for managing MySQL services, including starting, stopping, restarting, changing ports, and managing root passwords.
@global object $bearsamppLang Provides language support for retrieving language-specific values. @global object $bearsamppBins Provides access to system binaries and their configurations.
Returns
string The generated MySQL service menu items and actions.
Definition at line 198 of file class.tpl.app.mysql.php.
    {
        global $bearsamppLang, $bearsamppBins;
        $tplChangePort = TplApp::getActionMulti(
            self::ACTION_CHANGE_PORT, null,
            array($bearsamppLang->getValue(Lang::MENU_CHANGE_PORT), TplAestan::GLYPH_NETWORK),
            false, get_called_class()
        );
        $isInstalled = $bearsamppBins->getMysql()->getService()->isInstalled();
        $result = TplAestan::getItemActionServiceStart($bearsamppBins->getMysql()->getService()->getName()) . PHP_EOL .
            TplAestan::getItemActionServiceStop($bearsamppBins->getMysql()->getService()->getName()) . PHP_EOL .
            TplAestan::getItemActionServiceRestart($bearsamppBins->getMysql()->getService()->getName()) . PHP_EOL .
            TplAestan::getItemSeparator() . PHP_EOL .
            TplApp::getActionRun(
                Action::CHECK_PORT, array($bearsamppBins->getMysql()->getName(), $bearsamppBins->getMysql()->getPort()),
                array(sprintf($bearsamppLang->getValue(Lang::MENU_CHECK_PORT), $bearsamppBins->getMysql()->getPort()), TplAestan::GLYPH_LIGHT)
            ) . PHP_EOL .
            $tplChangePort[TplApp::SECTION_CALL] . PHP_EOL;
        $tplChangeRootPwd = null;
        if ($isInstalled) {
            $tplChangeRootPwd = TplApp::getActionMulti(
                self::ACTION_CHANGE_ROOT_PWD, null,
                array($bearsamppLang->getValue(Lang::MENU_CHANGE_ROOT_PWD), TplAestan::GLYPH_PASSWORD),
                !$isInstalled, get_called_class()
            );
            $result .= $tplChangeRootPwd[TplApp::SECTION_CALL] . PHP_EOL;
        }
        if (!$isInstalled) {
            $tplInstallService = TplApp::getActionMulti(
                self::ACTION_INSTALL_SERVICE, null,
                array($bearsamppLang->getValue(Lang::MENU_INSTALL_SERVICE), TplAestan::GLYPH_SERVICE_INSTALL),
                $isInstalled, get_called_class()
            );
            $result .= $tplInstallService[TplApp::SECTION_CALL] . PHP_EOL . PHP_EOL .
            $tplInstallService[TplApp::SECTION_CONTENT] . PHP_EOL;
        } else {
            $tplRemoveService = TplApp::getActionMulti(
                self::ACTION_REMOVE_SERVICE, null,
                array($bearsamppLang->getValue(Lang::MENU_REMOVE_SERVICE), TplAestan::GLYPH_SERVICE_REMOVE),
                !$isInstalled, get_called_class()
            );
            $result .= $tplRemoveService[TplApp::SECTION_CALL] . PHP_EOL . PHP_EOL .
            $tplRemoveService[TplApp::SECTION_CONTENT] . PHP_EOL;
        }
        $result .= $tplChangePort[TplApp::SECTION_CONTENT] . PHP_EOL .
            ($tplChangeRootPwd != null ? $tplChangeRootPwd[TplApp::SECTION_CONTENT] . PHP_EOL : '');
        return $result;
    }
References $bearsamppBins, $bearsamppLang, $result, Action\CHECK_PORT, TplApp\getActionMulti(), TplApp\getActionRun(), TplAestan\getItemActionServiceRestart(), TplAestan\getItemActionServiceStart(), TplAestan\getItemActionServiceStop(), TplAestan\getItemSeparator(), TplAestan\GLYPH_LIGHT, TplAestan\GLYPH_NETWORK, TplAestan\GLYPH_PASSWORD, TplAestan\GLYPH_SERVICE_INSTALL, TplAestan\GLYPH_SERVICE_REMOVE, Lang\MENU_CHANGE_PORT, Lang\MENU_CHANGE_ROOT_PWD, Lang\MENU_CHECK_PORT, Lang\MENU_INSTALL_SERVICE, Lang\MENU_REMOVE_SERVICE, TplApp\SECTION_CALL, and TplApp\SECTION_CONTENT.
getMenuMysqlVersions()
static TplAppMysql::getMenuMysqlVersions () static
Generates the MySQL versions menu.
This method creates menu items and actions for switching between different MySQL versions.
@global object $bearsamppBins Provides access to system binaries and their configurations.
Returns
string The generated MySQL versions menu items and actions.
Definition at line 128 of file class.tpl.app.mysql.php.
    {
        global $bearsamppBins;
        $items = '';
        $actions = '';
        foreach ($bearsamppBins->getMysql()->getVersionList() as $version) {
            $tplSwitchMysqlVersion = TplApp::getActionMulti(
                self::ACTION_SWITCH_VERSION, array($version),
                array($version, $version == $bearsamppBins->getMysql()->getVersion() ? TplAestan::GLYPH_CHECK : ''),
                false, get_called_class()
            );
            // Item
            $items .= $tplSwitchMysqlVersion[TplApp::SECTION_CALL] . PHP_EOL;
            // Action
            $actions .= PHP_EOL . $tplSwitchMysqlVersion[TplApp::SECTION_CONTENT];
        }
        return $items . $actions;
    }
References $bearsamppBins, TplApp\getActionMulti(), TplAestan\GLYPH_CHECK, TplApp\SECTION_CALL, and TplApp\SECTION_CONTENT.
process()
static TplAppMysql::process () static
Processes and generates the MySQL menu.
This method generates the MySQL menu and determines if MySQL is enabled.
@global object $bearsamppLang Provides language support for retrieving language-specific values. @global object $bearsamppBins Provides access to system binaries and their configurations.
Returns
array The generated MySQL menu.
Definition at line 42 of file class.tpl.app.mysql.php.
    {
        global $bearsamppLang, $bearsamppBins;
        return TplApp::getMenuEnable($bearsamppLang->getValue(Lang::MYSQL), self::MENU, get_called_class(), $bearsamppBins->getMysql()->isEnable());
    }
References $bearsamppBins, $bearsamppLang, TplApp\getMenuEnable(), and Lang\MYSQL.
Referenced by TplApp\getSectionMenuLeft().
Field Documentation
ACTION_CHANGE_PORT
const TplAppMysql::ACTION_CHANGE_PORT = 'changeMysqlPort'
Definition at line 27 of file class.tpl.app.mysql.php.
ACTION_CHANGE_ROOT_PWD
const TplAppMysql::ACTION_CHANGE_ROOT_PWD = 'changeMysqlRootPwd'
Definition at line 28 of file class.tpl.app.mysql.php.
ACTION_ENABLE
const TplAppMysql::ACTION_ENABLE = 'enableMysql'
Definition at line 25 of file class.tpl.app.mysql.php.
ACTION_INSTALL_SERVICE
const TplAppMysql::ACTION_INSTALL_SERVICE = 'installMysqlService'
Definition at line 29 of file class.tpl.app.mysql.php.
ACTION_REMOVE_SERVICE
const TplAppMysql::ACTION_REMOVE_SERVICE = 'removeMysqlService'
Definition at line 30 of file class.tpl.app.mysql.php.
ACTION_SWITCH_VERSION
const TplAppMysql::ACTION_SWITCH_VERSION = 'switchMysqlVersion'
Definition at line 26 of file class.tpl.app.mysql.php.
MENU
const TplAppMysql::MENU = 'mysql'
Definition at line 20 of file class.tpl.app.mysql.php.
MENU_DEBUG
const TplAppMysql::MENU_DEBUG = 'mysqlDebug'
Definition at line 23 of file class.tpl.app.mysql.php.
MENU_SERVICE
const TplAppMysql::MENU_SERVICE = 'mysqlService'
Definition at line 22 of file class.tpl.app.mysql.php.
MENU_VERSIONS
const TplAppMysql::MENU_VERSIONS = 'mysqlVersions'
Definition at line 21 of file class.tpl.app.mysql.php.
The documentation for this class was generated from the following file:
E:/Bearsampp-development/sandbox/core/classes/tpls/app/class.tpl.app.mysql.php