Bearsampp: TplAppTools Class Reference
TplAppTools Class Reference
Static Public Member Functions
static getActionGenSslCertificate ()
static getMenuTools ()
static process ()
Data Fields
const ACTION_GEN_SSL_CERTIFICATE = 'genSslCertificate'
const MENU = 'tools'
Detailed Description
Class TplAppTools
This class provides methods to generate menu items and actions for managing various tools within the Bearsampp application. It includes functionalities for accessing tools like Git, Python, Composer, Ghostscript, Ngrok, Pear, Perl, Ruby, XDebugClient, Yarn, and more.
Definition at line 17 of file class.tpl.app.tools.php.
Member Function Documentation
getActionGenSslCertificate()
static TplAppTools::getActionGenSslCertificate () static
Generates the action to generate an SSL certificate.
Returns
string The generated action to generate an SSL certificate.
Definition at line 155 of file class.tpl.app.tools.php.
    {
        return TplApp::getActionRun(Action::GEN_SSL_CERTIFICATE);
    }
References Action\GEN_SSL_CERTIFICATE, and TplApp\getActionRun().
getMenuTools()
static TplAppTools::getMenuTools () static
Generates the Tools menu with options for accessing various tools like Git, Python, Composer, etc.
@global object $bearsamppLang Provides language support for retrieving language-specific values. @global object $bearsamppCore Provides access to core functionalities and configurations. @global object $bearsamppTools Provides access to various tools and their configurations.
Returns
string The generated menu items and actions for Tools.
Definition at line 46 of file class.tpl.app.tools.php.
    {
        global $bearsamppLang, $bearsamppCore, $bearsamppTools;
        $resultItems = $resultActions = '';
        // Git
        $tplGit = TplAppGit::process();
        $resultItems .= $tplGit[TplApp::SECTION_CALL] . PHP_EOL;
        $resultActions .= $tplGit[TplApp::SECTION_CONTENT] . PHP_EOL;
        // Python
        $tplPython = TplAppPython::process();
        $resultItems .= $tplPython[TplApp::SECTION_CALL] . PHP_EOL;
        $resultActions .= $tplPython[TplApp::SECTION_CONTENT] . PHP_EOL;
        // Composer
        $resultItems .= TplAestan::getItemConsoleZ(
            $bearsamppLang->getValue(Lang::COMPOSER),
            TplAestan::GLYPH_COMPOSER,
            $bearsamppTools->getConsoleZ()->getTabTitleComposer()
        ) . PHP_EOL;
        // Ghostscript
        $resultItems .= TplAestan::getItemConsoleZ(
            $bearsamppLang->getValue(Lang::GHOSTSCRIPT),
            TplAestan::GLYPH_GHOSTSCRIPT,
            $bearsamppTools->getConsoleZ()->getTabTitleGhostscript()
        ) . PHP_EOL;
        // Ngrok
        $resultItems .= TplAestan::getItemConsoleZ(
            $bearsamppLang->getValue(Lang::NGROK),
            TplAestan::GLYPH_NGROK,
            $bearsamppTools->getConsoleZ()->getTabTitleNgrok()
        ) . PHP_EOL;
        // Pear
        $resultItems .= TplAestan::getItemConsoleZ(
            $bearsamppLang->getValue(Lang::PEAR),
            TplAestan::GLYPH_PEAR,
            $bearsamppTools->getConsoleZ()->getTabTitlePear()
        ) . PHP_EOL;
        // Perl
        $resultItems .= TplAestan::getItemConsoleZ(
            $bearsamppLang->getValue(Lang::PERL),
            TplAestan::GLYPH_PERL,
            $bearsamppTools->getConsoleZ()->getTabTitlePerl()
        ) . PHP_EOL;
        // Ruby
        $resultItems .= TplAestan::getItemConsoleZ(
            $bearsamppLang->getValue(Lang::RUBY),
            TplAestan::GLYPH_RUBY,
            $bearsamppTools->getConsoleZ()->getTabTitleRuby()
        ) . PHP_EOL;
        // XDebugClient
        $resultItems .= TplAestan::getItemExe(
            $bearsamppLang->getValue(Lang::XDC),
            $bearsamppTools->getXdc()->getExe(),
            TplAestan::GLYPH_DEBUG
        ) . PHP_EOL;
        // Yarn
        $resultItems .= TplAestan::getItemConsoleZ(
            $bearsamppLang->getValue(Lang::YARN),
            TplAestan::GLYPH_YARN,
            $bearsamppTools->getConsoleZ()->getTabTitleYarn()
        ) . PHP_EOL;
        $resultItems .= TplAestan::getItemSeparator() . PHP_EOL;
        // Console
        $resultItems .= TplAestan::getItemConsoleZ(
            $bearsamppLang->getValue(Lang::CONSOLE),
            TplAestan::GLYPH_CONSOLEZ
        ) . PHP_EOL;
        // HostsEditor
        $resultItems .= TplAestan::getItemExe(
            $bearsamppLang->getValue(Lang::HOSTSEDITOR),
            $bearsamppCore->getHostsEditorExe(),
            TplAestan::GLYPH_HOSTSEDITOR
        ) . PHP_EOL;
        // Generate SSL Certificate
        $tplGenSslCertificate = TplApp::getActionMulti(
            self::ACTION_GEN_SSL_CERTIFICATE, null,
            array($bearsamppLang->getValue(Lang::MENU_GEN_SSL_CERTIFICATE), TplAestan::GLYPH_SSL_CERTIFICATE),
            false, get_called_class()
        );
        $resultItems .= $tplGenSslCertificate[TplApp::SECTION_CALL] . PHP_EOL;
        $resultActions .= $tplGenSslCertificate[TplApp::SECTION_CONTENT];
        // Pwgen password manager
        $resultItems .= TplAestan::getItemExe(
            $bearsamppLang->getValue(Lang::PWGEN),
            $bearsamppCore->getPwgenExe(),
            TplAestan::GLYPH_PWGEN
        ) . PHP_EOL;
        return $resultItems . PHP_EOL . $resultActions;
    }
References $bearsamppCore, $bearsamppLang, Lang\COMPOSER, Lang\CONSOLE, TplApp\getActionMulti(), TplAestan\getItemConsoleZ(), TplAestan\getItemExe(), TplAestan\getItemSeparator(), Lang\GHOSTSCRIPT, TplAestan\GLYPH_COMPOSER, TplAestan\GLYPH_CONSOLEZ, TplAestan\GLYPH_DEBUG, TplAestan\GLYPH_GHOSTSCRIPT, TplAestan\GLYPH_HOSTSEDITOR, TplAestan\GLYPH_NGROK, TplAestan\GLYPH_PEAR, TplAestan\GLYPH_PERL, TplAestan\GLYPH_PWGEN, TplAestan\GLYPH_RUBY, TplAestan\GLYPH_SSL_CERTIFICATE, TplAestan\GLYPH_YARN, Lang\HOSTSEDITOR, Lang\MENU_GEN_SSL_CERTIFICATE, Lang\NGROK, Lang\PEAR, Lang\PERL, TplAppGit\process(), TplAppPython\process(), Lang\PWGEN, Lang\RUBY, TplApp\SECTION_CALL, TplApp\SECTION_CONTENT, Lang\XDC, and Lang\YARN.
process()
static TplAppTools::process () static
Generates the main Tools menu with options to access various tools.
@global object $bearsamppLang Provides language support for retrieving language-specific values.
Returns
array The generated menu items and actions for Tools.
Definition at line 30 of file class.tpl.app.tools.php.
    {
        global $bearsamppLang;
        return TplApp::getMenu($bearsamppLang->getValue(Lang::TOOLS), self::MENU, get_called_class());
    }
References $bearsamppLang, TplApp\getMenu(), and Lang\TOOLS.
Referenced by TplApp\getSectionMenuLeft().
Field Documentation
ACTION_GEN_SSL_CERTIFICATE
const TplAppTools::ACTION_GEN_SSL_CERTIFICATE = 'genSslCertificate'
Definition at line 21 of file class.tpl.app.tools.php.
MENU
const TplAppTools::MENU = 'tools'
Definition at line 20 of file class.tpl.app.tools.php.
The documentation for this class was generated from the following file:
E:/Bearsampp-development/sandbox/core/classes/tpls/app/class.tpl.app.tools.php