Bearsampp: TplService Class Reference
TplService Class Reference
Static Public Member Functions
static getActionCreate ($sName)
static getActionInstall ($sName)
static getActionRemove ($sName)
static getActionRestart ($sName)
static getActionStart ($sName)
static getActionStop ($sName)
static getItemInstall ($sName)
static getItemRemove ($sName)
static getItemRestart ($sName)
static getItemStart ($sName)
static getItemStop ($sName)
Detailed Description
Class TplService
Provides utility methods for generating action strings and menu items for service management. This includes functionalities to create, start, stop, restart, install, and remove services. Each service action can also be represented as a menu item with an associated glyph for visual representation.
Definition at line 17 of file class.tpl.service.php.
Member Function Documentation
getActionCreate()
static getActionCreate ($sName) static
Generates an action string for creating a service.
Parameters
string $sName The name of the service.
Returns
string The action command to create the service.
Definition at line 25 of file class.tpl.service.php.
    {
        return TplApp::getActionRun(Action::SERVICE, array($sName, ActionService::CREATE));
    }
References ActionService\CREATE, TplApp\getActionRun(), and Action\SERVICE.
getActionInstall()
static getActionInstall ($sName) static
Generates an action string for installing a service.
Parameters
string $sName The name of the service.
Returns
string The action command to install the service.
Definition at line 69 of file class.tpl.service.php.
    {
        return TplApp::getActionRun(Action::SERVICE, array($sName, ActionService::INSTALL));
    }
References TplApp\getActionRun(), ActionService\INSTALL, and Action\SERVICE.
getActionRemove()
static getActionRemove ($sName) static
Generates an action string for removing a service.
Parameters
string $sName The name of the service.
Returns
string The action command to remove the service.
Definition at line 80 of file class.tpl.service.php.
    {
        return TplApp::getActionRun(Action::SERVICE, array($sName, ActionService::REMOVE));
    }
References TplApp\getActionRun(), ActionService\REMOVE, and Action\SERVICE.
getActionRestart()
static getActionRestart ($sName) static
Generates an action string for restarting a service.
Parameters
string $sName The name of the service.
Returns
string The action command to restart the service.
Definition at line 58 of file class.tpl.service.php.
    {
        return TplApp::getActionRun(Action::SERVICE, array($sName, ActionService::RESTART));
    }
References TplApp\getActionRun(), ActionService\RESTART, and Action\SERVICE.
Referenced by TplAppOnline\getActionStatus(), TplAppApache\getActionSwitchApacheModule(), TplAppPhp\getActionSwitchPhpExtension(), TplAppPhp\getActionSwitchPhpSetting(), and ActionEditVhost\processWindow().
getActionStart()
static getActionStart ($sName) static
Generates an action string for starting a service.
Parameters
string $sName The name of the service.
Returns
string The action command to start the service.
Definition at line 36 of file class.tpl.service.php.
    {
        return TplApp::getActionRun(Action::SERVICE, array($sName, ActionService::START));
    }
References TplApp\getActionRun(), Action\SERVICE, and ActionService\START.
Referenced by TplAppServices\getActionStartServices().
getActionStop()
static getActionStop ($sName) static
Generates an action string for stopping a service.
Parameters
string $sName The name of the service.
Returns
string The action command to stop the service.
Definition at line 47 of file class.tpl.service.php.
    {
        return TplApp::getActionRun(Action::SERVICE, array($sName, ActionService::STOP));
    }
References TplApp\getActionRun(), Action\SERVICE, and ActionService\STOP.
Referenced by TplAppServices\getActionStopServices().
getItemInstall()
static getItemInstall ($sName) static
Generates a menu item for installing a service with a glyph.
Parameters
string $sName The name of the service.
Returns
string The menu item command to install the service.
Definition at line 139 of file class.tpl.service.php.
    {
        global $bearsamppLang;
        return TplApp::getActionRun(
            Action::SERVICE, array($sName, ActionService::INSTALL),
            array($bearsamppLang->getValue(Lang::MENU_INSTALL_SERVICE), TplAestan::GLYPH_SERVICE_INSTALL)
        );
    }
References $bearsamppLang, TplApp\getActionRun(), TplAestan\GLYPH_SERVICE_INSTALL, ActionService\INSTALL, Lang\MENU_INSTALL_SERVICE, and Action\SERVICE.
getItemRemove()
static getItemRemove ($sName) static
Generates a menu item for removing a service with a glyph.
Parameters
string $sName The name of the service.
Returns
string The menu item command to remove the service.
Definition at line 155 of file class.tpl.service.php.
    {
        global $bearsamppLang;
        return TplApp::getActionRun(
            Action::SERVICE, array($sName, ActionService::REMOVE),
            array($bearsamppLang->getValue(Lang::MENU_REMOVE_SERVICE), TplAestan::GLYPH_SERVICE_REMOVE)
        );
    }
References $bearsamppLang, TplApp\getActionRun(), TplAestan\GLYPH_SERVICE_REMOVE, Lang\MENU_REMOVE_SERVICE, ActionService\REMOVE, and Action\SERVICE.
getItemRestart()
static getItemRestart ($sName) static
Generates a menu item for restarting a service with a glyph.
Parameters
string $sName The name of the service.
Returns
string The menu item command to restart the service.
Definition at line 123 of file class.tpl.service.php.
    {
        global $bearsamppLang;
        return TplApp::getActionRun(
            Action::SERVICE, array($sName, ActionService::RESTART),
            array($bearsamppLang->getValue(Lang::MENU_RESTART_SERVICE), TplAestan::GLYPH_RELOAD)
        );
    }
References $bearsamppLang, TplApp\getActionRun(), TplAestan\GLYPH_RELOAD, Lang\MENU_RESTART_SERVICE, ActionService\RESTART, and Action\SERVICE.
getItemStart()
static getItemStart ($sName) static
Generates a menu item for starting a service with a glyph.
Parameters
string $sName The name of the service.
Returns
string The menu item command to start the service.
Definition at line 91 of file class.tpl.service.php.
    {
        global $bearsamppLang;
        return TplApp::getActionRun(
            Action::SERVICE, array($sName, ActionService::START),
            array($bearsamppLang->getValue(Lang::MENU_START_SERVICE), TplAestan::GLYPH_START)
        );
    }
References $bearsamppLang, TplApp\getActionRun(), TplAestan\GLYPH_START, Lang\MENU_START_SERVICE, Action\SERVICE, and ActionService\START.
getItemStop()
static getItemStop ($sName) static
Generates a menu item for stopping a service with a glyph.
Parameters
string $sName The name of the service.
Returns
string The menu item command to stop the service.
Definition at line 107 of file class.tpl.service.php.
    {
        global $bearsamppLang;
        return TplApp::getActionRun(
            Action::SERVICE, array($sName, ActionService::STOP),
            array($bearsamppLang->getValue(Lang::MENU_STOP_SERVICE), TplAestan::GLYPH_STOP)
        );
    }
References $bearsamppLang, TplApp\getActionRun(), TplAestan\GLYPH_STOP, Lang\MENU_STOP_SERVICE, Action\SERVICE, and ActionService\STOP.
The documentation for this class was generated from the following file:
E:/Bearsampp-development/sandbox/core/classes/tpls/class.tpl.service.php