My Project: LangProc Class Reference
LangProc Class Reference
Public Member Functions
__construct ()
getCurrent ()
getList ()
getValue ($key)
load ()
Private Attributes
$current
$raw
Detailed Description
Class LangProc
This class handles the language processing for the Bearsampp application. It loads language files, retrieves language settings, and provides language-specific values.
Definition at line 16 of file class.langproc.php.
Constructor & Destructor Documentation
__construct()
LangProc::__construct ()
LangProc constructor.
Initializes the LangProc object and loads the language settings.
Definition at line 33 of file class.langproc.php.
    {
        $this->load();
    }
References load().
Member Function Documentation
getCurrent()
LangProc::getCurrent ()
Gets the current language being used.
Returns
string The current language.
Definition at line 62 of file class.langproc.php.
    {
        return $this->current;
    }
References $current.
getList()
LangProc::getList ()
Retrieves the list of available languages.
This method scans the language directory and returns a list of available language files.
Returns
array The list of available languages.
Definition at line 74 of file class.langproc.php.
    {
        global $bearsamppCore;
        $result = array();
        $handle = @opendir($bearsamppCore->getLangsPath());
        if (!$handle) {
            return $result;
        }
        while (false !== ($file = readdir($handle))) {
            if ($file != "." && $file != ".." && Util::endWith($file, '.lang')) {
                $result[] = str_replace('.lang', '', $file);
            }
        }
        closedir($handle);
        return $result;
    }
References $bearsamppCore, $result, and Util\endWith().
Referenced by load().
getValue()
LangProc::getValue ($key)
Retrieves the value for a given language key.
This method returns the value associated with the specified key in the current language. If the key is not found, it logs an error and returns the key itself.
Parameters
string $key The language key to retrieve the value for.
Returns
string The value associated with the key, or the key itself if not found.
Definition at line 103 of file class.langproc.php.
    {
        global $bearsamppRoot;
        if (!isset($this->raw[$key])) {
            $content = '[' . date('Y-m-d H:i:s', time()) . '] ';
            $content .= 'ERROR: Lang var missing ' . $key;
            $content .= ' for ' . $this->current . ' language.' . PHP_EOL;
            file_put_contents($bearsamppRoot->getErrorLogFilePath(), $content, FILE_APPEND);
            return $key;
        }
        // Special chars not handled by Aestan Tray Menu
        $replace = array("ő", "Ő", "ű", "Ű");
        $with = array("o", "O", "u", "U");
        return str_replace($replace, $with, $this->raw[$key]);
    }
References $bearsamppRoot.
load()
LangProc::load ()
Loads the current language settings and data.
This method retrieves the default language from the configuration, checks if it is available, and then loads the corresponding language file.
Definition at line 44 of file class.langproc.php.
    {
        global $bearsamppCore, $bearsamppConfig;
        $this->raw = null;
        $this->current = $bearsamppConfig->getDefaultLang();
        if (!empty($this->current) && in_array($this->current, $this->getList())) {
            $this->current = $bearsamppConfig->getLang();
        }
        $this->raw = parse_ini_file($bearsamppCore->getLangsPath() . '/' . $this->current . '.lang');
    }
References $bearsamppConfig, $bearsamppCore, and getList().
Referenced by __construct().
Field Documentation
$current
LangProc::$current private
Definition at line 21 of file class.langproc.php.
Referenced by getCurrent().
$raw
LangProc::$raw private
Definition at line 26 of file class.langproc.php.
The documentation for this class was generated from the following file:
E:/Bearsampp-development/sandbox/core/classes/class.langproc.php