Bearsampp: ToolComposer Class Reference
ToolComposer Class Reference
Public Member Functions
__construct ($id, $type)
getExe ()
reload ($id=null, $type=null)
setVersion ($version)
Public Member Functions inherited from Module
__toString ()
getCurrentPath ()
getId ()
getName ()
getRelease ()
getRootPath ()
getSymlinkPath ()
getType ()
getVersion ()
getVersionList ()
isEnable ()
update ($sub=0, $showWindow=false)
Data Fields
const LOCAL_CFG_EXE = 'composerExe'
const ROOT_CFG_VERSION = 'composerVersion'
Data Fields inherited from Module
const BUNDLE_RELEASE = 'bundleRelease'
Private Attributes
$exe
Additional Inherited Members
Protected Member Functions inherited from Module
__construct ()
replace ($key, $value)
replaceAll ($params)
updateConfig ($version=null, $sub=0, $showWindow=false)
Protected Attributes inherited from Module
$bearsamppConf
$bearsamppConfRaw
$currentPath
$enable
$name
$release = 'N/A'
$rootPath
$symlinkPath
$version
Detailed Description
Class ToolComposer
This class represents the Composer tool module in the Bearsampp application. It extends the abstract Module class and provides functionalities specific to Composer.
Definition at line 16 of file class.tool.composer.php.
Constructor & Destructor Documentation
__construct()
ToolComposer::__construct ($id, $type)
Constructor for the ToolComposer class.
Parameters
string $id The ID of the module.
string $type The type of the module.
Definition at line 41 of file class.tool.composer.php.
{
        Util::logInitClass($this);
        $this->reload($id, $type);
    }
References Module\$id, Module\$type, Util\logInitClass(), and reload().
Member Function Documentation
getExe()
ToolComposer::getExe ()
Gets the path to the Composer executable.
Returns
string The path to the Composer executable.
Definition at line 100 of file class.tool.composer.php.
{
        return $this->exe;
    }
References $exe.
reload()
ToolComposer::reload ($id = null, $type = null)
Reloads the Composer module configuration based on the provided ID and type.
Parameters
string | null $id The ID of the module. If null, the current ID is used.
string | null $type The type of the module. If null, the current type is used.
Reimplemented from Module.
Definition at line 52 of file class.tool.composer.php.
{
        global $bearsamppConfig, $bearsamppLang;
        Util::logReloadClass($this);
        $this->name = $bearsamppLang->getValue(Lang::COMPOSER);
        $this->version = $bearsamppConfig->getRaw(self::ROOT_CFG_VERSION);
        parent::reload($id, $type);
        if ($this->bearsamppConfRaw !== false) {
            $this->exe = $this->symlinkPath . '/' . $this->bearsamppConfRaw[self::LOCAL_CFG_EXE];
        }
        if (!$this->enable) {
            Util::logInfo($this->name . ' is not enabled!');
            return;
        }
        if (!is_dir($this->currentPath)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_FILE_NOT_FOUND), $this->name . ' ' . $this->version, $this->currentPath));
        }
        if (!is_dir($this->symlinkPath)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_FILE_NOT_FOUND), $this->name . ' ' . $this->version, $this->symlinkPath));
            return;
        }
        if (!is_file($this->bearsamppConf)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_CONF_NOT_FOUND), $this->name . ' ' . $this->version, $this->bearsamppConf));
        }
        if (!is_file($this->exe)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_EXE_NOT_FOUND), $this->name . ' ' . $this->version, $this->exe));
        }
    }
References $bearsamppConfig, $bearsamppLang, Module\$id, Module\$type, Lang\COMPOSER, Lang\ERROR_CONF_NOT_FOUND, Lang\ERROR_EXE_NOT_FOUND, Lang\ERROR_FILE_NOT_FOUND, LOCAL_CFG_EXE, Util\logError(), Util\logInfo(), and Util\logReloadClass().
Referenced by __construct(), and setVersion().
setVersion()
ToolComposer::setVersion ($version)
Sets the version of the Composer module and updates the configuration.
Parameters
string $version The version to set.
Reimplemented from Module.
Definition at line 88 of file class.tool.composer.php.
{
        global $bearsamppConfig;
        $this->version = $version;
        $bearsamppConfig->replace(self::ROOT_CFG_VERSION, $version);
        $this->reload();
    }
References $bearsamppConfig, Module\$version, and reload().
Field Documentation
$exe
ToolComposer::$exe private
Definition at line 33 of file class.tool.composer.php.
Referenced by getExe().
LOCAL_CFG_EXE
const ToolComposer::LOCAL_CFG_EXE = 'composerExe'
Configuration key for the Composer executable in the local configuration.
Definition at line 26 of file class.tool.composer.php.
Referenced by reload().
ROOT_CFG_VERSION
const ToolComposer::ROOT_CFG_VERSION = 'composerVersion'
Configuration key for the Composer version in the root configuration.
Definition at line 21 of file class.tool.composer.php.
The documentation for this class was generated from the following file:
E:/Bearsampp-development/sandbox/core/classes/tools/class.tool.composer.php