Bearsampp: Win32Service Class Reference
Win32Service Class Reference
Public Member Functions
__construct ($name)
create ()
delete ()
getBinPath ()
getDisplayName ()
getError ()
getErrorControl ()
getLatestError ()
getLatestStatus ()
getName ()
getNssm ()
getParams ()
getStartType ()
infos ()
isInstalled ()
isPaused ()
isPending ($status)
isRunning ()
isStopped ()
reset ()
restart ()
setBinPath ($binPath)
setDisplayName ($displayName)
setErrorControl ($errorControl)
setName ($name)
setNssm ($nssm)
setParams ($params)
setStartType ($startType)
start ()
status ($timeout=true)
stop ()
Static Public Member Functions
static getVbsKeys ()
Data Fields
const PENDING_TIMEOUT = 20
const SERVER_ERROR_IGNORE = "0"
const SERVER_ERROR_NORMAL = "1"
const SERVICE_AUTO_START = "2"
const SERVICE_DEMAND_START = "3"
const SERVICE_DISABLED = "4"
const SLEEP_TIME = 500000
const VBS_DESCRIPTION = 'Description'
const VBS_DISPLAY_NAME = 'DisplayName'
const VBS_NAME = 'Name'
const VBS_PATH_NAME = 'PathName'
const VBS_STATE = 'State'
const WIN32_ERROR_ACCESS_DENIED = "5"
const WIN32_ERROR_CIRCULAR_DEPENDENCY = "423"
const WIN32_ERROR_DATABASE_DOES_NOT_EXIST = "429"
const WIN32_ERROR_DEPENDENT_SERVICES_RUNNING = "41B"
const WIN32_ERROR_DUPLICATE_SERVICE_NAME = "436"
const WIN32_ERROR_FAILED_SERVICE_CONTROLLER_CONNECT = "427"
const WIN32_ERROR_INSUFFICIENT_BUFFER = "7A"
const WIN32_ERROR_INVALID_DATA = "D"
const WIN32_ERROR_INVALID_HANDLE = "6"
const WIN32_ERROR_INVALID_LEVEL = "7C"
const WIN32_ERROR_INVALID_NAME = "7B"
const WIN32_ERROR_INVALID_PARAMETER = "57"
const WIN32_ERROR_INVALID_SERVICE_ACCOUNT = "421"
const WIN32_ERROR_INVALID_SERVICE_CONTROL = "41C"
const WIN32_ERROR_PATH_NOT_FOUND = "3"
const WIN32_ERROR_SERVICE_ALREADY_RUNNING = "420"
const WIN32_ERROR_SERVICE_CANNOT_ACCEPT_CTRL = "425"
const WIN32_ERROR_SERVICE_DATABASE_LOCKED = "41F"
const WIN32_ERROR_SERVICE_DEPENDENCY_DELETED = "433"
const WIN32_ERROR_SERVICE_DEPENDENCY_FAIL = "42C"
const WIN32_ERROR_SERVICE_DISABLED = "422"
const WIN32_ERROR_SERVICE_DOES_NOT_EXIST = "424"
const WIN32_ERROR_SERVICE_EXISTS = "431"
const WIN32_ERROR_SERVICE_LOGON_FAILED = "42D"
const WIN32_ERROR_SERVICE_MARKED_FOR_DELETE = "430"
const WIN32_ERROR_SERVICE_NO_THREAD = "41E"
const WIN32_ERROR_SERVICE_NOT_ACTIVE = "426"
const WIN32_ERROR_SERVICE_REQUEST_TIMEOUT = "41D"
const WIN32_ERROR_SHUTDOWN_IN_PROGRESS = "45B"
const WIN32_NO_ERROR = "0"
const WIN32_SERVICE_CONTINUE_PENDING = "5"
const WIN32_SERVICE_NA = "0"
const WIN32_SERVICE_PAUSE_PENDING = "6"
const WIN32_SERVICE_PAUSED = "7"
const WIN32_SERVICE_RUNNING = "4"
const WIN32_SERVICE_START_PENDING = "2"
const WIN32_SERVICE_STOP_PENDING = "3"
const WIN32_SERVICE_STOPPED = "1"
Private Member Functions
callWin32Service ($function, $param, $checkError=false)
getWin32ErrorCodeDesc ($code)
getWin32ServiceStatusDesc ($status)
writeLog ($log)
Private Attributes
$binPath
$displayName
$errorControl
$latestError
$latestStatus
$name
$nssm
$params
$startType
Detailed Description
Definition at line 10 of file class.win32service.php.
Constructor & Destructor Documentation
__construct()
__construct ($name)
Definition at line 81 of file class.win32service.php.
    {
        Util::logInitClass($this);
        $this->name = $name;
    }
References $name, and Util\logInitClass().
Member Function Documentation
callWin32Service()
callWin32Service ($function, $param, $checkError = false) private
Definition at line 104 of file class.win32service.php.
    {
        $result = false;
        if (function_exists($function)) {
            $result = call_user_func($function, $param);
            if ($checkError && dechex($result) != self::WIN32_NO_ERROR) {
                $this->latestError = dechex($result);
            }
        }
        return $result;
    }
References $result.
Referenced by create(), delete(), start(), status(), and stop().
create()
create ()
Definition at line 143 of file class.win32service.php.
    {
        global $bearsamppBins;
        if ($this->getName() == BinFilezilla::SERVICE_NAME) {
            $bearsamppBins->getFilezilla()->rebuildConf();
            return Batch::installFilezillaService();
        } elseif ($this->getName() == BinPostgresql::SERVICE_NAME) {
            $bearsamppBins->getPostgresql()->rebuildConf();
            $bearsamppBins->getPostgresql()->initData();
            return Batch::installPostgresqlService();
        }
        if ($this->getNssm() instanceof Nssm) {
            $nssmEnvPath = Util::getAppBinsRegKey(false);
            $nssmEnvPath .= Util::getNssmEnvPaths();
            $nssmEnvPath .= '%SystemRoot%/system32;';
            $nssmEnvPath .= '%SystemRoot%;';
            $nssmEnvPath .= '%SystemRoot%/system32/Wbem;';
            $nssmEnvPath .= '%SystemRoot%/system32/WindowsPowerShell/v1.0';
            $this->getNssm()->setEnvironmentExtra('PATH=' . $nssmEnvPath);
            return $this->getNssm()->create();
        }
        $create = dechex($this->callWin32Service('win32_create_service', array(
            'service' => $this->getName(),
            'display' => $this->getDisplayName(),
            'description' => $this->getDisplayName(),
            'path' => $this->getBinPath(),
            'params' => $this->getParams(),
            'start_type' => $this->getStartType() != null ? $this->getStartType() : self::SERVICE_DEMAND_START,
            'error_control' => $this->getErrorControl() != null ? $this->getErrorControl() : self::SERVER_ERROR_NORMAL,
        ), true));
        $this->writeLog('Create service: ' . $create . ' (status: ' . $this->status() . ')');
        $this->writeLog('-> service: ' . $this->getName());
        $this->writeLog('-> display: ' . $this->getDisplayName());
        $this->writeLog('-> description: ' . $this->getDisplayName());
        $this->writeLog('-> path: ' . $this->getBinPath());
        $this->writeLog('-> params: ' . $this->getParams());
        $this->writeLog('-> start_type: ' . ($this->getStartType() != null ? $this->getStartType() : self::SERVICE_DEMAND_START));
        $this->writeLog('-> service: ' . ($this->getErrorControl() != null ? $this->getErrorControl() : self::SERVER_ERROR_NORMAL));
        if ($create != self::WIN32_NO_ERROR) {
            return false;
        } elseif (!$this->isInstalled()) {
            $this->latestError = self::WIN32_NO_ERROR;
            return false;
        }
        return true;
    }
References $bearsamppBins, callWin32Service(), Util\getAppBinsRegKey(), getBinPath(), getDisplayName(), getErrorControl(), getName(), getNssm(), Util\getNssmEnvPaths(), getParams(), getStartType(), Batch\installFilezillaService(), Batch\installPostgresqlService(), isInstalled(), SERVER_ERROR_NORMAL, SERVICE_DEMAND_START, BinFilezilla\SERVICE_NAME, BinPostgresql\SERVICE_NAME, status(), WIN32_NO_ERROR, and writeLog().
Referenced by reset().
delete()
delete ()
Definition at line 194 of file class.win32service.php.
    {
        if (!$this->isInstalled()) {
            return true;
        }
        $this->stop();
        if ($this->getName() == BinFilezilla::SERVICE_NAME) {
            return Batch::uninstallFilezillaService();
        } elseif ($this->getName() == BinPostgresql::SERVICE_NAME) {
            return Batch::uninstallPostgresqlService();
        }
        $delete = dechex($this->callWin32Service('win32_delete_service', $this->getName(), true));
        $this->writeLog('Delete service ' . $this->getName() . ': ' . $delete . ' (status: ' . $this->status() . ')');
        if ($delete != self::WIN32_NO_ERROR && $delete != self::WIN32_ERROR_SERVICE_DOES_NOT_EXIST) {
            return false;
        } elseif ($this->isInstalled()) {
            $this->latestError = self::WIN32_NO_ERROR;
            return false;
        }
        return true;
    }
References callWin32Service(), getName(), isInstalled(), BinFilezilla\SERVICE_NAME, BinPostgresql\SERVICE_NAME, status(), stop(), Batch\uninstallFilezillaService(), Batch\uninstallPostgresqlService(), WIN32_NO_ERROR, and writeLog().
getBinPath()
getBinPath ()
Definition at line 537 of file class.win32service.php.
    {
        return $this->binPath;
    }
References $binPath.
Referenced by create().
getDisplayName()
getDisplayName ()
Definition at line 527 of file class.win32service.php.
    {
        return $this->displayName;
    }
References $displayName.
Referenced by create().
getError()
getError ()
Definition at line 603 of file class.win32service.php.
    {
        global $bearsamppLang;
        if ($this->latestError != self::WIN32_NO_ERROR) {
            return $bearsamppLang->getValue(Lang::ERROR) . ' ' .
                $this->latestError . ' (' . hexdec($this->latestError) . ' : ' . $this->getWin32ErrorCodeDesc($this->latestError) . ')';
        } elseif ($this->latestStatus != self::WIN32_SERVICE_NA) {
            return $bearsamppLang->getValue(Lang::STATUS) . ' ' .
                $this->latestStatus . ' (' . hexdec($this->latestStatus) . ' : ' . $this->getWin32ServiceStatusDesc($this->latestStatus) . ')';
        }
        return null;
    }
References $bearsamppLang, Lang\ERROR, getWin32ErrorCodeDesc(), getWin32ServiceStatusDesc(), and Lang\STATUS.
getErrorControl()
getErrorControl ()
Definition at line 567 of file class.win32service.php.
    {
        return $this->errorControl;
    }
References $errorControl.
Referenced by create().
getLatestError()
getLatestError ()
Definition at line 598 of file class.win32service.php.
    {
        return $this->latestError;
    }
References $latestError.
getLatestStatus()
getLatestStatus ()
Definition at line 593 of file class.win32service.php.
    {
        return $this->latestStatus;
    }
References $latestStatus.
getName()
getName ()
Definition at line 517 of file class.win32service.php.
    {
        return $this->name;
    }
References $name.
Referenced by create(), delete(), infos(), isInstalled(), isPaused(), isRunning(), isStopped(), start(), status(), and stop().
getNssm()
getNssm ()
Definition at line 577 of file class.win32service.php.
    {
        return $this->nssm;
    }
References $nssm.
Referenced by create(), and infos().
getParams()
getParams ()
Definition at line 547 of file class.win32service.php.
    {
        return $this->params;
    }
References $params.
Referenced by create().
getStartType()
getStartType ()
Definition at line 557 of file class.win32service.php.
    {
        return $this->startType;
    }
References $startType.
Referenced by create().
getVbsKeys()
static getVbsKeys () static
Definition at line 93 of file class.win32service.php.
    {
        return array(
            self::VBS_NAME,
            self::VBS_DISPLAY_NAME,
            self::VBS_DESCRIPTION,
            self::VBS_PATH_NAME,
            self::VBS_STATE
        );
    }
Referenced by Vbs\getServiceInfos().
getWin32ErrorCodeDesc()
getWin32ErrorCodeDesc ($code) private
Definition at line 392 of file class.win32service.php.
    {
        switch ($code) {
            case self::WIN32_ERROR_ACCESS_DENIED:
                return 'The handle to the SCM database does not have the appropriate access rights.';
                break;
            case self::WIN32_ERROR_CIRCULAR_DEPENDENCY:
                return 'A circular service dependency was specified.';
                break;
            case self::WIN32_ERROR_DATABASE_DOES_NOT_EXIST:
                return 'The specified database does not exist.';
                break;
            case self::WIN32_ERROR_DEPENDENT_SERVICES_RUNNING:
                return 'The service cannot be stopped because other running services are dependent on it.';
                break;
            case self::WIN32_ERROR_DUPLICATE_SERVICE_NAME:
                return 'The display name already exists in the service control manager database either as a service name or as another display name.';
                break;
            case self::WIN32_ERROR_FAILED_SERVICE_CONTROLLER_CONNECT:
                return 'This error is returned if the program is being run as a console application rather than as a service. If the program will be run as a console application for debugging purposes, structure it such that service-specific code is not called.';
                break;
            case self::WIN32_ERROR_INSUFFICIENT_BUFFER:
                return 'The buffer is too small for the service status structure. Nothing was written to the structure.';
                break;
            case self::WIN32_ERROR_INVALID_DATA:
                return 'The specified service status structure is invalid. ';
                break;
            case self::WIN32_ERROR_INVALID_HANDLE:
                return 'The handle to the specified service control manager database is invalid.';
                break;
            case self::WIN32_ERROR_INVALID_LEVEL:
                return 'The InfoLevel parameter contains an unsupported value.';
                break;
            case self::WIN32_ERROR_INVALID_NAME:
                return 'The specified service name is invalid.';
                break;
            case self::WIN32_ERROR_INVALID_PARAMETER:
                return 'A parameter that was specified is invalid.';
                break;
            case self::WIN32_ERROR_INVALID_SERVICE_ACCOUNT:
                return 'The user account name specified in the user parameter does not exist.';
                break;
            case self::WIN32_ERROR_INVALID_SERVICE_CONTROL:
                return 'The requested control code is not valid, or it is unacceptable to the service.';
                break;
            case self::WIN32_ERROR_PATH_NOT_FOUND:
                return 'The service binary file could not be found.';
                break;
            case self::WIN32_ERROR_SERVICE_ALREADY_RUNNING:
                return 'An instance of the service is already running.';
                break;
            case self::WIN32_ERROR_SERVICE_CANNOT_ACCEPT_CTRL:
                return 'The requested control code cannot be sent to the service because the state of the service is WIN32_SERVICE_STOPPED, WIN32_SERVICE_START_PENDING, or WIN32_SERVICE_STOP_PENDING.';
                break;
            case self::WIN32_ERROR_SERVICE_DATABASE_LOCKED:
                return 'The database is locked.';
                break;
            case self::WIN32_ERROR_SERVICE_DEPENDENCY_DELETED:
                return 'The service depends on a service that does not exist or has been marked for deletion.';
                break;
            case self::WIN32_ERROR_SERVICE_DEPENDENCY_FAIL:
                return 'The service depends on another service that has failed to start.';
                break;
            case self::WIN32_ERROR_SERVICE_DISABLED:
                return 'The service has been disabled.';
                break;
            case self::WIN32_ERROR_SERVICE_DOES_NOT_EXIST:
                return 'The specified service does not exist as an installed service.';
                break;
            case self::WIN32_ERROR_SERVICE_EXISTS:
                return 'The specified service already exists in this database.';
                break;
            case self::WIN32_ERROR_SERVICE_LOGON_FAILED:
                return 'The service did not start due to a logon failure. This error occurs if the service is configured to run under an account that does not have the "Log on as a service" right.';
                break;
            case self::WIN32_ERROR_SERVICE_MARKED_FOR_DELETE:
                return 'The specified service has already been marked for deletion.';
                break;
            case self::WIN32_ERROR_SERVICE_NO_THREAD:
                return 'A thread could not be created for the service.';
                break;
            case self::WIN32_ERROR_SERVICE_NOT_ACTIVE:
                return 'The service has not been started.';
                break;
            case self::WIN32_ERROR_SERVICE_REQUEST_TIMEOUT:
                return 'The process for the service was started, but it did not call StartServiceCtrlDispatcher, or the thread that called StartServiceCtrlDispatcher may be blocked in a control handler function.';
                break;
            case self::WIN32_ERROR_SHUTDOWN_IN_PROGRESS:
                return 'The system is shutting down; this function cannot be called.';
                break;
            default:
                return null;
                break;
        }
    }
References WIN32_ERROR_ACCESS_DENIED, WIN32_ERROR_CIRCULAR_DEPENDENCY, WIN32_ERROR_DATABASE_DOES_NOT_EXIST, WIN32_ERROR_DEPENDENT_SERVICES_RUNNING, WIN32_ERROR_DUPLICATE_SERVICE_NAME, WIN32_ERROR_FAILED_SERVICE_CONTROLLER_CONNECT, WIN32_ERROR_INSUFFICIENT_BUFFER, WIN32_ERROR_INVALID_DATA, WIN32_ERROR_INVALID_HANDLE, WIN32_ERROR_INVALID_LEVEL, WIN32_ERROR_INVALID_NAME, WIN32_ERROR_INVALID_PARAMETER, WIN32_ERROR_INVALID_SERVICE_ACCOUNT, WIN32_ERROR_INVALID_SERVICE_CONTROL, WIN32_ERROR_PATH_NOT_FOUND, WIN32_ERROR_SERVICE_ALREADY_RUNNING, WIN32_ERROR_SERVICE_CANNOT_ACCEPT_CTRL, WIN32_ERROR_SERVICE_DATABASE_LOCKED, WIN32_ERROR_SERVICE_DEPENDENCY_DELETED, WIN32_ERROR_SERVICE_DEPENDENCY_FAIL, WIN32_ERROR_SERVICE_DISABLED, WIN32_ERROR_SERVICE_DOES_NOT_EXIST, WIN32_ERROR_SERVICE_EXISTS, WIN32_ERROR_SERVICE_LOGON_FAILED, WIN32_ERROR_SERVICE_MARKED_FOR_DELETE, WIN32_ERROR_SERVICE_NO_THREAD, WIN32_ERROR_SERVICE_NOT_ACTIVE, WIN32_ERROR_SERVICE_REQUEST_TIMEOUT, and WIN32_ERROR_SHUTDOWN_IN_PROGRESS.
Referenced by getError().
getWin32ServiceStatusDesc()
getWin32ServiceStatusDesc ($status) private
Definition at line 351 of file class.win32service.php.
    {
        switch ($status) {
            case self::WIN32_SERVICE_CONTINUE_PENDING:
                return 'The service continue is pending.';
                break;
            case self::WIN32_SERVICE_PAUSE_PENDING:
                return 'The service pause is pending.';
                break;
            case self::WIN32_SERVICE_PAUSED:
                return 'The service is paused.';
                break;
            case self::WIN32_SERVICE_RUNNING:
                return 'The service is running.';
                break;
            case self::WIN32_SERVICE_START_PENDING:
                return 'The service is starting.';
                break;
            case self::WIN32_SERVICE_STOP_PENDING:
                return 'The service is stopping.';
                break;
            case self::WIN32_SERVICE_STOPPED:
                return 'The service is not running.';
                break;
            case self::WIN32_SERVICE_NA:
                return 'Cannot retrieve service status.';
                break;
            default:
                return null;
                break;
        }
    }
References WIN32_SERVICE_CONTINUE_PENDING, WIN32_SERVICE_NA, WIN32_SERVICE_PAUSE_PENDING, WIN32_SERVICE_PAUSED, WIN32_SERVICE_RUNNING, WIN32_SERVICE_START_PENDING, WIN32_SERVICE_STOP_PENDING, and WIN32_SERVICE_STOPPED.
Referenced by getError().
infos()
infos ()
Definition at line 308 of file class.win32service.php.
    {
        if ($this->getNssm() instanceof Nssm) {
            return $this->getNssm()->infos();
        }
        return Vbs::getServiceInfos($this->getName());
    }
References getName(), getNssm(), and Vbs\getServiceInfos().
isInstalled()
isInstalled ()
Definition at line 317 of file class.win32service.php.
    {
        $status = $this->status();
        $this->writeLog('isInstalled ' . $this->getName() . ': ' . ($status != self::WIN32_SERVICE_NA ? 'YES' : 'NO') . ' (status: ' . $status . ')');
        return $status != self::WIN32_SERVICE_NA;
    }
References getName(), status(), WIN32_SERVICE_NA, and writeLog().
Referenced by create(), and delete().
isPaused()
isPaused ()
Definition at line 338 of file class.win32service.php.
    {
        $status = $this->status();
        $this->writeLog('isPaused ' . $this->getName() . ': ' . ($status == self::WIN32_SERVICE_PAUSED ? 'YES' : 'NO') . ' (status: ' . $status . ')');
        return $status == self::WIN32_SERVICE_PAUSED;
    }
References getName(), status(), WIN32_SERVICE_PAUSED, and writeLog().
isPending()
isPending ($status)
Definition at line 345 of file class.win32service.php.
    {
        return $status == self::WIN32_SERVICE_START_PENDING || $status == self::WIN32_SERVICE_STOP_PENDING
            || $status == self::WIN32_SERVICE_CONTINUE_PENDING || $status == self::WIN32_SERVICE_PAUSE_PENDING;
    }
References WIN32_SERVICE_PAUSE_PENDING.
Referenced by status().
isRunning()
isRunning ()
Definition at line 324 of file class.win32service.php.
    {
        $status = $this->status();
        $this->writeLog('isRunning ' . $this->getName() . ': ' . ($status == self::WIN32_SERVICE_RUNNING ? 'YES' : 'NO') . ' (status: ' . $status . ')');
        return $status == self::WIN32_SERVICE_RUNNING;
    }
References getName(), status(), WIN32_SERVICE_RUNNING, and writeLog().
Referenced by start().
isStopped()
isStopped ()
Definition at line 331 of file class.win32service.php.
    {
        $status = $this->status();
        $this->writeLog('isStopped ' . $this->getName() . ': ' . ($status == self::WIN32_SERVICE_STOPPED ? 'YES' : 'NO') . ' (status: ' . $status . ')');
        return $status == self::WIN32_SERVICE_STOPPED;
    }
References getName(), status(), WIN32_SERVICE_STOPPED, and writeLog().
Referenced by stop().
reset()
reset ()
Definition at line 220 of file class.win32service.php.
    {
        if ($this->delete()) {
            usleep(self::SLEEP_TIME);
            return $this->create();
        }
        return false;
    }
References create().
restart()
restart ()
Definition at line 300 of file class.win32service.php.
    {
        if ($this->stop()) {
            return $this->start();
        }
        return false;
    }
References start(), and stop().
setBinPath()
setBinPath ($binPath)
Definition at line 542 of file class.win32service.php.
    {
        $this->binPath = str_replace('"', '', Util::formatWindowsPath($binPath));
    }
References $binPath, and Util\formatWindowsPath().
Referenced by setNssm().
setDisplayName()
setDisplayName ($displayName)
Definition at line 532 of file class.win32service.php.
    {
        $this->displayName = $displayName;
    }
References $displayName.
Referenced by setNssm().
setErrorControl()
setErrorControl ($errorControl)
Definition at line 572 of file class.win32service.php.
    {
        $this->errorControl = $errorControl;
    }
References $errorControl.
setName()
setName ($name)
Definition at line 522 of file class.win32service.php.
    {
        $this->name = $name;
    }
References $name.
setNssm()
setNssm ($nssm)
Definition at line 582 of file class.win32service.php.
    {
        if ($nssm instanceof Nssm) {
            $this->setDisplayName($nssm->getDisplayName());
            $this->setBinPath($nssm->getBinPath());
            $this->setParams($nssm->getParams());
            $this->setStartType($nssm->getStart());
            $this->nssm = $nssm;
        }
    }
References $nssm, setBinPath(), setDisplayName(), setParams(), and setStartType().
setParams()
setParams ($params)
Definition at line 552 of file class.win32service.php.
    {
        $this->params = $params;
    }
References $params.
Referenced by setNssm().
setStartType()
setStartType ($startType)
Definition at line 562 of file class.win32service.php.
    {
        $this->startType = $startType;
    }
References $startType.
Referenced by setNssm().
start()
start ()
Definition at line 229 of file class.win32service.php.
    {
        global $bearsamppBins;
        if ($this->getName() == BinFilezilla::SERVICE_NAME) {
            $bearsamppBins->getFilezilla()->rebuildConf();
        } elseif ($this->getName() == BinMysql::SERVICE_NAME) {
            $bearsamppBins->getMysql()->initData();
        } elseif ($this->getName() == BinMailhog::SERVICE_NAME) {
            $bearsamppBins->getMailhog()->rebuildConf();
        } elseif ($this->getName() == BinMemcached::SERVICE_NAME) {
            $bearsamppBins->getMemcached()->rebuildConf();
        } elseif ($this->getName() == BinPostgresql::SERVICE_NAME) {
            $bearsamppBins->getPostgresql()->rebuildConf();
            $bearsamppBins->getPostgresql()->initData();
        }
        $start = dechex($this->callWin32Service('win32_start_service', $this->getName(), true));
        $this->writeLog('Start service ' . $this->getName() . ': ' . $start . ' (status: ' . $this->status() . ')');
        if ($start != self::WIN32_NO_ERROR && $start != self::WIN32_ERROR_SERVICE_ALREADY_RUNNING) {
            if ($this->getName() == BinApache::SERVICE_NAME) {
                $cmdOutput = $bearsamppBins->getApache()->getCmdLineOutput(BinApache::CMD_SYNTAX_CHECK);
                if (!$cmdOutput['syntaxOk']) {
                    file_put_contents(
                        $bearsamppBins->getApache()->getErrorLog(),
                        '[' . date('Y-m-d H:i:s', time()) . '] [error] ' . $cmdOutput['content'] . PHP_EOL,
                        FILE_APPEND
                    );
                }
            } elseif ($this->getName() == BinMysql::SERVICE_NAME) {
                $cmdOutput = $bearsamppBins->getMysql()->getCmdLineOutput(BinMysql::CMD_SYNTAX_CHECK);
                if (!$cmdOutput['syntaxOk']) {
                    file_put_contents(
                        $bearsamppBins->getMysql()->getErrorLog(),
                        '[' . date('Y-m-d H:i:s', time()) . '] [error] ' . $cmdOutput['content'] . PHP_EOL,
                        FILE_APPEND
                    );
                }
            } elseif ($this->getName() == BinMariadb::SERVICE_NAME) {
                $cmdOutput = $bearsamppBins->getMariadb()->getCmdLineOutput(BinMariadb::CMD_SYNTAX_CHECK);
                if (!$cmdOutput['syntaxOk']) {
                    file_put_contents(
                        $bearsamppBins->getMariadb()->getErrorLog(),
                        '[' . date('Y-m-d H:i:s', time()) . '] [error] ' . $cmdOutput['content'] . PHP_EOL,
                        FILE_APPEND
                    );
                }
            }
            return false;
        } elseif (!$this->isRunning()) {
            $this->latestError = self::WIN32_NO_ERROR;
            return false;
        }
        return true;
    }
References $bearsamppBins, callWin32Service(), BinApache\CMD_SYNTAX_CHECK, BinMariadb\CMD_SYNTAX_CHECK, BinMysql\CMD_SYNTAX_CHECK, getName(), isRunning(), BinApache\SERVICE_NAME, BinFilezilla\SERVICE_NAME, BinMailhog\SERVICE_NAME, BinMariadb\SERVICE_NAME, BinMemcached\SERVICE_NAME, BinMysql\SERVICE_NAME, BinPostgresql\SERVICE_NAME, status(), WIN32_NO_ERROR, and writeLog().
Referenced by restart().
status()
status ($timeout = true)
Definition at line 116 of file class.win32service.php.
    {
        usleep(self::SLEEP_TIME);
        $this->latestStatus = self::WIN32_SERVICE_NA;
        $maxtime = time() + self::PENDING_TIMEOUT;
        while ($this->latestStatus == self::WIN32_SERVICE_NA || $this->isPending($this->latestStatus)) {
            $this->latestStatus = $this->callWin32Service('win32_query_service_status', $this->getName());
            if (is_array($this->latestStatus) && isset($this->latestStatus['CurrentState'])) {
                $this->latestStatus = dechex($this->latestStatus['CurrentState']);
            } elseif (dechex($this->latestStatus) == self::WIN32_ERROR_SERVICE_DOES_NOT_EXIST) {
                $this->latestStatus = dechex($this->latestStatus);
            }
            if ($timeout && $maxtime < time()) {
                break;
            }
        }
        if ($this->latestStatus == self::WIN32_ERROR_SERVICE_DOES_NOT_EXIST) {
            $this->latestError = $this->latestStatus;
            $this->latestStatus = self::WIN32_SERVICE_NA;
        }
        return $this->latestStatus;
    }
References $latestStatus, callWin32Service(), getName(), isPending(), PENDING_TIMEOUT, and WIN32_SERVICE_NA.
Referenced by create(), delete(), isInstalled(), isPaused(), isRunning(), isStopped(), start(), and stop().
stop()
stop ()
Definition at line 286 of file class.win32service.php.
    {
        $stop = dechex($this->callWin32Service('win32_stop_service', $this->getName(), true));
        $this->writeLog('Stop service ' . $this->getName() . ': ' . $stop . ' (status: ' . $this->status() . ')');
        if ($stop != self::WIN32_NO_ERROR) {
            return false;
        } elseif (!$this->isStopped()) {
            $this->latestError = self::WIN32_NO_ERROR;
            return false;
        }
        return true;
    }
References callWin32Service(), getName(), isStopped(), status(), WIN32_NO_ERROR, and writeLog().
Referenced by delete(), and restart().
writeLog()
writeLog ($log) private
Definition at line 87 of file class.win32service.php.
    {
        global $bearsamppRoot;
        Util::logDebug($log, $bearsamppRoot->getServicesLogFilePath());
    }
References $bearsamppRoot, and Util\logDebug().
Referenced by create(), delete(), isInstalled(), isPaused(), isRunning(), isStopped(), start(), and stop().
Field Documentation
$binPath
$binPath private
Definition at line 72 of file class.win32service.php.
Referenced by getBinPath(), and setBinPath().
$displayName
$displayName private
Definition at line 71 of file class.win32service.php.
Referenced by getDisplayName(), and setDisplayName().
$errorControl
$errorControl private
Definition at line 75 of file class.win32service.php.
Referenced by getErrorControl(), and setErrorControl().
$latestError
$latestError private
Definition at line 79 of file class.win32service.php.
Referenced by getLatestError().
$latestStatus
$latestStatus private
Definition at line 78 of file class.win32service.php.
Referenced by getLatestStatus(), and status().
$name
$name private
Definition at line 70 of file class.win32service.php.
Referenced by __construct(), getName(), and setName().
$nssm
$nssm private
Definition at line 76 of file class.win32service.php.
Referenced by getNssm(), and setNssm().
$params
$params private
Definition at line 73 of file class.win32service.php.
Referenced by getParams(), and setParams().
$startType
$startType private
Definition at line 74 of file class.win32service.php.
Referenced by getStartType(), and setStartType().
PENDING_TIMEOUT
const PENDING_TIMEOUT = 20
Definition at line 61 of file class.win32service.php.
Referenced by status().
SERVER_ERROR_IGNORE
const SERVER_ERROR_IGNORE = "0"
Definition at line 54 of file class.win32service.php.
SERVER_ERROR_NORMAL
const SERVER_ERROR_NORMAL = "1"
Definition at line 55 of file class.win32service.php.
Referenced by create(), BinFilezilla\reload(), BinMariadb\reload(), BinMysql\reload(), and BinPostgresql\reload().
SERVICE_AUTO_START
const SERVICE_AUTO_START = "2"
Definition at line 57 of file class.win32service.php.
SERVICE_DEMAND_START
const SERVICE_DEMAND_START = "3"
Definition at line 58 of file class.win32service.php.
Referenced by create(), BinFilezilla\reload(), BinMariadb\reload(), BinMysql\reload(), and BinPostgresql\reload().
SERVICE_DISABLED
const SERVICE_DISABLED = "4"
Definition at line 59 of file class.win32service.php.
SLEEP_TIME
const SLEEP_TIME = 500000
Definition at line 62 of file class.win32service.php.
VBS_DESCRIPTION
const VBS_DESCRIPTION = 'Description'
Definition at line 66 of file class.win32service.php.
VBS_DISPLAY_NAME
const VBS_DISPLAY_NAME = 'DisplayName'
Definition at line 65 of file class.win32service.php.
VBS_NAME
const VBS_NAME = 'Name'
Definition at line 64 of file class.win32service.php.
VBS_PATH_NAME
const VBS_PATH_NAME = 'PathName'
Definition at line 67 of file class.win32service.php.
Referenced by Nssm\infos(), and ActionStartup\installServices().
VBS_STATE
const VBS_STATE = 'State'
Definition at line 68 of file class.win32service.php.
WIN32_ERROR_ACCESS_DENIED
const WIN32_ERROR_ACCESS_DENIED = "5"
Definition at line 23 of file class.win32service.php.
Referenced by getWin32ErrorCodeDesc().
WIN32_ERROR_CIRCULAR_DEPENDENCY
const WIN32_ERROR_CIRCULAR_DEPENDENCY = "423"
Definition at line 24 of file class.win32service.php.
Referenced by getWin32ErrorCodeDesc().
WIN32_ERROR_DATABASE_DOES_NOT_EXIST
const WIN32_ERROR_DATABASE_DOES_NOT_EXIST = "429"
Definition at line 25 of file class.win32service.php.
Referenced by getWin32ErrorCodeDesc().
WIN32_ERROR_DEPENDENT_SERVICES_RUNNING
const WIN32_ERROR_DEPENDENT_SERVICES_RUNNING = "41B"
Definition at line 26 of file class.win32service.php.
Referenced by getWin32ErrorCodeDesc().
WIN32_ERROR_DUPLICATE_SERVICE_NAME
const WIN32_ERROR_DUPLICATE_SERVICE_NAME = "436"
Definition at line 27 of file class.win32service.php.
Referenced by getWin32ErrorCodeDesc().
WIN32_ERROR_FAILED_SERVICE_CONTROLLER_CONNECT
const WIN32_ERROR_FAILED_SERVICE_CONTROLLER_CONNECT = "427"
Definition at line 28 of file class.win32service.php.
Referenced by getWin32ErrorCodeDesc().
WIN32_ERROR_INSUFFICIENT_BUFFER
const WIN32_ERROR_INSUFFICIENT_BUFFER = "7A"
Definition at line 29 of file class.win32service.php.
Referenced by getWin32ErrorCodeDesc().
WIN32_ERROR_INVALID_DATA
const WIN32_ERROR_INVALID_DATA = "D"
Definition at line 30 of file class.win32service.php.
Referenced by getWin32ErrorCodeDesc().
WIN32_ERROR_INVALID_HANDLE
const WIN32_ERROR_INVALID_HANDLE = "6"
Definition at line 31 of file class.win32service.php.
Referenced by getWin32ErrorCodeDesc().
WIN32_ERROR_INVALID_LEVEL
const WIN32_ERROR_INVALID_LEVEL = "7C"
Definition at line 32 of file class.win32service.php.
Referenced by getWin32ErrorCodeDesc().
WIN32_ERROR_INVALID_NAME
const WIN32_ERROR_INVALID_NAME = "7B"
Definition at line 33 of file class.win32service.php.
Referenced by getWin32ErrorCodeDesc().
WIN32_ERROR_INVALID_PARAMETER
const WIN32_ERROR_INVALID_PARAMETER = "57"
Definition at line 34 of file class.win32service.php.
Referenced by getWin32ErrorCodeDesc().
WIN32_ERROR_INVALID_SERVICE_ACCOUNT
const WIN32_ERROR_INVALID_SERVICE_ACCOUNT = "421"
Definition at line 35 of file class.win32service.php.
Referenced by getWin32ErrorCodeDesc().
WIN32_ERROR_INVALID_SERVICE_CONTROL
const WIN32_ERROR_INVALID_SERVICE_CONTROL = "41C"
Definition at line 36 of file class.win32service.php.
Referenced by getWin32ErrorCodeDesc().
WIN32_ERROR_PATH_NOT_FOUND
const WIN32_ERROR_PATH_NOT_FOUND = "3"
Definition at line 37 of file class.win32service.php.
Referenced by getWin32ErrorCodeDesc().
WIN32_ERROR_SERVICE_ALREADY_RUNNING
const WIN32_ERROR_SERVICE_ALREADY_RUNNING = "420"
Definition at line 38 of file class.win32service.php.
Referenced by getWin32ErrorCodeDesc().
WIN32_ERROR_SERVICE_CANNOT_ACCEPT_CTRL
const WIN32_ERROR_SERVICE_CANNOT_ACCEPT_CTRL = "425"
Definition at line 39 of file class.win32service.php.
Referenced by getWin32ErrorCodeDesc().
WIN32_ERROR_SERVICE_DATABASE_LOCKED
const WIN32_ERROR_SERVICE_DATABASE_LOCKED = "41F"
Definition at line 40 of file class.win32service.php.
Referenced by getWin32ErrorCodeDesc().
WIN32_ERROR_SERVICE_DEPENDENCY_DELETED
const WIN32_ERROR_SERVICE_DEPENDENCY_DELETED = "433"
Definition at line 41 of file class.win32service.php.
Referenced by getWin32ErrorCodeDesc().
WIN32_ERROR_SERVICE_DEPENDENCY_FAIL
const WIN32_ERROR_SERVICE_DEPENDENCY_FAIL = "42C"
Definition at line 42 of file class.win32service.php.
Referenced by getWin32ErrorCodeDesc().
WIN32_ERROR_SERVICE_DISABLED
const WIN32_ERROR_SERVICE_DISABLED = "422"
Definition at line 43 of file class.win32service.php.
Referenced by getWin32ErrorCodeDesc().
WIN32_ERROR_SERVICE_DOES_NOT_EXIST
const WIN32_ERROR_SERVICE_DOES_NOT_EXIST = "424"
Definition at line 44 of file class.win32service.php.
Referenced by getWin32ErrorCodeDesc().
WIN32_ERROR_SERVICE_EXISTS
const WIN32_ERROR_SERVICE_EXISTS = "431"
Definition at line 45 of file class.win32service.php.
Referenced by getWin32ErrorCodeDesc().
WIN32_ERROR_SERVICE_LOGON_FAILED
const WIN32_ERROR_SERVICE_LOGON_FAILED = "42D"
Definition at line 46 of file class.win32service.php.
Referenced by getWin32ErrorCodeDesc().
WIN32_ERROR_SERVICE_MARKED_FOR_DELETE
const WIN32_ERROR_SERVICE_MARKED_FOR_DELETE = "430"
Definition at line 47 of file class.win32service.php.
Referenced by getWin32ErrorCodeDesc().
WIN32_ERROR_SERVICE_NO_THREAD
const WIN32_ERROR_SERVICE_NO_THREAD = "41E"
Definition at line 48 of file class.win32service.php.
Referenced by getWin32ErrorCodeDesc().
WIN32_ERROR_SERVICE_NOT_ACTIVE
const WIN32_ERROR_SERVICE_NOT_ACTIVE = "426"
Definition at line 49 of file class.win32service.php.
Referenced by getWin32ErrorCodeDesc().
WIN32_ERROR_SERVICE_REQUEST_TIMEOUT
const WIN32_ERROR_SERVICE_REQUEST_TIMEOUT = "41D"
Definition at line 50 of file class.win32service.php.
Referenced by getWin32ErrorCodeDesc().
WIN32_ERROR_SHUTDOWN_IN_PROGRESS
const WIN32_ERROR_SHUTDOWN_IN_PROGRESS = "45B"
Definition at line 51 of file class.win32service.php.
Referenced by getWin32ErrorCodeDesc().
WIN32_NO_ERROR
const WIN32_NO_ERROR = "0"
Definition at line 52 of file class.win32service.php.
Referenced by create(), delete(), start(), and stop().
WIN32_SERVICE_CONTINUE_PENDING
const WIN32_SERVICE_CONTINUE_PENDING = "5"
Definition at line 13 of file class.win32service.php.
Referenced by getWin32ServiceStatusDesc().
WIN32_SERVICE_NA
const WIN32_SERVICE_NA = "0"
Definition at line 20 of file class.win32service.php.
Referenced by getWin32ServiceStatusDesc(), isInstalled(), and status().
WIN32_SERVICE_PAUSE_PENDING
const WIN32_SERVICE_PAUSE_PENDING = "6"
Definition at line 14 of file class.win32service.php.
Referenced by getWin32ServiceStatusDesc(), and isPending().
WIN32_SERVICE_PAUSED
const WIN32_SERVICE_PAUSED = "7"
Definition at line 15 of file class.win32service.php.
Referenced by getWin32ServiceStatusDesc(), and isPaused().
WIN32_SERVICE_RUNNING
const WIN32_SERVICE_RUNNING = "4"
Definition at line 16 of file class.win32service.php.
Referenced by getWin32ServiceStatusDesc(), and isRunning().
WIN32_SERVICE_START_PENDING
const WIN32_SERVICE_START_PENDING = "2"
Definition at line 17 of file class.win32service.php.
Referenced by getWin32ServiceStatusDesc().
WIN32_SERVICE_STOP_PENDING
const WIN32_SERVICE_STOP_PENDING = "3"
Definition at line 18 of file class.win32service.php.
Referenced by getWin32ServiceStatusDesc().
WIN32_SERVICE_STOPPED
const WIN32_SERVICE_STOPPED = "1"
Definition at line 19 of file class.win32service.php.
Referenced by getWin32ServiceStatusDesc(), and isStopped().
The documentation for this class was generated from the following file:
E:/Bearsampp-development/sandbox/core/classes/class.win32service.php