Bearsampp: TplAppPython Class Reference
TplAppPython Class Reference
Static Public Member Functions
static getMenuPython ()
static process ()
Data Fields
const MENU = 'python'
Detailed Description
Class TplAppPython
This class provides methods to generate menu items and actions for managing Python tools within the Bearsampp application. It includes functionalities for accessing Python console, IDLE, and other Python-related executables.
Definition at line 17 of file class.tpl.app.python.php.
Member Function Documentation
getMenuPython()
static TplAppPython::getMenuPython () static
Generates the Python menu with options for accessing the Python console, IDLE, and other tools.
@global object $bearsamppLang Provides language support for retrieving language-specific values. @global object $bearsamppTools Provides access to various tools and their configurations.
Returns
string The generated menu items and actions for Python tools.
Definition at line 44 of file class.tpl.app.python.php.
    {
        global $bearsamppLang, $bearsamppTools;
        // Generate menu item for Python console
        $resultItems = TplAestan::getItemConsoleZ(
            $bearsamppLang->getValue(Lang::PYTHON_CONSOLE),
            TplAestan::GLYPH_PYTHON,
            $bearsamppTools->getConsoleZ()->getTabTitlePython()
        ) . PHP_EOL;
        // Generate menu item for Python IDLE
        $resultItems .= TplAestan::getItemExe(
            $bearsamppLang->getValue(Lang::PYTHON) . ' IDLE',
            $bearsamppTools->getPython()->getIdleExe(),
            TplAestan::GLYPH_PYTHON
        ) . PHP_EOL;
        // Generate menu item for Python command prompt
        $resultItems .= TplAestan::getItemExe(
            $bearsamppLang->getValue(Lang::PYTHON_CP),
            $bearsamppTools->getPython()->getCpExe(),
            TplAestan::GLYPH_PYTHON_CP
        ) . PHP_EOL;
        return $resultItems;
    }
References $bearsamppLang, TplAestan\getItemConsoleZ(), TplAestan\getItemExe(), TplAestan\GLYPH_PYTHON, TplAestan\GLYPH_PYTHON_CP, Lang\PYTHON, Lang\PYTHON_CONSOLE, and Lang\PYTHON_CP.
process()
static TplAppPython::process () static
Generates the main Python menu with options to access Python tools.
@global object $bearsamppLang Provides language support for retrieving language-specific values.
Returns
string The generated menu items and actions for Python.
Definition at line 29 of file class.tpl.app.python.php.
    {
        global $bearsamppLang;
        return TplApp::getMenu($bearsamppLang->getValue(Lang::PYTHON), self::MENU, get_called_class());
    }
References $bearsamppLang, TplApp\getMenu(), and Lang\PYTHON.
Referenced by TplAppTools\getMenuTools().
Field Documentation
MENU
const TplAppPython::MENU = 'python'
Definition at line 20 of file class.tpl.app.python.php.
The documentation for this class was generated from the following file:
E:/Bearsampp-development/sandbox/core/classes/tpls/app/class.tpl.app.python.php