My Project: TplAppXlight Class Reference
TplAppXlight Class Reference
Static Public Member Functions
static getActionChangeXlightPort ()
static getActionEnableXlight ($enable)
static getActionInstallXlightService ()
static getActionRemoveXlightService ()
static getActionSwitchXlightVersion ($version)
static getMenuXlight ()
static getMenuXlightService ()
static getMenuXlightVersions ()
static process ()
Data Fields
const ACTION_CHANGE_PORT = 'changeXlightPort'
const ACTION_ENABLE = 'enableXlight'
const ACTION_INSTALL_SERVICE = 'installXlightService'
const ACTION_REMOVE_SERVICE = 'removeXlightService'
const ACTION_SWITCH_VERSION = 'switchXlightVersion'
const MENU = 'xlight'
const MENU_SERVICE = 'xlightService'
const MENU_VERSIONS = 'xlightVersions'
Detailed Description
Definition at line 10 of file class.tpl.app.xlight.php.
Member Function Documentation
getActionChangeXlightPort()
static TplAppXlight::getActionChangeXlightPort () static
Generates the action to change the Xlight port.
This method creates the action string for changing the Xlight port and includes a command to reload the application.
@global object $bearsamppBins Provides access to system binaries and their configurations.
Returns
string The generated action string for changing the Xlight port.
Definition at line 234 of file class.tpl.app.xlight.php.
    {
        global $bearsamppBins;
        return TplApp::getActionRun(Action::CHANGE_PORT, array($bearsamppBins->getXlight()->getName())) . PHP_EOL .
            TplAppReload::getActionReload();
    }
References $bearsamppBins, Action\CHANGE_PORT, TplAppReload\getActionReload(), and TplApp\getActionRun().
getActionEnableXlight()
static TplAppXlight::getActionEnableXlight ($enable) static
Generates the action to enable or disable Xlight.
This method creates the action string for enabling or disabling Xlight and includes a command to reload the application.
@global object $bearsamppBins Provides access to system binaries and their configurations.
Parameters
int $enable The enable flag (1 to enable, 0 to disable).
Returns
string The generated action string for enabling or disabling Xlight.
Definition at line 139 of file class.tpl.app.xlight.php.
    {
        global $bearsamppBins;
        return TplApp::getActionRun(Action::ENABLE, array($bearsamppBins->getXlight()->getName(), $enable)) . PHP_EOL .
            TplAppReload::getActionReload();
    }
References $bearsamppBins, Action\ENABLE, TplAppReload\getActionReload(), and TplApp\getActionRun().
getActionInstallXlightService()
static TplAppXlight::getActionInstallXlightService () static
Generates the action to install the Xlight service.
This method creates the action string for installing the Xlight service and includes a command to reload the application.
Returns
string The generated action string for installing the Xlight service.
Definition at line 249 of file class.tpl.app.xlight.php.
    {
        return TplApp::getActionRun(Action::SERVICE, array(BinXlight::SERVICE_NAME, ActionService::INSTALL)) . PHP_EOL .
            TplAppReload::getActionReload();
    }
References TplAppReload\getActionReload(), TplApp\getActionRun(), ActionService\INSTALL, Action\SERVICE, and BinXlight\SERVICE_NAME.
getActionRemoveXlightService()
static TplAppXlight::getActionRemoveXlightService () static
Generates the action to remove the Xlight service.
This method creates the action string for removing the Xlight service and includes a command to reload the application.
Returns
string The generated action string for removing the Xlight service.
Definition at line 262 of file class.tpl.app.xlight.php.
    {
        return TplApp::getActionRun(Action::SERVICE, array(BinXlight::SERVICE_NAME, ActionService::REMOVE)) . PHP_EOL .
            TplAppReload::getActionReload();
    }
References TplAppReload\getActionReload(), TplApp\getActionRun(), ActionService\REMOVE, Action\SERVICE, and BinXlight\SERVICE_NAME.
getActionSwitchXlightVersion()
static TplAppXlight::getActionSwitchXlightVersion ($version) static
Generates the action to switch the Xlight version.
This method creates the action string for switching the Xlight version and includes a command to reload the application.
@global object $bearsamppBins Provides access to system binaries and their configurations.
Parameters
string $version The version to switch to.
Returns
string The generated action string for switching the Xlight version.
Definition at line 157 of file class.tpl.app.xlight.php.
    {
        global $bearsamppBins;
        return TplApp::getActionRun(Action::SWITCH_VERSION, array($bearsamppBins->getXlight()->getName(), $version)) . PHP_EOL .
            TplAppReload::getActionReload() . PHP_EOL;
    }
References $bearsamppBins, TplAppReload\getActionReload(), TplApp\getActionRun(), and Action\SWITCH_VERSION.
getMenuXlight()
static TplAppXlight::getMenuXlight () static
Generates the Xlight menu.
This method creates the menu items and associated actions for Xlight, including options for downloading, enabling, switching versions, managing the service, and viewing logs.
@global object $bearsamppRoot Provides access to the root path of the application. @global object $bearsamppConfig Provides access to the application configuration. @global object $bearsamppBins Provides access to system binaries and their configurations. @global object $bearsamppLang Provides language support for retrieving language-specific values.
Returns
string The generated Xlight menu items and actions.
Definition at line 53 of file class.tpl.app.xlight.php.
    {
        global $bearsamppRoot, $bearsamppConfig, $bearsamppBins, $bearsamppLang;
        $resultItems = $resultActions = '';
        $isEnabled = $bearsamppBins->getXlight()->isEnable();
        // Download
        $resultItems .= TplAestan::getItemLink(
                $bearsamppLang->getValue(Lang::DOWNLOAD_MORE),
                Util::getWebsiteUrl('module/xlight', '#releases'),
                false,
                TplAestan::GLYPH_BROWSER
            ) . PHP_EOL;
        // Enable
        $tplEnable     = TplApp::getActionMulti(
            self::ACTION_ENABLE, array($isEnabled ? Config::DISABLED : Config::ENABLED),
            array($bearsamppLang->getValue(Lang::MENU_ENABLE), $isEnabled ? TplAestan::GLYPH_CHECK : ''),
            false, get_called_class()
        );
        $resultItems   .= $tplEnable[TplApp::SECTION_CALL] . PHP_EOL;
        $resultActions .= $tplEnable[TplApp::SECTION_CONTENT] . PHP_EOL;
        if ($isEnabled) {
            $resultItems .= TplAestan::getItemSeparator() . PHP_EOL;
            // Versions
            $tplVersions   = TplApp::getMenu($bearsamppLang->getValue(Lang::VERSIONS), self::MENU_VERSIONS, get_called_class());
            $resultItems   .= $tplVersions[TplApp::SECTION_CALL] . PHP_EOL;
            $resultActions .= $tplVersions[TplApp::SECTION_CONTENT] . PHP_EOL;
            // Service
            $tplService    = TplApp::getMenu($bearsamppLang->getValue(Lang::SERVICE), self::MENU_SERVICE, get_called_class());
            $resultItems   .= $tplService[TplApp::SECTION_CALL] . PHP_EOL;
            $resultActions .= $tplService[TplApp::SECTION_CONTENT] . PHP_EOL;
            // Log
            $resultItems .= TplAestan::getItemNotepad($bearsamppLang->getValue(Lang::MENU_LOGS), $bearsamppBins->getXlight()->getLog()) . PHP_EOL;
        }
        return $resultItems . PHP_EOL . $resultActions;
    }
References $bearsamppBins, $bearsamppConfig, $bearsamppLang, $bearsamppRoot, Config\DISABLED, Lang\DOWNLOAD_MORE, Config\ENABLED, TplApp\getActionMulti(), TplAestan\getItemLink(), TplAestan\getItemNotepad(), TplAestan\getItemSeparator(), TplApp\getMenu(), Util\getWebsiteUrl(), TplAestan\GLYPH_BROWSER, TplAestan\GLYPH_CHECK, Lang\MENU_ENABLE, Lang\MENU_LOGS, TplApp\SECTION_CALL, TplApp\SECTION_CONTENT, Lang\SERVICE, and Lang\VERSIONS.
getMenuXlightService()
static TplAppXlight::getMenuXlightService () static
Generates the Xlight service menu.
This method creates the menu items and associated actions for managing the Xlight service, including starting, stopping, restarting, changing ports, and installing or removing the service.
@global object $bearsamppRoot Provides access to the root path of the application. @global object $bearsamppLang Provides language support for retrieving language-specific values. @global object $bearsamppBins Provides access to system binaries and their configurations.
Returns
string The generated Xlight service menu items and actions.
Definition at line 177 of file class.tpl.app.xlight.php.
    {
        global $bearsamppRoot, $bearsamppLang, $bearsamppBins;
        $tplChangePort = TplApp::getActionMulti(
            self::ACTION_CHANGE_PORT, null,
            array($bearsamppLang->getValue(Lang::MENU_CHANGE_PORT), TplAestan::GLYPH_NETWORK),
            false, get_called_class()
        );
        $isInstalled = $bearsamppBins->getXlight()->getService()->isInstalled();
        $result = TplAestan::getItemActionServiceStart($bearsamppBins->getXlight()->getService()->getName()) . PHP_EOL .
            TplAestan::getItemActionServiceStop($bearsamppBins->getXlight()->getService()->getName()) . PHP_EOL .
            TplAestan::getItemActionServiceRestart($bearsamppBins->getXlight()->getService()->getName()) . PHP_EOL .
            TplAestan::getItemSeparator() . PHP_EOL .
            TplApp::getActionRun(
                Action::CHECK_PORT, array($bearsamppBins->getXlight()->getName(), $bearsamppBins->getXlight()->getPort()),
                array(sprintf($bearsamppLang->getValue(Lang::MENU_CHECK_PORT), $bearsamppBins->getXlight()->getPort()), TplAestan::GLYPH_LIGHT)
            ) . PHP_EOL .
            $tplChangePort[TplApp::SECTION_CALL] . PHP_EOL .
            TplAestan::getItemNotepad($bearsamppLang->getValue(Lang::MENU_UPDATE_ENV_PATH), $bearsamppRoot->getRootPath() . '/nssmEnvPaths.dat') . PHP_EOL;
        if (!$isInstalled) {
            $tplInstallService = TplApp::getActionMulti(
                self::ACTION_INSTALL_SERVICE, null,
                array($bearsamppLang->getValue(Lang::MENU_INSTALL_SERVICE), TplAestan::GLYPH_SERVICE_INSTALL),
                $isInstalled, get_called_class()
            );
            $result .= $tplInstallService[TplApp::SECTION_CALL] . PHP_EOL . PHP_EOL .
                $tplInstallService[TplApp::SECTION_CONTENT] . PHP_EOL;
        } else {
            $tplRemoveService = TplApp::getActionMulti(
                self::ACTION_REMOVE_SERVICE, null,
                array($bearsamppLang->getValue(Lang::MENU_REMOVE_SERVICE), TplAestan::GLYPH_SERVICE_REMOVE),
                !$isInstalled, get_called_class()
            );
            $result .= $tplRemoveService[TplApp::SECTION_CALL] . PHP_EOL . PHP_EOL .
                $tplRemoveService[TplApp::SECTION_CONTENT] . PHP_EOL;
        }
        $result .= $tplChangePort[TplApp::SECTION_CONTENT] . PHP_EOL;
        return $result;
    }
References $bearsamppBins, $bearsamppLang, $bearsamppRoot, $result, Action\CHECK_PORT, TplApp\getActionMulti(), TplApp\getActionRun(), TplAestan\getItemActionServiceRestart(), TplAestan\getItemActionServiceStart(), TplAestan\getItemActionServiceStop(), TplAestan\getItemNotepad(), TplAestan\getItemSeparator(), TplAestan\GLYPH_LIGHT, TplAestan\GLYPH_NETWORK, TplAestan\GLYPH_SERVICE_INSTALL, TplAestan\GLYPH_SERVICE_REMOVE, Lang\MENU_CHANGE_PORT, Lang\MENU_CHECK_PORT, Lang\MENU_INSTALL_SERVICE, Lang\MENU_REMOVE_SERVICE, Lang\MENU_UPDATE_ENV_PATH, TplApp\SECTION_CALL, and TplApp\SECTION_CONTENT.
getMenuXlightVersions()
static TplAppXlight::getMenuXlightVersions () static
Generates the Xlight versions menu.
This method creates the menu items and associated actions for switching between different versions of Xlight.
@global object $bearsamppBins Provides access to system binaries and their configurations.
Returns
string The generated Xlight versions menu items and actions.
Definition at line 106 of file class.tpl.app.xlight.php.
    {
        global $bearsamppBins;
        $items   = '';
        $actions = '';
        foreach ($bearsamppBins->getXlight()->getVersionList() as $version) {
            $tplSwitchXlightVersion = TplApp::getActionMulti(
                self::ACTION_SWITCH_VERSION, array($version),
                array($version, $version == $bearsamppBins->getXlight()->getVersion() ? TplAestan::GLYPH_CHECK : ''),
                false, get_called_class()
            );
            // Item
            $items .= $tplSwitchXlightVersion[TplApp::SECTION_CALL] . PHP_EOL;
            // Action
            $actions .= PHP_EOL . $tplSwitchXlightVersion[TplApp::SECTION_CONTENT];
        }
        return $items . $actions;
    }
References $bearsamppBins, TplApp\getActionMulti(), TplAestan\GLYPH_CHECK, TplApp\SECTION_CALL, and TplApp\SECTION_CONTENT.
process()
static TplAppXlight::process () static
Processes the Xlight menu.
This method generates the menu for enabling or disabling Xlight. It uses the global language object to retrieve the localized string for Xlight.
@global object $bearsamppLang Provides language support for retrieving language-specific values. @global object $bearsamppBins Provides access to system binaries and their configurations.
Returns
array The generated menu for enabling or disabling Xlight.
Definition at line 33 of file class.tpl.app.xlight.php.
    {
        global $bearsamppLang, $bearsamppBins;
        return TplApp::getMenuEnable($bearsamppLang->getValue(Lang::XLIGHT), self::MENU, get_called_class(), $bearsamppBins->getXlight()->isEnable());
    }
References $bearsamppBins, $bearsamppLang, TplApp\getMenuEnable(), and Lang\XLIGHT.
Referenced by TplApp\getSectionMenuLeft().
Field Documentation
ACTION_CHANGE_PORT
const TplAppXlight::ACTION_CHANGE_PORT = 'changeXlightPort'
Definition at line 18 of file class.tpl.app.xlight.php.
ACTION_ENABLE
const TplAppXlight::ACTION_ENABLE = 'enableXlight'
Definition at line 16 of file class.tpl.app.xlight.php.
ACTION_INSTALL_SERVICE
const TplAppXlight::ACTION_INSTALL_SERVICE = 'installXlightService'
Definition at line 19 of file class.tpl.app.xlight.php.
ACTION_REMOVE_SERVICE
const TplAppXlight::ACTION_REMOVE_SERVICE = 'removeXlightService'
Definition at line 20 of file class.tpl.app.xlight.php.
ACTION_SWITCH_VERSION
const TplAppXlight::ACTION_SWITCH_VERSION = 'switchXlightVersion'
Definition at line 17 of file class.tpl.app.xlight.php.
MENU
const TplAppXlight::MENU = 'xlight'
Definition at line 12 of file class.tpl.app.xlight.php.
MENU_SERVICE
const TplAppXlight::MENU_SERVICE = 'xlightService'
Definition at line 14 of file class.tpl.app.xlight.php.
MENU_VERSIONS
const TplAppXlight::MENU_VERSIONS = 'xlightVersions'
Definition at line 13 of file class.tpl.app.xlight.php.
The documentation for this class was generated from the following file:
E:/Bearsampp-development/sandbox/core/classes/tpls/app/class.tpl.app.xlight.php