Bearsampp: E:/Bearsampp-development/sandbox/core/libs/winbinder/db/db_common.inc.php File Reference
db_common.inc.php File Reference
Functions
db_close_database ()
db_create_database ($database, $server="", $username="", $password="")
db_create_field ($tablename, $field, $type)
db_create_record ($tablename, $fieldnames=null, $fieldvalues=null, $idfield="id")
db_create_table ($tablename, $fieldnames, $fieldattrib, $idfield="id", $valarray=null)
db_delete_field ($tablename, $field)
db_delete_records ($tablename, $idarray, $idfield="id")
db_delete_table ($tablename)
db_edit_field ($tablename, $field, $type)
db_edit_record ($tablename, $id=0, $fieldnames=null, $fieldvalues=null, $idfield="id")
db_escape_string ($str)
db_fetch_array ($result, $type=FETCH_NUM)
db_free_result ($result)
db_get_data ($tablename, $id=null, $col=null, $where="", $result_type=FETCH_NUM, $idfield="id", $orderby="")
db_get_id ($tablename, $index, $idfield="id")
db_get_index ($tablename, $id, $idfield="id")
db_get_info ($info="")
db_get_next_free_id ($tablename, $idfield="id")
db_list_database_tables ()
db_list_table_fields ($tablename, $type=false)
db_open_database ($database, $server="", $username="", $password="")
db_query ($query)
db_rename_field ($tablename, $field, $newname, $type)
db_rename_table ($tablename, $newname)
db_swap_records ($tablename, $id1, $id2, $idfield="id", $xchangeid=true)
db_table_exists ($tablename)
Variables
$_mainpath = pathinfo(__FILE__)
const DB_WRAPVERSION "db_v2b"
if (!defined("APPPREFIX")) define("APPPREFIX"
Function Documentation
db_close_database()
db_close_database ()
db_close_database()
Returns
bool "TRUE" or "FALSE"
Definition at line 113 of file db_common.inc.php.
{
  return raw_db_close_database();
}
References raw_db_close_database().
db_create_database()
db_create_database ($database, $server = "", $username = "", $password = "")
db_create_database() Creates a database if it does not exist
Parameters
$database
string $server
string $username
string $password
Returns
resource or "FALSE"
Definition at line 77 of file db_common.inc.php.
{
  return raw_db_create_database($database, $server, $username , $password);
}
References raw_db_create_database().
db_create_field()
db_create_field ($tablename, $field, $type)
db_create_field()
Parameters
$tablename
$field
$type
Returns
bool "TRUE" or "FALSE"
Definition at line 248 of file db_common.inc.php.
{
  return raw_db_create_field(APPPREFIX . $tablename, $field, $type);
}
References raw_db_create_field().
db_create_record()
db_create_record ($tablename, $fieldnames = null, $fieldvalues = null, $idfield = "id")
db_create_record()
Insert a new record in table $tablename.
Parameters
$tablename Table name. If NULL uses the table used in last function call.
unknown $fieldnames Array or CSV string with field names, one per line.
unknown $fieldvalues Array or CSV string with field values, one per line.
string $idfield
Returns
id of the affected record, FALSE if not succeded
Definition at line 304 of file db_common.inc.php.
{
  global $g_lasttable;
  if (!$tablename)
    $tablename = $g_lasttable;
  $g_lasttable = $tablename;
    if (!$fieldnames) {
      $fieldnames = db_list_table_fields($tablename);
      array_shift($fieldnames);
    }
    if (!$fieldvalues) {
      $fieldvalues = array_fill(0, count($fieldnames), 0);
    }
  // Get next available index
  $sql = "SELECT max($idfield) FROM " . APPPREFIX . $tablename;
  $result = raw_db_query($sql);
  if ($result === false) {
    return false;
  }
  $newid = (db_fetch_array($result, FETCH_NUM)) ;
  $newid = $newid[0] + 1;
  // Build the two arrays
  $names = is_string($fieldnames) ? preg_split("/[\r\n]/", $fieldnames) : $fieldnames;
  $values = is_string($fieldvalues) ? preg_split("/[\r\n]/", $fieldvalues) : $fieldvalues;
  if (count($names) != count($values)) {
    trigger_error(__FUNCTION__ . ": both arrays must be same length.\n");
    return false;
  }
  // Build the SQL query
  $nfields = count($names);
  $fieldnames = $names;
  $fieldvalues = $values;
  for($i = 0, $names = ""; $i < $nfields; $i++)
  $names .= $fieldnames[$i] . ($i < $nfields - 1 ? ", " : "");
  for($i = 0, $values = ""; $i < $nfields; $i++)
  $values .= "'" . db_escape_string($fieldvalues[$i]) . "'" . ($i < $nfields - 1 ? ", " : "");
  $sql = "INSERT INTO " . APPPREFIX . $tablename . " ($idfield, $names) VALUES ($newid, $values)";
  $result = raw_db_query($sql);
  if (!$result) {
    trigger_error(__FUNCTION__ . ": could not create new record in table $tablename.");
    return false;
  }
  return $newid;
}
References $result, db_escape_string(), db_fetch_array(), db_list_table_fields(), FETCH_NUM, and raw_db_query().
Referenced by db_create_table(), and db_edit_record().
db_create_table()
db_create_table ($tablename, $fieldnames, $fieldattrib, $idfield = "id", $valarray = null)
db_create_table()
Parameters
$tablename
$fieldnames (beside "id")
$fieldattrib
string $idfield (set to "id")
array $valarray ($valarray[0] = 1.record, $valarray[1] = 2.record, ...)
Returns
bool "TRUE" or "FALSE" if Table already exists, could not create Table, could not create Records
Definition at line 144 of file db_common.inc.php.
{
  global $g_lasttable;
  if ($tablename == null || $tablename == "")
    $tablename = $g_lasttable;
  $g_lasttable = $tablename;
  if (db_table_exists($tablename))
    return false;
  if (is_string($fieldnames))
    $fieldnames = preg_split("/[\r\n,]/", $fieldnames);
  if (is_string($fieldattrib))
    $fieldattrib = preg_split("/[\r\n,]/", $fieldattrib);
  $attribs = count($fieldattrib);
  if (count($fieldnames) != $attribs) {
    trigger_error(__FUNCTION__ . ": both arrays must be same length.");
    return false;
  }
  $sql = "CREATE TABLE " . APPPREFIX . "$tablename (";
  $sql .= "$idfield int(11) NOT NULL PRIMARY KEY ";
  if ($attribs != 0) {
    $sql .= ", ";
    for($i = 0; $i < $attribs; $i++)
    $sql .= $fieldnames[$i] . " " . $fieldattrib[$i] . ($i < $attribs - 1 ? ", " : "");
  }
  $sql .= ")";
  // Send the sql command
  $result = raw_db_query($sql);
  if (!$result) {
    trigger_error(__FUNCTION__ . ": could not create table $tablename.");
    return false;
  }
  if ($valarray)
    foreach($valarray as $values) {
    $result = db_create_record($tablename, $fieldnames, $values, $idfield);
    if ($result === false) {
      return false;
    }
  }
  return $result;
}
References $result, db_create_record(), db_table_exists(), and raw_db_query().
db_delete_field()
db_delete_field ($tablename, $field)
db_delete_field()
Parameters
$tablename
$field
Returns
bool "TRUE" or "FALSE"
Definition at line 260 of file db_common.inc.php.
{
  return raw_db_delete_field(APPPREFIX . $tablename, $field);
}
References raw_db_delete_field().
db_delete_records()
db_delete_records ($tablename, $idarray, $idfield = "id")
db_delete_records()
Delete record from table $tablename.
Parameters
$tablename
$idarray the id or id array
Returns
bool "TRUE" or "FALSE"
Definition at line 363 of file db_common.inc.php.
{
  global $g_lasttable;
  if ($idarray == null || $idarray <= 0)
    return false;
  if (!is_array($idarray))
    $idarray = array($idarray);
  if (!$tablename)
    $tablename = $g_lasttable;
  $g_lasttable = $tablename;
  foreach($idarray as $item) {
    // Send the SQL command
    $sql = "DELETE FROM " . APPPREFIX . $tablename . " WHERE $idfield = " . $item;
    $result = raw_db_query($sql);
    if (!$result) {
      trigger_error(__FUNCTION__ . ": could not delete record $id in table $tablename.");
      return false;
    }
  }
  return true;
}
References $result, and raw_db_query().
db_delete_table()
db_delete_table ($tablename)
db_delete_table()
Parameters
$tablename
Returns
bool "TRUE" or "FALSE"
Definition at line 196 of file db_common.inc.php.
{
  global $g_lasttable;
  if (!$tablename)
    $tablename = $g_lasttable;
  $g_lasttable = $tablename;
  if ($tablename == null || $tablename == "")
    return false;
  if (db_table_exists($tablename))
    $result = raw_db_query("DROP table " . APPPREFIX . $tablename);
  return $result;
}
References $result, db_table_exists(), and raw_db_query().
db_edit_field()
db_edit_field ($tablename, $field, $type)
db_edit_field() edit field attribute
Parameters
$tablename
$field
$type
Returns
bool "TRUE" or "FALSE"
Definition at line 288 of file db_common.inc.php.
{
  return raw_db_edit_field(APPPREFIX . $tablename, $field, $type);
}
References raw_db_edit_field().
db_edit_record()
db_edit_record ($tablename, $id = 0, $fieldnames = null, $fieldvalues = null, $idfield = "id")
db_edit_record()
Edits a record from table $tablename. If $id is null, zero or < 0, inserts a new record.
Parameters
$tablename If NULL uses the table used in last function call.
integer $id
unknown $fieldnames Array or CSV string with field names, one per line. If NULL, affects all fields.
unknown $fieldvalues Array or CSV string with field values, one per line.
string $idfield
Returns
id of the affected record or FALSE on error
Definition at line 400 of file db_common.inc.php.
{
  global $g_lasttable;
  if ($id == null || $id <= 0) { // Create a new record
    return db_create_record($tablename, $fieldnames, $fieldvalues, $idfield);
  } else { // Edit existing record
    if (!$tablename)
      $tablename = $g_lasttable;
    $g_lasttable = $tablename;
    // Build the two arrays
    if (!$fieldnames) {
      $fieldnames = db_list_table_fields($tablename);
      array_shift($fieldnames);
    }
    if (!$fieldvalues) {
      $fieldvalues = array_fill(0, count($fieldnames), 0);
    }
    $names = is_string($fieldnames) ? preg_split("/[\r\n]/", $fieldnames) : $fieldnames;
    $values = is_string($fieldvalues) ? preg_split("/[\r\n]/", $fieldvalues) : $fieldvalues;
    if (count($names) != count($values)) {
      trigger_error(__FUNCTION__ . ": both arrays must be same length.\n");
      return false;
    }
    // Build the SQL query
    $nfields = count($names);
    for($i = 0, $str = ""; $i < $nfields; $i++) {
      $str .= $names[$i] . "='" . db_escape_string($values[$i]) . "'" .
      ($i < $nfields - 1 ? ", " : "");
    }
    $sql = "UPDATE " . APPPREFIX . "$tablename SET $str WHERE $idfield=$id";
    // Send the SQL command
    $result = raw_db_query($sql);
    if (!$result) {
      trigger_error(__FUNCTION__ . ": could not edit record $id in table $tablename.");
      return false;
    }
    return $id;
  }
}
References $result, db_create_record(), db_escape_string(), db_list_table_fields(), and raw_db_query().
Referenced by db_swap_records().
db_escape_string()
db_escape_string ($str)
db_escape_string()
Parameters
$str
Returns
string escaped
string mysql_real_escape_string (string unescaped_string [, resource link_identifier])
Definition at line 732 of file db_common.inc.php.
{
  return raw_db_escape_string($str);
}
References raw_db_escape_string().
Referenced by db_create_record(), and db_edit_record().
db_fetch_array()
db_fetch_array ($result, $type = FETCH_NUM)
db_fetch_array()
Parameters
$result
$type
Returns
array
array mysql_fetch_array (resource result [, int result_type]) int type MYSQL_ASSOC, MYSQL_NUM (== fetch_row), and MYSQL_BOTH
Definition at line 705 of file db_common.inc.php.
{
  return raw_db_fetch_array($result, $type);
}
References $result, and raw_db_fetch_array().
Referenced by db_create_record(), db_get_data(), db_get_id(), db_get_next_free_id(), db_swap_records(), and raw_db_list_table_fields_def().
db_free_result()
db_free_result ($result)
db_free_result()
Parameters
$result
Returns
bool "TRUE" or "FALSE"
Definition at line 721 of file db_common.inc.php.
{
  return raw_db_free_result($result);
}
References $result, and raw_db_free_result().
Referenced by db_get_data(), and db_get_id().
db_get_data()
db_get_data ($tablename, $id = null, $col = null, $where = "", $result_type = FETCH_NUM, $idfield = "id", $orderby = "")
db_get_data()
Reads data from table $tablename.
$tablename Table name. If NULL uses the table used in last function call. $id Identifier(s). May be an array or a CSV string $col Column(s) or field(s). May be an array or a CSV string $where Additional WHERE clause $result_type May be FETCH_ASSOC, FETCH_BOTH or FETCH_NUM $idfield Name of id field $orderby Additional ORDER BY clause
$id $col returns
int null array with the whole record $id int str the value of column $col from record $id int str[] array with column values in array $col of record $id int[] null array of arrays with values from all columns of the $id registers int[] str array with the values of column $col from the $id registers int[] str[] 2-D array with the values of columns $col from the $id registers null null array of arrays with the whole table null str array with values of the $col column from the whole table null str[] array of arrays with the values of the columns $col from all table
Parameters
$tablename
unknown $id
unknown $col
string $where
unknown $result_type
string $idfield
string $orderby
Returns
result or FALSE
Definition at line 535 of file db_common.inc.php.
{
  global $g_lasttable;
  if (!$tablename)
    $tablename = $g_lasttable;
  $g_lasttable = $tablename;
  if (is_array($col))
    $col = implode(",", $col);
  if ($col === null || $col === "")
    $col = "*";
  // Build the WHERE clause
  if ($id !== null) {
    if (is_string($id) && strstr($id, ",")) {
      $id = explode(",", $id);
    }
    if (is_array($id)) {
      $idcond = "";
      for($i = 0; $i < count($id); $i++)
      $idcond .= "$idfield = '{$id[$i]}'" . ($i < count($id) - 1 ? " OR " : "");
    } else
      $idcond = "$idfield = '$id'";
    $condition = $where ? " WHERE ($where) AND ($idcond)" : " WHERE ($idcond)";
  } else
    $condition = $where ? " WHERE ($where)" : "";
  $orderby = $orderby ? " ORDER BY $orderby" : "";
  // Do the query
  $sql = "SELECT $col FROM " . APPPREFIX . $tablename . $condition . $orderby;
  $result = raw_db_query($sql);
  if (!$result)
    return false;
  // Loop to build the return array
  $array = array();
  while ($row = db_fetch_array($result, $result_type)) {
    if (count($row) == 1)
      $row = array_shift($row);
    $array[] = $row;
  }
  if (db_free_result($result) === false) return false;
  // Return the result
  if (!is_array($array))
    return $array;
  switch (count($array)) {
    case 0:
      return false;
    case 1:
      $test = $array; // Copy array
      $elem = array_shift($test); // 1st element of array...
      if (is_null($elem)) // ...is it null?
        return false; // Yes: return null
      if (is_scalar($elem)) // ...is it a scalar?
        return $elem; // Yes: return the element alone
      else
        return $array; // No: return the whole array
    default:
      return $array;
  }
}
References $result, db_fetch_array(), db_free_result(), and raw_db_query().
Referenced by db_get_index().
db_get_id()
db_get_id ($tablename, $index, $idfield = "id")
db_get_id()
Returns the id of the record indexed by $index
Parameters
$tablename
$index
string $idfield
Returns
id or FALSE
Definition at line 629 of file db_common.inc.php.
{
  global $g_lasttable;
  if (!is_scalar($index)) {
    trigger_error(__FUNCTION__ . ": index must be an integer");
    return false;
  } else
    $index = (int)$index;
  if (!$tablename)
    $tablename = $g_lasttable;
  $g_lasttable = $tablename;
  // Do the query
  $sql = "SELECT $idfield FROM " . APPPREFIX . $tablename . " LIMIT 1 OFFSET $index";
  $result = raw_db_query($sql);
  if (!$result)
    return false;
  $ret = db_fetch_array($result, FETCH_NUM);
  if (db_free_result($result) === false)
    return false;
  return $ret[0];
}
References $result, db_fetch_array(), db_free_result(), FETCH_NUM, and raw_db_query().
db_get_index()
db_get_index ($tablename, $id, $idfield = "id")
db_get_index()
Returns the index of the record identified by $id
Parameters
$tablename
$id
string $idfield
Returns
index or FALSE
Definition at line 612 of file db_common.inc.php.
{
  $data = db_get_data($tablename, null, $idfield);
  return array_search($id, $data);
}
References db_get_data().
db_get_info()
db_get_info ($info = "")
db_get_info() Returns database and wrapper version information
Parameters
string $what
Returns
string
Definition at line 35 of file db_common.inc.php.
{
  switch (strtolower($info)) {
    case "version":
      return DB_DATABASE . " " . raw_get_db_version() . " with Database Wrapper " . DB_WRAPVERSION;
    case "dbtype":
      return DB_DATABASE;
    case "dbversion":
      return raw_get_db_version();
    case "wrapversion":
      return DB_WRAPVERSION;
  }
}
References DB_WRAPVERSION, and raw_get_db_version().
db_get_next_free_id()
db_get_next_free_id ($tablename, $idfield = "id")
db_get_next_free_id()
Returns the next available id in table $tablename.
Parameters
$tablename
string $idfield
Returns
id or FALSE
Definition at line 667 of file db_common.inc.php.
{
  global $g_current_db;
  global $g_lasttable;
  if (!$tablename)
    $tablename = $g_lasttable;
  $g_lasttable = $tablename;
  $sql = "SELECT max($idfield) FROM " . APPPREFIX . $tablename;
  $result = raw_db_query($sql);
  if (!$result) {
    return false;
  }
  $maxid = (db_fetch_array($result, FETCH_NUM)) ;
  return $maxid[0] + 1;
}
References $result, db_fetch_array(), FETCH_NUM, and raw_db_query().
Referenced by db_swap_records().
db_list_database_tables()
db_list_database_tables ()
db_list_database_tables() Returns an array with the list of tables of the current database
Returns
result or "FALSE"
Definition at line 88 of file db_common.inc.php.
{
  $tables = raw_db_list_database_tables();
  if (!$tables) {
    return false;
  }
  $tmp_tabs = "";
  $prefixlen = strlen(trim(APPPREFIX));
  if ($prefixlen > 0) {
    foreach($tables as $table) {
      if (!(stristr(substr($table, 0, $prefixlen), APPPREFIX) === false)) {
        $tmp_tabs[] = substr($table, strlen(APPPREFIX));
      }
    }
    if ($tmp_tabs == "") {
      return false;
    }
    return $tmp_tabs;
  } else return $tables;
}
References raw_db_list_database_tables().
db_list_table_fields()
db_list_table_fields ($tablename, $type = false)
db_list_table_fields()
Parameters
$tablename
Returns
array with the names of the fields of table $tablename or FALSE
Definition at line 228 of file db_common.inc.php.
{
  global $g_lasttable;
  if (!$tablename)
    $tablename = $g_lasttable;
  $g_lasttable = $tablename;
  $result = raw_db_list_table_fields_def(APPPREFIX . $tablename, $type);
  return $result;
}
References $result, and raw_db_list_table_fields_def().
Referenced by db_create_record(), and db_edit_record().
db_open_database()
db_open_database ($database, $server = "", $username = "", $password = "")
db_open_database() Opens and connects an existing database.
Parameters
$database
string $server
string $username
string $password
Returns
resource or "FALSE"
Definition at line 62 of file db_common.inc.php.
{
  return raw_db_open_database($database, $server, $username , $password);
}
References raw_db_open_database().
db_query()
db_query ($query)
depricated exists only for compatibility to previous version is the same as raw_db_query does not handle APPPREFIX
Definition at line 693 of file db_common.inc.php.
{
  return raw_db_query($query);
}
References raw_db_query().
Referenced by raw_db_list_table_fields_def().
db_rename_field()
db_rename_field ($tablename, $field, $newname, $type)
db_rename_field()
Parameters
$tablename
$field
$newname
$type
Returns
bool "TRUE" or "FALSE"
Definition at line 274 of file db_common.inc.php.
{
  return raw_db_rename_field(APPPREFIX . $tablename, $field, $newname, $type);
}
References raw_db_rename_field().
db_rename_table()
db_rename_table ($tablename, $newname)
db_rename_table()
Parameters
$tablename
$newname
Returns
bool "TRUE" or "FALSE"
Definition at line 218 of file db_common.inc.php.
{
  return raw_db_rename_table(APPPREFIX . $tablename, APPPREFIX . $newname);
}
References raw_db_rename_table().
db_swap_records()
db_swap_records ($tablename, $id1, $id2, $idfield = "id", $xchangeid = true)
db_swap_records()
Swaps values from two records, including the id field or not according to $xchangeid.
Parameters
$tablename
$id1
$id2
string $idfield
boolean $xchangeid
Returns
bool
Definition at line 457 of file db_common.inc.php.
{
  global $g_lasttable;
  // Table name
  if (!$tablename)
    $tablename = $g_lasttable;
  $g_lasttable = $tablename;
  $table = APPPREFIX . "$tablename";
  // Build SQL strings
  $result = raw_db_query("SELECT * FROM $table WHERE $idfield = $id1");
  if (!$result) {
    trigger_error(__FUNCTION__ . ": could not read record $id1 in table $tablename.");
    return false;
  }
  $a = db_fetch_array($result, FETCH_ASSOC);
  $fieldvalues1 = array_values($a);
  $fieldnames1 = array_keys($a);
  array_shift($fieldvalues1);
  array_shift($fieldnames1);
  $result = raw_db_query("SELECT * FROM $table WHERE $idfield = $id2");
  if (!$result) {
    trigger_error(__FUNCTION__ . ": could not read record $id2 in table $tablename.");
    return false;
  }
  $a = db_fetch_array($result, FETCH_ASSOC);
  $fieldvalues2 = array_values($a);
  $fieldnames2 = array_keys($a);
  array_shift($fieldvalues2);
  array_shift($fieldnames2);
  // Exchange values
  if (db_edit_record($tablename, $id1, $fieldnames2, $fieldvalues2, $idfield) === false) return false;
  if (db_edit_record($tablename, $id2, $fieldnames1, $fieldvalues1, $idfield) === false) return false;
  // Exchange id's
  if ($xchangeid) {
    $unique = db_get_next_free_id($tablename);
    if (db_edit_record($tablename, $id1, array($idfield), array($unique), $idfield) === false) return false;
    if (db_edit_record($tablename, $id2, array($idfield), array($id1), $idfield) === false) return false;
    if (db_edit_record($tablename, $unique, array($idfield), array($id2), $idfield) === false) return false;
  }
  return true;
}
References $result, db_edit_record(), db_fetch_array(), db_get_next_free_id(), FETCH_ASSOC, and raw_db_query().
db_table_exists()
db_table_exists ($tablename)
db_table_exists()
Parameters
$tablename of an opened database
Returns
bool "TRUE" if table $tablename exists in the current database
Definition at line 124 of file db_common.inc.php.
{
  global $g_lasttable;
  if (!$tablename)
    $tablename = $g_lasttable;
  $g_lasttable = $tablename;
  return raw_db_table_exists(APPPREFIX . $tablename);
}
References raw_db_table_exists().
Referenced by db_create_table(), and db_delete_table().
Variable Documentation
$_mainpath
$_mainpath = pathinfo(__FILE__)
Definition at line 23 of file db_common.inc.php.
DB_WRAPVERSION
const DB_WRAPVERSION "db_v2b"
WINBINDER - The native Windows binding for PHP for PHP
Copyright Hypervisual - see LICENSE.TXT for details Authors: Rubem Pechansky and Hans Rebel
Database wrapper functions for WinBinder version 2b tested with SQLite and mySQL 7.mar
Definition at line 18 of file db_common.inc.php.
Referenced by db_get_info().
if
if(!defined("DB_DATABASE")) define("DB_DATABASE" (! defined"APPPREFIX")
Definition at line 20 of file db_common.inc.php.