Bearsampp: WinBinder Class Reference
WinBinder Class Reference
Public Member Functions
__construct ()
createAppWindow ($caption, $width, $height, $style=null, $params=null)
createButton ($parent, $caption, $xPos, $yPos, $width=null, $height=null, $style=null, $params=null)
createControl ($parent, $ctlClass, $caption, $xPos, $yPos, $width, $height, $style=null, $params=null)
createEditBox ($parent, $value, $xPos, $yPos, $width=null, $height=null, $style=null, $params=null)
createFont ($fontName, $size=null, $color=null, $style=null)
createHyperLink ($parent, $caption, $xPos, $yPos, $width=null, $height=null, $style=null, $params=null)
createInputText ($parent, $value, $xPos, $yPos, $width=null, $height=null, $maxLength=null, $style=null, $params=null)
createLabel ($parent, $caption, $xPos, $yPos, $width=null, $height=null, $style=null, $params=null)
createNakedWindow ($caption, $width, $height, $style=null, $params=null)
createProgressBar ($parent, $max, $xPos, $yPos, $width=null, $height=null, $style=null, $params=null)
createRadioButton ($parent, $caption, $checked, $xPos, $yPos, $width=null, $height=null, $startGroup=false)
createTimer ($wbobject, $wait=1000)
createWindow ($parent, $wclass, $caption, $xPos, $yPos, $width, $height, $style=null, $params=null)
destroyTimer ($wbobject, $timerobject)
destroyWindow ($window)
drawImage ($wbobject, $path, $xPos=0, $yPos=0, $width=0, $height=0)
drawLine ($wbobject, $xStartPos, $yStartPos, $xEndPos, $yEndPos, $color, $height=1)
drawRect ($parent, $xPos, $yPos, $width, $height, $color=15790320, $filled=true)
drawText ($parent, $caption, $xPos, $yPos, $width=null, $height=null, $font=null)
exec ($cmd, $params=null, $silent=false)
findFile ($filename)
getFocus ()
getSystemInfo ($info)
getText ($wbobject)
getValue ($wbobject)
incrProgressBar ($progressBar)
isEnabled ($wbobject)
mainLoop ()
messageBox ($message, $type, $title=null)
messageBoxError ($message, $title=null)
messageBoxInfo ($message, $title=null)
messageBoxOk ($message, $title=null)
messageBoxOkCancel ($message, $title=null)
messageBoxQuestion ($message, $title=null)
messageBoxWarning ($message, $title=null)
messageBoxYesNo ($message, $title=null)
messageBoxYesNoCancel ($message, $title=null)
refresh ($wbobject)
reset ()
resetProgressBar ($progressBar)
setArea ($wbobject, $width, $height)
setCursor ($wbobject, $type=self::CURSOR_ARROW)
setDisabled ($wbobject)
setEnabled ($wbobject, $enabled=true)
setFocus ($wbobject)
setHandler ($wbobject, $classCallback, $methodCallback, $launchTimer=null)
setImage ($wbobject, $path)
setMaxLength ($wbobject, $length)
setProgressBarMax ($progressBar, $max)
setProgressBarValue ($progressBar, $value)
setRange ($wbobject, $min, $max)
setStyle ($wbobject, $style)
setText ($wbobject, $content)
setValue ($wbobject, $content)
sysDlgOpen ($parent, $title, $filter=null, $path=null)
sysDlgPath ($parent, $title, $path=null)
wait ($wbobject=null)
Data Fields
$callback
$gauge
const BOX_ERROR = WBC_STOP
const BOX_INFO = WBC_INFO
const BOX_OK = WBC_OK
const BOX_OKCANCEL = WBC_OKCANCEL
const BOX_QUESTION = WBC_QUESTION
const BOX_WARNING = WBC_WARNING
const BOX_YESNO = WBC_YESNO
const BOX_YESNOCANCEL = WBC_YESNOCANCEL
const CTRL_ID = 0
const CTRL_OBJ = 1
const CURSOR_ARROW = 'arrow'
const CURSOR_CROSS = 'cross'
const CURSOR_FINGER = 'finger'
const CURSOR_FORBIDDEN = 'forbidden'
const CURSOR_HELP = 'help'
const CURSOR_IBEAM = 'ibeam'
const CURSOR_NONE = null
const CURSOR_SIZEALL = 'sizeall'
const CURSOR_SIZENESW = 'sizenesw'
const CURSOR_SIZENS = 'sizens'
const CURSOR_SIZENWSE = 'sizenwse'
const CURSOR_SIZEWE = 'sizewe'
const CURSOR_UPARROW = 'uparrow'
const CURSOR_WAIT = 'wait'
const CURSOR_WAITARROW = 'waitarrow'
const INCR_PROGRESS_BAR = '++'
const NEW_LINE = '@nl@'
const SYSINFO_SCREENAREA = 'screenarea'
const SYSINFO_WORKAREA = 'workarea'
Private Member Functions
callWinBinder ($function, $params=array(), $removeErrorHandler=false)
Static Private Member Functions
static writeLog ($log)
Private Attributes
$countCtrls
$defaultTitle
Detailed Description
Class WinBinder
This class provides an interface to the WinBinder library, allowing for the creation and management of Windows GUI elements in PHP. It includes methods for creating windows, controls, handling events, and executing system commands.
Definition at line 17 of file class.winbinder.php.
Constructor & Destructor Documentation
__construct()
WinBinder::__construct ()
WinBinder constructor.
Initializes the WinBinder class, sets the default window title, and resets control counters.
Definition at line 69 of file class.winbinder.php.
    {
        global $bearsamppCore;
        Util::logInitClass( $this );
        $this->defaultTitle = APP_TITLE . ' ' . $bearsamppCore->getAppVersion();
        $this->reset();
    }
References $bearsamppCore, APP_TITLE, Util\logInitClass(), and reset().
Member Function Documentation
callWinBinder()
WinBinder::callWinBinder ($function, $params = array(), $removeErrorHandler = false) private
Calls a WinBinder function with the specified parameters.
Parameters
string $function The name of the WinBinder function to call.
array $params The parameters to pass to the function.
bool $removeErrorHandler Whether to remove the error handler during the call.
Returns
mixed The result of the function call.
Definition at line 107 of file class.winbinder.php.
    {
        $result = false;
        if ( function_exists( $function ) ) {
            if ( $removeErrorHandler ) {
                $result = @call_user_func_array( $function, $params );
            }
            else {
                $result = call_user_func_array( $function, $params );
            }
        }
        return $result;
    }
References $result.
Referenced by createControl(), createFont(), createTimer(), createWindow(), destroyTimer(), destroyWindow(), drawImage(), drawLine(), drawRect(), drawText(), exec(), findFile(), getFocus(), getSystemInfo(), getText(), getValue(), isEnabled(), mainLoop(), messageBox(), refresh(), setArea(), setCursor(), setEnabled(), setFocus(), setHandler(), setImage(), setMaxLength(), setRange(), setStyle(), setText(), setValue(), sysDlgOpen(), sysDlgPath(), and wait().
createAppWindow()
WinBinder::createAppWindow ($caption, $width, $height, $style = null, $params = null)
Creates a new application window.
Parameters
string $caption The window caption.
int $width The width of the window.
int $height The height of the window.
mixed $style The window style.
mixed $params Additional parameters for the window.
Returns
mixed The created window object.
Definition at line 188 of file class.winbinder.php.
    {
        return $this->createWindow( null, AppWindow, $caption, WBC_CENTER, WBC_CENTER, $width, $height, $style, $params );
    }
References createWindow().
createButton()
WinBinder::createButton ($parent, $caption, $xPos, $yPos, $width = null, $height = null, $style = null, $params = null)
Creates a button control.
Parameters
mixed $parent The parent window or control.
string $caption The caption for the button.
int $xPos The x-coordinate of the button.
int $yPos The y-coordinate of the button.
int | null $width The width of the button.
int | null $height The height of the button.
mixed $style The style for the button.
mixed $params Additional parameters for the button.
Returns
array An array containing the control ID and object.
Definition at line 809 of file class.winbinder.php.
    {
        $width  = $width == null ? 80 : $width;
        $height = $height == null ? 25 : $height;
        return $this->createControl( $parent, PushButton, $caption, $xPos, $yPos, $width, $height, $style, $params );
    }
References createControl().
createControl()
WinBinder::createControl ($parent, $ctlClass, $caption, $xPos, $yPos, $width, $height, $style = null, $params = null)
Creates a new control.
Parameters
mixed $parent The parent window or control.
string $ctlClass The control class.
string $caption The control caption.
int $xPos The x-coordinate of the control.
int $yPos The y-coordinate of the control.
int $width The width of the control.
int $height The height of the control.
mixed $style The control style.
mixed $params Additional parameters for the control.
Returns
array An array containing the control ID and object.
Definition at line 165 of file class.winbinder.php.
    {
        $this->countCtrls++;
        return array(
            self::CTRL_ID  => $this->countCtrls,
            self::CTRL_OBJ => $this->callWinBinder( 'wb_create_control', array(
                $parent, $ctlClass, $caption, $xPos, $yPos, $width, $height, $this->countCtrls, $style, $params
            ) ),
        );
    }
References callWinBinder().
Referenced by createButton(), createEditBox(), createHyperLink(), createInputText(), createLabel(), createProgressBar(), and createRadioButton().
createEditBox()
WinBinder::createEditBox ($parent, $value, $xPos, $yPos, $width = null, $height = null, $style = null, $params = null)
Creates an edit box control.
Parameters
mixed $parent The parent window or control.
string $value The initial value for the edit box.
int $xPos The x-coordinate of the edit box.
int $yPos The y-coordinate of the edit box.
int | null $width The width of the edit box.
int | null $height The height of the edit box.
mixed $style The style for the edit box.
mixed $params Additional parameters for the edit box.
Returns
array An array containing the control ID and object.
Definition at line 737 of file class.winbinder.php.
    {
        $value   = str_replace( self::NEW_LINE, PHP_EOL, $value );
        $width   = $width == null ? 540 : $width;
        $height  = $height == null ? 340 : $height;
        $editBox = $this->createControl( $parent, RTFEditBox, (string) $value, $xPos, $yPos, $width, $height, $style, $params );
        return $editBox;
    }
References createControl().
createFont()
WinBinder::createFont ($fontName, $size = null, $color = null, $style = null)
Creates a font for use in WinBinder controls.
Parameters
string $fontName The name of the font.
int | null $size The size of the font.
int | null $color The color of the font.
mixed $style The style of the font.
Returns
mixed The created font object.
Definition at line 344 of file class.winbinder.php.
    {
        return $this->callWinBinder( 'wb_create_font', array($fontName, $size, $color, $style) );
    }
References callWinBinder().
createHyperLink()
WinBinder::createHyperLink ($parent, $caption, $xPos, $yPos, $width = null, $height = null, $style = null, $params = null)
Creates a hyperlink control.
Parameters
mixed $parent The parent window or control.
string $caption The caption for the hyperlink.
int $xPos The x-coordinate of the hyperlink.
int $yPos The y-coordinate of the hyperlink.
int | null $width The width of the hyperlink.
int | null $height The height of the hyperlink.
mixed $style The style for the hyperlink.
mixed $params Additional parameters for the hyperlink.
Returns
array An array containing the control ID and object.
Definition at line 761 of file class.winbinder.php.
    {
        $caption   = str_replace( self::NEW_LINE, PHP_EOL, $caption );
        $width     = $width == null ? 120 : $width;
        $height    = $height == null ? 15 : $height;
        $hyperLink = $this->createControl( $parent, HyperLink, (string) $caption, $xPos, $yPos, $width, $height, $style, $params );
        $this->setCursor( $hyperLink[self::CTRL_OBJ], self::CURSOR_FINGER );
        return $hyperLink;
    }
References createControl(), and setCursor().
createInputText()
WinBinder::createInputText ($parent, $value, $xPos, $yPos, $width = null, $height = null, $maxLength = null, $style = null, $params = null)
Creates an input text control.
Parameters
mixed $parent The parent window or control.
string $value The initial value for the input text.
int $xPos The x-coordinate of the input text.
int $yPos The y-coordinate of the input text.
int | null $width The width of the input text.
int | null $height The height of the input text.
int | null $maxLength The maximum length of the input text.
mixed $style The style for the input text.
mixed $params Additional parameters for the input text.
Returns
array An array containing the control ID and object.
Definition at line 710 of file class.winbinder.php.
    {
        $value     = str_replace( self::NEW_LINE, PHP_EOL, $value );
        $width     = $width == null ? 120 : $width;
        $height    = $height == null ? 25 : $height;
        $inputText = $this->createControl( $parent, EditBox, (string) $value, $xPos, $yPos, $width, $height, $style, $params );
        if ( is_numeric( $maxLength ) && $maxLength > 0 ) {
            $this->setMaxLength( $inputText[self::CTRL_OBJ], $maxLength );
        }
        return $inputText;
    }
References createControl(), and setMaxLength().
createLabel()
WinBinder::createLabel ($parent, $caption, $xPos, $yPos, $width = null, $height = null, $style = null, $params = null)
Creates a label control.
Parameters
mixed $parent The parent window or control.
string $caption The caption for the label.
int $xPos The x-coordinate of the label.
int $yPos The y-coordinate of the label.
int | null $width The width of the label.
int | null $height The height of the label.
mixed $style The style for the label.
mixed $params Additional parameters for the label.
Returns
array An array containing the control ID and object.
Definition at line 686 of file class.winbinder.php.
    {
        $caption = str_replace( self::NEW_LINE, PHP_EOL, $caption );
        $width   = $width == null ? 120 : $width;
        $height  = $height == null ? 25 : $height;
        return $this->createControl( $parent, Label, $caption, $xPos, $yPos, $width, $height, $style, $params );
    }
References createControl().
createNakedWindow()
WinBinder::createNakedWindow ($caption, $width, $height, $style = null, $params = null)
Creates a new naked window.
Parameters
string $caption The window caption.
int $width The width of the window.
int $height The height of the window.
mixed $style The window style.
mixed $params Additional parameters for the window.
Returns
mixed The created window object.
Definition at line 204 of file class.winbinder.php.
    {
        $window = $this->createWindow( null, NakedWindow, $caption, WBC_CENTER, WBC_CENTER, $width, $height, $style, $params );
        $this->setArea( $window, $width, $height );
        return $window;
    }
References createWindow(), and setArea().
createProgressBar()
WinBinder::createProgressBar ($parent, $max, $xPos, $yPos, $width = null, $height = null, $style = null, $params = null)
Creates a progress bar control.
Parameters
mixed $parent The parent window or control.
int $max The maximum value for the progress bar.
int $xPos The x-coordinate of the progress bar.
int $yPos The y-coordinate of the progress bar.
int | null $width The width of the progress bar.
int | null $height The height of the progress bar.
mixed $style The style for the progress bar.
mixed $params Additional parameters for the progress bar.
Returns
array An array containing the control ID and object.
Definition at line 831 of file class.winbinder.php.
    {
        global $bearsamppLang;
        $width       = $width == null ? 200 : $width;
        $height      = $height == null ? 15 : $height;
        $progressBar = $this->createControl( $parent, Gauge, $bearsamppLang->getValue( Lang::LOADING ), $xPos, $yPos, $width, $height, $style, $params );
        $this->setRange( $progressBar[self::CTRL_OBJ], 0, $max );
        $this->gauge[$progressBar[self::CTRL_OBJ]] = 0;
        return $progressBar;
    }
References $bearsamppLang, createControl(), CTRL_OBJ, Lang\LOADING, and setRange().
createRadioButton()
WinBinder::createRadioButton ($parent, $caption, $checked, $xPos, $yPos, $width = null, $height = null, $startGroup = false)
Creates a radio button control.
Parameters
mixed $parent The parent window or control.
string $caption The caption for the radio button.
bool $checked Whether the radio button is checked.
int $xPos The x-coordinate of the radio button.
int $yPos The y-coordinate of the radio button.
int | null $width The width of the radio button.
int | null $height The height of the radio button.
bool $startGroup Whether this radio button starts a new group.
Returns
array An array containing the control ID and object.
Definition at line 786 of file class.winbinder.php.
    {
        $caption = str_replace( self::NEW_LINE, PHP_EOL, $caption );
        $width   = $width == null ? 120 : $width;
        $height  = $height == null ? 25 : $height;
        return $this->createControl( $parent, RadioButton, (string) $caption, $xPos, $yPos, $width, $height, $startGroup ? WBC_GROUP : null, $checked ? 1 : 0 );
    }
References createControl().
createTimer()
WinBinder::createTimer ($wbobject, $wait = 1000)
Creates a timer for a WinBinder object.
Parameters
mixed $wbobject The WinBinder object to create the timer for.
int $wait The wait time in milliseconds.
Returns
array An array containing the timer ID and object.
Definition at line 369 of file class.winbinder.php.
    {
        $this->countCtrls++;
        return array(
            self::CTRL_ID  => $this->countCtrls,
            self::CTRL_OBJ => $this->callWinBinder( 'wb_create_timer', array($wbobject, $this->countCtrls, $wait) )
        );
    }
References callWinBinder().
Referenced by setHandler().
createWindow()
WinBinder::createWindow ($parent, $wclass, $caption, $xPos, $yPos, $width, $height, $style = null, $params = null)
Creates a new window.
Parameters
mixed $parent The parent window or null for a top-level window.
string $wclass The window class.
string $caption The window caption.
int $xPos The x-coordinate of the window.
int $yPos The y-coordinate of the window.
int $width The width of the window.
int $height The height of the window.
mixed $style The window style.
mixed $params Additional parameters for the window.
Returns
mixed The created window object.
Definition at line 137 of file class.winbinder.php.
    {
        global $bearsamppCore;
        $caption = empty( $caption ) ? $this->defaultTitle : $this->defaultTitle . ' - ' . $caption;
        $window  = $this->callWinBinder( 'wb_create_window', array($parent, $wclass, $caption, $xPos, $yPos, $width, $height, $style, $params) );
        // Set tiny window icon
        $this->setImage( $window, $bearsamppCore->getResourcesPath() . '/homepage/img/icons/app.ico' );
        return $window;
    }
References $bearsamppCore, callWinBinder(), and setImage().
Referenced by createAppWindow(), and createNakedWindow().
destroyTimer()
WinBinder::destroyTimer ($wbobject, $timerobject)
Destroys a timer for a WinBinder object.
Parameters
mixed $wbobject The WinBinder object to destroy the timer for.
mixed $timerobject The timer object to destroy.
Returns
mixed The result of the destroy operation.
Definition at line 387 of file class.winbinder.php.
    {
        return $this->callWinBinder( 'wb_destroy_timer', array($wbobject, $timerobject) );
    }
References callWinBinder().
destroyWindow()
WinBinder::destroyWindow ($window)
Destroys a window.
Parameters
mixed $window The window object to destroy.
Definition at line 217 of file class.winbinder.php.
    {
        $this->callWinBinder( 'wb_destroy_window', array($window), true );
        exit();
    }
References callWinBinder().
drawImage()
WinBinder::drawImage ($wbobject, $path, $xPos = 0, $yPos = 0, $width = 0, $height = 0)
Draws an image on a WinBinder object.
Parameters
mixed $wbobject The WinBinder object to draw on.
string $path The path to the image file.
int $xPos The x-coordinate of the image.
int $yPos The y-coordinate of the image.
int $width The width of the image.
int $height The height of the image.
Returns
mixed The result of the draw operation.
Definition at line 269 of file class.winbinder.php.
    {
        $image = $this->callWinBinder( 'wb_load_image', array($path) );
        return $this->callWinBinder( 'wb_draw_image', array($wbobject, $image, $xPos, $yPos, $width, $height) );
    }
References callWinBinder().
drawLine()
WinBinder::drawLine ($wbobject, $xStartPos, $yStartPos, $xEndPos, $yEndPos, $color, $height = 1)
Draws a line on a WinBinder object.
Parameters
mixed $wbobject The WinBinder object to draw on.
int $xStartPos The starting x-coordinate of the line.
int $yStartPos The starting y-coordinate of the line.
int $xEndPos The ending x-coordinate of the line.
int $yEndPos The ending y-coordinate of the line.
int $color The color of the line.
int $height The height of the line.
Returns
mixed The result of the draw operation.
Definition at line 329 of file class.winbinder.php.
    {
        return $this->callWinBinder( 'wb_draw_line', array($wbobject, $xStartPos, $yStartPos, $xEndPos, $yEndPos, $color, $height) );
    }
References callWinBinder().
drawRect()
WinBinder::drawRect ($parent, $xPos, $yPos, $width, $height, $color = 15790320, $filled = true)
Draws a rectangle on a WinBinder object.
Parameters
mixed $parent The parent WinBinder object.
int $xPos The x-coordinate of the rectangle.
int $yPos The y-coordinate of the rectangle.
int $width The width of the rectangle.
int $height The height of the rectangle.
int $color The color of the rectangle.
bool $filled Whether the rectangle should be filled.
Returns
mixed The result of the draw operation.
Definition at line 311 of file class.winbinder.php.
    {
        return $this->callWinBinder( 'wb_draw_rect', array($parent, $xPos, $yPos, $width, $height, $color, $filled) );
    }
References callWinBinder().
drawText()
WinBinder::drawText ($parent, $caption, $xPos, $yPos, $width = null, $height = null, $font = null)
Draws text on a WinBinder object.
Parameters
mixed $parent The parent WinBinder object.
string $caption The text to draw.
int $xPos The x-coordinate of the text.
int $yPos The y-coordinate of the text.
int | null $width The width of the text area.
int | null $height The height of the text area.
mixed $font The font to use for the text.
Returns
mixed The result of the draw operation.
Definition at line 289 of file class.winbinder.php.
    {
        $caption = str_replace( self::NEW_LINE, PHP_EOL, $caption );
        $width   = $width == null ? 120 : $width;
        $height  = $height == null ? 25 : $height;
        return $this->callWinBinder( 'wb_draw_text', array($parent, $caption, $xPos, $yPos, $width, $height, $font) );
    }
References callWinBinder().
exec()
WinBinder::exec ($cmd, $params = null, $silent = false)
Executes a system command.
Parameters
string $cmd The command to execute.
string | null $params The parameters to pass to the command.
bool $silent Whether to execute the command silently.
Returns
mixed The result of the command execution.
Definition at line 401 of file class.winbinder.php.
    {
        global $bearsamppCore;
        if ( $silent ) {
            $silent = '"' . $bearsamppCore->getScript( Core::SCRIPT_EXEC_SILENT ) . '" "' . $cmd . '"';
            $cmd    = 'wscript.exe';
            $params = !empty( $params ) ? $silent . ' "' . $params . '"' : $silent;
        }
        $this->writeLog( 'exec: ' . $cmd . ' ' . $params );
        return $this->callWinBinder( 'wb_exec', array($cmd, $params) );
    }
References $bearsamppCore, callWinBinder(), Core\SCRIPT_EXEC_SILENT, and writeLog().
findFile()
WinBinder::findFile ($filename)
Finds a file using WinBinder.
Parameters
string $filename The name of the file to find.
Returns
mixed The result of the find operation.
Definition at line 423 of file class.winbinder.php.
    {
        $result = $this->callWinBinder( 'wb_find_file', array($filename) );
        $this->writeLog( 'findFile ' . $filename . ': ' . $result );
        return $result != $filename ? $result : false;
    }
References $result, callWinBinder(), and writeLog().
getFocus()
WinBinder::getFocus ()
Retrieves the focus from a WinBinder object.
Returns
mixed The WinBinder object that has the focus.
Definition at line 549 of file class.winbinder.php.
    {
        return $this->callWinBinder( 'wb_get_focus' );
    }
References callWinBinder().
getSystemInfo()
WinBinder::getSystemInfo ($info)
Retrieves system information.
Parameters
string $info The type of system information to retrieve.
Returns
mixed The retrieved system information.
Definition at line 252 of file class.winbinder.php.
    {
        return $this->callWinBinder( 'wb_get_system_info', array($info) );
    }
References callWinBinder().
getText()
WinBinder::getText ($wbobject)
Retrieves the text from a WinBinder object.
Parameters
mixed $wbobject The WinBinder object to get the text from.
Returns
mixed The retrieved text.
Definition at line 499 of file class.winbinder.php.
    {
        return $this->callWinBinder( 'wb_get_text', array($wbobject) );
    }
References callWinBinder().
getValue()
WinBinder::getValue ($wbobject)
Retrieves the value from a WinBinder object.
Parameters
mixed $wbobject The WinBinder object to get the value from.
Returns
mixed The retrieved value.
Definition at line 526 of file class.winbinder.php.
    {
        return $this->callWinBinder( 'wb_get_value', array($wbobject) );
    }
References callWinBinder().
incrProgressBar()
WinBinder::incrProgressBar ($progressBar)
Increments the value of a progress bar.
Parameters
array $progressBar The progress bar control.
Definition at line 850 of file class.winbinder.php.
    {
        $this->setProgressBarValue( $progressBar, self::INCR_PROGRESS_BAR );
    }
References setProgressBarValue().
isEnabled()
WinBinder::isEnabled ($wbobject)
Checks if a WinBinder object is enabled.
Parameters
mixed $wbobject The WinBinder object to check.
Returns
mixed True if the object is enabled, false otherwise.
Definition at line 586 of file class.winbinder.php.
    {
        return $this->callWinBinder( 'wb_get_enabled', array($wbobject) );
    }
References callWinBinder().
mainLoop()
WinBinder::mainLoop ()
Starts the main event loop.
Returns
mixed The result of the main loop.
Definition at line 228 of file class.winbinder.php.
    {
        return $this->callWinBinder( 'wb_main_loop' );
    }
References callWinBinder().
messageBox()
WinBinder::messageBox ($message, $type, $title = null)
Displays a message box.
Parameters
string $message The message to display.
int $type The type of message box.
string | null $title The title of the message box.
Returns
mixed The result of the message box operation.
Definition at line 904 of file class.winbinder.php.
    {
        global $bearsamppCore;
        $message    = str_replace( self::NEW_LINE, PHP_EOL, $message );
        $messageBox = $this->callWinBinder( 'wb_message_box', array(
            null, strlen( $message ) < 64 ? str_pad( $message, 64 ) : $message, // Pad message to display entire title
            $title == null ? $this->defaultTitle : $this->defaultTitle . ' - ' . $title, $type
        ) );
        // TODO why does this create an error sometimes.
        // Set tiny window icon
        $this->setImage( $messageBox, $bearsamppCore->getResourcesPath() . '/homepage/img/icons/app.ico' );
        return $messageBox;
    }
References $bearsamppCore, callWinBinder(), and setImage().
Referenced by messageBoxError(), messageBoxInfo(), messageBoxOk(), messageBoxOkCancel(), messageBoxQuestion(), messageBoxWarning(), messageBoxYesNo(), and messageBoxYesNoCancel().
messageBoxError()
WinBinder::messageBoxError ($message, $title = null)
Displays an error message box.
Parameters
string $message The message to display.
string | null $title The title of the message box. If null, the default title will be used.
Returns
mixed The result of the message box operation.
Definition at line 981 of file class.winbinder.php.
    {
        return $this->messageBox( $message, self::BOX_ERROR, $title );
    }
References messageBox().
messageBoxInfo()
WinBinder::messageBoxInfo ($message, $title = null)
Displays an informational message box.
Parameters
string $message The message to display.
string | null $title The title of the message box.
Returns
mixed The result of the message box operation.
Definition at line 929 of file class.winbinder.php.
    {
        return $this->messageBox( $message, self::BOX_INFO, $title );
    }
References messageBox().
messageBoxOk()
WinBinder::messageBoxOk ($message, $title = null)
Displays an OK message box.
Parameters
string $message The message to display.
string | null $title The title of the message box.
Returns
mixed The result of the message box operation.
Definition at line 942 of file class.winbinder.php.
    {
        return $this->messageBox( $message, self::BOX_OK, $title );
    }
References messageBox().
messageBoxOkCancel()
WinBinder::messageBoxOkCancel ($message, $title = null)
Displays an OK/Cancel message box.
Parameters
string $message The message to display.
string | null $title The title of the message box.
Returns
mixed The result of the message box operation.
Definition at line 955 of file class.winbinder.php.
    {
        return $this->messageBox( $message, self::BOX_OKCANCEL, $title );
    }
References messageBox().
messageBoxQuestion()
WinBinder::messageBoxQuestion ($message, $title = null)
Displays a question message box.
Parameters
string $message The message to display.
string | null $title The title of the message box. If null, the default title will be used.
Returns
mixed The result of the message box operation.
Definition at line 968 of file class.winbinder.php.
    {
        return $this->messageBox( $message, self::BOX_QUESTION, $title );
    }
References messageBox().
messageBoxWarning()
WinBinder::messageBoxWarning ($message, $title = null)
Displays a warning message box.
Parameters
string $message The message to display.
string | null $title The title of the message box. If null, the default title will be used.
Returns
mixed The result of the message box operation.
Definition at line 994 of file class.winbinder.php.
    {
        return $this->messageBox( $message, self::BOX_WARNING, $title );
    }
References messageBox().
messageBoxYesNo()
WinBinder::messageBoxYesNo ($message, $title = null)
Displays a Yes/No message box.
Parameters
string $message The message to display.
string | null $title The title of the message box. If null, the default title will be used.
Returns
mixed The result of the message box operation.
Definition at line 1007 of file class.winbinder.php.
    {
        return $this->messageBox( $message, self::BOX_YESNO, $title );
    }
References messageBox().
messageBoxYesNoCancel()
WinBinder::messageBoxYesNoCancel ($message, $title = null)
Displays a Yes/No/Cancel message box.
Parameters
string $message The message to display.
string | null $title The title of the message box. If null, the default title will be used.
Returns
mixed The result of the message box operation.
Definition at line 1020 of file class.winbinder.php.
    {
        return $this->messageBox( $message, self::BOX_YESNOCANCEL, $title );
    }
References messageBox().
refresh()
WinBinder::refresh ($wbobject)
Refreshes a WinBinder object.
Parameters
mixed $wbobject The WinBinder object to refresh.
Returns
mixed The result of the refresh operation.
Definition at line 240 of file class.winbinder.php.
    {
        return $this->callWinBinder( 'wb_refresh', array($wbobject, true) );
    }
References callWinBinder().
reset()
WinBinder::reset ()
Resets the control counter and callback array.
Definition at line 92 of file class.winbinder.php.
    {
        $this->countCtrls = 1000;
        $this->callback   = array();
    }
Referenced by __construct().
resetProgressBar()
WinBinder::resetProgressBar ($progressBar)
Resets the value of a progress bar to zero.
Parameters
array $progressBar The progress bar control.
Definition at line 860 of file class.winbinder.php.
    {
        $this->setProgressBarValue( $progressBar, 0 );
    }
References setProgressBarValue().
setArea()
WinBinder::setArea ($wbobject, $width, $height)
Sets the area of a WinBinder object.
Parameters
mixed $wbobject The WinBinder object to set the area for.
int $width The width of the area.
int $height The height of the area.
Returns
mixed The result of the set area operation.
Definition at line 487 of file class.winbinder.php.
    {
        return $this->callWinBinder( 'wb_set_area', array($wbobject, WBC_TITLE, 0, 0, $width, $height) );
    }
References callWinBinder().
Referenced by createNakedWindow().
setCursor()
WinBinder::setCursor ($wbobject, $type = self::CURSOR_ARROW)
Sets the cursor type for a WinBinder object.
Parameters
mixed $wbobject The WinBinder object to set the cursor for.
string $type The cursor type to set.
Returns
mixed The result of the set cursor operation.
Definition at line 574 of file class.winbinder.php.
    {
        return $this->callWinBinder( 'wb_set_cursor', array($wbobject, $type) );
    }
References callWinBinder().
Referenced by createHyperLink().
setDisabled()
WinBinder::setDisabled ($wbobject)
Disables a WinBinder object.
Parameters
mixed $wbobject The WinBinder object to disable.
Returns
mixed The result of the disable operation.
Definition at line 611 of file class.winbinder.php.
    {
        return $this->setEnabled( $wbobject, false );
    }
References setEnabled().
setEnabled()
WinBinder::setEnabled ($wbobject, $enabled = true)
Sets the enabled state for a WinBinder object.
Parameters
mixed $wbobject The WinBinder object to set the enabled state for.
bool $enabled True to enable the object, false to disable it.
Returns
mixed The result of the set enabled state operation.
Definition at line 599 of file class.winbinder.php.
    {
        return $this->callWinBinder( 'wb_set_enabled', array($wbobject, $enabled) );
    }
References callWinBinder().
Referenced by setDisabled().
setFocus()
WinBinder::setFocus ($wbobject)
Sets the focus to a WinBinder object.
Parameters
mixed $wbobject The WinBinder object to set the focus to.
Returns
mixed The result of the set focus operation.
Definition at line 561 of file class.winbinder.php.
    {
        return $this->callWinBinder( 'wb_set_focus', array($wbobject) );
    }
References callWinBinder().
setHandler()
WinBinder::setHandler ($wbobject, $classCallback, $methodCallback, $launchTimer = null)
Sets an event handler for a WinBinder object.
Parameters
mixed $wbobject The WinBinder object to set the handler for.
mixed $classCallback The class callback for the handler.
mixed $methodCallback The method callback for the handler.
mixed $launchTimer The timer to launch for the handler.
Returns
mixed The result of the set handler operation.
Definition at line 441 of file class.winbinder.php.
    {
        if ( $launchTimer != null ) {
            $launchTimer = $this->createTimer( $wbobject, $launchTimer );
        }
        $this->callback[$wbobject] = array($classCallback, $methodCallback, $launchTimer);
        return $this->callWinBinder( 'wb_set_handler', array($wbobject, '__winbinderEventHandler') );
    }
References callWinBinder(), and createTimer().
setImage()
WinBinder::setImage ($wbobject, $path)
Sets an image for a WinBinder object.
Parameters
mixed $wbobject The WinBinder object to set the image for.
string $path The path to the image file.
Returns
mixed The result of the set image operation.
Definition at line 460 of file class.winbinder.php.
    {
        return $this->callWinBinder( 'wb_set_image', array($wbobject, $path) );
    }
References callWinBinder().
Referenced by createWindow(), and messageBox().
setMaxLength()
WinBinder::setMaxLength ($wbobject, $length)
Sets the maximum length for a WinBinder object.
Parameters
mixed $wbobject The WinBinder object to set the maximum length for.
int $length The maximum length to set.
Returns
mixed The result of the set maximum length operation.
Definition at line 473 of file class.winbinder.php.
    {
        return $this->callWinBinder( 'wb_send_message', array($wbobject, 0x00c5, $length, 0) );
    }
References callWinBinder().
Referenced by createInputText().
setProgressBarMax()
WinBinder::setProgressBarMax ($progressBar, $max)
Sets the maximum value of a progress bar.
Parameters
array $progressBar The progress bar control.
int $max The maximum value to set.
Definition at line 890 of file class.winbinder.php.
    {
        $this->setRange( $progressBar[self::CTRL_OBJ], 0, $max );
    }
References setRange().
setProgressBarValue()
WinBinder::setProgressBarValue ($progressBar, $value)
Sets the value of a progress bar.
Parameters
array $progressBar The progress bar control.
mixed $value The value to set.
Definition at line 871 of file class.winbinder.php.
    {
        if ( $progressBar != null && isset( $progressBar[self::CTRL_OBJ] ) && isset( $this->gauge[$progressBar[self::CTRL_OBJ]] ) ) {
            if ( strval( $value ) == self::INCR_PROGRESS_BAR ) {
                $value = $this->gauge[$progressBar[self::CTRL_OBJ]] + 1;
            }
            if ( is_numeric( $value ) ) {
                $this->gauge[$progressBar[self::CTRL_OBJ]] = $value;
                $this->setValue( $progressBar[self::CTRL_OBJ], $value );
            }
        }
    }
References CTRL_OBJ, and setValue().
Referenced by incrProgressBar(), and resetProgressBar().
setRange()
WinBinder::setRange ($wbobject, $min, $max)
Sets the range for a WinBinder object.
Parameters
mixed $wbobject The WinBinder object to set the range for.
int $min The minimum value of the range.
int $max The maximum value of the range.
Returns
mixed The result of the set range operation.
Definition at line 638 of file class.winbinder.php.
    {
        return $this->callWinBinder( 'wb_set_range', array($wbobject, $min, $max) );
    }
References callWinBinder().
Referenced by createProgressBar(), and setProgressBarMax().
setStyle()
WinBinder::setStyle ($wbobject, $style)
Sets the style for a WinBinder object.
Parameters
mixed $wbobject The WinBinder object to set the style for.
mixed $style The style to set.
Returns
mixed The result of the set style operation.
Definition at line 624 of file class.winbinder.php.
    {
        return $this->callWinBinder( 'wb_set_style', array($wbobject, $style) );
    }
References callWinBinder().
setText()
WinBinder::setText ($wbobject, $content)
Sets the text for a WinBinder object.
Parameters
mixed $wbobject The WinBinder object to set the text for.
string $content The text content to set.
Returns
mixed The result of the set text operation.
Definition at line 512 of file class.winbinder.php.
    {
        $content = str_replace( self::NEW_LINE, PHP_EOL, $content );
        return $this->callWinBinder( 'wb_set_text', array($wbobject, $content) );
    }
References callWinBinder().
setValue()
WinBinder::setValue ($wbobject, $content)
Sets the value for a WinBinder object.
Parameters
mixed $wbobject The WinBinder object to set the value for.
mixed $content The value to set.
Returns
mixed The result of the set value operation.
Definition at line 539 of file class.winbinder.php.
    {
        return $this->callWinBinder( 'wb_set_value', array($wbobject, $content) );
    }
References callWinBinder().
Referenced by setProgressBarValue().
sysDlgOpen()
WinBinder::sysDlgOpen ($parent, $title, $filter = null, $path = null)
Opens a system dialog to open a file.
Parameters
mixed $parent The parent window for the dialog.
string $title The title of the dialog.
string | null $filter The file filter for the dialog.
string | null $path The initial path for the dialog.
Returns
mixed The selected file path.
Definition at line 667 of file class.winbinder.php.
    {
        return $this->callWinBinder( 'wb_sys_dlg_open', array($parent, $title, $filter, $path) );
    }
References callWinBinder().
sysDlgPath()
WinBinder::sysDlgPath ($parent, $title, $path = null)
Opens a system dialog to select a path.
Parameters
mixed $parent The parent window for the dialog.
string $title The title of the dialog.
string | null $path The initial path for the dialog.
Returns
mixed The selected path.
Definition at line 652 of file class.winbinder.php.
    {
        return $this->callWinBinder( 'wb_sys_dlg_path', array($parent, $title, $path) );
    }
References callWinBinder().
wait()
WinBinder::wait ($wbobject = null)
Waits for an event on a WinBinder object.
Parameters
mixed $wbobject The WinBinder object to wait on.
Returns
mixed The result of the wait operation.
Definition at line 356 of file class.winbinder.php.
    {
        return $this->callWinBinder( 'wb_wait', array($wbobject), true );
    }
References callWinBinder().
writeLog()
static WinBinder::writeLog ($log) static private
Writes a log message to the WinBinder log file.
Parameters
string $log The log message to write.
Definition at line 83 of file class.winbinder.php.
    {
        global $bearsamppRoot;
        Util::logDebug( $log, $bearsamppRoot->getWinbinderLogFilePath() );
    }
References $bearsamppRoot, and Util\logDebug().
Referenced by exec(), and findFile().
Field Documentation
$callback
WinBinder::$callback
Definition at line 61 of file class.winbinder.php.
$countCtrls
WinBinder::$countCtrls private
Definition at line 59 of file class.winbinder.php.
$defaultTitle
WinBinder::$defaultTitle private
Definition at line 58 of file class.winbinder.php.
$gauge
WinBinder::$gauge
Definition at line 62 of file class.winbinder.php.
BOX_ERROR
const WinBinder::BOX_ERROR = WBC_STOP
Definition at line 32 of file class.winbinder.php.
BOX_INFO
const WinBinder::BOX_INFO = WBC_INFO
Definition at line 28 of file class.winbinder.php.
BOX_OK
const WinBinder::BOX_OK = WBC_OK
Definition at line 29 of file class.winbinder.php.
BOX_OKCANCEL
const WinBinder::BOX_OKCANCEL = WBC_OKCANCEL
Definition at line 30 of file class.winbinder.php.
BOX_QUESTION
const WinBinder::BOX_QUESTION = WBC_QUESTION
Definition at line 31 of file class.winbinder.php.
BOX_WARNING
const WinBinder::BOX_WARNING = WBC_WARNING
Definition at line 33 of file class.winbinder.php.
BOX_YESNO
const WinBinder::BOX_YESNO = WBC_YESNO
Definition at line 34 of file class.winbinder.php.
BOX_YESNOCANCEL
const WinBinder::BOX_YESNOCANCEL = WBC_YESNOCANCEL
Definition at line 35 of file class.winbinder.php.
CTRL_ID
const WinBinder::CTRL_ID = 0
Definition at line 20 of file class.winbinder.php.
Referenced by ActionAbout\processWindow(), ActionAddAlias\processWindow(), ActionAddVhost\processWindow(), ActionChangeBrowser\processWindow(), ActionChangeDbRootPwd\processWindow(), ActionChangePort\processWindow(), ActionCheckVersion\processWindow(), ActionEditAlias\processWindow(), ActionEditVhost\processWindow(), and ActionGenSslCertificate\processWindow().
CTRL_OBJ
const WinBinder::CTRL_OBJ = 1
Definition at line 21 of file class.winbinder.php.
Referenced by ActionChangeBrowser\__construct(), ActionChangeDbRootPwd\__construct(), ActionChangePort\__construct(), createProgressBar(), ActionAddAlias\processWindow(), ActionAddVhost\processWindow(), ActionChangeBrowser\processWindow(), ActionChangeDbRootPwd\processWindow(), ActionChangePort\processWindow(), ActionEditAlias\processWindow(), ActionEditVhost\processWindow(), ActionGenSslCertificate\processWindow(), and setProgressBarValue().
CURSOR_ARROW
const WinBinder::CURSOR_ARROW = 'arrow'
Definition at line 38 of file class.winbinder.php.
CURSOR_CROSS
const WinBinder::CURSOR_CROSS = 'cross'
Definition at line 39 of file class.winbinder.php.
CURSOR_FINGER
const WinBinder::CURSOR_FINGER = 'finger'
Definition at line 40 of file class.winbinder.php.
CURSOR_FORBIDDEN
const WinBinder::CURSOR_FORBIDDEN = 'forbidden'
Definition at line 41 of file class.winbinder.php.
CURSOR_HELP
const WinBinder::CURSOR_HELP = 'help'
Definition at line 42 of file class.winbinder.php.
CURSOR_IBEAM
const WinBinder::CURSOR_IBEAM = 'ibeam'
Definition at line 43 of file class.winbinder.php.
CURSOR_NONE
const WinBinder::CURSOR_NONE = null
Definition at line 44 of file class.winbinder.php.
CURSOR_SIZEALL
const WinBinder::CURSOR_SIZEALL = 'sizeall'
Definition at line 45 of file class.winbinder.php.
CURSOR_SIZENESW
const WinBinder::CURSOR_SIZENESW = 'sizenesw'
Definition at line 46 of file class.winbinder.php.
CURSOR_SIZENS
const WinBinder::CURSOR_SIZENS = 'sizens'
Definition at line 47 of file class.winbinder.php.
CURSOR_SIZENWSE
const WinBinder::CURSOR_SIZENWSE = 'sizenwse'
Definition at line 48 of file class.winbinder.php.
CURSOR_SIZEWE
const WinBinder::CURSOR_SIZEWE = 'sizewe'
Definition at line 49 of file class.winbinder.php.
CURSOR_UPARROW
const WinBinder::CURSOR_UPARROW = 'uparrow'
Definition at line 50 of file class.winbinder.php.
CURSOR_WAIT
const WinBinder::CURSOR_WAIT = 'wait'
Definition at line 51 of file class.winbinder.php.
CURSOR_WAITARROW
const WinBinder::CURSOR_WAITARROW = 'waitarrow'
Definition at line 52 of file class.winbinder.php.
INCR_PROGRESS_BAR
const WinBinder::INCR_PROGRESS_BAR = '++'
Definition at line 24 of file class.winbinder.php.
NEW_LINE
const WinBinder::NEW_LINE = '@nl@'
Definition at line 25 of file class.winbinder.php.
SYSINFO_SCREENAREA
const WinBinder::SYSINFO_SCREENAREA = 'screenarea'
Definition at line 55 of file class.winbinder.php.
SYSINFO_WORKAREA
const WinBinder::SYSINFO_WORKAREA = 'workarea'
Definition at line 56 of file class.winbinder.php.
Referenced by ActionLoading\__construct(), and Splash\init().
The documentation for this class was generated from the following file:
E:/Bearsampp-development/sandbox/core/classes/class.winbinder.php