Bearsampp: Bins Class Reference
Bins Class Reference
Public Member Functions
__construct ()
getAll ()
getApache ()
getFilezilla ()
getLogsPath ()
getMailhog ()
getMailpit ()
getMariadb ()
getMemcached ()
getMysql ()
getNodejs ()
getPhp ()
getPostgresql ()
getServices ()
getXlight ()
reload ()
update ()
Data Fields
const TYPE = 'bins'
Private Attributes
$apache
$filezilla
$mailhog
$mailpit
$mariadb
$memcached
$mysql
$nodejs
$php
$postgresql
$xlight
Detailed Description
Definition at line 10 of file class.bins.php.
Constructor & Destructor Documentation
__construct()
Bins::__construct ()
Constructor for the Bins class. Initializes the Bins object and logs the initialization.
Definition at line 30 of file class.bins.php.
    {
        Util::logInitClass($this);
    }
References Util\logInitClass().
Member Function Documentation
getAll()
Bins::getAll ()
Retrieves all bin modules.
Returns
array An array of all bin modules.
Definition at line 64 of file class.bins.php.
    {
        return array(
            $this->getMailhog(),
            $this->getMailpit(),
            $this->getMemcached(),
            $this->getApache(),
            $this->getFilezilla(),
            $this->getMariadb(),
            $this->getPostgresql(),
            $this->getMysql(),
            $this->getPhp(),
            $this->getNodejs(),
            $this->getXlight(),
        );
    }
References getApache(), getFilezilla(), getMailhog(), getMailpit(), getMariadb(), getMemcached(), getMysql(), getNodejs(), getPhp(), getPostgresql(), and getXlight().
Referenced by reload(), and update().
getApache()
Bins::getApache ()
Retrieves the Apache bin module. If the Apache module is not initialized, it creates a new instance.
Returns
BinApache The Apache bin module.
Definition at line 129 of file class.bins.php.
    {
        if ($this->apache == null) {
            $this->apache = new BinApache('apache', self::TYPE);
        }
        return $this->apache;
    }
References $apache.
Referenced by getAll(), and getServices().
getFilezilla()
Bins::getFilezilla ()
Retrieves the FileZilla bin module. If the FileZilla module is not initialized, it creates a new instance.
Returns
BinFilezilla The FileZilla bin module.
Definition at line 213 of file class.bins.php.
    {
        if ($this->filezilla == null) {
            $this->filezilla = new BinFilezilla('filezilla', self::TYPE);
        }
        return $this->filezilla;
    }
References $filezilla.
Referenced by getAll(), getLogsPath(), and getServices().
getLogsPath()
Bins::getLogsPath ()
Retrieves the log paths for all bin modules.
Returns
array An array of log paths for all bin modules.
Definition at line 240 of file class.bins.php.
    {
        return array(
            $this->getFilezilla()->getLogsPath(),
        );
    }
References getFilezilla(), and getLogsPath().
Referenced by getLogsPath().
getMailhog()
Bins::getMailhog ()
Retrieves the Mailhog bin module. If the Mailhog module is not initialized, it creates a new instance.
Returns
BinMailhog The Mailhog bin module.
Definition at line 87 of file class.bins.php.
    {
        if ($this->mailhog == null) {
            $this->mailhog = new BinMailhog('mailhog', self::TYPE);
        }
        return $this->mailhog;
    }
References $mailhog.
Referenced by getAll(), and getServices().
getMailpit()
Bins::getMailpit ()
Retrieves the Mailpit bin module. If the Mailpit module is not initialized, it creates a new instance.
Returns
BinMailpit The Mailpit bin module.
Definition at line 101 of file class.bins.php.
    {
        if ($this->mailpit == null) {
            $this->mailpit = new BinMailpit('mailpit', self::TYPE);
        }
        return $this->mailpit;
    }
References $mailpit.
Referenced by getAll(), and getServices().
getMariadb()
Bins::getMariadb ()
Retrieves the MariaDB bin module. If the MariaDB module is not initialized, it creates a new instance.
Returns
BinMariadb The MariaDB bin module.
Definition at line 171 of file class.bins.php.
    {
        if ($this->mariadb == null) {
            $this->mariadb = new BinMariadb('mariadb', self::TYPE);
        }
        return $this->mariadb;
    }
References $mariadb.
Referenced by getAll(), and getServices().
getMemcached()
Bins::getMemcached ()
Retrieves the Memcached bin module. If the Memcached module is not initialized, it creates a new instance.
Returns
BinMemcached The Memcached bin module.
Definition at line 115 of file class.bins.php.
    {
        if ($this->memcached == null) {
            $this->memcached = new BinMemcached('memcached', self::TYPE);
        }
        return $this->memcached;
    }
References $memcached.
Referenced by getAll(), and getServices().
getMysql()
Bins::getMysql ()
Retrieves the MySQL bin module. If the MySQL module is not initialized, it creates a new instance.
Returns
BinMysql The MySQL bin module.
Definition at line 157 of file class.bins.php.
    {
        if ($this->mysql == null) {
            $this->mysql = new BinMysql('mysql', self::TYPE);
        }
        return $this->mysql;
    }
References $mysql.
Referenced by getAll(), and getServices().
getNodejs()
Bins::getNodejs ()
Retrieves the Node.js bin module. If the Node.js module is not initialized, it creates a new instance.
Returns
BinNodejs The Node.js bin module.
Definition at line 199 of file class.bins.php.
    {
        if ($this->nodejs == null) {
            $this->nodejs = new BinNodejs('nodejs', self::TYPE);
        }
        return $this->nodejs;
    }
References $nodejs.
Referenced by getAll().
getPhp()
Bins::getPhp ()
Retrieves the PHP bin module. If the PHP module is not initialized, it creates a new instance.
Returns
BinPhp The PHP bin module.
Definition at line 143 of file class.bins.php.
    {
        if ($this->php == null) {
            $this->php = new BinPhp('php', self::TYPE);
        }
        return $this->php;
    }
References $php.
Referenced by getAll().
getPostgresql()
Bins::getPostgresql ()
Retrieves the PostgreSQL bin module. If the PostgreSQL module is not initialized, it creates a new instance.
Returns
BinPostgresql The PostgreSQL bin module.
Definition at line 185 of file class.bins.php.
    {
        if ($this->postgresql == null) {
            $this->postgresql = new BinPostgresql('postgresql', self::TYPE);
        }
        return $this->postgresql;
    }
References $postgresql.
Referenced by getAll(), and getServices().
getServices()
Bins::getServices ()
Retrieves the services for all enabled bin modules.
Returns
array An associative array of service names and their corresponding service objects.
Definition at line 252 of file class.bins.php.
    {
        $result = array();
        if ($this->getMailhog()->isEnable()) {
            $result[BinMailhog::SERVICE_NAME] = $this->getMailhog()->getService();
        }
        if ($this->getMailpit()->isEnable()) {
            $result[BinMailpit::SERVICE_NAME] = $this->getMailpit()->getService();
        }
        if ($this->getMemcached()->isEnable()) {
            $result[BinMemcached::SERVICE_NAME] = $this->getMemcached()->getService();
        }
        if ($this->getApache()->isEnable()) {
            $result[BinApache::SERVICE_NAME] = $this->getApache()->getService();
        }
        if ($this->getMysql()->isEnable()) {
            $result[BinMysql::SERVICE_NAME] = $this->getMysql()->getService();
        }
        if ($this->getMariadb()->isEnable()) {
            $result[BinMariadb::SERVICE_NAME] = $this->getMariadb()->getService();
        }
        if ($this->getPostgresql()->isEnable()) {
            $result[BinPostgresql::SERVICE_NAME] = $this->getPostgresql()->getService();
        }
        if ($this->getFilezilla()->isEnable()) {
            $result[BinFilezilla::SERVICE_NAME] = $this->getFilezilla()->getService();
        }
        if ($this->getXlight()->isEnable()) {
            $result[BinXlight::SERVICE_NAME] = $this->getXlight()->getService();
        }
        return $result;
    }
References $result, getApache(), getFilezilla(), getMailhog(), getMailpit(), getMariadb(), getMemcached(), getMysql(), getPostgresql(), getXlight(), BinApache\SERVICE_NAME, BinFilezilla\SERVICE_NAME, BinMailhog\SERVICE_NAME, BinMailpit\SERVICE_NAME, BinMariadb\SERVICE_NAME, BinMemcached\SERVICE_NAME, BinMysql\SERVICE_NAME, BinPostgresql\SERVICE_NAME, and BinXlight\SERVICE_NAME.
getXlight()
Bins::getXlight ()
Retrieves the Xlight bin module. If the Xlight module is not initialized, it creates a new instance.
Returns
BinXlight The Xlight bin module.
Definition at line 227 of file class.bins.php.
    {
        if ($this->xlight == null) {
            $this->xlight = new BinXlight('xlight', self::TYPE);
        }
        return $this->xlight;
    }
References $xlight.
Referenced by getAll(), and getServices().
reload()
Bins::reload ()
Reloads the configuration for all bin modules. Logs the reload action and calls the reload method on each bin module.
Definition at line 39 of file class.bins.php.
    {
        Util::logInfo('Reload bins');
        foreach ($this->getAll() as $bin) {
            $bin->reload();
        }
    }
References getAll(), and Util\logInfo().
update()
Bins::update ()
Updates the configuration for all bin modules. Logs the update action and calls the update method on each bin module.
Definition at line 51 of file class.bins.php.
    {
        Util::logInfo('Update bins config');
        foreach ($this->getAll() as $bin) {
            $bin->update();
        }
    }
References getAll(), and Util\logInfo().
Field Documentation
$apache
Bins::$apache private
Definition at line 17 of file class.bins.php.
Referenced by getApache().
$filezilla
Bins::$filezilla private
Definition at line 23 of file class.bins.php.
Referenced by getFilezilla().
$mailhog
Bins::$mailhog private
Definition at line 14 of file class.bins.php.
Referenced by getMailhog().
$mailpit
Bins::$mailpit private
Definition at line 15 of file class.bins.php.
Referenced by getMailpit().
$mariadb
Bins::$mariadb private
Definition at line 20 of file class.bins.php.
Referenced by getMariadb().
$memcached
Bins::$memcached private
Definition at line 16 of file class.bins.php.
Referenced by getMemcached().
$mysql
Bins::$mysql private
Definition at line 19 of file class.bins.php.
Referenced by getMysql().
$nodejs
Bins::$nodejs private
Definition at line 22 of file class.bins.php.
Referenced by getNodejs().
$php
Bins::$php private
Definition at line 18 of file class.bins.php.
Referenced by getPhp().
$postgresql
Bins::$postgresql private
Definition at line 21 of file class.bins.php.
Referenced by getPostgresql().
$xlight
Bins::$xlight private
Definition at line 24 of file class.bins.php.
Referenced by getXlight().
TYPE
const Bins::TYPE = 'bins'
Definition at line 12 of file class.bins.php.
Referenced by Module\reload().
The documentation for this class was generated from the following file:
E:/Bearsampp-development/sandbox/core/classes/bins/class.bins.php