Bearsampp: Win32Ps Class Reference
Win32Ps Class Reference
Public Member Functions
__construct ()
Static Public Member Functions
static exists ($pid)
static findByPath ($path)
static findByPid ($pid)
static getCurrentPid ()
static getKeys ()
static getListProcs ()
static getStatProc ()
static kill ($pid)
static killBins ($refreshProcs=false)
Data Fields
const CAPTION = 'Caption'
const COMMAND_LINE = 'CommandLine'
const EXECUTABLE_PATH = 'ExecutablePath'
const NAME = 'Name'
const PROCESS_ID = 'ProcessID'
Static Private Member Functions
static callWin32Ps ($function)
Detailed Description
Class Win32Ps
This class provides various utility functions for interacting with Windows processes. It includes methods for retrieving process information, checking process existence, finding processes by PID or path, and terminating processes.
Definition at line 17 of file class.win32ps.php.
Constructor & Destructor Documentation
__construct()
Win32Ps::__construct ()
Definition at line 25 of file class.win32ps.php.
    {
    }
Member Function Documentation
callWin32Ps()
static Win32Ps::callWin32Ps ($function) static private
Calls a specified function if it exists.
Parameters
string $function The name of the function to call.
Returns
mixed The result of the function call, or false if the function does not exist.
Definition at line 35 of file class.win32ps.php.
    {
        $result = false;
        if (function_exists($function)) {
            $result = @call_user_func($function);
        }
        return $result;
    }
References $result.
Referenced by getStatProc().
exists()
static Win32Ps::exists ($pid) static
Checks if a process with the specified PID exists.
Parameters
int $pid The process ID to check.
Returns
bool True if the process exists, false otherwise.
Definition at line 108 of file class.win32ps.php.
    {
        return self::findByPid($pid) !== false;
    }
References findByPid().
findByPath()
static Win32Ps::findByPath ($path) static
Finds a process by its executable path.
Parameters
string $path The path to the executable.
Returns
array|false An array of process information, or false if not found.
Definition at line 141 of file class.win32ps.php.
    {
        $path = Util::formatUnixPath($path);
        if (!empty($path) && is_file($path)) {
            $procs = self::getListProcs();
            if ($procs !== false) {
                foreach ($procs as $proc) {
                    $unixExePath = Util::formatUnixPath($proc[self::EXECUTABLE_PATH]);
                    if ($unixExePath == $path) {
                        return $proc;
                    }
                }
            }
        }
        return false;
    }
References $proc, $procs, Util\formatUnixPath(), and getListProcs().
findByPid()
static Win32Ps::findByPid ($pid) static
Finds a process by its PID.
Parameters
int $pid The process ID to find.
Returns
array|false An array of process information, or false if not found.
Definition at line 119 of file class.win32ps.php.
    {
        if (!empty($pid)) {
            $procs = self::getListProcs();
            if ($procs !== false) {
                foreach ($procs as $proc) {
                    if ($proc[self::PROCESS_ID] == $pid) {
                        return $proc;
                    }
                }
            }
        }
        return false;
    }
References $proc, $procs, and getListProcs().
Referenced by exists().
getCurrentPid()
static Win32Ps::getCurrentPid () static
Retrieves the current process ID.
Returns
int The current process ID, or 0 if not found.
Definition at line 67 of file class.win32ps.php.
    {
        $procInfo = self::getStatProc();
        return isset($procInfo[self::PROCESS_ID]) ? intval($procInfo[self::PROCESS_ID]) : 0;
    }
References getStatProc().
Referenced by ActionLoading\__construct(), and ActionLoading\processLoading().
getKeys()
static Win32Ps::getKeys () static
Retrieves the keys used for process information.
Returns
array An array of keys used for process information.
Definition at line 51 of file class.win32ps.php.
    {
        return array(
            self::NAME,
            self::PROCESS_ID,
            self::EXECUTABLE_PATH,
            self::CAPTION,
            self::COMMAND_LINE
        );
    }
getListProcs()
static Win32Ps::getListProcs () static
Retrieves a list of running processes.
Returns
array|false An array of process information, or false on failure.
Definition at line 78 of file class.win32ps.php.
    {
        return Vbs::getListProcs(self::getKeys());
    }
References Vbs\getListProcs().
Referenced by findByPath(), findByPid(), killBins(), and Root\register().
getStatProc()
static Win32Ps::getStatProc () static
Retrieves the status of the current process.
Returns
array|null An array containing the process ID and executable path, or null on failure.
Definition at line 88 of file class.win32ps.php.
    {
        $statProc = self::callWin32Ps('win32_ps_stat_proc');
        if ($statProc !== false) {
            return array(
                self::PROCESS_ID => $statProc['pid'],
                self::EXECUTABLE_PATH => $statProc['exe']
            );
        }
        return null;
    }
References callWin32Ps().
Referenced by getCurrentPid().
kill()
static Win32Ps::kill ($pid) static
Terminates a process by its PID.
Parameters
int $pid The process ID to terminate.
Definition at line 164 of file class.win32ps.php.
    {
        $pid = intval($pid);
        if (!empty($pid)) {
            Vbs::killProc($pid);
        }
    }
References Vbs\killProc().
Referenced by killBins(), ActionLoading\processLoading(), and Util\stopLoading().
killBins()
static Win32Ps::killBins ($refreshProcs = false) static
Terminates all Bearsampp-related processes except the current one.
Parameters
bool $refreshProcs Whether to refresh the list of processes before terminating.
Returns
array An array of terminated processes.
Definition at line 178 of file class.win32ps.php.
    {
        global $bearsamppRoot;
        $killed = array();
        $procs = $bearsamppRoot->getProcs();
        if ($refreshProcs) {
            $procs = self::getListProcs();
        }
        if ($procs !== false) {
            foreach ($procs as $proc) {
                $unixExePath = Util::formatUnixPath($proc[self::EXECUTABLE_PATH]);
                $unixCommandPath = Util::formatUnixPath($proc[self::COMMAND_LINE]);
                // Not kill current PID (PHP)
                if ($proc[self::PROCESS_ID] == self::getCurrentPid()) {
                    continue;
                }
                // Not kill bearsampp
                if ($unixExePath == $bearsamppRoot->getExeFilePath()) {
                    continue;
                }
                // Not kill inside www
                if (Util::startWith($unixExePath, $bearsamppRoot->getWwwPath() . '/') || Util::contains($unixCommandPath, $bearsamppRoot->getWwwPath() . '/')) {
                    continue;
                }
                // Not kill external process
                if (!Util::startWith($unixExePath, $bearsamppRoot->getRootPath() . '/') && !Util::contains($unixCommandPath, $bearsamppRoot->getRootPath() . '/')) {
                    continue;
                }
                self::kill($proc[self::PROCESS_ID]);
                $killed[] = $proc;
            }
        }
        return $killed;
    }
References $bearsamppRoot, $proc, $procs, Util\contains(), Util\formatUnixPath(), getListProcs(), kill(), and Util\startWith().
Referenced by ActionManualRestart\__construct(), Batch\exitApp(), ActionStartup\killOldInstances(), ActionQuit\processWindow(), and ActionExt\procReload().
Field Documentation
CAPTION
const Win32Ps::CAPTION = 'Caption'
Definition at line 22 of file class.win32ps.php.
COMMAND_LINE
const Win32Ps::COMMAND_LINE = 'CommandLine'
Definition at line 23 of file class.win32ps.php.
EXECUTABLE_PATH
const Win32Ps::EXECUTABLE_PATH = 'ExecutablePath'
Definition at line 21 of file class.win32ps.php.
Referenced by Vbs\getListProcs(), ActionStartup\killOldInstances(), and ActionStartup\processWindow().
NAME
const Win32Ps::NAME = 'Name'
Definition at line 19 of file class.win32ps.php.
PROCESS_ID
const Win32Ps::PROCESS_ID = 'ProcessID'
Definition at line 20 of file class.win32ps.php.
Referenced by ActionStartup\killOldInstances(), and ActionStartup\processWindow().
The documentation for this class was generated from the following file:
E:/Bearsampp-development/sandbox/core/classes/class.win32ps.php