My Project: BinMemcached Class Reference
BinMemcached Class Reference
Public Member Functions
__construct ($id, $type)
changePort ($port, $checkUsed=false, $wbProgressBar=null)
checkPort ($port, $showWindow=false)
getExe ()
getLog ()
getMemory ()
getPort ()
getService ()
rebuildConf ()
reload ($id=null, $type=null)
setEnable ($enabled, $showWindow=false)
setMemory ($memory)
setPort ($port)
setVersion ($version)
switchVersion ($version, $showWindow=false)
Public Member Functions inherited from Module
__toString ()
getCurrentPath ()
getId ()
getName ()
getRelease ()
getRootPath ()
getSymlinkPath ()
getType ()
getVersion ()
getVersionList ()
isEnable ()
update ($sub=0, $showWindow=false)
Data Fields
const LOCAL_CFG_EXE = 'memcachedExe'
const LOCAL_CFG_MEMORY = 'memcachedMemory'
const LOCAL_CFG_PORT = 'memcachedPort'
const ROOT_CFG_ENABLE = 'memcachedEnable'
const ROOT_CFG_VERSION = 'memcachedVersion'
const SERVICE_NAME = 'bearsamppmemcached'
const SERVICE_PARAMS = '-m %d -p %d -U 0 -vv'
Data Fields inherited from Module
const BUNDLE_RELEASE = 'bundleRelease'
Protected Member Functions
replaceAll ($params)
updateConfig ($version=null, $sub=0, $showWindow=false)
Protected Member Functions inherited from Module
__construct ()
replace ($key, $value)
Private Attributes
$exe
$log
$memory
$port
$service
Additional Inherited Members
Protected Attributes inherited from Module
$bearsamppConf
$bearsamppConfRaw
$currentPath
$enable
$name
$release = 'N/A'
$rootPath
$symlinkPath
$version
Detailed Description
Class BinMemcached
This class represents the Memcached service module in the Bearsampp application. It handles the configuration, initialization, and management of the Memcached service.
Definition at line 16 of file class.bin.memcached.php.
Constructor & Destructor Documentation
__construct()
BinMemcached::__construct ($id, $type)
Constructs a BinMemcached object and initializes the Memcached service.
Parameters
string $id The ID of the module.
string $type The type of the module.
Definition at line 41 of file class.bin.memcached.php.
{
        Util::logInitClass($this);
        $this->reload($id, $type);
    }
References Module\$id, Module\$type, Util\logInitClass(), and reload().
Member Function Documentation
changePort()
BinMemcached::changePort ($port, $checkUsed = false, $wbProgressBar = null)
Changes the port for the Memcached service.
Parameters
int $port The new port number.
bool $checkUsed Whether to check if the port is already in use.
mixed $wbProgressBar The progress bar object for UI updates.
Returns
bool|int True if the port was successfully changed, false if the port is invalid, or the process using the port.
Definition at line 167 of file class.bin.memcached.php.
{
        global $bearsamppWinbinder;
        if (!Util::isValidPort($port)) {
            Util::logError($this->getName() . ' port not valid: ' . $port);
            return false;
        }
        $port = intval($port);
        $bearsamppWinbinder->incrProgressBar($wbProgressBar);
        $isPortInUse = Util::isPortInUse($port);
        if (!$checkUsed || $isPortInUse === false) {
            // bearsampp.conf
            $this->setPort($port);
            $bearsamppWinbinder->incrProgressBar($wbProgressBar);
            // conf
            $this->update();
            $bearsamppWinbinder->incrProgressBar($wbProgressBar);
            return true;
        }
        Util::logDebug($this->getName() . ' port in used: ' . $port . ' - ' . $isPortInUse);
        return $isPortInUse;
    }
References $port, Module\getName(), Util\isPortInUse(), Util\isValidPort(), Util\logDebug(), Util\logError(), setPort(), and Module\update().
checkPort()
BinMemcached::checkPort ($port, $showWindow = false)
Checks if the specified port is in use by the Memcached service.
Parameters
int $port The port number to check.
bool $showWindow Whether to show a message box with the result.
Returns
bool True if the port is in use by Memcached, false otherwise.
Definition at line 202 of file class.bin.memcached.php.
{
        global $bearsamppLang, $bearsamppWinbinder;
        $boxTitle = sprintf($bearsamppLang->getValue(Lang::CHECK_PORT_TITLE), $this->getName(), $port);
        if (!Util::isValidPort($port)) {
            Util::logError($this->getName() . ' port not valid: ' . $port);
            return false;
        }
        if (function_exists('memcache_connect')) {
            $memcache = @memcache_connect('127.0.0.1', $port);
            if ($memcache) {
                $memcacheVersion = memcache_get_version($memcache);
                Util::logDebug($this->getName() . ' port ' . $port . ' is used by: ' . $this->getName() . ' ' . $memcacheVersion);
                memcache_close($memcache);
                if ($showWindow) {
                    $bearsamppWinbinder->messageBoxInfo(
                        sprintf($bearsamppLang->getValue(Lang::PORT_USED_BY), $port, $this->getName() . ' ' . $memcacheVersion),
                        $boxTitle
                    );
                }
                return true;
            }
        } else {
            $fp = @fsockopen('127.0.0.1', $port, $errno, $errstr, 3);
            if (!$fp) {
                Util::logDebug($this->getName() . ' port ' . $port . ' is used by another application');
                if ($showWindow) {
                    $bearsamppWinbinder->messageBoxWarning(
                        sprintf($bearsamppLang->getValue(Lang::PORT_NOT_USED_BY), $port),
                        $boxTitle
                    );
                }
            } else {
                Util::logDebug($this->getName() . ' port ' . $port . ' is not used');
                if ($showWindow) {
                    $bearsamppWinbinder->messageBoxError(
                        sprintf($bearsamppLang->getValue(Lang::PORT_NOT_USED), $port),
                        $boxTitle
                    );
                }
                fclose($fp);
            }
        }
        return false;
    }
References $bearsamppLang, $port, Lang\CHECK_PORT_TITLE, Module\getName(), Util\isValidPort(), Util\logDebug(), Util\logError(), Lang\PORT_NOT_USED, Lang\PORT_NOT_USED_BY, and Lang\PORT_USED_BY.
getExe()
BinMemcached::getExe ()
Retrieves the executable file path for the Memcached service.
Returns
string The executable file path.
Definition at line 379 of file class.bin.memcached.php.
{
        return $this->exe;
    }
References $exe.
getLog()
BinMemcached::getLog ()
Retrieves the log file path for the Memcached service.
Returns
string The log file path.
Definition at line 370 of file class.bin.memcached.php.
{
        return $this->log;
    }
References $log.
getMemory()
BinMemcached::getMemory ()
Retrieves the memory allocation for the Memcached service.
Returns
int The memory allocation in MB.
Definition at line 388 of file class.bin.memcached.php.
{
        return $this->memory;
    }
References $memory.
getPort()
BinMemcached::getPort ()
Retrieves the port number for the Memcached service.
Returns
int The port number.
Definition at line 406 of file class.bin.memcached.php.
{
        return $this->port;
    }
References $port.
getService()
BinMemcached::getService ()
Retrieves the service object for the Memcached service.
Returns
Win32Service The service object.
Definition at line 329 of file class.bin.memcached.php.
{
        return $this->service;
    }
References $service.
rebuildConf()
BinMemcached::rebuildConf ()
Rebuilds the configuration for the Memcached service in the Windows Registry.
Returns
bool True if the configuration was successfully rebuilt, false otherwise.
Definition at line 139 of file class.bin.memcached.php.
{
        global $bearsamppRegistry;
        $exists = $bearsamppRegistry->exists(
            Registry::HKEY_LOCAL_MACHINE,
            'SYSTEM\CurrentControlSet\Services\\' . self::SERVICE_NAME . '\Parameters',
            Nssm::INFO_APP_PARAMETERS
        );
        if ($exists) {
            return $bearsamppRegistry->setExpandStringValue(
                Registry::HKEY_LOCAL_MACHINE,
                'SYSTEM\CurrentControlSet\Services\\' . self::SERVICE_NAME . '\Parameters',
                Nssm::INFO_APP_PARAMETERS,
                sprintf(self::SERVICE_PARAMS, $this->memory, $this->port)
            );
        }
        return false;
    }
References Registry\HKEY_LOCAL_MACHINE, and Nssm\INFO_APP_PARAMETERS.
reload()
BinMemcached::reload ($id = null, $type = null)
Reloads the configuration and settings for the Memcached service.
Parameters
string | null $id The ID of the module. If null, the current ID is used.
string | null $type The type of the module. If null, the current type is used.
Reimplemented from Module.
Definition at line 52 of file class.bin.memcached.php.
{
        global $bearsamppRoot, $bearsamppConfig, $bearsamppLang;
        Util::logReloadClass($this);
        $this->name = $bearsamppLang->getValue(Lang::MEMCACHED);
        $this->version = $bearsamppConfig->getRaw(self::ROOT_CFG_VERSION);
        parent::reload($id, $type);
        $this->enable = $this->enable && $bearsamppConfig->getRaw(self::ROOT_CFG_ENABLE);
        $this->service = new Win32Service(self::SERVICE_NAME);
        $this->log = $bearsamppRoot->getLogsPath() . '/memcached.log';
        if ($this->bearsamppConfRaw !== false) {
            $this->exe = $this->symlinkPath . '/' . $this->bearsamppConfRaw[self::LOCAL_CFG_EXE];
            $this->memory = intval($this->bearsamppConfRaw[self::LOCAL_CFG_MEMORY]);
            $this->port = intval($this->bearsamppConfRaw[self::LOCAL_CFG_PORT]);
        }
        if (!$this->enable) {
            Util::logInfo($this->name . ' is not enabled!');
            return;
        }
        if (!is_dir($this->currentPath)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_FILE_NOT_FOUND), $this->name . ' ' . $this->version, $this->currentPath));
            return;
        }
        if (!is_dir($this->symlinkPath)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_FILE_NOT_FOUND), $this->name . ' ' . $this->version, $this->symlinkPath));
            return;
        }
        if (!is_file($this->bearsamppConf)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_CONF_NOT_FOUND), $this->name . ' ' . $this->version, $this->bearsamppConf));
            return;
        }
        if (!is_file($this->exe)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_EXE_NOT_FOUND), $this->name . ' ' . $this->version, $this->exe));
            return;
        }
        if (empty($this->memory)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_INVALID_PARAMETER), self::LOCAL_CFG_MEMORY, $this->memory));
            return;
        }
        if (empty($this->port)) {
            Util::logError(sprintf($bearsamppLang->getValue(Lang::ERROR_INVALID_PARAMETER), self::LOCAL_CFG_PORT, $this->port));
            return;
        }
        $nssm = new Nssm(self::SERVICE_NAME);
        $nssm->setDisplayName(APP_TITLE . ' ' . $this->getName());
        $nssm->setBinPath($this->exe);
        $nssm->setParams(sprintf(self::SERVICE_PARAMS, $this->memory, $this->port));
        $nssm->setStart(Nssm::SERVICE_DEMAND_START);
        $nssm->setStdout($bearsamppRoot->getLogsPath() . '/memcached.out.log');
        $nssm->setStderr($bearsamppRoot->getLogsPath() . '/memcached.err.log');
        $this->service->setNssm($nssm);
    }
References $bearsamppConfig, $bearsamppLang, $bearsamppRoot, Module\$id, Module\$type, APP_TITLE, Lang\ERROR_CONF_NOT_FOUND, Lang\ERROR_EXE_NOT_FOUND, Lang\ERROR_FILE_NOT_FOUND, Lang\ERROR_INVALID_PARAMETER, Module\getName(), LOCAL_CFG_EXE, Util\logError(), Util\logInfo(), Util\logReloadClass(), Lang\MEMCACHED, and Nssm\SERVICE_DEMAND_START.
Referenced by __construct(), setEnable(), and setVersion().
replaceAll()
BinMemcached::replaceAll ($params) protected
Replaces multiple key-value pairs in the configuration file.
Parameters
array $params An associative array of key-value pairs to replace.
Reimplemented from Module.
Definition at line 115 of file class.bin.memcached.php.
{
        $content = file_get_contents($this->bearsamppConf);
        foreach ($params as $key => $value) {
            $content = preg_replace('|' . $key . ' = .*|', $key . ' = ' . '"' . $value.'"', $content);
            $this->bearsamppConfRaw[$key] = $value;
            switch ($key) {
                case self::LOCAL_CFG_MEMORY:
                    $this->memory = intval($value);
                    break;
                case self::LOCAL_CFG_PORT:
                    $this->port = intval($value);
                    break;
            }
        }
        file_put_contents($this->bearsamppConf, $content);
    }
References LOCAL_CFG_MEMORY, and LOCAL_CFG_PORT.
setEnable()
BinMemcached::setEnable ($enabled, $showWindow = false)
Enables or disables the Memcached service.
Parameters
bool $enabled Whether to enable or disable the service.
bool $showWindow Whether to show a message box with the result.
Definition at line 339 of file class.bin.memcached.php.
{
        global $bearsamppConfig, $bearsamppLang, $bearsamppWinbinder;
        if ($enabled == Config::ENABLED && !is_dir($this->currentPath)) {
            Util::logDebug($this->getName() . ' cannot be enabled because bundle ' . $this->getVersion() . ' does not exist in ' . $this->currentPath);
            if ($showWindow) {
                $bearsamppWinbinder->messageBoxError(
                    sprintf($bearsamppLang->getValue(Lang::ENABLE_BUNDLE_NOT_EXIST), $this->getName(), $this->getVersion(), $this->currentPath),
                    sprintf($bearsamppLang->getValue(Lang::ENABLE_TITLE), $this->getName())
                );
            }
            $enabled = Config::DISABLED;
        }
        Util::logInfo($this->getName() . ' switched to ' . ($enabled == Config::ENABLED ? 'enabled' : 'disabled'));
        $this->enable = $enabled == Config::ENABLED;
        $bearsamppConfig->replace(self::ROOT_CFG_ENABLE, $enabled);
        $this->reload();
        if ($this->enable) {
            Util::installService($this, $this->port, null, $showWindow);
        } else {
            Util::removeService($this->service, $this->name);
        }
    }
References $bearsamppConfig, $bearsamppLang, Config\DISABLED, Lang\ENABLE_BUNDLE_NOT_EXIST, Lang\ENABLE_TITLE, Config\ENABLED, Module\getName(), Module\getVersion(), Util\installService(), Util\logDebug(), Util\logInfo(), reload(), and Util\removeService().
setMemory()
BinMemcached::setMemory ($memory)
Sets the memory allocation for the Memcached service.
Parameters
int $memory The memory allocation in MB.
Definition at line 397 of file class.bin.memcached.php.
{
        $this->replace(self::LOCAL_CFG_MEMORY, $memory);
    }
References $memory, and Module\replace().
setPort()
BinMemcached::setPort ($port)
Sets the port number for the Memcached service.
Parameters
int $port The port number.
Definition at line 415 of file class.bin.memcached.php.
{
        $this->replace(self::LOCAL_CFG_PORT, $port);
    }
References $port, and Module\replace().
Referenced by changePort().
setVersion()
BinMemcached::setVersion ($version)
Sets the version of the Memcached service.
Parameters
string $version The version to set.
Reimplemented from Module.
Definition at line 317 of file class.bin.memcached.php.
{
        global $bearsamppConfig;
        $this->version = $version;
        $bearsamppConfig->replace(self::ROOT_CFG_VERSION, $version);
        $this->reload();
    }
References $bearsamppConfig, Module\$version, and reload().
Referenced by updateConfig().
switchVersion()
BinMemcached::switchVersion ($version, $showWindow = false)
Switches the version of the Memcached service.
Parameters
string $version The version to switch to.
bool $showWindow Whether to show a message box with the result.
Returns
bool True if the version was successfully switched, false otherwise.
Definition at line 257 of file class.bin.memcached.php.
{
        Util::logDebug('Switch ' . $this->name . ' version to ' . $version);
        return $this->updateConfig($version, 0, $showWindow);
    }
References Module\$version, Util\logDebug(), and updateConfig().
updateConfig()
BinMemcached::updateConfig ($version = null, $sub = 0, $showWindow = false) protected
Updates the configuration for the Memcached service.
Parameters
string | null $version The version to update to. If null, the current version is used.
int $sub The sub-level for logging indentation.
bool $showWindow Whether to show a message box with the result.
Returns
bool True if the configuration was successfully updated, false otherwise.
Reimplemented from Module.
Definition at line 270 of file class.bin.memcached.php.
{
        global $bearsamppLang, $bearsamppApps, $bearsamppWinbinder;
        if (!$this->enable) {
            return true;
        }
        $version = $version == null ? $this->version : $version;
        Util::logDebug(($sub > 0 ? str_repeat(' ', 2 * $sub) : '') . 'Update ' . $this->name . ' ' . $version . ' config');
        $boxTitle = sprintf($bearsamppLang->getValue(Lang::SWITCH_VERSION_TITLE), $this->getName(), $version);
        $bearsamppConf = str_replace('memcached' . $this->getVersion(), 'memcached' . $version, $this->bearsamppConf);
        if (!file_exists($bearsamppConf)) {
            Util::logError('bearsampp config files not found for ' . $this->getName() . ' ' . $version);
            if ($showWindow) {
                $bearsamppWinbinder->messageBoxError(
                    sprintf($bearsamppLang->getValue(Lang::BEARSAMPP_CONF_NOT_FOUND_ERROR), $this->getName() . ' ' . $version),
                    $boxTitle
                );
            }
            return false;
        }
        $bearsamppConfRaw = parse_ini_file($bearsamppConf);
        if ($bearsamppConfRaw === false || !isset($bearsamppConfRaw[self::ROOT_CFG_VERSION]) || $bearsamppConfRaw[self::ROOT_CFG_VERSION] != $version) {
            Util::logError('bearsampp config file malformed for ' . $this->getName() . ' ' . $version);
            if ($showWindow) {
                $bearsamppWinbinder->messageBoxError(
                    sprintf($bearsamppLang->getValue(Lang::BEARSAMPP_CONF_MALFORMED_ERROR), $this->getName() . ' ' . $version),
                    $boxTitle
                );
            }
            return false;
        }
        // bearsampp.conf
        $this->setVersion($version);
        return true;
    }
References Module\$bearsamppConf, Module\$bearsamppConfRaw, $bearsamppLang, Module\$version, Lang\BEARSAMPP_CONF_MALFORMED_ERROR, Lang\BEARSAMPP_CONF_NOT_FOUND_ERROR, Module\getName(), Module\getVersion(), Util\logDebug(), Util\logError(), setVersion(), and Lang\SWITCH_VERSION_TITLE.
Referenced by switchVersion().
Field Documentation
$exe
BinMemcached::$exe private
Definition at line 31 of file class.bin.memcached.php.
Referenced by getExe().
$log
BinMemcached::$log private
Definition at line 29 of file class.bin.memcached.php.
Referenced by getLog().
$memory
BinMemcached::$memory private
Definition at line 32 of file class.bin.memcached.php.
Referenced by getMemory(), and setMemory().
$port
BinMemcached::$port private
Definition at line 33 of file class.bin.memcached.php.
Referenced by changePort(), checkPort(), getPort(), and setPort().
$service
BinMemcached::$service private
Definition at line 28 of file class.bin.memcached.php.
Referenced by getService().
LOCAL_CFG_EXE
const BinMemcached::LOCAL_CFG_EXE = 'memcachedExe'
Definition at line 24 of file class.bin.memcached.php.
Referenced by reload().
LOCAL_CFG_MEMORY
const BinMemcached::LOCAL_CFG_MEMORY = 'memcachedMemory'
Definition at line 25 of file class.bin.memcached.php.
Referenced by replaceAll().
LOCAL_CFG_PORT
const BinMemcached::LOCAL_CFG_PORT = 'memcachedPort'
Definition at line 26 of file class.bin.memcached.php.
Referenced by replaceAll().
ROOT_CFG_ENABLE
const BinMemcached::ROOT_CFG_ENABLE = 'memcachedEnable'
Definition at line 21 of file class.bin.memcached.php.
ROOT_CFG_VERSION
const BinMemcached::ROOT_CFG_VERSION = 'memcachedVersion'
Definition at line 22 of file class.bin.memcached.php.
SERVICE_NAME
const BinMemcached::SERVICE_NAME = 'bearsamppmemcached'
Definition at line 18 of file class.bin.memcached.php.
Referenced by ActionService\__construct(), TplAppMemcached\getActionInstallMemcachedService(), TplAppMemcached\getActionRemoveMemcachedService(), Bins\getServices(), ActionStartup\installServices(), ActionQuit\processWindow(), and Win32Service\start().
SERVICE_PARAMS
const BinMemcached::SERVICE_PARAMS = '-m %d -p %d -U 0 -vv'
Definition at line 19 of file class.bin.memcached.php.
The documentation for this class was generated from the following file:
E:/Bearsampp-development/sandbox/core/classes/bins/class.bin.memcached.php