Bearsampp: TplAestan Class Reference
TplAestan Class Reference
Static Public Member Functions
static getActionServiceRestart ($service)
static getActionServicesClose ()
static getActionServiceStart ($service)
static getActionServiceStop ($service)
static getGlyphFlah ($lang)
static getItemActionServiceRestart ($service)
static getItemActionServicesClose ()
static getItemActionServiceStart ($service)
static getItemActionServiceStop ($service)
static getItemConsoleZ ($caption, $glyph, $id=null, $title=null, $initDir=null, $command=null)
static getItemExe ($caption, $exe, $glyph, $params=null)
static getItemExplore ($caption, $path)
static getItemLink ($caption, $link, $local=false, $glyph=self::GLYPH_WEB_PAGE)
static getItemNotepad ($caption, $path)
static getItemSeparator ()
static getSectionConfig ()
static getSectionMenuLeftSettings ($caption)
static getSectionMenuRightSettings ()
static getSectionMessages ()
Data Fields
const GLYPH_ABOUT = 21
const GLYPH_ADD = 1
const GLYPH_BROWSER = 5
const GLYPH_CHECK = 13
const GLYPH_COMPOSER = 37
const GLYPH_CONSOLEZ = 0
const GLYPH_DEBUG = 31
const GLYPH_EXIT = 20
const GLYPH_FILE = 6
const GLYPH_FILEZILLA = 47
const GLYPH_FOLDER_CLOSE = 3
const GLYPH_FOLDER_DISABLED = 48
const GLYPH_FOLDER_ENABLED = 49
const GLYPH_FOLDER_OPEN = 2
const GLYPH_GHOSTSCRIPT = 56
const GLYPH_GIT = 26
const GLYPH_HOSTSEDITOR = 39
const GLYPH_IMAGEMAGICK = 41
const GLYPH_LIGHT = 25
const GLYPH_NETWORK = 29
const GLYPH_NGROK = 57
const GLYPH_NODEJS = 28
const GLYPH_NOTEPAD2 = 42
const GLYPH_PASSWORD = 45
const GLYPH_PAUSE = 10
const GLYPH_PEAR = 38
const GLYPH_PERL = 55
const GLYPH_PWGEN = 58
const GLYPH_PYTHON = 50
const GLYPH_PYTHON_CP = 51
const GLYPH_REBUILD_INI = 60
const GLYPH_RED_LIGHT = 36
const GLYPH_RELOAD = 12
const GLYPH_RESTART = 34
const GLYPH_RUBY = 52
const GLYPH_SERVICE_ALL_RUNNING = 16
const GLYPH_SERVICE_INSTALL = 8
const GLYPH_SERVICE_NONE_RUNNING = 18
const GLYPH_SERVICE_REMOVE = 7
const GLYPH_SERVICE_SOME_RUNNING = 17
const GLYPH_SERVICES_RESTART = 22
const GLYPH_SERVICES_START = 24
const GLYPH_SERVICES_STOP = 23
const GLYPH_SSL_CERTIFICATE = 35
const GLYPH_START = 9
const GLYPH_STOP = 11
const GLYPH_TRASHCAN = 32
const GLYPH_UPDATE = 33
const GLYPH_WARNING = 19
const GLYPH_WEB_PAGE = 30
const GLYPH_XLIGHT = 59
const GLYPH_YARN = 54
const IMG_BAR_PICTURE = 'bar.dat'
const IMG_GLYPH_SPRITES = 'sprites.dat'
const SERVICE_RESTART = 'restart'
const SERVICE_START = 'startresume'
const SERVICE_STOP = 'stop'
const SERVICES_CLOSE = 'closeservices'
Static Private Member Functions
static getActionService ($service, $action, $item=false)
Detailed Description
Class TplAestan
This class provides various methods to generate configuration strings for the Bearsampp application. It includes methods to create items for ConsoleZ, links, Notepad, executables, and explorer actions. Additionally, it handles service actions such as start, stop, and restart, and generates configuration sections for messages, config, and menu settings.
Constants:
Glyph constants for various icons used in the application.
Service actions for starting, stopping, and restarting services.
Image files used in the application.
Methods:
getGlyphFlah($lang): Retrieves the glyph flag for a given language.
getItemSeparator(): Returns a string representing a separator item.
getItemConsoleZ($caption, $glyph, $id, $title, $initDir, $command): Returns a string representing a ConsoleZ item.
getItemLink($caption, $link, $local, $glyph): Returns a string representing a link item.
getItemNotepad($caption, $path): Returns a string representing a Notepad item.
getItemExe($caption, $exe, $glyph, $params): Returns a string representing an executable item.
getItemExplore($caption, $path): Returns a string representing an explorer item.
getActionService($service, $action, $item): Returns a string representing a service action.
getActionServiceStart($service): Returns a string representing a service start action.
getItemActionServiceStart($service): Returns a string representing a service start item.
getActionServiceStop($service): Returns a string representing a service stop action.
getItemActionServiceStop($service): Returns a string representing a service stop item.
getActionServiceRestart($service): Returns a string representing a service restart action.
getItemActionServiceRestart($service): Returns a string representing a service restart item.
getActionServicesClose(): Returns a string representing a close services action.
getItemActionServicesClose(): Returns a string representing a close services item.
getSectionMessages(): Returns a string representing the messages section.
getSectionConfig(): Returns a string representing the config section.
getSectionMenuRightSettings(): Returns a string representing the right menu settings section.
getSectionMenuLeftSettings($caption): Returns a string representing the left menu settings section.
Definition at line 45 of file class.tpl.aestan.php.
Member Function Documentation
getActionService()
static TplAestan::getActionService ($service, $action, $item = false) static private
Returns a string representing a service action.
Parameters
string | null $service The service name.
string $action The action to perform.
bool $item Whether to return as an item.
Returns
string The service action string.
Definition at line 255 of file class.tpl.aestan.php.
    {
        global $bearsamppLang;
        $result = 'Action: ' . $action;
        if ($service != null) {
            $result = 'Action: service; ' .
                'Service: ' . $service . '; ' .
                'ServiceAction: ' . $action;
        }
        if ($item) {
            $result = 'Type: item; ' . $result;
            if ($action == self::SERVICE_START) {
                $result .= '; Caption: "' . $bearsamppLang->getValue(Lang::MENU_START_SERVICE) . '"' .
                    '; Glyph: ' . self::GLYPH_START;
            } elseif ($action == self::SERVICE_STOP) {
                $result .= '; Caption: "' . $bearsamppLang->getValue(Lang::MENU_STOP_SERVICE) . '"' .
                    '; Glyph: ' . self::GLYPH_STOP;
            } elseif ($action == self::SERVICE_RESTART) {
                $result .= '; Caption: "' . $bearsamppLang->getValue(Lang::MENU_RESTART_SERVICE) . '"' .
                    '; Glyph: ' . self::GLYPH_RELOAD;
            }
        } elseif ($action != self::SERVICES_CLOSE) {
            $result .= '; Flags: ignoreerrors waituntilterminated';
        }
        return $result;
    }
References $bearsamppLang, $result, GLYPH_RELOAD, GLYPH_START, GLYPH_STOP, Lang\MENU_RESTART_SERVICE, Lang\MENU_START_SERVICE, and Lang\MENU_STOP_SERVICE.
Referenced by getActionServiceRestart(), getActionServicesClose(), getActionServiceStart(), getActionServiceStop(), getItemActionServiceRestart(), getItemActionServicesClose(), getItemActionServiceStart(), and getItemActionServiceStop().
getActionServiceRestart()
static TplAestan::getActionServiceRestart ($service) static
Returns a string representing a service restart action.
Parameters
string $service The service name.
Returns
string The service restart action string.
Definition at line 335 of file class.tpl.aestan.php.
    {
        return self::getActionService($service, self::SERVICE_RESTART, false);
    }
References getActionService().
getActionServicesClose()
static TplAestan::getActionServicesClose () static
Returns a string representing a close services action.
Returns
string The close services action string.
Definition at line 356 of file class.tpl.aestan.php.
    {
        return self::getActionService(null, self::SERVICES_CLOSE, false);
    }
References getActionService().
getActionServiceStart()
static TplAestan::getActionServiceStart ($service) static
Returns a string representing a service start action.
Parameters
string $service The service name.
Returns
string The service start action string.
Definition at line 291 of file class.tpl.aestan.php.
    {
        return self::getActionService($service, self::SERVICE_START, false);
    }
References getActionService().
getActionServiceStop()
static TplAestan::getActionServiceStop ($service) static
Returns a string representing a service stop action.
Parameters
string $service The service name.
Returns
string The service stop action string.
Definition at line 313 of file class.tpl.aestan.php.
    {
        return self::getActionService($service, self::SERVICE_STOP, false);
    }
References getActionService().
getGlyphFlah()
static TplAestan::getGlyphFlah ($lang) static
Retrieves the glyph flag for a given language.
Parameters
string $lang The language code.
Returns
void
Definition at line 117 of file class.tpl.aestan.php.
    {
    }
getItemActionServiceRestart()
static TplAestan::getItemActionServiceRestart ($service) static
Returns a string representing a service restart item.
Parameters
string $service The service name.
Returns
string The service restart item string.
Definition at line 346 of file class.tpl.aestan.php.
    {
        return self::getActionService($service, self::SERVICE_RESTART, true);
    }
References getActionService().
Referenced by TplAppApache\getMenuApacheService(), TplAppFilezilla\getMenuFilezillaService(), TplAppMailhog\getMenuMailhogService(), TplAppMailpit\getMenuMailpitService(), TplAppMariadb\getMenuMariadbService(), TplAppMemcached\getMenuMemcachedService(), TplAppMysql\getMenuMysqlService(), TplAppPostgresql\getMenuPostgresqlService(), and TplAppXlight\getMenuXlightService().
getItemActionServicesClose()
static TplAestan::getItemActionServicesClose () static
Returns a string representing a close services item.
Returns
string The close services item string.
Definition at line 366 of file class.tpl.aestan.php.
    {
        return self::getActionService(null, self::SERVICES_CLOSE, true);
    }
References getActionService().
getItemActionServiceStart()
static TplAestan::getItemActionServiceStart ($service) static
Returns a string representing a service start item.
Parameters
string $service The service name.
Returns
string The service start item string.
Definition at line 302 of file class.tpl.aestan.php.
    {
        return self::getActionService($service, self::SERVICE_STOP, true);
    }
References getActionService().
Referenced by TplAppApache\getMenuApacheService(), TplAppFilezilla\getMenuFilezillaService(), TplAppMailhog\getMenuMailhogService(), TplAppMailpit\getMenuMailpitService(), TplAppMariadb\getMenuMariadbService(), TplAppMemcached\getMenuMemcachedService(), TplAppMysql\getMenuMysqlService(), TplAppPostgresql\getMenuPostgresqlService(), and TplAppXlight\getMenuXlightService().
getItemActionServiceStop()
static TplAestan::getItemActionServiceStop ($service) static
Returns a string representing a service stop item.
Parameters
string $service The service name.
Returns
string The service stop item string.
Definition at line 324 of file class.tpl.aestan.php.
    {
        return self::getActionService($service, self::SERVICE_START, true);
    }
References getActionService().
Referenced by TplAppApache\getMenuApacheService(), TplAppFilezilla\getMenuFilezillaService(), TplAppMailhog\getMenuMailhogService(), TplAppMailpit\getMenuMailpitService(), TplAppMariadb\getMenuMariadbService(), TplAppMemcached\getMenuMemcachedService(), TplAppMysql\getMenuMysqlService(), TplAppPostgresql\getMenuPostgresqlService(), and TplAppXlight\getMenuXlightService().
getItemConsoleZ()
static TplAestan::getItemConsoleZ ($caption, $glyph, $id = null, $title = null, $initDir = null, $command = null) static
Returns a string representing a ConsoleZ item.
Parameters
string $caption The caption for the item.
int $glyph The glyph index.
string | null $id The ID for the item.
string | null $title The title for the item.
string | null $initDir The initial directory for the item.
string | null $command The command to execute.
Returns
string The ConsoleZ item string.
Definition at line 142 of file class.tpl.aestan.php.
    {
        global $bearsamppTools;
        $args = '';
        if ($id != null) {
            $args .= ' -t ""' . $id . '""';
        }
        if ($title != null) {
            $args .= ' -w ""' . $title . '""';
        }
        if ($initDir != null) {
            $args .= ' -d ""' . $initDir . '""';
        }
        if ($command != null) {
            $args .= ' -r ""' . $command . '""';
        }
        return self::getItemExe(
            $caption,
            $bearsamppTools->getConsoleZ()->getExe(),
            $glyph,
            $args
        );
    }
References getItemExe().
Referenced by TplAppGit\getMenuGit(), TplAppGit\getMenuGitRepos(), TplAppMariadb\getMenuMariadb(), TplAppMysql\getMenuMysql(), TplAppNodejs\getMenuNodejs(), TplAppPostgresql\getMenuPostgresql(), TplAppPython\getMenuPython(), and TplAppTools\getMenuTools().
getItemExe()
static TplAestan::getItemExe ($caption, $exe, $glyph, $params = null) static
Returns a string representing an executable item.
Parameters
string $caption The caption for the item.
string $exe The path to the executable.
int $glyph The glyph index.
string | null $params The parameters for the executable.
Returns
string The executable item string.
Definition at line 221 of file class.tpl.aestan.php.
    {
        return 'Type: item; ' .
            'Caption: "' . $caption . '"; ' .
            'Action: run; ' .
            'FileName: "' . $exe . '"; ' .
            (!empty($params) ? 'Parameters: "' . $params . '"; ' : '') .
            'Glyph: ' . $glyph;
    }
Referenced by getItemConsoleZ(), getItemLink(), getItemNotepad(), TplAppFilezilla\getMenuFilezilla(), TplAppGit\getMenuGit(), TplAppMailhog\getMenuMailhog(), TplAppMailpit\getMenuMailpit(), TplAppPython\getMenuPython(), and TplAppTools\getMenuTools().
getItemExplore()
static TplAestan::getItemExplore ($caption, $path) static
Returns a string representing an explorer item.
Parameters
string $caption The caption for the item.
string $path The path to explore.
Returns
string The explorer item string.
Definition at line 238 of file class.tpl.aestan.php.
    {
        return 'Type: item; ' .
            'Caption: "' . $caption . '"; ' .
            'Action: shellexecute; ' .
            'FileName: "' . $path . '"; ' .
            'Glyph: ' . self::GLYPH_FOLDER_OPEN;
    }
References GLYPH_FOLDER_OPEN.
Referenced by TplApp\getSectionMenuLeft().
getItemLink()
static TplAestan::getItemLink ($caption, $link, $local = false, $glyph = self::GLYPH_WEB_PAGE) static
Returns a string representing a link item.
Parameters
string $caption The caption for the item.
string $link The URL for the link.
bool $local Whether the link is local.
int $glyph The glyph index.
Returns
string The link item string.
Definition at line 177 of file class.tpl.aestan.php.
    {
        global $bearsamppRoot, $bearsamppConfig;
        if ($local) {
            $link = $bearsamppRoot->getLocalUrl($link);
        }
        return self::getItemExe(
            $caption,
            $bearsamppConfig->getBrowser(),
            $glyph,
            $link
        );
    }
References $bearsamppConfig, $bearsamppRoot, and getItemExe().
Referenced by TplAppApache\getMenuApache(), TplAppApps\getMenuApps(), TplAppFilezilla\getMenuFilezilla(), TplAppMailhog\getMenuMailhog(), TplAppMailpit\getMenuMailpit(), TplAppMariadb\getMenuMariadb(), TplAppMemcached\getMenuMemcached(), TplAppMysql\getMenuMysql(), TplAppNodejs\getMenuNodejs(), TplAppPhp\getMenuPhp(), TplAppPostgresql\getMenuPostgresql(), TplAppXlight\getMenuXlight(), TplApp\getSectionMenuLeft(), and TplApp\getSectionMenuRight().
getItemNotepad()
static TplAestan::getItemNotepad ($caption, $path) static
Returns a string representing a Notepad item.
Parameters
string $caption The caption for the item.
string $path The path to the file.
Returns
string The Notepad item string.
Definition at line 200 of file class.tpl.aestan.php.
    {
        global $bearsamppConfig;
        return self::getItemExe(
            $caption,
            $bearsamppConfig->getNotepad(),
            self::GLYPH_FILE,
            $path
        );
    }
References $bearsamppConfig, and getItemExe().
Referenced by TplAppApache\getMenuApache(), TplAppApache\getMenuApacheService(), TplAppFilezilla\getMenuFilezilla(), TplAppLogs\getMenuLogs(), TplAppMailhog\getMenuMailhog(), TplAppMailhog\getMenuMailhogService(), TplAppMailpit\getMenuMailpit(), TplAppMailpit\getMenuMailpitService(), TplAppMariadb\getMenuMariadb(), TplAppMemcached\getMenuMemcached(), TplAppMysql\getMenuMysql(), TplAppNodejs\getMenuNodejs(), TplAppPhp\getMenuPhp(), TplAppPostgresql\getMenuPostgresql(), TplAppXlight\getMenuXlight(), TplAppXlight\getMenuXlightService(), and TplAppEditConf\process().
getItemSeparator()
static TplAestan::getItemSeparator () static
Returns a string representing a separator item.
Returns
string The separator item string.
Definition at line 126 of file class.tpl.aestan.php.
    {
        return 'Type: separator';
    }
Referenced by TplAppApache\getMenuApache(), TplAppApache\getMenuApacheAlias(), TplAppApache\getMenuApacheService(), TplAppApache\getMenuApacheVhosts(), TplAppFilezilla\getMenuFilezilla(), TplAppFilezilla\getMenuFilezillaService(), TplAppGit\getMenuGit(), TplAppMailhog\getMenuMailhog(), TplAppMailhog\getMenuMailhogService(), TplAppMailpit\getMenuMailpit(), TplAppMailpit\getMenuMailpitService(), TplAppMariadb\getMenuMariadb(), TplAppMariadb\getMenuMariadbService(), TplAppMemcached\getMenuMemcached(), TplAppMemcached\getMenuMemcachedService(), TplAppMysql\getMenuMysql(), TplAppMysql\getMenuMysqlService(), TplAppNodejs\getMenuNodejs(), TplAppPhp\getMenuPhp(), TplAppPostgresql\getMenuPostgresql(), TplAppPostgresql\getMenuPostgresqlService(), TplAppTools\getMenuTools(), TplAppXlight\getMenuXlight(), TplAppXlight\getMenuXlightService(), TplApp\getSectionMenuLeft(), and TplApp\getSectionMenuRight().
getSectionConfig()
static TplAestan::getSectionConfig () static
Returns a string representing the config section.
Returns
string The config section string.
Definition at line 391 of file class.tpl.aestan.php.
    {
        global $bearsamppCore;
        return '[Config]' . PHP_EOL .
            'ImageList=' . self::IMG_GLYPH_SPRITES . PHP_EOL .
            'ServiceCheckInterval=1' . PHP_EOL .
            'TrayIconAllRunning=' . self::GLYPH_SERVICE_ALL_RUNNING . PHP_EOL .
            'TrayIconSomeRunning=' . self::GLYPH_SERVICE_SOME_RUNNING . PHP_EOL .
            'TrayIconNoneRunning=' . self::GLYPH_SERVICE_NONE_RUNNING . PHP_EOL .
            'ID={' . strtolower(APP_TITLE) . '}' . PHP_EOL .
            'AboutHeader=' . APP_TITLE . PHP_EOL .
            'AboutVersion=Version ' . $bearsamppCore->getAppVersion() . PHP_EOL;
    }
References $bearsamppCore, and APP_TITLE.
Referenced by TplApp\process(), and TplApp\processLight().
getSectionMenuLeftSettings()
static TplAestan::getSectionMenuLeftSettings ($caption) static
Returns a string representing the left menu settings section.
Parameters
string $caption The caption for the left menu.
Returns
string The left menu settings section string.
Definition at line 430 of file class.tpl.aestan.php.
    {
        return '[Menu.Left.Settings]' . PHP_EOL .
            'AutoLineReduction=no' . PHP_EOL .
            'BarVisible=yes' . PHP_EOL .
            'BarCaptionAlignment=bottom' . PHP_EOL .
            'BarCaptionCaption=' . $caption . PHP_EOL .
            'BarCaptionDepth=1' . PHP_EOL .
            'BarCaptionDirection=downtoup' . PHP_EOL .
            'BarCaptionFont=Tahoma,14,clWhite' . PHP_EOL .
            'BarCaptionHighlightColor=clNone' . PHP_EOL .
            'BarCaptionOffsetY=0' . PHP_EOL .
            'BarCaptionShadowColor=clNone' . PHP_EOL .
            'BarPictureHorzAlignment=center' . PHP_EOL .
            'BarPictureOffsetX=0' . PHP_EOL .
            'BarPictureOffsetY=0' . PHP_EOL .
            'BarPicturePicture=' . self::IMG_BAR_PICTURE . PHP_EOL .
            'BarPictureTransparent=yes' . PHP_EOL .
            'BarPictureVertAlignment=bottom' . PHP_EOL .
            'BarBorder=clNone' . PHP_EOL .
            'BarGradientEnd=$00c07840' . PHP_EOL .
            'BarGradientStart=$00c07840' . PHP_EOL .
            'BarGradientStyle=horizontal' . PHP_EOL .
            'BarSide=left' . PHP_EOL .
            'BarSpace=0' . PHP_EOL .
            'BarWidth=32' . PHP_EOL .
            'SeparatorsAlignment=center' . PHP_EOL .
            'SeparatorsFade=yes' . PHP_EOL .
            'SeparatorsFadeColor=clBtnShadow' . PHP_EOL .
            'SeparatorsFlatLines=yes' . PHP_EOL .
            'SeparatorsFont=Arial,8,clWhite,bold' . PHP_EOL .
            'SeparatorsGradientEnd=$00FFAA55' . PHP_EOL .
            'SeparatorsGradientStart=$00550000' . PHP_EOL .
            'SeparatorsGradientStyle=horizontal' . PHP_EOL .
            'SeparatorsSeparatorStyle=caption' . PHP_EOL;
    }
Referenced by TplApp\process().
getSectionMenuRightSettings()
static TplAestan::getSectionMenuRightSettings () static
Returns a string representing the right menu settings section.
Returns
string The right menu settings section string.
Definition at line 410 of file class.tpl.aestan.php.
    {
        return '[Menu.Right.Settings]' . PHP_EOL .
            'BarVisible=no' . PHP_EOL .
            'SeparatorsAlignment=center' . PHP_EOL .
            'SeparatorsFade=yes' . PHP_EOL .
            'SeparatorsFadeColor=clBtnShadow' . PHP_EOL .
            'SeparatorsFlatLines=yes' . PHP_EOL .
            'SeparatorsGradientEnd=clSilver' . PHP_EOL .
            'SeparatorsGradientStart=clGray' . PHP_EOL .
            'SeparatorsGradientStyle=horizontal' . PHP_EOL .
            'SeparatorsSeparatorStyle=shortline' . PHP_EOL;
    }
Referenced by TplApp\process().
getSectionMessages()
static TplAestan::getSectionMessages () static
Returns a string representing the messages section.
Returns
string The messages section string.
Definition at line 376 of file class.tpl.aestan.php.
    {
        global $bearsamppLang;
        return '[Messages]' . PHP_EOL .
            'AllRunningHint=' . $bearsamppLang->getValue(Lang::ALL_RUNNING_HINT) . PHP_EOL .
            'SomeRunningHint=' . $bearsamppLang->getValue(Lang::SOME_RUNNING_HINT) . PHP_EOL .
            'NoneRunningHint=' . $bearsamppLang->getValue(Lang::NONE_RUNNING_HINT) . PHP_EOL;
    }
References $bearsamppLang, Lang\ALL_RUNNING_HINT, Lang\NONE_RUNNING_HINT, and Lang\SOME_RUNNING_HINT.
Referenced by TplApp\process(), and TplApp\processLight().
Field Documentation
GLYPH_ABOUT
const TplAestan::GLYPH_ABOUT = 21
Definition at line 66 of file class.tpl.aestan.php.
Referenced by TplApp\getSectionMenuRight().
GLYPH_ADD
const TplAestan::GLYPH_ADD = 1
Definition at line 49 of file class.tpl.aestan.php.
Referenced by TplAppApache\getMenuApacheAlias(), and TplAppApache\getMenuApacheVhosts().
GLYPH_BROWSER
const TplAestan::GLYPH_BROWSER = 5
Definition at line 52 of file class.tpl.aestan.php.
Referenced by TplAppApache\getMenuApache(), TplAppFilezilla\getMenuFilezilla(), TplAppMailhog\getMenuMailhog(), TplAppMailpit\getMenuMailpit(), TplAppMariadb\getMenuMariadb(), TplAppMemcached\getMenuMemcached(), TplAppMysql\getMenuMysql(), TplAppNodejs\getMenuNodejs(), TplAppPhp\getMenuPhp(), TplAppPostgresql\getMenuPostgresql(), TplAppXlight\getMenuXlight(), and TplAppBrowser\process().
GLYPH_CHECK
const TplAestan::GLYPH_CHECK = 13
Definition at line 60 of file class.tpl.aestan.php.
Referenced by TplAppApache\getMenuApache(), TplAppApache\getMenuApacheModules(), TplAppApache\getMenuApacheVersions(), TplAppFilezilla\getMenuFilezilla(), TplAppFilezilla\getMenuFilezillaVersions(), TplAppGit\getMenuGit(), TplAppLang\getMenuLang(), TplAppLogsVerbose\getMenuLogsVerbose(), TplAppMailhog\getMenuMailhog(), TplAppMailhog\getMenuMailhogVersions(), TplAppMailpit\getMenuMailpit(), TplAppMailpit\getMenuMailpitVersions(), TplAppMariadb\getMenuMariadb(), TplAppMariadb\getMenuMariadbVersions(), TplAppMemcached\getMenuMemcached(), TplAppMemcached\getMenuMemcachedVersions(), TplAppMysql\getMenuMysql(), TplAppMysql\getMenuMysqlVersions(), TplAppNodejs\getMenuNodejs(), TplAppNodejs\getMenuNodejsVersions(), TplAppPhp\getMenuPhp(), TplAppPhp\getMenuPhpExtensions(), TplAppPhp\getMenuPhpSettings(), TplAppPhp\getMenuPhpVersions(), TplAppPostgresql\getMenuPostgresql(), TplAppPostgresql\getMenuPostgresqlVersions(), TplAppXlight\getMenuXlight(), TplAppXlight\getMenuXlightVersions(), TplAppPhp\getSubmenuPhpSettings(), and TplAppLaunchStartup\process().
GLYPH_COMPOSER
const TplAestan::GLYPH_COMPOSER = 37
Definition at line 81 of file class.tpl.aestan.php.
Referenced by TplAppTools\getMenuTools().
GLYPH_CONSOLEZ
const TplAestan::GLYPH_CONSOLEZ = 0
Definition at line 48 of file class.tpl.aestan.php.
Referenced by TplAppMariadb\getMenuMariadb(), TplAppMysql\getMenuMysql(), TplAppNodejs\getMenuNodejs(), TplAppPostgresql\getMenuPostgresql(), and TplAppTools\getMenuTools().
GLYPH_DEBUG
const TplAestan::GLYPH_DEBUG = 31
Definition at line 75 of file class.tpl.aestan.php.
Referenced by TplAppApache\getMenuApacheDebug(), TplAppMariadb\getMenuMariadbDebug(), TplAppMysql\getMenuMysqlDebug(), TplAppPostgresql\getMenuPostgresqlDebug(), and TplAppTools\getMenuTools().
GLYPH_EXIT
const TplAestan::GLYPH_EXIT = 20
Definition at line 65 of file class.tpl.aestan.php.
Referenced by TplAppExit\process().
GLYPH_FILE
const TplAestan::GLYPH_FILE = 6
Definition at line 53 of file class.tpl.aestan.php.
Referenced by TplAppApache\getMenuApacheAlias(), and TplAppApache\getMenuApacheVhosts().
GLYPH_FILEZILLA
const TplAestan::GLYPH_FILEZILLA = 47
Definition at line 87 of file class.tpl.aestan.php.
Referenced by TplAppFilezilla\getMenuFilezilla().
GLYPH_FOLDER_CLOSE
const TplAestan::GLYPH_FOLDER_CLOSE = 3
Definition at line 51 of file class.tpl.aestan.php.
Referenced by TplApp\getMenu(), TplApp\getMenuEnable(), TplAppPhp\getMenuPhpSettings(), and TplAppPhp\getSubmenuPhpSettings().
GLYPH_FOLDER_DISABLED
const TplAestan::GLYPH_FOLDER_DISABLED = 48
Definition at line 88 of file class.tpl.aestan.php.
Referenced by TplApp\getMenuEnable().
GLYPH_FOLDER_ENABLED
const TplAestan::GLYPH_FOLDER_ENABLED = 49
Definition at line 89 of file class.tpl.aestan.php.
GLYPH_FOLDER_OPEN
const TplAestan::GLYPH_FOLDER_OPEN = 2
Definition at line 50 of file class.tpl.aestan.php.
Referenced by getItemExplore().
GLYPH_GHOSTSCRIPT
const TplAestan::GLYPH_GHOSTSCRIPT = 56
Definition at line 95 of file class.tpl.aestan.php.
Referenced by TplAppTools\getMenuTools().
GLYPH_GIT
const TplAestan::GLYPH_GIT = 26
Definition at line 71 of file class.tpl.aestan.php.
Referenced by TplAppGit\getMenuGit(), and TplAppGit\getMenuGitRepos().
GLYPH_HOSTSEDITOR
const TplAestan::GLYPH_HOSTSEDITOR = 39
Definition at line 83 of file class.tpl.aestan.php.
Referenced by TplAppTools\getMenuTools().
GLYPH_IMAGEMAGICK
const TplAestan::GLYPH_IMAGEMAGICK = 41
Definition at line 84 of file class.tpl.aestan.php.
GLYPH_LIGHT
const TplAestan::GLYPH_LIGHT = 25
Definition at line 70 of file class.tpl.aestan.php.
Referenced by TplAppApache\getMenuApacheService(), TplAppFilezilla\getMenuFilezillaService(), TplAppMailhog\getMenuMailhogService(), TplAppMailpit\getMenuMailpitService(), TplAppMariadb\getMenuMariadbService(), TplAppMemcached\getMenuMemcachedService(), TplAppMysql\getMenuMysqlService(), TplAppPostgresql\getMenuPostgresqlService(), and TplAppXlight\getMenuXlightService().
GLYPH_NETWORK
const TplAestan::GLYPH_NETWORK = 29
Definition at line 73 of file class.tpl.aestan.php.
Referenced by TplAppApache\getMenuApacheService(), TplAppFilezilla\getMenuFilezillaService(), TplAppMailhog\getMenuMailhogService(), TplAppMailpit\getMenuMailpitService(), TplAppMariadb\getMenuMariadbService(), TplAppMemcached\getMenuMemcachedService(), TplAppMysql\getMenuMysqlService(), TplAppPostgresql\getMenuPostgresqlService(), and TplAppXlight\getMenuXlightService().
GLYPH_NGROK
const TplAestan::GLYPH_NGROK = 57
Definition at line 96 of file class.tpl.aestan.php.
Referenced by TplAppTools\getMenuTools().
GLYPH_NODEJS
const TplAestan::GLYPH_NODEJS = 28
Definition at line 72 of file class.tpl.aestan.php.
GLYPH_NOTEPAD2
const TplAestan::GLYPH_NOTEPAD2 = 42
Definition at line 85 of file class.tpl.aestan.php.
GLYPH_PASSWORD
const TplAestan::GLYPH_PASSWORD = 45
Definition at line 86 of file class.tpl.aestan.php.
Referenced by TplAppMariadb\getMenuMariadbService(), TplAppMysql\getMenuMysqlService(), and TplAppPostgresql\getMenuPostgresqlService().
GLYPH_PAUSE
const TplAestan::GLYPH_PAUSE = 10
Definition at line 57 of file class.tpl.aestan.php.
GLYPH_PEAR
const TplAestan::GLYPH_PEAR = 38
Definition at line 82 of file class.tpl.aestan.php.
Referenced by TplAppTools\getMenuTools().
GLYPH_PERL
const TplAestan::GLYPH_PERL = 55
Definition at line 94 of file class.tpl.aestan.php.
Referenced by TplAppTools\getMenuTools().
GLYPH_PWGEN
const TplAestan::GLYPH_PWGEN = 58
Definition at line 97 of file class.tpl.aestan.php.
Referenced by TplAppTools\getMenuTools().
GLYPH_PYTHON
const TplAestan::GLYPH_PYTHON = 50
Definition at line 90 of file class.tpl.aestan.php.
Referenced by TplAppPython\getMenuPython().
GLYPH_PYTHON_CP
const TplAestan::GLYPH_PYTHON_CP = 51
Definition at line 91 of file class.tpl.aestan.php.
Referenced by TplAppPython\getMenuPython().
GLYPH_REBUILD_INI
const TplAestan::GLYPH_REBUILD_INI = 60
Definition at line 99 of file class.tpl.aestan.php.
Referenced by TplAppRebuildIni\process().
GLYPH_RED_LIGHT
const TplAestan::GLYPH_RED_LIGHT = 36
Definition at line 80 of file class.tpl.aestan.php.
Referenced by TplAppApache\getMenuApacheService(), and TplAppFilezilla\getMenuFilezillaService().
GLYPH_RELOAD
const TplAestan::GLYPH_RELOAD = 12
Definition at line 59 of file class.tpl.aestan.php.
Referenced by getActionService(), TplService\getItemRestart(), TplAppGit\getMenuGit(), and TplAppReload\process().
GLYPH_RESTART
const TplAestan::GLYPH_RESTART = 34
Definition at line 78 of file class.tpl.aestan.php.
GLYPH_RUBY
const TplAestan::GLYPH_RUBY = 52
Definition at line 92 of file class.tpl.aestan.php.
Referenced by TplAppTools\getMenuTools().
GLYPH_SERVICE_ALL_RUNNING
const TplAestan::GLYPH_SERVICE_ALL_RUNNING = 16
Definition at line 61 of file class.tpl.aestan.php.
GLYPH_SERVICE_INSTALL
const TplAestan::GLYPH_SERVICE_INSTALL = 8
Definition at line 55 of file class.tpl.aestan.php.
Referenced by TplService\getItemInstall(), TplAppApache\getMenuApacheService(), TplAppFilezilla\getMenuFilezillaService(), TplAppMailhog\getMenuMailhogService(), TplAppMailpit\getMenuMailpitService(), TplAppMariadb\getMenuMariadbService(), TplAppMemcached\getMenuMemcachedService(), TplAppMysql\getMenuMysqlService(), TplAppPostgresql\getMenuPostgresqlService(), and TplAppXlight\getMenuXlightService().
GLYPH_SERVICE_NONE_RUNNING
const TplAestan::GLYPH_SERVICE_NONE_RUNNING = 18
Definition at line 63 of file class.tpl.aestan.php.
GLYPH_SERVICE_REMOVE
const TplAestan::GLYPH_SERVICE_REMOVE = 7
Definition at line 54 of file class.tpl.aestan.php.
Referenced by TplService\getItemRemove(), TplAppApache\getMenuApacheService(), TplAppFilezilla\getMenuFilezillaService(), TplAppMailhog\getMenuMailhogService(), TplAppMailpit\getMenuMailpitService(), TplAppMariadb\getMenuMariadbService(), TplAppMemcached\getMenuMemcachedService(), TplAppMysql\getMenuMysqlService(), TplAppPostgresql\getMenuPostgresqlService(), and TplAppXlight\getMenuXlightService().
GLYPH_SERVICE_SOME_RUNNING
const TplAestan::GLYPH_SERVICE_SOME_RUNNING = 17
Definition at line 62 of file class.tpl.aestan.php.
GLYPH_SERVICES_RESTART
const TplAestan::GLYPH_SERVICES_RESTART = 22
Definition at line 67 of file class.tpl.aestan.php.
Referenced by TplAppServices\process().
GLYPH_SERVICES_START
const TplAestan::GLYPH_SERVICES_START = 24
Definition at line 69 of file class.tpl.aestan.php.
Referenced by TplAppServices\process().
GLYPH_SERVICES_STOP
const TplAestan::GLYPH_SERVICES_STOP = 23
Definition at line 68 of file class.tpl.aestan.php.
Referenced by TplAppServices\process().
GLYPH_SSL_CERTIFICATE
const TplAestan::GLYPH_SSL_CERTIFICATE = 35
Definition at line 79 of file class.tpl.aestan.php.
Referenced by TplAppTools\getMenuTools().
GLYPH_START
const TplAestan::GLYPH_START = 9
Definition at line 56 of file class.tpl.aestan.php.
Referenced by getActionService(), and TplService\getItemStart().
GLYPH_STOP
const TplAestan::GLYPH_STOP = 11
Definition at line 58 of file class.tpl.aestan.php.
Referenced by getActionService(), and TplService\getItemStop().
GLYPH_TRASHCAN
const TplAestan::GLYPH_TRASHCAN = 32
Definition at line 76 of file class.tpl.aestan.php.
Referenced by TplAppClearFolders\process().
GLYPH_UPDATE
const TplAestan::GLYPH_UPDATE = 33
Definition at line 77 of file class.tpl.aestan.php.
Referenced by TplApp\getSectionMenuRight().
GLYPH_WARNING
const TplAestan::GLYPH_WARNING = 19
Definition at line 64 of file class.tpl.aestan.php.
Referenced by TplAppApache\getMenuApacheVersions(), TplAppPhp\getMenuPhpSettings(), TplAppPhp\getMenuPhpVersions(), and TplAppPhp\getSubmenuPhpSettings().
GLYPH_WEB_PAGE
const TplAestan::GLYPH_WEB_PAGE = 30
Definition at line 74 of file class.tpl.aestan.php.
Referenced by TplAppMailhog\getMenuMailhog(), and TplAppMailpit\getMenuMailpit().
GLYPH_XLIGHT
const TplAestan::GLYPH_XLIGHT = 59
Definition at line 98 of file class.tpl.aestan.php.
GLYPH_YARN
const TplAestan::GLYPH_YARN = 54
Definition at line 93 of file class.tpl.aestan.php.
Referenced by TplAppTools\getMenuTools().
IMG_BAR_PICTURE
const TplAestan::IMG_BAR_PICTURE = 'bar.dat'
Definition at line 108 of file class.tpl.aestan.php.
IMG_GLYPH_SPRITES
const TplAestan::IMG_GLYPH_SPRITES = 'sprites.dat'
Definition at line 109 of file class.tpl.aestan.php.
SERVICE_RESTART
const TplAestan::SERVICE_RESTART = 'restart'
Definition at line 104 of file class.tpl.aestan.php.
SERVICE_START
const TplAestan::SERVICE_START = 'startresume'
Definition at line 102 of file class.tpl.aestan.php.
SERVICE_STOP
const TplAestan::SERVICE_STOP = 'stop'
Definition at line 103 of file class.tpl.aestan.php.
SERVICES_CLOSE
const TplAestan::SERVICES_CLOSE = 'closeservices'
Definition at line 105 of file class.tpl.aestan.php.
The documentation for this class was generated from the following file:
E:/Bearsampp-development/sandbox/core/classes/tpls/class.tpl.aestan.php