My Project: QuickPick Class Reference
QuickPick Class Reference
Public Member Functions
__construct ()
checkDownloadId ()
checkQuickpickJson ()
fetchAndUnzipModule (string $moduleUrl, string $module)
getModules ()
getModuleUrl (string $module, string $version)
getQuickpickJson ()
getQuickpickMenu (array $modules, array $versions, string $imagesPath)
getVersions ()
installModule (string $module, string $version)
loadQuickpick (string $imagesPath)
rebuildQuickpickJson ()
Data Fields
$modules
const API_KEY = '4abe15e5-95f2-4663-ad12-eadb245b28b4'
const API_URL = 'https://bearsampp.com/index.php?option=com_osmembership&task=api.get_active_plan_ids&api_key='
const JSON_URL = 'https://raw.githubusercontent.com/Bearsampp/Bearsampp/main/core/resources/quickpick-releases.json'
Private Attributes
$jsonFilePath
$versions = []
Detailed Description
Class QuickPick
The QuickPick class provides functionalities for managing and installing various modules within the Bearsampp application. It includes methods for retrieving available modules, fetching module versions, parsing release properties, and validating license keys.
Definition at line 17 of file class.action.quickPick.php.
Constructor & Destructor Documentation
__construct()
QuickPick::__construct ()
Constructor to initialize the jsonFilePath.
Definition at line 77 of file class.action.quickPick.php.
    {
        global $bearsamppCore;
        $this->jsonFilePath = $bearsamppCore->getResourcesPath() . '/quickpick-releases.json';
    }
References $bearsamppCore.
Member Function Documentation
checkDownloadId()
QuickPick::checkDownloadId ()
Validates the format of a given username key by checking it against an external API.
This method performs several checks to ensure the validity of the username key:
Logs the method call.
Ensures the global configuration is available.
Retrieves the username key from the global configuration.
Ensures the username key is not empty.
Constructs the API URL using the username key.
Fetches the API response.
Decodes the JSON response.
Validates the response data.
Returns
bool True if the username key is valid, false otherwise.
Definition at line 294 of file class.action.quickPick.php.
                                     : bool
    {
        global $bearsamppConfig;
        Util::logDebug('checkDownloadId method called.');
        // Ensure the global config is available
        if (!isset($bearsamppConfig)) {
            Util::logError('Global configuration is not set.');
            return false;
        }
        $DownloadId = $bearsamppConfig->getDownloadId();
        Util::logDebug('DownloadId is: ' . $DownloadId);
        // Ensure the license key is not empty
        if (empty($DownloadId)) {
            Util::logError('License key is empty.');
            return false;
        }
        $url = self::API_URL . self::API_KEY . '&download_id=' . $DownloadId;
        Util::logDebug('API URL: ' . $url);
        $response = @file_get_contents($url);
        // Check if the response is false
        if ($response === false) {
            $error = error_get_last();
            Util::logError('Error fetching API response: ' . $error['message']);
            return false;
        }
        Util::logDebug('API response: ' . $response);
        $data = json_decode($response, true);
        // Check if the JSON decoding was successful
        if (json_last_error() !== JSON_ERROR_NONE) {
            Util::logError('Error decoding JSON response: ' . json_last_error_msg());
            return false;
        }
        // Validate the response data
        if (isset($data['success']) && $data['success'] === true && isset($data['data']) && is_array($data['data']) && count($data['data']) > 0) {
            Util::logDebug('License key valid: ' . $DownloadId);
            return true;
        }
        Util::logError('Invalid license key: ' . $DownloadId);
        return false;
    }
References $bearsamppConfig, $response, Util\logDebug(), and Util\logError().
Referenced by getQuickpickMenu().
checkQuickpickJson()
QuickPick::checkQuickpickJson ()
Checks if the local quickpick-releases.json file is up-to-date with the remote version.
This method compares the creation time of the local JSON file with the remote file's last modified time. If the remote file is newer or the local file does not exist, it fetches the latest JSON data by calling the rebuildQuickpickJson method.
Returns
array|false Returns the JSON data if the remote file is newer or the local file does not exist, otherwise returns false.
Exceptions
Exception
Definition at line 123 of file class.action.quickPick.php.
    {
        // Initialize variables
        $localFileCreationTime = 0;
        // Get the creation time of the local file if it exists
        if (file_exists($this->jsonFilePath)) {
            $localFileCreationTime = filectime($this->jsonFilePath);
        }
        // Get the creation time of the remote file
        $headers = get_headers(self::JSON_URL, 1);
        if ($headers === false || !isset($headers['Last-Modified'])) {
            // If we cannot get the headers or Last-Modified is not set, assume no update is needed
            return false;
        }
        $remoteFileCreationTime = strtotime($headers['Last-Modified']);
        // Compare the creation times
        if ($remoteFileCreationTime > $localFileCreationTime || $localFileCreationTime === 0) {
            return $this->rebuildQuickpickJson();
        }
        // Return false if the local file is up-to-date
        return false;
    }
References rebuildQuickpickJson().
Referenced by loadQuickpick().
fetchAndUnzipModule()
QuickPick::fetchAndUnzipModule (string $moduleUrl, string $module)
Fetches the module URL and stores it in /tmp, then unzips the file based on its extension.
Parameters
string $moduleUrl The URL of the module to fetch.
string $module The name of the module.
Returns
array An array containing the status and message.
Definition at line 405 of file class.action.quickPick.php.
                                                                          : array
    {
        Util::logDebug( "$module is: " . $module );
        global $bearsamppRoot, $bearsamppCore;
        $tmpDir = $bearsamppRoot->getTmpPath();
        Util::logDebug( 'Temporary Directory: ' . $tmpDir );
        $fileName = basename( $moduleUrl );
        Util::logDebug( 'File Name: ' . $fileName );
        $filePath = $tmpDir . '/' . $fileName;
        Util::logDebug( 'File Path: ' . $filePath );
        $moduleName = str_replace( 'module-', '', $module );
        Util::logDebug( 'Module Name: ' . $moduleName );
        $moduleType = $this->modules[$module]['type'];
        Util::logDebug( 'Module Type: ' . $moduleType );
        // Get path to write module to.
        if ( $moduleType === 'application' ) {
            $destination = $bearsamppRoot->getAppsPath() . '/' . $moduleName . '/';
        }
        elseif ( $moduleType === 'binary' ) {
            $destination = $bearsamppRoot->getBinPath() . '/' . $moduleName . '/';
        }
        elseif ( $moduleType === 'tools' ) {
            $destination = $bearsamppRoot->getToolsPath() . '/' . $moduleName . '/';
        }
        else {
            $destination = '';
        }
        // Fetch the file from the URL
        $fileContent = @file_get_contents( $moduleUrl );
        if ( $fileContent === false ) {
            Util::logError( 'Error fetching content from URL: ' . $moduleUrl );
            return ['error' => 'Error fetching module'];
        }
        // Save the file to /tmp
        if ( file_put_contents( $filePath, $fileContent ) === false ) {
            Util::logError( 'Error saving file to: ' . $filePath );
            return ['error' => 'Error saving module'];
        }
        Util::logDebug( 'File saved to: ' . $filePath );
        // Determine the file extension and call the appropriate unzipping function
        $fileExtension = pathinfo( $filePath, PATHINFO_EXTENSION );
        Util::logDebug( 'File extension: ' . $fileExtension );
        if ( $fileExtension === '7z' ) {
            if ( !$bearsamppCore->unzip7zFile( $filePath, $destination ) ) {
                return ['error' => 'Failed to unzip .7z file.  File: ' . $filePath . ' could not be unzipped', 'Destination: ' . $destination];
            }
        }
        elseif ( $fileExtension === 'zip' ) {
            if ( !$bearsamppCore->unzipFile( $filePath, $destination ) ) {
                return ['error' => 'Failed to unzip .zip file'];
            }
        }
        else {
            Util::logError( 'Unsupported file extension: ' . $fileExtension );
            return ['error' => 'Unsupported file extension'];
        }
        return ['success' => 'Module fetched and unzipped successfully'];
    }
References $bearsamppCore, $bearsamppRoot, Util\logDebug(), and Util\logError().
Referenced by installModule().
getModules()
QuickPick::getModules ()
Retrieves the list of available modules.
Returns
array An array of module names.
Definition at line 88 of file class.action.quickPick.php.
                                : array
    {
        return array_keys($this->modules);
    }
Referenced by loadQuickpick().
getModuleUrl()
QuickPick::getModuleUrl (string $module, string $version)
Fetches the URL of a specified module version from the local quickpick-releases.json file.
This method reads the quickpick-releases.json file to find the URL associated with the given module and version. It logs the process and returns the URL if found, or an error message if not.
Parameters
string $module The name of the module.
string $version The version of the module.
Returns
string|array The URL of the specified module version or an error message if the version is not found.
Definition at line 263 of file class.action.quickPick.php.
    {
        $this->getVersions();
        Util::logDebug('getModuleUrl called for module: ' . $module . ' version: ' . $version);
        $url = trim($this->versions['module-' . strtolower($module)][$version]['url']);
        if ($url <> '') {
            Util::logDebug('Found URL for version: ' . $version . ' URL: ' . $url);
            return $url;
        } else {
            Util::logError('Version not found: ' . $version);
            return ['error' => 'Version not found'];
        }
    }
References getVersions(), Util\logDebug(), and Util\logError().
Referenced by installModule().
getQuickpickJson()
QuickPick::getQuickpickJson ()
Retrieves the QuickPick JSON data from the local file.
Returns
array The decoded JSON data, or an error message if the file cannot be fetched or decoded.
Definition at line 155 of file class.action.quickPick.php.
                                      : array
    {
        $content = @file_get_contents($this->jsonFilePath);
        if ($content === false) {
            Util::logError('Error fetching content from JSON file: ' . $this->jsonFilePath);
            return ['error' => 'Error fetching JSON file'];
        }
        // file has extra spaces in key data, time to sanitise the data
        $j    = $content;
        $j    = str_replace("\" ", "\"", $j); // remove "<space>data
        $j    = str_replace(" \"", "\"", $j); // remove data<space>"
        $data = json_decode($j, true);
        if (json_last_error() !== JSON_ERROR_NONE) {
            Util::logError('Error decoding JSON content: ' . json_last_error_msg());
            return ['error' => 'Error decoding JSON content'];
        }
        return $data;
    }
References Util\logError().
Referenced by getVersions().
getQuickpickMenu()
QuickPick::getQuickpickMenu (array $modules, array $versions, string $imagesPath)
Generates the HTML content for the QuickPick menu.
This method creates the HTML structure for the QuickPick interface, including a dropdown for selecting modules and their respective versions. It checks if the license key is valid before displaying the modules. If the license key is invalid, it displays a subscription prompt. If there is no internet connection, it displays a message indicating the lack of internet.
Parameters
array $modules An array of available modules.
array $versions An associative array where the key is the module name and the value is an array containing the module versions.
string $imagesPath The path to the images directory.
Returns
string The HTML content of the QuickPick menu.
Definition at line 492 of file class.action.quickPick.php.
                                                                                         : string
    {
        ob_start();
        if ( Util::checkInternetState() ) {
            // Check if the license key is valid
            if ( $this->checkDownloadId() ): ?>
                <div id = 'quickPickContainer'>
                    <div class = 'quickpick me-5'>
                        <div class = "custom-select">
                            <button class = "select-button" role = "combobox"
                                    aria-label = "select button"
                                    aria-haspopup = "listbox"
                                    aria-expanded = "false"
                                    aria-controls = "select-dropdown">
                                <span class = "selected-value">Select a module and version</span>
                                <span class = "arrow"></span>
                            </button>
                            <ul class = "select-dropdown" role = "listbox" id = "select-dropdown">
                                <?php
                                foreach ( $modules as $module ): ?>
                                    <?php if ( is_string( $module ) ): ?>
                                        <li role = "option" class = "moduleheader">
                                            <?php echo htmlspecialchars( $module ); ?>
                                        </li>
                                        <?php
                                        foreach ( $versions['module-' . strtolower( $module )] as $version_array ): ?>
                                            <li role = "option" class = "moduleoption"
                                                id = "<?php echo htmlspecialchars( $module ); ?>-version-<?php echo htmlspecialchars( $version_array['version'] ); ?>-li">
                                                <input type = "radio"
                                                       id = "<?php echo htmlspecialchars( $module ); ?>-version-<?php echo htmlspecialchars( $version_array['version'] ); ?>"
                                                       name = "module" data-module = "<?php echo htmlspecialchars( $module ); ?>"
                                                       data-value = "<?php echo htmlspecialchars( $version_array['version'] ); ?>">
                                                <label
                                                    for = "<?php echo htmlspecialchars( $module ); ?>-version-<?php echo htmlspecialchars( $version_array['version'] ); ?>"><?php echo htmlspecialchars( $version_array['version'] ); ?></label>
                                            </li>
                                        <?php endforeach; ?>
                                    <?php endif; ?>
                                <?php endforeach; ?>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class = "modal" id = "myModal" tabindex = "-1"
                     aria-labelledby = "exampleModalLabel" aria-hidden = "true">
                    <div class = "modal-dialog">
                        <div class = "modal-content">
                            <div class = "modal-header">
                                <h5 class = "modal-title" id = "exampleModalLabel">Installing, please wait...</h5>
                                <button type = "button" class = "closeModalBtn" data-bs-dismiss = "modal" aria-label = "Close"></button>
                            </div>
                            <div class = "modal-body">
                                <div class = "waitloader"></div>
                            </div>
                            <div class = "modal-footer">
                                <button type = "button" class = "btn btn-secondary" data-bs-dismiss = "modal">Close</button>
                            </div>
                        </div>
                    </div>
                </div>
            <?php else: ?>
                <div id = "subscribeContainer" class = "text-center mt-3 pe-3">
                    <a href = "<?php echo Util::getWebsiteUrl( 'subscribe' ); ?>" class = "btn btn-dark d-inline-flex align-items-center">
                        <img src = "<?php echo $imagesPath . 'subscribe.svg'; ?>" alt = "Subscribe Icon" class = "me-2">
                        Subscribe to QuickPick now
                    </a>
                </div>
            <?php endif;
        }
        else {
            ?>
            <div id = "InternetState" class = "text-center mt-3 pe-3">
                <img src = "<?php echo $imagesPath . 'no-wifi-icon.svg'; ?>" alt = "No Wifi Icon" class = "me-2">
                <span>No internet present</span>
            </div>
            <?php
        }
        return ob_get_clean();
    }}
References $imagesPath, checkDownloadId(), Util\checkInternetState(), and Util\getWebsiteUrl().
Referenced by loadQuickpick().
getVersions()
QuickPick::getVersions ()
Retrieves the list of available versions for all modules.
This method fetches the QuickPick JSON data and returns an array of versions or If no versions are found, an error message is logged and returned.
Returns
array An array of version strings for the specified module, or an error message if no versions are found.
Definition at line 219 of file class.action.quickPick.php.
                                 : array
    {
        Util::logDebug('Versions called');
        $versions = [];
        $jsonData = $this->getQuickpickJson();
        foreach ($jsonData as $entry) {
            if (is_array($entry)) {
                if (isset($entry['module']) && is_string($entry['module'])) {
                    if (isset($entry['versions']) && is_array($entry['versions'])) {
                        $versions[$entry['module']] = array_column($entry['versions'], null, 'version');
                    }
                }
            } else {
                Util::logError('Invalid entry format in JSON data');
            }
        }
        if (empty($versions)) {
            Util::logError('No versions found');
            return ['error' => 'No versions found'];
        }
        Util::logDebug('Found versions');
        $this->versions = $versions;
        return $versions;
    }
References $versions, getQuickpickJson(), Util\logDebug(), and Util\logError().
Referenced by getModuleUrl(), and loadQuickpick().
installModule()
QuickPick::installModule (string $module, string $version)
Installs a specified module by fetching its URL and unzipping its contents.
This method retrieves the URL of the specified module and version from the QuickPick JSON data. If the URL is found, it fetches and unzips the module. If the URL is not found, it logs an error and returns an error message.
Parameters
string $module The name of the module to install.
string $version The version of the module to install.
Returns
array An array containing the status and message of the installation process. If successful, it returns the response from the fetchAndUnzipModule method. If unsuccessful, it returns an error message indicating the issue.
Definition at line 367 of file class.action.quickPick.php.
                                                                  : array
    {
        // Find the module URL and module name from the data
        $moduleUrl = $this->getModuleUrl($module, $version);
        if (is_array($moduleUrl) && isset($moduleUrl['error'])) {
            Util::logError('Module URL not found for module: ' . $module . ' version: ' . $version);
            return ['error' => 'Module URL not found'];
        }
        if (empty($moduleUrl)) {
            Util::logError('Module URL not found for module: ' . $module . ' version: ' . $version);
            return ['error' => 'Module URL not found'];
        }
        $state = Util::checkInternetState();
        if ($state) {
            $response = $this->fetchAndUnzipModule($moduleUrl, $module);
            Util::logDebug('Response is: ' . print_r($response, true));
            return $response;
        } else {
            Util::logError('No internet connection available.');
            return ['error' => 'No internet connection'];
        }
    }
References $response, Util\checkInternetState(), fetchAndUnzipModule(), getModuleUrl(), Util\logDebug(), and Util\logError().
loadQuickpick()
QuickPick::loadQuickpick (string $imagesPath)
Loads the QuickPick interface with the available modules and their versions.
Parameters
string $imagesPath The path to the images directory.
Returns
string The HTML content of the QuickPick interface.
Exceptions
Exception
Definition at line 102 of file class.action.quickPick.php.
                                                     : string
    {
        $this->checkQuickpickJson();
        $modules  = $this->getModules();
        $versions = $this->getVersions();
        return $this->getQuickpickMenu($modules, $versions, $imagesPath);
    }
References $modules, $versions, checkQuickpickJson(), getModules(), getQuickpickMenu(), and getVersions().
rebuildQuickpickJson()
QuickPick::rebuildQuickpickJson ()
Rebuilds the local quickpick-releases.json file by fetching the latest data from the remote URL.
Returns
array An array containing the status and message of the rebuild process.
Exceptions
Exception If the JSON content cannot be fetched or saved.
Definition at line 184 of file class.action.quickPick.php.
                                          : array
    {
        Util::logDebug('Fetching JSON file: ' . $this->jsonFilePath);
        // Define the URL of the remote JSON file
        $url = self::JSON_URL;
        // Fetch the JSON content from the URL
        $jsonContent = file_get_contents($url);
        if ($jsonContent === false) {
            // Handle error if the file could not be fetched
            throw new Exception('Failed to fetch JSON content from the URL.');
        }
        // Save the JSON content to the specified path
        $result = file_put_contents($this->jsonFilePath, $jsonContent);
        if ($result === false) {
            // Handle error if the file could not be saved
            throw new Exception('Failed to save JSON content to the specified path.');
        }
        // Return success message
        return ['success' => 'JSON content fetched and saved successfully'];
    }
References $result, JSON_URL, and Util\logDebug().
Referenced by checkQuickpickJson().
Field Documentation
$jsonFilePath
QuickPick::$jsonFilePath private
The file path to the local quickpick-releases.json file.
Definition at line 72 of file class.action.quickPick.php.
$modules
QuickPick::$modules
Initial value:
= [
        'Adminer'     => ['type' => 'application'],
        'Apache'      => ['type' => 'binary'],
        'Composer'    => ['type' => 'tools'],
        'ConsoleZ'    => ['type' => 'tools'],
        'Ghostscript' => ['type' => 'tools'],
        'Git'         => ['type' => 'tools'],
        'Mailpit'     => ['type' => 'binary'],
        'MariaDB'     => ['type' => 'binary'],
        'Memcached'   => ['type' => 'binary'],
        'MySQL'       => ['type' => 'binary'],
        'Ngrok'       => ['type' => 'tools'],
        'NodeJS'      => ['type' => 'binary'],
        'Perl'        => ['type' => 'tools'],
        'PHP'         => ['type' => 'binary'],
        'PhpMyAdmin'  => ['type' => 'application'],
        'PhpPgAdmin'  => ['type' => 'application'],
        'PostgreSQL'  => ['type' => 'binary'],
        'Python'      => ['type' => 'tools'],
        'Ruby'        => ['type' => 'tools'],
        'Webgrind'    => ['type' => 'application'],
        'Xlight'      => ['type' => 'binary'],
        'Yarn'        => ['type' => 'tools']
    ]
An associative array where the key is the module name and the value is an array containing the module type. The module type can be one of the following:
'application'
'binary'
'tool'
Definition at line 35 of file class.action.quickPick.php.
Referenced by loadQuickpick().
$versions
QuickPick::$versions = [] private
An associative array where the key is the module name and the value is an array containing the module versions.
Definition at line 65 of file class.action.quickPick.php.
Referenced by getVersions(), and loadQuickpick().
API_KEY
const QuickPick::API_KEY = '4abe15e5-95f2-4663-ad12-eadb245b28b4'
Definition at line 20 of file class.action.quickPick.php.
API_URL
const QuickPick::API_URL = 'https://bearsampp.com/index.php?option=com_osmembership&task=api.get_active_plan_ids&api_key='
Definition at line 21 of file class.action.quickPick.php.
JSON_URL
const QuickPick::JSON_URL = 'https://raw.githubusercontent.com/Bearsampp/Bearsampp/main/core/resources/quickpick-releases.json'
Definition at line 24 of file class.action.quickPick.php.
Referenced by rebuildQuickpickJson().
The documentation for this class was generated from the following file:
E:/Bearsampp-development/sandbox/core/classes/actions/class.action.quickPick.php