Bearsampp: Root Class Reference
Root Class Reference
Public Member Functions
__construct ($rootPath)
errorHandler ($errno, $errstr, $errfile, $errline)
getAliasPath ($aetrayPath=false)
getAppsPath ($aetrayPath=false)
getBatchLogFilePath ($aetrayPath=false)
getBinPath ($aetrayPath=false)
getConfigFilePath ($aetrayPath=false)
getCorePath ($aetrayPath=false)
getErrorLogFilePath ($aetrayPath=false)
getExeFilePath ($aetrayPath=false)
getHomepageFilePath ($aetrayPath=false)
getHomepageLogFilePath ($aetrayPath=false)
getIniFilePath ($aetrayPath=false)
getLocalUrl ($request=null)
getLogFilePath ($aetrayPath=false)
getLogsPath ($aetrayPath=false)
getNssmLogFilePath ($aetrayPath=false)
getProcessName ()
getProcs ()
getRegistryLogFilePath ($aetrayPath=false)
getRootPath ($aetrayPath=false)
getServicesLogFilePath ($aetrayPath=false)
getSslConfPath ($aetrayPath=false)
getSslPath ($aetrayPath=false)
getStartupLogFilePath ($aetrayPath=false)
getTmpPath ($aetrayPath=false)
getToolsPath ($aetrayPath=false)
getVbsLogFilePath ($aetrayPath=false)
getVhostsPath ($aetrayPath=false)
getWinbinderLogFilePath ($aetrayPath=false)
getWwwPath ($aetrayPath=false)
initErrorHandling ()
isRoot ()
register ()
removeErrorHandling ()
Static Public Member Functions
static loadApps ()
static loadBins ()
static loadConfig ()
static loadCore ()
static loadHomepage ()
static loadLang ()
static loadOpenSsl ()
static loadRegistry ()
static loadTools ()
static loadWinbinder ()
Data Fields
$path
const ERROR_HANDLER = 'errorHandler'
Private Member Functions
aetrayPath ($path)
Static Private Member Functions
static debugStringBacktrace ()
Private Attributes
$isRoot
$procs
Detailed Description
Class Root
This class represents the root of the Bearsampp application. It handles the initialization, configuration, and management of various components and settings within the application.
Definition at line 16 of file class.root.php.
Constructor & Destructor Documentation
__construct()
Root::__construct ($rootPath)
Constructs a Root object with the specified root path.
Parameters
string $rootPath The root path of the application.
Definition at line 29 of file class.root.php.
    {
        $this->path = str_replace('\\', '/', rtrim($rootPath, '/\\'));
        $this->isRoot = $_SERVER['PHP_SELF'] == 'root.php';
    }
References isRoot().
Member Function Documentation
aetrayPath()
Root::aetrayPath ($path) private
Formats a path for AeTrayMenu.
Parameters
string $path The path to format.
Returns
string The formatted path.
Definition at line 134 of file class.root.php.
    {
        $path = str_replace($this->getRootPath(), '', $path);
        return '%AeTrayMenuPath%' . substr($path, 1, strlen($path));
    }
References $path, and getRootPath().
Referenced by getCorePath(), and getRootPath().
debugStringBacktrace()
static Root::debugStringBacktrace () static private
Generates a debug backtrace string.
Returns
string The debug backtrace.
Definition at line 584 of file class.root.php.
    {
        ob_start();
        debug_print_backtrace();
        $trace = ob_get_contents();
        ob_end_clean();
        $trace = preg_replace('/^#0\s+Root::debugStringBacktrace[^\n]*\n/', '', $trace, 1);
        $trace = preg_replace('/^#1\s+isRoot->errorHandler[^\n]*\n/', '', $trace, 1);
        $trace = preg_replace_callback('/^#(\d+)/m', 'debugStringPregReplace', $trace);
        return $trace;
    }
Referenced by errorHandler().
errorHandler()
Root::errorHandler ($errno, $errstr, $errfile, $errline)
Handles errors and logs them to the error log file.
Parameters
int $errno The level of the error raised.
string $errstr The error message.
string $errfile The filename that the error was raised in.
int $errline The line number the error was raised at.
Definition at line 540 of file class.root.php.
    {
        if (error_reporting() === 0) {
            return;
        }
        $errfile = Util::formatUnixPath($errfile);
        $errfile = str_replace($this->getRootPath(), '', $errfile);
        if (!defined('E_DEPRECATED')) {
            define('E_DEPRECATED', 8192);
        }
        $errNames = array(
            E_ERROR             => 'E_ERROR',
            E_WARNING           => 'E_WARNING',
            E_PARSE             => 'E_PARSE',
            E_NOTICE            => 'E_NOTICE',
            E_CORE_ERROR        => 'E_CORE_ERROR',
            E_CORE_WARNING      => 'E_CORE_WARNING',
            E_COMPILE_ERROR     => 'E_COMPILE_ERROR',
            E_COMPILE_WARNING   => 'E_COMPILE_WARNING',
            E_USER_ERROR        => 'E_USER_ERROR',
            E_USER_WARNING      => 'E_USER_WARNING',
            E_USER_NOTICE       => 'E_USER_NOTICE',
            E_STRICT            => 'E_STRICT',
            E_RECOVERABLE_ERROR => 'E_RECOVERABLE_ERROR',
            E_DEPRECATED        => 'E_DEPRECATED',
        );
        $content = '[' . date('Y-m-d H:i:s', time()) . '] ';
        $content .= $errNames[$errno] . ' ';
        $content .= $errstr . ' in ' .  $errfile;
        $content .= ' on line ' . $errline . PHP_EOL;
        $content .= self::debugStringBacktrace() . PHP_EOL;
        file_put_contents($this->getErrorLogFilePath(), $content, FILE_APPEND);
    }
References debugStringBacktrace(), E_USER_ERROR, Util\formatUnixPath(), getErrorLogFilePath(), and getRootPath().
getAliasPath()
Root::getAliasPath ($aetrayPath = false)
Gets the path to the alias directory.
Parameters
bool $aetrayPath Whether to format the path for AeTrayMenu.
Returns
string The alias path.
Definition at line 146 of file class.root.php.
    {
        return $this->getRootPath($aetrayPath) . '/alias';
    }
References getRootPath().
getAppsPath()
Root::getAppsPath ($aetrayPath = false)
Gets the path to the apps directory.
Parameters
bool $aetrayPath Whether to format the path for AeTrayMenu.
Returns
string The apps path.
Definition at line 157 of file class.root.php.
    {
        return $this->getRootPath($aetrayPath) . '/apps';
    }
References getRootPath().
getBatchLogFilePath()
Root::getBatchLogFilePath ($aetrayPath = false)
Gets the path to the batch log file.
Parameters
bool $aetrayPath Whether to format the path for AeTrayMenu.
Returns
string The batch log file path.
Definition at line 366 of file class.root.php.
    {
        return $this->getLogsPath($aetrayPath) . '/bearsampp-batch.log';
    }
References getLogsPath().
getBinPath()
Root::getBinPath ($aetrayPath = false)
Gets the path to the bin directory.
Parameters
bool $aetrayPath Whether to format the path for AeTrayMenu.
Returns
string The bin path.
Definition at line 168 of file class.root.php.
    {
        return $this->getRootPath($aetrayPath) . '/bin';
    }
References getRootPath().
getConfigFilePath()
Root::getConfigFilePath ($aetrayPath = false)
Gets the path to the configuration file.
Parameters
bool $aetrayPath Whether to format the path for AeTrayMenu.
Returns
string The configuration file path.
Definition at line 267 of file class.root.php.
    {
        return $this->getRootPath($aetrayPath) . '/bearsampp.conf';
    }
References getRootPath().
getCorePath()
Root::getCorePath ($aetrayPath = false)
Gets the path to the core directory.
Parameters
bool $aetrayPath Whether to format the path for AeTrayMenu.
Returns
string The core path.
Definition at line 179 of file class.root.php.
    {
        return $aetrayPath ? $this->aetrayPath($this->path) : $this->path;
    }
References $path, and aetrayPath().
Referenced by register().
getErrorLogFilePath()
Root::getErrorLogFilePath ($aetrayPath = false)
Gets the path to the error log file.
Parameters
bool $aetrayPath Whether to format the path for AeTrayMenu.
Returns
string The error log file path.
Definition at line 311 of file class.root.php.
    {
        return $this->getLogsPath($aetrayPath) . '/bearsampp-error.log';
    }
References getLogsPath().
Referenced by errorHandler(), and initErrorHandling().
getExeFilePath()
Root::getExeFilePath ($aetrayPath = false)
Gets the path to the executable file.
Parameters
bool $aetrayPath Whether to format the path for AeTrayMenu.
Returns
string The executable file path.
Definition at line 256 of file class.root.php.
    {
        return $this->getRootPath($aetrayPath) . '/bearsampp.exe';
    }
References getRootPath().
getHomepageFilePath()
Root::getHomepageFilePath ($aetrayPath = false)
Gets the path to the homepage file.
Parameters
bool $aetrayPath Whether to format the path for AeTrayMenu.
Returns
string The homepage file path.
Definition at line 410 of file class.root.php.
    {
        return $this->getWwwPath($aetrayPath) . '/index.php';
    }
References getWwwPath().
getHomepageLogFilePath()
Root::getHomepageLogFilePath ($aetrayPath = false)
Gets the path to the homepage log file.
Parameters
bool $aetrayPath Whether to format the path for AeTrayMenu.
Returns
string The homepage log file path.
Definition at line 322 of file class.root.php.
    {
        return $this->getLogsPath($aetrayPath) . '/bearsampp-homepage.log';
    }
References getLogsPath().
getIniFilePath()
Root::getIniFilePath ($aetrayPath = false)
Gets the path to the INI file.
Parameters
bool $aetrayPath Whether to format the path for AeTrayMenu.
Returns
string The INI file path.
Definition at line 278 of file class.root.php.
    {
        return $this->getRootPath($aetrayPath) . '/bearsampp.ini';
    }
References getRootPath().
getLocalUrl()
Root::getLocalUrl ($request = null)
Constructs a local URL with the specified request.
Parameters
string | null $request The specific request to append to the URL.
Returns
string The constructed local URL.
Definition at line 431 of file class.root.php.
    {
        global $bearsamppBins;
        return (isset($_SERVER['HTTPS']) ? 'https://' : 'http://') .
            (isset($_SERVER['SERVER_NAME']) ? $_SERVER['SERVER_NAME'] : 'localhost') .
            ($bearsamppBins->getApache()->getPort() != 80 && !isset($_SERVER['HTTPS']) ? ':' . $bearsamppBins->getApache()->getPort() : '') .
            (!empty($request) ? '/' . $request : '');
    }
References $bearsamppBins.
getLogFilePath()
Root::getLogFilePath ($aetrayPath = false)
Gets the path to the log file.
Parameters
bool $aetrayPath Whether to format the path for AeTrayMenu.
Returns
string The log file path.
Definition at line 300 of file class.root.php.
    {
        return $this->getLogsPath($aetrayPath) . '/bearsampp.log';
    }
References getLogsPath().
getLogsPath()
Root::getLogsPath ($aetrayPath = false)
Gets the path to the logs directory.
Parameters
bool $aetrayPath Whether to format the path for AeTrayMenu.
Returns
string The logs path.
Definition at line 190 of file class.root.php.
    {
        return $this->getRootPath($aetrayPath) . '/logs';
    }
References getRootPath().
Referenced by getBatchLogFilePath(), getErrorLogFilePath(), getHomepageLogFilePath(), getLogFilePath(), getNssmLogFilePath(), getRegistryLogFilePath(), getServicesLogFilePath(), getStartupLogFilePath(), getVbsLogFilePath(), and getWinbinderLogFilePath().
getNssmLogFilePath()
Root::getNssmLogFilePath ($aetrayPath = false)
Gets the path to the NSSM log file.
Parameters
bool $aetrayPath Whether to format the path for AeTrayMenu.
Returns
string The NSSM log file path.
Definition at line 399 of file class.root.php.
    {
        return $this->getLogsPath($aetrayPath) . '/bearsampp-nssm.log';
    }
References getLogsPath().
getProcessName()
Root::getProcessName ()
Gets the name of the process.
Returns
string The process name.
Definition at line 420 of file class.root.php.
    {
        return 'bearsampp';
    }
getProcs()
Root::getProcs ()
Retrieves the list of processes.
Returns
array The list of processes.
Definition at line 101 of file class.root.php.
    {
        return $this->procs;
    }
References $procs.
getRegistryLogFilePath()
Root::getRegistryLogFilePath ($aetrayPath = false)
Gets the path to the registry log file.
Parameters
bool $aetrayPath Whether to format the path for AeTrayMenu.
Returns
string The registry log file path.
Definition at line 344 of file class.root.php.
    {
        return $this->getLogsPath($aetrayPath) . '/bearsampp-registry.log';
    }
References getLogsPath().
getRootPath()
Root::getRootPath ($aetrayPath = false)
Gets the root path, optionally formatted for AeTrayMenu.
Parameters
bool $aetrayPath Whether to format the path for AeTrayMenu.
Returns
string The root path.
Definition at line 122 of file class.root.php.
    {
        $path = dirname($this->path);
        return $aetrayPath ? $this->aetrayPath($path) : $path;
    }
References $path, and aetrayPath().
Referenced by aetrayPath(), errorHandler(), getAliasPath(), getAppsPath(), getBinPath(), getConfigFilePath(), getExeFilePath(), getIniFilePath(), getLogsPath(), getSslPath(), getTmpPath(), getToolsPath(), getVhostsPath(), and getWwwPath().
getServicesLogFilePath()
Root::getServicesLogFilePath ($aetrayPath = false)
Gets the path to the services log file.
Parameters
bool $aetrayPath Whether to format the path for AeTrayMenu.
Returns
string The services log file path.
Definition at line 333 of file class.root.php.
    {
        return $this->getLogsPath($aetrayPath) . '/bearsampp-services.log';
    }
References getLogsPath().
getSslConfPath()
Root::getSslConfPath ($aetrayPath = false)
Gets the path to the SSL configuration file.
Parameters
bool $aetrayPath Whether to format the path for AeTrayMenu.
Returns
string The SSL configuration file path.
Definition at line 289 of file class.root.php.
    {
        return $this->getSslPath($aetrayPath) . '/openssl.cnf';
    }
References getSslPath().
getSslPath()
Root::getSslPath ($aetrayPath = false)
Gets the path to the SSL directory.
Parameters
bool $aetrayPath Whether to format the path for AeTrayMenu.
Returns
string The SSL path.
Definition at line 201 of file class.root.php.
    {
        return $this->getRootPath($aetrayPath) . '/ssl';
    }
References getRootPath().
Referenced by getSslConfPath().
getStartupLogFilePath()
Root::getStartupLogFilePath ($aetrayPath = false)
Gets the path to the startup log file.
Parameters
bool $aetrayPath Whether to format the path for AeTrayMenu.
Returns
string The startup log file path.
Definition at line 355 of file class.root.php.
    {
        return $this->getLogsPath($aetrayPath) . '/bearsampp-startup.log';
    }
References getLogsPath().
getTmpPath()
Root::getTmpPath ($aetrayPath = false)
Gets the path to the temporary directory.
Parameters
bool $aetrayPath Whether to format the path for AeTrayMenu.
Returns
string The temporary path.
Definition at line 212 of file class.root.php.
    {
        return $this->getRootPath($aetrayPath) . '/tmp';
    }
References getRootPath().
getToolsPath()
Root::getToolsPath ($aetrayPath = false)
Gets the path to the tools directory.
Parameters
bool $aetrayPath Whether to format the path for AeTrayMenu.
Returns
string The tools path.
Definition at line 223 of file class.root.php.
    {
        return $this->getRootPath($aetrayPath) . '/tools';
    }
References getRootPath().
getVbsLogFilePath()
Root::getVbsLogFilePath ($aetrayPath = false)
Gets the path to the VBS log file.
Parameters
bool $aetrayPath Whether to format the path for AeTrayMenu.
Returns
string The VBS log file path.
Definition at line 377 of file class.root.php.
    {
        return $this->getLogsPath($aetrayPath) . '/bearsampp-vbs.log';
    }
References getLogsPath().
getVhostsPath()
Root::getVhostsPath ($aetrayPath = false)
Gets the path to the virtual hosts directory.
Parameters
bool $aetrayPath Whether to format the path for AeTrayMenu.
Returns
string The virtual hosts path.
Definition at line 234 of file class.root.php.
    {
        return $this->getRootPath($aetrayPath) . '/vhosts';
    }
References getRootPath().
getWinbinderLogFilePath()
Root::getWinbinderLogFilePath ($aetrayPath = false)
Gets the path to the Winbinder log file.
Parameters
bool $aetrayPath Whether to format the path for AeTrayMenu.
Returns
string The Winbinder log file path.
Definition at line 388 of file class.root.php.
    {
        return $this->getLogsPath($aetrayPath) . '/bearsampp-winbinder.log';
    }
References getLogsPath().
getWwwPath()
Root::getWwwPath ($aetrayPath = false)
Gets the path to the WWW directory.
Parameters
bool $aetrayPath Whether to format the path for AeTrayMenu.
Returns
string The WWW path.
Definition at line 245 of file class.root.php.
    {
        return $this->getRootPath($aetrayPath) . '/www';
    }
References getRootPath().
Referenced by getHomepageFilePath().
initErrorHandling()
Root::initErrorHandling ()
Initializes error handling settings for the application.
Definition at line 77 of file class.root.php.
    {
        error_reporting(-1);
        ini_set('error_log', $this->getErrorLogFilePath());
        ini_set('display_errors', '1');
        set_error_handler(array($this, self::ERROR_HANDLER));
    }
References getErrorLogFilePath().
Referenced by register().
isRoot()
Root::isRoot ()
Checks if the current script is executed from the root path.
Returns
bool True if executed from the root, false otherwise.
Definition at line 111 of file class.root.php.
    {
        return $this->isRoot;
    }
References $isRoot.
Referenced by __construct(), and register().
loadApps()
static Root::loadApps () static
Loads the apps components of the application.
Definition at line 497 of file class.root.php.
    {
        global $bearsamppApps;
        $bearsamppApps = new Apps();
    }
Referenced by register().
loadBins()
static Root::loadBins () static
Loads the binary components of the application.
Definition at line 479 of file class.root.php.
    {
        global $bearsamppBins;
        $bearsamppBins = new Bins();
    }
References $bearsamppBins.
Referenced by register().
loadConfig()
static Root::loadConfig () static
Loads the configuration settings of the application.
Definition at line 452 of file class.root.php.
    {
        global $bearsamppConfig;
        $bearsamppConfig = new Config();
    }
References $bearsamppConfig.
Referenced by ActionSwitchVersion\processWindow(), and register().
loadCore()
static Root::loadCore () static
Loads the core components of the application.
Definition at line 443 of file class.root.php.
    {
        global $bearsamppCore;
        $bearsamppCore = new Core();
    }
References $bearsamppCore.
Referenced by register().
loadHomepage()
static Root::loadHomepage () static
Loads the homepage settings of the application.
Definition at line 526 of file class.root.php.
    {
        global $bearsamppHomepage;
        $bearsamppHomepage = new Homepage();
    }
References $bearsamppHomepage.
Referenced by register().
loadLang()
static Root::loadLang () static
Loads the language settings of the application.
Definition at line 461 of file class.root.php.
    {
        global $bearsamppLang;
        $bearsamppLang = new LangProc();
    }
References $bearsamppLang.
Referenced by register().
loadOpenSsl()
static Root::loadOpenSsl () static
Loads the OpenSSL settings of the application.
Definition at line 470 of file class.root.php.
    {
        global $bearsamppOpenSsl;
        $bearsamppOpenSsl = new OpenSsl();
    }
Referenced by register().
loadRegistry()
static Root::loadRegistry () static
Loads the registry settings of the application.
Definition at line 517 of file class.root.php.
    {
        global $bearsamppRegistry;
        $bearsamppRegistry = new Registry();
    }
Referenced by register().
loadTools()
static Root::loadTools () static
Loads the tools components of the application.
Definition at line 488 of file class.root.php.
    {
        global $bearsamppTools;
        $bearsamppTools = new Tools();
    }
Referenced by register().
loadWinbinder()
static Root::loadWinbinder () static
Loads the Winbinder extension if available.
Definition at line 506 of file class.root.php.
    {
        global $bearsamppWinbinder;
        if (extension_loaded('winbinder')) {
            $bearsamppWinbinder = new WinBinder();
        }
    }
Referenced by register().
register()
Root::register ()
Registers the application components and initializes error handling.
Definition at line 38 of file class.root.php.
    {
        // Params
        set_time_limit(0);
        clearstatcache();
        // Error log
        $this->initErrorHandling();
        // External classes
        require_once $this->getCorePath() . '/classes/class.util.php';
        Util::logSeparator();
        // Autoloader
        require_once $this->getCorePath() . '/classes/class.autoloader.php';
        $bearsamppAutoloader = new Autoloader();
        $bearsamppAutoloader->register();
        // Load
        self::loadCore();
        self::loadConfig();
        self::loadLang();
        self::loadOpenSsl();
        self::loadBins();
        self::loadTools();
        self::loadApps();
        self::loadWinbinder();
        self::loadRegistry();
        self::loadHomepage();
        // Init
        if ($this->isRoot) {
            $this->procs = Win32Ps::getListProcs();
        }
    }
References getCorePath(), Win32Ps\getListProcs(), initErrorHandling(), isRoot(), loadApps(), loadBins(), loadConfig(), loadCore(), loadHomepage(), loadLang(), loadOpenSsl(), loadRegistry(), loadTools(), loadWinbinder(), and Util\logSeparator().
removeErrorHandling()
Root::removeErrorHandling ()
Removes the custom error handling, reverting to the default PHP error handling.
Definition at line 88 of file class.root.php.
    {
        error_reporting(0);
        ini_set('error_log', null);
        ini_set('display_errors', '0');
        restore_error_handler();
    }
Field Documentation
$isRoot
Root::$isRoot private
Definition at line 22 of file class.root.php.
Referenced by isRoot().
$path
Root::$path
Definition at line 20 of file class.root.php.
Referenced by aetrayPath(), getCorePath(), and getRootPath().
$procs
Root::$procs private
Definition at line 21 of file class.root.php.
Referenced by getProcs().
ERROR_HANDLER
const Root::ERROR_HANDLER = 'errorHandler'
Definition at line 18 of file class.root.php.
The documentation for this class was generated from the following file:
E:/Bearsampp-development/sandbox/core/classes/class.root.php