Bearsampp: E:/Bearsampp-development/sandbox/core/resources/homepage/ajax.php File Reference
ajax.php File Reference
Variables
$proc = Util::cleanPostVar('proc', 'text')
$procs
if(in_array($proc, $procs)) else
Variable Documentation
$proc
$proc = Util::cleanPostVar('proc', 'text')
Definition at line 43 of file ajax.php.
Referenced by ActionExt\__construct(), Win32Ps\findByPath(), Win32Ps\findByPid(), Win32Ps\killBins(), ActionStartup\killOldInstances(), and ActionStartup\processWindow().
$procs
$procs
Initial value:
= array(
    'summary',
    'latestversion',
    'apache',
    'filezilla',
    'mailhog',
    'mailpit',
    'memcached',
    'mariadb',
    'mysql',
    'nodejs',
    'php',
    'postgresql',
    'xlight',
    'quickpick'
)
Include the root configuration file. This file is expected to set up the environment and include necessary configurations.
An array of valid process names that can be included.
Definition at line 19 of file ajax.php.
Referenced by Win32Ps\findByPath(), Win32Ps\findByPid(), and Win32Ps\killBins().
else
if (in_array($proc, $procs)) else
Initial value:
{
    echo json_encode(['error' => 'Invalid proc parameter'])
Check if the cleaned 'proc' parameter is in the list of valid processes. If valid, include the corresponding AJAX handler file. If not valid, return a JSON error message.
Definition at line 58 of file ajax.php.