Bearsampp: TplAppExit Class Reference
TplAppExit Class Reference
Static Public Member Functions
static getActionExit ()
static process ()
Data Fields
const ACTION = 'exit'
Detailed Description
Definition at line 3 of file class.tpl.app.exit.php.
Member Function Documentation
getActionExit()
static getActionExit () static
Definition at line 18 of file class.tpl.app.exit.php.
    {
        return TplApp::getActionRun(Action::QUIT) . PHP_EOL . 'Action: exit';
    }
References TplApp\getActionRun(), and Action\QUIT.
process()
static process () static
Definition at line 7 of file class.tpl.app.exit.php.
    {
        global $bearsamppLang;
        return TplApp::getActionMulti(
            self::ACTION, null,
            array($bearsamppLang->getValue(Lang::QUIT), TplAestan::GLYPH_EXIT),
            false, get_called_class()
        );
    }
References $bearsamppLang, TplApp\getActionMulti(), TplAestan\GLYPH_EXIT, and Lang\QUIT.
Referenced by TplApp\getSectionMenuRight().
Field Documentation
ACTION
const ACTION = 'exit'
Definition at line 5 of file class.tpl.app.exit.php.
The documentation for this class was generated from the following file:
E:/Bearsampp-development/sandbox/core/classes/tpls/app/class.tpl.app.exit.php