Bearsampp: E:/Bearsampp-development/sandbox/core/resources/homepage/ajax/ajax.summary.php File Reference
ajax.summary.php File Reference
Variables
$apacheLabel = 'bg-secondary'
$apachePort = $bearsamppBins->getApache()->getPort()
$apacheSslPort = $bearsamppBins->getApache()->getSslPort()
global $bearsamppBins
$dlMoreTpl = '<a href="' . Util::getWebsiteUrl('module/%s', '#releases') . '" target="_blank" title="' . $downloadTitle . '"><span class="float-end" style="margin-left:.5rem;"><i class="fa-solid fa-cloud-arrow-down"></i></span></a>'
global $downloadTitle
$filezillaLabel = 'bg-secondary'
$filezillaPort = $bearsamppBins->getFilezilla()->getPort()
$filezillaSslPort = $bearsamppBins->getFilezilla()->getSslPort()
$mailhogLabel = 'bg-secondary'
$mailhogPort = $bearsamppBins->getMailhog()->getSmtpPort()
$mariadbLabel = 'bg-secondary'
$mariadbPort = $bearsamppBins->getMariadb()->getPort()
$memcachedLabel = 'bg-secondary'
$memcachedPort = $bearsamppBins->getMemcached()->getPort()
$mysqlLabel = 'bg-secondary'
$mysqlPort = $bearsamppBins->getMysql()->getPort()
$nodejsLabel = 'bg-secondary'
$phpLabel = 'bg-secondary'
$postgresqlLabel = 'bg-secondary'
$postgresqlPort = $bearsamppBins->getPostgresql()->getPort()
$result
if($bearsamppBins->getApache() ->isEnable()) $result ['binapache'] = sprintf($dlMoreTpl, 'apache')
$result ['binapache'] = '<span class = " float-end badge ' . $apacheLabel . '">' . $bearsamppBins->getApache()->getVersion() . '</span>'
if($bearsamppBins->getFilezilla() ->isEnable()) $result ['binfilezilla'] = sprintf($dlMoreTpl, 'filezilla')
$result ['binfilezilla'] = '<span class = " float-end badge ' . $filezillaLabel . '">' . $bearsamppBins->getFilezilla()->getVersion() . '</span>'
if($bearsamppBins->getMailhog() ->isEnable()) $result ['binmailhog'] = sprintf($dlMoreTpl, 'mailhog')
$result ['binmailhog'] = '<span class = " float-end badge ' . $mailhogLabel . '">' . $bearsamppBins->getMailhog()->getVersion() . '</span>'
if($bearsamppBins->getMariadb() ->isEnable()) $result ['binmariadb'] = sprintf($dlMoreTpl, 'mariadb')
$result ['binmariadb'] = '<span class = " float-end badge ' . $mariadbLabel . '">' . $bearsamppBins->getMariadb()->getVersion() . '</span>'
if($bearsamppBins->getMemcached() ->isEnable()) $result ['binmemcached'] = sprintf($dlMoreTpl, 'memcached')
$result ['binmemcached'] = '<span class = " float-end badge ' . $memcachedLabel . '">' . $bearsamppBins->getMemcached()->getVersion() . '</span>'
if($bearsamppBins->getMysql() ->isEnable()) $result ['binmysql'] = sprintf($dlMoreTpl, 'mysql')
$result ['binmysql'] = '<span class = " float-end badge ' . $mysqlLabel . '">' . $bearsamppBins->getMysql()->getVersion() . '</span>'
if($bearsamppBins->getNodejs() ->isEnable()) $result ['binnodejs'] = sprintf($dlMoreTpl, 'nodejs')
$result ['binnodejs'] = '<span class = " float-end badge ' . $nodejsLabel .'">' . $bearsamppBins->getNodejs()->getVersion() . '</span>'
if($bearsamppBins->getPhp() ->isEnable()) $result ['binphp'] = sprintf($dlMoreTpl, 'php')
$result ['binphp'] = '<span class = " float-end badge ' . $phpLabel .'">' . $bearsamppBins->getPhp()->getVersion() . '</span>'
if($bearsamppBins->getPostgresql() ->isEnable()) $result ['binpostgresql'] = sprintf($dlMoreTpl, 'postgresql')
$result ['binpostgresql'] = '<span class = " float-end badge ' . $postgresqlLabel . '">' . $bearsamppBins->getPostgresql()->getVersion() . '</span>'
Variable Documentation
$apacheLabel
$apacheLabel = 'bg-secondary'
Definition at line 31 of file ajax.summary.php.
$apachePort
$apachePort = $bearsamppBins->getApache()->getPort()
Definition at line 29 of file ajax.summary.php.
$apacheSslPort
$apacheSslPort = $bearsamppBins->getApache()->getSslPort()
Definition at line 30 of file ajax.summary.php.
$bearsamppBins
global $bearsamppBins
Definition at line 13 of file ajax.summary.php.
$dlMoreTpl
$dlMoreTpl = '<a href="' . Util::getWebsiteUrl('module/%s', '#releases') . '" target="_blank" title="' . $downloadTitle . '"><span class="float-end" style="margin-left:.5rem;"><i class="fa-solid fa-cloud-arrow-down"></i></span></a>'
Definition at line 26 of file ajax.summary.php.
$downloadTitle
global $downloadTitle
Generates a JSON output containing information about various bins such as Apache, Filezilla, MailHog, MariaDB, MySQL, PostgreSQL, Memcached, Node.js, and PHP. The output includes download links, version numbers, and status labels for each bin.
Definition at line 13 of file ajax.summary.php.
Referenced by TplAppNodejs\getMenuNodejs().
$filezillaLabel
$filezillaLabel = 'bg-secondary'
Definition at line 52 of file ajax.summary.php.
$filezillaPort
$filezillaPort = $bearsamppBins->getFilezilla()->getPort()
Definition at line 50 of file ajax.summary.php.
$filezillaSslPort
$filezillaSslPort = $bearsamppBins->getFilezilla()->getSslPort()
Definition at line 51 of file ajax.summary.php.
$mailhogLabel
$mailhogLabel = 'bg-secondary'
Definition at line 70 of file ajax.summary.php.
$mailhogPort
$mailhogPort = $bearsamppBins->getMailhog()->getSmtpPort()
Definition at line 69 of file ajax.summary.php.
$mariadbLabel
$mariadbLabel = 'bg-secondary'
Definition at line 84 of file ajax.summary.php.
$mariadbPort
$mariadbPort = $bearsamppBins->getMariadb()->getPort()
Definition at line 83 of file ajax.summary.php.
Referenced by AppAdminer\updateConfig(), and AppPhpmyadmin\updateConfig().
$memcachedLabel
$memcachedLabel = 'bg-secondary'
Definition at line 126 of file ajax.summary.php.
$memcachedPort
$memcachedPort = $bearsamppBins->getMemcached()->getPort()
Definition at line 125 of file ajax.summary.php.
$mysqlLabel
$mysqlLabel = 'bg-secondary'
Definition at line 98 of file ajax.summary.php.
$mysqlPort
$mysqlPort = $bearsamppBins->getMysql()->getPort()
Definition at line 97 of file ajax.summary.php.
$nodejsLabel
$nodejsLabel = 'bg-secondary'
Definition at line 140 of file ajax.summary.php.
$phpLabel
$phpLabel = 'bg-secondary'
Definition at line 149 of file ajax.summary.php.
$postgresqlLabel
$postgresqlLabel = 'bg-secondary'
Definition at line 112 of file ajax.summary.php.
$postgresqlPort
$postgresqlPort = $bearsamppBins->getPostgresql()->getPort()
Definition at line 111 of file ajax.summary.php.
Referenced by AppAdminer\updateConfig().
$result [1/19]
$result
Initial value:
= array(
    'binapache' => '',
    'binfilezilla' => '',
    'binmailhog' => '',
    'binmariadb' => '',
    'binmysql' => '',
    'binpostgresql' => '',
    'binmemcached' => '',
    'binnodejs' => '',
    'binphp' => '',
)
Definition at line 14 of file ajax.summary.php.
$result [2/19]
if ($bearsamppBins->getApache() ->isEnable()) $result[ 'binapache'] = sprintf($dlMoreTpl, 'apache')
Definition at line 46 of file ajax.summary.php.
$result [3/19]
$result[ 'binapache'] = '<span class = " float-end badge ' . $apacheLabel . '">' . $bearsamppBins->getApache()->getVersion() . '</span>'
Definition at line 47 of file ajax.summary.php.
$result [4/19]
if ($bearsamppBins->getFilezilla() ->isEnable()) $result[ 'binfilezilla'] = sprintf($dlMoreTpl, 'filezilla')
Definition at line 65 of file ajax.summary.php.
$result [5/19]
$result[ 'binfilezilla'] = '<span class = " float-end badge ' . $filezillaLabel . '">' . $bearsamppBins->getFilezilla()->getVersion() . '</span>'
Definition at line 66 of file ajax.summary.php.
$result [6/19]
if ($bearsamppBins->getMailhog() ->isEnable()) $result[ 'binmailhog'] = sprintf($dlMoreTpl, 'mailhog')
Definition at line 79 of file ajax.summary.php.
$result [7/19]
$result[ 'binmailhog'] = '<span class = " float-end badge ' . $mailhogLabel . '">' . $bearsamppBins->getMailhog()->getVersion() . '</span>'
Definition at line 80 of file ajax.summary.php.
$result [8/19]
if ($bearsamppBins->getMariadb() ->isEnable()) $result[ 'binmariadb'] = sprintf($dlMoreTpl, 'mariadb')
Definition at line 93 of file ajax.summary.php.
$result [9/19]
$result[ 'binmariadb'] = '<span class = " float-end badge ' . $mariadbLabel . '">' . $bearsamppBins->getMariadb()->getVersion() . '</span>'
Definition at line 94 of file ajax.summary.php.
$result [10/19]
if ($bearsamppBins->getMemcached() ->isEnable()) $result[ 'binmemcached'] = sprintf($dlMoreTpl, 'memcached')
Definition at line 135 of file ajax.summary.php.
$result [11/19]
$result[ 'binmemcached'] = '<span class = " float-end badge ' . $memcachedLabel . '">' . $bearsamppBins->getMemcached()->getVersion() . '</span>'
Definition at line 136 of file ajax.summary.php.
$result [12/19]
if ($bearsamppBins->getMysql() ->isEnable()) $result[ 'binmysql'] = sprintf($dlMoreTpl, 'mysql')
Definition at line 107 of file ajax.summary.php.
$result [13/19]
$result[ 'binmysql'] = '<span class = " float-end badge ' . $mysqlLabel . '">' . $bearsamppBins->getMysql()->getVersion() . '</span>'
Definition at line 108 of file ajax.summary.php.
$result [14/19]
if ($bearsamppBins->getNodejs() ->isEnable()) $result[ 'binnodejs'] = sprintf($dlMoreTpl, 'nodejs')
Definition at line 145 of file ajax.summary.php.
$result [15/19]
$result[ 'binnodejs'] = '<span class = " float-end badge ' . $nodejsLabel .'">' . $bearsamppBins->getNodejs()->getVersion() . '</span>'
Definition at line 146 of file ajax.summary.php.
$result [16/19]
if ($bearsamppBins->getPhp() ->isEnable()) $result[ 'binphp'] = sprintf($dlMoreTpl, 'php')
Definition at line 154 of file ajax.summary.php.
$result [17/19]
$result[ 'binphp'] = '<span class = " float-end badge ' . $phpLabel .'">' . $bearsamppBins->getPhp()->getVersion() . '</span>'
Definition at line 155 of file ajax.summary.php.
$result [18/19]
if ($bearsamppBins->getPostgresql() ->isEnable()) $result[ 'binpostgresql'] = sprintf($dlMoreTpl, 'postgresql')
Definition at line 121 of file ajax.summary.php.
$result [19/19]
$result[ 'binpostgresql'] = '<span class = " float-end badge ' . $postgresqlLabel . '">' . $bearsamppBins->getPostgresql()->getVersion() . '</span>'
Definition at line 122 of file ajax.summary.php.